### ISSUE TITLE
Tagify can change a tag value to its tagTextProp under mysterious circumstances

### ISSUE THREAD

**Issue by rsimoes** [yairEO/tagify#1001]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://user-images.githubusercontent.com/161220/160033898-ee13c70a-f7f9-46a7-af46-47c8dfd3d869.mp4

### Explanation
```js
        const select = html.querySelector("input[data-tagify-select]");
        if (!select) return;

        new Tagify(select, {
            enforceWhitelist: true,
            mode: "select",
            tagTextProp: "label",
            dropdown: {
                closeOnSelect: true,
                enabled: 1,
                highlightFirst: true,
                mapValueTo: "label",
                maxItems: 9,
                searchKeys: ["label"],
            },
            whitelist: this.choices
                .map((c, index) => ({ value: index.toString(), label: c.label }))
                .sort((a, b) => a.label.localeCompare(b.label, game.i18n.lang)),
        });
```

- **What is the expected behavior?**
`tag[value]` reflects the whitelist `value` after clicking outside the input

- **What is happening instead?**
The value changes to the `tagTextProp`

- **What error message are you getting?**
None

**Comment by rsimoes** [comment]
After a little digging, I noticed the following:

On initial selection, `selectOption` calls `addTags` with the full tag data:
![select-option](https://user-images.githubusercontent.com/161220/160040949-b5edfe94-46ae-47dd-86f1-eb88e9d5c051.png)

On blur, the `onFocusBlur` callback calls `addTags` with merely the text content:
![on-focus-blur](https://user-images.githubusercontent.com/161220/160041120-8d5dfaed-6405-4e7f-be5f-75e9f2aa40b2.png)

**Comment by yairEO** [comment]
It seems from your video that the `selectOption` method had set the value to an `id` and when you clicked outside (*blur* event)
then the value of the tag was changed to the string value. 

Can you provide a [simple demo on jsbin](https://jsbin.com/watedeh/edit?html,js,output)? (clone this one and update)

**Comment by rsimoes** [comment]
Can't connect to the jsbin URL at the moment because of an invalid TLS certificate + HSTS header. I'll try again later.

**Comment by rsimoes** [comment]
Here we go: https://jsbin.com/wisisocoqi/edit?html,js,output

Choose "Option 3": The bug is that the whitelist match is attempted against the items visible in the dropdown only.

**Comment by jeanbaptistevilain** [comment]
Hi,

Thanks for the great work on Tagify. 

I can confirm the behavior described here, as shown in another example : https://jsbin.com/yetoqer/edit?html,js,output
Select "Other value" in the dropdown, then blur the input by clicking anywhere outside. You should see that the input value becomes erroneous (`[{"label":"Other label","value":"Other label"}]` in this case).

If you set the `maxItems` setting to 10 instead of 5, the behavior is back to normal with the expected input value `[{"value":"othervalue","label":"Other label"}]`.

Please let me know if you need further details.

**Comment by yairEO** [comment]
@jeanbaptistevilain - How can I select `"Other value"` if you've set `maxItems: 5` and that option is the 6th?

![image](https://user-images.githubusercontent.com/845031/161821162-66f36940-ea25-4170-9eac-9017b537e3ba.png)


It isn't available to be selected, unless I type it and then select, which in that case, I don't see a bug:

![image](https://user-images.githubusercontent.com/845031/161821225-5f5b041c-ff43-43e7-9520-bea47fd00ae4.png)

**Comment by jeanbaptistevilain** [comment]
Yep sorry, I meant :
- type "other"
- select "Other label" => value is correct : `[{"value":"othervalue","label":"Other label"}]`
- click outside the text field to blur it => value gets updated somehow, and is now erroneous : `[{"label":"Other label","value":"Other label"}]`

Behavior can be reproduced on latest FF / Chrome / Safari.
Hope this helps
