### ISSUE TITLE
setDisabled doesn't completely disable the input

### ISSUE THREAD

**Issue by dmx-patrick** [yairEO/tagify#1002]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js](https://codepen.io/dmx-patrick/pen/QWadevR)

### Explanation

- **What is the expected behavior?**
setDisabled() should completely disable the input.

- **What is happening instead?**
it visually looks disabled, but it still can get focus and you can add new tags to it

- **What error message are you getting?**
no error message

**Comment by yairEO** [comment]
Your demo page is set to use old version of Tagify (`4.2.0`) and not the new one, which this bug does not occur

**Comment by dmx-patrick** [comment]
Also with your link and latest version it is not completely solved. Click on a tag and then in the input, it then allows you to type and add tags in the input while being disabled.

**Comment by yairEO** [comment]
@dmx-patrick - This is a new Chrome bug which is serious and I will report it to Google
