### ISSUE TITLE
Pressing tab twice and adding text, adds garbage as a tag

### ISSUE THREAD

**Issue by melenaos** [yairEO/tagify#1003]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://yaireo.github.io/tagify/

### Explanation

- When we press tab to exit the tagify, the focus is on an element that when you type something becomes garbage tag
![Untitled Project](https://user-images.githubusercontent.com/7249160/160997837-c7772be4-c7d7-4211-91ec-4c6b7d250fb6.gif)

To reproduce this follow the next steps:
- add dummy text,
- press tab key to create the tag
- press tab again
- start typing, you should see some json style object typed in the tag

**Comment by THenkeDE** [comment]
I had this, too. It felt like i was focusing the "real" Input field and so it broke the JSON tagify is inserting there. I (seemed) to have fixed it by setting tabindex="-1" on the input field so it cannot get focus.

**Comment by melenaos** [comment]
That's correct!
Thanks!
