### ISSUE TITLE
Deletion of just added tag by using Backspace is not working also in chrome help!!!!

### ISSUE THREAD

**Issue by johnChuj** [yairEO/tagify#1005]
Deletion of just added tag by using Backspace is not working also in chrome help!!!!

**Comment by johnChuj** [comment]
https://user-images.githubusercontent.com/35988190/161380393-d674149e-5c81-47e4-a211-8e38be728a5a.mp4

**Comment by yairEO** [comment]
This is a complex bug, it will take me some time to get to the bottom of this.. is this urgent?

**Comment by johnChuj** [comment]
Please fix it as soon as possible, now the project is in use, please solve it as soon as possible, thank you very much



发自我的iPhone


------------------ Original ------------------
From: Yair Even Or ***@***.***&gt;
Date: Mon,Apr 4,2022 5:59 AM
To: yairEO/tagify ***@***.***&gt;
Cc: johnChuj ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [yairEO/tagify] Deletion of just added tag by using Backspace isnot working also in chrome help!!!! (Issue #1005)





 
This is a complex bug, it will take me some time to get to the bottom of this.. is this urgent?

**Comment by yairEO** [comment]
As per the issue template, please provide me with a *jsbin* of a minimal reproducible code 

Please also write me the steps-to-reproduce as I don't understand the connection between the title of this issue and the video you've attached, and I did some check and I was able to delete all the tags I was adding (in `mix-mode`).

Are you sure you meant "Backspace" key and not the "Delete" key?

**Comment by johnChuj** [comment]
yes it is Backspace.
&nbsp;I'm glad you can reply to me about not deleting. I found that if readonly: true is set, it cannot be deleted. I can not set this attribute, for example, this tagify. addTags([{value:"banana","readonly" : true,color:"yellow",id:1}]); In addition, I would like to ask another question, how can I get the array returned in order in the input box, such as&nbsp;


11 [[{"value": "banana37", "color": "yellow", "Id": 1}]] 22 [[{"value": "banana38", "color": "yellow", "ID: 1}]] 33 [[{" value ":" banana39 "," color ":" yellow "," ID: 1}]] 44 [[{"value": "banana40", "color": "yellow", "ID: 1}]]







I want to get data like [11, banana37,22, banana38,33, banana39,44, banana40]? Look forward to your reply, thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yairEO/tagify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 凌晨1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yairEO/tagify] Deletion of just added tag by using Backspace is not working also in chrome help!!!! (Issue #1005)





 
As per the issue template, please provide me with a jsbin of a minimal reproducible code
 
Please also write me the steps-to-reproduce as I don't understand the connection between the title of this issue and the video you've attached, and I did some check and I was able to delete all the tags I was adding (in mix-mode).
 
Are you sure you meant "Backspace" key and not the "Delete" key?

**Comment by yairEO** [comment]
what do you mean *I can not set this attribute*? it's shown in the [demo page](https://yaireo.github.io/tagify/#section-mix) and is working well..

You need to sort your own data... before sending it to the server, or have the server sort it

**Comment by johnChuj** [comment]
&nbsp;my appeal ：





I want to get data like [11, banana37,22, banana38,33, banana39,44, banana40]?&nbsp;There is no corresponding method. I can't find it， Look forward to your reply, thank you


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yairEO/tagify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 凌晨1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yairEO/tagify] Deletion of just added tag by using Backspace is not working also in chrome help!!!! (Issue #1005)





 
As per the issue template, please provide me with a jsbin of a minimal reproducible code
 
Please also write me the steps-to-reproduce as I don't understand the connection between the title of this issue and the video you've attached, and I did some check and I was able to delete all the tags I was adding (in mix-mode).
 
Are you sure you meant "Backspace" key and not the "Delete" key?

**Comment by yairEO** [comment]
sorry, I don't understand...
