### ISSUE TITLE
Placeholder when input is not focused

### ISSUE THREAD

**Issue by Polm90** [yairEO/tagify#1011]
Hi,
I was trying to change this example https://yaireo.github.io/tagify/#outside-of-the-box in order to have the placeholder visible always when the input is not focused (i.e. when you are not typing) even when there is already a tag. But I was unable to achieve this. Can you help me?

Thank you

**Comment by yairEO** [comment]
It's a CSS thing. Just override the `::before` pseudo-element with `opacity: initial` or `1`

https://user-images.githubusercontent.com/845031/164793326-431bc3ff-1315-43dd-b292-bcb925f34b71.mp4
