### ISSUE TITLE
Custom dropdown rendering that looks like default SELECT OPTGROUPs

### ISSUE THREAD

**Issue by wurst-hans** [yairEO/tagify#1012]
Hello,

I'm experimenting with templates a bit, but still found no solution to group items like `optgroup`, that is used in a default `select` element (see [here](https://developer.mozilla.org/en/docs/Web/HTML/Element/optgroup)). Is there any template already that be used for that?

BR

**Comment by wurst-hans** [comment]
My approach is now:

1) add property `data-group` containing group name to each list item (the list is pre-sorted by group name and item value alphabetically)
2) use a custom `dropdownItem` template
3) added CSS for pseudo elements showing group name

Custom template:

```
function (item, tagify) {
    var showCategory = false;
    if (item['data-group'] !== tagify.last_group) {
        tagify.last_group= item['data-group'];
        showCategory = true;
    }
    return `<div ${this.getAttributes(item)}
        class="${this.settings.classNames.dropdownItem} ${item.class ? item.class : ''} ${showCategory ? 'tagify__item__group' : ''}"
        tabindex="0" role="option">${item.value}</div>`;
}
```

I had to inject a custom property `last_group` to Tagify object for keeping track of last printed group name.

CSS that is used:

```
.tagify__item__group {
    position: relative;
    margin-top: 2em;
    padding-left: 1.5em;
}

.tagify__item__group:before {
    content: attr(data-group);
    position: absolute;
    color: #000;
    pointer-events: none;
    top: -1.5rem;
    left: 0.5em;
}

.tagify__item__group ~ .tagify__dropdown__item {
    padding-left: 1.5em;
}
```

**Comment by yairEO** [comment]
Can you please show your design so I would see what you're aiming for?

**Comment by yairEO** [comment]
Something like this?

[jsbin.com/dehaduw/edit?css,js,output](https://jsbin.com/dehaduw/edit?css,js,output)

**Comment by wurst-hans** [comment]
Using my solution from above, it looks like this:

![image](https://user-images.githubusercontent.com/56444979/164883577-90bec7f1-5547-4445-90f6-10e304612e9f.png)

**Comment by yairEO** [comment]
@wurst-hans - this screenshot means you are happy?

**Comment by wurst-hans** [comment]
You're right, sorry for confusing you. I've never expected that such "simple" thing like `<optgroup>` hasn't been realized within Tagify already. I'm still not happy using a dirty injected property into Tagify for keeping track of last printed group name. Additionally I have to reset this value on  `dropdown:hide` event, else there are some issues when dropdown is going to be showed on next focus. My hope was, that someone has implemented such a solution already.
For my purposes, my solution is acceptable. Only the custom property `tagify.last_group` I'm using could be improved, if you've any idea for that.

**Comment by yairEO** [comment]
You want `optgroup` design but another person might want a totally different design, so the best way I came up with now was to re-create the `tagify.dropdown.createListHTML` method however you see fit. 

It is problematic for me, as the author, to come up with a more generic solution because I don't see how would I be able to cover all possibilities (for the users to be able to customize the HTML of the list) in a simpler way.
