### ISSUE TITLE
dropdownFooter shows "Refine your search" when maxItems = 0 (which shows all items)

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#1013]
## Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- **What is the expected behavior?**
- When maxItems = 0 is set, all the available options are displayed. Hence, "Refine your search" should not be there at the end.

- **What is happening instead?**
"Refine your search" is showing in the end.

- **What error message are you getting?**
N/A

For the moment I used the workaround of specifying maxItems = Infinity and it works as expected. It would be better if either the maxItems = 0 is not supported or this issue is fixed.

**Comment by yairEO** [comment]
You are not supposed to write `maxItems: 0` as it makes no sense :)
`Infinite` is more appropriate. It seems to to work the same, but it's logically incorrect. 

The real bug is that you have suggestion dropdown at all, since `maxItems: 0` means nothing should be shown.

**Comment by dirslashls** [comment]
Thanks @yairEO , no problem. Closing this as I can use Infinity for maxItems.

**Comment by nanawel** [comment]
> `Infinite` is more appropriate. It seems to to work the same, but it's logically incorrect.

This remark should be in the documentation IMHO. I made the same mistake thinking that `0` meant "no limit" as it's often the case.
