### ISSUE TITLE
I want react to be able to use Tagrify's Methods such as replaceTag

### ISSUE THREAD

**Issue by rnrnstar2** [yairEO/tagify#1015]
I want to get the key value of tagData from other states of react and change it dynamically.
However, there is no instance of tagrify in the react sample, and commands like tagrify.replaceTag () cannot be used.
I thought about changing it dynamically with transformTag, but it was not possible because it was read only once.
Please tell me the solution.

**Comment by rnrnstar2** [comment]
My sample code is here

`import React, { useEffect, useState, useCallback, useRef, VFC } from 'react';
import { TemplateDataChangeType, WhiteListType } from 'custom-types';

// tagrify
// import Tagify from '@yaireo/tagify'
// import Tags from '@yaireo/tagify/dist/react.tagify';
import { MixedTags } from '@yaireo/tagify/dist/react.tagify';

// Material-ui
import TextField from '@mui/material/TextField';

// SWR
import { fetchGetJSON } from 'utils/api-helpers';
import useSWR from 'swr';

type ChangeFunctionType = (index: number, e: TemplateDataChangeType) => void;
type Props = {
  index: number;
  tenantID: string;
  text: string;
  handleChange: ChangeFunctionType;
};
const TemplateText: VFC<Props> = ({ index, tenantID, text, handleChange }) => {
  // SWR
  const { data: whitelist, error: whitelistError } = useSWR<WhiteListType[]>(
    tenantID ? `/api/appSync/tenantWhiteList/?tenantID=${tenantID}` : null,
    fetchGetJSON,
  );

  // state
  const [score, setScore] = useState<number>(1);

  // ref
  const tagifyRef = useRef();

  useEffect(() => {
    // @ts-ignore
    const value = tagifyRef?.current?.value;
    if (value) {
      for (let index = 0; index < value.length; index++) {
        let tagData = value[index];
        console.log(tagData);
        if (tagData.category === 'Delivery') {
          if (tagData.value === 'date' || tagData.value === 'afterDate') {
            if (tagData.value === 'afterDate') {
              tagData.score = score;
              tagData.name = tagData.name.replace('X', String(tagData.score));
            }
          }
        }
        console.log(tagData);
        // @ts-ignore
        tagifyRef.current.value[index] = tagData;
      }
    }
  }, [score]);

  // タグ変更
  const onChange = useCallback(
    (e) => {
      console.log(e.detail.value);
      if (handleChange)
        handleChange(index, {
          text: e.detail.value,
        });
    },
    [index, handleChange],
  );

  const transformTag = useCallback((tagData: WhiteListType) => {
    console.log(tagData);
    const userStyle = '--tag-bg:#61d836; --tag-hover:#3bba0d';
    const userInfoCategoryStyle = '--tag-bg:#2196f3; --tag-hover:#0a8bf5';
    const deliveryStyle = '--tag-bg:#ffca28; --tag-hover:#f7bb05';
    if (tagData.category === 'User') {
      tagData.style = userStyle;
    } else if (tagData.category === 'UserInfoCategory') {
      tagData.style = userInfoCategoryStyle;
    } else if (tagData.category === 'Delivery') {
      tagData.style = deliveryStyle;
    }
    return tagData;
  }, []);

  const settings = {
    pattern: /\//,
    tagTextProp: 'name',
    duplicates: true,
    enforceWhitelist: true,
    placeholder: '「/」でコマンドを入力する',
    trim: true,
    dropdown: {
      enabled: 1,
      position: 'text',
      highlightFirst: true,
      searchKeys: ['name', 'category'],
    },
    templates: {
      tag: tagTemplate,
      dropdownItem: suggestionItemTemplate,
      dropdownHeader: dropdownHeaderTemplate,
      dropdownFooter: dropdownFooterTemplate,
    },
    transformTag: transformTag,
  };

  if (whitelistError) return <React.Fragment>whitelistError</React.Fragment>;
  return (
    <React.Fragment key={index}>
      <TextField
        label='score'
        type='number'
        value={score}
        fullWidth
        margin='normal'
        placeholder='1'
        onChange={(e) => setScore(Number(e.target.value))}
      />

      <MixedTags
        tagifyRef={tagifyRef}
        autoFocus={true}
        settings={settings}
        whitelist={whitelist}
        loading={whitelist ? false : true}
        className='myTags'
        readOnly={false}
        onChange={onChange}
        value={text}
      />
    </React.Fragment>
  );
};

export default TemplateText;

function suggestionItemTemplate(tagData: WhiteListType) {
  // console.log(tagData);
  return `
  ${
    tagData.type === 'title'
      ? `<div class="suggestion-item-title">
      ${tagData.name}
      </div>`
      : `<div
          ${this.getAttributes(tagData)}
          class='tagify__dropdown__item d-flex align-items-center'
        >
          <div class="d-flex flex-column">
            <span>${tagData.name}</span>
          </div>
        </div>`
  }
  `;
}

function dropdownHeaderTemplate() {
  return `
  <div class="${this.settings.classNames.dropdownHeader}">
          <strong>代入するアイテムを選択してください。</strong>
      </div>
  `;
}

function dropdownFooterTemplate() {
  return `<footer data-selector='tagify-suggestions-footer' class="${this.settings.classNames.dropdownFooter}">
            もっとデータを見る
          </footer>`;
}

function tagTemplate(tagData: WhiteListType) {
  // console.log(tagData);
  if (tagData.type === 'title') return null;
  return `
    <tag title="${tagData.name}
      contenteditable='false'
      spellcheck='false'
      tabIndex="-1"
      class="${this.settings.classNames.tag}"
      ${this.getAttributes(tagData)}
    >
      <x title='' class='tagify__tag__removeBtn' role='button' aria-label='remove tag'></x>
      <div class="d-flex align-items-center">
        <strong>${tagData.name}</strong>
        ${tagData.format ? `<span class='tagify__tag-text'>（${tagData.format}）</span>` : ''}
      </div>
    </tag>
  `;
}
`

**Comment by yairEO** [comment]
Hi @rnrnstar2, The [example page](https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/CrazyTags.jsx:2079-2140) shows:

You can set a `tagifyRef` prop and then you will have access to the *Tagify* instance like `tagifyRef.current.replaceTag(...)`
