### ISSUE TITLE
I want you to add a submenu to the item selection of the whitelist.

### ISSUE THREAD

**Issue by rnrnstar2** [yairEO/tagify#1016]
I want to dynamically change the value of key by selecting a submenu when selecting tagdata.

Specifically, it's time to decide on a date format.
{
date: "2022-04-22",
format: "yyyy / MM / dd"
}

{
date: "2022-04-22",
format: "MM-dd"
}

I am developing an app that converts text created with tagrify on an aws server and sends a message to SNS.
I think that it is necessary to set the date to be sent in the whiteList of tagrify when sending in the "MM-dd" format.
If it is not a submenu, the UI is not ideal, so I would like to ask you to implement a submenu.

<img width="398" alt="スクリーンショット 2022-04-18 13 59 45" src="https://user-images.githubusercontent.com/39724729/163757033-990ebb8c-3639-4b51-ba43-bc127aa3942a.png">

**Comment by yairEO** [comment]
Hi @rnrnstar2, that isn't possible out-of-the-box and is complex to achieve, although not impossible. 

It requires adding custom items (with Tagify templates) and attach hover events and logic which will show/hide the sub-menus... 
The current [positioning method](https://github.com/yairEO/tagify/blob/master/src/parts/dropdown.js#L234) does not support this

**Comment by rnrnstar2** [comment]
I created a sandbox.
I created it like this, but it doesn't take effect when I click it.
How do I write the code and it works?

In the firstLevel menu, select a category and assume a drop menu where various tagdata are displayed in that category.

I'm sorry I'm Japanese and I'm not good at English.

https://codesandbox.io/s/tagify-react-issue-template-forked-xpkv5b?file=/src/index.js

**Comment by yairEO** [comment]
It's OK, I'm also not a native English speaker

Tagify is automatically adding `tagifysuggestionidx` property each dropdown item (which is something you cannot add yourself)

https://github.com/yairEO/tagify/blob/43b7e2033f1810dee45e67fe8e99e6b982afb0bf/src/parts/dropdown.js#L694-L714

![image](https://user-images.githubusercontent.com/845031/163961935-bdb2c39d-c738-45dd-9cdf-56de8a4d150c.png)


I am unsure if this can even work even if the submenu items will have the `tagifysuggestionidx` attribute but I will try. 

It would take me some days, as I'm currently on vacation...

**Comment by rnrnstar2** [comment]
So that's it.
I'm okay if it takes time.
Thank you for your cooperation:)

**Comment by yairEO** [comment]
I would suggest you to modify the `createListHTML` method and use your own:

```js
Tagify.dropdown.createListHTML = optionsArr  => { 
     return extend([], optionsArr).map((suggestion, idx) => { 
         if( typeof suggestion == 'string' || typeof suggestion == 'number' ) 
             suggestion = {value:suggestion} 
  
         var value = this.dropdown.getMappedValue(suggestion) 
  
         suggestion.value = value && typeof value == 'string' 
             ? escapeHTML(value) 
             : value 
  
         var tagHTMLString = this.settings.templates.dropdownItem.apply(this, [suggestion, this]) 
  
         // make sure the sugestion index is present as attribute, to match the data when one is selected 
         tagHTMLString = tagHTMLString 
             .replace(/\s*tagifySuggestionIdx=(["'])(.*?)\1/gmi, '') // remove the "tagifySuggestionIdx" attribute if for some reason it was there 
             .replace('>', ` tagifySuggestionIdx="${idx}">`) // add "tagifySuggestionIdx" 
  
         return tagHTMLString 
     }).join("") 
 } 
 ```
 
 
 Keep in mind that the number of suggestions should not be above the number of items in the `whitelist`, and so the `idx` in the above function **must match** to the index of the `optionsArr` argument, which is basically the filtered version of your `whitelist`.
 
 Then you can simply remove the last part and add it yourself manually in the template (where `tagifySuggestionIdx` is assigned) and do that manually in your template (don't forget to pass `idx` to the template function)
 
 This is a bit complex but not by much. The only problem is to write the `createListHTML` function logic which groups certain items together
