### ISSUE TITLE
keepInvalidTags and duplicated bug

### ISSUE THREAD

**Issue by hihahihahoho** [yairEO/tagify#1017]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
When I remove the valid tag but got duplicated, the remain invalid duplicated tag should be come valid

- **What is happening instead?**
The remain invalid duplicated tag still invalid even though it is an unique tag

**Comment by yairEO** [comment]
Hi! Where is the [jsbin demo](https://jsbin.com/jekuqap/edit?html,js,output) page from the issue template?

**Comment by hihahihahoho** [comment]
Close because the Demo works fine, maybe my scripts gets conflicted
