### ISSUE TITLE
How to track all added/removed tags (including those that have invalid values).

### ISSUE THREAD

**Issue by yury-kozlov** [yairEO/tagify#1020]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo
Try adding some invalid tags, for example with numbers: https://jsbin.com/jidicinada/2/edit?html,js,output

We are wrapping the "tagify" library inside our own code and listen to `add`, `remove` events in order to invoke some business logic related to other UI components. However when we added custom validator (for example to make sure that added tags follow our pattern), we see that invalid tags are not added/removed from the input field. 

Is it possible to track those events even when tags are invalid?

**Comment by yairEO** [comment]
As the [documentation](https://github.com/yairEO/tagify#events) shows:

    tagify.on('add, remove, invalid', console.info)

https://jsbin.com/cuhizuw/edit?js,console,output
