### ISSUE TITLE
Is there a way to change the [{'value':'sdkfl'}] to [{'email':'semaltysourabh@gmail.com'}] while rendering the data

### ISSUE THREAD

**Issue by Sourabh-Semalty** [yairEO/tagify#1024]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page - *clone one of the below:*

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

**Comment by Sourabh-Semalty** [comment]
![image](https://user-images.githubusercontent.com/42134981/166876090-66a8fd60-4522-4361-b842-cd27f9afbe7b.png)
I'm using this textKeyProp but it is giving the me this

**Comment by yairEO** [comment]
Have you read [this](https://github.com/yairEO/tagify#modify-original-input-value-format) or have tried the `transformTag` setting mentioned in the docs?

**Comment by Sourabh-Semalty** [comment]
> Have you read [this](https://github.com/yairEO/tagify#modify-original-input-value-format) or have tried the `transformTag` setting mentioned in the docs?

I haven't seen this one brother but yeah thanks for this

**Comment by Sourabh-Semalty** [comment]
> Have you read [this](https://github.com/yairEO/tagify#modify-original-input-value-format) or have tried the `transformTag` setting mentioned in the docs?

One more thing is there any way to set maxTags dynamically ?

![image](https://user-images.githubusercontent.com/42134981/166917379-22297b55-8466-43f3-8941-9e5145d05106.png)

As i'm unable to set it dynamically

**Comment by yairEO** [comment]
please share how exactly are you setting it dynamically

**Comment by jjxtra** [comment]
transformTag isn't called for me. Odd.

**Comment by yairEO** [comment]
@jjxtra - I can't help without seeing a basic example showcasing the issue... please clone the JSBIN example from the github `issues` template and share here
