### ISSUE TITLE
Toggle whitelist enforcing in mixed mode

### ISSUE THREAD

**Issue by eugene-makarov** [yairEO/tagify#1027]
Hello!

I'm trying to use mixed mode with two types of tags: people and hashtags. The first one has to be enforced and the second can be free-typed. I tried dynamically changing `enforceWhitelist`, but that doesn't seem to work... If that's not possible, is there a better way to achieve the described behavior?

Demo: https://codepen.io/eugene-makarov-the-looper/pen/dydYvGZ
Expected: Type @ and whitelist is enforced, type # and whitelist is not enforced (user can create new tags)

Lots of thanks!

**Comment by yairEO** [comment]
It works very well, only one small change is required by you: `this.tagify.settings.enforceWhitelist`

add `.settings`  before `enforceWhitelist` :)

**Comment by eugene-makarov** [comment]
Thank you so much!
