### ISSUE TITLE
Autocomplete does not appear

### ISSUE THREAD

**Issue by deniswsrosa** [yairEO/tagify#103]
Hi folks,
Is there any way to make the suggestion appear even when there is only a single option?
http://jsfiddle.net/deniswsrosa/xpvt214o/802774/

**Comment by leccyril** [comment]
hi, i have exactly he same problem i want autocompletion even for only one item please how i can do ?

**Comment by yairEO** [comment]
I am sorry for such embarrassing bug, I'm fixing it at this instance

**Comment by yairEO** [comment]
I've made it not to appear and instead simply autocomplete because it seems more logical to go one step further and help the user instead of showing a dropdown for user to do a useless extra step of choosing the single item out of it. 

I think this is better UX.

Do you have any good reasons why would you still want to show the user a single-item dropdown instead of auto-completing (as it is now) ?

**Comment by leccyril** [comment]
because auto completion doe'snt not work for me

**Comment by leccyril** [comment]
@yairEO in fact downloaded yesterday the zip... => unzip, then open index.xtml

autocompletion not working, so we're using dropdown autocompletion instead...

**Comment by yairEO** [comment]
Just pushed a fix for this. I've changed my mind and now a single item in the dropdown is displayed

Version tag : `2.2.10`

**Comment by leccyril** [comment]
thank you very much, just a question... how to use autocompletion ?
 i see now the rest of the word in the input (autocompletion work)

... but i don't know how to choose it... and how the user will intuitivly choose it, for example enter made the word validate but nt with autocompletion, maybe add a paramter like addNew=true or false, like this if ther is autocompletion and we click on the word in input or type enter... it will write the autocompleted word...

**Comment by yairEO** [comment]
You use it by hitting the right arrow key <kbd>right</kbd>

**Comment by leccyril** [comment]
do you think it is inplicit or easy for the user ? it is just a reflexion... as a user i don't type right key -)....

and most of user do i like that.. tried on stackoverflow and it is right they don't do autocompletion directly in input... but with dropdwon with one item it is ok

do you think it will be possible like stackoverflow to show tag description in dropdown in  futur?

**Comment by leccyril** [comment]
thank you very much

**Comment by yairEO** [comment]
@leccyril - sorry for the delay, I missed this one.

The suggested text is there to help a user as they type, and the right-arrow feature which autocompletes the suggested term is a nice-to-have thing. 

If it is important for a developer to let their users know of this feature, they can write it somewhere around the Tagify component.

I have no better idea how to make it work nicer, and if you do, please share with me :)

**Comment by yairEO** [comment]
@gourav-nuzpapr - there's an annoying old bug in Android Chrome which prevents me from knowing if `enter` key is pressed when *contenteditable* has a value in it. all key codes are the same - `229`...

Tagify unfortunately faces a lot of issues with browser bugs since it's a very complex component
