### ISSUE TITLE
[React] Mix-mode: The onRemove method is called before the onChange method

### ISSUE THREAD

**Issue by agrawal-rohit** [yairEO/tagify#1030]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/s/tagify-issue-where-onremove-is-triggered-before-onchange-msyoyp?file=/src/index.js

### Explanation

- **What is the expected behavior?**
When a tag is removed in mix-mode using a backspace, the `onChange` method should be invoked first, and then the `onRemove` handler should be invoked.

- **What is happening instead?**
In the case of the `onAdd` method, whenever a new tag is added, `onAdd` is triggered after the `onChange` method is invoked. However, `onRemove` does not match that behaviour when a tag is removed using a backspace. 

It may seem like a trivial issue, but it's making it really difficult to write undo-redo logic in my application for `onRemove` events. I'd really appreciate it if this change can be done 😇

**Comment by agrawal-rohit** [comment]
@yairEO Can this issue be fixed?

**Comment by yairEO** [comment]
This change might break existing code for others that have relied on existing order... Why don't you just use `onChange` and not `onRemove`?

You can push the value of the Tagify to an array every time `onChange` is called, and use the last item in the array (or one before that) when doing your custom `undo` logic.

Users may also use `CTRL-Z` (or right-click context menu) to undo, why do you need your own custom undo logic?
