### ISSUE TITLE
Changing tab/window auto adds the tag

### ISSUE THREAD

**Issue by Polm90** [yairEO/tagify#1031]
If you are tipying a tag in the input but you do not "add" it, and you change browser tab/window (so you leave the input full), the tag you were tipying is automatically added.

This behaviour can be replicated in the official examples too.

I've tried setting to false the 'addTagOnBlur' but it doesn't change anything.

**Comment by yairEO** [comment]
it is working fine: https://jsbin.com/gukafumuwi/1/edit?html,js,output

Please add a demo page next time as instructed by the issues guidelines you've deleted before writing here...

**Comment by Polm90** [comment]
@yairEO sorry, I thought referring to your demos was enough.
This is the [demo page](https://yaireo.github.io/tagify/) and [this is a video](https://user-images.githubusercontent.com/4883463/168031294-5875c780-957c-42e4-a8b0-c77c617e7114.mp4) showing the issue.

As you can see, when I come back to the page, the tag I was typing has been added

**Comment by Polm90** [comment]
@yairEO here is my example with the issue: https://jsbin.com/vofisuneyi/1/edit?html,js,output

Can you help me?
