### ISSUE TITLE
Editing a tag, allows you to have duplicated tags (case insenstitve)

### ISSUE THREAD

**Issue by Polm90** [yairEO/tagify#1035]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/lunuzuj/1/edit?html,js,output
This is the same example used for [this](https://github.com/yairEO/tagify/issues/1031) UNRESOLVED issue

### Explanation

- **What is the expected behavior?**
Editing tags (using double click) doesn't allow you to have duplicated tags (which are different only for lowercase/uppercase characters) because if you try to manually add the duplicated tag, the library doesn't allow you.

- **What is happening instead?**
You can have 2 tags which are the same

- **Steps:**
1) add a tag (for example 'test')
2) try to add a similar tag (for example 'tesT') --> it is not allowed (correct)
3) add another tag (for example 'tes')
4) double click on the tag added at point 3, and modify it to make it equal to the first one using an upper case character (for example 'tesT'). --> the tag is actually acccepted by the library (wrong)
4) repeat step 2 (add for example 'tesT' again or 'TesT' or 'Test') --> it is not allowed (correct)

![image](https://user-images.githubusercontent.com/4883463/169082800-5fa18383-c677-47d4-a927-9a4f7a7fcbab.png)

**Comment by yairEO** [comment]
Related to #1019
