### ISSUE TITLE
How to change the output of a mixed mode textarea

### ISSUE THREAD

**Issue by welja** [yairEO/tagify#1037]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Demo page
https://jsfiddle.net/szntkq74/2/

## stackoverflow question
https://stackoverflow.com/questions/72288592/tagify-mixed-mode-change-format-posted-data

I would like to change the data submitted to the server from:
`[[{"value":"James"}]]`
to
`[[James]]`

The **originalInputValueFormat** example doesn't seem to work with a mode: 'mix' and i did not find any other way in de docs.
Is this possible?

By the way, thanks you for creating this great library!

**Comment by yairEO** [comment]
May I ask why can't you work with the way it is now? 
Such a change requires me to make adjustments in the code and devote time for it ofc, 
so it's very important for me to know that it is really help you and it's not out of laziness that you do not want to work with the current format

**Comment by welja** [comment]
I am using the data of the textarea in a template engine, for example i have in my database :
`My name is [[user.name]]`
And when is show the content, the user.name part is replaced with the username, like:
`My name is James`
When i edit the template for that page tagify is used to autocomplete the posible variables and mix it with text.

I solved this "problem" by cleaning up the data serverside, with a simple regex:
```
// remove all linebreaks ed
$string = str_replace(["\n", "\r"], '', $string);
// find the tags [[ ]] and lift out the value
return preg_replace( '/\[\[\{"value":"(.*?)\".*?\}\]\]/', '[[$1]]', $string );```

So it would be nicer (for me) if the input and the output was the same. Also Tagify added more properties in the json, like {value:"user.name", prefix: "{"}. My regex fixes that also.

I would not want you to spend time on it, i just wondered if there was an event so i can modify the output when the form is submitted so i can adjust it with javascript instead of using PHP for that. 

I am a PHP programmer with basic javascript skills so maybe i missed that option.

**Comment by yairEO** [comment]
It's not possible. You save it in your server, as-is (String). 

May I know why does it matter how the string looks like?

**Comment by yairEO** [comment]
Good suggestion. I am adding support now and for *mix-mode* that setting should be configured as so:

```js
originalInputValueFormat: tagData => tagData.value
```

**Comment by welja** [comment]
That looks great,
Thanks!
