### ISSUE TITLE
Adding tags without @ (by just typing the text and pressing enter)

### ISSUE THREAD

**Issue by ShadabFaiz** [yairEO/tagify#1040]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

How can I add the tag (in mix) by pressing `Enter` ? without using `@`.

**Comment by yairEO** [comment]
Hi, that is not supported and also doesn't make sense, because how would a user do a "regular" Enter for a new line? 
How will Tagify know what should be a tag and what shouldn't?
