### ISSUE TITLE
Correct way to have different display & edit values ?

### ISSUE THREAD

**Issue by adrienWeiss** [yairEO/tagify#1043]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page 
https://jsfiddle.net/adrienWeiss/05dmyLbu/13/

------ 

Hi, and thanks a lot for your work on Tagify 👍 
I am trying to achieve something that may look familiar, for handling email recipients kind of the way Gmail does it.

I have a function that will correctly detect a `name`  and an `email` in a string such as `John Doe <john@gmail.com>`.
My plan is only display the name in the tag (or email if not available), but always the full value when in edit mode (then, on update, parse again to update).
So basically a `tag` would look like this : 
```js
{
  title: 'John Doe',
  value: 'John Doe <john@gmail.com>',
}
```

I kinda have something working right now but I'm not quite sure this is the correct way to do it (see Demo).

1/ I am using `edit:start` event to change the `contenteditable` content (by querying it and modifying its `innerHTML` as I did not find an exposed method to do this . It does not feel right 😬 

2/ I am using `transformTag` to parse again the new value and recreate the shae `{ title, value }` I need.

3/ I am overriding the `tag` template to show the `tag.title` if exists.

4/ I have to use `duplicates: true` otherwise entering edit mode and immediately triggering blur would show a `Duplicate` error (I guess it does not recognize the tag because of the change in `edit:start` and compares the value, which is the same).

------ 

I cannot use `tagTextProp` to use my `title` key directly because when I do, Tagify does not escape its anymore and thus my `<email>` format is read as an unknown HTML tag. I could not find a way to correctly handle escaping/unescaping between display & edit mode (I found an [issue](https://github.com/yairEO/tagify/issues/733) for this but I don't think the fix applies when using a different `tagTextProp`. I don't know if it would help though.

Anyway, I would just like your opinion on the matter, I feel like I may be missing a much, much easier way of doing so using Tagify methods.

I think basically it comes down to "edit mode should use the `value` (or a custom key) and not the innerHTML of the `contenteditable` span. What do you think ?

Anyhow, I hope this helps anyone else trying to figure out how to have a custom display mode on tags.
Thank you for your help

**Comment by yairEO** [comment]
Thanks for letting me, this is a good suggestion and I will work on this task to allow defining a new setting property which will tell Tagify what should it use when editing a tag. It might be complex (with the way things are working now), but I see there is a need for such feature.

**Comment by yairEO** [comment]
I've done a full example of this which can be [seen here](https://yaireo.github.io/tagify/#users-list)

Closing this as the example should clarify how to show different value in *edit mode*
