### ISSUE TITLE
React Tagify Template Example is not working with latest Tagify version

### ISSUE THREAD

**Issue by lohit8846** [yairEO/tagify#1050]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/s/oempc

Comment out the import of custom package on line 2 of TagifyWithTemplates.jsx and comment in the import of the NPM package on line 3. It doesn't work even when updating to the latest version of Tagify

### Explanation

- **What is the expected behavior?**

Example should load when using NPM package for Tagify

- **What is happening instead?**

@yairEO The page crashes before loading with this error. `Cannot read properties of undefined (reading 'settings')`. Can you please check the difference between the custom tagify package used in the example and the one in NPM, so you can release a working version. This will allow us to use this useful feature you built for react component template substitutions. Thank you

**Comment by yairEO** [comment]
works fine for me, just updated the React Codesandbox example with latest packages (except React) 

https://codesandbox.io/s/tagify-react-wrapper-oempc

**Comment by lohit8846** [comment]
@yairEO It still doesn't work for me because you actually did not update the sandbox for the file TagifyWithTemplates.jsx
It is still using the custom package in the local directory and I see the same error when commenting in the NPM package

Please take a look. Here's a screenshot

<img width="1345" alt="Screen Shot 2022-06-21 at 4 15 37 PM" src="https://user-images.githubusercontent.com/27837168/174911898-f18fdd9f-f96a-4c6c-b8a8-08fd6ef9400f.png">

**Comment by lohit8846** [comment]
@yairEO Okay thanks for looking into this. I printed out the props and see that tagify is undefined, so the code will not work. Do you know what is different about the custom tagify package in local directory that allows it to work?

**Comment by yairEO** [comment]
nothing is different, I don't understand this, but we will see once I push the new version

**Comment by lohit8846** [comment]
@yairEO Okay got it. Any update on this or when you plan on pushing a new version?

**Comment by yairEO** [comment]
Hi, I hope to push it today/tomorrow

**Comment by yairEO** [comment]
> @yairEO Okay got it. Any update on this or when you plan on pushing a new version?

Hi, I hope to push it today/tomorrow
