### ISSUE TITLE
Wrong output value when removing a tag by clicking on the cross

### ISSUE THREAD

**Issue by AxelHaddad** [yairEO/tagify#1055]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://codesandbox.io/s/tagify-issue-when-removing-a-tag-by-clicking-on-it-dt5d48?file=/src/index.js

### Explanation

On react, in mixed mode I remove a tag by clicking on the <kbd>&times;</kbd> button. the value returned by the change event (`e.detail.value`) is wrong, instead of being removed the tag is just converted to text, while the displayed text is correct 

- **What is the expected behavior?**
The tag is removed in the textarea and the value given in the change event `e.detail.value` is the correct value (i.e. it matches what is in the text area).

- **What is happening instead?**

The tag is indeed removed in the text area but *not* in the value given by the event. Instead, in the value given by the event, the tag is just converted to text and to make it disappear I have to edit the text area.

- **Remarks**
    - I have the same problem with the remove event value in `e.detail.tagify.DOM.originalInput.tagifyValue`.
    - I don't have the problem when removing a tag with backspace

**Comment by AxelHaddad** [comment]
I found a workaroud in my case by setting a onRemove callback:
```javascript
onRemove = {() => {
    tagifyRef.current.update();
}}
```
This will trigger a new change event with the correct value. Note that this callback is also handy because removing with backslash does not trigger by default a change event.

**Comment by yairEO** [comment]
Hi, the `onChange` works exactly like the DOM spec - when the field gets a `blur` event (looses focus) then the event fires.

**Comment by AxelHaddad** [comment]
Thanks! Ok, so it's expected to have to add some more codes to get the correct output values (correct in the sens of mapping what we can see on the screen), as I mention in [this comment](https://github.com/yairEO/tagify/issues/1055#issuecomment-1172381907)?

**Comment by yairEO** [comment]
To be able to listen to the `change` event continuedly (not only when the field looses focus) I would need to modify the source-code. I will work on it.
