### ISSUE TITLE
Tagify does not support shadow dom / web components

### ISSUE THREAD

**Issue by lsgroup** [yairEO/tagify#1057]
Hello, drop down does not work properly when inside a web component / shadow dom.  Source code references things like document.body.appendChild.  Any suggestions?

**Comment by yairEO** [comment]
Please explain what are you trying to do? You want to convert Tagify into a web component?

**Comment by lsgroup** [comment]
Hi yairEO, 
No, when I use tagify within a web component (within shadow-dom), the suggestions list does not display correctly - it displays at the very top of the page instead of underneath the input tag.  The same code snippet works correctly if I am outside of the web component (in the light-dom).  I think this is because the suggestions list calls the document object to append elements for the suggestions list.  In order to append to a DOM element inside a shadow dom, you'd have to reference shadowRoot instead of document.  I'm happy to help on this as well, but wanted to see if you had any insights.

**Comment by lsgroup** [comment]
btw - thanks for responding - great component, works really well!

**Comment by yairEO** [comment]
I am guessing it will be quite difficult to fix this as web-components are encapsulated and many of Tagify's events are delegated
