### ISSUE TITLE
Stay focused after modifying an existing tag

### ISSUE THREAD

**Issue by frenci8** [yairEO/tagify#1058]
Hi,

Right now, if I enter a few keywords and then decide to modify one of those, the input field won't be focused anymore, so I have to grad my mouse and click the input field so I can start entering some fields. 

How can I make it so after a user modifies a certain existing keyword, the field stays focused so the user can keep writing and adding new keywords without needing to click the input field?

Thank you

**Comment by yairEO** [comment]
Are you using the `backspace = 'edit` setting?

Anyway, you can do it like so:

```js
tagify.on('edit:updated', ({detail: {tagify}}) => {
    tagify.DOM.input.focus()
});
```

**Comment by frenci8** [comment]
thank you
