### ISSUE TITLE
Tagify not compatible with Firefox 47

### ISSUE THREAD

**Issue by xavier-ottolini** [yairEO/tagify#1059]
## Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

I use Firefox 47 for a specific CMS called Screen Composer. Tagify is not working Firefox 47. There is a JS error
```
TypeError: this.DOM.input is null
Stack trace:
tagify.min.js:2641:9
```

Reason :

    Settings.inputSelector returns a bad selector.

The solution is in the `applySettings` method 👍 

```js
  for (let name in _s.classNames) {
    // Fix compatiblity with Firefox 47 +
    const currentName = name;
    const propName = currentName + "Selector";
    Object.defineProperty(_s.classNames, propName, {
      get() {
        return "." + this[currentName].split(" ")[0];
      }

    });
    // Fix compatiblity with Firefox 47 -
  }
```

**Comment by yairEO** [comment]
Hi, thanks for reporting but I don't understand how is your suggested fix different from the current code..
You just created 2 new variables which one of them is pointing to an already - existing variable `currentName  = name` and the other is doing what is already done in the 2 parameter of `defineProperty`:

```js
for( let name in _s.classNames )
    Object.defineProperty(_s.classNames, name + "Selector" , {
        get(){ return "." + this[name].split(" ")[0] }
})
```

**Comment by xavier-ottolini** [comment]
The problem is that with `let name in _s.classNames`, the property generated by `Object.defineProperty` is replace by the next one in the loop.
By the fix above, the problem does not occure any more.
You can also shorten it by :

```
 for (let name in _s.classNames) {
    // Fix compatiblity with Firefox 47 +
    const currentName = name;
    Object.defineProperty(_s.classNames, currentName + "Selector", {
      get() {
        return "." + this[currentName].split(" ")[0];
      }

    });
    // Fix compatiblity with Firefox 47 -
  }
```

**Comment by yairEO** [comment]
Very odd, as `let` keyword should work in Firefox 47, as it was [available after version 42](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#browser_compatibility)

The `let` keyword is what's creating an internal scope, so the "original" `name` variable is used when `get()` is called. 

I will fix this one
