### ISSUE TITLE
Demo fails sometimes auto-completing?

### ISSUE THREAD

**Issue by burtonator** [yairEO/tagify#106]
I'm following your demo here;

https://yaireo.github.io/tagify/

Sometimes some of the tag completion fails.

For example if I type this:

![image](https://user-images.githubusercontent.com/45447/45603297-cc3a0480-b9df-11e8-9448-5571be3b6efe.png)

but if I just type an 'a' it will fail:

![image](https://user-images.githubusercontent.com/45447/45603300-d6f49980-b9df-11e8-887f-93c015b79214.png)

**Comment by davide-lucchelli** [comment]
Hi, same error here.
If the typed chars match only one item, the dropdown disappear and there is no way to select item.

**Comment by leccyril** [comment]
hi same problem, i really need autocompletion with only one item

**Comment by yairEO** [comment]
I'm on it! Thanks for spotting this. I really aught to start writing tests for this project as it grew quite big and it's not easy to manually test everything after code changes

**Comment by yairEO** [comment]
I'm on it! Thanks for spotting this. I really aught to start writing tests for this project as it grew quite big and it's not easy to manually test everything after code changes

**Comment by leccyril** [comment]
no probleme great tools,  i have to adapt it because in my backend it is a select with multiple id object but i think i will manage to do it... thanks for reactivity
