### ISSUE TITLE
Wrong duplicate tag with capital letter

### ISSUE THREAD

**Issue by Polm90** [yairEO/tagify#1062]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

[https://jsbin.com/luvamexodu/edit?html,js,output](https://jsbin.com/luvamexodu/edit?html,js,output)

### Explanation

1. add a tag (e.g. "tes")
2. double click on the tag and rename it changhing a letter with the same capital letter (e.g. "teS"). --> the library doesn't accept it beacause it is duplicate (WRONG)
![image](https://user-images.githubusercontent.com/4883463/178238293-e6074fab-9f66-4a78-a3ee-39ef49b1edd0.png)
3. edit it again and change its name again (e.g. "test") --> the tag is now "grey" as it is valid, but it is not really added (WRONG)
![image](https://user-images.githubusercontent.com/4883463/178245118-6ba45a28-6be2-40d6-b861-fed74897f7be.png)

**Comment by Polm90** [comment]
@yairEO I'm still having the issue with version 4.13.2

**Comment by yairEO** [comment]
@Polm90 - oops :p will recheck check, sorry buddy!
