### ISSUE TITLE
maxItems: 0 does not show whitelist

### ISSUE THREAD

**Issue by Offerel** [yairEO/tagify#1063]
## Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

If maxItems is set to 0, the dropdown is not rendered. This seems to be the case since 4.12 but is also present in 4.13.1

### 💥 Demo Page
https://jsbin.com/jekuqap/edit?html,js,output

### Explanation

- **What is the expected behavior?**
- the dropdown should be visible

- **What is happening instead?**
- the Dropdown is not rendered

- **What error message are you getting?**
- No error message visible in dev console

**Comment by yairEO** [comment]
Why do you need to set `maxItems` at all?

**Comment by Offerel** [comment]
I know :-) My goal was it, to have all Whitelist entries in the view. Since the whitlelist is dynamic in my case, i never no for sure, how much I have on initialization time. If i previously set maxItems to 0, i got exactly this feature. Maybe this was a wrong understanding from my side. If this is the case, we can close this issue and i use my workaround, to count the array on receiving the whitelist array and use this as maxItems. This is absolute ok for me.

**Comment by yairEO** [comment]
Try setting it to [`Infinity`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity)
