### ISSUE TITLE
On change event getting called with the wrong value

### ISSUE THREAD

**Issue by Buzunda** [yairEO/tagify#1065]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/s/tagify-onchange-issue-ex0n70?file=/src/TagsInput.jsx

### Explanation

- **What is the expected behavior?**
Tag selection should work normally when using whitelist and the mode is select

- **What is happening instead?**

This is a weird one

If we have a whitelist
![Screen Shot 2022-07-12 at 21 07 03](https://user-images.githubusercontent.com/4948776/178620530-5931a486-ec23-4c5a-b7c0-5f50b7b700ef.png)

and we have to type to select the element

![Screen Shot 2022-07-12 at 21 07 25](https://user-images.githubusercontent.com/4948776/178621077-c8bea11d-7ecc-44d7-85b9-a13761432fe8.png)
![Screen Shot 2022-07-12 at 21 07 42](https://user-images.githubusercontent.com/4948776/178621198-07630723-ecf9-47d9-a9c4-43f24b66e4ac.png)

after selecting the element it initially works:

![Screen Shot 2022-07-12 at 21 07 47](https://user-images.githubusercontent.com/4948776/178621442-00c4dfe6-bf5a-4a90-84f2-22a88627a61e.png)

but if you click anywhere on the page after, the onchange event gets called again with the wrong values. Sometimes the menu opens too

![Screen Shot 2022-07-12 at 21 07 53](https://user-images.githubusercontent.com/4948776/178621669-a0866de7-af73-4bec-ad9a-2ae0680f2020.png)

This is not exclusive to react, found this with plain JS

- **What error message are you getting?**
No error messages

**Comment by Reikooters** [comment]
This may or may not be your issue, but I believe `value` (not `text`) should be the text that you want to appear in the list. You can also add other arbitrary data into the object you might need in your application.

I'm not using the React component so I don't know whether it differs.

I'm using the whitelist like so:

```
whitelist: [
  { value: "Zero", id: 0 },
  { value: "One", id: 1 },
  { value: "Two", id: 2 },
  { value: "Three", id: 3 },
],
```

And you can capture the selected value like so

```
tagify.on("change", function (e) {
  console.log(JSON.parse(e.detail.value));
});
```

Where if you selected Two it should give you

```
[{"value":"Two","id":2}]
```

**Comment by yairEO** [comment]
Hi, I will check this as soon as I can. hopefully it will be solved by the end of the weekend. it this urgent?

**Comment by Buzunda** [comment]
Thanks for checking it out, this is not urgent but I had to use a different component to handle the selection for the time being.

**Comment by yairEO** [comment]
Which one? is it as good as Tagify?

**Comment by Buzunda** [comment]
Haha no, is that we have some cases for single selection that I was using tagify on the same component and I am using a select instead. We also keep using tagify for multiple selections and on mix mode and is still working great.

**Comment by yairEO** [comment]
I'm pretty sure this is related to #1064

**Comment by yairEO** [comment]
seems to be fixed
