### ISSUE TITLE
Memory leak from observers?

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#1068]
## Prerequisites

- [x] I am running the latest version

### Explanation

- **What is the expected behavior?**

Calling tagify.destroy() should ensure it gets garbage collected eventually.

- **What is happening instead?**

The tagify objects are being retained.

- **What error message are you getting?**

I traced it down to https://github.com/yairEO/tagify/blob/39a61fc11343d9233c71c03e6c67c67a46d13f5f/src/parts/events.js#L76 where the observers are getting created. I think the binding function shouldn't setup the observers when it is called in unbind mode. I am temporarily able to workaround this with the following code

```js
tagify.removeAllTags();
tagify.destroy();
const listeners = tagify.listeners;
if(listeners.main.originalInputValueObserverInterval) clearInterval(listeners.main.originalInputValueObserverInterval);
```

I am able to confirm that the memory gets freed up but since this is making use of internal details of the Tagify implementation, I am filing this issue.

**Comment by yairEO** [comment]
Thanks for reporting! Makes sense, I will fix it

**Comment by dirslashls** [comment]
Thanks @yairEO for the fix
