### ISSUE TITLE
The tags are getting rendered at the bottom of the page.

### ISSUE THREAD

**Issue by KumarRitwick** [yairEO/tagify#1069]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
->  The dropdown of dynamic values should be there but not shown, unless the User is editing the tags.
- **What is happening instead?**
-> The dropdown is getting the whitelist value dynamically and the dropdown is always enabled and it gets rendered at the bottom of the page.
- **What error message are you getting?**
![Screenshot 2022-07-19 at 9 37 48 AM](https://user-images.githubusercontent.com/58397038/179662556-3652e639-73cb-4112-abcb-64e4ea86f1ef.png)

**Comment by yairEO** [comment]
Hi, I cannot help without a reproducible demo page in JSBIN (as asked for in the issue template which you deleted..)

I need to see your Tagify config, and any CSS that might causes this

**Comment by KumarRitwick** [comment]
Hi Sorry, my bad,
here's the link
https://jsbin.com/bidotitopi/edit?html,css,js,console,output
Have added the necessary comments and have added a pseudo version of my implementation.

**Comment by yairEO** [comment]
closing this as this is clearly a bug in your own CSS 99% likely and not related to Tagify

**Comment by KumarRitwick** [comment]
Thank You.
