### ISSUE TITLE
how to change the tag color (instead of grey)

### ISSUE THREAD

**Issue by leccyril** [yairEO/tagify#107]
hi, 

how to change the tag color please in css ? 

is possible to show in dropdwon autocompletion the description  ? 

thank you !

**Comment by it-xtech-dev** [comment]
Have you tried to look at markup and style sheets?

```
.tagify tag>div:not([contenteditable]) {
  background-color: red;
}
```

What do you mean by 'the description'?

**Comment by leccyril** [comment]
i wil try it.

for example we show an object Tag (with id, value, label, description) and we want aucomplete the label and for example other value from the JSON object (as the flag example, is great)

in stackoverflow, you can choose tag and in autocompletion, there is the label and the tag description

if we want choose only whitelist (we don't know the forbidden list we want only choose from white list) how do we do ? 

thanks a lot

**Comment by leccyril** [comment]
the color css is working , thanks for answer !
