### ISSUE TITLE
Issue with commas in whitelist or entries

### ISSUE THREAD

**Issue by slugb0t** [yairEO/tagify#1071]
## Prerequisites

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I am running version 3.25.0

### 💥 Demo Page

https://jsbin.com/febuginota/edit?html,js,output

### Explanation

- **What is the expected behavior?**
- Value from whitelist with commas should create one whole tag rather than dividing up into multiple tags where commas are.

- **What is happening instead?**
- I have some items in the tagify whitelist that have commas. When selecting them or writing a comma in a new tag it divides the tag where the commas are placed.

- **What error message are you getting?**
N/A

**Comment by yairEO** [comment]
For that you have the [delimiters](https://github.com/yairEO/tagify#settings) setting.
By default it is set to `','` so you need to change it to your needs.

**Comment by slugb0t** [comment]
Thank you! I appreciate the help!
