### ISSUE TITLE
`onChange` callback is called on `blur`

### ISSUE THREAD

**Issue by captain-yossarian** [yairEO/tagify#1072]
## Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

Hi, `onChange` callback of `MixedTags` is called only  ` on blur`. Is this by design ?
I want to make controlled component and every change of `value` should affect `state`. How can I do this if `onChange` actually called only on `blur` ?

**Comment by yairEO** [comment]
Yes, this is the W3C standard way for all inputs elements

**Comment by yairEO** [comment]
See issue #1055

I am going to a add a new setting in the next release called `onChangeAfterBlur`, and if set to `false` it will cause
the `change` event to be fired on every change (add/remove/edit) and not only when the field is blurred

**Comment by captain-yossarian** [comment]
@yairEO Hi, thank you for explanation. I think adding `onChangeAfterBlur` is very good idea. Thank you very much for your work!

**Comment by yairEO** [comment]
You can now try it out :)
