### ISSUE TITLE
How to add a `tag` on click (React) ?

### ISSUE THREAD

**Issue by captain-yossarian** [yairEO/tagify#1073]
## Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

How to add a `tag` on click ?  Is it possible, in React, to add a tag into content editable input on tag click ? I did not find it in examples. Could you please help ?

**Comment by yairEO** [comment]
add a tag on tag click? I don't understand. how can you add something by clicking on it before it exists?

**Comment by captain-yossarian** [comment]
@yairEO Sorry, I was not clear enough. See this example:
![tags](https://user-images.githubusercontent.com/16646733/180371742-69c1e20e-02ed-4b1c-9717-2862b1f9e180.png)

Imagine you have several tags on the top. When you click on some tag, this tag should also appear inside of Editable content

**Comment by yairEO** [comment]
Sorry I am currently overly flooded with tasks and I hope to answer you this weekend

**Comment by yairEO** [comment]
Hi, can you please [clone this jsbin](https://jsbin.com/jekuqap/edit?html,js,output) and configure the demo page as you wish, so I could examine?

**Comment by yairEO** [comment]
> Is there any way to keep the textarea focused and with the cursor after the added tag?

Yes, the [FAQ section in the README](https://github.com/yairEO/tagify#faq) explains how:
https://github.com/yairEO/tagify/issues/524#issuecomment-699140465
