### ISSUE TITLE
About validation before adding tags

### ISSUE THREAD

**Issue by wabgy** [yairEO/tagify#1074]
Hello,
Check the format of the input content before adding tags. If the input format is incorrect, but you want to keep the input content and prevent the input content from becoming a tag, can this be done?

**Comment by yairEO** [comment]
https://github.com/yairEO/tagify#validations

**Comment by yairEO** [comment]
Are you using the `keepInvalidTags` setting?

(Best writing in the original issue instead of opening a new issue for each question)

**Comment by yairEO** [comment]
I see what you mean - you want to have a custom function which completely blocks the creation of a tag (even an invalid one)

**Comment by wabgy** [comment]
Hi, thanks for your reply.
Yes, I was using keepInvalidTags at first, but found this still creates invalid tags.
I hope to have a custom function, when the content entered by the user does not meet the requirements, the user can directly modify the content to make it completely correct, and then generate the label. Instead of knowing that the input content is incorrect, it is necessary to generate a label and then modify it by editing.
