### ISSUE TITLE
Tagify input in datatable field cause web crash

### ISSUE THREAD

**Issue by HankLees** [yairEO/tagify#1075]
Hi:
I use the tagify kit in the Datatable field. When the first tag is not completed and cleared, the web page will crash. You need to close and restart the web page to respond. This problem only happens in chrome but in Firefox, Edge does not happen. , I would like to ask if you have encountered similar problems or where the writing needs to be adjusted

The following is the current usage
  const tagifyBasicEl = document.querySelector("#ID");
  const TagifyBasic = new Tagify(tagifyBasicEl);

environment
net core mvc
html+Jquery+Bootstrap5

https://user-images.githubusercontent.com/8588022/180403805-065ff053-1e07-4bf1-997c-5f34b7e61973.mp4

**Comment by yairEO** [comment]
I have no idea but it doesn't sound like it is related to Tagify at all
