### ISSUE TITLE
Change CDN away from unpkg

### ISSUE THREAD

**Issue by AndreasBakke** [yairEO/tagify#1076]
# Issue Summary: #
unpkg is unmaintained, which may result in a bad user experience for users. Especially today, when unpkg returned 520 errors for most libraries. ref:  https://github.com/mjackson/unpkg/issues/338

# Recommendation: # 
Change provider from unpkg to cdnjs, jsdelivr or equivalent.

Example:
````
<script src="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.14.0/tagify.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.14.0/tagify.polyfills.min.js" </script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.14.0/tagify.css"/>
````

**Comment by yairEO** [comment]
Thanks I havn't noticed any problems whatsoever with Tagify on `unpgk` but if you say they are unmaintained then I will update the text in the README to recommend `cdnjs`.
