### ISSUE TITLE
How to control focus position

### ISSUE THREAD

**Issue by wabgy** [yairEO/tagify#1078]
Hello,
Add the following property values
skipInvalid: true,
addTagOnBlur: false,
keepInvalidTags: false,
When I verify the content is not correct, press the enter key and keep the input content, use this method $('.tagify__input').text('input');
The focus position is always at the front of the content, and I want to set it at the end of the content. How to do it?

**Comment by yairEO** [comment]
Hello. Please create a **jsbin** as instructed in the issue template (which you've deleted)

**Comment by wabgy** [comment]
Enter characters longer than 6, press Enter, the focus of the input box is in front of the content.
https://jsbin.com/kerihitoyu/edit?js,output

**Comment by yairEO** [comment]
Your "solution" will fail when a user will paste content with multiple tags, such as: `aaa, bbb, cccccccc, ddddddd`

I've made modifications to [your code](https://jsbin.com/yezixab/1/edit?js,output)

```js
var input = document.querySelector('input')
var tagInput = document.getElementsByClassName('tagify__input')
var tagify = new Tagify(input, {
  skipInvalid: false,
  addTagOnBlur: false,
  keepInvalidTags: false,
  texts: {
    exceed: '',
    duplicate: '',
  },
  validate: (tagItem) => tagItem.value.length < 6,
})

tagify.on('change', console.log)

tagify.on('invalid', e => {
  setTimeout(()=> {
    tagify.input.set.call(tagify, e.detail.data.value);
    tagify.setRangeAtStartEnd(); 
  });
})
```
