### ISSUE TITLE
How can i keep line breaks in mix-mode

### ISSUE THREAD

**Issue by qijunxin** [yairEO/tagify#1079]
I prefer to keep line breaks in mix-mode, such as:
![image](https://user-images.githubusercontent.com/14814936/180691770-87aacc36-2cc7-4222-8b2a-b6c0c0b2cf59.png)
But i can't find an effective way to config it. The "\n" always be eliminated.

**Comment by qijunxin** [comment]
use  `InputMode="textarea" `and  `trim: false` can fix it!
import Tags from "@yaireo/tagify/dist/react.tagify";
     <Tags
        InputMode="textarea"
        settings={{
          trim: false,
        }}
        ...
     />...

**Comment by yairEO** [comment]
As the README says:

> `<MixedTags>` component is a shorthand for `<Tags InputMode="textarea">`
