### ISSUE TITLE
Remove child error

### ISSUE THREAD

**Issue by ranjitnadar** [yairEO/tagify#108]
Uncaught TypeError: Cannot read property 'removeChild' of null

**Comment by yairEO** [comment]
which browser? does this happen all the time?

**Comment by ranjitnadar** [comment]
Chrome, Yes it happen all time

**Comment by SarahShkb** [comment]
Hello and thanks for the great work!
I used to get this Error: "DOM is not defined" on version 4.9.0 after Tagify.destroy() was called,
And now after upgrading to the latest version (4.11.0) I'm getting this error: "Cannot read properties of null (reading 'removeChild')"
I'm using Tagify in a react modal, and after I close the modal, Tagify.destroy() is being called and the error happens
Maybe it's a bug, any hint or help would be so appreciated!

**Comment by yairEO** [comment]
Hi @SarahShkb - I can't seem to reproduce the error when using the `destroy` method:

> Tagify (v 4.11.0)

https://jsbin.com/kepuzel/edit?html,js,output

**Comment by SarahShkb** [comment]
@yairEO Hi again and thanks for your response!
I think it's ok in JS but not in React,
In React Modal, it looks like Tagify.destroy() is called after parent is destroyed.
in tagify.js, line 2325:
`this.DOM.scope.parentNode.removeChild(this.DOM.scope);`

if I check whether or not `parentNode` is defined, everything will be good:
`this.DOM.scope.parentNode?.removeChild(this.DOM.scope);`

could you please consider as a bug fix?
thanks!
