### ISSUE TITLE
dropdown.mapValueTo matches on title instead of value for duplicate items

### ISSUE THREAD

**Issue by wurst-hans** [yairEO/tagify#1080]
Sorry, have no Codepen account, so I'll describe how to reproduce the error. I'm using your example for "Single-Value Select" at [Codepen](https://codepen.io/vsync/pen/yLONYdx). Replace your definition of `var tagify = <...>` with:

```
var tagify = new Tagify(input, {
    mode : "select",
    whitelist: [{value:1,title:"first option"}, {value:2,title:"second option"}, {value:3,title:"third option"}, {value:4,title:"second option"}],
    tagTextProp: 'title',
    keepInvalidTags: true,   // do not auto-remove invalid tags
    dropdown: {
        mapValueTo: 'title'
    }
});
tagify.on('click', e => console.log(e.detail));
```

As you can see, I'm using an object for whitelist and set Tagify to display `title` instead of `value`. Please notice, that the `title` of the item with value `4` is the same title as for second item in list. When you select the last option in dropdown (which belongs to item with value `4`), Tagify uses second item instead (as you can see in console).

So, instead of only displaying the content of `title`, Tagify also seems to match tags internally using `title`. The documentation for `mapValueTo` states too, that the property is used for displaying dropdown text only. My expectation is, when there are multiple items, having same label or tag text, that Tagify still returns correct tag that has been selected from dropdown.

**Comment by yairEO** [comment]
_Codepen_ accounts are **free** :) and the issue template is asking for a _jsbin_ example (not Codepen)

I will examine this issue and get back to you soon
