### ISSUE TITLE
How to check if element has already been Tagified? (Stimulus JS)

### ISSUE THREAD

**Issue by daryld212** [yairEO/tagify#1085]
Hoping this is an easy one, I'm getting the error:
`Tagify:  input element is already Tagified `

How can I tell Tagify to skip an element, if it's already been Tagified? Maybe something like this:

```
export default class extends Controller {
  connect() {
    // This doesn't currently work - am I checking for the correct attr here?
    if (!this.element.tagified) {
      new Tagify(this.element, {
        ...
      });
    }

  }
}
```

**Comment by yairEO** [comment]
You don't need to tell it, it's already skipping it automatically + notifying you
