### ISSUE TITLE
'N more items' footer text is wrong when `maxItems` is set to -1

### ISSUE THREAD

**Issue by jdudley1123** [yairEO/tagify#1086]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/zavicufoza/1/edit?html,js,output
There are 6 items on the whitelist. Two tags have already been added to the field. That leaves 4 that are displayed in the dropdown, but the text says '5 more items', suggesting there are 9 others rather than 4.

### Explanation

- **What is the expected behavior?**
Dropdowns have a footer that reads 'N more items. Refine your search.', where N is the number of suggestions not shown in the dropdown.

- **What is happening instead?**
When a dropdown has `maxItems` set to -1 (ie. infinity), the value of N is wrong because it is calculated as `suggestions.length - this.settings.dropdown.maxItems` which doesn't work when `maxItems` is not actually an upper limit.

https://github.com/yairEO/tagify/blob/6f841fb8aad398592614f0b426723b51d75fc1ee/src/parts/templates.js#L73

I think this could be fixed with an additional check in this method so that it only returns the footer if `this.settings.dropdown.maxItems > 0`

**Comment by yairEO** [comment]
why would you set `maxItems` to `-1`? it must be greater than `0`

**Comment by jdudley1123** [comment]
Oh, for some reason I thought that `-1` was the way to set it to infinity - I've had it like that in my code for a long time, but I don't know where I got that idea from. I think it must be because `-1` is often used like that in other settings.

In any case, this is not documented functionality so please ignore my bug report. Setting it to a large number like 999 works fine for 'infinity'.

**Comment by yairEO** [comment]
if you want infinity than set it to [`Infinity` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity)
