### ISSUE TITLE
Type error after upgrading to 4.15.x

### ISSUE THREAD

**Issue by Polm90** [yairEO/tagify#1087]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
[https://jsbin.com/jekuqap/edit?html,js,output](https://jsbin.com/serenoh/edit?html,js,output)

After upgrading the library to version 4.15.x I receive the following error in console, so the code is not working.
![image](https://user-images.githubusercontent.com/4883463/182118732-0fac19da-1ac1-42af-bca1-26600aa0d0f7.png)

Downgrading the library to 4.14.2 properly works.

**Comment by yairEO** [comment]
The `dropdown` template has changed. You can compare yours with [the new one](https://github.com/yairEO/tagify/blob/master/src/parts/templates.js#L43).

The main change is renaming to `data-selector='tagify-suggestions-wrapper'`
