### ISSUE TITLE
My old codepen getting "Cannot set properties of null (setting 'innerHTML')"

### ISSUE THREAD

**Issue by eugene-makarov** [yairEO/tagify#1092]
## Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://codepen.io/eugene-makarov-the-looper/pen/zYRrYpg/c474749ef663e5a777c899b61793a661

### Explanation

- **What is the expected behavior?**
This is an old codepen, it used to work for several months, but recently got broken.

- **What is happening instead?**
Started getting an error in console logs

- **What error message are you getting?**
`Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')`
This is the line: `this.DOM.dropdown.content.innerHTML`

**Comment by eugene-makarov** [comment]
The issue appeared in `4.15.0` version

**Comment by yairEO** [comment]
Hi, you get an error because the `dropdownTemplate` has changed recently. 

See changed line:

https://github.com/yairEO/tagify/blob/master/src/parts/templates.js#L43

**Comment by eugene-makarov** [comment]
Hmm, okay I'll fix it on my side! Thanks!
