### ISSUE TITLE
[typescript] Module parse failed: Unexpected token (588:33)

### ISSUE THREAD

**Issue by breakerh** [yairEO/tagify#1093]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

When we want to use Tagify in our React Typescript project we get the following error on compilation:
```js
./node_modules/@yaireo/tagify/dist/tagify.js 588:33
Module parse failed: Unexpected token (588:33)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           headerRef = this.dropdown.getHeaderRef(),
|           footerRef = this.dropdown.getFooterRef();
>       newHeaderElem && headerRef?.parentNode.replaceChild(newHeaderElem, headerRef);
|       newFooterElem && footerRef?.parentNode.replaceChild(newFooterElem, footerRef);
|     },
```

### Explanation

It looks like optional-chaining doesn't work in the project and i'm not sure how to fix this on my side??

**Comment by breakerh** [comment]
Didn't notice the last update from 3 days ago..
[4.15.3](https://github.com/yairEO/tagify/commit/621d402183026e8b4427ff4668a9c2d54dd34466)

Seems to solve the issue...

**Comment by breakerh** [comment]
Was closed since i wasn't on latetst version.. I'm now but it's still not working :(

**Comment by yairEO** [comment]
You need to make sure your Babel is configured correctly and is updated. Are you using the latest `@babel/preset-env` ?

This is not a problem with Tagify but with your specific project's configuration

**Comment by breakerh** [comment]
Thanks! yes i use quite a lot of modules for this project I work on. And none used optional chaining as it seems...
latest `@babel/preset-env` solved it.
