### ISSUE TITLE
Suggestions dropdown does not highlight first item

### ISSUE THREAD

**Issue by eugene-makarov** [yairEO/tagify#1094]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://yaireo.github.io/tagify/#section-mix
https://codepen.io/eugene-makarov-the-looper/pen/zYRrYpg/c474749ef663e5a777c899b61793a661

### Explanation

- **What is the expected behavior?**
The dropdown.highlightFirst doesn't seem to work anymore. Seems to occur in 4.15 version

- **What is happening instead?**
When highlightFirst setting is set to true, the first item should be selected when the dropdown opens, so that a user can press enter to add a tag.

- **What error message are you getting?**
No message

**Comment by yairEO** [comment]
Thanks for reporting. I will fix this soon, hopefully in a matter of 2 days
