### ISSUE TITLE
Positioning issue when manually showing the dropdrown

### ISSUE THREAD

**Issue by AlanWaiss** [yairEO/tagify#1095]
I'm using tagify in "mix" mode and my tags are sorrounded by @ - e.g. "User text has @dynamic@ replacements" with the following options:
```
var tagify = new Tagify(t.$el, {
	mode: "mix",
	pattern: /@/,
	whitelist: ['@value 1@', '@value 2@'],
	dropdown: {
		enabled: 0,
		position: "text",
		highlightFirst: true,
		maxItems: Infinity
	}
})
```

I found that the drop down is _not_ showing when you focus on the field in mix mode. I'm not sure if that's intentional or not, but I wanted the users to know that dynamic values are possible, so I added a drop down button next to the field. The button simply focuses on the input, then shows the dropdown. E.g.
```
$(button).click(function() {
try {
	tagify.DOM.input.focus();
}
catch(x) {}

tagify.dropdown.show();
});
```

This works, but if the input field has text content, but the cursor is positioned at the start of the field, the dropdown won't be positioned correctly. It winds up way off the bottom of the page.

I traced the problem to the getCaretGlobalPosition function. The current code is:
```
getCaretGlobalPosition(){
    const sel = document.getSelection()

    if( sel.rangeCount ){
        const r = sel.getRangeAt(0)
        const node = r.startContainer
        const offset = r.startOffset
        let rect,  r2;

        if (offset > 0) {
            r2 = document.createRange()
            r2.setStart(node, offset - 1)
            r2.setEnd(node, offset)
            rect = r2.getBoundingClientRect()
            return {left:rect.right, top:rect.top, bottom:rect.bottom}
        }

        if( node.getBoundingClientRect )
            return node.getBoundingClientRect()
    }

    return {left:-9999, top:-9999}
}
```

The issue is that text nodes don't support getBoundingClientRect. Changing `if (offset > 0)` to `if (offset > 0 || 3 == node.nodeType)` resolves the issue, though there are probably other ways of fixing it.

**Comment by yairEO** [comment]
You are setting the position to `position: "text",` meaning it will open where the caret is. 

If you only run `tagify.DOM.input.focus()`, where is the caret positioned? 
You need to create me a demo page in JSBIN so I could investigate and come up with solutions

**Comment by yairEO** [comment]
Closing as OP disappeared
