### ISSUE TITLE
`new Function` breaks tagify if `'unsafe-eval'` is not set on the page

### ISSUE THREAD

**Issue by ornicar** [yairEO/tagify#1096]
- tagify 4.15.3
- Chrome 104.0 on Linux

Selecting a tag doesn't add it to the input. The browser console shows this:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-3M9bsVHMRdLZmNa3Jt7aoCZD' 'self' l1.org".

    at new Function (<anonymous>)
    at ublogForm.js:formatted:42671:49
    at I.trigger (ublogForm.js:formatted:42678:38)
    at I.selectOption (ublogForm.js:formatted:42516:26)
    at ublogForm.js:formatted:42464:55
```

Here's the problematic line of code:
https://github.com/yairEO/tagify/blob/621d402183026e8b4427ff4668a9c2d54dd34466/src/parts/EventDispatcher.js#L6

With (latest?) google chrome, invoking `new Function` requires that the page has `'unsafe-eval'` in its content security policy. But that's pretty bad security-wise, obviously, and I don't think tagify should require it.

**Comment by yairEO** [comment]
I've fixed it and will push a new version soon

**Comment by yairEO** [comment]
Fixed 

https://github.com/yairEO/tagify/releases/tag/v4.15.4
