### ISSUE TITLE
Placeholder-like suggestion is related to option AFTER the highlighted one

### ISSUE THREAD

**Issue by mbonaker** [yairEO/tagify#1099]
### 💥 Reproduce

- go to https://jsbin.com/belolilono/1/edit?html,js,output
- type `this` so that the dropdown appears
- hover `this-is-first`
- observe that the placeholder-like suggestion in the field is `this-is-second`, not `this-is-first`.

### 🪲 Issue

I would expect to see grey text right next to my input that says `-is-first` since that would complete my input to match what I hover. Instead I see grey text right next to my input that says `-is-second` which would complete my input to match the option *after the one that I hover*.

**Comment by yairEO** [comment]
Thanks for reporting, I will fix asap
