### ISSUE TITLE
Property 'elm' does not exist on type 'DropDownSelectEventData<TagData>'.ts(2339)

### ISSUE THREAD

**Issue by sssrit** [yairEO/tagify#1102]
Hi,
I am getting the error in ` Property 'elm' does not exist on type 'DropDownSelectEventData<TagData>'.ts(2339)
` in dropdown:select property of callback. I am using  tagify in angular.  (Image attached)
![image](https://user-images.githubusercontent.com/8317947/185594858-d75791f5-d21c-457f-a43c-25e71e0bef8a.png)

I am following the same code suggested in https://github.com/Brakebein/ngx-tagify/blob/master/src/app/example-templates/example-templates.component.ts

Please Advice me to solve the error

**Comment by yairEO** [comment]
I suggest you open the ticket there and not here, as it is a bug with that person's example code
