### ISSUE TITLE
Enter/tab don't work as delimiters for dropdown position 'manual'

### ISSUE THREAD

**Issue by ipd39952** [yairEO/tagify#1103]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/kepanadope/edit?html,js,output

### Explanation

- **What is the expected behavior?**
When setting the dropdown position to 'manual', writing a custom tag and pressing tab/enter should work as a delimiter. 

- **What is happening instead?**
Pressing tab/enter doesn't do anything. Commas still work as delimiters by default 

- **What error message are you getting?**
No error message

**This is also the case for the official example for the dropdown with position manual, not sure if this is the intended behavior.** 
https://yaireo.github.io/tagify/#section-manual-suggestions

**Comment by ipd39952** [comment]
@yairEO Thank you for the fix and for making such a useful package :raised_hands: :rocket:

**Comment by yairEO** [comment]
Thank you @ipd39952 for using it!
