### ISSUE TITLE
React tag template is not interactive

### ISSUE THREAD

**Issue by SzymonTMeniga** [yairEO/tagify#1105]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/TagifyWithTemplates.jsx

### Explanation

- **What is the expected behavior?**

It should be possible to use React components within the template and preserve their behaviour **OR** the demo page should be annoteded, listing the limitations, because it's misleading

- **What is happening instead?**

Because templates are stringified using https://reactjs.org/docs/react-dom-server.html#rendertostring in this method https://github.com/yairEO/tagify/blob/master/src/react.tagify.js#L14-L25, React components are no longer interactive - i.e. they will render correctly but events won't work, e.g. onClick, onHover...

- **What error message are you getting?**
None

- **Is there a workaround?**
I could call React.hydrateRoot on the element generated by the template just after it was rendered, but AFAIK there's no setting to override parseTemplate method. 

I'd love to be able to override parseTemplate.

**Comment by yairEO** [comment]
How does overriding `parseTemplate` helps?

Tagify is a vanilla-based component with a React wrapper which just is only mainly for JSX purposes, so developers could write declarative code.

There is a solution for everything, please explain what is your end-goal here, with having the template components with logic?

**Comment by SzymonTMeniga** [comment]
The endgoal here would be to use interactive React components within the tag template. That's impossible currently - the React components loose interactivity due to `renderToStaticMarkup()`. This is done because every template

**Comment by yairEO** [comment]
Yes I know all this, but what is the endgoal for you? Give me a concrete example of why you must have this supported.

This is impossible to achieve in Tagify because it is not written in React, and so I must know why is this so important. I need to know all the possible exact use cases, highly detailed, so I could determine if it's work me working ~100 hours on this...

**Comment by yairEO** [comment]
Closed as stale
