### ISSUE TITLE
About licensing

### ISSUE THREAD

**Issue by flyingatm** [yairEO/tagify#1107]
Hello there! Thank you for this nice library! I'm a JS and PHP developer and I'm coding a WordPress Social Media theme and it's about to end. I was looking for alternative library for my mention and hashtag system and found your project.

I wanna use this library in my theme that will be selled to the multiple clients on the Theme Forest market.

Am I able to do that?

Thank you!

**Comment by yairEO** [comment]
Ok, you can do that
