### ISSUE TITLE
Cursor position after adding a tag using mix mode

### ISSUE THREAD

**Issue by paourissi** [yairEO/tagify#1109]
Hi,

after adding a tag using mix mode, the cursor position is placed in the beginning of the input field, using mix mode.

Easily reproduce in the Mix mode section from your demo https://codesandbox.io/s/tagify-react-wrapper-oempc

Thank you

**Comment by yairEO** [comment]
You mean `caret`, not `cursor` (which is your mouse pointer)

**Comment by yairEO** [comment]
OK I see now, it only happens when using the mouse to select the suggestions (which I never do, as I use the keyboard only)

**Comment by paourissi** [comment]
Will this be fixed soon?

**Comment by yairEO** [comment]
yes, why? is this urgent?

**Comment by paourissi** [comment]
Kinda is, but this doesnt affect you. 
I hope that it will be fixed soon because its something that should be working, its an obvious functionality to put the cursor at the end of something you add in an input.

**Comment by Galexy5** [comment]
The bug is valid and it is a little annoying because it should follow the keyboard behaviour (the mouse pointer should not go to the start). I hope it will be fixed soon because I also need to implement it to one of my projects.

**Comment by yairEO** [comment]
It will be fixed today
