### ISSUE TITLE
Hover shadow too small for given inset

### ISSUE THREAD

**Issue by Massi-X** [yairEO/tagify#1110]
Hi, hovering over a tag result in a small empty line in the middle of the tag (see picture).
![pic](https://user-images.githubusercontent.com/7504132/188016617-f9cdffa5-385e-4dfa-8942-05820f22c0f8.png)
This is caused by the insets being too big or box-shadow being too small.

Increasing the value of `-tag-inset-shadow-size` to `-tag-inset-shadow-size: 1.3em` is enough to fix the issue.
Using Chrome on MacOS Monterey.

**Comment by yairEO** [comment]
This is only happening on your computer...and you can edit the CSS to fit your specific needs/OS setup

Check if you have any zoom or enlarged fonts in your OS

**Comment by Massi-X** [comment]
Nope the computer is not really the problem, maybe is caused by other css styling of the site I'm injections this into? Even if I don't see how it can happen

**Comment by yairEO** [comment]
You can simple adjust Tagify's CSS to match your specific needs, since I cannot change it for yours because I don't see
an issue with the internal shadow's size on my computer (with the default set up)

**Comment by Massi-X** [comment]
Ok I found the cause, the body font was set to a custom one (I don't remember exactly what it is, but if you need it I'll tell you).
This is probably bigger at the same font-size causing the little glitch. So really you should just set your preferred font in the css to avoid this, and if the user wants to change it at least he knows what has caused the glitch.

**Comment by Massi-X** [comment]
Ok I found the cause, the body font was set to a custom one (I don't remember exactly what it is, but if you need it I'll tell you).
This is probably bigger at the same font-size causing the little glitch. So really you should just set your preferred font in the css to avoid this, and if the user wants to change it at least he knows what has caused the glitch.

**Comment by Massi-X** [comment]
Ok I found the cause, the body font was set to a custom one (I don't remember exactly what it is, but if you need it I'll tell you).
This is probably bigger at the same font-size causing the little glitch. So really you should just set your preferred font in the css to avoid this, and if the user wants to change it at least he knows what has caused the glitch.

**Comment by yairEO** [comment]
enforcing a font for a 3rd-party component is not a good practice. 
Fonts should match across the app, with inheritance.

**Comment by Massi-X** [comment]
Yeah I know I intended to put it in css value like the colors. If you think is not the case it should be written somewhere for future reference don't you think?

**Comment by yairEO** [comment]
Nah it's OK, don't worry about it too much. Nobody hardly asks this for the past 5 years, and popularity is high, so I assume developers know how to adjust Tagify to fit their website/app style. I mean, you don't just simply use it as-is, it will not fit the overall look & feel if your project anyway

**Comment by Massi-X** [comment]
Ok then! 😉
