### ISSUE TITLE
Tags not added sometimes

### ISSUE THREAD

**Issue by visualight** [yairEO/tagify#1112]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hello @yairEO !

Sometimes tags are not added to the input.
I searched and I can't find why.

Tagify performs a database fetch to retrieve cities, towns, provinces and postal codes.

The search is executed after 2 characters.

The tags are added well in general but it happens that these are not added. If I try again those that do not add, they end up being added to the input.

```
enforceWhitelist:true,
createInvalidTags:false,
skipInvalid:true,
editTags:false,
pasteAsTags:false
```

Here is an exemple of the server side response

```
$zip = '4000';
$cities = implode(', ', $cities);
$response[] = [
  'id' => [1,2,3],
  'type' => 'Province',
  'label' => $city.' (Province)',
  'value' => $cities.' ('.$zip.')',
  'postcodes' => [$zip]
];
```

Here is a GIF explaining the problem and a jsFiddle.
https://jsbin.com/sunuzucoyu/edit?html,js,output

![Mon film 6](https://user-images.githubusercontent.com/3457651/188211776-068c6f42-b473-43c7-8d4a-0ad158019a72.gif)

**Comment by yairEO** [comment]
Your jsbin demo does not work. Please create a realistic server mocking using promises and fake random delays and make it work so I could examine the problem. I cannot begin to try and fix this without carefully examining a working flow

**Comment by visualight** [comment]
> Your jsbin demo does not work. Please create a realistic server mocking using promises and fake random delays and make it work so I could examine the problem. I cannot begin to try and fix this without carefully examining a working flow

Thanks for the reply.
Working DEV server : [shorturl.at/fhSTU](http://shorturl.at/fhSTU)

**Comment by visualight** [comment]
> Your jsbin demo does not work. Please create a realistic server mocking using promises and fake random delays and make it work so I could examine the problem. I cannot begin to try and fix this without carefully examining a working flow

@yairEO  : Here is a functional JS Fiddle : https://jsbin.com/zudubey/edit?html,js,console,output
Thank you for your support ! ;-)

**Comment by yairEO** [comment]
I've tried adding many many tags (in your **jsbin** demo) and it always works...

Also, why did you write your own `dropdownItem` template if it's the same as the default?

And why do you need all these...?

```js
tagify.on('add', function(e){
  if(tagify.listeners.dropdown) {
    tagify.whitelist = null;
  }
});


tagify.on('remove', function(e){
  tagify.whitelist = null;
});

tagify.on('blur', function(e){
  tagify.whitelist = null;
});
```

**Comment by visualight** [comment]
Indeed, my apologies ... today everything works. In my opinion a Bug in the cache of Safari. After restarting the computer everything seems to be working fine. I didn't think to test with another browser.

I use the on add and on remove methods to add and exclude id's from the database fetch (I didn't mention this feature in the demo). Incidentally, I reset the whitelist to prevent the data from remaining cached in the dropdown.

I also reset the whitelist if the input loses focus so as not to keep a cache in the dropdown.

I'm using a custom template to group dropzone items with an "optgroup".

Is there another more suitable method?

Thanks

**Comment by yairEO** [comment]
You can delete the `dropdownItem`, it has nothing to do with the "groups" you're creating, trust me

**Comment by visualight** [comment]
Thanks a lot YairEO !
