### ISSUE TITLE
BeforeRemoveTag fails if combined with single-value mode

### ISSUE THREAD

**Issue by Massi-X** [yairEO/tagify#1113]
``## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/jozesasopa/edit?js,console,output

### Explanation
When in single-value mode (or select if you prefer) with `enforceWhitelist=true` I would like to avoid to have the ability to leave the input empty; it should always be set to some value (like a real select).
Because I don't see any other way I used an hook to reject the deletion, it does work fine but the text is deleted anyway no matter what.

There should be a fix for this or even better when in this mode a value should always be required to avoid leaving the input empty (and so avoid backspace and remove the 'x' button).

EDIT: To point out why it works fine, I see that by sending the form the value is indeed there and not deleted.
EDIT 2: Just to add another thing, a workaround is to use
```
callbacks: {
	remove : (e) => {
		e.detail.tagify.addTags(e.detail.data.value);
	}
}
```

**Comment by yairEO** [comment]
Here you go:

https://jsbin.com/gikokox/1/edit?html,css,js,output
