### ISSUE TITLE
Disable the automatic filtering in whitelist

### ISSUE THREAD

**Issue by paourissi** [yairEO/tagify#1114]
As you can see in the mix-mode demo https://codesandbox.io/s/tagify-react-wrapper-forked-2ifhwp

When typing @ and start writing, the list will automatically be filtered with what iam typing. When using api requests the filtering is handled by the service itself and just returns the filtered data based on what we typed after the @. So as you can see there is no need for the dropdown to be filtered further.

Is there a way to disable the automatic filtering in the dropdown in react?

**Comment by yairEO** [comment]
You can replace the prototype method which does the filtering with your own:

```js
tagify.dropdown.filterListItems = (value, suggestions) => suggestions;
```

**Comment by paourissi** [comment]
And how do you do that when using react?

**Comment by yairEO** [comment]
This is how you can do it in *React*.:

https://codesandbox.io/s/tagify-1114-disable-the-automatic-filtering-in-whitelist-6ekx7w?file=/src/index.js:982-1042

I think its better I will add some option to disable it, for an easier way
