### ISSUE TITLE
On Firefox, When a selection already exists, newly created tagify elements may gain focus even if autofocus is not on

### ISSUE THREAD

**Issue by CarlosFdez** [yairEO/tagify#1115]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/havucusasu/edit?html,js,output
(make sure not to touch anything while its going, it needs to try to steal focus)

### Explanation
On Firefox (not Chrome), newly created tagify elements with existing values autofocus even if autofocus is currently disabled, so long as an already existing selection exists on the screen. This causes the dropdown to sometimes show up spontaneously while interacting with other elements.

From digging into the codebase, the root cause seems to be setRangeAtStartEnd() when called via addTags(). On Firefox, executing setStart() on a contenteditable span seems to cause it to gain focus. setRangeAtStartEnd() checks for the existance of a selection, but it should probably either not call it when its not supposed to auto focus, or make sure that the selected element is the same as the node.

I plan to work around it in the interim by calling blur on the element right after creating it.

**Comment by yairEO** [comment]
Interesting. I will examine, thanks for letting me know

**Comment by CarlosFdez** [comment]
Thanks for examining. As a heads up, I'm getting the issue on Chrome too (well, electron client), but less rarely. There are certain times when the dropdown opens suddenly when clicking around, and does not disappear until you refocus the input and then click away again. But I can't figure out how to reliably reproduce, hopefully its related to whatever caused this one :(

**Comment by yairEO** [comment]
Yeah, I've also seen these weird thing happening when the dropdown suddenly shows up when clicking outside.

I need to investigate more on this, as it is indeed rare
