### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by wabgy** [yairEO/tagify#1117]
Hello, I have the following questions for you

1. How to avoid entering commas and becoming labels?

2. When editing a label, if the rules are not met, how to control that only the current label can be edited, and the input focus will not disappear, and will always be on the currently edited label. And prohibit adding new tags?

3. When inputting text and obtaining a white list, how can I request an interface after inputting a complete word?

Please explain it to me. Thank you~

**Comment by wabgy** [comment]
First of all thanks for your reply,
Sorry, the third issue above has been resolved.
1. The second question above is to know, how to edit the tag, the current content does not conform to the specification, I want to limit only the current tag to be repaired, but not to edit other or add new tags?
2. The default value of the delimiter is a comma. How to set without specifying the delimiter?
3. How to prevent the copied content from automatically becoming a tag?

**Comment by yairEO** [comment]
1. So the user can only edit what's invalid but cannot do nothing else (add/remove or edit valid tags)?
2. Try an empty value for the `delimiters` setting `delimiters: ''`
3. what do you mean `copied`? you probably mean `pasted`...?

**Comment by wabgy** [comment]
Hello,
1. The first question you understand is correct. Can this be done?
2. I set delimiters like this: '', but it doesn't take effect. The input content will appear and immediately become a tag.
3. The third question is pasting. How to prevent the pasted content from becoming a tag?

**Comment by yairEO** [comment]
Hi, sorry for the delay, I was on vacation and also did other things.

You've raised some tough questions...

> The first question you understand is correct. How to control can only edit invalid content, but not do anything else (add/remove or edit valid tags)?

Currently impossible

> How to set the switch between read-only and edit state of a tag?
For a single tag, you would have to devise your own solution, for example, some icon
inside the tag, and detect when the user clicks on it 
and then you would need to update the tag's data and apply DOM changes manually:

```js
tagify.on('click', e => {
  const {data, tag, event} = e.detail;
  
  if( event.target.matches('.toggle-readonly-btn') ) {
    // flip the "readonly" tag data property and re-save the whole data
    tagify.tagData(tag, {...data, readonly: !data.readonly}) 
    
    // update DOM
    if( data.readonly )
	    tag.removeAttribute('readonly')
	else 
        tag.setAttribute('readonly', 'readonly')
  }
})
```


> I set delimiters like this: '', but it doesn't take effect. The input content will appear and immediately become a tag.
I don't understand your use case. please explain how should the user type something and at what point should it become a tag.

> The third question is pasting. How to prevent the pasted content from becoming a tag?
Why would you prevent pasting if you're not preventing typing? or is typing also not allowed? if so, when?

> When the tag is verified during the editing process, the focus of the input box will disappear. How to solve this?
Please write detailed steps-to-reproduce
