### ISSUE TITLE
Mixed mode submit on enter key

### ISSUE THREAD

**Issue by eugene-makarov** [yairEO/tagify#1118]
I'm using mixed mode with textarea and I'm trying to submit a form on Enter key. Unfortunately, the value is updated with a delay so instead of clearing the value.. I end up having it with a new line. (I'm using vue v-model)

Trying to think about workaround... but ideally I would want to preventDefault for keydown "Enter" key. 

Flow:
1. user presses enter while focused in the textarea
2. onKeyDown submits and clears the value
3. the value is set back to what it was + new line

PS. setTimeout doesn't help unless it's ~300ms, but then it looks weird.
PSS. I need to use keydown to confirm shiftKey wasn't pressed, otherwise I'd allow user to add new line

**Comment by yairEO** [comment]
Maybe [this basic example](https://jsbin.com/sukiceb/edit?html,js,output) can help, but you need to convert it to *Vue* code:

```js
var input = document.querySelector('input')
var tagify = new Tagify(input, {
  mode: 'mix',
})

tagify.DOM.input.addEventListener('keydown', e => {
  if( e.key == "Enter" ) {
    e.preventDefault();
    // submit...
  }
})
```

**Comment by eugene-makarov** [comment]
Thank you, this works very much. Maybe you could add this solution here as well? https://github.com/yairEO/tagify#:~:text=Submit%20on%20%60Enter%60%20key
