### ISSUE TITLE
updateValueByDOMTags is not a function

### ISSUE THREAD

**Issue by slugb0t** [yairEO/tagify#1119]
## Prerequisites

- [] I am running the latest version ( dragsort@1.3.1 & tagify@3.25.0)
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- **What is the expected behavior?**
I am using Tagify's DragSort library and included in the example was a function to update the DOM when rearranging tags
updateValueByDOMTags()

- **What is happening instead?**
Nothing

- **What error message are you getting?**
updateValueByDOMTags is not a function

**Comment by yairEO** [comment]
You mean [this method](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L645)

Your jsbin demo link seems to be the default from the template. Is this a React-specific question?

**Comment by slugb0t** [comment]
The example provided for using drag and sort had this:
`var tagify = new Tagify(inputElement)

// bind "DragSort" to Tagify's main element and tell
// it that all the items with the below "selector" are "draggable"
var dragsort = new DragSort(tagify.DOM.scope, {
    selector: '.'+tagify.settings.classNames.tag,
    callbacks: {
        dragEnd: onDragEnd
    }
})

// must update Tagify's value according to the re-ordered nodes in the DOM
function onDragEnd(elm){
    tagify.updateValueByDOMTags()
}`

What I had to do to get it working in my case was place onDragEnd() within new Dragsort
I created a function that would do this for me when I passed the tagify element.
`const createDragSort = (tagify) => {
  const onDragEnd = () => {
    tagify.updateValueByDOMTags();
  };
  new DragSort(tagify.DOM.scope, {
    selector: "." + tagify.settings.classNames.tag,
    callbacks: {
      dragEnd: onDragEnd,
    },
  });
};`

Thank you for the response though!
