### ISSUE TITLE
this.tagify.settings.editTags = null

### ISSUE THREAD

**Issue by wabgy** [yairEO/tagify#1120]
### **Hello, after setting this.tagify.settings.editTags = null, click on the tag to report an error:**

> tagify.js:formatted:998 
> Uncaught TypeError: Cannot read properties of null (reading 'keepInvalid')
>     at M.onEditTagBlur (tagify.js:formatted:998:44)
>     at tagify.js:formatted:1457:57
> onEditTagBlur @ tagify.js:formatted:998
> (anonymous) @ tagify.js:formatted:1457
> setTimeout (async)
> (anonymous) @ tagify.js:formatted:1457
> 
> tagify.js:formatted:920 
> Uncaught TypeError: Cannot read properties of null (reading 'clicks')
>     at M.onClickScope (tagify.js:formatted:920:68)

### **It is recommended that editTags.clicks can set additional values, and the control tag cannot enter edit-mode.**

**Comment by yairEO** [comment]
Have you tried setting it to `false`?

**Comment by wabgy** [comment]
Set to false, the non-editable function is invalid

**Comment by yairEO** [comment]
what does *"non-editable function is invalid"* means? nothing in this sentences is understandable to me :)

**Comment by wabgy** [comment]
Setting it to false didn't prevent it at all, still entering edit mode

**Comment by yairEO** [comment]
> Setting it to false didn't prevent it at all, still entering edit mode

https://jsbin.com/bogoneq/edit?html,js,output
