### ISSUE TITLE
Dropdown list position changes when selecting a value

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#1121]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

https://user-images.githubusercontent.com/2200491/189266712-df5e05d3-4993-4e20-a0b9-7ef6feb07a45.mov

When trying to select a value, the dropdown initially shows below but when the mouse moves to the dropdown list, it changes to top as there is more space. Wondering if it is possible to open the dropdown in the top position rather than doing it as soon as the user tries to select from the list.

**Comment by yairEO** [comment]
Well, you didn't show the whole viewport in your video but Tagify tried to fit the dropdown below the field (by default) and when you hovered it (with the mouse) then it re-positioned itself above it, so I assume this is a very specific situation where your page's scrollbar is at a specific place that barely gives Tagify space below and for some reason it thinks it can fit, when it actually cannot.

That's my guess, since the video is cropped.

**Comment by dirslashls** [comment]
Thanks @yairEO . I looked it in more detail and this is happening for the specific case I am trying to solve. Right now when tagify is displayed, the dropdown is open but the input field is not focused. To get the cursor at the end of the text in the input field, I do the following

```js
const input = this.#tagify.DOM.input;
const caret = document.createRange();
const sel = window.getSelection();
caret.selectNodeContents(input);
caret.collapse(null);
sel.removeAllRanges();
sel.addRange(caret);
```

This causes a focus even which triggers a show before the dropdown initialization is complete.

1. At https://github.com/yairEO/tagify/blob/6442a5967c6a515dcd6a4d18d620161c16ceffc6/src/parts/dropdown.js#L210

there is logic to add dropdown into the DOM. But before appending, a initial class is added whose max-height is 20px.
Then the initial class is removed within setTimeout. In addition, because the size is 20 with initial, the actual dropdown height is obtained explicitly and is used that for the position call which works.
2. But when a focus event is fired, show is called and this does a position call which doesn't pass the dropdown height.
https://github.com/yairEO/tagify/blob/6442a5967c6a515dcd6a4d18d620161c16ceffc6/src/parts/dropdown.js#L131

Wondering if there is a callback option that can be used to position the cursor after the dropdown is already being displayed.

**Comment by yairEO** [comment]
Why do you care about the caret position if the user will select a new value which will replace the current one?

You can use [`tagify.setRangeAtStartEnd.call(this, false)`](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L660) to place the caret at the end of the input, and you should call this probably when the `dropdown:show` event triggers

**Comment by dirslashls** [comment]
Thanks @yairEO . For some reason the above workaround didn't work. However, I managed to get the desired outcome using the following

```js
const position = tagify.settings.dropdown.position;
try {
	tagify.settings.dropdown.position = 'manual';
	tagify.DOM.input.focus();
	(tagify as any).setRangeAtStartEnd(false);
} catch(ex) {
	Console.debug(ex);
} finally {
	tagify.settings.dropdown.position = position;
}
```
