### ISSUE TITLE
Using whitespace as delimiter leads to unexpected result

### ISSUE THREAD

**Issue by zipprich** [yairEO/tagify#1124]
After updating from version 4.9.8 to 4.16.4 the behavior of whitespace characters as tag delimiters has changed. New tags now are created when inserting the first characte after the whitespace.
### 💥 Demo Page
https://jsbin.com/vujavaz/edit?html,js,output

(your example from #559)

### Explanation

- **Expected** A Tag should be created when a whitespace character is inserted

- **What is happening:** Nothing at first, the next inserted character will create the tag and will become a tag on it's own

**Comment by yairEO** [comment]
Duplicate of https://github.com/yairEO/tagify/issues/1026#issuecomment-1161684105
