### ISSUE TITLE
Paste does not execute input event

### ISSUE THREAD

**Issue by wabgy** [yairEO/tagify#1125]
Hello, the pasted content does not execute the input event, but delete the pasted content but execute the input event.
Is there an event handler that listens for paste? Please give pointers, thank you

**Comment by yairEO** [comment]
You can either use the [`beforeRemoveTag` hook](https://github.com/yairEO/tagify#hooks) or the `change` event listener:

https://jsbin.com/ligaqiq/2/edit?html,js,console,output

**Comment by wabgy** [comment]
Using the beforeRemoveTag hook, I want to process the format of the pasted content. Is there such a method?
