### ISSUE TITLE
Extract vue and react version to seperate packages

### ISSUE THREAD

**Issue by tobiasdiez** [yairEO/tagify#1126]
Currently, the vue and react parts are simply exported to `dist` which makes for rather awkward imports such as 
```ts
import Tags from "@yaireo/tagify/dist/tagify.vue"
import Tags from "@yaireo/tagify/dist/react.tagify"
```
Instead, I would propose to create new packages that encapsulate these. So for example, one could have
```ts
import { Tags } from "@yaireo/vue-tagify"
import { Tags } from "@yaireo/react-tagify"
``` 
Also has the advantage that one could properly declare dependencies (e.g. currently one has prop-types as peer dependency, but this is react-specific). (You don't have to split the repository, one common mono-repo approach is to have a `packages` folder, with each package being a subfolder there, i.e. `packages/vue`, `packages/react` and `packages/core`.)

This was triggered by https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62368#discussioncomment-3708286

**Comment by yairEO** [comment]
Good suggestion!
I don't even know how to start such a thing. Is there a good article for such a basic setup?

**Comment by tobiasdiez** [comment]
I have to admit that I don't have any experience with this myself. But based on what I've seen, you can start with yarn workspaces and setup publishing etc yourself. Or use build tools such as https://lerna.js.org/ which add additional convenience on top of workspaces.

**Comment by yairEO** [comment]
Yarn is very old and lerna is also very old, I used to work with them many years ago.

Today I work with `pnpm` and for monorepo you have `turborepo`. Lerna is very old and nothing something anyone is using for years now..

**Comment by johan-weitner** [comment]
I noticed this thread is quite old, but I agree about Turbo and pnpm, they're both no-brainers in 2024. I could take a stab at setting it up, if you're open for pull requests? I would leave the existing code where it is and deprecate it, so as to not introduce a breaking change.

**Comment by yairEO** [comment]
@johan-weitner - I don't see a reason anymore because the imports are quite short, unlike OP claims back in 2022:

```js
import Tags from '@yaireo/tagify/react'
```

I don't see a need to separate the codebase because the React wrapper is only but a thin layer and the Vue wrapper is extremely tiny.

**Comment by tobiasdiez** [comment]
@yairEO the imports for vue didn't change. Moreover, the react dependencies are still there (https://github.com/yairEO/tagify/blob/d19f246256eb41827b7eb30a97b57255f0f5745e/package.json#L71-L72), although in a vue project one would never use them.

**Comment by yairEO** [comment]
The import for the `vue` wrapper has indeed changed by me yesterday:

https://github.com/yairEO/tagify/blob/master/package.json#L56

```
"./vue": "./dist/tagify.vue",
```

So you can now import it from `@yaireo/tagify/vue`.

the "react" dependency is a **peer** dependency. it is not installed and is optional, so in a Vue project it is disregarded.

It is required for the React wrapper, but since I don't know *Vue* at all and its wrapper is only a few lines long, I think there is no need for a peer dependency for Vue.

If you think there is a need and you know *Vue* and can help with improving how Tagify works in Vue I will be very happy to hear your wisdom! ❤️️

**Comment by tobiasdiez** [comment]
> So you can now import it from `@yaireo/tagify/vue`.

Thanks this is already an improvement.

> the "react" dependency is a **peer** dependency. it is not installed and is optional, so in a Vue project it is disregarded.

Peer dependency are not optional; package managers will complain about unsatified peer dependencies (there is however peerDependenciesMeta to improve the situation).

> It is required for the React wrapper, but since I don't know _Vue_ at all and its wrapper is only a few lines long, I think there is no need for a peer dependency for Vue.

A peer dependency on Vue is needed for the same reason as the react peer dependency. It tells users of the package what version of vue/react they need to have installed in order to use the component in their apps. I agree, the vue component is simple enough and thus requiring a sufficient recent vue (perhaps `vue >= 3.0.0) should be okay.

> If you think there is a need and you know _Vue_ and can help with improving how Tagify works in Vue I will be very happy to hear your wisdom! ❤️️

I still think three packages would be best:
- core
- react: dependency on core + react
- vue: dependency on core + vue

if you prefer one could also setup the build-process to inline the code from core so that you would not need to ship it.

I think https://github.com/wobsoriano/vue-sfc-unbuild is a good start for the vue library, and would give support to a few things that are currently missing (registration of the vue component in the vue app, built pure-js component not a vue sfc, typescript support etc). I can help with setting this is up if you want.

**Comment by yairEO** [comment]
I will ponder heavily on what you've said here
