### ISSUE TITLE
Quickly click to delete tag, there is a bug

### ISSUE THREAD

**Issue by wabgy** [yairEO/tagify#1127]
Hello, there are the following two bugs
1). When entering the edit mode, change it to clicks: 1, enter the number 1, 2 becomes two tags, and quickly click the delete button, there is a chance to trigger the edit:start event method, and enter the number 1 or 2 again, it becomes Can't tag.
2). Double-click the input box, the console will prompt the message 'tag element doesn't exist'.
please verify, thanks!

Sorry I don't know how to upload the video.

[https://jsbin.com/becapidoqi/edit?js,console,output](url)

**Comment by yairEO** [comment]
sorry but I don't understand

**Comment by yairEO** [comment]
I've tried so many times to delete as fast as I could but I could not reproduce the bug (in your JSBIN)

**Comment by yairEO** [comment]
@LucasCardoso-LC - please upload a video but I cannot reproduce this at all... I've tried adding several tags and holding the <kbd>BACKSPACE</kbd> key and it always perfectly removes them all and the value of the original input is in-sync.

**Comment by SongTeaheon** [comment]
I have also reproduced the issue and I am experiencing a similar problem.

Here is the issue I am facing:

When I quickly perform the following two steps after entering "1", the UI reflects both events, but the actual value change from the first event (deleting "1") is ignored.
- First event: Delete "1".
- Second event: Paste another value using cmd + v.

(Although the situation is different from the initially reported issue, both problems shows that the value change from the first event is ignored.)


https://github.com/yairEO/tagify/assets/39703207/757b520e-e21e-4780-a250-f0d29126f267

**Comment by yairEO** [comment]
@SongTeaheon - thanks! that helped a lot, now I can reproduce it. I will create a fix shortly.
