### ISSUE TITLE
Can't access the value of tagify objects

### ISSUE THREAD

**Issue by Tch4lla** [yairEO/tagify#1128]
I am creating a form and sending tagify tags to my database. When I try to access the values from the tags. I get undefined 

To send the data to my database, I created a schema `tag: mongoose.Schema.Types.Mixed` This makes that part appear in my db as 
`tag: "[{"value":"randomTagName"},{"value":"anotherRandomTagName"}]"`

When I `console.log(req.body.tags)` the same thing is returned. But when trying to console.log the values using , console.log(`req.body.tags[0].value)` It's undefined. Why is this the case?

**Comment by yairEO** [comment]
I need to the the code. it's impossible to help with out. Also you are asking a backend-related question which is out of the scope for help in Github. You can try asking in Stackoverflow

**Comment by yairEO** [comment]
Closing as OP is unresponsive
