### ISSUE TITLE
Edit mode accepts html pasted content

### ISSUE THREAD

**Issue by adrienWeiss** [yairEO/tagify#1131]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jasilegera/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Pasting in edit mode should paste text-only 

- **What is happening instead?**
Content is pasted as rich / html (see demo)

This is probably the side-effect of using contenteditable on the edit mode element. As far as I know I cannot access the `clipboardData` in `event.detail.originalEvent` from the `edit:input` event so I cannot fix this on my side.

Thank you again for your work

**Comment by yairEO** [comment]
Tagify is automatically stripping away pasted HTML content, but maybe I've forgotten to do so inside an edited tag.

https://github.com/yairEO/tagify/blob/master/src/parts/events.js#L713-L729

The paste event is only handled for the `input` element (which hosts all the tags) 

https://github.com/yairEO/tagify/blob/master/src/parts/events.js#L65

And is not binded when editing a specific tag:|
https://github.com/yairEO/tagify/blob/master/src/tagify.js#L532-L537

I will remedy this.

**Comment by adrienWeiss** [comment]
Thank you @yairEO 
if I may, rather than stripping HTML, I personally think it's best to hijack the paste event and retrieve the pasted content with `clipboardData.getData('text/plain')` but I may be overlooking some use cases
