### ISSUE TITLE
Mix Text & Tags show list without a pattern

### ISSUE THREAD

**Issue by paourissi** [yairEO/tagify#1132]
Can we somehow show the list of possible options when the user types without the need of entering a pattern.
Basically, every time the user types, can we show the list?

This is needed to a customer's project of mine. Thank you.

**Comment by yairEO** [comment]
I have no idea what you are talking about. You must be extremely specific and supply with a jsbin demo, as instructed in the *issue template* (which you have deleted)

**Comment by paourissi** [comment]
No need to provide a demo things are very clear.

Here in your MixedModeTagify, in line 8 it says:  pattern: /@/, // <- must define "patten" in mixed mode.

What am i asking is:

Is it possible to  just show the whitelist when user types without typing any pattern like @?

**Comment by paourissi** [comment]
That might work. Thanks
