### ISSUE TITLE
Allow using Space key like Enter

### ISSUE THREAD

**Issue by eugene-makarov** [yairEO/tagify#1133]
I'd like to use Space key to add a selected tag from a dropdown. So basically it would behave exactly the way Enter does. I'm curious if it's something easy to add as a feature?

We are using Tagify for @mentions with an enforced whitelist.

**Comment by yairEO** [comment]
While it is kind of easy to add as a feature, I would say it's not common to use <kbd>Spacebar</kbd> and not <kbd>Enter</kbd>. Why is it so important?

**Comment by eugene-makarov** [comment]
Our UX team provides JIRA as an example - they do add a mention on spacebar press. I think in our case, because we also use space as "delimiters" for hashtags, a user might be expecting space to also add mentions.

If this doesn't sound like a good feature, I'll try to do a workaround with capturing spacebar keydown event.

**Comment by yairEO** [comment]
You want the user to use the keyboard up/down arrows to move between the suggestions in the dropdown list and then hit <kbd>spacebar<kbd> to select one, correct?

**Comment by yairEO** [comment]
Listening to the `keydown` event won't help you because the Tagify's method which handles the dropdown selection is inaccessible from outside. I would have to modify the code for you to be able to call it:

https://github.com/yairEO/tagify/blob/master/src/parts/dropdown.js#L443-L464

**Comment by eugene-makarov** [comment]
Correct. However, I understand that this is not common. I'm also asked to autocomplete the tag on comma, period, tab. A solution that works for me is capturing keydown and adding tags manually. I would side with your first reaction - no need to introduce extra complexity because it's not common.

```
// simplified version of my code

tagify.DOM.input.addEventListener("keydown", onKeyDown);

if (e.code === "Space) {
  e.preventDefault();
  tagify.addTags([ tagify.suggestedListItems[0] ]);
}
```

**Comment by yairEO** [comment]
Tagify has built-in event listeners all described in the README, so you should not write this:

`tagify.DOM.input.addEventListener("keydown", onKeyDown)` as this is a hacky code, and instead do:

```js
tagify.on('keydown', onKeyDown)
```

**Comment by eugene-makarov** [comment]
I think I had to do it that way in order to call `event.preventDefault()`. Otherwise it's not an actual "event".

**Comment by yairEO** [comment]
why call `event.preventDefault()`?

**Comment by eugene-makarov** [comment]
Otherwise it was adding new line/space to value when user tried to submit form/autocomplete tag or mention. Perhaps this could is caused by our Vue implementation...

**Comment by RANSUROTTO** [comment]
I had the same problem and couldn't prevent Enter from being typed. It was implemented after changing the listening object through your code, thank you.
