### ISSUE TITLE
Library is not supported on browser Chrome version < 80

### ISSUE THREAD

**Issue by Levon930** [yairEO/tagify#1135]
## Prerequisites

- [x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- **What is the expected behavior?**
It should work on browser version which is less than 80 but actually does not work as the operator "?" in test?.examples  is not supported by lib. How can I bypass this or could you please resolve this issue ?
- **What is happening instead?**
"?" operator should work but instead it does not understand that there is such a thing
- **What error message are you getting?**
Unexpected token

**Comment by yairEO** [comment]
This is not an Issue with Tagify but with your build system, as it should transpile/polyfill 3rd-party code to your desired target browsers (taking browser API limitations into consideration).

If you use Babel, you should make sure to use the correct version of [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env) as it should automatically transpile `optional-chaining`

**Comment by yairEO** [comment]
Related to https://github.com/yairEO/tagify/issues/1093
