### ISSUE TITLE
[MixMode] - Caret position is so closer to the TAG when focusing the textArea

### ISSUE THREAD

**Issue by mezzouhri** [yairEO/tagify#1137]
## Prerequisites

- [] I am running the latest version
   I am running this  version : "^3.25.0"
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codepen.io/nokwiw/pen/jOxdLYy

### Explanation

- **What is the expected behavior?**
- should have a space between the TAG and the caret position when the textArea is focused

- **What is happening instead?**
 Everytime the textArea is focused the caret position is too closer to the TAG. Is there any solution to fix this problem, please ?

Note that happens just with the TAGS that are loaded with the textArea... when I add a new TAG, it works as expected and I have a space between the new TAG and the caret position when I focus the textArea. 
Video description here : https://youtu.be/UvLIwiqnV18

Thanks for help

**Comment by mezzouhri** [comment]
Hi, any response please ?

**Comment by yairEO** [comment]
Sorry I was on vacation. I will try to address the issue this week

**Comment by mezzouhri** [comment]
Hi, have you any news, please ?

**Comment by yairEO** [comment]
Ha I forgot about this, I will investigate today

**Comment by mezzouhri** [comment]
Thank you for handling this bug,
but for me, I use this version "3.25.0", could you tell me how can I fix this problem without MAJ  the version, please ?

**Comment by yairEO** [comment]
what is `MAJ`?

You don't you want to upgrade? I constantly fix bugs and you'll miss all the goodies

**Comment by mezzouhri** [comment]
MAJ == upgrade,
I can't update to the last version, my app doesn't support it, I have somme error msg about chaining operator when using the last version (it's another problem...).

the 3.25.0 work fine for my except this bug.
