### ISSUE TITLE
After ingresing tags, my event stops triggering

### ISSUE THREAD

**Issue by AlbertoVargasMoreno** [yairEO/tagify#1139]
## Prerequisites

- [x] I am running the latest version, I'm using the CDN provided in the README
- [x] I checked the documentation and found no clue about the topic
- [x] I searched through the issues and coudn't identify something helpful

I am putting an input that uses tagify inside a form, this input is using attributtes: placeholder and pattern, the pattern validates that the tags have the email address structure; I setted a submit event listener. And there's a behaviour from which I have no clue how to debug.

### Demo Page
https://jsbin.com/dafanolave/1/edit?html,js,output

Flow (case 1):
1. I enter text in the inputs, except the one that uses tagify
2. Submit the form
3. The submit event handler works as expected

Flow (case 2):
1. Enter data in the inputs
2. Write some tags, in the tagify input
3. The submit event seems to stop listening

Am I missing something obvious?,

**Comment by yairEO** [comment]
Well, I have no idea how to help without seeing a live demo page, as requested in the issue-template...it's close to impossible for me to randomly guess what is happening in your specific case.

**Comment by AlbertoVargasMoreno** [comment]
For my particular case, the solution was to remove the pattern attribute of the input using tagigy and set the pattern option in the configuration of the tagify object.
 
You can see the code here:
https://jsbin.com/qogemosisa/1/edit?html,js,output

Using the pattern attribute keeps stopping the submission. I have no idea if that is a bug or a particularity of my implementation.

**Comment by yairEO** [comment]
Your input field pattern is incorrect. Inspect your `input` element with `devtools` to see its value and match your regex accordingly. It is a String representing array of emails:

`"["a@b.com","b@c.com"]"`
