### ISSUE TITLE
Combine plain text and tag in same field

### ISSUE THREAD

**Issue by darlontrofy** [yairEO/tagify#114]
I have a requirement where I want to use tagify but have to combine it with plain text. For example, if the text starts with @, it should be tagged but if it does not, it should display it as plain text. Is that possible?

thanks

**Comment by it-xtech-dev** [comment]
You can treat evething as tags but use different styling to for 'text' (no background, no delete) and for tags (normal styling).

**Comment by it-xtech-dev** [comment]
Do you have any CSS expirience?

**Comment by darlontrofy** [comment]
@it-xtech-dev yes, I know CSS very well :-) but I'm not sure where to return the CSS using tagify. I mean how to connect my CSS to show different styles for the display of the tagify. What function or where to add it ...not the actual CSS style.

**Comment by yairEO** [comment]
since tags can have properties, give a `class` property only the the tags you want to style and then simply style only those (by modifying the CSS and removing overall tags styles and moving the rules to be under your specific classname)


see https://github.com/yairEO/tagify#tags-with-properties-example

**Comment by yairEO** [comment]
Can you please be a little more specific about the requirement?

How would I know when to create the tag when a user start writing `@` ?   
Best would be to check the `delimiters` setting and apply the tag once a match is found.

**Comment by darlontrofy** [comment]
The requirement is that when a user types and starts with @@ and ends with%%, tagify should convert all the text in between to a tag, and any other text not following this format should be displayed as plain text. That is the full requirement.

**Comment by yairEO** [comment]
@darlontrofy  - it's not a very "full requirement" description :)

you should specify if the tags can be removed or not, and what happen if they are removed. Also specify if you need autocomplete support (drop down suggestions list) for this.
