### ISSUE TITLE
Is there a way to add a button like the close button

### ISSUE THREAD

**Issue by bacloud23** [yairEO/tagify#1140]
Thanks a lot @yairEO 💯 
I want to let user be able to subscribe to tags, for this it would be nice to have a native (button to add) tagify solution. Just like the delete button.

![Capture](https://user-images.githubusercontent.com/10267332/197399331-53551cc2-8aa6-4f78-8354-cec0cccbe790.PNG)

From then I might be able to add a post request or other interactions.

**Comment by yairEO** [comment]
The README address this under the [`templates` section](https://github.com/yairEO/tagify#dom-templates)

Here's a demo for you:
https://jsbin.com/rumokomavi/1/edit?css,js,console,output

**Comment by bacloud23** [comment]
Thanks a lot @yairEO 
so now all should work with the internals and my aim;

Still I'm looking for how to replicate something like the default [x] button.

I've found the class `tagify__tag__removeBtn` but not its definition so I can add mine. 

Thanks for the help !
