### ISSUE TITLE
Warnings in Console and Dropdown dont open on first Click

### ISSUE THREAD

**Issue by LordRazen** [yairEO/tagify#1143]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
```
<!DOCTYPE html>
<html>
<input name='categories' class='some_class_name' placeholder='Select categories...' >

<script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify@4.16.4"></script>
<script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
var test = JSON.parse(`[{"value":"Test","code":1},{"value":"Test2","code":2},{"value":"Test3","code":3}]`);
tagify = new Tagify(document.querySelector('input[name="categories"]'), {
  whitelist: test,
  dropdown: {
    enabled: 0,
  }
});
</script>
</html>
```
https://jsbin.com/huqizahoma/edit?html,js,output

### Explanation
I found out a few problems within the upper example with Firefox and Chrome. 

**1. Console Messages:**
If you load the example in Firefox, console shows you the following messages. 
![grafik](https://user-images.githubusercontent.com/9381368/200118789-6d2716f1-5237-4600-97e2-8ab951146f53.png)
Translated it means, that the named functions are deprecated and are about to be replaced or removed. 

If you click a tag, another message is shown:
![grafik](https://user-images.githubusercontent.com/9381368/200118845-4c527a7f-d7c4-4e6e-8d9d-6d5380805db1.png)

If you click within the input field if all tags are selected, the following message appears in Firefox AND Chrome:
![grafik](https://user-images.githubusercontent.com/9381368/200118870-c090b75a-55b2-42d4-8f7e-95c4e082f03e.png)

**2. Dropdown does not open on first click in Firefox:**
- Open the example
- Select one tag
- Press F5 (not Strg + F5! The tag should still be selected!)
- Click in the field to show the dropdown again: The dropdown does not open on the first click. You have to click on an empty area of the website and click in the input field again in order to make it open. 

I detected the problem while I send my form with the field and tried to open the dropdown again. It never worked on the first click.

This behaviour does not happen in Chrome. 

Firefox 106.0.3
Chrome 107.0.5304.88

**Comment by yairEO** [comment]
Hi, thanks, but why did you delete the jsbin template link and pasted code here?
I've explicitly BEGGED for people not to do that and urged them to paste code only in jsbin...

This is not a serious bug, and the warning can be ignored, they are not important :)

**Comment by LordRazen** [comment]
Hi,
thanks for the reply. I'm not that versed with that page so I wasnt sure if the bug can really be reproduced on it. 
I added the link which you would like to have... ;-)

Hm... InstallTrigger is flagged to be removed in future... doesnt sound that unimportant to me...

But from your answer, I guess you do not plan to fix this soon, right?

**Comment by yairEO** [comment]
> InstallTrigger is flagged to be removed in future... doesn't sound that unimportant to me...

This is not important, it's for Firefox detection code. nothing harmful.
This is not a "fix", since nothing is broken and console warnings are not bugs, just don't
read them, ignore it.

**Comment by yairEO** [comment]
> Press F5 (not Strg + F5! The tag should still be selected!)

I have no idea what is `Strg` and why should the tag persist (exist in tagify) after refreshing the page with F5...

**Comment by LordRazen** [comment]
> > Press F5 (not Strg + F5! The tag should still be selected!)
> 
> I have no idea what is `Strg` and why should the tag persist (exist in tagify) after refreshing the page with F5...

Oh sorry, Strg is german Ctrl key, forgot to translate it. 

The F5 thing is also something I can only show in firefox, not on jsbin. If I open the html page, select a tag, refresh, the tag is still there but the dropdown does not open on the first click. Indeed it might be another good question WHY the tag is still there and the field is not empty yet..

**Comment by yairEO** [comment]
The tag is still there because Firefox, as a browser, persists input values. It's a known thing

https://stackoverflow.com/q/7377301/104380
