### ISSUE TITLE
How to active Drag Sort in Mix Mode 

### ISSUE THREAD

**Issue by ozknozsrt** [yairEO/tagify#1144]
Hey there,

I made an email template page, it has "Subject" input. And this input getting Dynamic values from modal. Like this, https://prnt.sc/BK6SJ5xz5hI1

But if anyone wants to write it like this: https://prnt.sc/zxV8UH93-MdP This is okay.
But they has to erase everything and rewrite it. It would be easier with drag&drop instead, because they wastes time again to add Dynamic values.

If there is a workaround, how can I do it?

**Comment by yairEO** [comment]
why erase everything I don't get it. They can simply delete the tag or the text before/after it, whichever is faster, and re-create it. a person can select the text and do ctrl+x and then ctrl+v, that's it.

There is no support for dragging tags within text..
It is quite complex and I believe the use-case to be too rare for me to invest time on it...sorry
