### ISSUE TITLE
Weird caret behaviour on addTags() in mixed mode

### ISSUE THREAD

**Issue by northwest-dev** [yairEO/tagify#1145]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [-] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

Couldn't reproduce but here are the videos.
https://drive.google.com/file/d/1uX3GhQyoJfmmEDkPGLfkgH5WxPnjKksy/view?usp=share_link
https://drive.google.com/file/d/1ggXujiuS_0bscgVzPke0feE7fzJcdhAn/view?usp=share_link

### Explanation
I'm dynamically instantiating Tagify on input or textarea elements and hooking the on click event to the dropdown items.

```
<div class="form-group">
	<label for="primaryTextInput">Primary text</label>
	<div class="input-group input-tags">
		<textarea type="textarea" class="form-control" id="primaryTextInput" placeholder=""></textarea>
		<div class="input-group-append">
			<button class="btn btn-outline-secondary input-tags-button" type="button" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-bolt"></i></button>
			<div class="dropdown-menu">
				<button class="dropdown-item" value="name">Name</button>
				<button class="dropdown-item" value="city">City</button>
				<button class="dropdown-item" value="country">Country</button>
				<button class="dropdown-item" value="zip">Zip</button>
				<button class="dropdown-item" value="phone">Phone</button>
			</div>
		</div>
	</div>
</div>
```

```
jQuery.each(elems, (index, elem) => {
	var _input = jQuery(elem).find('input, textarea')

	var tagify = new Tagify(_input[0], {
		mode: 'mix',
		originalInputValueFormat: tagData => tagData.value,
		whitelist: tagify_whitelist,
		mixMode: {
			insertAfterTag: ' '
		},
	})

	jQuery(elem).find('.dropdown-menu .dropdown-item').on('click', (e) => {
		tagify.addTags(jQuery(e.currentTarget).val())
	})
})
```

- **What is the expected behavior?**
Add a tag to the end of the text if the caret is not set.
- **What is happening instead?**
Sometimes a tag is injected at the start of the text or entirely outside of the input element.
- **What error message are you getting?**
none

**Comment by northwest-dev** [comment]
@yairEO could you please take a look?

**Comment by yairEO** [comment]
I see, I will examine why the caret is not appearing after the created node, but at least you can create a JSBIN demo with a bare minimal reproduction of your Tagify settings + external button which injects the tags where the caret is

**Comment by northwest-dev** [comment]
https://jsbin.com/haluteriwo/edit?html,js,console,output

Still can't reproduce that weird addTags() in the label thing, but you can everything else.

**Comment by yairEO** [comment]
You are incorrectly using the wrong API method `addMixTags` instead of the correct way, which is mentioned in the [FAQ section](https://github.com/yairEO/tagify/issues/524#issuecomment-699140465) (in the README):

```js
var input = document.querySelector('textarea')

var tagify = new Tagify(input, {
  mode: 'mix',
  originalInputValueFormat: function(tagData) {return tagData.value;},
  whitelist: ['event', 'city'],
  enforceWhitelist: true,
  duplicates: true,
  mixMode: {
    insertAfterTag: ' '
  }
})

$('.dropdown-item'). on('click', function(e){
  var v = $(e.currentTarget).val()
  var tagElm = tagify.createTagElem({ value:v })
  tagify.injectAtCaret(tagElm)
  var elm = tagify.insertAfterTag(tagElm)   //  <- adds space after the tag
  tagify.placeCaretAfterNode(elm)           //  <- places the caret after the space
})
```

**Comment by northwest-dev** [comment]
Thanks for the caret fix, but there is still a problem with placing tags in labels...
https://drive.google.com/file/d/14ODZoAuGR7xmcbCLYQMykEMDSLgbjFnz/view?usp=share_link
