### ISSUE TITLE
ERROR ReferenceError: content is not defined on manually adding mix tags

### ISSUE THREAD

**Issue by tarungiri** [yairEO/tagify#1148]
I recently start facing "content is not defined" issue while I am adding Tag programmatically using "tagifyService.get("xyz").addMixTags([{ value: tagId, text: tagValue, title: tagValue, type: tagType }])".

![image](https://user-images.githubusercontent.com/39086277/202192452-caaa0e89-ec95-4ce2-aae6-b51165bf59f1.png)

**Comment by yairEO** [comment]
Please open the issue here - https://github.com/Brakebein/ngx-tagify

**Comment by tarungiri** [comment]
Okay, I have opened this on suggested page, Thanks for the information.
But I found that this issue is start coming with yaireo/tagify@4.17.0 version and it is working with older version.

**Comment by Brakebein** [comment]
It's a bug in this repo. You changed `injectAtCaret`, and there, the variable `content` is not previously defined: https://github.com/yairEO/tagify/compare/v4.16.4...v4.17.2#diff-c25a58bcb38aa4fa6506c3017ab957bd356e6fc9f577cc256c8befe559b40050R664-R665 (src/tagify.js L 665)

**Comment by Brakebein** [comment]
Here is the link to the JSBIN: https://jsbin.com/kukovegepi/edit?html,js,console,output
As I pointed out, this is the line where `content` is referenced, but not defined: https://github.com/yairEO/tagify/blob/master/src/tagify.js#L665
