### ISSUE TITLE
with custom dropdown template, the autocomplete doesn't work

### ISSUE THREAD

**Issue by simkimsia** [yairEO/tagify#1151]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jefipudobe/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Tab cannot auto complete when i have custom template for tag and dropdownitem

```
templates : {
                tag : function(tagData) {
                    try {
                        return `<tag title='${tagData.value}' contenteditable='false' spellcheck="false" class='tagify__tag ${tagData.class ? tagData.class : ""}' ${this.getAttributes(tagData)}>
                                <x title='remove tag' class='tagify__tag__removeBtn'></x>
                                <div>
                                    <span class='tagify__tag-text'>${tagData.label ? tagData.label : tagData.value}</span>
                                </div>
                            </tag>`
                    }
                    catch(err){}
                },

                dropdownItem : function(tagData){
                    try{
                        // the ${this.getAttributes(tagData)} is impt because without value="...value"
                        // it beomes unclickable
                        return `<div ${this.getAttributes(tagData)} class='tagify__dropdown__item ${tagData.class ? tagData.class : ""}' >
                                    <span>${tagData.label ? tagData.label : tagData.value}</span>
                                </div>`
                    }
                    catch(err){}
                }
            },
```

- **What is happening instead?** 
Nothing basically.

See loom below
 https://www.loom.com/share/52b91a320b8440e5bc2127b4da99577e

**Comment by yairEO** [comment]
Can you please create a demo page in jsbin? the link in your question does not show your code :)

**Comment by simkimsia** [comment]
i thought i did show the code at [jsbin.com/jefipudobe/edit?html,js,output](https://jsbin.com/jefipudobe/edit?html,js,output)

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/245021/204430575-cc0ba90b-d5b9-4e85-a9c0-15db3928ae48.png">

AM i mistaken?

**Comment by yairEO** [comment]
You need to set `highlightFirst: true` as a `dropdown` setting for `tab`/`right arrow` to autocomplete.
It's technically just applying the selected suggestion item, which will just be the first item, which should be the best-match.

**Comment by simkimsia** [comment]
it worked! thank you :)
