### ISSUE TITLE
React MixedTags onInput issue

### ISSUE THREAD

**Issue by Galexy5** [yairEO/tagify#1152]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I'm not sure if its a bug or something but in React (MixedTags) I'm just trying to access the input state whenever I'm typing.
It seems that **_onInput_** holds the first reference of the function and does not change on each render.

Also I tried to use  _**onChange**_ with **_onChangeAfterBlur=false_** in _settings_ but it doesn't seem to work.
Do I miss something ?
Can you elaborate ? 

Thank you.

***React*** issue template:
https://codesandbox.io/s/tagify-react-wrapper-forked-q29frd?file=/src/MixedModeTagify.jsx:326-381

**Comment by paourissi** [comment]
I can confirm the issue. I tried to do the same thing and i couldnt take the updated state value console logged in the Input function. The component must hold the same reference in every render.

**Comment by yairEO** [comment]
I will examine, thanks for reporting

**Comment by Galexy5** [comment]
> I will examine, thanks for reporting

Thank you for your response. 
If you can let me know about this asap because I need to fix something in production I would really appreciate it.

Thank you again

**Comment by yairEO** [comment]
This is normal expected React behaviour. I also don't understand why you are trying to read `input` (react state) when you have direct access to the Tagify real value)

**Comment by paourissi** [comment]
This not how react works. If you run the simple input example below, you will see that the console show the different inputs. When using mix and tags the input is always the same.


`const MixedModeTagify = () => {
  const [isReadonly, setIsReadonly] = useState(false);
  const [input, setInput] = useState("");

  const onInput = (e) => {
    setInput(e.detail.textContent);
    console.log(input);
  };

  return (
    <>
      <MixedTags placeholder="Input" onInput={onInput} value={``} />
    </>
  );
};

export default MixedModeTagify;`


`const Test = ({ children }) => {
  const [state, setState] = useState("");

  const handleChange = async (event) => {
    console.log(state);
    setState(event.target.value);
  };

  return (
    <div>
      <span>Text: </span>
      <input onInput={handleChange} />
      {/* <Test2 ref={ref}></Test2> */}
    </div>
  );
};`

**Comment by yairEO** [comment]
Why do you need to access the state within the `inInput`?

**Comment by paourissi** [comment]
We want to access the input the user is currently writing. GetInputValue doesnt seem work.

**Comment by yairEO** [comment]
Why don't you use `onChange` with `onChangeAfterBlur`? it works well

```jsx
import React, { useState } from "react";
import {MixedTags} from "../../tagify/src/react.tagify";

// Tagify settings object
const settings = {
  onChangeAfterBlur: false
};

const MixedModeTagify = () => {
  const [isReadonly, setIsReadonly] = useState(false);
  const [input, setInput] = useState("");

  const onInput = (e) => {
    const currentValue = e.detail.tagify.getInputValue()
    setInput( currentValue )
    console.log( currentValue )
  };

  return (
    <>
      <MixedTags placeholder="Input" onInput={onInput} value={``} onChange={console.log} settings={settings} />
    </>
  );
};

export default MixedModeTagify;
```

**Comment by paourissi** [comment]
Onchange executes only after out of  focus. We want to get user input as he writes.

Is there a way to do that?

**Comment by yairEO** [comment]
> Onchange executes only after out of focus. We want to get user input as he writes.

No, try my code from above with the `onChangeAfterBlur: false` and see

**Comment by Galexy5** [comment]
> > Onchange executes only after out of focus. We want to get user input as he writes.
> 
> No, try my code from above with the `onChangeAfterBlur: false` and see

It does work but let me tell you what I'm actually trying to do.
After an event (button click) I add a <span> with a custom class inside input because I want to highlight a part of the text .After that, every time the user writes something inside onInput I want to remove the span.
Is there a way to do it? Can I access the whole raw input with the span somehow ?

**Comment by yairEO** [comment]
what do you want to highlight exactly? a part of the regular text which will always consists of a text or is it mixed with tag(s)?
