### ISSUE TITLE
AJAX Whitelist Code in readme.md incorrect or misleading

### ISSUE THREAD

**Issue by mikrjohn** [yairEO/tagify#1155]
- Below is the code shown as an example beneath AJAX Whitelist Code in readme.md. 
- The line which reads "tagify.loading(true).dropdown.hide()" should be replaced with "tagify.loading(true)", per this example (https://yaireo.github.io/tagify/#section-input). 
- Otherwise, when a user types quickly and hits enter before the dropdown is shown, both parts/events.js and parts/dropdown.js fire addTags via their onKeyDown callbacks. 
- Not calling dropdown.hide() keeps parts/events.js from firing addTags due to this.state.dropdown.visible being true.

```javascript
var input = document.querySelector('input'),
    tagify = new Tagify(input, {whitelist:[]}),
    controller; // for aborting the call

// listen to any keystrokes which modify tagify's input
tagify.on('input', onInput)

function onInput( e ){
  var value = e.detail.value
  tagify.whitelist = null // reset the whitelist

  // https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort
  controller && controller.abort()
  controller = new AbortController()

  // show loading animation and hide the suggestions dropdown
  tagify.loading(true).dropdown.hide()

  fetch('http://get_suggestions.com?value=' + value, {signal:controller.signal})
    .then(RES => RES.json())
    .then(function(newWhitelist){
      tagify.whitelist = newWhitelist // update whitelist Array in-place
      tagify.loading(false).dropdown.show(value) // render the suggestions dropdown
    })
}
```

### 💥 Demo Page
[JSBin Example](https://jsbin.com/cesebac/edit?html,css,js,output)

**Note that typing really quickly, successfully causes this issue to occur 1-2 times out of 5 for me.** Locally, on my machine, using a real ajax, it occurs much more frequently. I believe this was the issue that [suchoss ran into](https://github.com/yairEO/tagify/issues/869) which you were unable to reproduce. Looking at his code, I see that he copied and modified from the readme file, and used tagify.loading(true).dropdown.hide(). 

### Explanation

- Below is code from parts/events.js. If the dropdown is not visible when enter is pressed, addTags gets called.
```javascript
                case 'Enter' :
                    // manual suggestion boxes are assumed to always be visible
                    if( this.state.dropdown.visible && _s.dropdown.position != 'manual' ) return
                    e.preventDefault(); // solves Chrome bug - http://stackoverflow.com/a/20398191/104380
                    // because the main "keydown" event is bound before the dropdown events, this will fire first and will not *yet*
                    // know if an option was just selected from the dropdown menu. If an option was selected,
                    // the dropdown events should handle adding the tag
                    setTimeout(()=>{
                        if( this.state.actions.selectOption )
                            return
                        this.addTags(s, true)
                    })
            }
```
- Below is code from parts/dropdown.js. If the dropdown is not visible when enter is pressed, addTags still gets called.
```javascript
                    case 'Enter' : {
                        e.preventDefault()

                        this.settings.hooks.suggestionClick(e, {tagify:this, tagData:selectedElmData, suggestionElm:selectedElm})
                            .then(() => {
                                if( selectedElm ){
                                    this.dropdown.selectOption(selectedElm)
                                    // highlight next option
                                    selectedElm = this.dropdown.getNextOrPrevOption(selectedElm, !actionUp)
                                    this.dropdown.highlightOption(selectedElm)
                                    return
                                }
                                else
                                    this.dropdown.hide()

                                if( this.settings.mode != 'mix' ) {
                                    //if (!this.state.dropdown.visible)
                                    //    return
                                    console.log('adding tags(7)');
                                    this.addTags(this.state.inputText.trim(), true)
                                }
                            })
                            .catch(err => err)

                        break;
                    }
```

**Comment by yairEO** [comment]
> The line which reads "tagify.loading(true).dropdown.hide()" should be replaced with "tagify.loading(true)", per this example

Don't you mean the other way? it's already written as that

**Comment by mikrjohn** [comment]
I mean that the example under AJAX Whitelist in the Readme is incorrect: https://github.com/yairEO/tagify#ajax-whitelist. 

Whereas the github.io example is correct: https://yaireo.github.io/tagify/#section-input

**Comment by yairEO** [comment]
It's not incorrect - the dropdown should be hidden while a fetch to get a new whitelist is happening, because the current dropdown whitelist shown is now out-of-sync with the typed-query
