### ISSUE TITLE
How do I allow autocomplete based on tag label when the tag label and tag value are different?

### ISSUE THREAD

**Issue by simkimsia** [yairEO/tagify#1156]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page 

https://jsbin.com/sayacazizu/edit?html,js,output

When I type "abc" as in "abc.com", the autocomplete doesn't show.

Thanks for helping me with issue #1151 very grateful

**Comment by simkimsia** [comment]
@yairEO sorry did I provide sufficient info in my demo page?

**Comment by yairEO** [comment]
Hi, here you go, sorry I've missed your question:

https://jsbin.com/qagulac/2/edit?html,js,output

**Comment by SofiaSousa** [comment]
> Hi, here you go, sorry I've missed your question:
> 
> https://jsbin.com/qagulac/2/edit?html,js,output
> 
> ```js
> var tagify = new Tagify(input, {
>     tagTextProp: 'label', // <- what to render inside the selected tag
>     whitelist: whitelist,
>     // maxTags: 1, // set the limit of acceptable tags as input
>     mode: 'select', // <- better than "maxTags: 1"
>     dropdown: {
>         mapValueTo: 'label', // <- what will render for each suggestion
>         searchKeys: ['label'], // <- by which key(s) to filter suggestions
>         maxItems: 20,           // <- mixumum allowed rendered suggestions
>         classname: "tags-look", // <- custom classname for this dropdown, so it could be targeted
>         enabled: 0,             // <- show suggestions on focus
>         closeOnSelect: true,    // <- do not hide the suggestions dropdown once an item has been selected
>         highlightFirst: true,  // <- automatically highlights first item in the list; also needed for autocomplete via tab
>     }
> })
> ```

It seems there is an issue if the input has a default `value` and `searchKeys` are added to the dropdown settings. Ex:

`<input placeholder="type tags" value="111" />`

```js
var input = document.querySelector('input')
var whitelist = [
  {"label": "aaa.aaa.aaa.aaa - abc.com", "value": "111"},
  {"label": "bbb.bbb.bbb.bbb - def.com", "value": "555"}
]

var tagify = new Tagify(input, {
    tagTextProp: 'label',
    whitelist: whitelist,
    // maxTags: 1, // set the limit of acceptable tags as input
    mode: 'select',
    dropdown: {
        mapValueTo: 'label',
        maxItems: 20,           // <- mixumum allowed rendered suggestions
        classname: "tags-look", // <- custom classname for this dropdown, so it could be targeted
        enabled: 0,             // <- show suggestions on focus
        closeOnSelect: true,    // <- do not hide the suggestions dropdown once an item has been selected
        highlightFirst: true,  // <- automatically highlights first item in the list; also needed for autocomplete via tab
        searchKeys: ['label']
    }
})
```
