### ISSUE TITLE
loadOriginalValue() not populating tags when mode is mix

### ISSUE THREAD

**Issue by Nick-PDS** [yairEO/tagify#1157]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/muqugukupi/edit?html,js,output

### Explanation

- **What is the expected behavior?**
- I am using the mix mode to allow user input to add custom delimiters, spaces, text, whatever. When I try to load the value stored in the database and then run loadOriginalValues() it does not properly tag the ones marked with the pattern. I've attempted to add commas like you have to when the mode isn't mix but it still will not populate the tags.

- **What is happening instead?**
- What should be tags is showing up as plaintext instead of a tag after running loadOriginalValues. This is strictly happening when the mode is mix.

- **What error message are you getting?**
- No error messages, just not properly functioning as expected.

**Comment by havebeeair** [comment]
Hi @Nick-PDS, I'm currently facing this issue as well, did you find a way to work around this? Thanks in advance!

**Comment by Nick-PDS** [comment]
> Hi @Nick-PDS, I'm currently facing this issue as well, did you find a way to work around this? Thanks in advance!

Unfortunately, no.

**Comment by yairEO** [comment]
Hi good people, I only saw this now and I will get to the bottom of this.

**Comment by yairEO** [comment]
Your demo was way overly complex. I've simplified it.

https://jsbin.com/jegucof/1/edit?html,js,output

As the documentation states, for `mix` mode, the (real) input's value is written so a tag is represented by a starting `[[` and ends with `]]`. 

https://github.com/yairEO/tagify#mixed-content

Tagify cannot know what is a tag and what isn't without this. 
I remind you that tags can have spaces between words and that's one of the reasons for the use of interpolation.
