### ISSUE TITLE
jquery tagify self contained (with a wrapper) or just a wrapper?

### ISSUE THREAD

**Issue by gidzr** [yairEO/tagify#1158]
Hi and apologies for the basic question, but is it enough to simply download the jquery tagify to run? or is it in addition to the other tagify (are they core?) files?

The reason I ask is because the jquery file is a ".min" so I can't speed read it, and my current implementation of tagify is included in a single JS file for a web template I'm using.. and I'm trying to avoid setting up a new project just to test it manually.

What are the minimum files I need to use with Jquery?

Many thanks.

**Comment by yairEO** [comment]
Hi, yes it is enough to only use the jQuery version of Tagify. You don't need to test it on a new project, you can go to jsbin.com and do it in 2 minutes. just add jquery and then use the Tagify script from any CDN (mentioned in the README)

**Comment by gidzr** [comment]
many thanks :)

(and super awesome work on the tagify - it's so good!!)
