### ISSUE TITLE
Accessing tagified input field with dynamic naming not working, but works on non-tagified input.

### ISSUE THREAD

**Issue by gidzr** [yairEO/tagify#1159]
## Prerequisites

- [x] I am running the latest version (YES! defo! I'm using the core tagify files and the jquery wrapper.)
- [x] I checked the documentation and found no answer (YES! defo!)
- [x] I checked to make sure that this issue has not already been filed (YES! defo!)

I'm losing my mind on this.. At the moment, I'm just trying random guessing trying to fix.. 

Background: I'm using dynamic variables for DOM id names, and more specifically using arrays.
eg. tabname[0]= 'tab1', tabname[1]= 'tab2', etc
then, I loop through using tabname[n] to select all the different tabnames, being tab1... tab9 in the series.

In every other usage, I've had no problems changing an input value programmatically by selecting input field using the dynamic id array name: 
eg.  $('input#'+tabname[n]).val('blahblah'), DOES change the value for any in the series of : input#tabname[0] ... input#tabname[9].

However, I'm not able to change value of a tagified input field when looping through. Strangely I can use direct selection of the dynamic naming either by doing: 
`$("input#"+tabname[1]).val('blahblah')` ..THIS WORKS on $(id).tagify().. OR
`$("input#tab2").val('blahblah')`.. THIS WORKS on $(id).tagify()
`$("input#"+tabname[n]).val('blahblah')`.. but this does NOT WORK with the $.tagify() input field. 

`

     inputIdName = tabNameVarArr[n]+'_sas';
      if($("#"+inputIdName).length>0)     //ie. this line to prevent any issues in tagifying an undefined
      {
         $("#"+inputIdName).tagify({         
            whitelist: ["banana", "orange", "apple"],
            /// id: tabNameVarArr[n]+'_sas',  // must be unique (per-tagify instance) <-- also tried this, but didn't work for me and then commented it out.
            enforceWhitelist: false,
            //maxTags: 10,  //<-- unlimited by default
            dropdown: {
               maxItems: 20,           // <- mixumum allowed rendered suggestions
               classname: "tagify__inline__suggestions", // <- custom classname for this dropdown, so it could be targeted
               enabled: 0,             // <- show suggestions on focus
               closeOnSelect: false    // <- do not hide the suggestions dropdown once an item has been selected
            }
         })
      };

     $("#"+inputIdName).length>0?$("#"+inputIdName).val('asdfasdf'):0;    //<------ this fails to update the tagified field

     $("#"+tabNameVarArr[2]+'_sas'").length>0?$("#"+inputIdName).val('asdfasdf'):0;    //<------ however this DOES update the tagified field

`
I don't see any error messages in the console. 

I've tried using eval, .toString, parseInt on the 'n' .. I've run out of ideas and it's not making any sense :((( .. help me pleeease!!!!!! :)

**Comment by gidzr** [comment]
I've answered my own question.. but wanted to share..

It's a JS timing sync/async issue. 

When I put the dynamic input.val() in a setTimeout(()=>{}, 100), it worked.

I thought the unique id in the tagify was supposed to help with this, but it doesn't.. unless I'm using it wrong.

Any advice?

**Comment by yairEO** [comment]
Hi, you should probably ask this in Stackoverflow as the question is too long and specific to your case, and also not much related to Tagify, and since I'm the only person who answers here and don't have much time, you will probably have better luck asking in a public place and not here, for a single person in the whole world to read :)
