### ISSUE TITLE
whitelist load with ajax on keystroke

### ISSUE THREAD

**Issue by it-xtech-dev** [yairEO/tagify#116]
Is it possible with current implementation to load whitelist dynamically form server via asynchronous. request? If yes, can you give some example?

If not can you expose a callback in settings to do that?
I mean something like: 
````
instance.settings.whitelistLoader = function(returnCallback) {
    $.get('myurl',function(whitelist) {
       returnCallback(whitelist);
    });
}
````

`returnCallback` should fire dropdown render.

**Comment by yairEO** [comment]
What's stopping you from loading it and updating the `whitelist` Tagify setting once the list has been fetched?

    ...initialize tagify...
    var serverWhitelist = fetch...
    .. [when Ajax is done]...
    tagify.settings.whitelist = serverWhitelist;

**Comment by it-xtech-dev** [comment]
Yes, I would like to load whitelist directly from the server, every time user hits the key - maybe with some delay.

**Comment by yairEO** [comment]
Is this helpful?

https://github.com/yairEO/tagify#ajax-whitelist
