### ISSUE TITLE
Re-expose getSetTagData (former tagData()) for us to use

### ISSUE THREAD

**Issue by adrienWeiss** [yairEO/tagify#1160]
Hi
I've been trying to upgrade from v4.16.4 and I noticed you removed the `tagData()`  method from the instance in order to use the `getSetTagData` helper in [v4.17.1](https://github.com/yairEO/tagify/releases/tag/v4.17.1). However, and unless I'm missing something, this helper is not exported for us to use.
I won't go into details too much but on my project I relied onto `tagData()` for different things to quickly retrieve the tag data of an item. 
The readme also still documents the `tagData` method, so I'm wondering if it is possible for you to expose the helper or re-add it to the prototype, or if you instead expect users to use a different approach.

Again, thank you for the work you keep doing on Tagify 👍

**Comment by yairEO** [comment]
Thanks for alerting me! 
I've fixed this a new version will be published soon including the fix.
