### ISSUE TITLE
Bizarre race with dynamic whitelist

### ISSUE THREAD

**Issue by Learath2** [yairEO/tagify#1161]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/nulanuhuga/edit?js,output

### Explanation
Typing `te` and clicking "Test" on the suggestions dropdown doesn't add a tag, but instead just closes the dropdown.

Typing `t` or `tes` and clicking "Test" does add the tag as expected, beyond 3 characters you can seemingly reliably always add the tag.

By adjusting the `dropdownShowDelay` variable at the top you can get it to reliably work no matter how many characters are entered by setting it somewhere around or above 50. This smells like a race condition somewhere, but I just couldn't figure out where. Maybe in the binding of events to the suggestions?

Though I guess it is also possible that I'm just holding it wrong :sweat_smile:

**Comment by yairEO** [comment]
You must clear your `timeout` before each attempt to fetch new data (whitelist).

This is basic in programing, not and unrelated to Tagify.

I also advise wrapping the `onInput` event listener callback with a `debounce` mechanism.

**Comment by Learath2** [comment]
> You must clear your `timeout` before each attempt to fetch new data (whitelist).
> 
> This is basic in programing, not and unrelated to Tagify.
> 
> I also advise wrapping the `onInput` event listener callback with a `debounce` mechanism.
> 

Hm, I'm a little unsure that's the issue here. This is just an attempt to reproduce it. The exact same behaviour happens with a fetch and an abort controller aborting it.

**Comment by yairEO** [comment]
Well, the demo you've posted clearly has issues coming from the timeout not being cleared. 
You should created another version of the demo to make it closer to your "real" setup (but still keep it minimal)
