### ISSUE TITLE
Select / Restore previously chosen tags via ID, not text value (like a select)

### ISSUE THREAD

**Issue by gidzr** [yairEO/tagify#1162]
Hi there
The reason I'm asking for this feature, is because when I restore previously selected tags, I'm using ids. That's because the selections are stored as id's in the DB (relate to the primary key column). When a user returns and loads up a form that was previously saved, it AJAX's the primary key column and what I currently need to do, is extract the tagify names to re-add as $(tagifyField).val() or tagify.addTags().

Currently I'm running these four steps to do this:
Step 1. Create array from DB AJAX [{texval:'hello' ,id:'1'}{texval:'there' ,id:'2'}] for the whitelist
Step 2. Retrieve users stored selection from DB AJAX [1]
Step 3. Filter the array to extract the texts against the previously stored id.  eg. filteredArr = whitelist.filter(item){if id=1, get textval}
Step 4. $(tagifyField).val(filteredArr)

What I would like to do is
Step 1. same as above: get the DB AJAX whitelist [{texval:'hello' ,id:'1'}{texval:'there' ,id:'2'}]
Step 2. same as above: get the DB AJAX selected tags [1]
Step 3. $(tagifyField).val.id([1])

maybe $(tagifyField).text() <--- for selection of tag via text ??
maybe $(tagifyField).val() <--- for selection of tag via id ??

Not sure if I'm overlooking that this is already possible - apologies if I've missed this.

Thanks heaps :)

**Comment by yairEO** [comment]
`$(tagifyField).val.id([1])` is illegal jQuery code, since `val` is not an Object, and certainly not with a property named `id`, and even more, writing `id([1])` makes no sense in javascript.

You should save the value of the input in your DB and use that value again when the page reloads (or the Tagified-component is re-rendered). Ignore Tagify completely. You should work directly with the original `input` element, setting/reading its `value` property.

**Comment by yairEO** [comment]
You want to select a value for the Tagify "select-mode"? just do this:

https://jsbin.com/gopetap/2/edit?html,js,output

```js
var input = document.querySelector('input')

// every whitelist Object item MUST ALWAYS have "value" property
var whitelist = [
  {value: 1, label: "first"},
  {value: 2, label: "second"},
  {value: 3, label: "third"}
]

var tagify = new Tagify(input, {
  mode : "select",
  tagTextProp: 'label',
  whitelist,
  dropdown: {
    mapValueTo: 'label'
  }
})


function setTagifyValueByKey(key) {
  // find the item in the whitelist, by "value"
  var defaultValue = whitelist.find(item => item.value == key)

  // if exists, set it
  defaultValue && tagify.addTags([defaultValue])
}

setTagifyValueByKey(2)
```
