### ISSUE TITLE
Access tags list of tags which are added in text area

### ISSUE THREAD

**Issue by Yawan-1** [yairEO/tagify#1163]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

I am implementing `tagify` in my react app and I am building my custom dropdown and I want to add tags `onClick` on tags from my custom dropdown.

If this is not possible to add tags from custom dropdown then How can I access the tags list or array in which I can append on click in my custom dropdown.

**Comment by yairEO** [comment]
Hi, I don't see any custom dropdown in your Codesandbox... What is wrong with Tagify's dropdown?
