### ISSUE TITLE
Tagify settings option 'Callbacks' work on js version, but not on jquery version

### ISSUE THREAD

**Issue by gidzr** [yairEO/tagify#1164]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hi Yair, just confirming whether the callback{} setting is supposed to work with the Jquery version or not? (as it currently doesn't).

This works
`new Tagify(inputId, {whitelist: blah, callback:{add: ()=>{console.log('blah')}}});`

But this doesn't work
`$('#id').tagify({whitelist: blah, callback:{add: ()=>{console.log('blah')}}});`

I realise you're not keen on the jquery version, but I'm preferring the jquery version as it permits access to the whitelist directly by `whitelistTags = ($(inputId).data()).tagify.whitelist`, instead of using a global variable `var tagify = new Tagify` and accessing tagify later.

Unfortunately using jquery callback with `bind/on('change',callback)` will trigger the callback twice, whereas using the javascript callback methodology works correctly.

Alternatively, is there a way to prevent the jquery callback on tag change triggering twice?

Cheers

**Comment by yairEO** [comment]
Hi gidzr

`var tagify = new Tagify` is not a global variable. it's just **a** variable. You are the programmer of your code and you decide what variable is global or not..

Yeah, I do not really think using the jQuery versions contributes much beside very minor jQuery syntax support.. it's more of a hassle for me to support the very few who uses it.

There is absolutely nothing you can do in jQuery port that you cannot do with the vanilla version.

> But this doesn't work
> $('#id').tagify({whitelist: blah, callback:{add: ()=>{console.log('blah')}}});

I need to find some free time to investigate why that is, but I really recommend using the `.on(...` for binding events. Don't use both

**Comment by gidzr** [comment]
Cool cool.. thanks for that. I'll prob switch back to the vanilla version once I can figure out how to access the whitelist on the DOM with a vanilla version tagified element.
