### ISSUE TITLE
Pasted data into empty tag created via addEmptyTag automatically disappears on lost focus.

### ISSUE THREAD

**Issue by gitgitwhat** [yairEO/tagify#1167]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
You can see this behavior on your own demo page (https://yaireo.github.io/tagify).  Under your 'Easy to customize' demo, click the + to create an empty tag and paste some data into it.  Then simply make the tag lose focus and the tag is cleared.

### Explanation

- **What is the expected behavior?**
Pasted data should become a valid tag.

- **What is happening instead?**
Pasted data disappears.

- **What error message are you getting?**
None

**Comment by yashpandey002** [comment]
Can I work on this issue?

**Comment by yairEO** [comment]
Sorry I was on vacation. I will examine it.
