### ISSUE TITLE
Display an alert when a user enters a tag that doesn't match the pattern

### ISSUE THREAD

**Issue by alsahliahmed** [yairEO/tagify#1168]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I am sorry, I don't have any online demo to show, but I hope that my question is clear enough. I am using tagify plugin and it is working perfectly. The only question I have is, how can I display a message if the user tries to add an invalid tag?

For example, this is my tagify:
`var $el = $('#distributionLst').tagify({`
`pattern: /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,`
`delimiters: ",|;| "`
`});`
`var jqTagify = $el.data('tagify');`

The above tagify, forces the users to enter only emails, the email entry gets validated in the pattern section. Everything works just fine, but some users are confused because they don't know why some tags get deleted.

So, I am wondering if I can create a red label that only gets displayed when the user enters an invalid tag.

Thank you

**Comment by yairEO** [comment]
Under the [Events](https://github.com/yairEO/tagify#events) section in the README you can read about the `invalid` event, so you can use it to show whatever message, anywhere you want.

```js
tagify.on('invalid', e => renderMessage(e.detail))
```

Also, citing from the REAMD:

> Note - there is a setting to keep invalid tags ([keepInvalidTags](https://github.com/yairEO/tagify#settings)) and if it's set to true, the user can see the reason for the invalidation by hovering the tag and see the browser's native tooltip via the title attribute

I advise you to go over the README

**Comment by alsahliahmed** [comment]
Thank you!!
