### ISSUE TITLE
Tag already used in list

### ISSUE THREAD

**Issue by davide-lucchelli** [yairEO/tagify#117]
Hi,
with "enabled" config set to "0", if I click on the input I see the dropdown as expected but in the tag list I see all the tags, also the already used ones. If I type some chars I see the list filtered. 
Is it possible remove the used tags also with no chars typed?

Thanks a lot,
Davide

**Comment by yairEO** [comment]
This never had crossed my mind actually. thanks for the suggestion, I shall add an option to control if already-existing tags should show in the dropdown list or not

**Comment by davide-lucchelli** [comment]
Great! Thank you so much!
