### ISSUE TITLE
Uncaught TypeError: t.hasAttribute is not a function

### ISSUE THREAD

**Issue by Sonic3R** [yairEO/tagify#1174]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsfiddle.net/vz8wdgs6/

### Explanation

- **What is the expected behavior?**
No error should happen

- **What is happening instead?**
A javascript error occured (like in this title)

- **What error message are you getting?**
Uncaught TypeError: t.hasAttribute is not a function

**Comment by yairEO** [comment]
You are using `querySelectorAll` instead of `querySelector`...

If you want to apply Tagify to all fields then use:

`querySelectorAll(...).forEach(elem => { new Tagify(...)})`

**Comment by Sonic3R** [comment]
Dumb me, yes indeed
