### ISSUE TITLE
Dropdown excluding duplicates

### ISSUE THREAD

**Issue by christo0pher** [yairEO/tagify#1177]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/cilaniw/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Expected to get a dropdown showing all tags from our whitelist

- **What is happening instead?**
The whitelist gets filtered and duplicates are removed, even if we explicitly allow duplicates

- **What error message are you getting?**

**Comment by yairEO** [comment]
Define the [dropdown.includeSelectedTags](https://github.com/yairEO/tagify#settings) setting:

```js
var tagify = new Tagify(input, {
  dropdown: {
    enabled: 0,
    includeSelectedTags: true,              // <- set this to "true"
  },
  enforceWhitelist: true,
  duplicates: true,
  whitelist: ["a", "aa", "aaa", "b", "bb", "ccc"]
})
```
