### ISSUE TITLE
escapeHTML function in tagify example for users list not working

### ISSUE THREAD

**Issue by simkimsia** [yairEO/tagify#1188]
## Prerequisites

- [x] I am running the latest version
I copy exactly the code from the example

```js
function escapeHTML( s ){
      return typeof s == 'string' ? s
          .replace(/&/g, "&")
          .replace(/</g, "<")
          .replace(/>/g, ">")
          .replace(/"/g, """)
          .replace(/`|'/g, "'")
          : s;
  }
```

I get the following
<img width="737" alt="image" src="https://user-images.githubusercontent.com/245021/224535706-17262af5-fc2e-449f-b567-95227fcec858.png">

Chrome complained abt the same thing

<img width="290" alt="image" src="https://user-images.githubusercontent.com/245021/224535733-f20756cf-20ac-472a-b47f-666595c79bfd.png">

## What I do as workaround

I commented out that line

```js
function escapeHTML( s ){
      return typeof s == 'string' ? s
          .replace(/&/g, "&")
          .replace(/</g, "<")
          .replace(/>/g, ">")
          // .replace(/"/g, """)
          .replace(/`|'/g, "'")
          : s;
  }

```

**Comment by yairEO** [comment]
The code posted above is not in [Tagify's example code](https://github.com/yairEO/tagify/blob/master/index.html#L1949-L1957):

```js
function escapeHTML( s ){
    return typeof s == 'string' ? s
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/`|'/g, "&#039;")
        : s;
}
```

**Comment by simkimsia** [comment]
Oh i see. 

it showed up like this

<img width="461" alt="image" src="https://user-images.githubusercontent.com/245021/231517594-d12336a0-eaca-4e6d-a0c7-b32bf3eb5337.png">
under https://yaireo.github.io/tagify/
for User List

**Comment by yairEO** [comment]
Ha I understand. I will add a comment saying where to copy this from. The browser is unescaping the unicode and there's nothing I can do
