### ISSUE TITLE
onChange gets triggered when instantiating Tagify in React

### ISSUE THREAD

**Issue by navaniharsh31** [yairEO/tagify#1191]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Im using MixedTags in react, whenever i give in the value prop, it messes up my state and kinda makes a loop. When only defaultValue is given, the onChange is triggered once. How do i prevent the trigger of onChange at all unless a user types in?

Did find a few issues which said removeAllTags would fire without the change event, but for me the change event is fired.

**Comment by yairEO** [comment]
It's not happening in the [official demo](https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/MixedModeTagify.jsx)

You also did not post an example demo page with simplified version of your implementation, so I cannot help you.

**Comment by yairEO** [comment]
![image](https://user-images.githubusercontent.com/845031/227769666-e0646739-02b2-4cf7-8ca9-b855712ddaf6.png)

You are using it as if it was a controlled component, hence, getting an infinite loop.
