### ISSUE TITLE
Emojis are filtered out

### ISSUE THREAD

**Issue by northwest-dev** [yairEO/tagify#1193]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

https://drive.google.com/file/d/1xTRo2YHLXjZuP-JXf5dyBgX8-VGbjapk/view?usp=share_link
Please look at the screen recording because I can't reproduce the problem.

When I add emojis to the Tagify field, they are filtered out from the actual textarea, and if I add them to the textarea, they are automatically replaced by newlines.

### My code:

```js
var tagify = new Tagify(_input[0], {
    mode: 'mix',
    originalInputValueFormat: tagData => tagData.value,
    whitelist: tagify_whitelist,
    enforceWhitelist: true,
    duplicates: true,
    mixMode: {
        insertAfterTag: ' '
    },
    callbacks: {
        "keydown": (e) => {
            setTimeout(() => {
                jQuery(e.detail.tagify.DOM.originalInput).trigger('change')
            }, 200);
        }
    }
})
```

**Comment by yairEO** [comment]
I am using your code and can am able to type emojis

**Comment by northwest-dev** [comment]
The problem is not in typing emojis, it's in saving them to DB. When fetching values from inputs, emojis are not there.
As you can see in the video, pasting emojis into Tagiyf fields doesn't add them to the hidden field on the right (in this case I've removed the style that hides the fields), and pasting them directly to the hidden field automatically filters them out.

I don't have any additional logic that would filter out emojis.

**Comment by yairEO** [comment]
Emojis work for me, and have always worked:

As **required** in the issue template, you should have created a minimal demo which reproduces the issue (which I spent time creating for you): 
https://jsbin.com/savejel/edit?html,css,js,output

As you can see, typing an emoji works as expected

https://user-images.githubusercontent.com/845031/231384229-057d3448-5602-4d34-9db6-cb373074931d.mp4

**Comment by northwest-dev** [comment]
I'm sorry, I know it works for you and I couldn't recreate the problem in the jsbin, so I made the video explaining where the problem is in hope you or someone else could help me with the issue. 
I tried looking at the Tagify core for any filtering or setting that would make this kind of behavior but couldn't find anything. 

Thank you for trying.

**Comment by yairEO** [comment]
There is no reason to look at Tagify's source code if all examples allow Emojis, it is obviously your own code and the issue is unrelated to Tagify.

Just follow the path of data (in your code) and see at which point does the Emoji disappears.
