### ISSUE TITLE
In readonly mode, click on the current label and press Enter to enter the editing state

### ISSUE THREAD

**Issue by wabgy** [yairEO/tagify#1195]
[Readonly](https://yaireo.github.io/tagify/#section-readonly)

**Comment by yairEO** [comment]
Thanks for reporting!

**Comment by wabgy** [comment]
Hello, thank you for fixing this issue.

May I ask if this issue can be fixed without upgrading the code and using existing settings, events, and methods?

**Comment by yairEO** [comment]
Hi, no it is impossible without upgrading

**Comment by wabgy** [comment]
Thanks
