### ISSUE TITLE
Cannot change `tagTextProp` to anything other than 'value'

### ISSUE THREAD

**Issue by aminebenkeroum** [yairEO/tagify#1199]
Hello,

I have a problem with the setting tagTextProp, that I cannot change to `label`, with my Typescript app, the typescript error says: 

`Type '"label"' is not assignable to type '"value"'.ts(2322)`

```
<Tags
      name={name}
      readOnly={disabled}
      loading={loading}
      value={value}
      settings={{
        placeholder,
        mode: !multiple ? 'select' : undefined,
        whitelist: finalOptions,
        enforceWhitelist: !freeSolo,
        tagTextProp: 'label',
        dropdown: {
          enabled: options && options.length > 0 ? 1 : 0,
          mapValueTo: 'label',
        },
      }}
    />
```

The Tagify version is `4.17.7`.

Thank you for the help

**Comment by yairEO** [comment]
Sorry, I don't know Typescript. Somebody else wrote the type definitions (I don't know who) and posted them [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fa7cf9e766e32570344130284915dbbdbcff636c/types/yaireo__tagify/index.d.ts#L646) so you can maybe debug it there and create a pull request if you think there's a bug
