### ISSUE TITLE
Support dynamic suggestions list

### ISSUE THREAD

**Issue by yairEO** [yairEO/tagify#12]
Have the code support dynamic suggestions list which might come from the server using AJAX

**Comment by taheri-mohammad** [comment]
hi i have an idea,
 if add one more eventhandler on keydown (or keyup) tagify input feild and callback it like remove or add then run an ajax to load new whitelist.

**Comment by carbontwelve** [comment]
This is one feature I am looking for, seems difficult to find a good vanilla library like this one with dynamic suggestions.

**Comment by yairEO** [comment]
I will get to it in the next few weeks, promise!

I will tackle this by enabling the option to include a 3rd party drop-down list component script that could be integrated with Tagify

**Comment by yairEO** [comment]
I think that it is technically possible to have a dynamic suggestion list in this manner:
    
    // do some ajax here...
    // when the Ajax resolves, use the response data to change the "whitelist" 
    this.settings.whitelist = reposone; // where "response" is an Array
    // The "datalist" element should be re-built now
    this.DOM.datalist = this.buildDataList();

This should probably work

**Comment by johnaau** [comment]
+1 for a dynamic suggestion list, based on user input.

**Comment by johnaau** [comment]
I've made some modifications to the code to support a dynamic suggestion list based on user input.

Not sure I did it the best way, but it works.

It would be good if this feature was part of this great component.

See http://blog.johnavis.com/blog/963/how-to-add-ajax-suggestions-to-yaireo-s-tagify-tag-input-component/

**Comment by yairEO** [comment]
I've come to the conclusion that this should happen from outside Tagify, and it's the developer's responsibility to update the tagify's instance `whitelist` setting on ajax `success`

**Comment by Olezha** [comment]
Please tell me on what event it is best to calling the ajax request and what is the replacement for the ```this.DOM.datalist = this.buildDataList();``` in the new version. Is it possible to do this in the initialization part without touching the library code?

Perhaps it makes sense to write a working example in the documentation.

**Comment by phaberest** [comment]
I need the same, but I'm getting my suggestions from a function that analyzes the values of the previously filled fields, is there still a way to update the values? I tried using `.datalist` but id doesn't seem to be working
