### ISSUE TITLE
IE 11 with Polyfills consistent errors

### ISSUE THREAD

**Issue by hunkydoryrepair** [yairEO/tagify#120]
One of my requirements is to support IE 11.

Unfortunately, the polyfill solution does not completely work.  It consistently gets an error 

Object doesn't support property or method 'forEach' on line 474.  This is shown below.
querySelectorAll('tag') appears to return a valid array-like object, but it does not have a forEach method.

I am not using either react or jquery. This does work in Chrome so it seems a polyfill may be needed for this case. 

```
  getTagIndexByValue: function getTagIndexByValue(value) {
    var result = [];
    this.DOM.scope.querySelectorAll('tag').forEach(function (tagElm, i) {
      if (tagElm.textContent.trim().toLowerCase() == value.toLowerCase()) result.push(i);
    });
    return result;
  },
```

**Comment by hunkydoryrepair** [comment]
I found a workaround. Adding this to the polyfills.js solves it:

```
    if (window.NodeList && !NodeList.prototype.forEach) {
        NodeList.prototype.forEach = Array.prototype.forEach;
    }

```

**Comment by yairEO** [comment]
Thanks for reporting! I've completely forgotten to test IE11 after a few commits done in the past month.

I will incorporate your fix in the polyfill file and test
