### ISSUE TITLE
re-populating tagify field causes multiple event fires instead of the one

### ISSUE THREAD

**Issue by gidzr** [yairEO/tagify#1200]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
When restoring previously multiple previously chosen tags from localstorage in a single hit, on page reload, I expect an event listener for that field to only trigger ONCE

For example:
var restoredValue = ["selection1","selection2","selection3"]
$('tagifyInput').val(["selection1","selection2","selection3"])
$('tagifyInput').on('add removeTag',()=>{  console.log('fired') })  //<-- should fire once only.

Even though there are three previously stored tags, when they are added back tot he tagified field, I expect the event to be triggered once.

- **What is happening instead?**
When restoring multiple selections as shown above, I get an event fired for each restored tag. ie. 3 events are fired.

Hi Yair
I'm not sure if this issue is coming from JQUERY tagify version, JQUERY itself, or just Tagify add listener. I've noticed the same thing also happens whether use 'change' OR 'add' on the listener.

This issue only occurs in the JQuery version, not the JS version.

Yay - I've replicated this in codepen:   https://codepen.io/gidzr/pen/MWPbBMB?editors=1010

Kinda racking my brains so would appreciate any signposts you can give. If it's a purely JQUERY issue I can try figure it out myself. If it's a Tagify JQuery issue I'm certain you'll tell me to switch to the JS version which I don't want to do because of how I can access the tagified items without global variables including easy access to data.whitelist and without creating global variables, and without re-init new Tagify on a pre-existing tag just to get the field without using a global variable.

Cheers

**Comment by gidzr** [comment]
Hey mate, I've decided to migrate to the pure JS version .. not using the jquery tagify anymore. Although technically the above bug is still there if you ever feel OCD to fix it :``D  ;P

Could you clarify something I've not seen in the documentation.. How do I access a tagify field without a global variable and without re-initialising tagify on a field.

Currently for the js version, when I .addTags('xx') to an existing tagify field, I'm doing this:
> var preexistingTagify = document.querySelector("#apreviouslyTagifiedInupt")
> new Tagify('prexistingTagify').addTags.

This works! buuuuuut causes a warning message that the field has already been tagified. I'm not sure if it's also breaking something unintentionally - like resetting tagify IDs.

Everything else I've managed to find an equivalent for in the JS version that I had working in the JQuery version.

**Comment by yairEO** [comment]
Hi, 

this is bad:

```js
  var tagJSElem =  document.querySelector('#tagifyJSInput')
  new Tagify(tagJSElem,{}).addTags(restoredTags)
```

this is good:

```js
  var tagJSElem =  document.querySelector('#tagifyJSInput')
  var myTagify = new Tagify(tagJSElem)
  myTagify.addTags(restoredTags)
```

Just don't use jQuery :) no need. I've made it support it many years ago while jQuery was still popular

**Comment by gidzr** [comment]
Yep yep .. i understand the "good" version.. .. but that's that version requiring global variables right?

I thought it was bad practice to rely on global variables in JS.. and coding generally.. and I've run into troubles losing track of global variables as well. 

It would be EPIC if there was some global way of accessing addTags for the DOM.. like

`
function a(){
   var tagJSElem =  document.querySelector('#tagifyJSInput');
   new Tagify(tagJSElem);
}

function b(){
   var tagJSElem =  document.querySelector('#tagifyJSInput');

   ?? tagJSElem.dataList.addTags = restoredTags. ??
   // or tagJSElem.dataList.value= restoredTags.
   // or $(tagJSElem).val(restoredTags) //<-- which doesn't seem to work for JS Tagify.. unless I'm missing something..?

}
`

Is there something I'm overlooking?

**Comment by yairEO** [comment]
There are no global variables... at all. `myTagify` is a local variable.
This question is unrelated to Tagify but to the fundamentals of the javascript language.

You need to construct your code in a way which the `addTags` method would be available for you in another code-block (or file). 

`addTags` is a function. You cannot assign it a *value*.

**Comment by gidzr** [comment]
Hey Yair - Just to confirm, I get all that. I understand the difference between JS/JQ. I tested using both JQ/JS simultaneously in the CodePen and created two distinct tagifies. So that bit is clear. I also get that  JS would go tagJSElem.dataList.value instead of .val().

But structuring the codeblock to ensure the **tagifyVar** = new Tagify() variable is available does require  a lot of work to restructure the code around an extrinsic element. I wouldn't restructure code to accommodate one library. I could use a global variable as a workaround but was hoping to have overlooked something that could help me avoid this.

All good - and mucho appreciated for your help  :) .. You're a legend and I lurrrv tagify!!!
