### ISSUE TITLE
How to allow user input of invalid tag but still enforce maxTag

### ISSUE THREAD

**Issue by simkimsia** [yairEO/tagify#1203]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page - *clone one of the below:*

In this page, https://yaireo.github.io/tagify/#section-advance-options under Advance Options, it's possible to type multiple new entries without hitting the maxTag limit.

I used the #13 where the fix was to add a callback.

But I can still keep adding. My purpose is to limit to 1 tag regardless whether the user creates a new tag or uses the whitelist option.

```
callbacks : { add:onAddTag },

function onAddTag(e){
        // limit to "1" tags
        if( e.detail.index > 1 )
            tagify1.removeTag();
    }
```

How to allow user to create new tag but also respecting the maxTag limit?

**Comment by simkimsia** [comment]
the better solution is to use SELECT MODE

 `'mode': 'select'`
 
 see https://yaireo.github.io/tagify/#section-mode-select

**Comment by yairEO** [comment]
use the [setting](https://github.com/yairEO/tagify#settings) `keepInvalidTags: true`
