### ISSUE TITLE
[React] How to create custom tags in mixed mode

### ISSUE THREAD

**Issue by shahriarshafin** [yairEO/tagify#1205]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page - *clone one of the below:*

***React*** issue template:
https://codesandbox.io/s/tagify-react-wrapper-forked-mfdmbd?file=/src/MixedModeTagify.jsx

Hello, I'd like to have custom created tag in mixed mode using react. Any ideas on how to do that?

**Comment by yairEO** [comment]
Pass the `templates` setting to the Tagify component

https://github.com/yairEO/tagify#example-of-overriding-the-tag-template
```js
const settings = {
  pattern: /@/,
  templates: {
    tag(tagData, tagify){
      return `<tag title="${(tagData.title || tagData.value)}"
                  contenteditable='false'
                  spellcheck='false'
                  tabIndex="${this.settings.a11y.focusableTags ? 0 : -1}"
                  class="${this.settings.classNames.tag} ${tagData.class ? tagData.class : ""}"
                  ${this.getAttributes(tagData)}>
          <x title='' class="${this.settings.classNames.tagX}" role='button' aria-label='remove tag'></x>
          <div>
              <img style='height:20px;weight:20px' src="${"https://developer-beta.taskeasy.io/storage/applications/images/1674381255_github.png"}">
              <span class="${this.settings.classNames.tagText}">${tagData[this.settings.tagTextProp] || tagData.value}</span>
          </div>
        </tag>`
    }
  }
};
```

Here's the modified code:

https://codesandbox.io/s/tagify-react-wrapper-forked-3c4j94

**Comment by shahriarshafin** [comment]
@yairEO, thank you so much!
