### ISSUE TITLE
Tag background breaks if tags include multiple lines

### ISSUE THREAD

**Issue by max-callone** [yairEO/tagify#1208]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/wogiyajivo/edit?html,css,js,output

### Explanation

- **What is the expected behavior?**

Line breaks inside tags should not destroy tag background

![image](https://github.com/yairEO/tagify/assets/85161482/20990482-47a8-4819-958e-2cd696a7fbad)

- **What is happening instead?**

Line breaks inside tag produces gab/line in tag background due to background being set as box-shadow with specific size. Line breaks might occur when the tagify container or surrounding box is limited in width. This box-shadow size can be adjusted via CSS variables but is therefore not dynamic when it comes to handling tags with multiple lines.
Is there a reason the set the tag background as inset box-shadow?

**Comment by yairEO** [comment]
it is easily configurable, as everything else in this module. All CSS configuration is visible at the live playground page:

https://yaireo.github.io/tagify/

![image](https://github.com/yairEO/tagify/assets/845031/dabcc87c-1ac0-400f-892e-a5442a21ada7)
