### ISSUE TITLE
TAB key does nothing (re-open #90)

### ISSUE THREAD

**Issue by hunkydoryrepair** [yairEO/tagify#121]
This can be seen in the demos in the very top demo.

Type a couple letters, then hit TAB. Nothing happens.

If there are no partial tags typed in, it goes to the next field.

In this scenario, I would expect TAB to work like a delimiter and complete the tag, and either go to the next element or not (probably not, because hitting it a second time would then let it proceed).

This is definitely related to issue #90

**Comment by hunkydoryrepair** [comment]
This issue seems to be that the TAB key has preventDefault called even it autocomplete does not have a suggestion. The original bug report had a solution for that, which required testing if it was in the state.

Another solution would be to have autocomplete.set return `false` if it has no effect. You already have a test in there, so call set, if it is === false then call preventDefault, otherwise do not.

**Comment by yairEO** [comment]
Just checked it works as expected. See my [comment](https://github.com/yairEO/tagify/issues/90#issuecomment-422288724) from that issue.

Tab autocompletes, not adding the tag for you. If you started writing a tag that was in a `whitelist` and you see it suggested to you, then hitting tab will use that suggestion

----

Tagify is still a form input type, like all other types, hitting tab should "jump" to the next focusable element, and I believe messing with that wildly agreed accessibility feature is not so good

**Comment by yairEO** [comment]
ok I understand what you're saying and will make the change

**Comment by hunkydoryrepair** [comment]
Yes, I found this works pretty well:

around line 934:
```

            case 'ArrowRight':
            case 'Tab':
                e.preventDefault();
                if (this.input.autocomplete.set.call(this, selectedElm ? selectedElm.textContent : null) !== false)
                    return false;
                // fall through and act like ENTER

            case 'Enter':
              e.preventDefault();
              newValue = selectedElm ? selectedElm.textContent : this.input.value;
              this.addTags(newValue, true);
              this.dropdown.hide.call(this);
              break;

```

and then around 439:

```

          if (suggestion) {
              ... /* unchanged */
          }
          else {
              return false;
          }
```

**Comment by hunkydoryrepair** [comment]
I realize the "set" function may be overridden in some cases. I haven't tested that, but unless they are returning `false` already for some reason, it shouldn't break anything, it just may not fix the problem in those cases.
