### ISSUE TITLE
How to manipulate the arrow of the dropdown (or input)?

### ISSUE THREAD

**Issue by VictorAndrade11** [yairEO/tagify#1210]
I am trying to modify the input arrow, as you can see in the attachment: https://i.imgur.com/TnmH7n3.png

However, it is not programmable (LUL).
I tried creating functions to manipulate it;
I tried manipulating it with CSS;
But I always get two results: Either it doesn't work or it breaks the code.

I need to make it possible to choose whether the arrow appears or not.

Tks

**Comment by yairEO** [comment]
hi, such questions I advise to ask on Stackoverflow, and you should also add code...
