### ISSUE TITLE
Prevent pattern validation on tag edit

### ISSUE THREAD

**Issue by alessio-de-padova** [yairEO/tagify#1214]
Hi! 
I come to seek your help once again! :D 
I am still using version 4.17.8 and I need help with tag editing.

As you can see also in your [demo page](https://yaireo.github.io/tagify/), in the mixed-mode example when you create a new tag and then edit it you will have a validation error which will prevent you from adding the tag.

![image](https://github.com/yairEO/tagify/assets/57996166/3285b0b0-9965-4212-a19a-a93c496377da)

I think this is happening because the user's edit does not respect the pattern property in the Tagify configuration (e.g., such edit does not begin with a "@") so I would like to ask you if there is a way to prevent such validation from happening since we haven't managed to find one!

**Comment by bertorres** [comment]
Hi,
Any updates on this? I'm facing the same problem where I cannot edit any Tag after being added in Mix-mode.
I'm adding the tags from a button so I really need a Tag to be editable.

Is there any way to prevent from doing any validation? 

Thanks in advance, you are doing a great job.

**Comment by bertorres** [comment]
Hi again,

I managed to make it work by adding a RegEx.

Cheers!

**Comment by alessio-de-padova** [comment]
> Hi again,
> 
> I managed to make it work by adding a RegEx.
> 
> Cheers!

Hi! Can you tell me how you fixed it?

**Comment by bertorres** [comment]
Hi,

Keep in mind I'm using a custom dropdown to add the Tags only from that, so maybe is not the same case as yours.

Here is the code:
`
        var input = document.getElementById(inputName);
        var tagify = new Tagify(input, {
            mode: 'mix',
            pattern: /^.*$/,
        });
        // "add new tag" custom dropdown
        var button = document.getElementById(inputName+'_dropdown-menu');  

        button.addEventListener("click", function(event) {
            tagify.addTags(event.target.textContent+'['+(scene+1)+']');
        })
`

**Comment by yairEO** [comment]
Sorry I was away from coding for a while... I will continue working on this.
