### ISSUE TITLE
Focus blurs input immediately

### ISSUE THREAD

**Issue by BruceKristelijn** [yairEO/tagify#1216]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation
When I click to edit the tagify input in blurs immediatly. But when I use tab to get to the input it works normally. When my mouse is on the dropdownfield it however does work.
![cce0f762e0d4ebaefdca484f3d4a95a8](https://github.com/yairEO/tagify/assets/32113184/7fdb8fdb-16c9-4832-a08c-424462750b28)

- **What is the expected behavior?**
The dropdown should display and I would be able to type.

- **What is happening instead?**
The dropdown closes after appearing and the input is blurred.

- **What error message are you getting?**
None

**Comment by yairEO** [comment]
OK...and how can I possibly help? 
I have no idea what you've done in your code.

If the [demo page]([yaireo.github.io/tagify/](https://yaireo.github.io/tagify/)) works then something in your own code is causing this.

I've **specifically** asked in the Github issue template to add a minimal reproduction of the bug (in jsbin.com) but you did not supply one.

I am not a medium and cannot solve your bugs remotely without seeing what's going on :)

**Comment by MiniJude** [comment]
we have the same expression：
https://github.com/yairEO/tagify/issues/1218#issue-1795983923
