### ISSUE TITLE
Mixed mode, how to render html nodes string as plain text

### ISSUE THREAD

**Issue by bingxin-xia** [yairEO/tagify#1217]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I'm using this excellent component with "mixed" mode.
The situation is I may have an initial string value like `"this is a sample <b>bold not required</b>"`.
But the `"<b>bold not required</b>"` was rendered as HTML `"<b>"` tag inside the input. What I want is just to be rendered as plain text.
![image](https://github.com/yairEO/tagify/assets/9410789/a1c250e5-bff5-4035-aa61-6ee4738613b0)

Thanks in advance for any help!

**Comment by yairEO** [comment]
so [escape it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

```js
encodeURIComponent('<b>bold not required</b>')
```

or manually convert `<` to unicode `&lt;`:

```
&lt;b>bold not required&lt;/b>
```
