### ISSUE TITLE
`<input>` wrapped in a `<label>` doesn't work

### ISSUE THREAD

**Issue by jjonescz** [yairEO/tagify#1219]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/fegocotaju/1/edit?html,js,output

```html
<label>
    Label:
    <input />
</label>
```

### Explanation

- **What is the expected behavior?** I would expect it to work normally, it's just slightly modified basic example. This alternative works fine:
  ```html
  <label for="tags">Label:</label>
  <input id="tags" />
  ```

- **What is happening instead?** The tags input cannot be focused, the underlying text box is focused instead. If I type something anyway, the UI breaks:
  ![screenshot](https://github.com/yairEO/tagify/assets/3669664/b7039fac-6e70-4cb3-b376-9e89ef99b292)

- **What error message are you getting?** None.

**Comment by yairEO** [comment]
well, it's something developers should change in their own HTML structure I guess.

**Comment by jjonescz** [comment]
Perhaps it could be at least documented as unsupported. It's not obvious.

**Comment by yairEO** [comment]
@jjonescz - updated the README and will be visible soon when I deploy a new version

**Comment by dmx-patrick** [comment]
I know this issue is already closed, but why not change the original input to type="hidden". This makes it hidden and prevents the focus to it and it still is being submitted with the form. It should fix this issue and the extra css to make the original input hidden is not needed.
