### ISSUE TITLE
TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by mbajur** [yairEO/tagify#122]
Hello!
I have a following setup:

```
{
_initTags () {
    let _this = this

    this.tagify = new Tagify(this.tagsPhantomInputTarget, {
      delimiters: ', ',
      maxTags: this.tagsPhantomInputTarget.dataset.maxTags,
      whitelist: [],
      transformTag (value) { return value.replace('#', '') }
    })

    let fetchTags = debounce((e) => { this._fetchTags(e) }, 300)
    this.tagify.on('input', (e) => fetchTags(e))
  }

  _fetchTags (e) {
    let value = e.detail.value

    this.tagify.settings.whitelist.length = 0
    let req = api.tags({ q: value })

    req.then((resp) => {
      this.tagify.settings.whitelist = resp.data.map((tag) => { return tag.name })
      console.log(this.tagify.settings.whitelist)
      this.tagify.dropdown.show.call(this.tagify, value)
    })
  }
}
```

and when trying to search for existing tag, instead of getting the suggestions dropdown, tagify raises

```
Uncaught (in promise) TypeError: Cannot set property 'innerHTML' of undefined
    at Tagify.show (tagify.js:852)
```

i have observed i can fix this error by adding **anything** to the `whitelist` array when initializing the Tagify but it seems like a bug. Or have i misconfigured something? :)

Full code i here: https://gitlab.com/mbajur/prismo/blob/master/app/javascript/packs/controllers/story_form_controller.js

Thanks in advance!

**Comment by yairEO** [comment]
The problem was the I never initialized the dropdown element if the `whitelist` wasn't already defined on initialization. This is a bug since I wrote that part of initializing the dropdown itself much before I re-write the rest of the code to allow setting a dynamic whitelist (from Ajax)

**Comment by yairEO** [comment]
Btw, I would write it:

    this.tagify.on('input', debounce(e => _this.fetchTags(e), 300))
