### ISSUE TITLE
The dropdown does not work in React

### ISSUE THREAD

**Issue by mrold** [yairEO/tagify#1220]
## Prerequisites

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Try it 

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-forked-wlzz4w?file=/src/index.js

**Comment by yairEO** [comment]
You did not specify a `whitelist`...
