### ISSUE TITLE
Vanilla JS trims line breaks

### ISSUE THREAD

**Issue by tomlazersheep** [yairEO/tagify#1223]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hi, I'm trying to store the tagify content with tags and everything, but line breaks are always gone. 
I've seen a couple similar issues but using React, could not make it work in vanilla js.
Am I missing something?

### Demo Page - *clone one of the below:*

[https://jsbin.com/loveqim/edit?html,js,console,output](https://jsbin.com/loveqim/edit?html,js,console,output)

**Comment by yairEO** [comment]
please show me the piece of code which saves the tagify field to the server. 

how do you get the value of the textarea?

**Comment by tomlazersheep** [comment]
Hi @yairEO thank you so much for answering!
I'm currently providing support for a plugin to use Tagify mix mode in a platform called Bubble.io, the idea is to create something similar to any comment tagging section in bubble platform, just like here -> @yairEO 

The code to retrieve the textarea content is the following: 

> instance.data.tagify.on("change", (e) => {
>         console.log("e.detail: ", e.detail);
>         instance.publishState("content_tags", e.detail.value);
>         //replace tags for values
>         instance.publishState(
>           "content_plain_text",
>           replaceTags(e.detail.value)
>         );
>       });

I prepared an example in bubble to show what's going on, the value coming inside e.detail is already trimmed (watch the console logs for that). Here's the demo -> https://tagify-demo.bubbleapps.io/version-test/test1?debug_mode=true

Here's my implementation for creating the Tagify object, many values come from user properties so ignore those, I'd be happy to try something to avoid trimming.

> new Tagify(tagify_input, {
>         whitelist: instance.data.tag_whitelist.map(function (item) {
>           return typeof item == "string" ? { value: item } : item;
>         }),
>         enforceWhitelist: true,
>         mode: "mix",
>         pattern: tag_openers_regex,
>         tagTextProp: "text",
>         editTags: false,
>         placeholder: properties.placeholder,
>         dropdown: {
>           enabled: properties.characters_for_dropdown,
>           position: "text",
>           mapValueTo: "text",
>           highlightFirst: true,
>         },
>       });

Of couse I just need to access the untrimmed content, once I have that, it is my own issue how to store it. Can't thank you enough for looking into this.

Best Regards

**Comment by yairEO** [comment]
Please use `<textarea placeholder="type tags"></textarea>` and not an `<input>` as the element which gets Tagified 

Sorry I haven't answered before, I didn't feel like working on Tagify for months
