### ISSUE TITLE
Uncaught TypeError: t.hasAttribute is not a function Inside Bootstrap Modal

### ISSUE THREAD

**Issue by Nasirkhan-259** [yairEO/tagify#1225]
`let inputTags = $("#kt_tagify_2");
        new Tagify(inputTags);`
        
        `                                <input type="text" name="tags" class="form-control form-control-xs" id="kt_tagify_2"/>
`

**Comment by yairEO** [comment]
please create a reproducible demo which I can inspect

**Comment by yairEO** [comment]
closing as stale
