### ISSUE TITLE
Initial value when using originalInputValueFormat

### ISSUE THREAD

**Issue by adantart** [yairEO/tagify#1226]
Hi!

I have the data as a JSON, with different variables as your example: name, value, email ...
I use also this
```
originalInputValueFormat: valuesArr => valuesArr.map(item => item.value).join(','),
```

So when I get the value of the input, I have (for example): 6,45,153
But when I want to populate the input field when loading the page with that string (6,45,153), the tagify remains blank.

It works if I don't use the "originalInputValueFormat", but when using it, it works to get what users selects, but it does not to populate it when loading the page.

It's very useful to have cleaner post/get variables ;-)

Thank you in advance

**Comment by yairEO** [comment]
you need to convert it to something tagify understands. `6,45,153` means nothing to Tagify as a value, unless they are ids and then you'll need to set `tagTextProp` setting to whichever property of your whitelist hold those ids
