### ISSUE TITLE
 How can I position the dropdown of Tagify library right below the input?

### ISSUE THREAD

**Issue by andydella** [yairEO/tagify#1229]
Hello, I'm using the [Tagify](https://github.com/yairEO/tagify) library for JavaScript, and I'm having a little issue. I want to make sure that the dropdown always appears directly below the input element. Currently, in some cases, it appears in different positions based on the content or the size of the viewport. Is there a way to enforce the dropdown to always appear right below the input?

I show you some code:
"
                var tagify2 = new Tagify(input2, {
                    whitelist: indice, // Aquí pondríamos la lista de conceptos
                    maxTags: 10,
                    dropdown: {
                        maxItems: 20,
                        classname: "tags-look",
                        enabled: 0,
                        closeOnSelect: false,
                        position: "input",
                    }
                });"

Thank you in advance for your help

**Comment by yairEO** [comment]
the suggestions dropdown automatically opens below the input unless it won't fit and then renders above the input element. forcing a certain position is currently not possible
