### ISSUE TITLE
Error in `setAttribute` When Adding Tags if a function is passed in `tagTemplate`

### ISSUE THREAD

**Issue by mohammad-matini** [yairEO/tagify#123]
I'm trying to use Tagify in my TypeScript/Angular application.
Tagify version: "2.6.2"

I want to have a mixed text with tags where the tags have additional attributes. On a button click I want to get a text value where the tags are replaced with a specific attribute. I also want tags to start with a pattern '@'.

Anyways, I'm getting errors when adding a tag if a function is passed to `tagTemplate`, I tried to isolate the problem a little bit. This code is lifted from the examples page, and it doesn't work:

HTML:
``` html
<input name='tags3-1' placeholder="Try to add tags from the list">
```

TS:
``` typescript
var tagify = new Tagify(document.querySelector('input[name=tags3-1]'), {
            tagTemplate: function(v, tagData) {
                console.log(v, tagData);
                return `${v}`;
            },
            whitelist : [
                { value:'Afghanistan', code:'AF' },
                { value:'Åland Islands', code:'AX' }
            ],
            dropdown : {
                enabled: 1,
            },
        })
```

I type "Af" and I get completion, I choose "Afghanistan" and press enter, nothing happens in the UI, and I get an error.

The error I'm getting:
```
ERROR TypeError: Cannot read property 'setAttribute' of null
    at addTagAttrs (app-apps-apps-module.js:3424)
    at Tagify.createTagElem (app-apps-apps-module.js:3431)
    at app-apps-apps-module.js:3357
    at Array.forEach (<anonymous>)
    at Tagify.addTags (app-apps-apps-module.js:3334)
    at Tagify.onKeyDown (app-apps-apps-module.js:3615)
```

If I remove the `tagTemplate` property, it works.

I'm not sure what's wrong, hopefully I'm not missing something silly.
Thanks for your time.

**Comment by yairEO** [comment]
You did not write any template, so what do you expect?

    tagTemplate: function(v, tagData) {
            console.log(v, tagData);
            return `${v}`;  // <-- this is NOT a template. 
    }

A template must return an **HTML** element, not a _Text Node_.

This is the default template:

    <tag title='${v}' contenteditable='false'>
            <x title=''></x><div><span>${v}</span></div>
    </tag>

You need to work with that and modify it to whatever you want, but it should stay a `<tag>` element which wraps the tag's text

**Comment by mohammad-matini** [comment]
I appreciate your help. Turns out the demo page is not rendering the templates, angled brackets in them must be escaped.

![screenshot-20181016222747](https://user-images.githubusercontent.com/44205473/47047016-2ecd1e80-d19f-11e8-8e16-3f9c9d4a4691.png)

I wrote some regex quick fix for this.
There are probably better ways.

See pull-request: https://github.com/yairEO/tagify/pull/124
