### ISSUE TITLE
Caret is not visible in mix mode

### ISSUE THREAD

**Issue by Megas78** [yairEO/tagify#1231]
Good day. It is reproducible on demo page: https://yaireo.github.io/tagify/ (Google crome / Mac Os).  

#1. If caret is on the beginning of input and tag is the first element of input then caret is not visible.  

#2. Also caret is not visible between tags if tags are right one after another.

In Firefox (Mac Os) I can't put carpet at the beginning of input if first element is tag and I also can't put it between tags if they are one after another.

Thank you for your efforts! 
![Screenshot at Aug 14 10-17-14](https://github.com/yairEO/tagify/assets/19715177/bee0f928-d4ff-48c2-b1e3-4eb0bc6132c5)

**Comment by yairEO** [comment]
Chrome bugs... :( 
reported years ago but Google won't bother to fix
