### ISSUE TITLE
Question: tag autocomplete with extra data, but remove extra data on actual tag creation?

### ISSUE THREAD

**Issue by jzohrab** [yairEO/tagify#1235]
## Prerequisites

- [x] I am running the latest version -- NO, exploratory question only :-)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hello, thank you for the project, and for all your work, it's a real contribution!  I hope I have not missed anything in your docs.

I have a case where I'd like the autocomplete to include some extra info.  My app is for reading and vocabulary.  For example, if I'm entering a tag "cat", the autocomplete should suggest:

```
cat (animal)
catalogue (list of stuff)
catatonic (sleep/shock)
cataxxxx (...)
```

and if I choose "catalogue (list of stuff)", the tag "catalogue" (without "(list of stuff)") would be created and added.

Is such a manipulation possible?

Cheers and regards!  Jeff

**Comment by jzohrab** [comment]
To anyone reading this in the future, yes, such a manipulation is possible.  You use a template for the dropdownItem, and your whitelist should be of the correct format.

For my case, I had an ajax method that returned some data, so I had to change it to make an object with `value` and `suggestion` properties:

```
      let make_dropdown = function(hsh) {
        t = hsh.translation ?? '';
        if (t == '') {
          return hsh.text;
        }
        return `${hsh.text} (${hsh.translation})`;
      };

      fetch(`/term/search/${s}/${langid}`, {signal:controller.signal})
        .then(RES => RES.json())
        .then(function(data) {
          // const newWhitelist = data.map((a) => { value: `${a.text}` });
          const newWhitelist = data.map((a) => ({
            "value": a.text,
            "suggestion": make_dropdown(a)
          }));
          tagify.whitelist = newWhitelist; // update whitelist Array in-place
          tagify.loading(false).dropdown.show(s); // render the suggestions dropdown
      });
```

then in my tagify constructor I specified the template to use the new `suggestion` property:

```
      templates: {
        dropdownItem: function(item) {
          return `<div ${this.getAttributes(item)}
                    class='${this.settings.classNames.dropdownItem} ${item.class || ""}'
                    tabindex="0"
                    role="option">${item.suggestion}</div>`;
        }
      }
```

@yairEO -- I don't know if there is a good place for me to make a README contribution, or if this should just be something that library users figure out.  Thank you!

**Comment by yairEO** [comment]
Hi sorry I have missed your question and only now am seeing this.

There is no for such complexity.. no need to override the `templates` setting.

It's actually right there in the [demos page](file:///C:/Users/vsync/projects/tagify/index.html#section-rtl)

All you need to do is set the `dropdown.mapValueTo` setting to some other property other than `value`:

```js
var input = document.querySelector('input[name=rtl-example]');

// initialize Tagify on the above input node reference
new Tagify(input, {
    whitelist: [
        {value: "cat", full: "cat (animal)"},
		{value: "catalogue ", full: catalogue "(list of stuff)"},
		{value: "catatonic ", full: "catatonic (sleep/shock)"}
    ],
    dropdown: {
        mapValueTo: 'full', // will render "full" property as dropdown suggestions
    }
})
```
