### ISSUE TITLE
How to give the text inside the label a different color for each character according to certain rules

### ISSUE THREAD

**Issue by ymengting** [yairEO/tagify#1237]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page - *clone one of the below:*

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

**Comment by ymengting** [comment]
I can't get the value when I use a custom template to nest multiple layers. What can I do

**Comment by yairEO** [comment]
closed as unresponsive
