### ISSUE TITLE
How to keep the dropdown open if a user deletes an item in the input.

### ISSUE THREAD

**Issue by MaxKoldun** [yairEO/tagify#1239]
How to keep the dropdown open, when a user deletes an item in the input, It disappears in all examples I checked and I did not find a prop that keeps it open. Example:

https://codesandbox.io/s/tagify-react-issue-template-forked-fxv6xg?file=/src/index.js

When you select an item and then try to delete it, the dropdown will be closed i want to keep it open.

**Comment by dixflatlinr** [comment]
This is a partial solution. The dropdown will disappear, then reapper since the trigger is hooked on the input's focus. Also, the event trigger is a bit sloooow.

```
callbacks: {
    "remove": (e) =>
    {
        //Refocus the tagify input field
        $(e.detail.tagify.DOM.input).focus()
    },

or

oTagify.on('remove', (e) => $(e.detail.tagify.DOM.input).focus()
```
