### ISSUE TITLE
Browser scripts using the CDN script can't access Tagify

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [yairEO/tagify#1241]
### Summary
I'm trying to use tagify in a CMS environment that still uses some old ASP.NET ways of bundling javascript.

I expected the CDN minified javascript file to support just adding
`<script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"></script>`
and then I could use it in any subsequent script tags, but it doesn't look like it adds tagify to the window object, and only supports modules?

Is that by design? I thought UMD was supposed to be able to detect this kind of thing? Am I doing something dumb in the demo below?

To be clear, the CMS environment I use loads modules via AMD

### Demo Page
https://codesandbox.io/s/wizardly-leftpad-vdrspz?file=/src/index.js

**Comment by xXTraceXx** [comment]
Did you watch? https://jsbin.com/jekuqap/edit?html

**Comment by xXTraceXx** [comment]
Tried it myself and it is working

**Comment by NathanBeddoeWebDev** [comment]
So... the issue is that my CMS' plugin system has an insane frontend build system, and I don't have a particularly competent grasp of AMD.
