### ISSUE TITLE
Selectable icon/flag with custom text

### ISSUE THREAD

**Issue by xXTraceXx** [yairEO/tagify#1242]
Hi,

maybe i have a "useful" idea for a new feature. Image u have templates with icon/flag like in your example. As a user u have to chose a item from the dropdown list. But image if u can write your own tag with a selectable icon/flag. 

My suggested syntax will something like `icon:Test` => this would create a tag with text and a changeable icon in the tag.

If you think this would be a nice feature i will try to make a pull-request for that. Just let me know ;-)

Thanks for you awesome project!

**Comment by yairEO** [comment]
Hi, I didn't quite understand fully but you can already do that using a custom tag template
