### ISSUE TITLE
XSS vulnerability in <Tags InputMode='textarea'>.

### ISSUE THREAD

**Issue by OND4330** [yairEO/tagify#1243]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-wrapper-forked-y8v7dg?file=/src/MixedModeTagify.jsx

### Explanation

Hi, I was using tagfiy through the wrapper of react and I have discovered an XSS vulnerability and would like to report it.

I can reproduce it with the following simple code.

```
import React from 'react';
import logo from '. /logo.svg';
import '. /App.css';
import Tags from "@yaireo/tagify/dist/react.tagify" // React-wrapper file
import "@yaireo/tagify/dist/tagify.css" // Tagify CSS

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <Tags
           InputMode='textarea' 
          defaultValue={
          '{<img src=a onerror=alert(document.location)>}' 
        }/>
      </header>
    </div>
  );
}

export default App;
```
 Without InputMode='textarea', the script does not work and is not vulnerable to XSS.
 However, isn't it problematic that InputMode='textarea' only gives the defaultValue to be vulnerable?
 
 I have confirmed the same vulnerability in demo.
 
![スクリーンショット 2023-09-15 15 55 48](https://github.com/yairEO/tagify/assets/96280413/b38302b9-3ef9-4f5b-858c-2fed9b5428dd)
![スクリーンショット 2023-09-15 15 56 10](https://github.com/yairEO/tagify/assets/96280413/29757c8a-a161-4893-ae0c-1f18f6e55251)

**Comment by thadeubrito** [comment]
I created a PR fixing a similar issue in mix mode. you can try to apply the same approach for this case.
https://github.com/yairEO/tagify/pull/1244

**Comment by OND4330** [comment]
Thank you!!!

**Comment by yairEO** [comment]
it is up to the *backend* developers of you product to prevent XSS.

You should see Tagify as another type of `input` element. 
HTML (text) input elements do not care about XSS, they are agnostic to it.
