### ISSUE TITLE
is Tagify compatible with alpinejs V3

### ISSUE THREAD

**Issue by eafarooqi** [yairEO/tagify#1246]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

getting error with basic initializing with alpinejs 

```
<input
            x-data="{
                tagify: null,
                initTagify() {
                    this.tagify = Tagify(this.$el, {
                        enforceWhitelist: true,
                        whitelist : ['aaa', 'aaab', 'aaabb', 'aaabc', 'aaabd', 'aaabe', 'aaac', 'aaacc'],
                    });
                }
            }"
            x-init="initTagify()"
            name="tags"
            id="tags"
            type="text"
        />
```

- **What is the expected behavior?**
- normal tagify instance

- **What is happening instead?**
getting error
- **What error message are you getting?**
Alpine Expression Error: Cannot set properties of undefined (setting 'isFirefox')

**Comment by yairEO** [comment]
I don't know what is `alpinejs`
