### ISSUE TITLE
React Version 18: Available options not showing (caused by new createRoot syntax)

### ISSUE THREAD

**Issue by MrAvantiC** [yairEO/tagify#1248]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo
https://github.com/MrAvantiC/react-tagify-version-18-bug

### Explanation

- **What is the expected behavior?**
When using the `MixedTags` component, I expect to see available options when starting to type with "@".

- **What is happening instead?**
I see no available options.

- **What error message are you getting?**
None.

---

I was already able to determine the cause of the issue here.
In the example, you can see that in `main.jsx` we use `ReactDOM.createRoot` which is the new default in React Verison 18+.

If you replace the entire  `main.jsx` with the legacy syntax, it works as expected:
```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import App from './App.jsx'

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
)
```

However, this will show the following deprecation warning.
<img width="616" alt="Screenshot 2023-10-02 at 15 38 55" src="https://github.com/yairEO/tagify/assets/17713179/9b590c29-8c3d-4493-bcd5-1883ebfed57d">

So, it seems there is an issue with the new syntax in React 18+ which causes the suggested options to not show anymore.

**Comment by yairEO** [comment]
Try using without `<React.StrictMode>`, it's a horrible buggy wrapper

**Comment by yairEO** [comment]
I don't understand what do you mean by "Available options not showing".. showing where?
Anyway, tested on React 18 and everything works fine.

**Comment by MrAvantiC** [comment]
Hi @yairEO ,
did you even check out the repository I provided? 
I'm still able to easily reproduce this behaviour with it...

You can also see it here:
https://github.com/yairEO/tagify/assets/17713179/aa6328d0-e75b-4d75-84f1-33655485cec5

...same repository as above.
By default, the options/suggestions are not working.
Only after changing the syntax in `main.jsx` to the "legacy" syntax, Tagify works as expected and shows the options/suggestions.
