### ISSUE TITLE
Hook for Add Tag event

### ISSUE THREAD

**Issue by eric-aurora** [yairEO/tagify#1255]
It would be fantastic to be able to add a tag before another tag is added, we could do this via a add tag hook.

My use case involves dynamically adding a tag just before a tag gets added by the user. Using the onAdd method produces some odd results, as it adds a visual tag before the element, but the linked input box has the value listed after. I have hacked together a solution which utilizes the dropdown:select event, but it doesn't account for all ways of adding a tag (with tab/enter/,)

We have a beforeRemoveTag hook and I would be eternally grateful if there was a beforeAddTag as well.

**Comment by yairEO** [comment]
The concept of hooks solely exists due the async nature of their usage and there is no asynchronicity in your needs, it's a matter of A before B, as fast as it can happen, so adding a hook is not the correct thing here.

There is an infinite-look problem here that if one would programmatically add a tag, before a tag was added by the user, that that programmatically-added tag would also trigger the same (tagify) event which detected a tag has been added, and keep re-adding.

the `addTags()` method is quite complex and it automatically triggers the `add` event, there is no way around that unless you would temporarily stop listening to the event and then re-instate it:

https://jsbin.com/xiyoken/2/edit?html,js,output

```js
var input = document.querySelector('input')
var tagify = new Tagify(input)

tagify.on('add', onAddTag)

function onAddTag() {
    tagData = {value: 'added before'}
    
    tagify.off('add', onAddTag)
    tagify.addTags('xxx')
    tagify.on('add', onAddTag)
}
```
