### ISSUE TITLE
Enable adding custom attributes to Tagify

### ISSUE THREAD

**Issue by Git002** [yairEO/tagify#1256]
I have a specific requirement where I want to have an `id` attribute to Tagify element. That could be very useful at identifying a specific Tagify instance on the page easily as Tagify creates a new element and shifts the original element to `left: -9999em!important` so, what if I want to, say suppose hide/show that Tagify instance I cannot do that easily with `.getElementById()`

If we have an option to just pass id to our Tagify instance, that would be really helpful.
Thanks!

**Comment by awesome1128** [comment]
You're right.
I am trying to use id attribute in Tagify next.js, but no id attribute.
I 100% don't understand why @yairEO didn't add it.
I am still trying to understand why.
Hope @yairEO adds id attritube asap.
Thank you so much!

**Comment by Git002** [comment]
yeah, I did my own implementation of adding an id to each Tagify instance I created through my components. Was a bit of hassle but 🤷‍♂️.... ofcourse that would be a nice feature to be added. I hope @yairEO adds that too

**Comment by yairEO** [comment]
@awesome1128 for "ASAP" situations, payment for changes can certainly help

**Comment by yairEO** [comment]
You can use a `class` attribute just as well as an `id` for "identifying a specific Tagify instance", why do you need `id` specifically?
