### ISSUE TITLE
Is it possible to have "Enter" key not create a tag?

### ISSUE THREAD

**Issue by jheengoo** [yairEO/tagify#1259]
Hi

Is it possible to configure tagify in such a way that it does not add  a tag when enter is pressed? I tried stoppropagation, preventdefault on keypress,keydown,keyup events of tagify event. I also tried this on parent container of tagify but to no avail. 

Thanks
Waqar

**Comment by yairEO** [comment]
Hi, it isn't possible unless I make changes in the source code. May I know why you need this?

**Comment by yairEO** [comment]
you can use the [`addTagOn` setting](https://github.com/yairEO/tagify#settings) (Array) to eliminate <kbd>Enter</kbd> key from converting input text to tags:

```js
new Tagify(document.querySelector('input'), {
    addTagOn: ['blur'],  // default is: ['blur', 'tab', 'enter']
}
```

**Comment by jheengoo** [comment]
Thanks a lot. I really appreciate it.
