### ISSUE TITLE
Tags get broken when clicking on label

### ISSUE THREAD

**Issue by ancc** [yairEO/tagify#1260]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/hovosavawe/edit?html,js,output

### Explanation
Start typing in input and hold down some key and the same time click on input label(still holding down the key).

- **What is the expected behavior?**
tags not get broken
- **What is happening instead?**
Tags get broken, result for example when holding down key "d"
{"value":"{\"value\":\"{\\\"value\\\":\\\"ddddddddddddddd\\\"}]dd\"}]dddddddddddd"}]dddddddd
- **What error message are you getting?**
no errors

**Comment by AaronAsAChimp** [comment]
This is also an issue if the input is located inside the label. The focus is moved to the (usually) hidden input immediately upon focusing the Tagify component. This causes the dropdown to close immediately.

Demo: https://jsbin.com/laquxiqeyi/1/edit?html,js,output

**Comment by yairEO** [comment]
@AaronAsAChimp - the JSBIN you posted seems to lack any modifications which showcases an issue

**Comment by yairEO** [comment]
@ancc - simply remove the `for` attribute in your HTML: `<label for="text">Text</label>` 

It shouldn't/can't co-exist with Tagify

**Comment by AaronAsAChimp** [comment]
@yairEO I'm not sure what happened there. This bin should show the issue (I doubled checked it 😁). https://jsbin.com/nanapotihe/edit?html,js,output

**Comment by yairEO** [comment]
Tagify cannot work with inputs which reside inside `<Label>` unless you manipulate the label so it won't point to the input: `<label for=''>`

**Comment by AaronAsAChimp** [comment]
Thank you, I found something that works. Adding the following to my above example makes it work as expected. Could this or something similar be integrated into Tagify? If not that's ok, but I like the usability that the label provides.

```js
function redirectFocus(e) {
  e.preventDefault()
  const tagifyInput = e.target.querySelector('.tagify__input');
 
  if (tagifyInput) {
    tagifyInput.focus();
  }
}

input.labels.forEach((label) => {
  label.addEventListener('click', redirectFocus);
})
```

**Comment by yairEO** [comment]
please use event delegation and do not bind an event on each individual element.

ask `bard` or `chatGPT` to convert it for you to event-delegated `click` event on all `<label>` elements and ask it to teach you what that is :)

you can also just do this in your `redirectFocus` function:

```js
e.target.querySelector('.tagify__input')?.focus()
```

I don't want Tagify to directly mess with HTML elements in the page and prefer to leave that for developers to solve.
