### ISSUE TITLE
Unexpected Behavior with Tagify Input Height

### ISSUE THREAD

**Issue by MuneebChaudhry-dev** [yairEO/tagify#1261]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/gabumocuje/1/edit?html,css,console,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-forked-868gn4

### Explanation
I am encountering an issue with the Tagify library. In my application, I have an input field for entering tags, and I have specified the height of the input field to be 150px as per the design requirements. However, I am facing unexpected behavior when adding tags.

The issue occurs when I input some tags in the field and reach the end of the first line. When I press Enter to start a new line, the cursor moves to the middle of the container instead of shifting to the next line as expected. This results in an excessive space between the first and second lines. Interestingly, as I continue adding more lines of tags, the space between lines decreases until both lines act normally at the end.

- **What is the expected behavior?**
When adding tags in the input field, the cursor should move to the next line without excessive space between lines, maintaining the specified height for the input field.

- **What is happening instead?**
After adding tags and pressing Enter, the cursor moves to the middle of the container, creating excessive space between the lines, which gradually decreases as more lines are added.

- **What error message are you getting?**
![Screenshot from 2023-11-06 18-00-08](https://github.com/yairEO/tagify/assets/109788422/fe1bb219-f832-4489-b0e8-40d901968eb8)
![image](https://github.com/yairEO/tagify/assets/109788422/d1f8d821-5f3d-45b8-9a37-59afb79bf529)

- **Expected Space Should be:**
![image](https://github.com/yairEO/tagify/assets/109788422/81b0cb74-779e-4589-a4ed-877a9ae0ff8f)

**Comment by tsjensen** [comment]
I am facing the same problem - did you find a solution?

**Comment by yairEO** [comment]
Hi, just add the style `align-content: baseline;` to `.tagify` selector

**Comment by MuneebChaudhry-dev** [comment]
> I am facing the same problem - did you find a solution?

Yes,  Just use `align-content` property

**Comment by tsjensen** [comment]
Thank you for the hints!

`align-content` improved the situation, but did not completely fix it. In my case, I managed to fix it by

```css
.tagify {
    display: inline-flex !important;
}
```

**Comment by tsjensen** [comment]
You're right! It seems that my Bootstrap setup somehow caused it to be changed. 🤷‍♂
