### ISSUE TITLE
Avoid modal closing when click ESC key in open whitelist dropdown

### ISSUE THREAD

**Issue by kuhlware** [yairEO/tagify#1262]
Hi,

we have the problem, that we position the tagify textarea in a bootstrap modal. If the dropdown whitelist is open and the user click the ESC key the whole modal closes. I tried to listen on the tagify keydown event, but it doesn't work. Also listen on the document doesn't work. Any ideas how to fix this? :)

```
document.onkeydown = function(e) {
            let tagify = document.querySelector('.tagify');
            if (e.keyCode == 27 && tagify !== undefined && tagify !== null) {
                console.log("avoid esc close");
                e.preventDefault();
                e.stopPropagation();
                return false;
            }
        };
```

```
onKeydown(e, that, tagify){
        console.log(e);
        if (e.detail.event.code == "Escape") {
            console.log("Tagify: avoid esc close");
            e.preventDefault();
            e.detail.event.preventDefault();
            e.detail.event.stopPropagation();
            e.stopPropagation();
            return false;
        }
    }
```

Best regards,
Fabian

**Comment by yairEO** [comment]
You need to bypass your modal's closing mechanism. You have the state of `Tagify` and can know if the suggestions menu (dropdown) is shown or not, and from that infer if your modal is allowed to be closed when clicking on the `ESC` button.

```js
tagify.state.dropdown
```

Will show you the current state. it is an *object* with `visible` property in state which its value is the currently "filtered-by" text which was typed/pasted
