### ISSUE TITLE
There is a little line at the middle of the tag when hover the tag with high dpi

### ISSUE THREAD

**Issue by liesauer** [yairEO/tagify#1263]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation
my system is running at 200% scale and the browser is 125%, when i change the browser scale to 100%, the line appears.

i found that it's caused by `--tag-bg-inset: -2.5px`, i change to `-2px` and the line is gone, it looks like it is a rendering issue with float pixels.

![GIF 2023-11-20 14-32-06](https://github.com/yairEO/tagify/assets/8676741/1822d7b3-9b9c-471e-9187-fdc55cdb790b)
![image](https://github.com/yairEO/tagify/assets/8676741/fa8cbcfe-0dff-4008-8558-bb3733072718)

**Comment by yairEO** [comment]
It's not a bug, it's just the default CSS that cannot possibly work for all scenarios. If your tags are pretty large, then you would have to adjust the CSS to accommodate. 

Please adjust the `--tag-inset-shadow-size` CSS variable 

This can be seen in the [demo](https://github.com/yairEO/tagify) using the top-right settings, you can increase the `--tag-pad` CSS variable (first one) and see how it affects and then adjust ``--tag-inset-shadow-size`
