### ISSUE TITLE
Max Length attribute

### ISSUE THREAD

**Issue by YRaviSW** [yairEO/tagify#1265]
Is there is any way to set the maximum length for the Tagify input?

Example - https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_maxlength like this

Example - If I set MaxLength to 10 then the use only able to enter 10 character in the tagify input

**Comment by yairEO** [comment]
It's up to you as the developer to validate the user's input. All the information is in the README file. 
there are multiple ways you can validate it (while the user is typing, or after the tag is appended)

See https://github.com/yairEO/tagify#validations or the `transformTags` setting, or listen to the `input` [event](https://github.com/yairEO/tagify#events)

**Comment by billsaysthis** [comment]
FYI @yairEO we tried to implement max length for a MixedTag implementation and gave up. `Pattern` is not really useful in mix mode, and validate doesn't seem to get called in a way that I could get working.

**Comment by yairEO** [comment]
@billsaysthis - here you go sir, hopefully this is what you've wanted:

https://jsbin.com/qumipal/edit?html,js,output

Please use Tagify `v4.21.1` or above
