### ISSUE TITLE
`transformTag` is not called before a tag is edited by selecting a dropdown suggestion

### ISSUE THREAD

**Issue by ciccabanana** [yairEO/tagify#1268]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

- https://jsbin.com/suvaciquha/edit?html,js,output
- https://yaireo.github.io/tagify/#section-advance-options

![GIF Exemple](https://github.com/yairEO/tagify/assets/69674899/21475daf-2ca2-4d36-b3e4-873020fac785)

### P.s. / Note
- In the jsbin example I have defined a "CustomConsole" that will add a colored prefix for each different event, only for a easier console reading.

### Explanation

- **From the documentation**

Name | Type | Default | Info
-- | -- | -- | --
transformTag | Function |   | Takes a tag data as argument and allows mutating it before a tag is created or edited and also before validation.Should not return anything, only mutate the argument.

When edit a tag and you select a new value for the dropdown the transformTag  is not called.
If you edit a tag and lose the focus and blur event occur transformTag  is called.

- **What is the expected behavior?**
That transformTag will be called before the edit take in place.

- **What is happening instead?**
The transformTag is not called and the tag lose the color.

**Comment by yairEO** [comment]
Thanks for reporting! 
I was away from coding for some months but now I am back and will fix this
