### ISSUE TITLE
N items selected instead of showing everything selected

### ISSUE THREAD

**Issue by mete89** [yairEO/tagify#1269]
## Prerequisites

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

Hey, 

I checked the docs and examples (sorry if I missed anything).

Is there any option to limit the items selected? For example if user selects more than 10 tags, instead of showing every selected tags, can we show text like N items selected like here: https://developer.snapappointments.com/bootstrap-select/examples/#selected-text-format

**Comment by yairEO** [comment]
Hi, I have no idea what you mean. please post a screenshot

**Comment by yairEO** [comment]
How would then the user be able to remove a specific tag if all they sees is one accumulative thing instead of a list of tags? You can just add a custom text somewhere saying everything was/is selected.
