### ISSUE TITLE
Different order of callbacks on desktop and mobile

### ISSUE THREAD

**Issue by vorant** [yairEO/tagify#1272]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codepen.io/vorant/pen/oNVbGOd?editors=1111

### Explanation

**Steps to reproduce?**
- Open on desktop 
- Click to edit a tag
- Being in edit mode, click on outside button
- see results in console
- - **callback of `edit:updated` event**
- - **callback of outside button**

- Open on mobile device or mobile emulator in Chrome  
- Click to edit a tag
- Being in edit mode, click on outside button
- see results in console
- - **callback of outside button**
- - **callback of `edit:updated` event**

**Actual results?**
Different order of callbacks for different types of devices
 
**Expected results?**
- Same order of callbacks for different types of devices 

**Video**
[Screencast_04.01.2024_18:37:53.webm](https://github.com/yairEO/tagify/assets/4313099/460ebf79-2840-4692-8f2a-8c5d222c2834)

**Comment by vorant** [comment]
I have a bug in my project related to this issue.

**Comment by yairEO** [comment]
I will try to if there is a way to fix this to align both to work the same
