### ISSUE TITLE
Duplicate entry on hit Return for suggestion

### ISSUE THREAD

**Issue by jzohrab** [yairEO/tagify#1275]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**

With a whitelist of suggestions, hitting Return should enter the selected value as a tag only once.

- **What is happening instead?**

The selected value is entered twice, and the extra entry is deleted after a short delay.  Note this doesn't happen every time, I'm not sure why it occurs at all.

> https://github.com/yairEO/tagify/assets/1637133/d3b79348-7c30-4091-94ab-2c4248384724

- **What error message are you getting?**

No error, just a dup.

**This is not a critical issue!** Just looks funny for users.  Thank you very much!

**Comment by yairEO** [comment]
Hi, can you please add steps to reproduce? I cannot understand how to get to this situation

**Comment by jzohrab** [comment]
Hi @yairEO -- I can't reproduce it all the time.  Basically, I enter the full tag, and then at the end I hit "enter".  My tagify settings use a suggestion list, but are not restricted.to the whitelist (user can add new entries).

I'm using the files from the CDN referenced on the README: https://github.com/yairEO/tagify?tab=readme-ov-file#option-1---import-from-cdn   --  I downloaded these files and use them locally in my Flask project.

If there is something more up-to-date I should use, let me know.

ps - thank you so much for your responses.  Running a free open source project of any time is a real investment of time, and a real contribution.  Much appreciated!

**Comment by yairEO** [comment]
Thanks! Yeah I've invested probably a thousand hours at least for this codebase alone, and I have many other open-source projects as well :) it's very time consuming with no benefits what so ever except satisfaction for helping developers by creating good tools

**Comment by jzohrab** [comment]
It hasn't happened for a while now, so I believe this should be closed.  If it happens again, I'll try to collect more useful information.  I'll assume it's a user error until proven otherwise.

Re the open-source and satisfaction: I hear you, I'm the same, though not on the scale of tagify.  tagify will be helping me out on my project, [Lute](https://github.com/jzohrab/lute-v3), a free open-source tool for people to learn languages through reading -- so you'll be having an impact there as well.

I'll close this issue, but perhaps in the meantime you can let me know what attribution is good for tagify.  Would an "acknowledgements" page be sufficient for you, with a brief note about your work?  Cheers and best wishes! jz

**Comment by Biszu** [comment]
I was facing the same issue. It is caused by a combination of having the whitelist fetched with Ajax and `dropdown.hide()`.

@jzohrab I see that you use Ajax for fetching the whitelist as well, and I assume you do it in a similar manner as the example in README.md (which, unfortunately, is causing issues) — see if not calling `dropdown.hide()` before making the whitelist request helps.

Kudos to @bdteo for figuring it out in https://github.com/yairEO/tagify/issues/884

**Comment by jzohrab** [comment]
Thank you @Biszu , I changed `tagify.loading(true).dropdown.hide()` to `tagify.loading(true)` and this _may_ have addressed the issue.  That changed also fixed a very small hiccup: before, I used to have to press the down arrow twice in order to get into the suggestion list; after making the change, I only have to press the down arrow once.  A small fix, but still nice.
