### ISSUE TITLE
Allow hitting TAB for autocomplete, as well as right arrow key

### ISSUE THREAD

**Issue by jzohrab** [yairEO/tagify#1276]
This is just a nice-to-have.  

Currently the code has `autoComplete: { rightKey: true },` in the settings.  

It would be very nice to have `autoComplete: { tabKey: true },` as well, as the tab key is so convenient, and using tab for autocomplete is standard for terminal-level commands in many environments.

Regards and thank you!

**Comment by yairEO** [comment]
<kbd>Tab</kbd> key currently adds the input as a tag, and is mapped just like the <kbd>Enter</kbd> key.

Actually just yesterday I've coded a new setting called `addTagOn` with the value `['blur', 'tab', 'enter']` so if one would want to **not** have the <kbd>Tab</kbd> key creating a tag of whatever is typed in the Tagify field, it's much easier now with this setting.

I can add `autoComplete: { tabKey: true }` setting, but for that to work, developers would have to configure the `addTagOn` setting accordingly to disable the `<kbd>Tab</kbd>` from adding a tag

**Comment by yairEO** [comment]
OK I've made it so the `tabKey` setting you've suggested will only autocomplete but won't convert it into a tag, unless `tab` is pressed again. Will be available on next Tagify release (very soon)

**Comment by Levivb** [comment]
Coincidentally, I just upgraded from 2.31.3 to 4.18.1 (I know, I know 😅). The tab key used to work in v2.31 kinda as the enter key does in in the latest version - albeit it was a bit more intuitive back then since you now have to explicitly select an option from the selection list before the enter/tab can be applied.

**Comment by jzohrab** [comment]
Thank you @yairEO , appreciate the time!

**Comment by Levivb** [comment]
It occurred to me that the required dropdown selection is only needed when working with the Ajax Whitelist (https://github.com/yairEO/tagify/tree/2d2a5a1e0e6c4a7badb7616e593634c70b3b5574?tab=readme-ov-file#ajax-whitelist)

But a second time hitting `tab` seems to be required. The first `tab` autocompletes the selected option from the dropdown and stays in edit mode and a second `tab` creates an actual tag from the addition.

See difference (.mov files):
Tagify 2.31 - 1.8MB
https://github.com/yairEO/tagify/assets/2494320/cdd32134-b0b5-4705-88bf-fc5ea9ad3671

Tagify 4.18 - 1.7MB
https://github.com/yairEO/tagify/assets/2494320/26c23d1f-042c-454b-8966-7e68a20e63c9
