### ISSUE TITLE
Problems with Dropdown and tab-to-complete (AJAX)

### ISSUE THREAD

**Issue by Maxxxel** [yairEO/tagify#128]
So i got a little problem. 

```html
<div class="modal-body" style="overflow-y:auto">
    <form id="replay-form" role="form">
        <div class="form-group">
            <input type="text" name="allies" id="allies" tabindex="1" class="form-control" placeholder="Allies (Maxxxel, Crunchy, ...)" value="" minlength="3" required>
        </div>
    </form>
</div>
```

```js
var input = document.getElementById('allies'),
	tagify = new Tagify(input, {
		whitelist: [],
		dropdown: {
			enabled: 3
		}
	});

tagify.on('input', onInput)

function onInput(obj) {
	var value = obj.detail;
	tagify.settings.whitelist.length = 0;

	if (value.value.length >= 3) {
		$.ajax({
			type: 'POST',
			url: 'getUsername.php',
			dataType: 'JSON',
			data: {v: value.value},
			success: function(result) {
				var a = [];
				
				result.map(function(el) {
					var t = el.names.replace(/\s/g, '');
					var n = t.split(",");

					for (var i = n.length - 1; i >= 0; i--) {
						var d = n[i];

						if (d.includes(value.value)) {
							a.push(d);
						}
					}
				});

				tagify.settings.whitelist = a;
				tagify.dropdown.show.call(tagify, value.value);
			}
		});
	}
}
```

Im using ajax call instead of fetch and when i enter a value i got this: https://i.gyazo.com/4447f9df4f4d06949545f896c55d5dce.gif

I see the correct value in grey but there is no drop down shown to select the value directly. Also if i press tabulator the current written word is taken instead of autocompleted one. Instead when i press right-arrow on keyboard the full word is taken.

What can i try to get the dropdown displayed?

**Comment by yairEO** [comment]
which Tagify version are you using?

**Comment by Maxxxel** [comment]
Sorry just went out, I report back in 1-2hrs.

**Comment by Maxxxel** [comment]
Im using latest version 2.6.2

Console Shows some error aswell: ```TypeError: this.DOM.dropdown is undefined 
tagify.min.js:1:12942```

**Comment by yairEO** [comment]
I don't see any problem except a minor bug which I've fixed.
did you make sure that when you do:

    tagify.settings.whitelist = a;

`a` is an array?

### You wrote:

    dropdown: {
        enabled: 3
    }


Which means the dropdown will only show if the first 3 characters match any first 3 first letter of a string in the _whitelist_. maybe you don't have any match

**Comment by yairEO** [comment]
yes you are correct, it wouldn't work. it would have helped if you posted your AJAX whitelist as well (for a specific input value)

**Comment by Maxxxel** [comment]
```js
["Maxxxel", "Crunchy"]
```

**Comment by yairEO** [comment]
I can't reproduce the problem. Can you please try verison `2.6.3` and let me know?

**Comment by Maxxxel** [comment]
After my breakfast :)

**Comment by Maxxxel** [comment]
So with 2.6.3 tabulator works now, but still no dropdown

**Comment by Maxxxel** [comment]
i also tried:
```js
var input = document.querySelector('input'),
    tagify = new Tagify(input, {
        whitelist : ['aaa', 'aaab', 'aaabb', 'aaabc', 'aaabd', 'aaabe', 'aaac', 'aaacc'],
        dropdown : {
            classname : "color-blue",
            enabled   : 3,
            maxItems  : 5
        }
    });
```
with same results, maybe its because of the modal + form combination, i will try it on a standard input filed in body

**Comment by Maxxxel** [comment]
Ok i found out, that as soon as i use it inside a modal, dropdown isnt working anymore

**Comment by yairEO** [comment]
then it's probably a CSS issue with `z-index`

you can edit it to be higher value than your modal's

**Comment by Maxxxel** [comment]
I'll try tomorrow and report back

**Comment by yairEO** [comment]
@Maxxxel - You forgot to report back ;)

Anyway, letting you know I will be releasing a new major version `v3` this week, so keep tuned.

**Comment by Maxxxel** [comment]
Ye was the z index. Nice to hear!

**Comment by suresh121** [comment]
In my code had,
whitelist : ['sss', 'aa>5', 'zz>23']

**Comment by asaduli** [comment]
> Ye was the z index. Nice to hear!

how you solved z index issue ?? My dropdown work but under the modal
