### ISSUE TITLE
Empty (no value) edited tag is not removed when pressing `esc` key

### ISSUE THREAD

**Issue by billy0222** [yairEO/tagify#1282]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codepen.io/vsync/pen/wvGaKxd

### Explanation

- **What is the expected behavior?**
1. After added tag, press escape does not remove it.
2. Does not response to dropdown.enabled: 0 to show dropdown immediate after addEmptyTag()

**Comment by billy0222** [comment]
Thanks a lot!
Can you also fix the second problem?

**Comment by yairEO** [comment]
Well that is a separate thing for which I will need to create a separate ticket and look into it.

**Comment by billy0222** [comment]
The new release throw an error on the demo page again. 

Empty (no value) edited tag is not removed when focus out.

> Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
>     at _.onEditTagDone (tagify:26:45526)
>     at _.onEditTagBlur (tagify:26:33430)

**Comment by yairEO** [comment]
@billy0222 - Thanks a lot for reporting, am fixing it now

**Comment by billy0222** [comment]
When the dropdown list is re-filtered and the suggestions list is visible again (previously hidden since no match), then press "esc", the tag is removed, but the dropdown list is still shown.
