### ISSUE TITLE
Template with select mode

### ISSUE THREAD

**Issue by balex25** [yairEO/tagify#1283]
About [https://github.com/yairEO/tagify/issues/845](https://github.com/yairEO/tagify/issues/845)

How to style tag in select mode?

```
        tag(tagData) {
          console.log(tagData);
          return `
            <tag title="${tagData.value}"
                 contenteditable='false'
                 spellcheck='false'
                 tabIndex="-1"
                 class="${this.settings.classNames.tag} ${tagData.class ? tagData.class : ''}"
                 ${this.getAttributes(tagData)}>
              <x title='remove tag' class="${this.settings.classNames.tagX}"></x>
              <div>
                <span class="${this.settings.classNames.tagText}">
                  ${tagData.icon ? `${tagData.icon} ` : ''}${tagData.name ? `${tagData.name}` : `${tagData.value}`}
                </span>
              </div>
              <h1>xxx</h1>
            </tag>
          `;
        },
```

Also, I checked out `[https://github.com/yairEO/tagify/blob/master/src/parts/templates.js](https://github.com/yairEO/tagify/blob/master/src/parts/templates.js)` and I don't see any template to customize that part of the tag.

HTML OUTPUT:
![chrome_TMcphRv8dR](https://github.com/yairEO/tagify/assets/37195461/dcc08cf4-fde6-403d-b3a5-5d5b9350e1a2)

It is possible to style this part of the tag?
`<span contenteditable="true" tabindex="0" data-placeholder="Enter value..." aria-placeholder="Enter value..." class="tagify__input" role="textbox" aria-autocomplete="both" aria-multiline="false" data-last-active-input="" data-suggest="">positive</span>`

**Comment by yairEO** [comment]
Currently no, I apparently forgot about this, I will take a look and see what would be the best way to support what you want

**Comment by yairEO** [comment]
This has been fixed and now you can use the `tag` template to modify the selected item when in `select` mode
