### ISSUE TITLE
Duplicated item does not appear in dropdown even though `duplicates` is set to `true` when whitelisting a list of strings

### ISSUE THREAD

**Issue by nop33** [yairEO/tagify#1284]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/p/sandbox/tagify-react-issue-template-forked-gsh23y

### Explanation

- **What is the expected behavior?**

Given the following settings, I would expect that duplicates are allowed:

```tsx
<Tags
  whitelist={["a", "b", "c"]}
  settings={{
    duplicates: true,
    dropdown: {
      enabled: 1,
    }
  }}
/>
```

- **What is happening instead?**

When I type "a" for the second time, the dropdown does not show up

- **What error message are you getting?**

The item "a" is not included in the dropdown

**Comment by yairEO** [comment]
See the setting `includeSelectedTags`

https://github.com/yairEO/tagify#settings

See discussion here: https://github.com/yairEO/tagify/issues/1098
