### ISSUE TITLE
Selecting with properties other than value doesn't work

### ISSUE THREAD

**Issue by jjxtra** [yairEO/tagify#1287]
I can type in the text box and the dropdown appears and displays my name property. But when I click to select an item, nothing happens. How do I make it put the name property in the tag text box?

I tried using transformTag, but it's not called until I exit the text box. That's not what I want. I need it to put name in as the tag.
```js
// my initialization code
var input = document.querySelector(sel);
var options =
{
  enforceWhitelist: true,
  whitelist: whitelist // array of objects [{ 'id':...,'name':...}]
};
options.dropdown =
{
  mapValueTo: 'name',
  searchKeys: ['name']
};
var tagify = new Tagify(input, options);
```

**Comment by jjxtra** [comment]
Ended up mapping my name property to value.

**Comment by yairEO** [comment]
You should always have a `value` property in the whitelist if the whitelist items are of type `Object`, but to actually see that text when the tag is selected, you aught to use the `tagTextProp` setting.
