### ISSUE TITLE
Not allowing to edit the last tag

### ISSUE THREAD

**Issue by TinaDimitrovska** [yairEO/tagify#1288]
When you have set property maxTags for example to 4, when you want to edit the last Tag, and you type something in it and press enter nothing is happening and there is not x sign, and you can`t save the edited tag. How to solve this issue?   The tag looks like this, after editing
![Screenshot from 2024-01-29 12-33-16](https://github.com/yairEO/tagify/assets/93677200/c8799c6e-7a26-4afb-af88-396969e429d4)

**Comment by yairEO** [comment]
fixed in https://github.com/yairEO/tagify/releases/tag/v4.19.1
