### ISSUE TITLE
If tag value ends with space whitelist not working

### ISSUE THREAD

**Issue by akursat** [yairEO/tagify#129]
Hi,
I'm using tagify 2.6.2 with ajax autocomplete.
here is my init.
```
let tagify = new Tagify(input, {
   enforceWhitelist: true,
   whitelist: []
});
```
Also, I'm using function onInput(e) to clear and fill whitelist and my data.
If a tag name ends with space like "Test ", tagify  select the element but selected element disappearing instantly.

**Comment by yairEO** [comment]
I don't see this happening with `2.6.3` so please try and tell me (`2.6.3` was deployed a few minutes ago)

**Comment by pedromschmitt** [comment]
Hi! 
I have the same problem! 

With a whitelist and enforceWhiteliste: true, if a value has space at the end, like "Catan ", and the user clicks on the tag, it is inserted without space and removed after.

I'm using version 3.20.3.

_(Great work by the way yairEO. Tagify is an awesome plugin and helps a lot)_

**Comment by yairEO** [comment]
@pedromschmitt - have you tried setting the `trim` setting to `false` ?

https://github.com/yairEO/tagify#settings

**Comment by yairEO** [comment]
Please provide a demo page with steps to reproduce.

I've made one for you and everything works as expected:
https://jsbin.com/zejuqezuga/edit?html,js,output

You can clone mine and change.

Type: `aa`, `ee` and so on. works fine even if a whitelist item has a trailing space.
