### ISSUE TITLE
Selecting a second time breaks

### ISSUE THREAD

**Issue by userman123** [yairEO/tagify#1291]
The fist time I click arrow in select mode drop down, it works. 

The second time, nothing happens - I click a couple more times and then I see "tag element doesn't exist" in the console.

Happening on v4.19.1

https://github.com/yairEO/tagify/assets/5345477/471bd7de-0ad5-40b4-8713-e596bba14712

Many thanks

**Comment by yairEO** [comment]
only happens when clicking on the `down` arrow. will fix now
