### ISSUE TITLE
userInput: false not working dropdown

### ISSUE THREAD

**Issue by NaturalHokke** [yairEO/tagify#1293]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/sesuyukire/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Click to display dropdown and select input values

- **What is happening instead?**
If nothing is selected, dropdown is displayed, but if it is already selected, dropdown is not displayed

- **What error message are you getting?**
nothing

**Comment by jzohrab** [comment]
I'm not the project owner, just saw this issue.

You have "mode: select" in your js.  From the docs, "Use select for single-value dropdown-like select box. See mix as value to allow mixed-content. The 'pattern' setting must be set to some character."

If you remove "mode: select", it appears to behave more like you want.  (perhaps!)

**Comment by yairEO** [comment]
Fixed now in [`v4.20`](https://github.com/yairEO/tagify/releases/tag/v4.20.0)
