### ISSUE TITLE
Pasting into autocomplete/suggestion box doesn't fire 'input' event -- Possible workaround given in jsbin

### ISSUE THREAD

**Issue by jzohrab** [yairEO/tagify#1294]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Description of issue and demo of possible solution

Users wanted a "paste" to still open the ajaxed whitelist.  As it is, paste doesn't fire the 'input' event, so the whitelist wasn't getting opened.  After some playing, I came up with a workaround solution in the JS bin demo:

https://jsbin.com/zadaded/edit?html,js,output

I'd like to make sure that this solution isn't completely ridiculous -- I may have missed something in the docs, though I read through everything.

## Solution notes

Essentially this required adding a paste hook:

```
      // Use a hook to fire the onInput event!
      // Pasting from the clipboard doesn't fire the
      // tagify.on('input') event, so intercept it and handle
      // it manually.
      hooks: {
        beforePaste : function(content) {
          return new Promise((resolve, reject) => {
            clipboardData = content.clipboardData || window.clipboardData;
            pastedData = clipboardData.getData('Text');
            console.log("pasting => " + pastedData);
            let e = {
              detail: { value: pastedData }
            };
            onInput(e);
            resolve();
          });
        }
      },
```

With the hook active, the paste opened the whitelist as expected:

> <img width="300" alt="image" src="https://github.com/yairEO/tagify/assets/1637133/81af4ef4-1b7d-462c-ad46-11f683f797ec">

Without the hook, paste would just paste the value:

> <img width="316" alt="image" src="https://github.com/yairEO/tagify/assets/1637133/0c47d387-ff10-408c-8c7f-119b707d80b8">

If this is a reasonable solution, I'm happy to post a patch to the README.md.

Thanks @yairEO !

**Comment by yairEO** [comment]
I've just released [`v4.20`](https://github.com/yairEO/tagify/releases/tag/v4.20.0) which includes a `paste` event listener:

```js
const tagify new Tagify(...)

tagify.on('paste', e => console.log(e))
```
