### ISSUE TITLE
Tag element does not exist

### ISSUE THREAD

**Issue by russssl** [yairEO/tagify#1295]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/p/devbox/tagify-bug-7lryqm?file=%2Findex.html%3A35%2C1

### Explanation
When `enforceWhitelist: true` enabled, input is empty and Backspace clicked 'tag element does not exist' appears in the console.
It does not affect the input itself just a little annoying seeing spam in the console
- **What is the expected behavior?**
No warning
- **What error message are you getting?**
 tag element doesn't exist undefined undefined

**Comment by russssl** [comment]
@yairEO Why did you decide to go with default enabled in v1.23?

**Comment by yairEO** [comment]
@russssl -because I think it is helpful for developers, and non-developers (users) are not working with their console open anyway so it doesn't matter in that case

**Comment by russssl** [comment]
> @russssl -because I think it is helpful for developers, and non-developers (users) are not working with their console open anyway so it doesn't matter in that case

yes, I understand your logic of course but in my use case, it just seems wrong to have a warning when I did nothing wrong or the code is not wrong just I have no tags inside input. But anyway, I turned it off so it does not bother me anymore :)

**Comment by yairEO** [comment]
I have now fixed the core of this issue and you will not see this specific error again even if you enable debugging. will push a new version today, soon

**Comment by russssl** [comment]
> I have now fixed the core of this issue and you will not see this specific error again even if you enable debugging. will push a new version today, soon

Awesome

**Comment by yairEO** [comment]
done https://github.com/yairEO/tagify/releases/tag/v4.25.0

**Comment by russssl** [comment]
🫡
