### ISSUE TITLE
Duplicates with mixed mode

### ISSUE THREAD

**Issue by DMeganoski** [yairEO/tagify#1297]
As far as I can tell, it seems this issue has been brought up and addressed already, so perhaps it's something I am doing wrong.

But the demo below demonstrates how 'duplicates' seems to have no effect.

I am just trying to make a similar @tag mechanism to most social media sites.

But I am setting a UID as the 'value' and showing instead this 'identifier', so that if an identifier changes I can update the appropriate tag, without losing the reference to the item itself.

How can I make sure we can use the same tag more than once in the same field?

### Demo Page 
https://jsbin.com/cegepatuso/1/edit?html,js,console,output

**Comment by yairEO** [comment]
set the nested setting `includeSelectedTags: true` within the `dropdown` setting

it's in the README :)
