### ISSUE TITLE
CSS bug with certain fonts

### ISSUE THREAD

**Issue by streamworksaudio** [yairEO/tagify#1299]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I have noticed that when using certain fonts there seems to be a CSS style issue somewhere that is resulting in a line running horizontally through the tag when hovering over it.

If you go to the sample on CodePen (https://codepen.io/vsync/pen/PoNqYVY) and import the Google Font Open Sans into the styles using:

`@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');`

Then use `'font-family: "Open Sans";'` for the .tagify style you will see what I mean.  Below is a screenshot.

<img width="228" alt="Screenshot 2024-02-20 at 9 15 47 AM" src="https://github.com/yairEO/tagify/assets/20709333/6d81d2fe-5abc-48b1-95d7-e864d18a7cfa">

This seems to happening only with certain fonts.  The default font on CodePen (sans-serif) does not have this issue, nor does 'Roboto' from Google Fonts - it appears to be with just some fonts.

**Comment by hunxjunedo** [comment]
it's because some fonts are a bit bigger than the others, and unfortunately the tag doesn't have background color.

**Comment by yairEO** [comment]
That is not a bug - simply adjust the CSS variable `--tag-inset-shadow-size`.
You can see all the variables on the top-right side of the demos page
