### ISSUE TITLE
Add limit of tags

### ISSUE THREAD

**Issue by ElvenDev** [yairEO/tagify#13]
Another (hopefully small) feature what I thought would be nice (for me needed, lol):

Add possibility to limit the amount of tags.

So, basically, once you hit a certain amount (for example 4), it won't allow you to add any more tags.

I hope I am not becoming annoying here :)!

**Comment by yairEO** [comment]
This can be done so very simply by using the "add" callback on the tagify instance:

    // create a Tagify component
    var tagify = new Tagify(input2, {
        callbacks : { add:onAddTag }
    });


    // add tag callback
    function onAddTag(e){
        // limit to "5" tags
        if( e.detail.index > 4 )
            tagify1.removeTag(4);
    }

**Comment by yairEO** [comment]
Also added a `maxTags` option (see demo page)

**Comment by ElvenDev** [comment]
@yairEO Another note, what I got while I talked with another person while doing my project demo and touched this tagify: "While tags are limited, maybe deny possibility to add new tags at all, as it might be confusing", I do not know however it is even possible, if it is input and all. Just wanted to share thoughts.

I understand that it will activate "Duplicate" event, if it gets denied as over tag limit? This way it is at least possible to add personal notification somewhere with javascript.

**Comment by yairEO** [comment]
I can expose custom events for a "tag denial" which will detail the denial reason so you could, for example, print a message on the page which explain what happened. 

In my [demo page](https://yaireo.github.io/tagify/) I write in the placeholder `write up to 5 tags` so the user will know there's a limit

**Comment by ElvenDev** [comment]
That would be actually really wise. Would offer possibilities to do more with it.

**Comment by Pekkonen** [comment]
@yairEO 
Can I open this issue?
```
// add tag callback
function onAddTag(e){
    // limit to "5" tags
    if( e.detail.index > 4 )
        tagify1.removeTag(4);
}
```
This code return an error in Chrome console:
```
tagify.min.js:1 Uncaught TypeError: Cannot read property 'value' of undefined
    at tagify.min.js:1
    at Array.findIndex (<anonymous>)
    at f.getTagIdx (tagify.min.js:1)
    at tagify.min.js:1
    at Array.reduce (<anonymous>)
    at f.removeTags (tagify.min.js:1)
    at Text.onAddTag (test.html:325)
    at f.trigger (tagify.min.js:1)
    at tagify.min.js:1
    at Array.forEach (<anonymous>)
```
Can you check it?
Maybe for new version of tagify we need to use other handle for limit count of selected tags?
Thanks

**Comment by yairEO** [comment]
@Pekkonen - this code makes no sense. If you want to limit the tags allowed then use the appropriate [setting](https://github.com/yairEO/tagify#settings) for that: `maxTags: 4` and any tag after the 4th will be deleted automatically. 

Also, to remove the last tag, you can simply call `tagify1.removeTag()` without parameters

**Comment by sashadorval** [comment]
> @yairEO Another note, what I got while I talked with another person while doing my project demo and touched this tagify: "While tags are limited, maybe deny possibility to add new tags at all, as it might be confusing to user when it simply disappears", I do not know however it is even possible, if it is input and all. Just wanted to share thoughts.
> 
> I understand that it will activate "Duplicate" event, if it gets denied as over tag limit? This way it is at least possible to add personal notification somewhere with javascript.

I agree that it could be more clear as to why the tag was removed when `maxTags` is reached. We chose to change the visible text of the tag that gets added and then shortly removed to be 'Maximum 3 items':
```javascript
var tagify = new Tagify(input, {
	validate: function (tag) {
		var max = 3;
		if (tagify.value.length < max) {
			return true;
		}
		tag.value = 'Maximum ' + max + ' items';
	}
});
```
Note that **you can't use the `maxTags` Tagify property with this method**.

I tried setting the `maxTags` property on the Tagify object to 3 and referencing `tagify.settings.maxTags` in the validate function, but it seems like `validate` is not called when you reach maxTags set on the object.

**Comment by yairEO** [comment]
@sashadorval - *"it could be more clear as to why the tag was removed when `maxTags` is reached."*

If you want it to be clearer than you can add a message on your website/app that explains the user there is a maximum tags limit and also you can count it, or do it by any other way you see fit to explain this to your users. This explanatory part up to the developer to handle, and not *tagify*
