### ISSUE TITLE
How to disable userInput if user paste a valid tag and need no more tags.

### ISSUE THREAD

**Issue by AhsanBhatti786** [yairEO/tagify#1300]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

    <script type="text/javascript">
        function enableTheLoaderFunction() {
            var loader_name = document.getElementById('loader-4');
            loader_name.style.display = 'block';
        }
        var addProductBtn = document.getElementById('add-product-btn-imp');
        var productNameInput = document.getElementById("id_product_name");
        var productURLInput ;
        var isValidationPass = false;
            function onInvalidTag(e){
                document.getElementById("error_message_key_keywords").style.display = "block";
                handleInputValidation();
                addProductBtn.disabled = true;
            }
            function onValidTag(e){
                document.getElementById("error_message_key_keywords").style.display = "none";
                handleInputValidation();
                addProductBtn.disabled = false;

            }
            var jqTagify = $('#tagify-urls').tagify(
                {
                    maxTags: 1,
                    userInput: true,
                    validate: function (tagText) {
                        // Custom validation function
                        handleInputValidation();
                        // console.log("hello tag")
                        if (!tagText.value.startsWith("http://") && !tagText.value.startsWith("https://")) {
                            this.settings.userInput = true;
                            onInvalidTag();
                            return {
                                message: 'Please enter a valid URL starting with "http://" or "https://"',
                                valid: false,
                            };
                        }
                        this.settings.userInput = false;
                        productURLInput = tagText.value;
                        console.log("productURLInput",productURLInput);
                        onValidTag();
                        return true;
                    },
                    hooks: {
                        beforeRemoveTag : tags => {
                            // check if the last tag is about to get removed and if so, cancel the whole removal operation
                            exiting_tags = jqTagify.value.map(function(t) {
                                return t.value;
                            });
                            if (exiting_tags.length <= 1) {
                                return new Promise((resolve, reject) => {
                                    $('#add-product-btn-imp').attr('disabled', true);
                                    // jqTagify.settings.userInput = true;
                                    handleInputValidation();
                                    resolve()
                                })
                            }
                            else if (exiting_tags.length === 1) {
                                return new Promise((resolve, reject) => {
                                    // jqTagify.settings.userInput = false;
                                    $('#add-product-btn-imp').attr('disabled', false);
                                    $('input[name="urls"]').prop('disabled', true);
                                    resolve()
                                })}
                            else {
                                return new Promise((resolve, reject) => {
                                    resolve()
                                })
                            }
                        }
                 }
                })
                .on('add', (e, tagify) =>{
                    jqTagify.settings.userInput = false;
                })
                .on('invalid', (e, tagify) => {
                    if(tagify.message.message != "number of tags exceeded"){
                        addProductBtn.disabled = true;
                    }
                })
                // console.log(jqTagify.userInput());
            var jqTagify = jqTagify.data('tagify');

            function handleInputValidation() { 
                var productName = productNameInput.value.trim();
                if (productURLInput) {
                    var productURL = productURLInput;
                } else {
                    var productURL = "";
                }
                isValidationPass = (productName !== "" && !productName.startsWith(" ")) && 
                                ((productURL !== "" && productURL.startsWith("http://")) || 
                                    (productURL !== "" && productURL.startsWith("https://")));
                addProductBtn.disabled = !isValidationPass;
            }
            // productNameInput.addEventListener("input", handleInputValidation);
            // $input.on('add', handleInputValidation);
            $('#tagify-urls').on('input', handleInputValidation);
            $(document).on('click', '.tagify__tag__removeBtn', function() {
                addProductBtn.disabled = true;
            });
        </script>

### Explanation

- **When user enters a url first it will validate urls then if found valid tag it should enable ADD button and along with disable the further user inputs.**

- **i tried many method but nothing is working it works till valid tag and also enables ADD button but after userInput is not disabled**

![image](https://github.com/yairEO/tagify/assets/159757263/695074a9-2d55-427d-ac79-feec90cfcf75)

**Comment by yairEO** [comment]
why do you need a tags component if you only allow one single tag?

**Comment by AhsanBhatti786** [comment]
i have many other forms where i m using tagify. but due to UI restriction i have to convert it to tag also in future they can be 20. 
but the main important demand is input field must be disabled when reaches required numbers of valid tags.

**Comment by yairEO** [comment]
# Here are 2 ways to do that:

### Listen to `change` event and set the `setContentEditable` method accordingly:

https://jsbin.com/sezuraf/edit?html,js,output:

```js
var input = document.querySelector('input')
var tagify = new Tagify(input, {maxTags: 1})

tagify.on('change', () => {
  tagify.setContentEditable(!tagify.hasMaxTags())
})
```

### Or using CSS:

https://jsbin.com/yowibez/1/edit?html,css,js,output

```css
.tagify--hasMaxTags .tagify__input{
  display: none;
}
```

**Comment by AhsanBhatti786** [comment]
Thanks
Can i get your whatsapp Contact number?

**Comment by yairEO** [comment]
sorry that is too personal information..

**Comment by AhsanBhatti786** [comment]
Hi
I hope you are well.
i got an issue need your help.
        function enableTheLoaderFunction() {
            var loader_name = document.getElementById('loader-4');
            loader_name.style.display = 'block';
        }
        var addProductBtn = document.getElementById(
'add-product-btn-link-booster');
        var productNameInput = document.getElementById("id_product_name");
        var productURLInput;
        console.log(productNameInput);
        var productTargetUrlInput;
        console.log(productTargetUrlInput);
            function onInvalidTag(e){

document.getElementById("error_message_key_keywords").style.display
= "block";
                handleInputValidation();
                addProductBtn.disabled = true;
            }
            function onValidTag(e){

document.getElementById("error_message_key_keywords").style.display
= "none";
                handleInputValidation();
                addProductBtn.disabled = false;
            }
            var $input = $('#tagify-urls')
                .tagify({
                    maxTags: 50,
                    backspace: "edit",
                    // setDisabled: true,
                    addTagOnBlur: true,
                    validate: function (tagText) {
                        // Custom validation function
                        handleInputValidation();
                        if (!tagText.value.startsWith("http://") && !
tagText.value.startsWith("https://")) {
                            onInvalidTag();
                            return {
                                message: 'Please enter a valid URL starting
with "http://" or "https://"',
                                valid: false
                            };
                        }
                        productURLInput = tagText.value;
                        onValidTag();
                        handleInputValidation();
                        return true; // Tag is valid
                    },
                    hooks: {
                        beforeRemoveTag : tags => {
                            // check if the last tag is about to get
removed and if so, cancel the whole removal operation
                            exiting_tags = jqTagify.value.map(function(t) {
                                return t.value;
                            });
                            if (exiting_tags.length == 0 && exiting_tags.
length == 50) {
                                return new Promise((resolve, reject) => {
                                    $('#add-product-btn-link-booster').attr(
'disabled', true);
                                    resolve()
                                })
                            }
                            else {
                                return new Promise((resolve, reject) => {
                                    resolve()
                                })
                            }
                        }
                 }
                })
                .on('invalid', (e, tagify) => {
                    if(tagify.message.message != "number of tags exceeded"){
                        addProductBtn.disabled = true;
                    }
                }) in this i am validating the URL with basic string
matching but now i wanna do it by Regex. so I have created this below code
validate: function (tagText) {
    // Custom validation function
    handleInputValidation();
    // Regular expression for URL validation
    var urlRegex = /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([/\w
.-]*)*\/?$/;
    if (!urlRegex.test(tagText.value)) {
        onInvalidTag();
        return {
            message: 'Please enter a valid URL',
            valid: false
        };
    }
    productURLInput = tagText.value;
    onValidTag();
    handleInputValidation();
    return true; // Tag is valid
},
But issue is when i use this Validate tagify stop working. how to resolve
it.
