### ISSUE TITLE
addMixTags throws 'Uncaught ReferenceError: tagElm is not defined'

### ISSUE THREAD

**Issue by sisackov** [yairEO/tagify#1301]
## Description
In version 4.21.1, calling the `addMixTags` method throws an `Uncaught ReferenceError: tagElm is not defined` error. 

## Reproduction Steps
1. Call the `addMixTags` method.
2. Observe the error in the console.

## Expected Behavior
The `addMixTags` method should execute without throwing an error.

## Actual Behavior
An `Uncaught ReferenceError: tagElm is not defined` error is thrown. The error stack trace is as follows:
  Uncaught ReferenceError: tagElm is not defined
        at 8657.js:2:61085
        at Array.forEach (<anonymous>)
        at z.addMixTags (8657.js:2:60987)
        
## Possible Solution
https://github.com/yairEO/tagify/blame/9bd64ed14cb951b27fb23e3bae2bef7f58128ee0/src/tagify.js#L1390
The error seems to originate from this line in the code. It appears that the correct line should be:
```javascript
this.postProcessNewTagNode(newTagNode.tagElm, newTagNode.tagData)

**Comment by yairEO** [comment]
please provide an example. when are you calling it and which what parameters?

**Comment by yairEO** [comment]
I've created a test page (you should have reported a bug using a test page) and I do not see any error when calling the method `addMixTags`:

https://jsbin.com/xibukudave/1/edit?html,js,output

**Comment by pavel-nitka** [comment]
@yairEO  this issue related to 4.21.2 version but jsbin uses 4.20.0 and addTags.
If you will change version and will use addMixTags you will be able to see error
![image](https://github.com/yairEO/tagify/assets/43527493/a46fa429-836e-4593-a20a-3ed50d3ce31b)

**Comment by yairEO** [comment]
Your demo isn't configured for `mix` mode but you are using the `addMixTags` method nonetheless.

**Comment by sisackov** [comment]
Sorry @yairEO, initial issue lacked details.

The problem is with React MixedTags component. 
This is an approximate implementation of how we use it:
[https://github.com/yairEO/tagify/issues/1301](CodeSandbox example)

**Comment by yairEO** [comment]
what *"CodeSandbox example* do you refer to? there is no link. please re-check

**Comment by sisackov** [comment]
> what _"CodeSandbox example_ do you refer to? there is no link. please re-check

https://codesandbox.io/p/sandbox/tagify-react-issue-template-forked-7hvxhs?file=%2Fsrc%2Findex.js

**Comment by yairEO** [comment]
You are correct, there is a bug. 

But also your code is incorrect:

(1) You did not import Tagify correctly:

```
// good:
import { MixedTags } from "@yaireo/tagify/dist/react.tagify";

// bad:
import MixedTags from "@yaireo/tagify/dist/react.tagify";
```

(2) Your `label` variable has interpolation within the string which should not be there:

```
// good:
const label = "Level Name";

// bad:
const label = "{Level Name}";
```

(3) you cannot define the `delimiters` setting for the `<MixedTags>` component because it's not for mixed-mode

(4) there's already a setting for `insertAfterTag` and you should very much not call `tagifyRef.current.insertAfterTag(tagElem, " ");` yourself manually because it runs automatically for each tag added using the `addMixTags()` method

**Comment by sisackov** [comment]
Thanks for the pointers - I'll update my code accordingly. 
Is there a way to track the found bug? This issue is marked closed - should I open a new one?

**Comment by yairEO** [comment]
Everything I wrote in the [README](https://github.com/yairEO/tagify#react) and the live demo CodeSandbox 

If you have any question let me know
