### ISSUE TITLE
Duplicates tag in Internet Explorer if tag has "@" symbol and delimiter is space bar.

### ISSUE THREAD

**Issue by nikbo** [yairEO/tagify#131]
I use the latest version of `tagify` (2.6.3) library and polyfill for Internet Explorer.
The code of tagify configuration:
```
  let element = document.querySelector('input');
  let tagify = new Tagify(element, {
                delimiters          : ",| ", 
                suggestionsMinChars : 3,
                maxTags             : 100,
                keepInvalidTags     : true,
                duplicates: false,
                blacklist: []
            }
```
The result is that library duplicates tags which has "@" symbol and it's delimiter is "Space" key:
![ie_issue](https://user-images.githubusercontent.com/3669062/47614782-25ed1e80-dab6-11e8-8d15-8133643f5e44.jpg)

The issue is reproducible for the latest version of IE for Windows 7, 10. 
_Updated: 2.6.4 - still reproducible._

**Comment by PeterEltgroth** [comment]
This behavior can be reproduced by entering a email address into the ADVANCE OPTIONS demo at https://yaireo.github.io/tagify/#section-advance-options using IE 11.

**Comment by PeterEltgroth** [comment]
Thank you @yairEO !
