### ISSUE TITLE
Enter tags without any delimiters in mix mode / Empty Pattern

### ISSUE THREAD

**Issue by finddeepali** [yairEO/tagify#1310]
Hi @yairEO ,
Thank you for this library. I know this issue was reported earlier https://github.com/yairEO/tagify/issues/163
But i did not understand conclusion on this.

I am using mixed mode to create a search box to support both of below use cases
1. Type a text like 'social" and show all autosuggest entries like google.
<img width="324" alt="image" src="https://github.com/yairEO/tagify/assets/17897287/7577855d-9aeb-4174-b6a3-4254b4cb6107">

2. in the same text box if i type '#mysearchtext' all entries matching  mysearchtext like github
<img width="301" alt="image" src="https://github.com/yairEO/tagify/assets/17897287/44567147-d196-4f36-a1b3-6c33ef361038">

For this reason, i cant fix my pattern to '#'. empty pattern will suit my usecase better. 

I can not have two separate input boxes for above use cases. They need to be the same input element.
Any suggestions on this is highly appreaciated.

Thank you.

**Comment by finddeepali** [comment]
hi @yairEO , 
Thanks for your reply.

I have explained partial use case above. the actual use case to be able to type free text along with showing pills from selected options (this is selected by typing # , this separate api call only for # use case).
<img width="328" alt="image" src="https://github.com/yairEO/tagify/assets/17897287/f1ada198-8352-4f40-8065-9a26b46791ff">

however in absense of # character we still need to be able to match and autosuggest based on whatever text is typed (these are different options than # ones), which is why i am looking for empty pattern

**Comment by yairEO** [comment]
The link in my last comment has a code example showcasing how it can be done
