### ISSUE TITLE
New Logger throws error when Tagify used as module

### ISSUE THREAD

**Issue by Brakebein** [yairEO/tagify#1311]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/p/sandbox/simple-tagify-setup-logger-error-95nc55

### Explanation

This applies only when Tagify is imported as module (see codesandbox &uarr;).

- **What is the expected behavior?**
When the script enters code where `Tagify.logger` is supposed to print some logs, no error should be thrown. For example, `tag element doesn't exist` in `getSetTagData()`.

- **What is happening instead?**
An error is thrown at the point where `Tagify.logger` is called.

- **What error message are you getting?**
`ReferenceError: Tagify is not defined`

The problem is that Tagify is not globally available when used as module. You would need to put the logger logic into some extra file from where it gets imported into the other files. Something like:

```js
// ./parts/Logger.js

export const Logger = {
    enabled: false,
    log(...args){ this.enabled && console.log('[Tagify]:', ...args) },
    warn(...args) { this.enabled && console.warn('[Tagify]:', ...args) }
};
```
```js
// ./parts/Logger.js

import { Logger } from './Logger';

export function getSetTagData(tagElm, data, override){
    if( !tagElm ){
        Logger.warn("tag element doesn't exist",{tagElm, data})
        return data
    }
}
```

```js
// ./Tagify.js

import { Logger } from './parts/Logger';

function Tagify( input, settings ){
    if( !input ){
        Logger.warn('input element not found', input)
    }
}

Tagify.logger = Logger;
```

**Comment by yairEO** [comment]
Fixed in https://github.com/yairEO/tagify/releases/tag/v4.23.0
