### ISSUE TITLE
Please add setting for only show dropdown when editing tag

### ISSUE THREAD

**Issue by billy0222** [yairEO/tagify#1312]
## Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://codepen.io/vsync/pen/wvGaKxd

### Issue
When dropdown.enabled set to 0, click on \<tags\> scope will show the dropdown.
Is there any way that only allow add tag / show dropdown by click add button?

### Issue 2
Added new tag and click on its border triggered blur, but the event target is itself which make it doesn't destroy that invalid tag.

**Comment by yairEO** [comment]
Hi,

As of [`v4.23`](https://github.com/yairEO/tagify/releases/tag/v4.23.0) you can change the `tagify.userInput` property to allow/disallow manual typing/pasting and this will not affect how the dropdown works when clicking the component.

I hope this helps in any way.

Regarding **issue 2**, I don't quite understand, maybe you can record a video/gif showcasing the problem and put it here

**Comment by billy0222** [comment]
https://github.com/yairEO/tagify/assets/22493672/11927330-3a73-4920-8ad4-18f997d4215d

**Comment by billy0222** [comment]
https://github.com/yairEO/tagify/assets/22493672/0e5ad995-a889-4e10-a903-f7edcb71801b

I have set the `tagify.userInput` to false, but the dropdown still pop up when I click on the `DOM.scope` (triggering `focusin`).
Also, that `focusin` event trigger when chrome focus again (changign window).

**Comment by yairEO** [comment]
I see. Investigating, thanks for the videos!

**Comment by yairEO** [comment]
This is the setup I test react version of Tagify on:

https://replit.com/@yairEO/tagify-react-demo

**Comment by yairEO** [comment]
added a new setting called `focusable` which should be set to `false` at situations such as shown in above videos
