### ISSUE TITLE
Select mode with editTags = false doesn't open dropdown (regression from 4.19.0)

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#1314]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/yisotapavi/edit?html,js,output

### Explanation

- **What is the expected behavior?**
When using Tagify in "select" mode and setting the editTags to false, clicking on the displayed option should open the dropdown list of options

- **What is happening instead?**
The dropdown list is not displayed

- **What error message are you getting?**
No error messages. I noticed the expected behavior worked till 4.18.3 but stopped in 4.19.0. Most likely due to https://github.com/yairEO/tagify/commit/bacaeb09efe04546bbed488cf5144e68da5fbf4b#diff-c25a58bcb38aa4fa6506c3017ab957bd356e6fc9f577cc256c8befe559b40050

**Comment by yairEO** [comment]
Well it's not really a bug because there is no reason at all to set `editTags` to anything in `select` mode.. This setting is only makes sense to be used for the other modes
