### ISSUE TITLE
Tagify prevents form validation

### ISSUE THREAD

**Issue by Maxxxel** [yairEO/tagify#132]
As soon as i use 
```js
var usernames= document.getElementById('userNames');
var Tag = new Tagify(usernames);
```
the form validation wont check ```userNames``` for input even if its is set to ```required```.
Once i remove the code above, the validation is working.

**Comment by yairEO** [comment]
You mean set to `required` (not "requred")

you need to change your form validation to work with Tagify, there's not other way.
