### ISSUE TITLE
Unminified tagify.js is missing

### ISSUE THREAD

**Issue by chrisdeeming** [yairEO/tagify#1324]
As title

**Comment by yairEO** [comment]
I am bringing it back today, will push soon. Have been working on a new version for a week now.

I don't know what was I thinking doing that some months ago, but I am removing the file `tagify.min.js` and will from now on only create a file in the `./dist` folder called `tagify.js` which will be minified and come with a *sourcemap* file for debugging purposes.

**Comment by yairEO** [comment]
pushed new version https://github.com/yairEO/tagify/releases/tag/v4.25.0
