### ISSUE TITLE
UNPKG CDN Redirecting to tagify.min.js for v4.25.0

### ISSUE THREAD

**Issue by vatsal-elixir** [yairEO/tagify#1326]
Loading the files from cdn, redirects to https://unpkg.com/@yaireo/tagify@4.25.0/dist/tagify.min.js,  resulting in 404 

<script src="https://unpkg.com/@yaireo/tagify"></script>

**Comment by simkimsia** [comment]
I have the same issue.

**Comment by yairEO** [comment]
1. `unpkg` not as good a CDN as `jsdelivr` 
2. you should have any specific file in the CDN URL as the `package.json` already instructs which file is the main one

please use the below URL to load Tagify (latest version):

```
https://cdn.jsdelivr.net/npm/@yaireo/tagify
```

**Comment by simkimsia** [comment]
Thank you @yairEO 

Guess i copied it since before this commit. https://github.com/yairEO/tagify/commit/3b84145e8f809bdabb19714f8603897beeb736e0
