### ISSUE TITLE
Missing "./dist/tagify.css" specifier in "@yaireo/tagify" package

### ISSUE THREAD

**Issue by russssl** [yairEO/tagify#1327]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I Just updated to .25 and got this error using vite 
![image](https://github.com/yairEO/tagify/assets/70024944/70cffe9b-de40-44f8-b6fa-351867272f8d)

**Comment by hoetaek** [comment]
@russssl how did you fix this?

**Comment by russssl** [comment]
> @russssl how did you fix this?

It was fixed in the newer versions

**Comment by hoetaek** [comment]
Thank you

**Comment by russssl** [comment]
> Thank you

No problem

**Comment by yairEO** [comment]
Sorry for all this, I assumed something which are wrong. I sometimes rush to release versions without checking everything.
