### ISSUE TITLE
Callback when original tag data has loaded

### ISSUE THREAD

**Issue by gitgitwhat** [yairEO/tagify#1330]
When you set the input value or textarea with tag data, it would be nice if there was a callback when that data has been completely processed and turned into tags.  The issue I'm running into is on Javascript heavy pages and with inputs that get preloaded with a lot of dynamic tags, the JSON string value placed inside of the value is shown until the Tagify processing is complete.  See the images below.  First one shows what I see when the page is loading and the second is when Tagify is complete.

![tag1](https://github.com/yairEO/tagify/assets/33796553/09d682bf-b65f-4774-b81c-efc2eab05dc7)
![tag2](https://github.com/yairEO/tagify/assets/33796553/184f01cf-fa10-4a5b-97dd-647255a31e46)

My thought is to initially hide the input control and then when Tagify is complete, unhide the control.  But without a "loaded" callback, that won't work.

**Comment by yairEO** [comment]
you can add the `hidden` attribute to your input fields:

```html
<input value='...' hidden />
```
