### ISSUE TITLE
Warning in Console: [Tagify]: Cannot find element in Tag template: . .tagify__tag-text

### ISSUE THREAD

**Issue by oderyn** [yairEO/tagify#1333]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
The issue can be seen on the examples page:
https://yaireo.github.io/tagify/

### Explanation
1. Open the console
2. Add a tag
3. Warning displays in the console

".tagify__tag-text" does exist where it is expected...

It seems to be caused by an extra dot: ". .tagify__tag-text" ... though a seach of the codebase did not reveal where the error is located at.

This message did not exist in 4.24.0

**Comment by yairEO** [comment]
There was a problem with Github apparently. it did not update the Tagify website after last push.

I've re-run the action to build it and now it is updated as expected
