### ISSUE TITLE
prop-type error

### ISSUE THREAD

**Issue by rohan-logicrays** [yairEO/tagify#1339]
chunk-RYOGGBNK.js?v=73822179:19441 Uncaught SyntaxError: The requested module '/node_modules/prop-types/index.js?v=73822179' does not provide an export named 'array' (at react.tagify.jsx:13:18)

**Comment by yairEO** [comment]
which version of Tagify?

As stated in the README, try this:
https://github.com/yairEO/tagify#react

![image](https://github.com/yairEO/tagify/assets/845031/229f03db-cc57-4312-a3be-fdc32044e16f)

**Comment by rohan-logicrays** [comment]
"@yaireo/tagify": "^4.21.1",
    
    import Tags from "@yaireo/tagify/dist/react.tagify";
    
    using it like this only dont know why getting this error
    chunk-RYOGGBNK.js?v=fbc70bda:19441 Uncaught SyntaxError: The requested module '/node_modules/prop-types/index.js?v=fbc70bda' does not provide an export named 'array' (at react.tagify.jsx:13:18)

**Comment by yairEO** [comment]
do you have any error if you are importing like so?

```
import Tags from "@yaireo/tagify/react"
```

**Comment by rohan-logicrays** [comment]
Failed to resolve import "@yaireo/tagify/react" from "src/utils/Input/SelectTag/SelectTagComponent.tsx". Does the file exist?

i am getting this error when i try your way

**Comment by yairEO** [comment]
Are you absolutely sure you have the latest version of Tagify?

because my official Codesandbox demo here shows it works:

https://codesandbox.io/p/sandbox/tagify-react-wrapper-oempc?file=%2Fsrc%2FCrazyTags.jsx%3A12%2C1-13%2C41

Also I have a repo showing this works:

https://github.com/yairEO/tagify-react-test/blob/master/src/App.jsx#L2

**Comment by rohan-logicrays** [comment]
I move back to the older version 
 "@yaireo/tagify": "^4.21.1",
 "@types/yaireo__tagify": "^4.18.0",
 
 now the error is different
 chunk-RYOGGBNK.js?v=80573a65:9145 Uncaught DOMException: Failed to execute 'toggle' on 'DOMTokenList': The token provided ('form-control custom-class  d-flex gap-2 ps-1 tag-placeholder ') contains HTML space characters

**Comment by yairEO** [comment]
this error does not seem to be related to Tagify. 
Also, I do not recommend downgrading as I constantly fix bugs and have very recently, in the past week, have fixed a few important ones.

Which bundler are you using and its version & your Node version?

**Comment by kiransbaliga** [comment]
I also have the smae issue. 
I am using Vite as bundler. and use node 21
The issue seems to be realted with VIte as the problem doesnt occur while i use [storybook](https://storybook.js.org/)

**Comment by yairEO** [comment]
I am using Vite in my test project also, to test Tagify, and have no problems:

[yairEO/tagify-react-test@master/src/App.jsx#L2](https://github.com/yairEO/tagify-react-test/blob/master/src/App.jsx?rgh-link-date=2024-05-06T08%3A22%3A31Z#L2)

With the minimal [config](https://github.com/yairEO/tagify-react-test/blob/master/vite.config.js)

**Comment by lweibel** [comment]
I seem to be having the same issue.

If I run your test project [yairEO/tagify-react-test@master/src/App.jsx#L2](https://github.com/yairEO/tagify-react-test/blob/master/src/App.jsx?rgh-link-date=2024-05-06T08%3A22%3A31Z#L2) but install Tagify via npm rather than as a local dependency as you have it, I can recreate the issue.

Thanks for your help btw.

**Comment by yairEO** [comment]
@lweibel - are you using the latest Tagify version?
How are you importing it? it matters if you are importing directly from the `src` folder or the `dist` folder

**Comment by lweibel** [comment]
Here are the steps I took to create the error:

```
mkdir test
cd test
git clone https://github.com/yairEO/tagify
cd tagify
npm i
cd ..
git clone https://github.com/yairEO/tagify-react-test
cd tagify-react-test
npm remove @yaireo/tagify
npm i @yaireo/tagify
```

This installed 4.27.0.

I tried importing it in all the ways you have mentioned here and in the documentation. Do you also get an error?

**Comment by yairEO** [comment]
@lweibel - have you tried what I've suggested here? https://github.com/yairEO/tagify#react

> A none-minified and raw source-code Tagify React component is exported from [react.tagify.jsx](https://github.com/yairEO/tagify/blob/master/src/react.tagify.jsx) and you can import it as seen in the below code example. This React port will only work if your bundler can handle raw source-code in ES2015+ which is better for tree-shaking.

> If you get bundling errors, import Tagify (react port) from the `dist` folder: `@yaireo/tagify/dist/react.tagify`

**Comment by lweibel** [comment]
Yes, you can try running it. I am using your repository.

**Comment by yairEO** [comment]
@lweibel - are you using `npm` or `pnpm`? it matters

**Comment by lweibel** [comment]
> Here are the steps I took to create the error:
> 
> ```
> mkdir test
> cd test
> git clone https://github.com/yairEO/tagify
> cd tagify
> npm i
> cd ..
> git clone https://github.com/yairEO/tagify-react-test
> cd tagify-react-test
> npm remove @yaireo/tagify
> npm i @yaireo/tagify
> npm run dev
> ```
> 
> This installed 4.27.0.
> 
> I tried importing it in all the ways you have mentioned here and in the documentation. Do you also get an error?

npm
