### ISSUE TITLE
Different tags for different pattern prefixes

### ISSUE THREAD

**Issue by balupton** [yairEO/tagify#134]
I'd like to have an input field where I can do something like this:

```
Buy thing for @person regarding !project #expense
```

Where `@` is person completions, `!` is project completions, and `#` is general completions.

Seems I can do this via the `https://github.com/yairEO/tagify#ajax-whitelist` example, but unsure how I would get the pattern.

**Comment by yairEO** [comment]
Hi, I will look into this over the weekend

**Comment by yairEO** [comment]
Done. see [demo page ](http://localhost/tagify/#section-mix)
