### ISSUE TITLE
Options not filtered in select mode, userInput=true and tagX=''

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#1341]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/yipohapina/1/edit?html,js,console,output

### Explanation

- **What is the expected behavior?**
In select mode, userInput=true and tagX='', clicking the dropdown icon brings the entire list of options. Clicking the dropdown icon towards the left-half of it also puts focus on the currently selected option (but right-half doesn't, surprisingly). Now, enter backspaces to edit the selected option and notice that the dropdown list is not filtered. Keep entering backspaces all the way till the selected option is blank and now start entering valid letters and see that the dropdown is not short listed either.

- **What is happening instead?**
The option list always displays the entire list of options regard less of what is currently typed. Notice that instead of bringing down the dropdown list first, if one were to directly click on the option and start typing backspaces, it shows short listed options in the dropdown.

- **What error message are you getting?**
No error messages. I noticed that when this happens, the 'edit:input' events are not getting fired.

**Comment by yairEO** [comment]
Thanks for reporting. will create a fix shortly
