### ISSUE TITLE
A double tag is created for delimiter when typed

### ISSUE THREAD

**Issue by maxi-amodei** [yairEO/tagify#1343]
DEMO:
![CleanShot 2024-05-09 at 18 16 36](https://github.com/yairEO/tagify/assets/70491418/0c709e53-d62a-4d49-bfd0-79e1283b50d1)

**Comment by maxi-amodei** [comment]
Its an issue when the automatic duplicate removal is deactivated

**Comment by yairEO** [comment]
what are the steps to reproduce please?

**Comment by maxi-amodei** [comment]
Thanks for the quik response:
Go to official page: https://yaireo.github.io/tagify/
press comma (') on any if the first two inputs
