### ISSUE TITLE
Tagify selct mode incorrect behavior

### ISSUE THREAD

**Issue by russssl** [yairEO/tagify#1346]
Hi. Thank You for the amazing job. I have found some bugs with the `select` mode. 
1. So pre 4.19 everything was alright. However, in 4.19 you changed the behavior of the select mode so that the tag could be removed letter by letter. This leads to unexpected behavior like removing the whole words not enabling the `change` event till I click out of input and the `blur` event fires (and consequently `change` does). 
2. After 4.20 new bug appeared, so clicking into a tag with `tagify--select` class does not focus on input. Only clicking into `tagify__input` (wich is significantly smaller) results in focusing the input. I had to manually track clicks on `tagify--select` and making it work by  `tagify__input.focus()`
3. Version 4.22 has one more very significant error. So after selecting a tag and removing it something crashes probably, changes are not being made, and dropdown stops showing

	Bugs 2-3 I was not able to reproduce them, so probably they appear because I use Vue so it might be the case. But still letting you know. Bug 1 was easy to reproduce just by creating a basic `select` tagify. Versions 22+ have the same issues mentioned earlier

**Comment by yairEO** [comment]
but what about the current `4.26.5` version? older versions are irrelevant because nobody should use nothing except the newest as I constantly find & fix bugs

**Comment by russssl** [comment]
> Thanks!
> 
> But what about the current `4.26.5` version? bugs in older versions are irrelevant because nobody should use nothing except the newest as I constantly find & fix bugs.
> 
> Regarding your first point, I don't see any issue with it, as it is expected to fire a `change` event only on blur

but is there an option to fire it in change for example? because when whole word was deleted it was more convenient

**Comment by yairEO** [comment]
I will look into it

**Comment by yairEO** [comment]
I'm confused how do you *"use tagify for the users' list and show user names as tags"* if the title of this issue is about "select mode", which mean only a single option may be selected (there are no tags in this mode)

**Comment by yairEO** [comment]
what do you mean `a divided tag`?

can you please re-explain to me what is the issue (with the latest Tagify version)? 
I cannot understand. please explain it step-by-step what are you doing and what you expect to happen and what happens instead

**Comment by yairEO** [comment]
closing as stale
