### ISSUE TITLE
We Insert HTML Tags Or some text between '<' and '>' its remove from textarea when edit 

### ISSUE THREAD

**Issue by garvindankursoftware** [yairEO/tagify#1352]
## Prerequisites

- [ ✔] I am running the latest version
- [✔ ] I checked the documentation and found no answer
- [ ✔] I checked to make sure that this issue has not already been filed

### Demo Page - *clone one of the below:*

https://jsbin.com/jekuqap/edit?html,js,output

![1st image](https://github.com/yairEO/tagify/assets/126649206/b5a5f060-bf1c-4aae-84d9-8e9e553ab71e)
1st image text of my input

![2nd image](https://github.com/yairEO/tagify/assets/126649206/5dc6d067-aa5b-41be-8e9a-ba7eb74ee3ca)
2nd image when textarea convert to tagify and try to edit my input

**Comment by yairEO** [comment]
I will fix this, thanks for reporting

**Comment by yairEO** [comment]
I don't see any limitation on Tagify's side. please check you backend if your content is being sanitized. 

Also, you did not add the required **demo page** but simply left the default one, which isn't helpful.

Also, you did not write which steps are needed to reproduce this. 
Please rectify your issue so I could continue with the investigation

**Comment by yairEO** [comment]
closing as OP is unresponsive
