### ISSUE TITLE
On mobile device keyboard automatically adds space after dot type so it's not possible to write an email to tag

### ISSUE THREAD

**Issue by DontGiveAFck** [yairEO/tagify#1353]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/bekowigaco/1/edit?html,css,js,console,output

### Explanation

- **Preconditions**
1. On Android device autospace after dot feature enabled in keyboard settings. (probably this keyboard feature also available for ios) - I didn't do anything to enable this feature, so it was enabled by default
2. tags pattern is email regex.
3. space should be in delimiters list

- **What is the expected behavior?**
When user adds new tag and write email to it after he clicks on dot device keyboard doesn't add space after dot entering so user can finish.

- **What is happening instead?**
When user adds new tag and write email to it after he clicks on dot device keyboard automatically adds space after dot so user can't complete email entering.

- **How it might me fixed**
After some searching I found that if input is `<input>` element with `type="email"` device keyboard doesn't add space automatically.
Maybe it's possible to allow input elm to be overridden in templates obj?

https://github.com/yairEO/tagify/assets/24360535/dfeda95c-4d18-4e48-8636-4e1948666e65

**Comment by DontGiveAFck** [comment]
@yairEO issue still exists:


https://github.com/user-attachments/assets/2b082254-19ab-4029-b5d6-26ace7998055

**Comment by DontGiveAFck** [comment]
@yairEO 

hitting backspace after tag created deletes tag:

https://github.com/user-attachments/assets/4e6dc146-db9e-413b-823c-9ba7dc585421

**Comment by danziv** [comment]
I have this issue as well.

Is this fixable?

**Comment by yairEO** [comment]
> @yairEO
> 
> hitting backspace after tag created deletes tag:
> 
>  2024-08-28.16.25.18.mp4

why wouldn't it delete the tag? that is expected

**Comment by DontGiveAFck** [comment]
@yairEO I added this video because you asked about it here:


> does hitting backspace to deleted the auto-added space and continuing typing solves this?

(Sorry if I didn't get your question correctly)

but original issue still exists

**Comment by yairEO** [comment]
@DontGiveAFck - I don't know how to solve this problem
