### ISSUE TITLE
Curly braces not working for tags even with mixTagsInterpolator in settings

### ISSUE THREAD

**Issue by hritikb27** [yairEO/tagify#1354]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**ISSUE**
I want to add tags whenever the content is inside curly braces, so if {{tag1}} is there in input field it would become a tag. I tried searching and found mixTagsInterpolator method mentioned in one of the issues but its also not working.

I am attaching my code and current output's screenshots below, please help.
<img width="1108" alt="Screenshot 2024-06-22 at 7 20 55 PM" src="https://github.com/yairEO/tagify/assets/86529959/04463e8c-6d25-45f4-9fe8-5516d90ac350">
<img width="1440" alt="Screenshot 2024-06-22 at 7 20 19 PM" src="https://github.com/yairEO/tagify/assets/86529959/b2beed9b-c32e-4cc5-a313-c02de34455c1">

**Comment by yairEO** [comment]
Can you please create a simplified jsbin demo page, as I've asked for in this issue template?

**Comment by yairEO** [comment]
closing as OP is unresponsive
