### ISSUE TITLE
Prevent new lines at all in tagify input

### ISSUE THREAD

**Issue by FreshDoktor** [yairEO/tagify#1356]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

https://jsbin.com/hekicef/edit?html,css,js,output

We want to use this library so our user can easily insert variables/placeholders into an normal Input. The height of it should not change nor should the text be vertically scrollable only horizontal. I tried to stop the event in the keydown event but it did nothing. I just want it to behave like any other normal <input> just that i have chips between my text. Is there any way to get this behavior? I can't find an example working like what i want, nor does the documentation helped me. 

Thanks in advance

**Comment by yairEO** [comment]
You are talking about CSS here, not javascript, which is unrelated to this library. you are the one who is in charge of styling things in your app, so make your specific CSS changes for Tagify in your app according to your requirements.

if you are asking "how should I style tagify to not wrap tags" then that has been asked a few times in the past and is mentioned in the [FAQ section](https://github.com/yairEO/tagify#faq)
