### ISSUE TITLE
Duplicates not allowed in 'mix' mode even though duplicates is true

### ISSUE THREAD

**Issue by dinukapj** [yairEO/tagify#1358]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

I want to create a mix input with multiple duplicates as needed by the user. However the suggestions avoid showing the same tag again if it already exists in the input. I've enabled duplicates as stated in the library.

What I see:

![image](https://github.com/yairEO/tagify/assets/11241826/be3d44f4-53d6-49dc-8b4f-9d41b8847409)

Since First name already exists, the suggestions never show it until I delete it.

```
<script>
    var whitelist = [
        { text: "account.first_name", value: "Account: First Name" },
        { text: "account.last_name", value: "Account: Last Name" },
        { text: "deal.deal_name", value: "Deal: Name" },
    ];

    var inputElem = document.getElementById('smsBody');
    var tagify = new Tagify(inputElem, {
        mode: 'mix',
        pattern: /@|#/,
        enforceWhitelist: true,
        whitelist: whitelist,
        duplicates: true, //enforced this to allow duplicates
    });

    console.log(tagify.settings.duplicates); //this prints 'true' which means library accepted it

    tagify.on('add', function (e) {
        var tagElm = e.detail.tag;
        var tagType = e.detail.data.text.startsWith('account.') ? 'account' : 'deal';
        tagElm.classList.add('tagify__tag--' + tagType);
    });

    inputElem.addEventListener('change', onChange);
    function onChange(e) {
        document.getElementById("outputValue").innerText = e.target.value;
    }
</script>
```

**Comment by yairEO** [comment]
Yes it's possible! shown in the [demo page here](https://yaireo.github.io/tagify/#section-advance-options)

There are multiple ways (CSS or JS)

**Comment by yairEO** [comment]
They are allowed, they only not being suggested
