### ISSUE TITLE
Remove/Removed Callback

### ISSUE THREAD

**Issue by lukesnowden** [yairEO/tagify#137]
I think you may need a `removed` callback/event at the end of the function `removeNode` or update the position at which the `remove` callback/event is called/emitted. When relying on the `remove` callback the value is still the same as before, yet when using `add` callback, the value is the new updated value.

Hope this makes sense!

**Comment by yairEO** [comment]
makes sense, I will make the change soon, thanks!

**Comment by Karamhaj1995** [comment]
still not fixed, I still have this issue only after removing some tags, the deleted tag is still appear in tagify.value
please help

**Comment by viqashussain** [comment]
Also having trouble with this issue. Any idea when this will be fixed?

**Comment by viqashussain** [comment]
This still doesn't work for mix mode as I can see from your code change. What difference does the mode make?
