### ISSUE TITLE
Invalid tags stuck in editable state

### ISSUE THREAD

**Issue by sohaibali123** [yairEO/tagify#1370]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

[
https://jsbin.com/deqixobolo/edit?html,js,output

### Explanation

- editTag() method is called on an invalid tag and then when user is done adding something to the tag it should remove the editable state and should remain when keepinvalidtag is true

- editTag() works fine but when called on invalid tags and when user changes that tag it gets stuck in editable state.

**Comment by yairEO** [comment]
This is intentional: there is a setting called `editTags.keepInvalid` which is `true` by default:

https://github.com/yairEO/tagify#settings

> keeps invalid edits as-is until esc is pressed while in focus

**Comment by sohaibali123** [comment]
Maybe I am not explaining it right. 

Any valid tag that is edited to an invalid state causes that tag to get stuck in editable state. 

for example on your second example on https://yaireo.github.io/tagify/. Once you edit any tag (css,html,javascript) by adding any characters which should make the tag invalid. Once losing focus by clicking away it doesn't lose its editable state making it hard to remove that invalid tag. It should lose editable state and show x.

**Comment by yairEO** [comment]
Yes, I know, as I said that is intentional. You can se `editTags.keepInvalid` option to `false` if you don't think this is helpful for you or your users. ("lose editable state and show `x`")

Undoing (`ctrl-z`) inside the tag will revert it back to what it previously, if you don't remember what was there before.
