### ISSUE TITLE
Entering two tags consecutively will not display the suggestions list on the second time

### ISSUE THREAD

**Issue by alex-praschek** [yairEO/tagify#1372]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

v4.21.0: https://codesandbox.io/p/sandbox/tagify-issue-v4-21-0-w8jt6d
v4.21.1: https://codesandbox.io/p/sandbox/tagify-issue-v4-21-1-nr6nqx
v4.31.2: https://codesandbox.io/p/sandbox/tagify-issue-v4-31-2-kpktgs

### Explanation

Hi, I'm currently integrating Tagify into an application to allow users to mention other users in chat messages and comments. It's looking really good so far. However, I noticed an odd bug happening when mentioning multiple users at the beginning of a message.

I managed to narrow it down (see linked examples above): Version 4.21.0 works perfectly, versions 4.21.1 up to the latest version 4.31.2 contain the bug. I've been testing on MacOS 14.2.1 with Chrome 128.0.6613.85, Firefox 129.0.2 and Safari 17.2.1. They all display the same behavior. 

- **What is the expected behavior?**
1. Input @ to show suggestions
2. Suggestions are shown, press Enter to insert the first tag
3. Input @ again to show suggestions again (without typing any other character before)
4. Suggestions are shown

- **What is happening instead?**
Step 4 does not work, the suggestions are not shown. If I type a space or another character before the second @, it works perfectly (check the video).

https://github.com/user-attachments/assets/e8e463b9-bcdb-4047-ac47-e931a410df0e

- **What error message are you getting?**
None.

I hope I included all information required to understand the bug. Thank you for your amazing work on this library!

**Comment by SakhnoI** [comment]
@yairEO Issue is still relevant

Demo: https://codesandbox.io/p/sandbox/tagify-issue-v4-31-3-nwnqr9?file=%2Fpackage.json%3A7%2C20
