### ISSUE TITLE
Thanks, now at demo page svg images are visible, but it still do not have autocomplete and when you select smething it do not appear as tag until you write exactly same text and then hit double enter.

### ISSUE THREAD

**Issue by Maremic** [yairEO/tagify#1380]
Thanks, now at demo page svg images are visible, but it still do not have autocomplete and when you select smething it do not appear as tag until you write exactly same text and then hit double enter. 

![{0C6BFAC2-3AA6-483E-8E62-0F784FC60CD2}](https://github.com/user-attachments/assets/d69ef45f-1b13-41c8-a1a1-170db120cc04)

=> on https://yaireo.github.io/tagify/#section-extra-properties

![{243314EF-BB22-4EC2-824A-C9F4196B3480}](https://github.com/user-attachments/assets/28c6badc-55af-41a7-888c-b9e9c5a2ede1)

=> on demo page

there are no images on dropdown, and autocomplete do not run, when you hit enter it do not create selected tag till its exactly the same, I met exactly same issue in my project

_Originally posted by @Maremic in https://github.com/yairEO/tagify/issues/1379#issuecomment-2357623223_

**Comment by Maremic** [comment]
https://codepen.io/Hellsink/pen/yLddRro
same in this demo, when you try to include autoComplete:{enabled:true,}
it do not work

**Comment by yairEO** [comment]
if you start typing `cz` you must apply the auto-complete, which is only a suggestion and doesn't actually changes your input until you press the `Right-Arrow` or `Tab` key.

Also, in this [specific demo]([yaireo.github.io/tagify#section-extra-properties](https://yaireo.github.io/tagify/#section-extra-properties)), the there is no auto-highlighting of the first-matched dropdown item.
