### ISSUE TITLE
Blur on some event

### ISSUE THREAD

**Issue by Maremic** [yairEO/tagify#1381]
Hi, for some of my inputs I need loss focus on add of tag, but I am not able too, 
(blur on DOM.input, or blur on my default input etc seems to not work
I tried to focus other element or click on document body, but tagify is still focused in last input where user was)

would be nice same as clearOnSelect have BlurOnSelect or so 

Thanks

**Comment by yairEO** [comment]
hi, please create a simple demo page or show me a video... I don't understand the situation

**Comment by yairEO** [comment]
closing as stale
