### ISSUE TITLE
Ajax whitelist sends object and not string ?

### ISSUE THREAD

**Issue by Alekusu** [yairEO/tagify#139]
Hello !

First a huge THANKS, because your script is awesome and you really did an amazing work. I benchmarked many "tags system", and yours was above others ! 

I tried to use the Ajax whitelist, but seems it doesn't work. 
I used the example you done here : https://github.com/yairEO/tagify#ajax-whitelist

But the value sent is not a string but an object ? is it normal or an error ? 

The JS console says : 
Fetch finished loading: GET "http://www.site.com/tags/tags_json/?value=[object%20Object]"

Is it a way to fix that ? 

Thanks a lot.
FYI : there is a missing ")" at the end of your sample

**Comment by Alekusu** [comment]
Thanks for your fast reply, can't show you any FETCH result cause it failed, the console said : 

18:21:30.222 form:331 Fetch failed loading: GET "http://www.site.com/tags/tags_json/?value=[object%20Object]"
18:21:30.832 form:331 Fetch finished loading: GET "http://www.site.com/tags/tags_json/?value=[object%20Object]"

i guess it's because it's an object and not a string which is sent through GET. Is it normal ? 

Update : It's ok i fixed it. 
It's because of the var value = e.detail.value; (the .value was missing)
Now it's sending a string and it works :D

**Comment by yairEO** [comment]
1. it's a problem with your server if the fetch fails
2. you need to use POST or do JSON.stringify(tagify.value) and send via GET. I would do POST

**Comment by KiranRW1** [comment]
@yairEO Could you please update the documentation and README to reflect   `var value = e.detail.value;` instead of `var value = e.detail;` I too encountered an issue and finally debugged to this point to find the issue. Thank you so much for such an amazing library.

**Comment by yairEO** [comment]
@KiranRW1 - Thanks, fixed in [`2.9.1`](https://github.com/yairEO/tagify/commit/d21bea94106c58ad6e73a05ff3367a427a9fa959)
