### ISSUE TITLE
Fails on inputs with no value

### ISSUE THREAD

**Issue by JGMerlix** [yairEO/tagify#1394]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
   Instantiating Tagify on an input field with no previous value should result in an instance with no preloaded tags

- **What is happening instead?**
  Getting an error on a forEach() call for inputs with no pre-existing values (```<input value="">```)

- **What error message are you getting?**
```
 Uncaught TypeError: t.forEach is not a function
    at Q.addTags (tagify:34:67646)
    at Q.loadOriginalValues (tagify:34:53518)
    at new Q (tagify:34:48502)
```

It's like Tagify is assuming that ALL inputs have pre-existing values. This did not happen before. In previous version, Tagify would simply return an instance with no preloaded tags if the input had no value.

**Comment by yairEO** [comment]
which version are you using? make sure it's the latest

**Comment by yairEO** [comment]
I think this has already been fixed so closing until OP responds saying the issue persists with latest version
