### ISSUE TITLE
Store only ids of tags to handle tag text change cases

### ISSUE THREAD

**Issue by mkmaker** [yairEO/tagify#1396]
Consider a case where we have 3 tags:

Tag1: id: 1, value: red
Tag1: id: 2, value: green
Tag1: id: 3, value: bluo (deliberately added typo)

We use mix mode. When user selects this currently it saves as follows:

I love [{'id': 1, 'value': 'red'}] and [{'id': 3, 'value': 'blue'}]

Now suppose the original text of the tag with id 3 is changed from settings and made 'blue' now. I want the saved mix tag above also handles that but currently what happens is I need to change this for all those records in database where tag id 3 was used. Consider this happening at large scale. Not ideal.

What we can do instead is the mix mode (or even simple mode) stores the ids only so this becomes:

I love [{'id': 1] and [{'id': 3}]

And while rendering or initializing with this the plugin can match the ids from whitelist array to show the correct text.

Is this currently possible?

**Comment by yairEO** [comment]
I highly recommend not to use `id`. only use `value` and some other property, for example `text` or `name` or `label`. `id` means nothing to Tagify. It **must** have a unique `value` property and then it will automatically find those within the whitelist and add them as tags.

```js
var tagify = new Tagify(input,
    {
        tagTextProp: "name",
        dropdown: {
            enabled: 0,
            mapValueTo: "name"
        },
        whitelist: [
            {
                "value": "1", // <--- this is your `id`
                "name": "One",
                "title": "One",
            },
            {
                "value": "2",
                "name": "Two",
                "title": "Two",
            },
            {
                "value": "3",
                "name": "Three"
                "title": "Three",
            }
        ],
    })
```

**Comment by mkmaker** [comment]
Hey @yairEO Sorry if I was not clear in my post. Actually I am making a form builder. So I want my users to reference a form element in the next question.

Each form question has an id and question_text. If I save the question_text in the db when user reference Q1 in Q2 then the problem is if Q1's question_text is changed it won't reflect properly in the previously saved data. Let me know if I need to explain or give a better example.
