### ISSUE TITLE
Disable Backspace Key for Tag Deletion in Tagify Basic Version

### ISSUE THREAD

**Issue by Nithish-1141** [yairEO/tagify#1398]
Hi,

I am using the basic version of Tagify in my application, and my client has requested to prevent tags from being removed by clicking the backspace key. If they accidentally press backspace, it removes the added tags, making it difficult to identify which tags were removed.

For example:

- I added tags as shown in the image.

![image](https://github.com/user-attachments/assets/75fc463e-64b0-462b-82b1-a55babdd17e3)

- Then, when I click backspace, it removes the last tag.

![image](https://github.com/user-attachments/assets/c7226cfc-f4c6-4508-92ca-c1a581baa1af)

My requirement is to allow tag removal only by clicking the "x" button, not by using backspace.

**Comment by yairEO** [comment]
[The README explains all the settings:](https://github.com/yairEO/tagify#settings)

![image](https://github.com/user-attachments/assets/65253ffa-559d-48e6-aa3c-9666594442e7)
