### ISSUE TITLE
Unexpected token with gatsbyjs

### ISSUE THREAD

**Issue by devnasim** [yairEO/tagify#140]
![screenshot from 2018-11-14 16-53-57](https://user-images.githubusercontent.com/25324607/48479651-f5cfaa80-e82d-11e8-96dc-54f0fb7881ae.png)

**Comment by yairEO** [comment]
Which version of Babel are you using?

I will change the code to not use ES2017 _Class Arrow Functions_

**Comment by devnasim** [comment]
@yairEO using gatsby V2

**Comment by devnasim** [comment]
yup

**Comment by yairEO** [comment]
I think you are seeing a older cached  version because it is impossible you are still seeing that error in your console. There no more Arrow functions at all in the [file](https://github.com/yairEO/tagify/blob/master/dist/react.tagify.js).

**Comment by devnasim** [comment]
thanks
