### ISSUE TITLE
'invalid' event does not fire when createInvalidTags is false.

### ISSUE THREAD

**Issue by blue-int** [yairEO/tagify#1405]
When a user tries to add an invalid tag, I want to cancel it and show popup.
So, I used skipInvalid: true, createInvalidTags: false.
Then, however, I cannot get the invalid event because it fires when a invalid tag is added, which is not added by this setting.
How can I achieve my goal?
Thank you.

**Comment by yairEO** [comment]
Int such case you should probably use the `transformTag` (function) setting to validate each tag there and decide what should be done with it. It can be done quite easily.
