### ISSUE TITLE
Pasting HTML text creates Tag with duplicate content 

### ISSUE THREAD

**Issue by Olezha** [yairEO/tagify#141]
To reproduce: copy word with styles, like `duplicates` with yellow bg, and paste it to tagify, and **press Enter**.

But if end this process with outside click by mouse - all ok.

![2018-11-14 13-46-51](https://user-images.githubusercontent.com/7818007/48480842-4fc37680-e814-11e8-94ec-ad477e771f95.png)

**Comment by yairEO** [comment]
Thanks. will be fixed today/tomorrow. I know what's going on.

**Comment by yairEO** [comment]
reverted the fix since it created another bug

**Comment by lakshmicode** [comment]
Is this issue fixed ?

**Comment by zzcyrus** [comment]
Now the demo on the official website still has the issue

**Comment by oleh-kostovynsky** [comment]
> Is this issue fixed ?

I did fix it this way:

```
  hooks: {
    beforePaste: (e, data) => {
      return new Promise((res, rej) => {
        if (data.pastedText) {
          res(''); // prevent insertion of duplicates
        } else {
          rej();
        }
      });
    },
  },
```
