### ISSUE TITLE
Instant Update input/textarea 

### ISSUE THREAD

**Issue by Alekusu** [yairEO/tagify#142]
Hello Again ! :D 

I was wondering how to get the result once the user is done with the tags. Seems you designed your script for a full JS system and not for PHP or other similar language :D At the end, the input/textarea is empty and if the user submits the form, there is nothing. 
A boolean parameter activating instant update of the input/textarea with the tags values will be a great asset ! It's still possible to do that through the add callbacks but a native function will be better ! 

I tried to implement this callback function but it doesn't work : 

`<input type="text" name='tags' id="tags" value="" />
`
```
callbacks        : {
            add    : function(addThis){
                 var elem = document.getElementById('tags');
    		var old  = elem.value;	
        	elem.value = old + addThis.detail.id + ',';
        	},  // callback when adding a tag
            remove : console.log   // callback when removing a tag
        }
```
The whole script works perfectly but not the callback function cause the input value stays empty (and the javascript console gives no error). Do you have any idea why ? Or another solution ?  

My purpose is to get something like value="43,93,123" to treat the data easily in PHP after. 
Note : when i use alert(addThis.detail.id) it works perfectly, the issue is just the append input part.

Thanks a lot !

**Comment by yairEO** [comment]
The (original) input is not empty at all, you can even see it in the [demo page](https://yaireo.github.io/tagify/) if you click on the toggle on the right bottom side of the viewport.

**Comment by Alekusu** [comment]
I didn't say it's empty, i said if you start with an input value="Apple,Banana" 
If you add the tag "Pineapple", the input value will not be updated, right ? 
So if you submit the form, the value will still be "Apple,Banana", right ? 

What i would like is the input value to be updated each time and when the user submit the form, the value received is "Apple,Banana,Pineapple"

**Comment by yairEO** [comment]
no, not right.

What are you keep saying that? 
read my previous message and see for yourself
