### ISSUE TITLE
Space in tag requires pressing spacebar twice

### ISSUE THREAD

**Issue by ttk** [yairEO/tagify#144]
If I want to type in a tag with a space, say: `Not Found`, it requires me to type in two spaces in order for it to insert a single space.  If I type in a single space, it simply gets ignored and the tag becomes `NotFound`

Not{space}Found => `NotFound`
Not{space}{space}Found => `Not Found`

It shouldn't be required to type in two spaces.

Version: 2.7.4

**Comment by yairEO** [comment]
Ho, now I know what that piece of code I deleted yesterday was about :)

I was wondering what was the reason for a piece of code that I didn't write comment for. now i know. thanks, reverting

**Comment by yairEO** [comment]
it's a very difficult bug apparently. I am forced to revert back the fix for #141.

`setRangeAtStartEnd` method doesn't seem to work when a `contenteditable` element's `innerText` has trailing space character :/ tried some tricks, none works for now. tough problem.
