### ISSUE TITLE
tagify.min.js is not synch with tagify.js

### ISSUE THREAD

**Issue by ElvenDev** [yairEO/tagify#15]
Hi, me again :)! I hope I am not getting annoying, as I truly think this is one of the best tagify libs out there. So I am suggesting things what makes sense, what are kinda needed in my current project and so on.

The first bug: Took me a while, when I didn't see that any updated weren't synching. Apparently, min.js is not same as just js. For an example that auto-add tag doesn't work there. Else, awesome job!

**Comment by yairEO** [comment]
I will check why the `min` version isn't the same as the unminified one. it's strange.. 
I'm using Gulp to create it automatically.

**Comment by yairEO** [comment]
I've tested the minified version and it's the same.. all works well.. maybe it's caching thing?

I need to write tests in the future so there will be no doubt.

**Comment by ElvenDev** [comment]
Weird. I'll look into it tomorrow. Thanks for checking anyway!

**Comment by yairEO** [comment]
Tell me if this issue can be closed

**Comment by ElvenDev** [comment]
Sorry, couldn't check sooner.

It works now. No idea why, but I guess maybe it was indeed cache issue or something.

Sorry for false alarm :).
