### ISSUE TITLE
Different height for input with and without tags in Firefox

### ISSUE THREAD

**Issue by BGrigorovich** [yairEO/tagify#150]
Hi! Thanks for the cool lib!

I'm having issue with input height in Firefox. When it has tags everything works great, but when it's empty it's height gets shorter.

I'm using Tagify 2.7.6, Firefox 63.0.3 and Bootstrap 4.1.3 (although I don't add bootstrap classes to tagify inputs).

<img width="755" alt="screen shot 2018-11-22 at 11 51 52" src="https://user-images.githubusercontent.com/10698057/48895278-62a9fc80-ee4d-11e8-90df-cd3952401766.png">
<img width="748" alt="screen shot 2018-11-22 at 11 52 03" src="https://user-images.githubusercontent.com/10698057/48895279-62a9fc80-ee4d-11e8-9020-388c26fb8a50.png">

**Comment by yairEO** [comment]
I see. it's because you do not have a `placeholder`. You can resolve this by adding it or by adding a zero-width space character as the placeholder `\200B`:

    <input placeholder="\200B" ... />

**Comment by BGrigorovich** [comment]
Oh, thanks a lot!

**Comment by yairEO** [comment]
Actually you need the placeholder as the HTML entity (and not the CSS):

    &#8203;

I'll make this the default when there's no placeholder.
