### ISSUE TITLE
keepInvalidTags, suggestionsMinChars are not listed in the Settings

### ISSUE THREAD

**Issue by rolandtoth** [yairEO/tagify#151]
Thanks for this fine lib, it's very handy.

I found that keepInvalidTags and suggestionsMinChars options are not listed in the Readme, could you check? (perhaps there are even more missing)

**Comment by yairEO** [comment]
I have no idea what `suggestionsMinChars`... it's not even in the [source code](https://github.com/yairEO/tagify/blob/master/src/tagify.js) :D

**Comment by rolandtoth** [comment]
suggestionMinChars is on the demo page:
https://yaireo.github.io/tagify/

keepInvalidTags is imo an important feature, thanks for considering adding to the docs.

**Comment by yairEO** [comment]
`suggestionMinChars` is also not in the demo page...

**Comment by yairEO** [comment]
I see. that section is old, there is no `suggestionMinChars` any more. Thanks for pointing that out! it has been named `dropdown.enabled`

**Comment by rolandtoth** [comment]
Thanks, sorry for the typo :)
