### ISSUE TITLE
Add class if maxTags limit is reached

### ISSUE THREAD

**Issue by rolandtoth** [yairEO/tagify#152]
Adding a class if `maxTags` limit has reached would be handy, eg. for CSS styling, or hiding the tagify__input. Currently you can type to the input even when the limit is reached, which doesn't make too much sense.

**Comment by yairEO** [comment]
You can count the number of tags and add a class yourself. Using `add` & `remove` [events](https://github.com/yairEO/tagify#events):

````
tagify.on('add', onChange)
tagify.on('remove', onChange)

function onChange(){
  tagify.DOM.scope.classList.toggle("limitReached", tagify.value.length >= tagify.settings.maxTags)
}
````

**Comment by yairEO** [comment]
BTW, you can do it with CSS only (for maximum 6 tags):

    tag:nth-of-type(6) ~ .tagify__input{ display:none }

**Comment by rolandtoth** [comment]
Thanks, I know about the CSS way but it would require hardcoding the value. I still think it would be better handling this internally (without events), and toggling a class is an unobtrusive way of doing this - I mean who needs it can use it.

**Comment by yairEO** [comment]
See [Settings](https://github.com/yairEO/tagify#settings):

> when reached, adds a class "hasMaxTags" to <Tags>
