### ISSUE TITLE
License makes it very difficult to use this library anywhere

### ISSUE THREAD

**Issue by potay** [yairEO/tagify#153]
Just would like to let you know that GNU AGPL is quite restrictive and makes it very difficult for people to use this library legally.

**Comment by yairEO** [comment]
in what way is it restrictive? I've made it on purpose because I had troubles were people stole my code and re-sold it as a part of their package. I do not want anyone to sell me code or that my code be a core-component in a sold code.

**Comment by gencer** [comment]
For instance, it is a bit unclear if we can use this on our SaaS apps freely without giving our source code to you or anyone. Can we allowed to use your library in our apps that we sell as a SaaS?

I've no intention to make your component better and sold as is. Just want to use it in my SaaS app. If you clearly state this here, I would be happy to use your library. (Very powerful, BTW)

**Comment by yairEO** [comment]
Good luck and hope you like Tagify! Tell all your friends about it :)
