### ISSUE TITLE
tags permanently classed as "tagify--notAllowed" while using itemTemplate and maxTags

### ISSUE THREAD

**Issue by aripalli** [yairEO/tagify#154]
When using the `itemTemplate` option to add properties to the tags, and adding a restriction for `maxTags`, the tags are permanently _classed_ as `tagify--notAllowed` when they break the `maxTags` restriction.

For example, if you add the settings `maxTags: 1` to the [flag demo](https://yaireo.github.io/tagify/#section-extra-properties). You can see that when you then remove the `"Afghanistan"` tag and want to add the `"Åland Islands"` tag back again it will still have the `tagify--notAllowed` class and be _`invalid`_.

**Comment by yairEO** [comment]
Thank you very much for spotting this bug, I will try to fix it today/tomorrow

**Comment by yairEO** [comment]
I've set it `maxTags` to `1` in the `TAGS WITH PROPERTIES` section of the demo page, and cannot reproduce the bug:

![d](https://user-images.githubusercontent.com/845031/49182844-07ec3580-f364-11e8-8dd3-d6672a402a36.gif)

**Comment by aripalli** [comment]
The bug is a bit specific. Try putting in one of the countries again after it got denied (got the not-allowed class), e.g. In your example in the gif above: Åland Islands, Cambodia, or Georgia

**Comment by yairEO** [comment]
Still cannot re-produce. Setting `maxTags` to `1`. adding `Cambodia` -> deleting it and re-adding it. works as expected.

**Comment by yairEO** [comment]
Ok, I see the bug now.
