### ISSUE TITLE
Set readonly tags via attribute

### ISSUE THREAD

**Issue by rolandtoth** [yairEO/tagify#156]
You can add initial tags by adding a "value" attribute on the input, which is great. How about adding readonly tags via eg. "value-readonly" attribute?

In my current project I needed to add the initial tags as readonly (but allow non-readonly tags to be added later). The workaround I used is to add tags via "value" attribute, and add another data-attribute to the input "data-init-tags-readonly". After init I iterate over the tags and add the "readonly" attributes manually. This works, but having a built-in way would be useful.

**Comment by yairEO** [comment]
The demo pages shows this exact scenario:

https://yaireo.github.io/tagify/#section-readonly
