### ISSUE TITLE
Issue while pre-populating an unique numeric tag

### ISSUE THREAD

**Issue by Jibeji** [yairEO/tagify#157]
Hi,
When an unique numeric tag is populated from the database like this 

`<input name='tags' id="tags" type="text" value="450" autofocus>`

I got the following error

> Uncaught TypeError: t.forEach is not a function
    at t.addTags (tagify.min.js?v=2:1)
    at t.loadOriginalValues (tagify.min.js?v=2:1)
    at new t (tagify.min.js?v=2:1)
    at alerte-par-email:348
    at alerte-par-email:386

The issue is not present with an unique alphanumeric tag. If two or more tags, even numeric are populated, it's ok.
The issue only appears with an unique numeric value.

**Comment by yairEO** [comment]
Fixed, thanks for spotting and reporting!

**Comment by petritnuredini** [comment]
@yairEO this happened to me today 24.10.2024

I have these scripts added to my project

```
<script async src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
<script async src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.min.js"></script>
```

> tagify.js:1866 Uncaught TypeError: t.forEach is not a function
> at Q.addTags (tagify.js:1866:47)
> at Q.loadOriginalValues (tagify.js:1866:47)
> at new Q (tagify.js:1866:47)
> at recruiter-search.js:5:14

**Comment by melkishengue** [comment]
I started having the same issue couple of hours ago also. Had to revert to using the previous version

**Comment by dougc84** [comment]
Same after just upgrading to latest version just a few moments ago.

**Comment by yairEO** [comment]
@dougc84 - I cannot reproduce. please create a [JSON demo](https://jsbin.com/jekuqap/edit?html,js,output) ok?

**Comment by melkishengue** [comment]
The link you posted reproduces that error

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/999c3bc4-3c50-489c-8109-7282d17ae206">

**Comment by yairEO** [comment]
fixing now, real sorry about that!

**Comment by melkishengue** [comment]
Thanks! What about providing versioned cdn links? pinning the version would have prevented this from a consumer perspective

**Comment by petritnuredini** [comment]
> Thanks! What about providing versioned cdn links? pinning the version would have prevented this from a consumer perspective

You can find online the cdn with previous version of the library.

And maybe consider download the required files into your project so project won't be affected from outside like this case.

**Comment by Harikarthyk** [comment]
Can anyone please share the cdn link with previous version history of this library, not able to find them.

**Comment by petritnuredini** [comment]
This version worked for me 

<script src="
https://cdn.jsdelivr.net/npm/@yaireo/tagify@4.31.3/dist/tagify.min.js
"></script>

<link href="
https://cdn.jsdelivr.net/npm/@yaireo/tagify@4.31.3/dist/tagify.min.css
" rel="stylesheet">

**Comment by Harikarthyk** [comment]
Thanks @petritnuredini 

> This version worked for me
> 
> <script src=" https://cdn.jsdelivr.net/npm/@yaireo/tagify@4.31.3/dist/tagify.min.js "></script>
