### ISSUE TITLE
Sources tagify/src/tagify.js is not actual

### ISSUE THREAD

**Issue by denisimo1984** [yairEO/tagify#158]
Sources `tagify/src/tagify.js` is not actual.
I downloaded your sources. 
Evereything works well.
But index use minified version. `dist/tagify.min.js`
If i take unminifed version

    tagify/src/tagify.js

and replace `dist/tagify.min.js` by it
i got error `this.EventDispatcher is not a constructor`

**Comment by denisimo1984** [comment]
Firefox 63.0.3

**Comment by yairEO** [comment]
Why do you want to use the source code directly? it's very unusual thing to do

**Comment by denisimo1984** [comment]
I minify it by our internal tools which used for minification for all scripts, that's why I prefer to use unmified version.

**Comment by yairEO** [comment]
Are you using Babel? 
Just take a look at the build process done in Gulp to understand how to replicate it on your end.
