### ISSUE TITLE
Line break (\n) as delimetr

### ISSUE THREAD

**Issue by eav93** [yairEO/tagify#160]
Hello, I want set \n as delimiter, but you remove this elements on "normalize".

**Comment by yairEO** [comment]
why would you want tags to be in a vertical list layout instead of horizontal "bricks" layout?

**Comment by eav93** [comment]
i want divide text with /n on paste, to horizontal tags list.

**Comment by yairEO** [comment]
Fixed. Now you can input things such as:

      aaa   
      bbb   
      ccc   
     

The way it works is by doing this trick:

    replace(/(?:\r\n|\r|\n)/g, this.settings.delimiters.source.charAt(1))

which replaces new lines with the first delimiter specified (if one was specified)

**Comment by eav93** [comment]
Now, **delimiters** are regular expressions. When I set
 `{delimiters: ',|;'}
this.settings.delimiters.source.charAt(1)=='|'
`

**Comment by yairEO** [comment]
To have multi-line pasted text become multiple tags, the `delimiters` setting should be as follows:

    delimiters: ",|\n|\r"

It's imperative to use both `\n` & `\r`
