### ISSUE TITLE
Editing a tag does not catch duplicates

### ISSUE THREAD

**Issue by Fijvect** [yairEO/tagify#161]
I wanted to point out a loophole in the duplication-check: when a tag is inputted, if the user goes back and edits that tag, it will not catch if the user had just edited the tag to be a duplicate of another tag.

For example ("duplicates" is set to default (false)):
![image](https://user-images.githubusercontent.com/12387268/49674745-43f05c00-fa30-11e8-9444-8647bd048e28.png)

...This is a rather insignificant loophole, but your code is practically perfect and your attention to detail and feedback to your user's issues is fantastic, that I figured you'd WANT this pointed out!
Keep up the good work! After using this component for a while, I'm definitely sold on your work and will be checking out your other projects btw

**Comment by yairEO** [comment]
ho.. right :)

it's a good catch. will be fixed at once.
