### ISSUE TITLE
Firefox: Input positioning is not compatible even though there is a placeholder.

### ISSUE THREAD

**Issue by devatmin** [yairEO/tagify#167]
Hi, I am using tagify with textarea input. It looks good in chrome and opera. But it is not in Firefox. Refer the images

1. Chrome
  
![image](https://user-images.githubusercontent.com/45559164/50419081-edb75180-0854-11e9-8ccd-6f53714163ff.png)

When click to type

![image](https://user-images.githubusercontent.com/45559164/50419284-26a3f600-0856-11e9-98a9-a05d2e946e70.png)

2. Firefox
![image](https://user-images.githubusercontent.com/45559164/50419115-163f4b80-0855-11e9-8fd6-627f7dc7d6d4.png)

When click to type

![firefox2](https://user-images.githubusercontent.com/45559164/50419390-9b773000-0856-11e9-8bda-09b8f09f7997.png)

I seen this https://github.com/yairEO/tagify/issues/150 but in my case I have placeholder.

I guess this `.tagify__input::before {
     ...
    position: absolute;
    top: 0;
    ...
    `
positioning is not compatible with firefox. Help me to solve this issue

**Comment by yairEO** [comment]
Weird, everything looks OK on my Firefox in the [demo page](https://yaireo.github.io/tagify/). 

Could you create a demo page which replicate this issue or provide a link to your implementation?

**Comment by yairEO** [comment]
It seems you aren't using the latest [tagify.css](https://github.com/yairEO/tagify/blob/master/dist/tagify.css) or something in your build process is removing these [lines](https://github.com/yairEO/tagify/blob/master/src/tagify.scss#L267)

**Comment by devatmin** [comment]
Yeah. Its fine after replacing css with latest. Thank you
