### ISSUE TITLE
Error when clicking outside of dropdown

### ISSUE THREAD

**Issue by ww9** [yairEO/tagify#168]
When dropdown is opened, clicking outside doesn't close it and triggers an error:

> Cannot read property 'previousElementSibling' of undefined at t.getNodeIndex()

![image](https://user-images.githubusercontent.com/27555162/50543295-d8268c80-0bb2-11e9-8b35-cf5ecd29db7b.png)

**Comment by yairEO** [comment]
Thanks for reporting, will be fixed ASAP
