### ISSUE TITLE
Destroy method causes TypeError

### ISSUE THREAD

**Issue by jacobedawson** [yairEO/tagify#17]
Thanks for making Tagify!

I'm trying to basically 'reset' tagify fairly often based upon new information grabbed from a database. When I do that, I want to essentially remove all the old tags and start from scratch OR add tags retrieved from the database. 

I saw the new 'destroy' method, which I'm attempting to use like this: 

`tagify.destroy();
`
When I try that, I get the following error: 

`Error in event handler for (unknown): TypeError: Cannot read property 'destroy' of undefined`

However, tagify is definitely defined as I can run the tagify.on('foo') event handlers and it's working very well in all other respects. I imagine I am using the destroy method incorrectly, but I'm not sure how. If someone could please provide an example with real code that would also be very helpful. 

Thanks!

Jake

**Comment by yairEO** [comment]
You must be using some older version because the method exist and it does work.

You can go to the [demo page](https://yaireo.github.io/tagify/) and try in your browser's console:

    tagify1.destroy() 
    // or
    tagify2.destroy()
    // or
    tagify3.destroy()
