### ISSUE TITLE
DOM.originalInput not updated in some cases

### ISSUE THREAD

**Issue by mohamedaymenkarmous** [yairEO/tagify#170]
Hello,

I'm using tagify in mix mode and I need to get the value of the textarea (DOM.originalInput.value) dynamically.

Each time I write some text in the input (DOM.input.textContent) or I insert a tag there, the DOM.originalInput.value value is updated (I don't know how it's done but it's OK).

Since I did the next use-case, the textarea value stop being updated from the DOM.input.textContent:

Step 1: input="" --> textarea=""

Step 2: input="Hello there" --> textarea="Hello there"

Step 3: input="Hello @Homer" --> textarea="Hello @Homer"

Step 4: I insert the whitelisted tag [Homer](x) from the dropdown menu. So input="Hello [Homer](x)" --> textarea="Hello Homer"

Step 5 (the problem started): input="Hello [Homer](x) how are you ?" --> textarea="Hello Homer"

The textarea keep being not updated until I delete add the pattern configured in settings (``@``).

Step 6: input="Hello [Homer](x) how are you ? I'm @kely" --> textarea="Hello Homer how are you ? I'm @kely"

I don't know how the textarea is updated dynamically from the input but I think this is a bug (a missing use-case condition).

Is there any workaround or something that I can help with to solve this problem ?

Thank you

Best regards

**Comment by yairEO** [comment]
Hi, very interesting use-case! I think I know what's going on here.

The `this.update()` method is only called when a tag is added to removed, so any "regular" text written after a tag has been added doesn't trigger the `update` method. 

I will push a fix for this as soon as i'm able

**Comment by mohamedaymenkarmous** [comment]
Hi,

Alright

Thank you for your support in a such great project.

Best regards

**Comment by yairEO** [comment]
Fixed, try the new version `2.9.7`

**Comment by mohamedaymenkarmous** [comment]
Hi,

Nice, difficult and great update as expected. And it works like a charm.

Thank you

Best regards
