### ISSUE TITLE
Configuration via attributes

### ISSUE THREAD

**Issue by melenaos** [yairEO/tagify#172]
It would be wonderful to accept Whitelist and blacklist configuration via attributes.

I am using C# to render my views and I can include the whitelists in the input tag via attributes and I use static files for Javascript.

It's not convinient to create JS objects to pass information from my views to JS. It would be much better to use the input attrubute to configure Taggify object than using Javascript.

**Comment by melenaos** [comment]
If you need help developing this please let me know.

**Comment by yairEO** [comment]
Done, see demo page:

https://yaireo.github.io/tagify/#section-basic

**Comment by melenaos** [comment]
Super! Does this works with the specified delimiter as well? I mean other than comma

???? t?? Outlook ??a Android<https://aka.ms/ghei36>

________________________________

**Comment by yairEO** [comment]
It automatically used the same delimiter as specified in the settings or uses the default one which is comma
