### ISSUE TITLE
Placeholder does not update when changing dropdown active item using down arrow

### ISSUE THREAD

**Issue by ww9** [yairEO/tagify#175]
![2019-01-03_09-19-09](https://user-images.githubusercontent.com/27555162/50637548-321fad00-0f39-11e9-9153-37bb89b8cd6f.gif)

I expected placeholder to update as user changes active dropdown item using keyboard down arrow. But it stays as the first item "albania" giving the impression that "albania" will be added instead.

**Comment by yairEO** [comment]
Good point, thanks
