### ISSUE TITLE
event listener propagation

### ISSUE THREAD

**Issue by privateOmega** [yairEO/tagify#177]
@yairEO
I was going through the source code for tagify and found out that, build() constructs a `<div contenteditable>` on top of the input element used, but this way the event listeners attached to the input element gets lost.
Is there some way to propagate the event listeners to retain them in new `<div contenteditable>` element.
Google Chrome provides getEventListeners() to get list of event listeners, but other than that all other approaches I see are maintaining a global list on addition and removal of event listeners (maybe even google chrome is relying on the same thing) but do you know any method to tackle this situation?

**Comment by privateOmega** [comment]
A little background on this question:
I was trying tagify on top of an input element and on pressing enter key, since its a <div contenteditable>, it created new empty <div>'s inside it which is undesirable. What I think and propose of as a solution to it would be to have an additional attribute manually set on the input element or text area or whatever, and if it is present, add an onpress() that prevents enter keypress.

**Comment by privateOmega** [comment]
@yairEO I am not sure how to use tagify's callback, but lets keep that aside for now.
I have attached code for a demo that verifies my claim about new elements on pressing enter. Could you please check that out. It might probably something I must have done to mess it up, but cannot figure it out on my own.
<script src="https://gist.github.com/privateOmega/4d281c3e6082af84a4e706521db367b3.js"></script>

**Comment by yairEO** [comment]
the demo code in the link has no events on the input **before** tagify was applied. what is the specific question / scenario?

**Comment by privateOmega** [comment]
Yes I haven't attached any events, I thought we would tackle one problem at a time. In this demo code, if you press enter key, a new element gets created and new text would appear on next line only.
