### ISSUE TITLE
BUG, when you write some whitelisted tag completely

### ISSUE THREAD

**Issue by hacknlove** [yairEO/tagify#183]
Steps to reproduce it

1. go to: https://yaireo.github.io/tagify/
2. focus on the first example tagify input
3. write "bash" or "Bash" or "BASH" etc
4. press Enter

It should add the tag but it does nothing, and the next error is showed in the console

TypeError: t is undefined tagify.min.js:7:9669

**Comment by yairEO** [comment]
Thanks for reporting, will be fixed at once.
