### ISSUE TITLE
Using Mixed Tags: How to add new Tags that are not listed in the whitelist?

### ISSUE THREAD

**Issue by Issabln** [yairEO/tagify#186]
Ì'm trying to create new Tags, which should be pushed thereafter into the whitelist. 

where does the check happen whether my new input is part of the white list or not? I'd have to change the code here.

**Comment by yairEO** [comment]
You must add it to the whitelist before the tag was typed.. it must be first in the whitelist. why can't you update the whitelist dynamically?

**Comment by Issabln** [comment]
"You must add it to the whitelist before the tag was typed.. it must be first in the whitelist."
 The thing is, I want to add them by typing them just as in your other examples in the demo. For example: " this is my #hash", so when I hit enter after the second "h" it should be added to the list and therefore be styled in the input like them.

**Comment by yairEO** [comment]
OK now I understand. I will think what to do regarding this

**Comment by Issabln** [comment]
Thanks, that would be great. I'm trying it currently by comparing the 'basic' with the 'mix' example, looking for the key points to solve this.

**Comment by yairEO** [comment]
Actually I do not understand at all.

Are you saying you want everything that starts with `#` to look like a tag??

**Comment by Issabln** [comment]
Yes and to add it to the whitelist.

**Comment by Issabln** [comment]
Great. Yes, saving it on the server is not the problem.

**Comment by Issabln** [comment]
"and when I hit Enter after #tom cruise then it will create a tag. That can be done, and the tag is then added to the Array of tags in tagify.value"

How can it be done or where in the code?

tagifiy.js-File

        // search if the tag exists in the whitelist as an Object (has props), to be able to use its properties
        if(  whitelistWithProps ){
            tagsItems.forEach(tag => {
                var matchObj = this.settings.whitelist.filter( WL_item => WL_item.value.toLowerCase() == tag.value.toLowerCase() )
                if( matchObj[0] )
                    temp.push( matchObj[0] ); // set the Array (with the found Object) as the new value
                else if( this.settings.mode != 'mix' )
                    temp.push(tag)
            })

            return temp;
        }
        else{  HERE ???....
]

**Comment by Issabln** [comment]
I can now push typed words with prefix '#' into the whitelist, but the problem is, they dont get syled as the other whitelist-words. What can I do?

**Comment by Issabln** [comment]
I can now push typed words with prefix '#' into the whitelist, but the problem is, they dont get syled as the other whitelist-words. What can I do?

**Comment by yairEO** [comment]
Sorry I am extremely bust with my job and have no time until March..

**Comment by knasser** [comment]
Hi ,, I see your comment on #389   .. and I think #389  is a bit simpler than #189.. and you dont have the space issue,, 
It is just about selecting some text and pressing a button to change it to a tag.. no prefix or keyboard..

**Comment by yairEO** [comment]
@knasser - you want the user to type regular text and then select a part of it, and somewhere there will appear a button to convert the selected text into a tag?

You would need to add it to your DB as a tag as well after the user creates it

**Comment by knasser** [comment]
yes exactly as you describe it.. 
also add it a s a tag is okay,  and can keep track of it for later reading from server

**Comment by knasser** [comment]
we are able to do it with the below code..  not sure if the best way or may be you want to incude as  part of tagify itself 
`$scope.buttonClick= function(){
			var tagify = $scope.getTagifyByCurrentSelection(); 
			if(!tagify) { return;}

			var selection = window.getSelection();
			var range = selection.getRangeAt(0);
			var text = range.toString();
			range.deleteContents()
			range.insertNode(new Text("[["+ text+ "]]"));
			range.startContainer.parentElement.dispatchEvent(new Event('input'));
			console.debug(tagify)
			tagify.loadOriginalValues();
		
		}
		$scope.getTagifyByCurrentSelection = function (){
			var tagifies = $scope.tagified.filter(function (t) {
				var selection = window.getSelection();
				var range = selection.getRangeAt(0);
				var e = range.startContainer.parentElement;
				console.debug(e);
				console.debug(t.DOM);
				console.debug(t.DOM.input == e);
				return t.DOM.input == e;

			});
			if(tagifies.length > 0 ) return tagifies[0];

		}
`

**Comment by yairEO** [comment]
I am currently on vacation, but I will try to make time for this in the upcoming days

**Comment by yairEO** [comment]
Ok, I put this on my TO-DO, and will address this soon, I have some other stuff I must do first..in code and in general

**Comment by knasser** [comment]
no worries. the above had done the job for us.. though you might want to do differently I think
