### ISSUE TITLE
Select multiple tags

### ISSUE THREAD

**Issue by MarcosRakesh** [yairEO/tagify#187]
Hello,

How can i keep dropdown/autocomplete open to select multiple tags? I didn't find any option, if there isn't one can you make one?

**Comment by yairEO** [comment]
That is not supported.. sorry. 

I don't think support for this should be developed since I've never seen such a behavior for tags components. it's very uncommon..

**Comment by MarcosRakesh** [comment]
@yairEO 

What's the point of tags with autocomplete/dropdown if you can't select multiple tags without closing, opening one by one is bad UX and time consuming. Also using dropdown/autocomplete just for one tag is pointless if you can type multiple tags in one input.

[Example: Scroll down to 'Email contacts' and you can see it opens and you can select multiple tags from one click instead of reopen the dropdown](https://selectize.github.io/selectize.js/)

I needed this behavion with [#102](https://github.com/yairEO/tagify/issues/102#issuecomment-419378925) to select tags more faster than one by one.

 `it's very uncommon..`
I think you live in a cave...
Was just a suggestion for better ux, you close the issue without thinking about it, shouldn't wasted my time.

Thank you.

**Comment by yairEO** [comment]
I did think about it and I've never seen such a tags input.. can you please provide me a website link which shows such a thing?

even [stackoverflow.com](www.stackoverflow.com) doesn't have such a thing, maybe you can write them also they live in a cave

**Comment by MarcosRakesh** [comment]
Well did you ever used multiple select ux? The scenario is about using autocomplete/dropdown faster and at full potential, if not why use it if you can type without it. I don't care if stackoverflow have or not, i only care if WE HAVE it and where i use it, also many other have bad ux and i didn't meant to offend you , if i did sorry.

I did provide you an example with what i try to do, read again my previous comment, if not here:
[Multi select examples](https://dribbble.com/tags/multiselect)

**Comment by mdashti** [comment]
+1 for this capability. It's commonly asked from our clients.
