### ISSUE TITLE
Override default backspace action

### ISSUE THREAD

**Issue by GRA0007** [yairEO/tagify#188]
Hey, so I have a tagify instance with the tags outside of the box as per [the example](https://yaireo.github.io/tagify/#outside-of-the-box), and I was wondering if there was any good way of overriding the default backspace action, because at the moment, pressing backspace in the input deletes tags, but because it's not very intuitive when the tags are not in the box, I would like to disable the backspace delete.

**Comment by vibhoom** [comment]
I also have a similar question, where I want to provide the functionality of edit on pressing the backspace, instead of removing the tag.

**Comment by gencer** [comment]
To achieve this find this line:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L339

And change this:

this.removeTag( lastTag );

to this:

**Comment by yairEO** [comment]
fixed on version `2.12.0`
