### ISSUE TITLE
Enter tags without delimiters in mix mode

### ISSUE THREAD

**Issue by jnpatrick99** [yairEO/tagify#189]
How can I make the suggestions work in the "mix" mode without entering tags delimiters like "#" or "@"? 

For example I want to enter "This is a mix mode" into the input and have the word "mix" converted into a tag, without writing "#mix". And before I enter it display the suggestions dropbox.

**Comment by privateOmega** [comment]
@jnpatrick99 Isn't it better to track the issue from a single place. Could you please close this issue and let's jot down our inputs at #163

**Comment by yairEO** [comment]
Good idea @privateOmega
