### ISSUE TITLE
Updated Bower version?

### ISSUE THREAD

**Issue by jameshoward** [yairEO/tagify#19]
Would it be possible to tag a new version so that the latest code can be used with Bower? I see that Bower config is on v1.0.5 while NPM is v1.1.0. Looks like the latest version has some improvements we'd like to use.

**Comment by jameshoward** [comment]
Ignore that, it just looks like the 'tagify' module in Bower isn't this one, even though it looks almost exactly the same. It's this one - https://github.com/decipherinc/tagify

So you may need to pick a different name in `bower.json` to publish to Bower.

**Comment by yairEO** [comment]
cool. didn't know about it. they don't seem to have any demo page sadly..
