### ISSUE TITLE
enhanced search

### ISSUE THREAD

**Issue by inVisement** [yairEO/tagify#190]

**Comment by inVisement** [comment]
Real world application: ticker search
User knows part of the company name, starts typing: 'coca' the dropdown shows (KO: The Coca-Cola Co.), when selects this item the company symbol (KO) will be added to tags.

whitelist: [{value: companySymbol, name: companyName}, ...]
dropdownItem: function(tag) {return tag.value + ': ' + tag.name}

and search should be matched any part of string.

BTW, it is an awesome plugin, thank you!

**Comment by yairEO** [comment]
Ok, I will add it to my backlog, thanks!

**Comment by yairEO** [comment]
Done, see: https://github.com/yairEO/tagify#example-for-a-suggestion-item-alias
