### ISSUE TITLE
Unminified dist version

### ISSUE THREAD

**Issue by ap** [yairEO/tagify#193]
It would be nice to have a copy of the built but not yet minified source in `dist`. I want to take the code you are graciously publishing in `dist` (instead of dealing with another dependency on a toolchain (since I do not already have deps on either Gulp or Babel)) – but during development it would be nice to be able to actually read the code. That way I can be sure that the code I’m looking at is the same as the code I’ll be shipping to visitors, even though I get the readable form and they get the fast-loading form.

If you do not publish such a file, I can only get it by installing your toolchain and making such a file myself. And then to make my build reproducible, I need to deal with version-pinning it all etc…

(I guess this is what the person in #158 wanted also.)

**Comment by yairEO** [comment]
But there is already *unminified* version in the `dist` folder..

https://github.com/yairEO/tagify/blob/master/dist/tagify.js

**Comment by ap** [comment]
Uhm, wow. I don’t know what kind of blindness struck me. Sorry about the noise.
