### ISSUE TITLE
Include tag data on 'edit' event

### ISSUE THREAD

**Issue by mattiasnixell** [yairEO/tagify#195]
The #192 pull request got merged into master at the perfect moment for a project I'm working on, thanks! However, I noticed a missing piece. The 'edit' event details only include the tag value. Not the tag data as it is on the 'add' event if you have an object whitelist.

To circumvent this I manage the tag data outside of Tagify instead. Yet, it'd be cleaner/more consistent if the 'edit' event returned a whitelist data object similar to how the 'add' event does.

Other than that, great job on this library, it's flexible and easy to work with!

**Comment by yairEO** [comment]
Thanks! I will hopefully get to fix this today
