### ISSUE TITLE
Get tags value

### ISSUE THREAD

**Issue by pesseyjulien** [yairEO/tagify#197]
Hi,

I updated to the newer version, but now when I get the tags input value (.val() method) I'm getting :

`[{value:fr}]`

Anyway to just get the 'fr' ?

Thanks in advance,
Julien

**Comment by yairEO** [comment]
You need to parse it yourself either on the client or the server. Why is this a problem?

**Comment by pesseyjulien** [comment]
I see, good point. Thanks for your answer.

Maybe you have an easy way to parse it then ?

**Comment by yairEO** [comment]
var value = JSON.parse( tagifyInput.val() )

**Comment by ycv005** [comment]
Situation- Using Tagify inside my django project within bootstrap 4 model. When I was sending data via $(this).serialize, it was not appropriate. So this is how I made an appropriate data format. (Also, I need not to install [django-tagify](https://pypi.org/project/django-tagify/)). Hope below method will help some one.
`var TagValues = JSON.parse($('[name=tags]').tagify().val())
        var TagArray = []
        for(let i=0;i<TagValues.length;i++){
            TagArray.push(TagValues[i].value)
        }
        var dataToSend = $(this).serializeArray();
        for (let index = 0; index < dataToSend.length; ++index) {
            if (dataToSend[index].name == "tags") {
                dataToSend[index].value = TagArray;
                break;
            }
        }
$.ajax({
        url: url,
        method: httpMethod,
        data: jQuery.param(dataToSend)
....
....`

**Comment by cvid2410** [comment]
To retrieve the data from tagify on your django view just use the eval() built-in function.

So, in your view you would do `tags = request.POST['tags']`, then you can loop as such `for tag in tags:
print(tag['values'])`

**Comment by willmeyers** [comment]
> To retrieve the data from tagify on your django view just use the `eval()` built-in function.
> 
> lets say in your form you have:
> `<input type='text' name='tags'>`
> 
> So, in your view you would do:
> `tags = eval(request.POST['tags'])`,
> 
> then you can loop as such:
> `for tag in tags: `
> ` print(tag['value'])`

I also just wanted to chime in say if your going with the above solution, you might want to consider using Python's built-in json module instead of eval. Building off from the above example.
```python
import json
...
tags = json.loads(request.POST['tags'])
...
```

**Comment by HRahman1777** [comment]
If anyone looking for another solution in PHP to get values, I think this may help.
[Personally, I was looking for solution and this issue came over]

```
$value = $request->tags;

$tag_array = [];
$manage = json_decode($value, true);
for ($i = 0; $i < count($manage); $i++) {
array_push($tag_array, $manage[$i]['value']);
}
```
you will get all values in `$tag_array` this array.

<br>

Script with input form
```
var input = document.querySelector('input[name=tags]');
new Tagify(input);
```

**Comment by iamcodefoxx** [comment]
Anybody looking to parse their tags on the server with Node.js? Here it is. 
`  let tags = {}; // CREATE JSON OBJECT
  const values = JSON.parse(req.body.tags); // PARSE TAGS COMING IN FROM THE FRONT END

  for(let i = 0;i < values.length;i++) // LOOP THROUGH EACH TAG
    tags[`${i}`] = values[i]["value"]; // STORE EACH VALUE IN THE JSON OBJECT

  tags = JSON.stringify(tags); // CONVERT TO JSON  (TO STORE IN DATABASE)`
