### ISSUE TITLE
Disable spacebar

### ISSUE THREAD

**Issue by splyy** [yairEO/tagify#198]
Is it possible to disable the tag addition event when using the space bar?
I would like to have tags containing sentences :bulb: 

Maybe I can use the `tagify.on('input', onInput)` methods ? But if there is a simpler and faster method: I take!

(Great job this plugin!)

**Comment by yairEO** [comment]
why are tags being added after clicking the spacebar in the first place?

Please share your Tagify settings configuration

**Comment by splyy** [comment]
That's precisely my problem : If I enter **New York**, for example, I get `New` and `York` instead of `New York` :thinking: 

I have a basic configuration :
```
new Tagify(input, {
    maxTags: 4
})
```

**Comment by yairEO** [comment]
This doesn't happen for me.. Are you using the latest *Tagify* version?

on which browser also?

This also does not replicate in the [demo page](https://yaireo.github.io/tagify/)

**Comment by splyy** [comment]
I'm using `"@yaireo/tagify": "^2.12.2"`.

I use Firefox, but I just tested it on Opera for example and I notice that the spacebar is not counted as a delimiter.

I think the problem may be on Firefox 🤔 I'll look into it in more detail first thing in the morning.
