### ISSUE TITLE
Feature request: List of matching tags

### ISSUE THREAD

**Issue by bobrinch** [yairEO/tagify#2]
May I suggest a new feature: A list of matching tags showing in a list while you type in a tag.

For example, you type in #j and the list shows 5 available tags containing a "j". Typing #jq and the list is limited to tags containing "jq". User may select one of the matching tags from the list.

Anway, nice work you did with tagify :+1:

**Comment by yairEO** [comment]
I will add this, good idea.

**Comment by yairEO** [comment]
Done! check the demo:

https://yaireo.github.io/tagify/

**Comment by bobrinch** [comment]
Nice work. Thanks :-)
