### ISSUE TITLE
removeTag is not working

### ISSUE THREAD

**Issue by dimmat** [yairEO/tagify#200]
Sorry for the new issue but you closed the previous one too early. 

I skipped the JQuery version of Tagify (JQuery.tagify.min.js) and tried to use the latest plain-javascript version (tagify.min.js). I also tried to implement all other of your suggenstions. My code now is:

```js
<!DOCTYPE html>
<html lang="el">

<head>
    <meta charset="utf-8">

    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="js/tagify/tagify.css" />
    <link rel="stylesheet" type="text/css" href="css/style.css">
    
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/tagify/tagify.min.js"></script>    
</head>

<body>

<div class="container">
    <h1>Test page</h1>
    
    <div class="row">
        <div class="col-md-12">
            <input id="txtMyList" value="">
        </div>
    </div>
    
    <div class="row" style="margin-top:10px;"><div class="col-md-12"></div></div>    
    
    <div class="row">
        <div class="col-md-12">
            <button id="btnRemove" type="button" class="btn btn-primary">Remove item with value -a-</button>
        </div>
    </div>
    
</body>

</html>

<script>
$(document).ready(function() 
{ 
    var tagify = new Tagify($('#txtMyList')[0], 
    {
        pattern: null,   
        delimiters: ',|',
        keepInvalidTags: false,
        callbacks: {},
        addTagOnBlur: true,
        duplicates: false,
        whitelist: [],
        blacklist: [],
        enforceWhitelist: false
    });
        
    $('#btnRemove').on('click', function()
    {
        alert('Button was pressed!');  
        tagify.removeTag('a'); // Remove item with value 'a' if it is in txtMyList textbox
    });

}); 
</script>
```
Please revise the removeTag function again, it seems that it is not working. Thank you.

**Comment by yairEO** [comment]
You could have asked me to re-open instead of creating a new one..

Why is the `<script>` tag outside of the `</html>` tag?

**Comment by dimmat** [comment]
Putting the `<script>` tag inside the `</html>` tag, will solve the problem? 

Anyway, I've done it but nothing happend, the problem remains. Any other "suggestions"? :-)

**Comment by yairEO** [comment]
Ok, fixed on `2.14.0`, please try the latest version now.

Thanks

**Comment by adinhodovic** [comment]
Tried 2.14 still can't get it to work with vanilla JS (?).

**Comment by yairEO** [comment]
@adinhodovic - works for me.. do you have any error in the console?

**Comment by metalsoft10** [comment]
hi can i remove tag with id 

tagify.removeTag([{id:data.res}]);

**Comment by metalsoft10** [comment]
![image](https://user-images.githubusercontent.com/12839970/93024502-5b8e4880-f5f7-11ea-8980-5da3e8e03ff0.png)
 and how to use this way

**Comment by yairEO** [comment]
@metalsoft10 - no you cannot use `id` (which is something Tagify knows nothing of) to remove a tag.

in Tagify, only the `value` property is considered special, not `id`. You can call `removeTags` with a String corresponding to your `id`, for example:

    tagify.removeTags('123456789')  // the first parameter must be of type String

----

I don't understand your second question because it's not clear on what the red arrow is pointing. You could have simply wrote it down to be clear instead of taking a screenshot of the docs :)
