### ISSUE TITLE
Deleting (backspacing) current tag input to the end, makes subsequent input change into tag immediately

### ISSUE THREAD

**Issue by Illusive7Man** [yairEO/tagify#201]
Happens on Firefox, not on Chrome. Using the latest version (dist folder). 

If I input something like **_progra_** and backspace it to the end, and whether I leave the field and return or do it immediately afterwards, next input (any letter on the keyboard) changes into one letter tag, automatically.

I use "," as the delimiter, with server side whitelist (ajax), which isn't enforced. And my input trigger doesn't get triggered when I press that last key, but what gets triggered is:

1. _backspace_ makes e.value = ","
2. last input, for example a letter **s** has makes e.value = "s,"

**Comment by yairEO** [comment]
I honestly understand nothing of your description, but I will open my Firefox, type something and press backspace and see what happens..

**Comment by yairEO** [comment]
Ok, I see the bug.. will be fixed, thanks for reporting!

**Comment by brianwozeniak** [comment]
Actually I just fixed, noticed this yesterday:

https://github.com/yairEO/tagify/pull/202
