### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '$$hashkey' is not a valid attribute name.

### ISSUE THREAD

**Issue by hanzal** [yairEO/tagify#204]
tried using object list with values in the whitelist. when I try to create a tag the following error is thrown.

```contacts.bundled.min.js:1 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '$$hashkey' is not a valid attribute name.```

**Comment by yairEO** [comment]
Please tell me the **exact** steps needed to replicate the problem, including which browser  this occurred on

**Comment by malienist** [comment]
Are special characters not allowed inside the string for the first parameter of setAttribute() ?

**Comment by yairEO** [comment]
I think special characters are illegal as node attributes, as it does makes sense
