### ISSUE TITLE
Tags are added too soon

### ISSUE THREAD

**Issue by tobias-kuendig** [yairEO/tagify#205]
![ezgif-2-c84432e64468](https://user-images.githubusercontent.com/8600029/53624687-69d96700-3c01-11e9-901f-0d0649a4ad41.gif)

I write `page` then hit <kbd>Tab</kbd> to add the tag. When I remove it and begin to type again, the tag is added after the first keypress without hitting <kbd>Tab</kbd>. 

Is this a bug or configuration issue?

I'm using Firefox Nightly 67.

**Comment by yairEO** [comment]
This has been solved in the last update of tagify which was over a month ago, you probably used an earlier version. does this still happens with the last version?
