### ISSUE TITLE
Multiple tags in Whitelist as a single value

### ISSUE THREAD

**Issue by rNianios** [yairEO/tagify#208]
Hi,

I was wondering if it's possible to add multiple tags in a whitelist as a single value. What I want actually to achieve is while the user is typing to receive his/her history of multiple inputted tags. 

I've tried to push the following formats to whitelist but without success.
Case a:
whitelist =  ["F2YXJC2","F46R3L2"	]
and
Case b:
whitelist =  [ "F2YXJC2, F46R3l2"]

In case a, every tag is being a single tag which doesn't help, they should be displayed as a single selection. On case b the multiple tags are displayed together (good) but when they are clicked they are being added altogether as a single string into the input element rather than individual tags.

Any ideas about how to save multiple tags in whitelist as a single selection and return them as multiple tags?

Kind regards,
Romanos

**Comment by yairEO** [comment]
you want a whole tag to show many words which were once separate tags the user has chosen?

Do you have a design to upload here and show?

**Comment by yairEO** [comment]
Do you still need assistance regarding this?
