### ISSUE TITLE
calling dropdown.show() in react-wrapper?

### ISSUE THREAD

**Issue by privateOmega** [yairEO/tagify#210]
How do I show drop-down after making an AJAX request like `tagify.dropdown.show.call(tagify, value);` from React.JS using react-wrapper? I have already made a ref for Tags component using `this.tagifyRef = React.createRef();` and `<Tags ref={this.tagifyRef} />`

**Comment by yairEO** [comment]
Fixed. I've also improved the [React demo](https://codepen.io/vsync/project/editor/ARaJye) to show exactly what you've asked.
