### ISSUE TITLE
How to get input focus after dropdown item click?

### ISSUE THREAD

**Issue by fabianp60** [yairEO/tagify#218]
I want to know how to get the focus in the tagify input after a click in a dropdown item.

I modify the tagify.min.js but nothing works, I think is not working because the focus event must be called after any tags animation but i dont know where to do it.

Please help or suggestions

**Comment by yairEO** [comment]
But the input in the Tagify component already gets focus after clicking a dropdown item. Are you using the latest Tagify version?

**Comment by fabianp60** [comment]
mmmm ... I will try with the latest version

**Comment by fabianp60** [comment]
you were right, it was fixed with the latest version,

thanks a lot
