### ISSUE TITLE
Bug when changing letter to uppercase, tag become invalid

### ISSUE THREAD

**Issue by Mushr0000m** [yairEO/tagify#221]
Hi,

On the demo page https://yaireo.github.io/tagify/ in the first example, if you change for example `html` tag to `Html` it's marked as invalid. The comparaison with itself looks case sensitive and IMHO it shouldn't.

**Comment by yairEO** [comment]
Yes i see what you mean. I will change this line to be *case insensitive*

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L481

**Comment by Mushr0000m** [comment]
👍

**Comment by Mushr0000m** [comment]
I saw you fixed the issue but I can't install the version 2.19.2 from NPM, it's stuck to 2.19.1

**Comment by yairEO** [comment]
@Mushr0000m  - will be fixed in 6-7 hours after I get home from work and publish the version to NPM
