### ISSUE TITLE
Possible to add random colors for each tag?

### ISSUE THREAD

**Issue by hamzabinamin** [yairEO/tagify#223]
I'm showing tags in a particular column of a data row. I want each tag to have a distinct or a random color instead of all being grey. How can I do that?

If that's not possible, then is there a way I can use a different color for each of the tag input elements through html?
Something like:
`<input name="tags'" value="" readonly style="color: red;">`

**Comment by yairEO** [comment]
Ok, I've just updated the [demo page](https://yaireo.github.io/tagify/#section-advance-options) as to your request, but you also need to make sure you're using the at least *Tagify* version `2.18.1`

**Comment by hamzabinamin** [comment]
This works great thanks @yairEO however I've noticed the colors don't work if I make the tags readonly. Can you change that? I'm displaying a list that is coming from the db, so the user won't be writing any new tags themselves. Also would be nice if I can somehow hide the border of the input field. Since the tags class is somehow overriding the behavior.

**Comment by yairEO** [comment]
Why do you even need Tagify at all? why can't you just create some simple template which iterate over your list and creates tabs (`<div>`) elements and then simply style them?
