### ISSUE TITLE
Removing an element from values using react-wrapper

### ISSUE THREAD

**Issue by gencer** [yairEO/tagify#225]
I would like to remove an item from Tags. But, I am using React wrapper. Only accessible way is to change state.

Problem starts here. If I add values, state changes and my tags are added. Okay until here. Then I remove an item from state. But this does not remove anything from Tagify. Once its added, it should be manually removed.

Before I rewrite component, I wanted to ask if there is an easy way to remove tags from the list dynamically from main component and reflect to Tagify that removal.

**Comment by yairEO** [comment]
No problem, I will think about this and get back to you as soon as I can

**Comment by yairEO** [comment]
Fixed. See [React example](https://codepen.io/vsync/project/editor/ARaJye) in the [README](https://github.com/yairEO/tagify)
