### ISSUE TITLE
File path issue in Angular wrapper component

### ISSUE THREAD

**Issue by igarashitm** [yairEO/tagify#226]
Hi! this Tagify looks very promising and I'd like to use it in my Angular project.
So `angular-tagify.component.ts` and `angular-tagify.service.ts` are provided in `dist/`, but I hit a path problem there, I think it needs to either
1. change the name in the import statement from `tagify` to `angular-tagify`
or
1. change the file name to `tagify.component.ts` and `tagify.service.ts`

Thanks!

**Comment by yairEO** [comment]
But what is the actual problem? Can you describe the problem in detail?

**Comment by igarashitm** [comment]
It just doesn't transpile, saying like `./tagify.component.ts not found`

**Comment by igarashitm** [comment]
Here is the exact build error:
```
ERROR in node_modules/@yaireo/tagify/dist/angular-tagify.component.ts(2,29): error TS2307: Cannot find module './tagify.service'.
node_modules/@yaireo/tagify/dist/angular-tagify.service.ts(3,31): error TS2307: Cannot find module './tagify.component'.
```

**Comment by igarashitm** [comment]
FYI, I locally tested with this change in the node_modules/@yaireo/tagify and works fine.
```diff
diff --git a/dist/angular-tagify.component.ts b/dist/angular-tagify.component.ts
index c4c1485..a82d70e 100644
--- a/dist/angular-tagify.component.ts
+++ b/dist/angular-tagify.component.ts
@@ -1,5 +1,5 @@
 import {AfterViewInit, Component, EventEmitter, Input, Output, ViewChild} from '@angular/core';
-import {TagifyService} from './tagify.service';
+import {TagifyService} from './angular-tagify.service';
 
 export interface SettingsModel {
   delimiters?: string;
diff --git a/dist/angular-tagify.service.ts b/dist/angular-tagify.service.ts
index e22520e..5ed5906 100644
--- a/dist/angular-tagify.service.ts
+++ b/dist/angular-tagify.service.ts
@@ -1,6 +1,6 @@
 import {ElementRef, Injectable} from '@angular/core';
 import * as Tagify from '@yaireo/tagify';
-import { SettingsModel } from './tagify.component';
+import { SettingsModel } from './angular-tagify.component';
 
 @Injectable({
   providedIn: 'root'
```

**Comment by yairEO** [comment]
How is this even possible... what does importing has to do with file naming?

I'm googling this error and many people complain.

    Angular error TS2307: Cannot find module

**Comment by igarashitm** [comment]
Is this what you're looking for? without correct packaging with `.d.ts` bundled, it's just a file path without extensions like `.ts` or `.tsx`. https://www.typescriptlang.org/docs/handbook/module-resolution.html

This commit seems to have removed ng library packaging bits and just left those source files in dist dir.
https://github.com/yairEO/tagify/commit/5001e16e490625f263b03d9eccb9fac4eb1b9a88
Then only way to consume it is to import those source files and transpile as a part of application.
