### ISSUE TITLE
Retrieve instance in Vanilla JS

### ISSUE THREAD

**Issue by Mushr0000m** [yairEO/tagify#229]
I saw in the doc that with JQuery we can retrieve later the instance by doing `$(element).data('tagify')`. Is there a way without JQuery ? When creating it this way :  
```
var tagify = new Tagify(element, {...})
```
I have a piece of code that create an instance for each input with a certain class and on one page I need to add some whitelist tags and do some specific stuffs, but can't find a way to retrieve the tagify instance.

**Comment by yairEO** [comment]
var tagify = new Tagify(element, {...})

`tagify` is the instance. you created the instance when you uses the `new` keyword

**Comment by Mushr0000m** [comment]
Sorry but I think you didn't understand my question.

I create the instances in one place and need to access it on an other place, not the same file. As I said, in the doc you explain that when using JQuery we can access the instance created from the DOM element by doing `$(element).data('tagify')`. So my question was do you store something in the DOM element when NOT using JQuery so we also get the instance later in some other place.

**Comment by yairEO** [comment]
No, that is specific to jQuery. The data is not really on the DOM element, but in jQuery.

You will need to create your own solution. The easiest (and worst) way is to share the instances on the `window` object, since it is accessible from both files.

**Comment by AndryHTC** [comment]
Honestly, I agree with @Mushr0000m.
There should be a default way for accessing the "Tagify-ed" input without the need for the dev to recreate everything from scratch.

@yairEO After 4+ years do you have something to propose?

**Comment by Ashwinvalento** [comment]
@AndryHTC you could get the Tagify instance using the `__tagify` attached to the element.

Here is what I did.

```
const el =  document.getElementById("tagEl");

let tagify = el.__tagify;

if(!tagify){
   tagify = new Tagify(el);
}

.....
```

**Comment by AndryHTC** [comment]
@Ashwinvalento thanks a lot
