### ISSUE TITLE
The original input is not return the right value

### ISSUE THREAD

**Issue by xiangming** [yairEO/tagify#230]
I tried to get the original input value in this demo page: https://yaireo.github.io/tagify/
$('[name=tags]').val()

It returns things with role? Why?
[{"value":"css","role":"tag"},{"value":"html","role":"tag"},{"value":"javascript","role":"tag"}]

**Comment by yairEO** [comment]
Thanks for spotting that. I really need to create more tests. Will be fixed asap.
