### ISSUE TITLE
When you double click to update tag, it looks like the `transformTag` isn't being fired anymore.

### ISSUE THREAD

**Issue by owldesign** [yairEO/tagify#232]
It looks like when you are editing already added tag by double clicking it, the `transformTag` function isn't firing anymore, anyway to retrigger that? 

I'm appending `#` character infront of each new tag, but users can change tag by double clicking it and I can't use `transformTag` no longer to transform value.

Thank you for any help on this one!

**Comment by yairEO** [comment]
Fixed. Thanks for reporting!

**Comment by owldesign** [comment]
@yairEO thank for fixing this!

I did notice another thing, and I feel like its realated to this fix.

When you double click tags and click away anywhere it doesn't close editing of the tag. Before if you double clicked but changed your mind and clicked away it would go back.

**Comment by yairEO** [comment]
Fixed this new issue also. thanks for reporting again!
