### ISSUE TITLE
Adding new tag which is sub-string of a white-listed tag in JQuery

### ISSUE THREAD

**Issue by akhilpgeorge** [yairEO/tagify#233]
Hi @yairEO,

When i try to add a tag which is a sub-string of an already white listed tag, it is not getting added. rather the already white-listed tag is getting added.

Steps to reproduce,

1. Add "JavaScript" as a tag. Now "JavaScript" got added to white listed tags 
2. Try to add "Java"

When i type "Java", drop down will appear with "JavaScript" as first item. if i type ENTER, "JavaScript" will get added instead of "Java".

The cause may be the first item in drop down appears with active class.

How can i mitigate the issue?

PFB code

```javascript
$("#projtechnology").tagify({
		whitelist: allTags,
		autoComplete: false,
		backspace: false,
		dropdown: {
			classname: "color-blue",
			enabled: 1,
			maxItems: 5
		},
	});
```

**Comment by yairEO** [comment]
What do you mean _"Now "JavaScript" got added to white listed tags"_ ?

Tagify doesn't add things to the whitelist. You are probably doing that yourself

**Comment by akhilpgeorge** [comment]
Yes.. Me only added "JavaScript" to white list. 

my real issue is I've added "JavaScript" to white list. later when i try to add "java", it don't let me to add java since "JavaScript" appears as a drop-down which is active since I've enabled drop-down of white-list. Even if i type "Java" and press ENTER, "JavaScript" is getting added instead of "Java".

Hope you got my point...

**Comment by yairEO** [comment]
Why are you adding things to the _whitelist_? what is the goal of this? to allow new tags to be suggested in the dropdown after the first time they were added as new tags?

**Comment by akhilpgeorge** [comment]
suppose i have only "JavaScript" in white-list , i should be able to add "Java" as a tag right?? But when i try so, only "JavaScript" is getting added in tag.

![image](https://user-images.githubusercontent.com/20010559/57827422-e6252480-77c4-11e9-912f-e6e371d4b7f1.png)

Now if i press ENTER, instead of "Java", "JavaScript" is getting added. Hope this clarifies..

**Comment by yairEO** [comment]
Now I understand, thanks for clarifying. I've released a fix in `v2.19.2`

**Comment by akhilpgeorge** [comment]
Resolved. Thank you dude :heart_eyes:

**Comment by krzyko** [comment]
Many thanks, fix resolves issue also for me. Unfortunately it didn't make into 2.19.2 - release was tagged two commits earlier.

**Comment by yairEO** [comment]
I will republish then and bump
