### ISSUE TITLE
Send field value either as an array or as an empty string, when there are not tags selected

### ISSUE THREAD

**Issue by gaganlokesh** [yairEO/tagify#235]
I'm using tagify in a form and when I submit the form without selecting any tag, I'm getting empty string `""` as value. But, when I try to deselect all the tags and then submit it, I'm getting empty array in string format `"[]"` as value.

This makes it hard to validate form fields.

**Comment by yairEO** [comment]
how can you deselect all the tags if you said in the first sentence "without selecting any tag"? That means there where no tags to deselect in the first place. 

Why is it hard to validate the field? You have the `tagify.value` to validate against, which is an _array_ and if you don't have access to it, then you can validate by regex. it's quite easy.
