### ISSUE TITLE
Map labels to an actual value

### ISSUE THREAD

**Issue by ricardojbertolin** [yairEO/tagify#236]
First of all, thank you @yairEO for your amazing job.

I'm missing a feature, that consist on supporting a different value rather than showed on the tag.

In the demo page there is an example that explains this: https://yaireo.github.io/tagify/#section-extra-properties
It explains about a "mapValueToProp" property that in fact is the "actual" value.

However, it doesn't work to me. And furthermore, if you check the source code, "mapValueToProp" does not appear.

Could you please support such feature?

**Comment by yairEO** [comment]
Can you please post a code example?

**Comment by ricardojbertolin** [comment]
Thanks for your quick answer.

Imagine the following configuration:

```
 { 
       enforceWhitelist : true,
       mode: 'mix',
       pattern: /@/, 
        whitelist: [{value: 'myValue', actualValue:'myActualValue'}],
        mapValueToProp : 'actualValue'
   }
```
And then, a textarea like this:
`
<textarea name='mix'>This is my label @myValue</textarea>
`

If I check tagify.DOM.originalInput.value, my expected value should be: "This is my label myActualValue"

Nevertheless, on screen I would like to see the following:

![image](https://user-images.githubusercontent.com/2734242/58404559-ad5b3a00-8065-11e9-92bb-65f15d5df533.png)

Hope it clarifies. Thank you

**Comment by yairEO** [comment]
You did not initially specify the issue was specifically with the `mix` mode

I will fix fix this. somehow. soon.

**Comment by ricardojbertolin** [comment]
Sorry, I skip that part unintentionally.

Thank you!

**Comment by yairEO** [comment]
May I ask why don't you simply switch between `actualValue` and `value` properties?

**Comment by ricardojbertolin** [comment]
Not sure what you mean with "switch between actualValue and value"; can you please clarify?

**Comment by yairEO** [comment]
[{value:'myValue', actualValue:'myActualValue'}]
    // to
    [{value:'myActualValue', actualValue:'myValue'}]

**Comment by ricardojbertolin** [comment]
You mean, switching the fields before collecting the output? Still don't understanding, sorry..

In any case it won't work because of my purpose: showing different value than actual. I believe that a "mapValueToProp" field would solve it perfectly.

**Comment by yairEO** [comment]
Why don't you change the template then? this is very much solvable with a [custom template](https://github.com/yairEO/tagify#dom-templates)
