### ISSUE TITLE
Support initial value on mix mode containing white spaces

### ISSUE THREAD

**Issue by ricardojbertolin** [yairEO/tagify#237]
I'm trying to set an initial value for a textarea, with the following configuration:

- Mix mode
- White list enforced
- Pattern: @
- On white list, tags with whitespaces (e.g 'My label')
- An initial value that have an expression to be "tagified", for example: "This is @My label"

It seems that doesn't work if the label has whitespaces, but it works without them. 
This can be reproduced using the code in the demo page: https://yaireo.github.io/tagify/#section-textarea

My suggestion is, in the initial value, to limit labels between the pattern. For example: 
"This is @My label@". It would help for an easier implementation.

Thank you

**Comment by yairEO** [comment]
I am thinking to changing the initial tagging to this:

    [[cartman]] and [[kyle]] do not know [[homer simpson]]

**Comment by ricardojbertolin** [comment]
Great, thank you!
