### ISSUE TITLE
Same value with different attributes considered duplicate

### ISSUE THREAD

**Issue by gencer** [yairEO/tagify#238]
I have 2 different tags like this:

```
[
  { value: 'Gencer', id: 1, type: 'folder', data: {...} },
  { value: 'Gencer', id, 5, type: 'category', data: {...} }
]
```

As you can see, both tags are valued as `Gencer`. However, their attributes are different. One of them is a folder and other is category. I also render items and add icons based on type.

Problem starts here, When folder `Gencer` added, category `Gencer` cannot be added. If duplicates enabled, this time `folder` and `category` can be added multiple time. Also dropdown autocomplete does not show category when folder selected.

Can we at least add an `id` attribute to tags or similar to this to identify difference and check the uniqueness based on this value?

Or maybe, you can check similarity based on tag data (whole object) and not just by name (value)

**Comment by yairEO** [comment]
I'll fix this by tomorrow

**Comment by yairEO** [comment]
Why aren't you changing the `duplicates` setting to `true`?

**Comment by yairEO** [comment]
It is difficult for Tagify to know if a tag is a duplicate or not based on what you're asking, since the user is simply typing something, and if the `duplicates` flag is set to `false` which means the program should not allow duplicates to be added or be suggested (in the dropdown) then how can Tagify know it's not a duplicate? 

All the user has done was typing a word which already exist as a _tag_, and the typed word must be matched against something, and that something is the `value` property, because that's the only mandatory property. See the problem?

**Comment by gencer** [comment]
I re-reviewed my situation. There is 2 workarounds. First one changing value and append text other one is checking dupes on the backend.

Both ways, I decided to agree with you on this. Because, in the end, user will want to add a value that doesn't in autocomplete, This means only way to check dupes are with `value`

Thanks for looking into this, @yairEO.

Issue closed now.

**Comment by gencer** [comment]
@yairEO, I have successfully managed to pass this situation, however, one thing bothers me. Maybe you can understand better. I can create a new issue if you want.

Issue is, if I do this:

```
dropdownItem: function (item) {
          try {
            const value: string = item.value || item
            const name: string = item.name || value
            const email: string = item.email
            const avatar: string = item.avatar[0].url
            return `<div ${this.getAttributes(item)} class='${styles.uFlex} ${styles.uJustifyStart} ${styles.uAlignItemsCenter} tagify__dropdown__item'>
                <div class="${styles.uPrSmall}">
                  <img style="border-radius: 50%;" src="${avatar}" />
                </div>
                <div>
                  ${name}   <---- NOTICE HERE. CLINK ONLY WORKS HERE.
                  <br />
                  <span class="${styles.uTextMute}">
                    ${email}
                  </span>
                </div>          
            </div>`
          }
          catch (err) { }
        }
```

Then, my display is just what i want however, i cannot click image, content or anywhere for selecting. Only if I click to value it selects.

How can I force selection anywhere in the content? Do you check clicked are with value or something?
