### ISSUE TITLE
How to set delimiter to double space?

### ISSUE THREAD

**Issue by pkolenic** [yairEO/tagify#239]
I'm trying to allow **City, State** to be entered in as a tag.  However, for this to work I would need to be able to use a double space as the delimiter.

If tried `delimiters:'   '` and `delimiters:' \s{2}'` 
The first matches on a single space and the second matches on the literal \s but leaves the \\.

Ultimately I would like:
_New York City, New York  Boston, Massachusetts  Los Angeles, California_

To end up being three tags

- New York City, New York
- Boston, Massachusetts
- Los Angeles, California

**Comment by yairEO** [comment]
maybe without any delimiter? it's still possible to add tags by pressing <kbd>enter</kbd> or clicking outside (`blur` event)

**Comment by pkolenic** [comment]
Ok, I can work with that; thanks for the quick response

**Comment by yairEO** [comment]
I will release a fix anyway for this, so passing `"  "` will work
