### ISSUE TITLE
Clicking on dropdown item doesn't select if item has divs inside

### ISSUE THREAD

**Issue by gencer** [yairEO/tagify#240]
Issue is, if I do this:

```
dropdownItem: function (item) {
          try {
            const value: string = item.value || item
            const name: string = item.name || value
            const email: string = item.email
            const avatar: string = item.avatar[0].url
            return `<div ${this.getAttributes(item)} class='${styles.uFlex} ${styles.uJustifyStart} ${styles.uAlignItemsCenter} tagify__dropdown__item'>
                <div class="${styles.uPrSmall}">
                  <img style="border-radius: 50%;" src="${avatar}" />
                </div>
                <div>
                  ${name}   <---- NOTICE HERE. CLINK ONLY WORKS HERE.
                  <br />
                  <span class="${styles.uTextMute}">
                    ${email}
                  </span>
                </div>          
            </div>`
          }
          catch (err) { }
        }
```

Then, my display is just what i want however, i cannot click image, content or anywhere for selecting. Only if I click to value it selects.

How can I force selection anywhere in the content? Do you check clicked with value or something?

Here is a demo screencast:

![1](https://user-images.githubusercontent.com/1711576/58360386-3ec58300-7e91-11e9-8979-e5af532472bc.gif)

**Comment by yairEO** [comment]
Checking

**Comment by gencer** [comment]
Hey @yairEO, One more issue:

![1](https://user-images.githubusercontent.com/1711576/58387796-a90b2e80-801d-11e9-9351-f69ae869d4d9.gif)

**Description**: I listen `input` event. When input fired, i search on server-side via ajax. `enforceWhitelist` is `false`. `Enter` doesn't add my custom value, but `blur` (clicking another window in browser or desktop for example) adds value.


(Note: I am investigating this issue on Tagify, If I found anything I will either post here or open a PR).

**Comment by gencer** [comment]
I've found the second issue:

See this line: https://github.com/yairEO/tagify/blob/f5039d677d6b184e20e2b7354f7ab42ffdc0a9f1/src/tagify.js#L399

This should be `s` instead of `this.input.value`. But, If you rely on this, perhaps we can do this:

```
var value = this.input.value;
if(!value && s) {
   value = s;
}
this.addTags(value, true)
```

After this change:

![1](https://user-images.githubusercontent.com/1711576/58387980-ce4d6c00-8020-11e9-89b4-f3170cebc6d5.gif)
