### ISSUE TITLE
Angular not working

### ISSUE THREAD

**Issue by BDominik** [yairEO/tagify#243]
The angular installation guide is completly broken.
It's says that we need to import the service from 'ngTagify' but it's not exists.
Also the simple js version is not doin anything in angular more specificly in ionic 3 app.
Help pls...

**Comment by yairEO** [comment]
Some others helped me with the Anuglar wrapper, since I do not know anything regarding Angular. I honestly cannot help at all unless someone else will be kind enough to help fix this

**Comment by BDominik** [comment]
Thanks.

**Comment by BDominik** [comment]
Okay I just included the js and css file, and now it's working.
My only questi how to create new line?

**Comment by ricardojbertolin** [comment]
Probably you should use this: https://github.com/LironHazan/angular-tagify-module
Also, check out the medium post: https://itnext.io/how-i-wrapped-ngtagify-a-pure-js-lib-into-an-angular-module-packed-and-installed-it-on-my-app-ac828e89fdf0

**Comment by yairEO** [comment]
Yes, she is my friend & co-worker... she helped me and contributed to this project enabling Angular support.
