### ISSUE TITLE
Render suggestions dropdown manually

### ISSUE THREAD

**Issue by BDominik** [yairEO/tagify#244]

**Comment by yairEO** [comment]
what is the question?

**Comment by BDominik** [comment]
How to get cursor position #244

**Comment by BDominik** [comment]
I dont know what is not clear with the question.
To be more specific,  I want to get the cursor top and left position relative to the parent container, and display the suggestion list under the cursor position.

**Comment by yairEO** [comment]
I would suggest using [popper](https://popper.js.org/) for positioning, but currently this is too complex to do. I'll think about the place of this request in the project's roadmap

**Comment by yairEO** [comment]
Here's a [stakcoverflow discussion](https://stackoverflow.com/q/4928586/104380) regarding caret position

**Comment by BDominik** [comment]
Thanks.
