### ISSUE TITLE
Limit the length of a tag name

### ISSUE THREAD

**Issue by jasoncharnes** [yairEO/tagify#245]
Good afternoon! Thank you for Tagify. It is a beautiful addition to our application. 

I'm looking to limit the length of a given tag name to _n_ characters. I tried using a regular expression piped to `pattern` and found no luck.

```javascript
new Tagify(input, {
  pattern: /^.{1,70}/
}
```

My apologies, as I might misunderstand the use of `pattern`

Is there a way to limit the length of a tag? If so, would you mind pointing me in the right direction?

Thank you for your time.

**Comment by yairEO** [comment]
Hi! thanks you very much for the kind words :)

You can use the setting `transformTag` to achieve that, seen in [this example](https://yaireo.github.io/tagify/#section-advance-options).

**Comment by jasoncharnes** [comment]
This works great. Thanks, again!

**Comment by yairEO** [comment]
See [demo page](https://yaireo.github.io/tagify/#section-advance-options), using this `/^.{0,20}$/` pattern

**Comment by eugenetraction** [comment]
I implemented a tag max length by ignoring the user after they reached the max length
`
tagify.DOM.input.addEventListener('keydown', function(e) {
  if (tagify.state.dropdown.visible && tagify.state.tag.value.length >= TAG_MAX_LENGTH) {
    e.preventDefault();
  }
}
`

**Comment by FatihYilmaz06** [comment]
This soluiton works .


 $(".tagify").tagify({
        //  etiketin max uzunlugu
        pattern: /^[A-Za-z_✲ ]{1,50}$/,
    });
