### ISSUE TITLE
`Enter` key does not add value if `input` has ajax call but `blur` does

### ISSUE THREAD

**Issue by gencer** [yairEO/tagify#246]
Hey @yairEO, One more issue:

![1](https://user-images.githubusercontent.com/1711576/58387796-a90b2e80-801d-11e9-9351-f69ae869d4d9.gif)

**Description**: I listen `input` event. When input fired, i search on server-side via ajax. `enforceWhitelist` is `false`. `Enter` doesn't add my custom value, but `blur` (clicking another window in browser or desktop for example) adds value.

After few seconds, enter works but this is random

**Comment by gencer** [comment]
I've found the second issue:

See this line: https://github.com/yairEO/tagify/blob/f5039d677d6b184e20e2b7354f7ab42ffdc0a9f1/src/tagify.js#L399

This should be `s` instead of `this.input.value`. But, If you rely on this, perhaps we can do this:

```
var value = this.input.value;
if(!value && s) {
   value = s;
}
this.addTags(value, true)
```

After this change:

![1](https://user-images.githubusercontent.com/1711576/58387980-ce4d6c00-8020-11e9-89b4-f3170cebc6d5.gif)

**Comment by gencer** [comment]
This fixed in the last build. Weird. :)

**Comment by yairEO** [comment]
Thanks for reporting! will be fixed in a few hours once I get home from work.
