### ISSUE TITLE
Double-click tag fires both "edit" & "click" custom events

### ISSUE THREAD

**Issue by shakeeb-mts** [yairEO/tagify#247]
When we double click a tag to edit it should not trigger the click. Currently it is generating 2 click event.

As I am running some test which is CPU intensive per tag on click and show the result of them but when I go for editing the callback is still running.

Any quick solution would be highly appreciated.

Rest the library is great KUDOS for that.

**Comment by yairEO** [comment]
For now I think this solution should work for you (haven't tested it)

```
function applyTagify(){
    const tagify = new Tagify(...);
    let clickTimeout; // declare a timeout variable at the same scope where tagify is declared

    tagify.on('click', onClick)
          .on('edit', onEdit)

    function onClick(e){
        if( e.detail.classList.contains("tagify--editable") ){
            clickTimeout && clearTimeout(clickTimeout);
            return;
        }

        clickTimeout = clickTimeout || setTimeout(()=>{
            ...CPU-intensive code here...
            clickTimeout = null; // reset
        }, 400) 
    }

    function onEdit(){
        ...
    }
}
```

**Comment by shakeeb-mts** [comment]
Hi @yairEO any luck doing it.

**Comment by yairEO** [comment]
I didn't test the above code, it's probably a minor thing, so I will test it soon and let you know. There is no internal "fix" to this, and one must work out a specific fix outside of Tagify's scope (as shown above)

**Comment by shakeeb-mts** [comment]
Hi we can add a double click event in the library just like click event.

**Comment by yairEO** [comment]
@shakeeb-mts - why do you need to know about a double-click event fired?
it's the same as `editTag` event, if you allow tag-editing
