### ISSUE TITLE
IOs device problem

### ISSUE THREAD

**Issue by BDominik** [yairEO/tagify#248]
On iPad and iPhone the plugin not working correctly.
When I'm focusing to the input then the keyboard shows and after typeing it's not showing anything.
Like I'm focused on the textarea but it's content not syncing into the wrapper.

**Comment by yairEO** [comment]
I don't understand anything. Which browser?

**Comment by BDominik** [comment]
![kép](https://user-images.githubusercontent.com/1481659/58546051-dbc34b80-8204-11e9-9ff6-8d5ab823f204.png)
The wrapper is obviously the content editable span, I mean what else should be..., and like I said when I clicking ot it the keyboard pops up, but on typing it's not inserting anything inside the span content editable, but in the textarea which is not visible because you set it to display none.
So this is why I said it's not syncing.

**Comment by BDominik** [comment]
Actually nevermind, I already spent to much time whit this plugin.

**Comment by yairEO** [comment]
I have no clue you referenced the Tagify's input element as the word "wrapper", I have no way of knowing that and it's very much not obvious. 

I've asked you which browser does this happens on, but you did not say. 
May I know the browser where this bug happens? did you try different browsers?

BTW, You should not close a bug if the bug exists, even if you are the reporter.
If you experience the bug, so might be others.

**Comment by perrystone1** [comment]
I've experienced the same thing Bdomnik experienced on a Cordova iOS app.

Basically, when you tap on the input field, the keyboard appears, but whatever you type does not show on the input field itself. It's like the input field is disabled when it shouldn't be.

It works fine on Cordova Android. 

On iOS, it also works fine on Safari, Chrome, and Firefox. I suspect the issue is with the JS engine Cordova iOS uses.

**Comment by yairEO** [comment]
So you're saying everything works fine on a real device but not in some simulated env?

**Comment by perrystone1** [comment]
Correct.

Adding these in the CSS file appears to have fixed the Cordova IOS problem:

-webkit-user-select: text;
user-select: text;
-webkit-user-modify:read-write;

I added them in these:
.tagify__tag>div>[contenteditable] {}
.tagify__input {}

Thanks for the awesome library!
