### ISSUE TITLE
tags color

### ISSUE THREAD

**Issue by alibabaazimi** [yairEO/tagify#25]
Tags color not working when we set background color for parent div or container.

# For example:

    <div style="background-color: black">
        <input type=text id="tg">
    </div>

    <script>
        var tag = document.getElementById("tg"),
            tagify1 = new Tagify(tag);
    </script>

**Comment by yairEO** [comment]
Yes, I forgot to address that in the CSS.. I will this ASAP. for now, you can add `z-index:1` in the below rule in the CSS/SCSS source code

    tags tag > div{ z-index:1 }

**Comment by alibabaazimi** [comment]
Thank you so much. It works now.
And can you tell me how to insert value and label both in the whitelist?
for example:
<option value="1">Javascript</option>
<option value="2">CSS</option>
<option value="3">Html</option>

And the output should be tags=1,2,3

Thank you

**Comment by yairEO** [comment]
you cannot do both, you should convert the works to numbers before sending the data to the server in a separate function where it can access some sort of dictionary (probably best an `Object`) which will be used to convert the words into whatever the server needs. OR, you could do it on the server...before it's saving the result into the DB.
