### ISSUE TITLE
EVENT on ADD tags added by script, tags added by user

### ISSUE THREAD

**Issue by Tadek888** [yairEO/tagify#250]
Hello :)
Need to find some solution to distinguish event 
`tagify.on('add', function(e){...`
when tag is added by user and when tag is added by script on load. Just need to add ajax update tags :)

**Comment by Tadek888** [comment]
In my case it work :)
```
tagify.on('add', function(e){
    if(tagify.listeners.dropdown){
        var tag_id = e.detail.data.code;
        //do my code
    }
});
```

**Comment by yairEO** [comment]
nice solution, but you can simply bind your even listener **after** you added your default tags grammatically, therefor every event triggered afterwards must be by the user:

```
const tagify = new Tagify(...);
tagify.addTags(["aaa, bbb, ccc"]) // add your tags, as soon as tagify is initialized 
tagify.on('add', onTagAdded) // now you can bind the event, after the above was done
```
