### ISSUE TITLE
Output type

### ISSUE THREAD

**Issue by Gibbu** [yairEO/tagify#251]
Greetings, I am making a PHP/SQL website that uses comma separated arrays. Is there a way to turn the json data that it gives me from this:
```
[{"value":"addon"},{"value":"anime"},{"value":"space"},{"value":"nature"},{"value":"abstract"}]
```
to this?:
```
addon, anime, space, nature, abstract
```
Fantastic library by the way. <3

EDIT:
Never mind, I found a way.
```php
implode(', ', array_column(json_decode($_POST['tags']), 'value'));
```

**Comment by marcelogarbin** [comment]
@Gibbu Thank you, you helped me. Are you using this package yet? Some problem? I'll start using it.

**Comment by yairEO** [comment]
Related to #197 which I'm currently handling and will release a new Tagify *setting* shortly which gives the power to manipulate the output format. stay tuned.
