### ISSUE TITLE
Input value sent changed at v2.21.1

### ISSUE THREAD

**Issue by Mushr0000m** [yairEO/tagify#255]
Sorry to open an other issue but I found a change that break my inputs after updating to the last version and after searching the changes happen at v2.21.1. My input when loading the page have this value : `[{"id":36,"value":"Berger"},{"id":45,"value":"Suzanne"}]` but when submitting the form I lose all keys in this object except the `value`ones, so I have server side : `[{"value":"Berger"},{"value":"Suzanne"}]`. Before the update I had all the key/values from selected tags.

Maybe I missed something or a change needed in the options ?

**Comment by yairEO** [comment]
I will check as soon as I get home from work! thanks. 
I really aught to write more [tests](https://github.com/yairEO/tagify/blob/master/test/tagify.test.js) to cover many of the common cases

**Comment by Mushr0000m** [comment]
Yep I took the latest version, that had this issue, and downgraded it to be able to tell you when the issue occured ;-)
