### ISSUE TITLE
Loading CSS Error (with fix)

### ISSUE THREAD

**Issue by davidgolden** [yairEO/tagify#256]
I was getting an error when loading any of the css or scss files with webpack. I ended up creating my own local copy and changing line 139 of tagify.scss from `animation : .3s tags--bump 1 ease-out;` to `animation : tags--bump .3s ease-out 1;` to fix the issue. It seems that the corrected version is in line with [specification](https://developer.mozilla.org/en-US/docs/Web/CSS/animation).

**Comment by yairEO** [comment]
thanks! I will change on push an update. I wasn't aware there the order on the animation value parts is important. It always worked fine for many years
