### ISSUE TITLE
When you use mixed content, transformTag is not being fired

### ISSUE THREAD

**Issue by vonmaster** [yairEO/tagify#258]
Hi,

First of all, thank you for this very useful script. 

I found an issue. When I use mixed content, `transformTag` is not being fired. Is it normal?

I applied a quick fix by adding this line `this.settings.transformTag.call(this, tagData);` in the function `addMixTag`.

>         addMixTag: function addMixTag(tagData) {
>             if (!tagData || !this.state.tag) return;
>             var tag = this.state.tag.prefix + this.state.tag.value,
>                 iter = document.createNodeIterator(this.DOM.input, NodeFilter.SHOW_TEXT),
>                 textnode,
>                 tagElm,
>                 idx,
>                 maxLoops = 100,
>                 replacedNode;
> 
>             this.settings.transformTag.call(this, tagData); // fix is here
> 
>             while (textnode = iter.nextNode()) {

Best regards,

**Comment by yairEO** [comment]
Thanks for reporting, will be fixed hopefully by tomorrow
