### ISSUE TITLE
Event not triggering (?)

### ISSUE THREAD

**Issue by EmanueleCoppola** [yairEO/tagify#26]
Hello, I have this piece of code
```
$('.tagify').each(function () {

            var $toTagify = $(this);

            $toTagify.tagify({

                duplicates : false

            });
            
            $toTagify.on('add', function (e) {
                console.log(e);
                console.log("test");
            });

        });
```

but the events are not triggering. Am I wrong or there's something that doesn't work properly?

**Comment by yairEO** [comment]
Hi, Are you using the jQuery version or the vanilla version?

I think I know what's happening here, and that's a fault of mine, I think I forgot to dispatch a jQuery event and i'm only dispatching the plugin's own events, so it should be like this:

    $('.tagify').each(function () {
        var $toTagify = $(this);

        $toTagify.tagify({ duplicates:false });
        
        $toTagify.data("tagify").on('add', function(e){
            console.log(e);
            console.log("test");
        });
    });

You currently need to use the `.data("tagify")` to access the `Tagify` instance which is attached to the jQuery element, until I will update the source code to also dispatch jQuery events.
