### ISSUE TITLE
Pressing Enter while Suggestion List is open

### ISSUE THREAD

**Issue by theRiley** [yairEO/tagify#262]
I love this library and incorporating it as a Vue component for a project at my company. It was super easy to set up and thank you for creating it.

Issue I got back from the QA team, this is my first time submitting an issue so I am sorry if information in this form isn't right or if this isn't the right place for this.

**Example Tags:**
bravo, brake,

**Use Case:**
User wants to enter a new tag "bra". They type "b" - "r" - "a" and the auto suggest dropdown appears showing "bravo" and "brake". They hit ENTER and a break return appears in the textarea.  

**Config:**
- Must be a textarea, based on the layout we have
- enforceWhitelist must be false since users add new tags in this same area

**Expected Behavior:**
The new tag "bra" would be added when Enter is pressed. From our QA team "enter should work the same as comma".

I have some push back on this, but thought I'd ask you before going that route.

Thank you so much.

**Comment by yairEO** [comment]
Thanks! first, which Tagify version are you using?

**Comment by yairEO** [comment]
Please try latest version `2.22.3`

**Comment by theRiley** [comment]
This works great, thank you so much.
