### ISSUE TITLE
JQuery events tagify.on('input', ...) not triggered

### ISSUE THREAD

**Issue by Mushr0000m** [yairEO/tagify#264]
From the doc I read there are some events emitted like `input`, `dropdown:show` etc. But I'm using JQuery version and from my understanding by doing `let tagify = $(element).data('tagify')` I should have the tagify instance and so I should be able to register new events later like this : 
```
tagify.on('input', function (event) {
    console.log(event);
});
```
But it's not working. Any idea ?

**Comment by yairEO** [comment]
No idea, I will check soon (a bit busy this week, but hopefully in a few days)

I would like to recommend not to use the jQuery version at all, there is no need

**Comment by yairEO** [comment]
The demo shows how it should be done:

https://yaireo.github.io/tagify/#section-jquery

You are using jQuery on a non-jquery element, therefor you cannot bind jQuery events
