### ISSUE TITLE
Identifying callback instance

### ISSUE THREAD

**Issue by iwalucas** [yairEO/tagify#265]
I have a page that can have MULTIPLE input tags, I was able to have it working quite good, but am struggling finding a solution for the input typeahead whitelisting....

I create my tags like this (on a loop of the inputs):
```javascript
var instance = new Tagify(tagNode, {
		callbacks: {
			add: callbackTag,
		    remove: callbackTag,
		    input: typeahead
		},
    });
```

On the typeahead callback I am not able to identify the instance of the caller, so I cannot define the whitelist, could maybe the event send back a reference for the tagify instance? That would solve this.

Thanks!

**Comment by yairEO** [comment]
Well, you could simply use your own callbacks that will call the callbacks you want (shown in first post), something like this:

javascript
```
var instance = new Tagify(tagNode, {
		callbacks: {
            add   : e => { callbackTag(e, instance) },
            remove: e => { callbackTag(e, instance) },
            input : e => { typeahead(e, instance) }
        }
    });
```
