### ISSUE TITLE
Pasted text separated with new line symbol doesn't process correct

### ISSUE THREAD

**Issue by nikbo** [yairEO/tagify#267]
I have the latest version (2.22.3) and I have a code to initialize tagify:
```
this.tagify = new Tagify(emails, {
                delimiters          : ",| |:", 
                suggestionsMinChars : 3,
                maxTags             : 100,
                keepInvalidTags     : true,
                duplicates: false
            }
        );
```
If I paste lines like these, separated by new line symbol ('\n'):
```
example@fake.com
example2@fake.com
example@fake.com
example3@fake.com
```
And then click enter - it doesn't process text in a correct way:
<img width="644" alt="Screen Shot 2019-06-26 at 12 10 50" src="https://user-images.githubusercontent.com/3669062/60167355-9ac25500-980b-11e9-8b7d-d6c350695ed2.png">
As you can see it adds "||" symbols.

Pasting works fine if I paste text separated by comma or whitespace.

Thanks.

**Comment by yairEO** [comment]
Thanks for reporting, I'll fix it asap

**Comment by yairEO** [comment]
Updated *Tagify* version to fix this (v2.24.0). 

You should write your Regex as so:

```javascript
tagify = new Tagify(input, {
        delimiters          : ",| |:|[\\n\\r]",
        suggestionsMinChars : 3,
        maxTags             : 100,
        keepInvalidTags     : true,
        duplicates: false
    }
);
```

**Comment by keksa** [comment]
Hello @yairEO, we have exactly the same problem with `v2.31.6`. Is there any chance of regression with this bug?

This input does not work:
```
fd:97:30:9b:66:70
b5:b4:e6:cc:6b:de
01:1b:75:84:c2:2f
```

This one works just fine:
```
fd:97:30:9b:66:70,
b5:b4:e6:cc:6b:de,
01:1b:75:84:c2:2f
```

The settings can be just to reproduce:
```
{
    delimiters: ",| |[\\n\\r]"
}
```

**Comment by yairEO** [comment]
@keksa - I will check and let you know

**Comment by yairEO** [comment]
Related - https://github.com/yairEO/tagify/issues/160#issuecomment-465309897

**Comment by keksa** [comment]
Hi @yairEO, I tried and it does not help at all.

First, I now understand this issue https://github.com/yairEO/tagify/issues/268. The problem is, that with the delimiters now being a regexp (instead of list of characters), the `this.settings.delimiters.source.charAt(1)` will return `|`, which will not match as delimiter, because it is not one of delimiters.

Second, even if I change the code to use `,` (just for debug) instead of the `charAt(1)`, which is a valid delimiter in my case, it will still not process the pasted text correctly. Instead of creating 3 tags, it creates a single invalid tag with everything squashed together.

**Comment by yairEO** [comment]
@keksa - ok, I see there is a bug with the CSS of the input itself and will issue a fix asap (hopefully today I will be releasing a major version)

For now, keep your delimiters setting:

    delimiters: ",|[\\n\\r]"

**Comment by keksa** [comment]
Hello @yairEO, I tried grabbing the code from the `v3` branch and the newline paste still does not work even after the CSS fix.

Works properly with commas, copy & paste of
```
fd:97:30:9b:66:70,
b5:b4:e6:cc:6b:de,
01:1b:75:84:c2:2f
```
results in:
![comma](https://user-images.githubusercontent.com/7985651/69950299-7c1b6500-14f3-11ea-99d0-3f461bbfdccc.png)

Does not work without commas, copy & paste of:
```
fd:97:30:9b:66:70
b5:b4:e6:cc:6b:de
01:1b:75:84:c2:2f
```
results in:
![not-comma](https://user-images.githubusercontent.com/7985651/69950311-8473a000-14f3-11ea-9747-394a4c6524b4.png)

The configuration is reduced to just this for testing:
```js
var tagify = new Tagify(
    document.querySelector('.js-inventory-mac-addresses'),
    {
        delimiters: ",|[\\n\\r]",
    }
);

**Comment by yairEO** [comment]
Just released version `3.0.0` so this should work. Try updating Tagify and check

**Comment by keksa** [comment]
Hi @yairEO, sorry to say it still does not work. Same settings as above, same data, Tagify updated to 3.1.0.

**Comment by yairEO** [comment]
![GIF](https://user-images.githubusercontent.com/845031/71028184-1b07aa00-210d-11ea-9e69-beec8d71f978.gif)

copy-pasted your exact text from your comment and it works fine. 

**BUT** now I see the problem is only with Firefox. Do you happen to use Firefox and not say it all this time..? :)

**Comment by keksa** [comment]
@yairEO I use Firefox as primary browser and it was where I first noticed the problem. However I tried in Chrome (latest version) with the exact same code I posted and Tagify 3.1.0 and it did not work as well, behaved exactly the same as Firefox.

I'm on macOS, so maybe that could be the issue? I'll try tomorrow when I get back to office and let you know. Also I'm always pasting with keyboard shortcuts (cmd+v), possibly it could make a difference as well?

**Comment by keksa** [comment]
Hello @yairEO, it works in Chrome, I think I may have screwed up a little when I was trying it and only used the new JS, but not CSS and since the fix was in CSS, it did not work.

However it still does not work in Firefox, could you please look into that? 🙂

**Comment by yairEO** [comment]
I fixed it and will release the new version today. it's totally fixed so don't worry.

I just prepared a big release with many other fixes issues and a few new features and am testing things now

**Comment by yairEO** [comment]
Please try `v3.2.0`

**Comment by keksa** [comment]
@yairEO It works! Thank you very much.
