### ISSUE TITLE
Now, **delimiters** are regular expressions.

### ISSUE THREAD

**Issue by eav93** [yairEO/tagify#268]
Now, **delimiters** are regular expressions. When I set
 `{delimiters: ',|;'}`
 `this.settings.delimiters.source.charAt(1)=='|'
`

_Originally posted by @eav93 in https://github.com/yairEO/tagify/issues/160#issuecomment-506964551_

**Comment by yairEO** [comment]
Thanks! will be promptly fixed

I was extremely occupied these few weeks but I will get sh*t done asap.

**Comment by yairEO** [comment]
Can you please explain the problem with words?
