### ISSUE TITLE
Can not move cursor to left and insert tag between the existing tags

### ISSUE THREAD

**Issue by Jiramew** [yairEO/tagify#269]
Thanks so much for creating such a great package.

In non-mix mode, The cursor won't response for the 'ArrowLeft' keydown event.
Will you provide some help?

Thanks so much.
Jiramew

**Comment by yairEO** [comment]
What response are you expecting?

**Comment by Jiramew** [comment]
Like:
“[Tag A][Tag B][Tag C]|”， where [Tag X] means the existing tags, and "|" is the cursor.
Hit left key on keyboard:
“[Tag A][Tag B]|[Tag C]”
Hit left key again:
“[Tag A]|[Tag B][Tag C]”
and so on.

Thanks.

**Comment by Jiramew** [comment]
Finally got it working, thanks~

**Comment by FurbyonSteroid** [comment]
Thanks, I too enjoy trying random stuff for several days. Glad you didn't spoiler me :neutral_face:

**Comment by yairEO** [comment]
@FurbyonSteroid - don't worry, I will help you. As I understand you require the same? 

The order of the tags is important in your case and you would like to add a tag in between tags?

**Comment by FurbyonSteroid** [comment]
Thanks, I appreciate it! 

The order is not necessarily important, but it would still be nice.. The user might find it weird if the ordering changes when navigating.

So we would love to be able to use left and right arrow keys to navigate through the already added  tags. And still have full functionality (backspace should remove the tag in front of the cursors current position, autocomplete etc.). In addition, the mouse should be able to click between tags to change the position of the cursor to that position.

This is written on a phone so if anything is unclear, feel free to ask.

**Comment by yairEO** [comment]
@FurbyonSteroid - Why would the order change when navigating? why don't you keep it the same order in your server-side (DB or whatever)?

I might be adding support for drag & drop so a user would be able to order the tags however they please, if order is important in the website/app (would be a setting that could be turned on/off) but I am still wondering about the UX implications

**Comment by FurbyonSteroid** [comment]
I don't know why it would change, you asked me if the order is important. Backend always returns the results in the same order. Drag and Drop is not really a priority for my use-case. Navigation with arrow keys + mouse click would be sufficient.

**Comment by oliver-schulz** [comment]
@Jiramew is there a chance that you will post your solution here? i need the same feature, to move the caret to insert a tag to a specific position. Always append to the end of the list does not work in my case, because the tags have an priority, first is most important and so on.

@yairEO do you have a hint where to start? Your plugin is pretty nice, well done!!

**Comment by Kilian** [comment]
Just to comment here as well: I would like this too.

My use case: I have a list of 10 tags and I would prefer users to be able to do everything with a keyboard, so also use their keyboard to move to the 1st tag and edit that one rather than having to use the mouse to click into that tag.

**Comment by yairEO** [comment]
@Kilian 

1. How do you know your users' preferences are identical to yours? (keyboard > mouse)
2. Why does the order of the tags important in your case?

**Comment by Kilian** [comment]
@yairEO 

1. I want to use tagify to replace a space-separated list of items currently in a textarea, and would prefer people not lose functionality. They would add ten items just by typing so if they then need to go back and edit the first item, I would prefer them to be able to do that without leaving the keyboard.
2. The order is not important for me, just the cursor (caret) position.


For anyone encountering this issue, you can sort of get there with this in your settings, which lets people tab to a tag and enter to edit it (but there is no way to delete tags)

```js
a11y: {
      focusableTags: true,
    },
```
