### ISSUE TITLE
input event doesn't fire with empty value

### ISSUE THREAD

**Issue by davidgolden** [yairEO/tagify#270]
I am using Tagify in 'mix' mode and migrating a project to a new codebase. The on input callback wasn't firing when the value is an empty string, which was firing before. I downgraded from `@latest` to `2.6.2` and it is working now. I'm not sure if expected behavior has changed since this version or if this is unintentional, but it seems like this would be a breaking change if not.

**Comment by yairEO** [comment]
I will check this asap, I have been on a vacation until recently, sorry for the delay

**Comment by yairEO** [comment]
I'm not sure what you mean by:

> The on input callback wasn't firing when the value is an empty string

What are the steps to reproduce?

**Comment by davidgolden** [comment]
It's been a while since I've looked at this, I'll try to find some time in the next few days to come up with a minimal reproducible example.

**Comment by yairEO** [comment]
I don't see any such bug on the latest version. 
The `input` event works as expected. You can even see it working in the [live demo page](https://yaireo.github.io/tagify/)

Both normal mode & mix mode fires the `input` event **after** removing the last tag / last character, thus emitting an event where the value is empty

**Comment by yairEO** [comment]
Just released version `3.0.0` so this should work. Try updating Tagify and let me know if this still happens.

**Comment by wjoeyu** [comment]
@davidgolden was this issue solved for you? I am experiencing the same issue.
