### ISSUE TITLE
wish the license was more permissive like MIT

### ISSUE THREAD

**Issue by joeaudette** [yairEO/tagify#272]
nice project, I would like to use it in my work but I cannot use anything with a GNU copyleft viral license.

I wish you would release it under a more liberal license like MIT or Apache2

**Comment by yairEO** [comment]
sorry about that, but I prefer to keep it as is

**Comment by joeaudette** [comment]
Fair enough, but I think that will hinder adoption by those who understand the implications of the license. Those who don't will likely violate the license out of ignorance.
https://stackoverflow.com/questions/1239470/restrictions-of-gpl-on-javascript-libraries

In any case I've found this which does what I need well enough and is MIT license:
https://select2.org/

**Comment by yairEO** [comment]
White select2 seems nice, it is **extremely** bloated library, old, and with many open issues, and not easy to customize at all.

https://bundlephobia.com/result?p=select2@4.0.7
https://bundlephobia.com/result?p=@yaireo/tagify@2.23.0
