### ISSUE TITLE
Some missing actions on keydown

### ISSUE THREAD

**Issue by aicsoft115** [yairEO/tagify#273]
Thanks for creating wonderful component, first.

In mix mode, I found some missing actions and crash issues on keydown event.

First, I wrote some tags and text, delete last text one by one with backspace key.
Once all last characters(just after last tag) are deleted, I can't continuously delete last tag with backspace key. Even I can't give the focus(caret) after the last tag and can't type any characters.
I checked your demo and it has the same issue.

Second, If I select all text and tags with keys or mouse and delete them, I enter the some text and make it as a tag by dropdown, it is crashed.

Will you provide some help?

Thanks

**Comment by yairEO** [comment]
I will check this out
