### ISSUE TITLE
Getting TypeError when trying to use whitelist

### ISSUE THREAD

**Issue by st1pps** [yairEO/tagify#276]
Hi,

I'm trying to get the Ajax whitelist example to work. 
This is the code I use:
```
var input = document.querySelector('[data-role=tagsinput]');
var controller;
var tagify = new Tagify(input, {
    whitelist: [],
    autocomplete: false
}, controller);

function onInput(e) {
    if (e.detail.value.length >= 2) {
        var value = e.detail;
        tagify.settings.whitelist.length = 0;

        controller && controller.abort();
        controller = new AbortController();

        fetch("/api/tag/suggest/" + e.detail.value, { signal: controller.signal })
            .then(RES => RES.json())
            .then(function(whitelist) {
                console.log(whitelist);
                tagify.settings.whitelist = whitelist;
                tagify.dropdown.show.call(tagify, value);
            });
    }
}
```
The whitelist variable that I print seems to be a proper array. My API returns this for example: ["Biologie","Lokal","Mindestlohn"]
It does not show the drowdown and the console shows this error:

```
tagify.js:1356 Uncaught (in promise) TypeError: value.toLowerCase is not a function
    at Tagify.filterListItems (tagify.js:1356)
    at Tagify.show (tagify.js:1143)
    at taglist.js:36
```

I'm a bit lost here, any idea what could be going wrong here?

**Comment by jaschaio** [comment]
@st1pps how did you resolve this? Getting the same error

**Comment by topikon-de** [comment]
@jaschaio In my case it was because my api was returning an array of objects containing the whitelist strings, not just an array of strings. I realised it a day later and closed the issue, hoping that no one would notice ;) the tagify code I'm still using today is exactly the same as shown above.

**Comment by st1pps** [comment]
@jaschaio In my case it was because my api was returning an array of objects containing the whitelist strings, not just an array of strings. I realised it a day later and closed the issue, hoping that no one would notice ;) the tagify code I'm still using today is exactly the same as shown above.

**Comment by jaschaio** [comment]
@st1pps thanks for clarification.

I found my mistake as well: One of the tags returned by the API was an empty string, which evaluated to false so `( t.value || t ).toLowerCase()` throwed an error. Filtering the whitelist, removing empty strings works.
