### ISSUE TITLE
Use double curly braces instead of double brackets in mixed content mode?

### ISSUE THREAD

**Issue by mrpsiho** [yairEO/tagify#279]
Hi,

Thanks for the great library!
Is it possible to use  double curly braces instead of double brackets in mixed content mode? I would like to use `{{` instead of `[[`.

**Comment by yairEO** [comment]
Well, the `[[` is hard coded in several places, such as this line that parses the text:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L848

so currently it's impossible. why can't you use `[[` ?

**Comment by mrpsiho** [comment]
Well, basically because in our project we use this content in twig and its format for variables is by using double curly braces. So, as soon we change it to the same format on front end we do not have to do anything extra but just use the value in backend. So, it is all about consistency.

**Comment by yairEO** [comment]
If your company wants this functionality asap, you can ask them to pay me some contribution, and I will clear some time and do it this week.

**Comment by mrpsiho** [comment]
I am totally understand you. I have the same situation. This project is of my mates and mine side project. There is no company behind this, only few nerds))

**Comment by yairEO** [comment]
Done. see `mixTagsInterpolator` [setting](https://github.com/yairEO/tagify#settings)
