### ISSUE TITLE
Using keyboard to select whitelisted item in Firefox fails

### ISSUE THREAD

**Issue by ghost** [yairEO/tagify#28]
Firefox 55.0.0.2 on Ubuntu

Using the most recent commit from the GitHub repo and the demo index.html.

1. Type, "A#" to display two whitelisted suggestions
2. Use the down arrow on the keyboard to select one of the suggestions
3. Rather than the selected suggestion being added to the field, the typed letters ("A#") are added

The behaviour is as expected in Chromium 60 on Ubuntu. The behaviour is expected in both browsers if the mouse is used instead of the keyboard to select one of the suggestions.

I will look at this myself now but any suggestions welcome.

**Comment by debug-discord** [comment]
Looks like this issue is due to a difference in how browsers handle events from the `datalist` element.

https://github.com/whatwg/html/issues/2605.

**Comment by yairEO** [comment]
yeah... this sure sucks. I did not want to implement my own dropdown suggestion box, because that would really inflate the code. It would require a positioning system and events.. 

I will contemplate about if it's worth bloating the code for the sake of better suggestions support.

**Comment by yairEO** [comment]
re-made the whole suggestions dropdown, take a look in the demo page
