### ISSUE TITLE
IE11 error "Invalid descriptor for property 'value'"

### ISSUE THREAD

**Issue by KeenthemesHub** [yairEO/tagify#284]
Hi,

Appreciate any workaround on this  IE11 error **"Invalid descriptor for property 'value'"**:

```javascript
var tagify = new Tagify(element, {
      delimiters: ", ", 
      maxTags: 10,
      keepInvalidTags: true, 
      whitelist: [ {
            value: 'Sam Seanic',
            email: 'sam.senic@loop.com'
      }, {
            value: 'Lina Nilson',
            email: 'lina.nilson@loop.com'
      }]
});
```

Any polyfill that needs to be added ?

Thanks.

**Comment by yairEO** [comment]
It seems like a Babel thing, I am trying to update versions and will check how it behaves. 
will report.

**Comment by yairEO** [comment]
Ok it was a Babel issue, I will push a fix tomorrow.
