### ISSUE TITLE
Empty tag (via editing) *is* invalid, but remains, even with `keepInvalidTags: false`

### ISSUE THREAD

**Issue by ar-rm** [yairEO/tagify#288]
Tagify is really great and impressive.

But I found (what seems to be) a really simple case/bug related to empty tags.

And since it *seems* to be "really simple", it probably isn't, and I wouldn't be surprised if I'm doing something wrong. You'll let me know.

### tl;dr:
- The use-case* of someone editing a tag down to nothing should then *remove* the tag (since it's empty). But Tagify doesn't.
- *Someone might think that *one* of the ways to remove a tag (once in editing mode) would be to just delete all of the text. But they'd be wrong.

### Overview:
- Edit a tag (via double click) down to nothing.
- The tag remains in an empty state, uneditable, and with its `value` set to what it was before the edit began.
- Even with `keepInvalidTags: false` set.

### Steps:
- Set `keepInvalidTags: false`
- Enter a tag (ex: "123456")
- Edit the tag (double click on it) by removing *all* of the characters

### Results:
- The tag is now invalid (class added: `.tagify--invalid`) but it's **not** removed.
- `contenteditable="false"` is set, so you can't add text again. Only clicking the "x" or delete key (when the cursor is to the right of it) will remove it.
- Because it's not removed, its `<tag value="123456">` (and `detail.data.tag.value`) remains and is **included** in the results when `tagify.value` is called.

### Other Info:

- I've tried the `pattern` option *and* `keepInvalidTags: false` together and it works well for rejecting *non* pattern matches. In that it nicely "cleans ups" the invalid tags.
- But it still doesn't remove this now-empty/invalid tag.
- I've even tried getting `pattern` to reject an empty tags, but I can't.
    - ex: `pattern: /^[A-z0-9\s]+$/` (Not 100% sure this regex would do it though).
- I've tried blacklisting `""` (empty string), but that doesn't help either.
- I was going to try disabling editing of tags (as a temporary workaround). But there doesn't seem to be a single option for that. I'd have to modify the `template`, but I didn't want to go that far yet.
- I even tried something like this, but it didn't work either:
```
    tagify.on('edit', function(e){
        console.log(e)
        if( e.detail.tag.isValid == 'empty' ){
            tagify.removeTag.call(tagify, e.detail.data.tag, false, false);
            // tagify.addTags(e.detail.data.value + '!!!');
        }
    });
```
Via: https://github.com/yairEO/tagify/pull/92#issuecomment-413663239

Unless I'm missing something, the bug is that Tagify **is** properly invalidating the empty tag, but it's just **not** "cleaning up" after it invalidates.

Or put another way: Once it "invalidates" it **because** its empty, most (all?) of the other logic, that operates on tags, ends.

Here's a simple example:
https://jsbin.com/wuhiwonewe/1/edit?js,output

(It's just the base setup, with `keepInvalidTags: false` set.)

Thanks.

**Comment by yairEO** [comment]
`keepInvalidTags` is set to `false` by default, and it's meant to be used in in very specific cases where you would want to give the users the chance to edit an invalid tag and correct it, instead of deleting it and have them type it again, which might be annoying if you have the `enforceWhitelist` set to `true` so if a user typed something with a typo, for example, it would seem reasonable to keep the tag but mark it as invalid.

Edited tag (which are currently being in the process of "edit") is a special case, and I've designed Tagify to mark as "invalid" to let the user know that they may not edit a tag and leave it empty, which is an unacceptable state. A user aught to fill the tag with some text or remove it by clicking the (x) button.

Now, thanks to you pointing out this issue, I have noticed a CSS bug that if a user edits a tag, remove all its text, and click outside (anywhere), then it becomes impossible to focus back on the tag and type. I'll remedy this by giving `min-width:10px` to the `<span>` element hosting the text.

**Comment by yairEO** [comment]
Did your other issue reference this issue here? Can I close this?

**Comment by ar-rm** [comment]
> `keepInvalidTags` is set to `false` by default, and it's meant to be used in in very specific cases where you would want to give the users the chance to edit an invalid tag and correct it, instead of deleting it and have them type it again, which might be annoying if you have the `enforceWhitelist` set to `true` so if a user typed something with a typo, for example, it would seem reasonable to keep the tag but mark it as invalid.

I must have had something backwards in my head.

I thought I was *setting* `keepInvalidTags: false` and the **default** was `true`. (*wrong*!)

In my use-case, `false` is what I want.

And I totally understand the purpose of `true`. That's a good idea.

**Feature Request (?):** Instructional text that explains *why* it's invalid. (Or maybe that's something that could be constructed with callbacks?)

> Edited tag (which are currently being in the process of "edit") is a special case, and I've designed Tagify to mark as "invalid" to let the user know that they may not edit a tag and leave it empty, which is an unacceptable state. A user aught to fill the tag with some text or remove it by clicking the (x) button.

Sure.

#### Counter thought:

If the user enters this "editing" state[1], and wants to remove the tag, they may think *one* way to do that would be to just delete all the text via the delete key. And when it's "empty" it goes away.

In the same way that, in *non-tag-editing* mode, they can press the delete key and each tag is treated as a character. Or like most other cases, where deleting text to nothing is the equivalent of wanting to remove the thing entirely.

([1] I'd think this could frequently be by accident, since there's no explicit UI to indicate double-clicking = *Edit* mode)

#### That UX consideration *aside*:

- Is there a situation where having an empty tag, just sitting there, would be the desired behavior? (Especially on submission.)

- And if *so*, shouldn't the `value=` be set to `null` or similar? Instead of the value remaining in its pre-edited state?

- And if I'm totally wrong on all of the above (completely possible! ;-) then how would *I* go about handling this with callback or something like that?

IOW (pseudo-code):
```
IF tag.content == ""
    Then set tag.value to ""

```

I first thought I could write that logic into whatever non-Tagify code handles the `submit` button. ex: Loop through `tagify.value` and remove the one that's supposed to be empty.

But then I realized:
- I'm not sure how to figure out *what* is empty. Since its "emptiness" is only seen (as far as I know) in the empty `<span class="tagify__tag-text"></span>`.

- But even that fails, because I don't know how to correlate that *specific* empty `<span>` instance with the corresponding `tagify.value` key. (But this is likely my ignorance of how to reach into Tagifys prototype.)

- And even if I could, this seems like something that should be baked into Tagify. (And now we're back to my thoughts above :-)


> Now, thanks to you pointing out this issue, I have noticed a CSS bug where a tag is edited & all texts is removed. Then, if clicking outside (anywhere), it becomes impossible to focus back on the tag and type text. 

Exactly.
That too.

> I'll remedy this by giving `min-width:10px` to the `<span>` element hosting the text.

Cool little fix.
I might make it a bit more than `10px`. But that's just me ;-)

May I suggest adding: `cursor: text` as well?

I might even go further, and suggest: Add `cursor: text` as the default and making a single-click = enter edit mode. Either as the default or an option. (Although I can imagine a conflict with the single-click of the "remove" button.)

BUT I haven't thought that through and it might be a terrible idea for 28 other reasons.

Thank so much for the quick response, time, and consideration!!

**Comment by yairEO** [comment]
> **Feature Request (?):** Instructional text that explains why it's invalid. (Or maybe that's something that could be constructed with callbacks?)

Well, my thinking is that it's pretty obvious an empty value is invalid :)

---

> If the user enters this "editing" state[1], and wants to remove the tag, they may think one way to do that would be to just delete all the text via the delete key. And when it's "empty" it goes away.

 > In the same way that, in non-tag-editing mode, they can press the delete key and each tag is treated as a character. Or like most other cases, where deleting text to nothing is the equivalent of wanting to remove the thing entirely.

In my view it is a different scenario than hitting the <kbd>backspace</kbd> button, because in this scenario, the whole component is viewed as a "whole", one continuous flow of tags, where one can add or remove using keyboard only.

BUT, when editing a tag, the scope of the what you are allowed to change narrows down to that tag only, and is encapsulated within that tag, so a user can only add or remove text within that (editable) tag only. I view editing is an action that is somewhat rare in the sense that most users won't edit a tag, and if they do, they have a range of reasons in doing so, for example: typo, change of words, or completely change the tag (which is odd reason since they can just delete the tag and add another one). 

I could not think of a reason why a user would enter "edit" mode and trouble all the way in removing all the text just to empty the tag, and not just delete it entirely. 

Another reason is do not want to remove the tag completely on editing and removing all text and then hit an extra <kbd>backspace</kbd> is that in edit-mode, it is **much** more probable for a use to use the <kbd>backspace</kbd> key than in any other scenario, since they wish to change something, and therefor, knowing users make mistakes, I do not want it to be so sensitive that if a user hit the backspace accidently too many times, the tag will be deleted and user will not be able to edit it anymore since it will be "gone", and the user will be left disappointed (or so I believe)

----

> Is there a situation where having an empty tag, just sitting there, would be the desired behavior? (Especially on submission.)

I cannot see why such a situation will be desired by the user, as I've said, I do not believe a user will actively take the time to edit a tag just to remove all the text, because why bother and not just delete it in single click?

Tagify does not set the tag text until "edit-mode" (for a tag) has been exited, by `blur` event or <kbd>Enter</kbd> key was pressed, because I always give the option for the user to hit the <kbd>Esc</kbd> key and revert his edit (while in edit-mode).

I do not think of a reason one would want to send an empty tag to the server. 

Why, in your opinion, would a user want to send an empty tag to the server?

---

> I'd think this could frequently be by accident, since there's no explicit UI to indicate double-clicking = Edit mode)

I leave it up to developers if they wish to add some text explaining tags can be edited by double-clicking, and leave it outside of Tagify's scope to explain that.
For example, a developer can create a Tag template where the title says "click to edit", so when hovering a tag it shows it. This is ofcourse not good for touch-screens, so any hover-based information will not be seen.

In many websites, editing tags is not a common practice, and I've actually added that feature long after Tagify was stable, because I believe editing is a powerful feature, lacked in many of today's Tags component. 

The main reason I've developed Tagify is that all the other Tags Components disappointed me, in code quality, functionality or customization range. My vision was to make Tagify perfect in every way possible. It is an ever-evolving component, and I have new exciting features I want to add, but also I **must** consider one of my main goals, which is to keep the code slim and bloat-free, so it's a battle between adding features and keeping the codebase small.

---

> I might even go further, and suggest: Add cursor: text as the default and making a single-click = enter edit mode. 

There is an even firing for single-clicking a tag. Some developers want actions to be called when clicking a tag. A tag can also be a link to other pages or popups..or anything for that matter, so I've made editing be double-click, to not interfere with any custom single-click functionality. Theoretically I can add a setting to choose if edit-mode will be triggered with one click or double, but I think it might be a bit tricky to achieve. 

Regarding `cursor: text` - great idea, I will do that. I think on windows it is the default.

**Comment by ar-rm** [comment]
First:

Thank you so much for this detailed, thoughtful, and *quick* (turnaround time) reply!


> > **Feature Request (?):** Instructional text that explains why it's invalid. (Or maybe that's something that could be constructed with callbacks?)
> 
> Well, my thinking is that it's pretty obvious an empty value is invalid :)

Sure.

I should have been clearer:

I was thinking more *generally*.

As in: Have a *tooltip-style* area that appears, with customizable error text.

ex:
- Pattern Matched = "Tags must not contain one or more special characters"
- White/Black List = "The tag you entered is not allowed"

I realize all of this could be listed outside of Tagify in some way. But that wouldn't be dynamic or specific to what was *just* entered.

Also since you've already started down the path of handling validation in the UI, I thought this would be nice a corresponding feature.

Choices.js has a version of this:
https://joshuajohnson.co.uk/Choices/
https://github.com/jshjohnson/Choices

> BUT, when editing a tag, the scope of the what you are allowed to change narrows down to that tag only, and is encapsulated within that tag, so a user can only add or remove text within that (editable) tag only.

Agreed.

> I view editing is an action that is somewhat rare in the sense that most users won't edit a tag, and if they do, they have a range of reasons in doing so, for example: typo, change of words, or completely change the tag (which is odd reason since they can just delete the tag and add another one).

Agreed.
That's what I was getting at too :-)

> I could not think of a reason why a user would enter "edit" mode and trouble all the way in removing all the text just to empty the tag, and not just delete it entirely.

Again, I should have been clearer:

I *don't* think the user will enter "edit" mode **for** that purpose. I was imagining a scenario where they do it for *any* reason.

Maybe they're in edit mode because they realize the name of the tag is not quite right. They change it to something else completely and realize that's not right either. Then they just want to delete it, and they do by erasing all of the text via <kbd>backspace</kbd> followed by <kbd>tab</kbd> or <kbd>esc</kbd>.

Ultimately, I think you're right that these are edge cases.

BUT my main point is: **Since** it's *possible* to delete all of the text while in edit mode, shouldn't there be a mechanism to **automatically** clean those up those now-empty tags?

Maybe call it a "fall-through" or "fail-safe" state. Where if they get themselves into this "mess" ;-) Tagify will, **at most**, "clean it up" for them (remove something "red" that has no purpose to anyone) and, **at least**, "clean it up" for the developer, by not sending the wrong data.

(More on that in a second.)

> Another reason is do not want to remove the tag completely on editing and removing all text and then hit an extra backspace is that in edit-mode, it is **much** more probable for a use to use the backspace key than in any other scenario, since they wish to change something, and therefor, knowing users make mistakes, I do not want it to be so sensitive that if a user hit the backspace accidentally too many times, the tag will be deleted and user will not be able to edit it anymore since it will be "gone", and the user will be left disappointed (or so I believe)

I can understand that.

But if they `blur` *out* of the now empty tag, that's a pretty strong indication that they are "done" with that tag. Or at least (if Tagify removes it), there won't be any loss of data, since there's no data (as far as they're concerned).

This goes double if they continue to edit other tags or leave Tagify's scope completely.

> > Is there a situation where having an empty tag, just sitting there, would be the desired behavior? (Especially on submission.)
> 
> I cannot see why such a situation will be desired by the user,

Agreed!

> Tagify does not set the tag text until "edit-mode" (for a tag) has been exited, by `blur` event or Enter key was pressed, because I always give the option for the user to hit the Esc key and revert his edit (while in edit-mode).

That's good.

The problem (in this case) is, once the tag has *no* text, the `value=` (from its pre-*no-text* state) remains. Which is almost certainly a problem for the developer.

Which leads us back to:

> I do not think of a reason one would want to send an empty tag to the server.
> 
> Why, in your opinion, would a user want to send an empty tag to the server?

Ha!
I think something is backwards again :-)

That's **exactly *my* point**.

I **don't** think there's any situation where that would be desired. Which is why I think **automatically cleaning up** that empty tag is a **good** idea.

That's what I was referring to here:

> - And if so, shouldn't the value= be set to null or similar? Instead of the value remaining in its pre-edited state?

> - And if I'm totally wrong on all of the above (completely possible! ;-) then how would I go about handling this with callback or something like that?

> > I'd think this could frequently be by accident, since there's no explicit UI to indicate double-clicking = Edit mode)
> 
> I leave it up to developers if they wish to add some text explaining tags can be edited by double-clicking, and leave it outside of Tagify's scope to explain that.

Understood.

> For example, a developer can create a Tag template where the title says "click to edit", so when hovering a tag it shows it. This is ofcourse not good for touch-screens, so any hover-based information will not be seen.

Good point.

> In many websites, editing tags is not a common practice, and I've actually added that feature long after Tagify was stable, because I believe editing is a powerful feature, lacked in many of today's Tags component.

Agreed.

> The main reason I've developed Tagify is that all the other Tags Components disappointed me, in code quality, functionality or customization range. My vision was to make Tagify perfect in every way possible.

I agree!!
And it shows.

I evaluated a bunch of other libraries. Tagify was my first choice.

Funny enough, it was so powerful and full featured, that I choose *not* to use it. Only because sometimes choosing that type of library can get *me* into trouble. Funny enough, it was the fallback library that got me into trouble (because it lacked some of the customization, among other things), which made me cut-bait and try Tagify.

> It is an ever-evolving component, and I have new exciting features I want to add, but also I **must** consider one of my main goals, which is to keep the code slim and bloat-free, so it's a battle between adding features and keeping the codebase small.

Of course!
I can tell that from everything you've written (the actual code and these/other issue replies).

> > I might even go further, and suggest: Add cursor: text as the default and making a single-click = enter edit mode.
> 
> There is an even firing for single-clicking a tag. Some developers want actions to be called when clicking a tag.

Oh! I didn't realize that.

> A tag can also be a link to other pages or popups..or anything for that matter, so I've made editing be double-click, to not interfere with any custom single-click functionality.

Exactly.
Good thought.
That's why I mentioned it could be a bad idea :-)

> Theoretically I can add a setting to choose if edit-mode will be triggered with one click or double, but I think it might be a bit tricky to achieve.

Yeah.

Out of curiosity: Is there a Tagify method to have a tag *enter* `Edit Mode` ?

(Again, just curiosity. I don't have a use case.)

> Regarding `cursor: text` - great idea, I will do that. I think on windows it is the default. opened #290

Cool!

Thanks again for your time, thoughts, and work.

**Comment by yairEO** [comment]
> But if they blur out of the now empty tag, that's a pretty strong indication that they are "done" with that tag. Or at least (if Tagify removes it), there won't be any loss of data, since there's no data (as far as they're concerned).

> I don't think there's any situation where that would be desired. Which is why I think automatically cleaning up that empty tag is a good idea.

I have given thought to it, and I agree it makes more sense if a user removed all text in a tag, in edit-mode, and then trigger a `blur` event, then Tagify should simply delete that tag and not leave it in this weird state. I will make it so.

---

> I realize all of this could be listed outside of Tagify in some way. But that wouldn't be dynamic or specific to what was just entered.

> Also since you've already started down the path of handling validation in the UI, I thought this would be nice a corresponding feature.

Technically you can use the `invalid` event which exposes the reason for the invalidation:

    tagify.on('invalid', e => console.log(e.detail))

Then a developer chose what to do with that text (render in a Toast message, or somewhere next to the Tagify component maybe. some creativity is needed)

----

> Funny enough, it was so powerful and full featured, that I choose not to use it. Only because sometimes choosing that type of library can get me into trouble. Funny enough, it was the fallback library that got me into trouble (because it lacked some of the customization, among other things), which made me cut-bait and try Tagify.

I read this sentence a few times and it I was very surprised.
The last thing I want is to scare off people who are considering using Tagify, simply by overwhelming them with settings and examples. 

If you thought it was looking a bit too complex and you only wanted something simple, then I bet others also thought the same. 
I must find a way to better explain things. 

When I have to choose other components online, for my personal use, I also don't like the ones which looks bloated or full of open issues. I am not sure how to solve this in a way that I can still show how powerful Tagify can be and yet not to scare anyone off.

---

> Out of curiosity: Is there a Tagify method to have a tag enter Edit Mode?
   
    const tagify = new Tagify(...)
    const someTagElement = tagify.getTagElms()[2]  // get third tag DOM node
    tagify.editTag( tagElement )

or you could also use the method to a find specific tag: `tagify.getTagElmByValue('foo')`

**Comment by ar-rm** [comment]
> > I don't think there's any situation where that would be desired. Which is why I think automatically cleaning up that empty tag is a good idea.
> 
> I have given thought to it, and I agree it makes more sense if a user removed all text in a tag, in edit-mode, and then trigger a `blur` event, then Tagify should simply delete that tag and not leave it in this weird state. I will make it so.

Great!
Thank you!!

> Technically you can use the `invalid` event which exposes the reason for the invalidation:
> 
> ```
> tagify.on('invalid', e => console.log(e.detail))
> ```
> 
> Then a developer chose what to do with that text (render in a Toast message, or somewhere next to the Tagify component maybe. some creativity is needed)

Duh!
Thanks for that.

> If you thought it was looking a bit too complex and you only wanted something simple, then I bet others also thought the same.
> I must find a way to better explain things.
> 

I'll reply to this directly.

> > Out of curiosity: Is there a Tagify method to have a tag enter Edit Mode?
> 
> ```
> const tagify = new Tagify(...)
> const someTagElement = tagify.getTagElms()[2]  // get third tag DOM node
> tagify.editTag( tagElement )
> ```
> 
> or you could also use the method to a find specific tag: `tagify.getTagElmByValue('foo')`

Cool. Thanks.
