### ISSUE TITLE
Safari (11.1.2): Can't edit tags (includes proposed fix)

### ISSUE THREAD

**Issue by ar-rm** [yairEO/tagify#289]
### Overview:
- Editing a tag is broken in Safari Version 11.1.2 (11605.3.8.1)

### Steps:
- Double click on a tag.

### Results:
- Tagify *does* go into "editing" mode.
- But you *can't* change the text.

### Other Info:
- This is the most recent version of Safari that with macOS 10.11.6 El Capitan. (I realize this is a somewhat old version.)
- I don't know if this bug exists in newer versions. I suspect it does (see the SO answer below).

### Proposed Fix:

```
.tagify__tag-text[contenteditable="true"] {
    -webkit-user-select: text
    user-select: text
}
```

Via: https://stackoverflow.com/a/31831776/886672

A few things:

- It needs the `-webkit` prefixed version.
- I locked it down the specificity because I'm not super farmiliar with the structure of the css.
- However I did see that `.tagify__tag-text` is **not** it `tagify.css` at all.
- Those two things combined are why I didn't want to submit a pull request. IOW: I didn't want to mess up your code too badly :-)

Thanks!

**Comment by yairEO** [comment]
Awesome :) Such a weird bug in Safari. I do not have a Mac so I cannot test on it though.

No need for the `-webkit` prefix (or any prefix) because GULP does that for you, by using the [`autoprefixer`](https://www.npmjs.com/package/gulp-autoprefixer) plugin, so it got our backs here.

**Comment by ar-rm** [comment]
> Awesome :) Such a weird bug in Safari. I do not have a Mac so I cannot test on it though.

Fix = Confirmed

Also this (just for future reference):
https://stackoverflow.com/a/20930385/886672

> No need for the `-webkit` prefix (or any prefix) because GULP does that for you, by using the [`autoprefixer`](https://www.npmjs.com/package/gulp-autoprefixer) plugin, so it got our backs here.

Ahh. I didn't realize that was run on everything. Also just wanted to be explicit because I first tested it un-prefixed and it didn't work.

Thanks!!
