### ISSUE TITLE
Always show dropdown and tab-press breaks expected behavior

### ISSUE THREAD

**Issue by muddymess** [yairEO/tagify#293]
When dropdown is set to always show (enabled: 0), when tabbing through fields in a form the dropdown will open on focus (correct behavior) but when the user keeps tabbing the first tag is selected and added. Meanwhile if you're actively selecting from dropdown, tab might be useful as a key to choose with.

The expected behavior I think should be to simply blur and focus next input.

**Comment by muddymess** [comment]
My local fix is to on tab-press check if active selection has been made:

```
case 'Tab':
   if (!activeListElm) {
      this.dropdown.hide.call(this);
      break;
   }
case 'ArrowRight':
   e.preventDefault();
   if (!this.input.autocomplete.set.call(this, selectedElm ? selectedElm.textContent : null)) return false;
```
[Here](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1280)

**Comment by yairEO** [comment]
fixed
