### ISSUE TITLE
Inconsistency when selecting via Keyboard or Mouse

### ISSUE THREAD

**Issue by tkoenig** [yairEO/tagify#299]
There is an inconsistency which might also be related to the setting `dropdown.enabled: 0`.

When clicking a tag from the dropdown with the mouse, the dropdown immediately shows up again (see https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1357) whereas when selecting a tag from the dropdown via keyboard does not show the dropdown after selecting a tag.

I think the best might be to solve this via an option like `refocusAfterAdd` where you could decide wether the input field is focused or blurred after a tag has been added.

![tagify-reopen-dropdown](https://user-images.githubusercontent.com/63860/64771271-f7055d00-d54e-11e9-8e35-458159b8ffc0.gif)

**Comment by yairEO** [comment]
I can add a new setting named `dropdown.closeOnSelect`

I will give it some thought

**Comment by yairEO** [comment]
Ok, I've implemented it and will deploy tomorrow I hope. It was a complex feature because of how all the events work when the dropdown is open, but anyway, it works really nice. Found some other bugs along the way and fixed them as well :)

**Comment by tkoenig** [comment]
Hi @yairEO, I would love to test this.
Please let me know once this has been released.
Thanks alot!
