### ISSUE TITLE
force to select from some specific items

### ISSUE THREAD

**Issue by sajadabasi** [yairEO/tagify#3]
Hi,
it looks greats but it dont support force to select from some specific items.
it exists and i can not see that or could you add it?
thank you

**Comment by yairEO** [comment]
I will add this support, hopefully in a few days

**Comment by yairEO** [comment]
related to #2

**Comment by yairEO** [comment]
done! check the demo:

https://yaireo.github.io/tagify/

**Comment by yairEO** [comment]
Forgot to add something, will try to fix today

**Comment by sajadabasi** [comment]
thanks sounds great ...

**Comment by yairEO** [comment]
done
