### ISSUE TITLE
Ability to select a single value (or create a new tag and select it)

### ISSUE THREAD

**Issue by cowwoc** [yairEO/tagify#301]
Looking at https://v1.react-select.com I'm looking for a feature equivalent to "custom tag creation" with "single value" mode. Meaning, I expect users to select a single value from a down-drop list, or enter a new value that will get added to the drop-down list.

I plan to use AJAX to populate the list of suggestions but if the user enters a new value I will save it to the server as well as using it locally.

**Comment by yairEO** [comment]
You want to allow adding only 1 tag and not more, and it can be any tag?
Tagify does this already, it's on the [demo page](https://yaireo.github.io/tagify/)

**Comment by cowwoc** [comment]
@yairEO I don't see it. Which example should I be looking at?

**Comment by yairEO** [comment]
There are [settings](https://github.com/yairEO/tagify#settings) which can be passing when initializing Tagify, the demo shows many in ["ADVANCE OPTIONS" example](https://yaireo.github.io/tagify/#section-advance-options), and the one you need is `maxTags:1`

**Comment by cowwoc** [comment]
@yairEO I think you misunderstood my request. Here is what tagify looks like with `maxTags=1`: https://jsfiddle.net/cowwoc/e14hmzg2/5/

Now, compare this to "Single Item Select" at http://selectize.github.io/selectize.js/ or `Custom tag creation` found at the bottom of https://v1.react-select.com/ (make sure to enable `Single Value` mode!)

I am expecting the UI to look like a cross between an `<input>` and a `<select>`:
* When unfocused, the component looks like a `<select>`.
* When focused, the component allows the user to type custom tags and offers auto-complete options using the datalist.

I don't want Tagify to allow users to type in multiple options, and I expect the selected value to fill the entire width.

**Comment by yairEO** [comment]
OK, I understand your need. I will put it in the todo-backlog

Why don't you use `selectize`? it seems to have all your requirements

**Comment by cowwoc** [comment]
@yairEO Three problems:

1. `selectize` development has ceased.
2. The library requires jquery.
3. I read it doesn't work well on mobile platforms.

I tried coding this up from scratch a few weeks back but ran into blockers trying to use datalist. I guess I will give this another try until you're able to add support on your end.

Thank you.

**Comment by yairEO** [comment]
It shouldn't be that difficult for me to tweak Tagify to behave like a `<Select>`, I only need to allow to a "tag" (whatever is the current value) to be always editable without double-clicking on it. All the rest is easy.

I will try to patch it this week. I'll report once done.

**Comment by cowwoc** [comment]
That sounds great! Looking forward to it.

**Comment by yairEO** [comment]
Just asking, why is the title says "single value" but later in one of your comments you've written:

> When focused, the component allows the user to type custom **tags** and offers auto-complete options using the datalist.

Why did you write *tags* in plural?

**Comment by cowwoc** [comment]
I meant that users will add multiple tags over time, but only one tag will be added at a time.

Meaning, the input field should only hold one tag at a time.

Feel free to ask me any other questions you might have.

**Comment by yairEO** [comment]
Just released version `2.29.0` with a new "select-mode" option. [see demo here](https://yaireo.github.io/tagify/#section-mode-select)

**Comment by cowwoc** [comment]
@yairEO Looks good. How would I listen for users entering a value that was not on the list, so I can create a new/custom tag? Alternatively (not for me, but other people might want this) how do you configure the pulldown to only accept values from the list?

**Comment by yairEO** [comment]
If you want to only allow items from the dropdown list, then you can use the `enforceWhitelist` setting.

Regarding knowing if the added tag is custom or not, simply check if it was in your original whitelist. Probably it should be done on the server-side.
