### ISSUE TITLE
Place sugession tag by enter not by mouse click only

### ISSUE THREAD

**Issue by brain2xml** [yairEO/tagify#306]
Hi!
Great module! 
When i start to type tag (**_he_**), dropdown open with sugesstion tags (**_hello world_**) and I press arrows on keyboard and select sugession tag,  in that moment when I press enter button and **_he_** becoms new tag, not **_hello world_**. And I still want to add new tags. Haw made to enter  **_hello world_** as a tag if i selected it?
maybe I miss something in documentation?

**Comment by yairEO** [comment]
To fully input the suggested value, you can use the right arrow key <kbd>→</kdb> and it will fill the currently suggested value, and then you can click Enter.

I see there's a bug which prevents that, so I will fix it and will release a new version today.

**Comment by brain2xml** [comment]
Yes! you are good! now it's working! thank you wery much!
