### ISSUE TITLE
Can I limit the number of tags?

### ISSUE THREAD

**Issue by tanerkay** [yairEO/tagify#308]
I even have a use case that would only necessitate one tag per field.

**Comment by yairEO** [comment]
See [`maxTags` setting](https://github.com/yairEO/tagify#settings). It's also in the [demo page](https://yaireo.github.io/tagify/#section-advance-options).

If you need only 1 tag, then wait a day until I push a new version for #301

**Comment by tanerkay** [comment]
Sorry, I thought I scanned the list of settings at least twice!

Thanks for the quick reply, and #301 sounds perfect for what we are after!
