### ISSUE TITLE
ID => Value tags

### ISSUE THREAD

**Issue by DavidSprauel** [yairEO/tagify#31]
Hi,

Can the plugin support an array of key => value as tag ?
I mean something like that : `<tag data-id="1">...</tag>`

I use the plugin with an user system and filtering users with name is not that good.

Thanks :)

**Comment by yairEO** [comment]
I'm guessing you're using a whitelist of names for autosuggestion list.
currently what you wish for is not possible. 
you would need to map the names to ids separately
