### ISSUE TITLE
Removing an invalid tag removes the correct element child and the wrong data element

### ISSUE THREAD

**Issue by zoaked** [yairEO/tagify#310]
### JSBIN bug template
https://jsbin.com/silukaxafi/edit?html,output

### Explanation
When you have a whitelist and allow invalid tags to remain things will get out of sync if the invalid tag is removed later on. In the above example typing 'item' will correctly offer 'item3' as the only option when the page first loads.  Removing 'something' will not only remove the 'something' tag element from the dom, but will also splice 'item2' data from the value.  This can be seen by the action taken text as well as typing 'item' offering both 'item2' and 'item3' as options.

### Suggested Fix
Add the following block of code to [this line](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1087):
```
!tagElm.classList.contains('tagify--notAllowed')
```
so the full line would then read:
```
if(!silent && !tagElm.classList.contains('tagify--notAllowed')) {
    ...
}
```
I would be happy to make a PR for this if that would be easier for you and you agree that no other ill effects would result from making this change.

**Comment by yairEO** [comment]
Ho... I see what you mean. Good catch! I know what this happens.
Hopefully I will get to fix this on monday since I'm on vacation today and half tomorrow.
