### ISSUE TITLE
Manually close list

### ISSUE THREAD

**Issue by steve-alt-ctrl** [yairEO/tagify#311]
Hello,

I would like to use tagify to allow the selection of only 1 item and proceed to the next element, so I have maxTags set to 1. I am currently using tagify with the suggestion list to show on focus with the following... 

`dropdown : {  enabled : 0 }`

I am looking to manually close the suggestion list after a selection is made.  I have the following...

`add   : e => { document.getElementById("time").focus(); }`

Thinking that setting the focus on another element would close the list but to no avail.  Is there something I'm missing?

Edit: I tried to manually close it with the following code below, but the list still shows (thinking the list waits then shows).

`tagify.dropdown.hide.call(tagify);`

**Comment by yairEO** [comment]
Just released version `2.29.0` with a new `closeOnSelect` [setting](https://github.com/yairEO/tagify#settings)

**Comment by steve-alt-ctrl** [comment]
Awesome. This worked. Thanks!
