### ISSUE TITLE
Bugs in documentation of single-value select

### ISSUE THREAD

**Issue by cowwoc** [yairEO/tagify#312]
1. At https://yaireo.github.io/tagify/#section-mode-select, the JS code references `input[name=tags-select-mode]` but the HTML code contains `name='tags-readonly-mix'`. I am expecting the names to match.
2. The settings documentation at https://github.com/yairEO/tagify/blob/master/README.md#settings does not state that `mode` may be `select`.

**Comment by yairEO** [comment]
I will update it, thanks for catching those!

**Comment by yairEO** [comment]
fixed
