### ISSUE TITLE
Dropdown should close when input loses focus

### ISSUE THREAD

**Issue by cowwoc** [yairEO/tagify#313]
1. Open https://yaireo.github.io/tagify/#section-mode-select
2. Click on the input field. The dropdown menu will expand.
3. Press TAB. The `input` component will lose focus but the dropdown will remain open. I am expecting it to close when the `input` loses focus.

**Comment by cowwoc** [comment]
The reason this is important is if the page contains multiple dropdowns, then hitting TAB over and over again results in many dropdown menus remaining open. It then becomes hard to see what is going on.

**Comment by yairEO** [comment]
Yes I saw this also while preparing this feature and also started to write a test for this and for some reason this slipped by to the published version, untested.

I am currently on vacation abroad and have no way of publishing a new version until 6th of October, sorry about this

**Comment by cowwoc** [comment]
No worries. Shana Tova U'Metuka :)
