### ISSUE TITLE
Focus event listener

### ISSUE THREAD

**Issue by cowwoc** [yairEO/tagify#315]
Looking at https://yaireo.github.io/tagify/#section-mode-select, I want to populate the dropdown menu when an `input` element gains focus (as opposed to populating it up-front). As far as I can tell, if I start with an empty dropdown menu then none of the existing event listeners fire when the `input` gains focus.

I cannot add a `focus` listener on the real `input` element because tagify inserts a `span` with a `tagify__input` class that steals the `input` focus.

Consider adding `tagify.on("focus", eventListener)` or enabling us to add a focus listener on the underlying `input` somehow.

**Comment by 7iomka** [comment]
Any news?

**Comment by 7iomka** [comment]
I made sintetic manual focus on contenteditable area like this:
`$(tagifyInstance.DOM.input).trigger('focus');`

**Comment by yairEO** [comment]
Example:

```
tagify.DOM.input.addEventListener('focus', onSelectFocusBlur)
tagify.DOM.input.addEventListener('blur', onSelectFocusBlur)

function onSelectFocusBlur(e){
    console.log(e.type)
}
```
