### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keepInvalidTags' of undefined

### ISSUE THREAD

**Issue by chrismogz** [yairEO/tagify#318]
Every time I repeat the same tag then press enter or ','. The repeated tag is removed but following console error appears:

```
Uncaught TypeError: Cannot read property 'keepInvalidTags' of undefined
    at d (tagify.min.js:10)
```

**Comment by yairEO** [comment]
Thanks for letting me know. I'm currently on vacation so could only fix this in about a week

**Comment by farfromfearless** [comment]
Temporary fix until patched:
`} else if ( this.settings ? this.settings.keepInvalidTags : false ) that.trigger('remove', {`

**Comment by yairEO** [comment]
I will try to release a fix in ~10 hours

**Comment by yairEO** [comment]
I cannot seem to reproduce this on the [demo page](file:///C:/projects/tagify/index.html#section-advance-options)
