### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by tknayak75** [yairEO/tagify#32]
I am trying to use tagify in one of the pages to implement tags and auto-suggestions.
The problem I am facing in safari is that the suggestion dropdown comes with a plain html dropdown menu and also selecting a keyword from the list of suggestions does not create a tag. Not sure if this has been reported before, but I do not see it in the list of issues here.

**Comment by yairEO** [comment]
This is somehow related to #28. I will see what I would do about implementing my own dropdown box

**Comment by adaniello** [comment]
Need polyfill for datalist (for IE <=9, Safari, ...) http://caniuse.com/datalist/embed/. I'm trying some ways but no success with Safari.

**Comment by tknayak75** [comment]
I am not convinced that it needs polyfill. If I see the tagify code, it is not really using datalist. It is actually using "select". The display is ugly but the dropdown does show up in Safari.
But somehow upon selecting the "tags" do not work. So I feel it is somehow related to css.

**Comment by adaniello** [comment]
See at
https://github.com/yairEO/tagify/blob/1f17bf18604f7f41cea7dbb63237b756f12a5de7/src/tagify.js#L243
Then the plugin attachs a select to a datalist for some browsers support (see at https://github.com/thgreasi/datalist-polyfill).
The way is right.

**Comment by yairEO** [comment]
I think I might create another file which could be combined with `Tagify` and will extend it in a way which will create a custom dropdown list. I prefer not to have that code within `Tagify` because it's quite a lot of code and I don't believe it would be relevant to many.

**Comment by yairEO** [comment]
This is probably fixed on Tagify v2.0.0 
Try the demo page and see
