### ISSUE TITLE
react.tagify.js addTagOnBlur doesn't work when dropdown is open

### ISSUE THREAD

**Issue by aquaductape** [yairEO/tagify#323]
On the [**live demo**](https://codesandbox.io/s/tagify-react-wrapper-6vd3i) change `addTagOnBlur` to `true`. 

1. Type `aaa` to match whitelist so that dropdown opens
1. click outside of the input to tag `aaa`

The result is that input text doesn't get tagged. 

1. Type `cat`, that way dropdown will not open. 
2. Then click outside and `cat` will get tagged.

**Comment by yairEO** [comment]
There's no need to change `addTagOnBlur` to `true` because it's `true` by default
