### ISSUE TITLE
Mix Text & Tags Dropdown Limit

### ISSUE THREAD

**Issue by coding-tech-guy** [yairEO/tagify#324]
Hi,

Is it possible to have a mix text and tags textarea, and only have the dropdown show when entering a matched # or @ and 2/3 characters after?

Currently the dropdown shows on focus even though a matched tag start character isn't present (# | @). Worse still you cannot select anything from the dropdown anyway so the dropdown shouldn't be showing. This is the same even when the textarea is empty.

Can be seen from the demo here:
https://yaireo.github.io/tagify/#section-mix

Any advice is appreciated.

Thanks.

**Comment by coding-tech-guy** [comment]
Never mind, I've commented out the following which is now working as expected:

`if (this.settings.mode) this.settings.dropdown.enabled = 0;`

Can i ask why was this line put in the applySettings function?

Thanks.

**Comment by yairEO** [comment]
It's a bug, I will fix it now. Thanks for letting me know!

The code should apply only for "select" mode and not any other mode, such as "mixed"
