### ISSUE TITLE
Edit tags with single click

### ISSUE THREAD

**Issue by collimarco** [yairEO/tagify#325]
I really love the ability to edit existing tags. However it is not very intuitive that you should use a double click: most users would expect to simply click on a tag in order to edit it.

Is there any way to trigger the edit mode on a single click?

**Comment by yairEO** [comment]
Good point, I will add support for this in the upcoming days

**Comment by yairEO** [comment]
Added [`editTags`](https://github.com/yairEO/tagify#settings) setting which accepts the number of clicks needed to enter edit mode: `1` or `2`.

any other value will disable entering "edit" mode
