### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by collimarco** [yairEO/tagify#326]
I was going to use this (great) library in a SaaS, however I have noticed that the license in not very transparent.

The _AGPL_ license implies that if we use this library in a SaaS, we must make all the SaaS code publicly available (which is crazy). I am sure that this is not your intent (https://github.com/yairEO/tagify/issues/153#issuecomment-450974982), however that license makes it impossible to use this library **legally** in any SaaS.

**Comment by yairEO** [comment]
Ok then, I am contemplating on this and will let you know this week.
I might change the license to *freeware*

**Comment by collimarco** [comment]
@yairEO Thanks for the permissive license!  :) 
Just a suggestion: if you want to grant a very permissive license, but make sure that your attribution is kept in the source code, you can use the MIT license, which is widespread in open source.

**Comment by yairEO** [comment]
Thanks. I've changed it now to MIT because I admit that I do love credit.. what can I say, I've worked hard on this component for 2 years now and I am really proud of it.
