### ISSUE TITLE
Get the DOM of Tagify on input with 'mix' mode

### ISSUE THREAD

**Issue by hasyemiraws** [yairEO/tagify#327]
Hi, is there a way for me to get the Tagify DOM element when using 'mix' mode on input event listener? I noticed that it's only returning textContent.

**Comment by yairEO** [comment]
What do you mean *"Get the DOM of Tagify"*?
Can you be specific which DOM element do you want and why?

You have all the DOM elements accessible by:

```javascript
var tagify = new Tagify(...)
console.log( tagify.DOM )
```
