### ISSUE TITLE
Mix Mode deletion bug

### ISSUE THREAD

**Issue by VIRUS-ATTACK** [yairEO/tagify#329]
Bug observed in Mix Mode demo at [https://yaireo.github.io/tagify/#section-mix](url).

## Steps to reproduce
- First add a tag using "@"
- Then type some plain text
- Then begin adding a tag with "@" and type in a few characters, then delete the typed characters.

## Observed behaviour
- The entire input box gets cleared

## Expected behaviour
- Only the deleted tag gets cleared.

## Platform on which bug was observed
- Browser: Google Chrome Version 77.0.3865.90
- OS: Windows 10

**Comment by coding-tech-guy** [comment]
I see this issue too, although for me it doesn't clear the whole input, only the present tag(s) leaving the plain text part.

**Comment by yairEO** [comment]
I will check this asap and let you know when it's fixed

**Comment by VIRUS-ATTACK** [comment]
Thanks for fixing it @yairEO 👍
