### ISSUE TITLE
Mix Mode Cursor Position on trying to delete a Tag using Backspace key.

### ISSUE THREAD

**Issue by VIRUS-ATTACK** [yairEO/tagify#330]
Bug observed in Mix Mode demo at [`https://yaireo.github.io/tagify/#section-mix`](url)

## Steps to reproduce
- First add a tag using "@"
- Then try to delete the tag using Backspace key

## Observed behavior
- Cursor jumping to the start of the input box

## Expected behavior
- Delete the tag that was added.

## Platform on which bug was observed
- Browser: Google Chrome Version 77.0.3865.90
- OS: Windows 10

**Comment by yairEO** [comment]
This is VERY difficult problem. I currently have no solution for this. I see it as a browser bug which is VERY difficult to solve :/

**Comment by VIRUS-ATTACK** [comment]
@yairEO Thanks for fixing it 👍
