### ISSUE TITLE
Mix Mode - Caret Focus After Dropdown Select

### ISSUE THREAD

**Issue by coding-tech-guy** [yairEO/tagify#332]
When selecting an option from a dropdown, the drop down won't close even when closeOnSelect is set to true.

I've attempted to add `this.dropdown.hide.call(this);` to line: https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1518

This does close the dropdown but the focus is lost.

It would be ideal if we could have this close on select, and for the caret to focus after the newly added tag to continue input if required.

**Comment by yairEO** [comment]
More specifically, selecting by mouse, not keyboard.

I didn't see this once because I never use the mouse when I'm using Tagify since I am typing it's intuitive to continue using the keyboard for selecting a dropdown item.

I will investigate and eradicate this bug, thanks for reporting

**Comment by coding-tech-guy** [comment]
No problem, I only noticed it as i was testing on mobile and touch is the only option without arrow keys.

Thanks.

**Comment by yairEO** [comment]
I've added 2 new events now: `focus` & `blur`

You can see them in [this exmaple](https://yaireo.github.io/tagify/#section-input)
