### ISSUE TITLE
Placeholder not updating

### ISSUE THREAD

**Issue by codertimu** [yairEO/tagify#334]
Hi, setting the placeholder does not update the control.
Here is an example:
https://jsbin.com/kodesuroyi/edit?html,js,output

**Comment by codertimu** [comment]
I should have been more clear. I don't mean the initial setting. I mean changing it for example in add/remove events does not update it. In the above example jsbin, I wanted to hide the placeholder if there is at least one tag and show otherwise.

**Comment by yairEO** [comment]
You can do it with CSS, so **only** if there's a tag this selector will happen:

```css
.tagify__tag + .tagify__input::before{
  content: "";
}
```

[demo page](https://jsbin.com/zovibac/edit?html,css,js,output)
