### ISSUE TITLE
Callback when removing a tag with backspace

### ISSUE THREAD

**Issue by nichollascarter** [yairEO/tagify#335]
Hello! 
Thank you for your work.
I need to use backspace for removing tags in the "mix" mode, but callback not firing. 
Maybe I am missing something, but I checked your [demo](https://yaireo.github.io/tagify/#section-mix) and backspace not firing remove event(see console).
I am not sure if it is a bug...

## Update:
I use **react.tagify** and It would be great to see an example for "mix" mode with setting "value" prop for **<Tags>** component.

**Comment by yairEO** [comment]
Just published a fix. The `this.value` wasn't updated before the `input` event was fired. You can see it works well in the [demo page](file:///C:/projects/tagify/index.html#section-mix)

**Comment by nichollascarter** [comment]
Here is an example of [React demo](https://codesandbox.io/s/tagify-react-wrapper-xrxky).
My config includes **mix** mode and allowing **duplicates**.

React example does not work with mix mode, so I decided temporary use Vanilla JS solution.
With [Vanilla JS component](https://codesandbox.io/s/tagify-react-wrapper-sybx1) works well, but when I allow duplicates, duplicated tag is not showing as tag and not displaying in dropdown menu.

Thanks.

**Comment by muskangupta3** [comment]
Is this issue fixed in javascript version ?

**Comment by yairEO** [comment]
@nichollascarter - is it the same as this ticket?
https://github.com/yairEO/tagify/issues/339

**Comment by nichollascarter** [comment]
@yairEO, this is exactly the same.

**Comment by yairEO** [comment]
@nichollascarter - Just released version `3.0.0`. Try updating Tagify and let me know if this still happens. Should be fixed

**Comment by nichollascarter** [comment]
Firstly, thanks for the response.
Just updated to the newest version and got next result(mix mode / duplicates allowed):

- [x]  Duplicated tags interpreted correctly
- [x]  Dropdown menu appears when new tag is entering
- [ ]  Dropdown menu show duplicated tag in list

Last item is not so important, but I would like to have possibility to show existed tag in dropdown list.

Thanks!

**Comment by yairEO** [comment]
@nichollascarter - have you set the `duplicates` setting to `true` ?

**Comment by nichollascarter** [comment]
@yairEO - yes, I have set to `true`, but I did not see the item("_Current_") in list:

![image](https://user-images.githubusercontent.com/7247874/70910847-44470e00-2019-11ea-810e-bda2488a2439.png)

But I can to add duplicate if I am entering a first letter of a tag:

![image](https://user-images.githubusercontent.com/7247874/70911040-ac95ef80-2019-11ea-9f21-6f4de6984928.png)
