### ISSUE TITLE
Line Break doesn't work on mix mode textarea, REACT

### ISSUE THREAD

**Issue by mirkosantangelo** [yairEO/tagify#337]
#143 # Explanation
I'm using Tagify via the provided React component. Adding a line-break or soft return on the component (I'm using a Textarea) breaks the plugins, and return wrong values.

**Settings:**
```
{
            addTagOnBlur: false,
            placeholder: "Expression...",
            whitelist: this.getTokensData(),
            mode: 'mix',
            pattern: /\$/,
            enforceWhitelist: true,
            duplicates: true,
            dropdown: {
                enabled: 1,
            },
            callbacks: {
                add: this.handleInput,
                input: this.handleInput,
                remove: this.handleInput
            }
}
```

***Component***
```
 <Tags
                        mode="textarea"
                        settings={this.tagifySettings}
                        value={value}
                        ref={ (el) => this.tagifyInstance = el }
 />
```

**Get Value Method**
```
    handleInput = (e) => {
        const val = this.tagifyInstance.tagify.DOM.originalInput.value;

        this.setState({ expValue: val }, () => {
            console.log(this.state.expValue);
        })
    }
```

**- What is the expected behavior?**
Should return string with corrects tags format: 
`[[{"value": "Page Name"}]] my sample text  [[{"value": "Page Index"}]]` 

**- What is happening instead?**
Return simple string instead of formatted text after newline is added:  
`[[{"value": "Page Name"}]] my sampletextPage Index`

Backspace stops working too, after a newline is added.

**Comment by yairEO** [comment]
Thanks for reporting, I will investigate and let you know

**Comment by yairEO** [comment]
How about now?
https://codesandbox.io/s/tagify-react-wrapper-6vd3i

Please open the demo in full-view to be able to use <kbd>Enter<kbd> key. Something is blocking the key from functioning within the demo, in edit-mode, for some reason.

Also pushed a minor update to the code so feel free to update
