### ISSUE TITLE
"Duplicates" option seems doesn't work correctly.

### ISSUE THREAD

**Issue by Temdi** [yairEO/tagify#339]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

In **Mix** mode with **Textarea** input, when option **duplicates** is set to **true**, all tags should be interpreted. (i guess).

## Current Behavior

Actually, when option **duplicates** is set to **true**, only first occurrence of duplicate tags is interpreted.

Oddly, when the option is **false**, all tags are correctly interpreted, but I can not add an already existing tag.

## Steps to Reproduce

https://jsbin.com/yepuwadutu/1/edit?html,js,output

Thank you in advance,

**Comment by yairEO** [comment]
Will be fixed promptly, thanks!

**Comment by yairEO** [comment]
> Oddly, when the option is false, all tags are correctly interpreted, but I can not add an already existing tag.

Since `duplicates` is set to `false` then of course you cannot add already-existing tags...because they would be a duplicate, and it would invalidate the rule.

Regarding the bug when it's set to `true`, I will push a fix today

Thanks for reporting!
