### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by pompex** [yairEO/tagify#34]
Not sure if it's related by bootstrap (since the demo works fine for me) but anyways, here is how the fresh setup looks like:

![image](https://user-images.githubusercontent.com/4152201/30839145-43d72dca-a270-11e7-96cb-e6e1c217e71b.png)

background doesn't work at all for tags. Probably caused by the opacity and z-index in the `tags tag > div::before`. 

When I remove the z-index from it:

![image](https://user-images.githubusercontent.com/4152201/30839200-9d5007fa-a270-11e7-84b5-5eb4ded1896f.png)

Then in the `tags tag > div > span` change the opacity to `.9` to make it work:

![image](https://user-images.githubusercontent.com/4152201/30839237-e21ab970-a270-11e7-8288-7f13a8a20ee8.png)

If you set the opacity to 1 it will not work. 

This is known behaviour when using animations + z-indexing. 

Using latest Opera browser. Doesn't work in Chrome neither.

**Comment by yairEO** [comment]
I need to see some demo page to be able to help with this.. it's quite difficult to assume anything without seeing what's going on

**Comment by pompex** [comment]
Simply load bootstrap 3 css before tagify css. That should do it.

**Comment by melenaos** [comment]
Set the background of tags to White to see this problem.
`tags {
    background: #fff;
}`

I have made a fix that works without the `z-index:-1`

Override the following CSS rules:

  ```
    tags {
        background: #fff;
    }
    tags tag > div::before {
        z-index: 0;
        background: rgba(126, 126, 126, 0.2)
    }

    tags tag:hover div::before {
        background: rgba(65, 65, 83, 0.2)
    }
```

**Comment by yairEO** [comment]
Loaded bootstrap CSS file and all works well..

![tagify - demo - mozilla firefox 2017-10-11 23 03 47](https://user-images.githubusercontent.com/845031/31464004-b582023c-aed8-11e7-8a5a-bb11645c9b5c.png)

**Comment by melenaos** [comment]
Accidentally i used the #34 in that pull request. I haven't implement my proposition in the pull request
