### ISSUE TITLE
React example doesn't work

### ISSUE THREAD

**Issue by pixelmixer** [yairEO/tagify#344]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### codesandbox template

https://codesandbox.io/s/tagify-react-wrapper-o7bww

### Explanation

The project should build and importing Tags from @yaireo/tagify/dist/react.tagify should render properly.

Using `import Tags from "@yaireo/tagify/dist/react.tagify";` results in a module import error because it cannot find **tagify.scss**.

`Could not find module in path: '@yaireo/tagify/dist/tagify.scss' relative to '/node_modules/@yaireo/tagify/dist/react.tagify.js'`

Whoever prepared the react example in the documentation apparently discovered the same problem and worked around it by copying the files and running them locally instead of using the files from the library. Instead of fixing the issue, they commented out the proper example.

```
// import Tags from "@yaireo/tagify/dist/react.tagify";

//// IMPORTANT ///////////////////////////////////
// ☝☝☝ In reality use the ABOVE commented line
import Tags from "./tagify/react.tagify";
```

**Comment by yairEO** [comment]
Thanks!

**Comment by souuu** [comment]
So what is the correct way to use tagify on react please ?
No need to do npm install ? I import everything locally ? If not how to import the react wrapper ?
Thank you,
