### ISSUE TITLE
Possible to add custom key & value element in the array ?

### ISSUE THREAD

**Issue by pesseyjulien** [yairEO/tagify#347]
Hi,

I was wondering if it was possible to have a custom key <-> value relation when adding an element ?

Thanks in advance for your help,
Julien

**Comment by yairEO** [comment]
Can you clarify or ask this differently? I don't understand, sorry :)

**Comment by pesseyjulien** [comment]
Sure, trying to achieve something like that : 

![Capture d’écran 2019-11-21 à 12 24 30](https://user-images.githubusercontent.com/10850944/69333933-f4636a00-0c59-11ea-9971-cb9dda7dc5d7.jpg)

But more elegantly :)

**Comment by yairEO** [comment]
Combining [this](https://github.com/yairEO/tagify#adding-tags-dynamically) & [this](https://github.com/yairEO/tagify#dom-templates) examples:

https://jsbin.com/zosajaroru/1/edit?html,js,output

As you can see from the demo, I can build the HTML of the tag anyway I please, using other properties of a tag beside the `value` property.

Does this solution suits you?

**Comment by pesseyjulien** [comment]
Not really, I actually ended up using table.

Thanks anyway !
