### ISSUE TITLE
mix-mode: right-arrow should autosuggest keeping the interpolator 

### ISSUE THREAD

**Issue by yairEO** [yairEO/tagify#348]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

https://jsbin.com/bakovoduja/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**
    The same interpolator character(s) should be kept after applying the autosuggestion of an highlighted option in the dropdown menu when clicking the <kbd>→</kbd> key

- **What is happening instead?**

clicking the right-arrow while highlighting a suggestion from the dropdown, it autocomplete it without the interpolator character at the start, which then will not allow it to become a tag.

> Replace this text with your text - This is only a template for bug report.

**Comment by muskangupta3** [comment]
The issue doesn't seems to be completely resolved , i was testing the issue on the uploaded demo and now when i click the right arrow key , tag is not created , and the characters which were written to filter the options in the dropdown are erased and the remaining characters from the selected option is attached in the input.
For instance , i typed @k and i had one of the options as kenny , so when i select it , only 'enny' is inserted into the input field and not the entire option 'kenny' as a tag.
Is the issue just in the demo ?

**Comment by yairEO** [comment]
Weird, I do not see the bug you are referring to, BUT tomorrow I will be releasing a new version with many bug fixes and improvements so be sure to check again then

**Comment by muskangupta3** [comment]
Is it Some OS specific issue ? 
Yes I’ll check it again tomorrow

**Comment by yairEO** [comment]
I've postponed the new release by a few days due to the massive amount of code changes, it needs to be carefully tested first
