### ISSUE TITLE
Is there a way to add a tag by code?

### ISSUE THREAD

**Issue by criocere** [yairEO/tagify#35]
Hello,

I don't see in demos if it is possible to add a tag by calling a method in javascript.
I tried this without success. Is there a way?

```
var elm= $('#myInput').tagify();
elm.addTag('myTag');
```

**Comment by yairEO** [comment]
in your case `elm` is a jQuery element, and does not have any methods which are related to `tagify`.

To access Tagify's methods, you need to do it like so:

     elm.data("tagify").addTag('myTag');
