### ISSUE TITLE
Tag matching using ajax / a regular expression

### ISSUE THREAD

**Issue by b-cil** [yairEO/tagify#351]
Hello everybody,

I'm using tagify as I want to replicate some features of todoist or slack where you can mix text and tag recognition which trigger actions...

The problem I have is that tag recognition in mix mode is limited to tags being declare in a js array...

Thing is I have pattern which are looking into long lists and might not want it to be treated in javascript but server side so could I search dropdown or whitelist using ajax ?

Another prefix will trigger a date which could either be tomorrow next day or a given day... I can input tomorrow or fixed day in javascript but is there a way to do pattern matching or regular expression for flexible input ?

**Comment by yairEO** [comment]
The demo page shows this exact scenario, although not using AJAX, it does say where should the ajax call ideally be placed:

https://yaireo.github.io/tagify/#section-mix
