### ISSUE TITLE
Regarding destroy method

### ISSUE THREAD

**Issue by muskangupta3** [yairEO/tagify#352]
I want to empty the tagify object which contains the information about the last active input once the destroy method is called . How can i achieve this ?

**Comment by yairEO** [comment]
Why would you want to do that? is Tagify was removed, then what does it matter regarding that instance? It will be garbage-collected if is unused and un-referenced

**Comment by muskangupta3** [comment]
Within my Code I am checking if tagify has some value or not , and even after destroying , the value in the tagify object is still there , so it fails my condition. So I want to empty the object also as I destroy it

**Comment by yairEO** [comment]
You should call the `removeAllTags` method before calling `destroy`.
I do not want to include that method in the `destroy` process automatically because I believe it isn't a desirable thing to be happening when destroying Tagify.

**Comment by muskangupta3** [comment]
I did call removeAllTags method before destroy , but this also doesn't seem to serve my purpose

**Comment by yairEO** [comment]
And what is your purpose? If you called `removeAllTags` then now the your tagify instance's value is an empty array `[]` and the value of the *input* element is an empty string `""`

**Comment by muskangupta3** [comment]
Tagify {settings: {…}, state: {…}, value: Array(0), listeners: {…}, DOM: {…}, …}
DOM: {originalInput: input#description, 
scope: tags.tagify.tagify--mix., input: span#description.tagify__input, dropdown: div.tagify__dropdown}
listeners: {main: {…}}
off: ƒ (name, cb)
on: ƒ (name, cb)
settings: {delimiters: /,/g, pattern: /@/, maxTags: Infinity, callbacks: {…}, addTagOnBlur: true, …}
state: {}
trigger: ƒ (eventName, data)
value: []
}

I want the above tagify object to be empty , not just the value array. after i destroy tagify

**Comment by yairEO** [comment]
Tagify cannot do that for you, you must cleanup the instance yourself, because you have created it, it's your part of the code which should handle this.

Why don't you simply assign it `undefined` once you've called the `destory()` method?

---
Here's a quick Google I've made and found a Stackoverflow question on this:
https://stackoverflow.com/q/21118952/104380

**Comment by muskangupta3** [comment]
Yea, i solved it by assigning it undefined myself.
