### ISSUE TITLE
Jest and Create React App -  SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by natejcho** [yairEO/tagify#355]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo
https://codesandbox.io/s/tagify-react-jest-w20of

### Explanation
Using create-react-app, cannot test react tagify component

![image](https://user-images.githubusercontent.com/9434077/69553067-7e1e7a80-0f6d-11ea-9571-aa1b63029be3.png)

- **What is the expected behavior?**
No Syntax Error, jest suite runs

- **What is happening instead?**
Test suite cannot execute

- **What error message are you getting?**
/node_modules/@yaireo/tagify/dist/react.tagify.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from "react";

  SyntaxError: Unexpected identifier

 import Tags from '@yaireo/tagify/dist/react.tagify';

 at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/tag-input/index.js:3:1)

**Comment by yairEO** [comment]
How are you testing it? importing it directly to the test or are you testing another component which uses Tagify internally?

Note that there is no need to test it unless you have custom modifications done, since 3rd-party scripts from the internet should not be tested and should come tested out-of-the-box

**Comment by natejcho** [comment]
i have a custom callback for add,remove and edit. so i am testing that component.
it fails there and in all implementations of my custom version

**Comment by natejcho** [comment]
https://codesandbox.io/s/tagify-react-jest-w20of

**Comment by yairEO** [comment]
you can copy your `package.json` to the demo and it should install CRA and then it will be similar to your env

**Comment by natejcho** [comment]
code-sandbox should be up to date now. please inspect. 

I noticed that everything worked fine until i added the custom test script.
might have to do with transform

**Comment by yairEO** [comment]
Your sandbox shows me that the jest test has passed:

![image](https://user-images.githubusercontent.com/845031/69556342-d91f9400-0fa4-11ea-9bb8-2b85485b62eb.png)

**Comment by natejcho** [comment]
![image](https://user-images.githubusercontent.com/9434077/69556464-be342c00-0f72-11ea-8d47-94c663d4c64a.png)

**Comment by yairEO** [comment]
Maybe clear cache? try in incognito?
I do not know why your own demo works for me but not for you, very strange. it should be sandboxed and OS-agnostic

**Comment by natejcho** [comment]
Still having an issue, though don't know why I can't recreate it in sandbox. 

Googling the error, it seems to be common for babel module importing error. Is it possible that the file name is causing compilation issues? 

.tagify.js

**Comment by yairEO** [comment]
Try using the exact same `package.json` in the demo and it should install all the dependencies and maybe the issue will appear
