### ISSUE TITLE
cannot insert data using addtags by mode mix

### ISSUE THREAD

**Issue by zuliandri2** [yairEO/tagify#356]
Hi all

I tried to insert data using addtags, bui it cannot be tags
you can see in my code, how to make it?
I am using 2.9.9, when I change to latest version, the result is the same

https://jsbin.com/maxizunaso/edit?html,js,output

**Comment by yairEO** [comment]
I will check and let you know

**Comment by zuliandri2** [comment]
Hi @yairEO 

I thought it will be work in mix mode when I used addTags in my function
I resolve with loadOriginalValues
but first must be insert value, before call loadOriginalValues, 
now my problem is delimeters, it must be has a delimeter, without delimeter it will not become tags

Thanks @yairEO

**Comment by yairEO** [comment]
I am currently on vacation but have pushed a fix for this to my experimental [v3 branch](https://github.com/yairEO/tagify/tree/v3), so you are free to try it until I come back on Monday

**Comment by yairEO** [comment]
I will release v3 this week which will have this fixed

**Comment by yairEO** [comment]
Just released version `3.0.0`. Try updating. Now `addTags` method should work for `mix` mode and should add a tag at the end of the content

**Comment by zuliandri2** [comment]
Hi @yairEO 
Thank's for updated.
