### ISSUE TITLE
UI distorted in case of Duplicates

### ISSUE THREAD

**Issue by muskangupta3** [yairEO/tagify#357]
I have set duplicates as true, and i have two values 'chris' and 'Chris' and when i add 'chris' first and then try to add 'Chris' , the UI of the tag gets distorted . The old value of 'chris' is replaced with the new value'Chris' 
And if i do the opposite of this , it works . 
I have attached screenshot of both the cases .

![Screenshot 2019-11-28 at 1 45 20 AM](https://user-images.githubusercontent.com/45684893/69756696-1a6c9b00-1181-11ea-810d-4aa312564806.png)
![Screenshot 2019-11-28 at 1 45 54 AM](https://user-images.githubusercontent.com/45684893/69756698-1b053180-1181-11ea-920e-394bf882ad3e.png)

**Comment by yairEO** [comment]
Please follow the issues template (and don't delete it) and make a demo showing this in action with the same configuration, so I could examine.

> clone & modify the below template to reproduce your issue 
> https://jsbin.com/degobup/edit?html,js,output

**Comment by yairEO** [comment]
@muskangupta3 - do you still require help?

**Comment by muskangupta3** [comment]
@yairEO No, this is resolved
