### ISSUE TITLE
Tag value doesn't update when changing option in single-value select mode

### ISSUE THREAD

**Issue by thetuningspoon** [yairEO/tagify#359]
### Demo Page

The issue can be seen on the demo: https://yaireo.github.io/tagify/#section-mode-select
Inspect the element as you change the selection and watch the value attribute on the tag element.

### Explanation

- The single-value select works properly when the option is first selected. However, when changing options, the value on the tag element doesn't update.

- The title changes but the underlying value remains the same.

**Comment by yairEO** [comment]
Seems to work fine for me. Which browser and OS are you using?

![GIF](https://user-images.githubusercontent.com/845031/70704574-8e0abe00-1cd2-11ea-8b0f-e5cc0f24107b.gif)

**Comment by thetuningspoon** [comment]
Thanks for looking into it. I’m using Chrome on Mac. I don’t know about the original input, but the value I am getting from it and the value on the tag element is not updating.

**Comment by thetuningspoon** [comment]
Just tested again and the original input is being updated, but tagify.value is not. You can see in the inspector that the tag element's title changes but value stays the same.

**Comment by yairEO** [comment]
Seems good to me, I cannot reproduce this.
See here: https://jsbin.com/wofenukabo/1/edit?html,js,console,output

**Comment by zoaked** [comment]
Hi @yairEO,

@thetuningspoon jumped in with me to investigate this issue as I have been short on time.  I apologize for the difficulty in communicating the things we were observing.  Here is a template that quickly demonstrates the specific problem we ran into.  https://jsbin.com/recajetame/2/edit?html,output

Things seem to be fine when setting, changing, or clearing the value using the visual elements.  When the element is programmatically removed the object value is cleared correctly while the visual value becomes out of sync by continuing to show the previous value.  (note that the X for removing the tag DOES become hidden so some of the UI is responding)  This only seems to happen in select mode as when we take that out tagify config the button works correctly.

Please let one of us know if you have any other questions about this report or if we can assist in troubleshooting / testing a fix for it.

Thank you.

**Comment by yairEO** [comment]
I will investigate your demo and let you know

**Comment by yairEO** [comment]
Please explain to me the steps I need to do in your demo to see the problem.
Tell me what to click and when to look where.

**Comment by yairEO** [comment]
Ho I think I understand. After selecting an item in the dropdown, when clicking the "clear all" button, the value should disappear.

**Comment by zoaked** [comment]
1) Click the template link to load the example
2) Press the clear button
3) See the message that shows before/after value array being cleared correctly
4) See that the value still appears in the box which is out of sync with the value shown in step 3 - should be empty

On a side note, when creating this template (or on the demo page) it seems that once a value has been chosen in select mode clicking on whitespace anywhere on the page will trigger the dropdown to open again.  This does not happen when a value has not been chosen or is cleared again.

**Comment by yairEO** [comment]
You need to call `tagify.input.set.call(tagify)` after you call `tagify.removeAllTags()`:

```
function clearAll() {
  var oldValue = toString(tagify.value);
  tagify.removeAllTags();
  tagify.input.set.call(tagify)
  var newValue = toString(tagify.value);
  recordLastEvent('Before Clear: "' + oldValue + '" After Clear: "' + newValue + '"', null);
}
```

This will also clear the input itself.

**Comment by yairEO** [comment]
I don't see the bug you've mentioned on the side-note happening. I selected a value and click randomly and the dropdown is not opening

**Comment by zoaked** [comment]
Firefox 71.0 on Windows
![image2](https://user-images.githubusercontent.com/10800710/70754841-43a33480-1d06-11ea-9dc5-09c30a213489.gif)

**Comment by yairEO** [comment]
@zoaked - just checked and this only happens on FF. I will investigate tomorrow.

**Comment by zoaked** [comment]
Thank you for the instructions on how to get the dropdown back in sync!  Two small follow up questions that are not clear to me:
1) Is calling `tagify.input.set.call(tagify);` something that should be done each time `removeAllTags` is used or is it only needed in select mode?
1) Is this a work around to get us going or is this intended behavior that we should always be performing?

I'm asking so I know how to document this in our code.  If it is intended, perhaps it would be helpful for others in the future to have a note in the readme docs and/or example?  If it unintended, perhaps an easy fix would be for removeAllTags to run this line of code automatically in select mode?

**Comment by yairEO** [comment]
> Is calling tagify.input.set.call(tagify); something that should be done each time removeAllTags is used or is it only needed in select mode?

> Is this a work around to get us going or is this intended behavior that we should always be performing?

No, it's an internal method, I need to make it fire inside `removeAllTags` only if the mode is "select". I will make the change and push an update today
