### ISSUE TITLE
When I remove a tag the input element is deleted

### ISSUE THREAD

**Issue by melenaos** [yairEO/tagify#36]
Hi and thank you for the nice js lib.
I have run onto a problem;
When i remove a tag the hidden input element is removed from DOM.
The bug also happens at your live demo page.
Please see the following screenshots.
At the first screenshot I highlight the hidden input before taking any action and at the second screenshot I delete a tag, as you can see the input element is removed.
![before removing tag](https://user-images.githubusercontent.com/7249160/31353516-8a24c370-ad3b-11e7-8d12-8a9f6842feee.png)
![after removing tag](https://user-images.githubusercontent.com/7249160/31353524-909b427e-ad3b-11e7-853c-d35ff4575955.png)

**Comment by yairEO** [comment]
Thanks for reporting. On it.
