### ISSUE TITLE
Questions about new version changes (maybe missed in docs)

### ISSUE THREAD

**Issue by 7iomka** [yairEO/tagify#361]
What is that tagify__dropdown__wrapper?
How to override this className or remove unecessary styling for this?
I don't needed to have blue style and fixed max-height for a wrapper of my suggestion items

**Comment by yairEO** [comment]
Yeah I forgot to update the README section for this update.
I've added a wrapper element to allow more complex customization on the dropdown, and this allowed me to also add a nice transition effect when the dropdown is shown.

I will update the README

Do you know CSS and how/where to use it?

**Comment by 7iomka** [comment]
> Do you know **CSS** and _how/where_ to use it?

Yes) I'm frontender)
Also
See please this rule: https://github.com/yairEO/tagify/blob/master/src/tagify.scss#L165
transition has wrong value (time without unit)
please fix it ....1s color

**Comment by yairEO** [comment]
Thanks for spotting that!

If you want to override the styles and you are a frontend developer, than why don't you simply override those specific rules which apply to the dropdown within your own stylesheet? (don't edit Tagify's CSS)

**Comment by 7iomka** [comment]
Another question:
### How to do that:
1) to search across multiple fields (in my case: `name`, `nickName`)
2) depended from what filed typed, tag will be filled with this `value`

If I have response from server for suggestion items like that
```
[
// ...
   {
      name: 'Chris Muller',
      nickName: 'cmr22',
    },
// ...
]
```

### My expectations:
User types **cmr**
In suggestion dropdown will be rendered item (in my case - custom template that contain all user fields from response: avatar, nickName, name, etc..)
On navigation between dropdown items inside tag autocomplete will be value of needed field that starts with **cmr**.
On select dropdown item, tag will be filled with that field value (in my case **cmr22**)
Native input will achieve this filed value inside "value" prop
`(input.value === [{ value: 'cmr22' }]`

**Comment by yairEO** [comment]
You can use [alias](https://github.com/yairEO/tagify#example-for-a-suggestion-item-alias) which can help you in your case. You need to define another property, `searchBy`, for each of your items, and inside it you can put whatever string you wish and Tagify will also look there.

Currently there is no way of telling tagify to scan specific properties other than `value` & `searchBy`

I might add such functionality though, it is an interesting suggestion

**Comment by 7iomka** [comment]
> Currently there is no way of telling tagify to scan specific properties other than `value` & `searchBy`
> 
> I might add such functionality though, it is an interesting suggestion

the best way out of the situation at the moment is additional post-processing of data received from the server? Like that

```
tagifyInst.settings.whitelist = { response.items.map(item =>{
const { nickName, name } = item;
 return {
...item,
value: nickName,
searchBy: [nickName, name]
}

}) }
```

?
I will check this at the moment, but what to do that automatically when we needed to have default whitelist values? 
It turns out you need to create a function that you always use when initially filling whitelist with default available tags, and, when receiving data to display suggestion if users types a new one.

**Comment by yairEO** [comment]
`searchBy` key should be a String, not an Array, so you need to change it in your example to:

    searchBy: nickName + name


Yes, I can see why this might be annoying. I will put this request on high-priority, which means between a day to few days.

**Comment by 7iomka** [comment]
> Yes, I can see why this might be annoying. I will put this request on high-priority, which means between a day to few days.

Thank you so much.
I use your plugin to implement the mail-mix service and I want the same hint work as the **gmail** when you type something in the "to" field

**Comment by 7iomka** [comment]
I tested your recommendation on the current workaround and found a bug.
DEMO: https://codepen.io/7iomka/pen/jOEMEoo?editors=0010

1) First - when you type **cmr** you see needed suggestion item, but rightKey not working.
Only if you once navigate with arrow down on suggestion item, and go back to input and press right key - it will work fine in further.

2) Another bug - after first, if you press right key directly, **without any input**, value of previous tag will be dublicated and appended. Why?
Thanks

**Comment by yairEO** [comment]
I will release a fix on Monday, I've already started working on this

**Comment by yairEO** [comment]
Sorry it took so long, I wanted to include a few other fixes and improvements along the way, which took more time than I thought.

Anyway, checkout this issue which solves your problem
https://github.com/yairEO/tagify/issues/367
