### ISSUE TITLE
Can't delete tags (in mix mode) using keyboard in Firefox

### ISSUE THREAD

**Issue by tagspace** [yairEO/tagify#362]
## Prerequisites

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Demo Page
If I open this jsbin in the latest version of Firefox (currently 71.0 64-bit Mac version) and add a few tags (using @ symbol) and then try to delete the tags using the delete or backspace key on the keyboard, I cannot delete them:
https://jsbin.com/wokovon/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Can delete tags using the delete or backspace key in firefox.

- **What is happening instead?**
Tags are not being deleted.

- **What error message are you getting?**
No error message is shown in console, unfortunately.

**Comment by yairEO** [comment]
The problem is not that you cannot delete tags, it's that there is no way to gain focus on the input inside *Tagify* after a tag was added and there was no text after that tag. 

I is a tough problem, a bug in the browser

**Comment by yairEO** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=685452

**Comment by yairEO** [comment]
Partial fix. see my [answer here](https://stackoverflow.com/a/59383394/104380)
