### ISSUE TITLE
There is no typescript support for React.

### ISSUE THREAD

**Issue by manvel-khnkoyan** [yairEO/tagify#363]

**Comment by yairEO** [comment]
What do you mean? does this script (React wrapper) not working for you in some way?
Please further explain

**Comment by spaceemotion** [comment]
Right now the TypeScript files seem to be for the Angular implementation. There is no general TypeScript interface for the settings and so forth. I have the same "problem" with a Vue-based application, where it tries to import the .ts files from the angular files.

**Comment by yairEO** [comment]
I do not know *typescript*, how hard is it to make this interface thing?

**Comment by centrual** [comment]
Hello guys,

I added PR about typescript declarations. Check it out: https://github.com/yairEO/tagify/pull/531

Have a wonderful day!
