### ISSUE TITLE
mix-mode: duplicate items are not shown in suggestion list

### ISSUE THREAD

**Issue by yairEO** [yairEO/tagify#366]
When `duplicates:true` setting is set, and `dropdown.enabled:0` is also set, when typing only `@`, the the list is missing options which are already included as tags. When continuing to type, the option is then shown in the dropdown.

![image](https://user-images.githubusercontent.com/7247874/70910847-44470e00-2019-11ea-810e-bda2488a2439.png)

> But I am able to add duplicate if I am entering a first letter of a tag:

![image](https://user-images.githubusercontent.com/7247874/70911040-ac95ef80-2019-11ea-9f21-6f4de6984928.png)

_Originally posted by @nichollascarter in https://github.com/yairEO/tagify/issues/335#issuecomment-566066167_

**Comment by nichollascarter** [comment]
@yairEO, please, check problem with `mixTagsInterpolator` option.
I set this option as `mixTagsInterpolator: ['{{', '}}']`, but `tagify.on('input', ...)` event does not fire...
