### ISSUE TITLE
how to determine if there are any tags

### ISSUE THREAD

**Issue by keksa** [yairEO/tagify#369]
Is there any way of determining if there are any tags present including invalid tags? I tried using the `getTagElms()` method, but it does not contain invalid tags, neither does the `value` property.

I also tried simply counting the present `.tagify__tag` elements, which gives me the correct number, but I need to get the count after any change whatsoever, but it seems the `invalid` event is triggered before the DOM is updated, so the count does not fit.

What I'm trying to do is to add a class to the `.tagify` element, because I need to style it differently when empty.

(Tagify 3.1.0, latest Firefox on macOS)

**Comment by yairEO** [comment]
`getTagElms` method should give you all tags.

You can use `setTimeout` with `0` delay and then call that method, to make sure the tags are already there. I can make the fix internally in Tagify, good idea.

Can you please post here a picture how do you want to style an empty tag?
Do you mean a user would edit a tag and delete all the text, or create a new, empty tag and then fill it (like in the [demo page](https://yaireo.github.io/tagify/#section-different-look)) ?

**Comment by keksa** [comment]
I don't mean empty tag, but empty textarea (`.tagify`). Basically I need to have different padding on it when it's empty and when it has any tags, so that it conforms better to the form style I have on all other inputs.

**Comment by yairEO** [comment]
Ok, I've released a new version this minute (`v3.2.1`) with many fixes, and what you need is included.

Added a class, `tagify--noTags`,  when there are no tags to the main element.

**Comment by keksa** [comment]
Hello @yairEO, the `tagify--noTags` is not present when the tagify is initialized, I first must input something and then delete it to trigger adding the class.

I'm on `v3.2.6` and it's the case in both latest Chrome and Firefox.

**Comment by yairEO** [comment]
@keksa - I will check, thanks

**Comment by yairEO** [comment]
@keksa seems like `tagify--noTags` class is indeed *present* when tagify is initialized, just verified
