### ISSUE TITLE
posibility to disable animation when removing a tag

### ISSUE THREAD

**Issue by keksa** [yairEO/tagify#371]
When a tag is removed, it currently takes 400 ms (hardcoded value) until the tag is really removed. Would it be possible to add an option to disable this animation?

The animation is already disabled when `mode=select`, but I'd like to disable it even in normal mode.

Please note, that I'm talking about tag removal via keyboard backspace or by clicking the (x) button, not about calling the method programmatically.

**Comment by yairEO** [comment]
Currently it's not possible, because I have never thought someone would not like my nice animation.. BUT, I can make a settings, especially for you, to allow controlling the animation. 

But why don't you want the animation?

**Comment by keksa** [comment]
I don't want the animation for the absolutely same reason as in https://github.com/yairEO/tagify/issues/369 :) I need the tagify component to fit with the overall style of my application and since I don't have any such animations anywhere, it breaks the feel in comparison to other form elements.

**Comment by yairEO** [comment]
Released new version (`v3.2.1`). Now you can control the animation via CSS variable:

    --tag-hide-transition

You can set it to `0s` by applying this variable on your custom `.tagify` selector, if you have one (or just add one)

Additionally, it is possible to hook into Tagify internals and set this:

    this.CSSVars.tagHideTransition = 0

After initializing Tagify

**Comment by keksa** [comment]
Brilliant, thank you very much (and also for #369). I'm out of office for the year, so I'll let you know how it goes in january. :)

**Comment by keksa** [comment]
Just got to this and it works nicely, thank you again. There is a slight problem, when I set the transition to only `0` and not `0s` (as I don't use units for zeroes) the javascript will crash in the `seprateUnitFromValue` function.

It would be nice if it could detect, that the value is already a number

**Comment by yairEO** [comment]
CSS transition duration cannot be a unitless-number, this is invalid code

**Comment by keksa** [comment]
@yairEO Huh, you're right, did not know that. I presumed the zero could be unitless just like for length values. Thanks.
