### ISSUE TITLE
Force paste as plain text

### ISSUE THREAD

**Issue by thetuningspoon** [yairEO/tagify#376]
I noticed that Tagify does some odd things when you try to paste formatted/rich text into it. Here is one possible solution:
http://jsfiddle.net/HBEzc/

Could something like this be implemented?

**Comment by yairEO** [comment]
newlines (`\n` or `\r\n`) should remain intact. I have some idea I want to try.

I am aware of this problem

**Comment by thki91** [comment]
It would be great if pasting rich text would work 👍 or if there's a simple solution for adding it

**Comment by hugomn** [comment]
Is there any plan to support pasting markup / rich text? This makes tagify unusable when pasting any content from google spreadsheets, for example. Any thoughts?

**Comment by gpetrov** [comment]
Well I added easily copy as text to Tagify after it's creation but something like this might be better added to the core @yairEO 

```js
   var TAGIFY = new Tagify(input, {
      ....
    })

    //Add events
    function handlePaste (e) {
      var clipboardData, pastedData;

      // Get pasted data via clipboard API
      clipboardData = e.clipboardData || window.clipboardData;
      pastedData = clipboardData.getData('Text');

      // insert text manually
      document.execCommand("insertHTML", false, pastedData);

      // Stop data actually being pasted into div
      e.stopPropagation();
      e.preventDefault();
    }

    function handleCopy (e) {
      const selection = document.getSelection();
      var copyText = selection.toString();

      event.clipboardData.setData('text/plain', copyText);

      // Stop the default copy
      e.stopPropagation();
      e.preventDefault();
    }

    TAGIFY.DOM.input.addEventListener('paste', handlePaste);
    TAGIFY.DOM.input.addEventListener('copy', handleCopy);
```
