### ISSUE TITLE
Wrong value after edit/update a tag

### ISSUE THREAD

**Issue by ricardocanelas** [yairEO/tagify#377]
**What is the expected behavior?**
Get all values after add/update/remove events, by accessing the property `e.detail.tagify.value`

**What is happening instead?**
Getting the wrong values only after editing a tag.

To reproduce the bug, go to https://codesandbox.io/s/tagify-react-78ww1
and try to edit the 'brazil' tag to 'portugal'.

Should be `["foo", "portugal"]` but it's bringing `["portugal", "brazil"]`

**version** 
- 3.2 @yaireo/tagify 
- 16.12.0 react

(using React wrapper)

**Comment by yairEO** [comment]
I will fix it ASAP, thanks
