### ISSUE TITLE
Documentation / readonly but can delete tags

### ISSUE THREAD

**Issue by onassar** [yairEO/tagify#380]
Really great library.
Having trouble finding documentation on the API, events, etc.
Is that somewhere?

For context, this is why I'm searching for more documentation.
I have some inputs that have some tags specified (eg. `abc, 123, xyz`).

I want to limit users so that all they can do is:
- delete any of the tags specified

I don't want to let them:
1. edit any of the tags
2. add any more tags

I couldn't see how this would be accomplished out of the box, so I started to search for documentation on how I could accomplish this.

Thanks and happy holidays :)

**Comment by yairEO** [comment]
Besides the [README/main page](https://github.com/yairEO/tagify#css-variables-see-mdn-docs) of this Github repo?

**Comment by yairEO** [comment]
You can simply make CSS changes in your side to show the (x) button on tha *read-only* tags

![image](https://user-images.githubusercontent.com/845031/71470704-579e6a00-27cd-11ea-96c3-9d3f8cc52a15.png)

**Comment by onassar** [comment]
Gotcha thanks that'll work :)
