### ISSUE TITLE
Prevent tag from beign editable

### ISSUE THREAD

**Issue by inDeev** [yairEO/tagify#381]
Hi, can you add some property to prevent tag from being editable?
E.g. in whitelist I have data from db

```
[
  {"id":3,"title":"Drama","fg_color":"FFFFFF","bg_color":"DC3434","value":"Drama"},
  {"id":2,"title":"Documents","fg_color":"016771","bg_color":"ACACAC","value":"Documents"},
  {"id":1,"title":"Fantasy","fg_color":"F9F9F9","bg_color":"D23989","value":"Fantasy"}
]
```

Let's say I will add `"editable": false` to all of them when parsing from db, to prevent these tags from being edited? Only new tags, which have only `"value":"something"` would be editable then. 
Also there can be some global setting like "editable" to disable edit of all tags.

**Comment by yairEO** [comment]
hi I'm currently on vacation and will be back in 6 days

**Comment by yairEO** [comment]
To prevent all tags from being "editable" you can set this setting:

    {editTags : false}

Regarding your first suggestion, I will think of a solution.
