### ISSUE TITLE
Pagination in dropdown

### ISSUE THREAD

**Issue by evsign** [yairEO/tagify#382]
Hi. Maybe there are exists the way to create scrollable pagination within ajax populated dropdown like in select2?

**Comment by yairEO** [comment]
Do you have a link with an example to show me?

**Comment by evsign** [comment]
Yeah. https://select2.org/data-sources/ajax
At the top of the page there are select input where ajax call is triggered after only one input character and you can infinitely scroll search suggestions.

**Comment by yairEO** [comment]
This is lazy-loading of list items while scrolling, it's not a real pagination.
Why would you want that? is it slow on the server side to pull the whole list of results and return it with the ajax response?

**Comment by evsign** [comment]
From my point of view lazy-loading its almost the same as pagination) We display first page of results and when we encounter end of this results we display the second and so on.

This is very useful for user friendliness of interface. For example user don't know what tag to add and instead of adding some random useless thing user can explore already created tags to choose what to add.
Also when, for example, we found in database something like 30 results total, which we cannot display on the page at one time, and then we don't need to load its all at once, but we can do 3 requests with 10 results in response. Considering that average user could not load more than 1-2 pages we save some computation time in average (i suppose)

**Comment by yairEO** [comment]
@evsign - Ok, I will add a new event for the scroll position of tagify's suggestions dropdown. hopefully I will release it in a few days from now.

**Comment by evsign** [comment]
Thanks! Ideally will be if you add event like `dropdown:end` in which will be passed number of occurrence which can be used as a page for subsequent request.

**Comment by charlesr1971** [comment]
This is a great idea. I am looking forward to this feature. It will allow infinite scalability. I think lazy loading is the best approach, rather than trying to fit pagination links at the bottom of the drop down.

**Comment by JuanDa90laq** [comment]
Hello, this method is already implemented, if so, could you give me a small example of how to use it, Thank you very much

**Comment by antondalgren** [comment]
Hi @evsign, did you ever get this to work, or did you go with select2?

**Comment by yairEO** [comment]
@antondalgren - yes, as you can see it was closed with a commit which implemented the [dropdown:scroll](https://github.com/yairEO/tagify#events) event listener

## Basic example:
```js
const tagify = new Tagify(...)

tagify.on('dropdown:scroll', e => console.log(e.detail.percentage)
```
