### ISSUE TITLE
Can't delete tag by backspace if it is only one tag in input

### ISSUE THREAD

**Issue by Megas78** [yairEO/tagify#384]
If you have the only one tag in input you can't delete it by backspace. To reproduce ... just create a tag, then try to delete it by Backspace. Issue also reproducible  if you have several tags without any separator (like space or another symbol). Thanks for your work!

**Comment by yairEO** [comment]
Cannot reproduce. which browser? does this also happens in the [demo page](https://yaireo.github.io/tagify/)?

**Comment by traed** [comment]
I have the same problem and I can reproduce it on the demo page in the mixed mode input. If you delete the prefilled content, create an "@" tag, and then try to remove it using backspace it doesn't work. I'm running latest chrome on mac.

**Comment by Megas78** [comment]
I also use latest chrome on mac.

**Comment by yairEO** [comment]
I am looking into it. These Chrome bugs are not easy to fix

**Comment by andy-reach** [comment]
I tried reverting to a previous version and discovered the following:
3.2.0 works correctly. Backspace deletes the tag
3.2.1 deletes the tag after pressing backspace twice
3.2.2 deletes the tag after pressing backspace twice
3.2.3 backspace does not delete the tag at all

I am using latest chrome on windows 10
