### ISSUE TITLE
Quotes are missing from tags when there's only one tag

### ISSUE THREAD

**Issue by onassar** [yairEO/tagify#386]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/petozoguvu/edit?html,js,output

### Explanation
I'm dealing with a Tagify input that may have tag values like this:
- abc
- def
- "ghi"

Notice the quotes in the last one.
This works fine, but only when the value `"ghi"` is accompanied by other tags.
You can see this here: https://jsbin.com/lusexefohi/1/edit?html,js,output

When it's the _only_ tag, the quotes are missing.
You can see that here: https://jsbin.com/jodatataji/1/edit?html,js,output

- **What is the expected behavior?**
The quotes should always show up, regardless how many tags there are.

- **What is happening instead?**
The quotes are missing when it's the only tag.

- **What error message are you getting?**
No error message.

--
Thanks so much for this library!

**Comment by onassar** [comment]
Bump! Hope to get some help on this, as it's stopping us from a production update :(

**Comment by yairEO** [comment]
I am investigating now, thanks for reporting

**Comment by onassar** [comment]
Okay thanks so much!

**Comment by onassar** [comment]
Thanks for the push :)

**Comment by onassar** [comment]
Quick question: are you going to release a new distribution with this fix?

**Comment by yairEO** [comment]
Yes, a new version is deployed on NPM with every update to this repo

**Comment by onassar** [comment]
So the `3.2.6` release on GitHub has these changes?

**Comment by yairEO** [comment]
yes, it says this in the `closed this in 74a65cc 21 hours ago` above.. there was a commit pushed so that means it has the changes for this *exact* issue

**Comment by onassar** [comment]
Okay thanks so much; really appreciate the time you've put into this library. It's amazing. I'll follow up if I have any more problems.

Thank you from Toronto 🇨🇦 :)

**Comment by onassar** [comment]
Hi there -
`3.2.6` doesn't seem to address the problem. Looking at the commits (https://github.com/yairEO/tagify/commits/master), it looks like you committed the fix after you bumped the version.

I'm downloading the release from here:
https://github.com/yairEO/tagify/releases

Would you be able to release a new version there?

**Comment by yairEO** [comment]
Why aren't you downloading from NPM as a node module?

You should download always from the *Master* branch which has the most up-to-date code

**Comment by onassar** [comment]
I prefer not to use NPM; any chance you'll push up a new release that has the changes?
