### ISSUE TITLE
Text Area insert line break doesnt work

### ISSUE THREAD

**Issue by knasser** [yairEO/tagify#388]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/kibesakeha/1/edit?html,js,output

### Explanation

- **What is the expected behavior?** 
inserting a line break in the tagify span is also inserted in the hidden text area

- **What is happening instead?**
line break is ignore in the text area
- **What error message are you getting?**

**Comment by yairEO** [comment]
now it works
