### ISSUE TITLE
change to tag in mix mode

### ISSUE THREAD

**Issue by knasser** [yairEO/tagify#389]
we would like to give the user the ability to select a word in a mixed mode.. then click "make tag" to add the word to the whitelist and turns it to a tag.. 
not sure if this is is possible with the current tagify or could be a new feature?

**Comment by yairEO** [comment]
Hi @knasser

This has been asked in an open issue - https://github.com/yairEO/tagify/issues/186

I will make this feature soon, just need to think of the design and UX parts it will have. I'm closing this one because it's a duplicate, so you can subscribe yourself to the other one for updates

**Comment by yairEO** [comment]
See version `3.4.0`

It is now possible to create new tags. There is no "make tag" button, but the typed tag is shown in the dropdown suggestion menu (as a single option) and the user can select it and it will be parsed as tag and an `add` event will be dispatched.

**Comment by knasser** [comment]
Thanks 👍 
would be great if pressing enter would add it directly ..

**Comment by yairEO** [comment]
It can add it on <kbd>Enter</kbd> keypress if you set 

````
dropdown:{
  highlightFirst: true
}
````
