### ISSUE TITLE
Mix Mode with Textarea - using line breaks causes tags on the second line to output as text (not as tags)

### ISSUE THREAD

**Issue by etline** [yairEO/tagify#392]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/degobup/edit?html,js,output

We are using Mix Mode with a text area.  The only way to get the tags and text (mixed) in the order its presented is to get the DOM.originialInput.value .  This works fine however, when there is a line break, every tag after the line break is treated as text.  For example:

By reading this text you can see there is a line break right before CountryDropDown.  CountryDropDown is supposed to be a tag.  The UI renders it as a tag. But the output from tagify.DOM.orginalInput.value is this:

```
[[{"id":100,"value":"IF","title":"IF","style":"--tag-bg:#2bb9e4;--tag-text-color:white;margin:3px","prefix":"@"}]][[{"value":"Name date","style":"--tag-bg:#36D17B;--tag-text-color:white;margin:3px","prefix":"#"}]]= '123' [[{"id":101,"value":"THEN","title":"?","style":"--tag-bg:#2bb9e4;--tag-text-color:white;margin:3px","prefix":"@"}]]CountryDropdown = 'USA'
```

- **What is the expected behavior?**
This should render all tags after the line break as tags.  Is there another way to get this data out mixed tags and text in the correct order and with valid tags?
- **What is happening instead?**

- **What error message are you getting?**

**Comment by yairEO** [comment]
Are you saving the newline also in your database? maybe the string isn't being saved or sent back as-it-was in the textarea's value.

**Comment by etline** [comment]
Well I’m not even getting that far.  I have a routine that parses the tags but when it gets to that new line the tags are just plain text.

**Comment by yairEO** [comment]
I will check in the upcoming days, I promise

**Comment by dion** [comment]
I tested this too and it looks like when you add new lines into a textarea control, the tagify library is creating <div><br></div> with no attributes. maybe it should be `\n` instead of <br> tag since it's a textarea element? and maybe ditch the wrapping div tags? maybe the parser isn't stepping into the child element causing an early termination.

**Comment by yairEO** [comment]
It's chome that is creating `div` elements automatically when you click <kbd>enter</kbd>:

https://stackoverflow.com/q/18552336/104380

I will fix this (hopefully) today, I already started working on it

**Comment by yairEO** [comment]
I worked on the problem for many hours and I think I have a working solution which is to my satisfactory. I will hopefully publish a fix tomorrow

**Comment by yairEO** [comment]
ok try now using `tagify@3.3.0`
