### ISSUE TITLE
Cannot leave single-select input after choosing a value in Mozilla Firefox 72.0.1

### ISSUE THREAD

**Issue by thetuningspoon** [yairEO/tagify#394]
I cannot leave the single-select input after choosing a value in Mozilla Firefox 72.0.1 (Mac), either with the tab key or mouse. The cursor keeps jumping back to the input.

It actually appears to go into some sort of add event loop--sometimes thousands of add events are triggered.

This can be observed on the demo page.

I was previously using Tagify 2.31.2 and this wasn't an issue.

**Comment by yairEO** [comment]
I am looking into it, thanks!
