### ISSUE TITLE
Please, make insensitive case for compare entered value with mapValueTo

### ISSUE THREAD

**Issue by 7iomka** [yairEO/tagify#398]
As I understand, `mapValueTo: 'some',` will suggest me with placeholder value of prop named as `some`.
I expect that when I write in any case (upper or lower), the plugin converts the entered value to a one of cases (upper or lower) both values and compare it. In fact I see that - if I enter a value that is not in the correct case, the placeholder suggestion is not displayed! Although dropdown suggestions is normally displayed.
Is there a fix for this?

**Comment by yairEO** [comment]
`mapValueTo` is only for mapping which text (which tag property value) will be printed *inside* the tag. it's presentational-only and does not affect search filtering logic.

Anyway, it seems to be working well, as always:

https://yaireo.github.io/tagify/#section-extra-properties

Try to type a country name with uppercase letters and see the search works as expected.
