### ISSUE TITLE
send selected tags with ajax

### ISSUE THREAD

**Issue by sajadabasi** [yairEO/tagify#4]
Hey,
How can I send tags with ajax?
Thanks.

**Comment by yairEO** [comment]
Googling `send input ajax` gives these results:

http://stackoverflow.com/q/6890533/104380
http://stackoverflow.com/q/2604874/104380
http://stackoverflow.com/q/21662836/104380

Just send the input element's data to the server. 
I think the links above clarified how to do this.
This is outside the scope of this code (obviously)
