### ISSUE TITLE
Object doesn't support property or method 'findIndex'

### ISSUE THREAD

**Issue by criocere** [yairEO/tagify#40]
Hello,

I have the following error on IE11
"Object doesn't support property or method 'findIndex'"

In the following line in jquery.tagify.min.js
function(t){var e=this.value.findIndex(function(e){return t.toLowerCase()===e.toLowerCase()}

It's seem  that IE11 doesn't support findIndex
https://stackoverflow.com/questions/41938036/object-doesnt-support-property-or-method-findindex-ie11-javascript-issue

Maybe you do not support IE11?

Thx in advance

**Comment by carbontwelve** [comment]
You will need to use a polyfill or something like babel to ensure the compiled javascript will work on the endpoints you define.

**Comment by yairEO** [comment]
which version are you using?

I changed that line about 2 weeks ago. [Here's the commit](https://github.com/yairEO/tagify/commit/efacb252edc0a96fc8c1883345ac0b494871013d)
