### ISSUE TITLE
Hide Dropdown on Scroll

### ISSUE THREAD

**Issue by charlesr1971** [yairEO/tagify#400]
I think it would be great, if another method could be added:

`dropdown.hide()`

Then we could manually control when the whitelist dropdown is displayed. For instance, I prefer to hide library dropdowns, when the user is scrolling the page. The reason for this, is that the dropdown is appended to the body rather than the nearest parent container. The result, is that the dropdown becomes unattached positionally from its tag input, when the page is scrolled. To me, this looks a bit messy, although I guess this is a subjective UX matter. 

An alternative idea would be to add a setting called:

`contextDropdown: [element[htmlElement]]`

The value of this setting would represent the container that the drop down should be appended to. By default this would be the **body**

And possibly a linked setting called:

`contextDropdownPosition: [{x:[numeric],y:[numeric]}] `

This would allow us to position the dropdown within its parent container. This would only take affect, if the **contextDropdown** is set to something other than its default. 

Anyway, thanks for creating such a great library.

**Comment by charlesr1971** [comment]
I’ve just found a work around:

```
element.addEventListener(“scroll”,function(){
    tagify.dropdown.hide.call(tagify);
});
```

It might be good though, to allow the dropdown to be appended to a container other than the body. In fact, you wouldn’t need the:

`contextDropdownPosition: [{x:[numeric],y:[numeric]}]`

Because, you could position it relative to the input, as you are currently doing. The only difference, is the position would be relative to container rather than the body. 

So, perhaps, just:

`contextDropdown: [element[htmlElement]]`

Is required.

**Comment by yairEO** [comment]
> The dropdown *should* be appended to the body because this ensures it will be visible and not get accidentally "clipped" if the parent element of Tagify has `overflow:hidden` (or `auto`).

You can re-position the dropdown when `scroll` event happens.<br>

   tagify.dropdown.position.call(tagify)

**Comment by charlesr1971** [comment]
Fair enough...
