### ISSUE TITLE
invalid duplicate tag is not validated when the original valid tag is removed

### ISSUE THREAD

**Issue by keksa** [yairEO/tagify#401]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/dixevoxaji/1/edit?html,js,output - just remove the first "aaa" tag

### Explanation
- **What is the expected behavior?**
When there are 2 duplicate tags and the first (valid) tag is removed, the second tag should change from invalid to valid.

- **What is happening instead?**
The second tag stays invalid.

- **What error message are you getting?**
none

**Comment by yairEO** [comment]
Awesome bug! I will brush it at once.
