### ISSUE TITLE
replaceTag Method update tag with 'undefined'

### ISSUE THREAD

**Issue by Waad-3** [yairEO/tagify#403]
Hi, I have an urgent issue appreciate your help.

I'm trying to updated the tag value using replaceTag method as below:

`tagify.addTags('123');
tagify.replaceTag(tagify.getTagElmByValue('123'), 'John');`

the UI get the tag updated but with 'Undefined'! I want it to show 'John'
I didn't get what the second parameter mean "tagData" 

How can I update a tag with a string? Thank you

**Comment by yairEO** [comment]
`replaceTag` method's `tagData` argument must be of type *Object*.

`John` is *String*. Try `{value:"John"}`
