### ISSUE TITLE
Tag doesn't get added if cursor is not at the end of the text

### ISSUE THREAD

**Issue by nammpham94** [yairEO/tagify#404]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/capetiwecu/5/edit?html,js,output

### Explanation

- **What is the expected behavior?**
In `mix` mode, when a tag is selected from the dropdown of items from a whitelist, the tag should be added, even if the cursor has moved from the end of the text (this may be caused by human error). This was the behavior from a previous version (v2.22.3).

- **What is happening instead?**
The tag does not get added, even after moving the cursor back to the end of the text. The user needs to delete the value and prefix for the tag, and attempt to add the tag again.

- **What error message are you getting?**
![image](https://user-images.githubusercontent.com/15674259/72926508-2bb5cc00-3d1a-11ea-8a65-0a7249f4d15e.png)
`Uncaught DOMException: Failed to execute 'splitText' on 'Text': The offset 4294967295 is larger than the Text node's length.`

**Comment by yairEO** [comment]
What cursor? do you mean `caret` and you accidentally say `cursor`?

**Comment by nammpham94** [comment]
> What cursor? do you mean `caret` and you accidentally say `cursor`?

Yes, sorry, that is what I meant.

**Comment by yairEO** [comment]
I will publish a fix very soon, i'm gather a bunch of other fixes into a new minor version bump
