### ISSUE TITLE
Wrong behavior of replaceTag method

### ISSUE THREAD

**Issue by Waad-3** [yairEO/tagify#405]
Hello,
I'm using `replaceTag` method inside add event as below:
`tagify1.on('add', function(e){
        tagify1.replaceTag(tagify1.getTagElmByValue(e.detail.data.value), {value:'John'+counter++, id:e.detail.data.value});
console.log(tagify1.value)
`

What I'v been facing the last 2 days is a very strange issue, `replaceTag` replace the tag with `John1` and `John2` and so on very well. But when printing `tagify1.value` each time I add a tag it replace the first value of the array as you see in the schreenshot

[
![Screenshot from 2020-01-25 15-25-27](https://user-images.githubusercontent.com/32552245/73121061-f8c44000-3f86-11ea-93dc-9a273efeba16.png)
](url)

the array values should be like : 
```
0: {value: "John1", id: "1"}
1: {value: "John2", id: "2"}
2: {value: "John3", id: "3"}
```

and because of this. `on remove`  has wrong `e` value.
**Note: I have the same exact code in an online editor and it works PERFECTLY. I don't know if there's something in my project that could contradict with your lib!**

I really appreciate your help with me on this. 
Thank you

**Comment by yairEO** [comment]
I've re-written the `replaceTag` method yesterday and will release a new version today/tomorrow

**Comment by Waad-3** [comment]
oh so glad to know that! waiting for your update :pray:

**Comment by yairEO** [comment]
Ok, try now with `tagify@3.3.0`

**Comment by Waad-3** [comment]
Upgraded to `tagify@3.3.0` but I got this gulp error 
[
![Screenshot from 2020-01-26 10-55-12](https://user-images.githubusercontent.com/32552245/73132319-af2d3100-402a-11ea-9442-a03e526f3288.png)
](url)

**Comment by yairEO** [comment]
Very bizarre. I don't get any error and the code is fine also.

Maybe you have different dependencies versions than I (maybe globally installed `gulp-sass` which is using `"node-sass": "^4.8.3"`

Why are you running Gulp to compile the code, may I ask? (and not use it via NPM)
