### ISSUE TITLE
Possibly xss?

### ISSUE THREAD

**Issue by noahzgard** [yairEO/tagify#406]
## Prerequisites

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed

### Demo Page
[https://i.imgur.com/YoIQj0B.png]()

### Explanation

- It should sanitize value

- Value could be passed to tag title without sanitizing

- No errors

**Comment by noahzgard** [comment]
'\<> onclick=" onclick="javascript:alert('hello_there');"

This text could be run in browser

**Comment by yairEO** [comment]
If you want to sanitize content then do it on the server
