### ISSUE TITLE
Is it possible to customise the tag value as appended to query string?

### ISSUE THREAD

**Issue by anaximander23** [yairEO/tagify#407]
I'm using tagify for a search page, and I want the search parameters to be entirely in the query string so that copy&paste and deep-linking will work, and I'd like the resultant URL to be roughly human-readable (or at least not too ugly). I have an autocomplete list being loaded from a REST endpoint that just returns a JSON array of strings, but when I select a tag, it gets added to the query string as an object, so my URL looks like this:

`https://www.example.com/search?searchString=something&tags=[{"value"%3A"foo"}%2C{"value"%3A"bar"}]`

I was hoping for `&tags=foo,bar`; is there a way to customise this when configuring tagify?

**Comment by yairEO** [comment]
Modify it before you update your page's query string to be whatever you wish it to be
