### ISSUE TITLE
Adding tags at startup

### ISSUE THREAD

**Issue by massivespace** [yairEO/tagify#408]
I'm using the React version of Tagify, and I have some issues I can't seem to resolve and thought someone might be able to offer some suggestions.

First, if I pass in value as a prop to the Tags component, it's ignored.  So I can't initialize the list of tags this way.  I added code instead to setTagifyProps() with the list of tags when the list changes, and that works.  However, when I call setTagifyProps, the "add" callback is called for each tag.  I utilize the "add" callback to update my database with the new tags after a tag is added (type and hit enter).  So, this ends up erasing all but 1 tag when it initializes.  The first tag initialized calls the "add" callback, which in turn updates my database with the single tag, which then updates the tags list, which then calls the effect on tagList change, which calls setTagifyProps to set it to only 1 tag, and repeat.  The same thing happens when I add a single tag, hit enter, the "add" callback runs, which adds the single tag to my database, but that triggers the effect, etc, which erases all other tags except the new one.  I just seem to be in a chicken/egg situation.

My question is: what's the proper solution for this kind of use case?  Essentially, the tags need to reflect what is in my database, but when I first load the component, it can take a second to get the database tags list.  The thought was a useEffect() on that list that set the "value" property of the Tags component (following the example project), but this doesn't seem right since it calls the "add" callback, so then I can't use the "add" callback properly.  Any ideas?

**Comment by yairEO** [comment]
I've looked into it, and as it appears, the best solution I can think of is modifying the `componentDidMount` lifecycle method in `react.tagify.js` to:

```javascript
componentDidMount() {
  if( this.props.value )
    this.component.value = this.props.value
  this.tagify = new Tagify(this.component, this.props.settings || {});}
```

when doing `this.component.value = this.props.value` and afterwards initializing Tagify, it will automatically fill tags.

I will release a fix tomorrow. 

---

Regarding your chicken/egg problem, I don't understand this:

> ...which in turn updates my database with the single tag, which then updates the tags list, which then calls the effect on tagList change

After the DB has updated successfully, you should't re-render the component.
Only if it failed to update, you should probably remove the last tag added and give the user some notice, but if it was saved, then why the re-render (*"which then updates the tags list"*)?

**Comment by yairEO** [comment]
Solution has been implemented in the last release, you may update and check
