### ISSUE TITLE
React callbacks using stale data

### ISSUE THREAD

**Issue by massivespace** [yairEO/tagify#409]
### Explanation

- **What is the expected behavior?**
Setting the callback add method to a local function should see the latest Props variable data.

- **What is happening instead?**
The add method only sees the Props variable as the value it was initialized to at component mount time.

- **What error message are you getting?**
No error message, but the code functionally fails.

I have a functional React component as follows:

```javascript
const TagContainer = ({tags}) => {

  const tagifySettings = {
    maxTags: 10,
    ... other settings ...
    callbacks: tagifyCallbacks
  };

  const tagifyCallbacks = {
    add: onAdd,
    ... other callbacks ...
  }

  const onAdd = (e) => {
    console.log("tags Prop is " + JSON.stringify(tags));  // Prints out [] as [] is what is first passed into TagContainer props above.  Always prints out [] when a tag is added, never updates to reflect what "tags" props variable actually is.
  }

  return (
    <Tags settings={tagifySettings} {...tagifyProps} />
  );
}
```

This is a very watered down example of what I'm seeing, but basically the Props value "tags" is an empty array when the component is first mounted.  After this, my database is loaded in external code and passed into TagContainer as tags, but the add callback always shows the list as empty still.  However, if I do something like the following, it prints the expected results:

```javascript
... Same code as above, but in the return section:
  return (
    <div>
      <Tags settings={tagifySettings} {...tagifyProps} />
      <Button onClick={onAdd}>Test Add</Button>
    </div>
  );
```

Clicking the Test Add button runs the same code that should be run from the Tagify callback, but it prints out the latest values of the "tags" Prop as one would expect.

Another thing I tried was to add an effect so that the callbacks would only be set later on, after the "tags" prop updated.  Something like this:

```javascript
useEffect(() => {
    if (tags.length > 0) {
      setTagifySettings((lastState) => ({...lastState, callbacks: tagifyCallbacks}));
    }
  }, [tags]);
```

The idea above was to see if somehow new objects were getting created, and the old callbacks were pointing to out of scope data or something.  When I did this, however, the add callback is never even called.  I verified the settings stored in the Tagify component reflect the callbacks.  It just doesn't appear to be using them, or it's still using callbacks pointing to another location in memory or something.

Is this an issue with Tagify not supporting Functional React components, or a bug?

**Comment by yairEO** [comment]
React is creating a *closure* around:

```javascript
const onAdd = (e) => {
  console.log("tags Prop is " + JSON.stringify(tags))
}
```

so `tags` initial value is encapsulated and in terms of memory access, it does not go to the same place as the `tags` prop, but rather access the *closure* version of the `tags` variable which was copied to another part of the memory.

In your specific example you don't need to access `tags` because everything related to Tagify is already available to you if you access `e.detail.tagify` inside the callback.

If you do however wish to access a prop of `TagContainer` which is not somewhow reflected in your *tagify* component then you could utilize [`useRef`](https://reactjs.org/docs/hooks-reference.html#useref) hook to get away with the *closure* problem:

```javascript
const TagContainer = ({tags}) => {
  const self = useRef({tags})

  useEffect(()=>{
    self.current.tags = tags
  }, [tags])

  const onAdd = e => {
    console.log(JSON.stringify(self.current.tags))
  }

  ...
}
```

**Comment by zilched0** [comment]
Just to say thanks, this post was perfectly timed to help resolve a similar challenge I'd faced passing a reference to the event callback

**Comment by massivespace** [comment]
Thanks yairEO.  I thought it might be a closure issue, but I didn't really understand why calling the same function from a react component's onClick callback didn't do the same thing.  I will admit I don't fully understand the intricacies yet.  I will check out the useRef approach though.

In the end, I added a new state as I couldn't find a way around this.  I set the state in the onAdd callback, then added an effect on that state change, and then sent the newly added tag in the passed in callback for adding a tag.  That seemed to get around the issue.

To clarify my original issue and some other things I tried, I wasn't able to read the "tags" property from a parent component through a passed-in callback, even though the "tags" state was owned by the parent.  So, something like this still showed the initial state of tags (does this make sense in the closure case?):

```
const Parent = () => {
  [tags, setTags] = useState([])

  useEffect(() => {
    // ... Request the tags from the database
    setTags(TagsFromDatabase)
  }, [])

  const onAdd = (newTag) => {
    let newTags = tags
    newTags.push(newTag)
    setTags(newTags)   // At this point, tags was still [], would never reflect TagsFromDatabase unless I called it outside of the Tagify->Callbacks
  }

  return (<TagContainer onAddHandler={onAdd} />)
}

// Then in TagContainer, I simply called onAddHandler from the callback
const TagContainer = ({tags, onAddHandler}) => {

  const [tagifyProps, setTagifyProps] = useState({...initial stuff})
  const [tagifySettings, setTagifySettings] = useState({...initial stuff})

  useEffect(() => {
    // Update the tags when the tags in the database change
    setTagifyProps((lastState) => {...lastState, value: tags})
  }, [tags])

  const tagifySettings = {
    maxTags: 10,
    ... other settings ...
    callbacks: tagifyCallbacks
  };

  const tagifyCallbacks = {
    add: (e) => {onAddHandler(e.detail.data.value)},
    ... other callbacks ...
  }

  return (
    <Tags settings={tagifySettings} {...tagifyProps} />
  );
}
```

**Comment by yairEO** [comment]
I don't see in your example where does `tags` prop is being set on the `<TagContainer>` component. Only the `onAddHandler` prop is set on it.

Can you write down the logic here, break it down to steps so I could understand your thinking behind this.

**Comment by massivespace** [comment]
Sorry about that.  I just forgot to put that in.  I updated the code above.  I just pass in the "tags" state to TagContainer as a prop.  The Parent component sets the "tags" state a second after the component mounts, after pulling the tags in from the database (I left the actual code for that out to simplify).  I do see the Tagify input box update with the tags pulled from the DB, but then when I go to add a tag, the onAddHandler method only sees [] for "tags" at the Parent level.  I hope that makes sense.  I will try to take some time to create a jsfiddle or similar example.

**Comment by yairEO** [comment]
I don't understand the scenario, but did you manage to work it out?
