### ISSUE TITLE
Remote content

### ISSUE THREAD

**Issue by chistel** [yairEO/tagify#41]
Just need to know if the tags can be fetched via ajax

**Comment by yairEO** [comment]
well.. there are two ways:
1. fetch your data and set your input value with it, and only then call `tagify` on the input element
2. init `tagify` on the input element as soon as possible and then use the this method: 
   
    // assuming you are using vanilla Tagify (not jQuery version)
    tagify.addTag("tag 1, tag 2,") // basically just pass the value of the ajax to the `addTag` method.
