### ISSUE TITLE
FYI: CreateReactApp defaults fail to minify React wrapper

### ISSUE THREAD

**Issue by alixander** [yairEO/tagify#410]
With CreateReactApp defaults, I got an error compiling the project when following the instructions for the React wrapper. Just noting here for anyone in the future who comes across this: the wrapper in the node_modules is written in ES6 and is not compiled/minified as other packages are. I fixed this by copying the React wrapper into my src code so it transpiles, but you can also get around it by tweaking your webpack configs.

**Comment by yairEO** [comment]
Can you post the error?

**Comment by yairEO** [comment]
I've just installed fresh `create-react-app` then installed `@yaireo/tagify` and tried Tagify and it works as expected. I get no error after running `npm start` or `npm run build`

**Comment by alixander** [comment]
I couldn't reproduce it with a new createreactapp, I guess mine diverged far enough or it's from an old version of createreactapp. Either way, looks like it's no longer an issue.

Thanks for creating and maintaining this!
