### ISSUE TITLE
Programmatic update of a tag

### ISSUE THREAD

**Issue by knasser** [yairEO/tagify#415]
the more I dig into Tagify the more the ways we think we can use it. 
keep the good work. 
my new question is :  is it possible to change the value of tag programmatically ?
for instance I need to have a function to loop over the tags as change the text by appending a prefix. 
 is that possible?

**Comment by yairEO** [comment]
You can call `tagify.editTag()` and pass a tag DOM element to edit, and its new data, for example:

````
var tagElm = ...
var newData = {
  value: "new value",
  class: "blue",
  id: 123,
  title: "my tag title"
}

tagify.editTag(tagElm, newData )
````

**Comment by knasser** [comment]
This opens the tag for editing I guess.   I mean with update is to change the value of the tag without actually opening it for manual edit.  see here?  am I doing something wrong?
https://jsbin.com/bipasahoba/1/edit?html,js,output

**Comment by yairEO** [comment]
Sorry, I meant to tell you to use the `tagify.replaceTag()` method which accepts the same parameters as the `editTag` method.

**Comment by yairEO** [comment]
assume issue was resolved

**Comment by knasser** [comment]
Yes .. Thank you
