### ISSUE TITLE
Fix tagify.value becoming out of sync with input.value

### ISSUE THREAD

**Issue by schosin** [yairEO/tagify#416]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/joluwumena/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**
`tagify.value` and `input.value` being in sync.

- **What is happening instead?**
When a Tagify is instantiated with a present value in *mixed-mode*, removing a node compares the `__tagifyid` incorrectly. The parameter of `removeValueById` is a string, whereas the compared attribute is of type object.
Additionally, when another tag is added afterwards, the old value is still present while the displayed value seems to be the correct one.

- **What error message are you getting?**
None.

**Comment by yairEO** [comment]
I cannot see the bug, what exact steps should I do to reproduce?

`removeValueById` is very simple and works fine:

```
removeValueById( uid ){
  this.value = this.value.filter(item => item.__tagifyId != uid)
}
```

`uid` is a *String* and `__tagifyId` is also a *String*, I don't know what you mean by:

> removing a node compares the __tagifyid incorrectly

**Comment by schosin** [comment]
When I open the demo page, remove the tag "two" and add the tag "one" (@ prefix), you can see the invalid output in the console (I use the browser console). See comments in the javascript section of that demo page.

The following code within the filter callback of removeValueById:
`console.log({ itemId: item.__tagifyId, itemIdType: typeof item.__tagifyId, removedId: event.detail.tag.attributes.__tagifyid, removedIdType: typeof event.detail.tag.attributes.__tagifyid })`
results in the following log:
`Object { itemId: "17034dac628", itemIdType: "string", removedId: __tagifyid="17034dac628", removedIdType: "object" }`
That means that the != check will always result true, since string != object

Greetings,
Ken

**Comment by yairEO** [comment]
This should be fixed in the new version coming it in a few minutes

**Comment by yairEO** [comment]
fixed
