### ISSUE TITLE
Not correct display tags on dublicate and existing text

### ISSUE THREAD

**Issue by padhie** [yairEO/tagify#419]
Hello,
i use the jquery plugin on a textarea and have a problem from existing text.

On a clear content i can insert tags pretty fine 
![image](https://user-images.githubusercontent.com/2571550/74275255-d61a8100-4d13-11ea-9b6f-289d7b823a7a.png)
but if i have a existing text and apply the plugin in the textarea just the first tag display fine, the rest are broken 
![image](https://user-images.githubusercontent.com/2571550/74275321-f64a4000-4d13-11ea-8a8e-4914c2202b35.png)

Settings:
```
$('#form_text').tagify({
                whitelist: generateWhitelist(),
                skipInvalid: true,
                mode: 'mix',
                pattern: /%/,
                enforceWhitelist: true,
                duplicates: true,
                dropdown : {
                    enabled: 1,
                    position: "text",
                    highlightFirst: true
                },
            });
```

If i remove the `duplicates: true` it will be pretty on existing text but i need the duplicate adding the same tags.

Is this an bug in the Plugin or maybe i forgot a parameter to fix this problem?

best regards
Padhie

**Comment by yairEO** [comment]
Try now with new version `3.5.0`

**Comment by padhie** [comment]
The Problem seams to be resolved. i cant resproduce the error with the Version 3.5.0
Thanks <3
