### ISSUE TITLE
Any reason why it's not using normal HTML markup?

### ISSUE THREAD

**Issue by Swennet** [yairEO/tagify#42]
I found this from the StackOverflow question, and I think it really is the best plugin for tagging out of the list.

But why is it not using normal HTML elements? I think that would make this plugin perfect.

**Comment by yairEO** [comment]
Thank you very much.

What does it matter to you, if I may ask, that I chose custom names for HTML tags?

**Comment by Swennet** [comment]
To me it seems like a useless feature, with the price being possible incompatibility with some older browsers.

**Comment by yairEO** [comment]
For this script to even work on older browsers, you would need to first load a script which will extend the old browser's lack of support for methods used by my script (ES5 methods), for example, a script like [Modernizr](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills).

So, it will also enable the use of custom html elements (tags) anyway, so there wouldn't be any problem in the first place
