### ISSUE TITLE
Control + Z is adding tags visually but not programmatically

### ISSUE THREAD

**Issue by ahmetkoprulu** [yairEO/tagify#420]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

Bug can be reproduced on mix part of the demo page in code page.

### Explanation
Note: I am not sure is it good place to mention but there could be option to disable undo feature for input or event maybe disabled by default. Since tagify is managing all the input event I could not find a way to access to pressed key to prevent default undo behaviour. If there is one i will be appreciated to get some help.

- **What is the expected behavior?**
When pressing control + z I am expecting to fill also tagify.value array and all related attributes. Also, maybe trigger add/remove event and callback.

- **What is happening instead?**
What is happening is that tags are not being added to tagify.value and only input event is being triggered. 

In my case, I am using whole text to transform it in different format but when I undo tags they are becoming like {{undefined}} rather than {{tag}}.

This is the initial state of mix input.
<img width="507" alt="issue1" src="https://user-images.githubusercontent.com/31247645/74310508-6b525f80-4d7e-11ea-9827-3434a26cb74a.png">

I am deleting until the last tag  with backspace and tag is also removed as expected.
<img width="506" alt="issue2" src="https://user-images.githubusercontent.com/31247645/74310562-81f8b680-4d7e-11ea-9c6d-f0aa18ca16c8.png">

Now, I am undo the removed tag which is "Homer simpson" but it is not added to tags.
<img width="508" alt="issue3" src="https://user-images.githubusercontent.com/31247645/74310664-be2c1700-4d7e-11ea-8eb0-0909aa306b6f.png">

This is how it looks like visually.
<img width="389" alt="issue4" src="https://user-images.githubusercontent.com/31247645/74310829-19f6a000-4d7f-11ea-8f77-ea01dabf19fb.png">

- **What error message are you getting?**
No error message.

**Comment by yairEO** [comment]
I was working on a fix, it required a huge re-design of some aspects in Tagify just to deal with redo/undo... it's complex. I will release a version very soon after I am done testing all the million different scenarios which I haven't had time to write tests for since it would have taken me weeks

**Comment by yairEO** [comment]
This has been fixed on that last update `v3.5.0`
