### ISSUE TITLE
handle remove tag with backspace 

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#422]
I am trying to remove a tag from the database as well and so that I checking the remove tag event but I found something wrong. Like

I have this callback

```
callbacks: {
    add: console.log,  // callback when adding a tag
    remove: console.log   // callback when removing a tag
}
```

and this on event as well:

```
tagify.on('remove', function(e){
   console.log("onRemoveTag:", e.detail, "tagify instance value:", tagify.value)
})
```

problem is like when I press backspace to delete the tag it does not trigger the above events. And when I press "x" (cross)  to remove tag then it works.

And I check `removeTag` function you use `setTimeout` when remove tag with Backspace. So maybe due to that SetTimeOut, it doesn't work. 

So can you please help me to help this issue.

**Comment by singh-vikramjit** [comment]
Can i use this kind of typehead 

![typehead](https://user-images.githubusercontent.com/45350698/74661211-cd083480-5197-11ea-8b06-14fc0d15a96d.png)

In mix content 

![mix](https://user-images.githubusercontent.com/45350698/74661209-cc6f9e00-5197-11ea-9516-66c5d7a8b51f.png)

Please let me know.

**Comment by yairEO** [comment]
Regarding first question - Are you using Tagify in *mix-mode*? if so, I don't see what use you have for listening to "add" and "remove"  because you need to update the DB with the **whole** value of the, mixed with tags & strings, and not just the tags, so you should listen to the "input" event probably, and also have it debounced, so you won't update your DB too frequently. 

Regarding second question, no you cannot use autocomplete in *mix-mode*

**Comment by singh-vikramjit** [comment]
Thanks @yairEO for your response.  

Yes, I am using Tagify in mix-mode and the thing is like I want to save every tag in the database and it can be achieved in the "tagify.on('add', function(e){})" event which fire after tag is created but when I try to remove it from DB then the thing is "tagify.on('remove', function(e){})" only trigger when we delete tag from the "x"(cross) button then I can remove it from DB but if I remove tag with backspace then it does not trigger the "tagify.on('remove', function(e){})" remove method.

**Comment by singh-vikramjit** [comment]
And @yairEO I also notice one thing that I can not enter space while creating a tag in "Mix-mode".

Like I press "#Tagify js" and press enter to create only "#tagify" is created as a tag. In other examples space is working fine and if you look in below screenshot the preset set value having space.
![mix](https://user-images.githubusercontent.com/45350698/74724933-650c2980-523d-11ea-86bc-5d12e936aa1d.png)

**Comment by yairEO** [comment]
@singh-vikramjit - can you open a separate issue for the "create new tag" problem you are facing?

**Comment by singh-vikramjit** [comment]
Yes sure, I will create a separate issue for create tag issue. and what do you think about my first question?

**Comment by yairEO** [comment]
@singh-vikramjit - I will fix the "focus" and "blur" now and publish a new version

**Comment by eugenetraction** [comment]
@yairEO I stumbled into the same issue with backspace not firing "remove/change" event. As you suggested, I was going to always use "input" event to have the latest value. I'm not sure which value it is, but `tagify.DOM.originalInput.value` seems to be it. It does emit new value on Backspace tag removal... but it does not emit new value on new tag add... 

I think "remove" event should fire when Backspace removes the tag. As well as `tagify.DOM.originalInput.value` should include newly added tag.

Ideally "change" event would fire when input change in mixed mode. So we have both the string and tag values available on every change.

(I'm currently listening to 'input' and using timeout to wait for `tagify.value` to reflect the changes.)
