### ISSUE TITLE
textContent does not contain tags wrapped in mixTagsInterpolator

### ISSUE THREAD

**Issue by spaceemotion** [yairEO/tagify#424]
I would like to use tagify as a template editor. Tags are wrapped in `{{` and `}}`. Whenever the value changes, I would like to get the full string - tags plus mixed content - , instead of a list of all tags used as objects.

This is my current config:

```js
{
  whitelist: [
    'user_name',
    'client_name',
    'product_name',
  ],
  duplicates: true,
  enforceWhitelist: true,
  mixTagsInterpolator: ['{{', '}}'],
  pattern: /{{/,
  editTags: false,
  mode: 'mix',
  dropdown: {
    classname: 'color-blue',
    enabled: 0,
    maxItems: 5,
    position: 'text',
    highlightFirst: true,
  },
}
```

Adding Tagify to an existing input (with value `lorem {{user_name}} ipsum`) shows the tags correctly mapped, but my `input` listener only gets `lorem user_name ipsum` back, instead of `lorem {{user_name}} ipsum` (under `event.details.textContent`).

Is this an error or something I am missing in using this library? Thanks in advance!

**Comment by yairEO** [comment]
What is your use-case for the mix-mode `input` listener?

**Comment by spaceemotion** [comment]
I have a text field that is used to edit templates that have a value like so:

```handlebars
Dear {{ user_name }}, 
{{ product_name }} just launched.
```

If I put that into tagify, I would like to have the tags replaced and be able to add additional ones (like `client_name`) from the dropdown / whitelist.

When I'm done editing the text, I'd like to get the full text, with the tags re-interpolated like so:

```handlebars
Dear {{ user_name }}, 
{{ product_name }} was just launched by {{ client_name }}.
```

The reason for using the input event is that I am using Vue and somehow need to be notified of any change in the input.

**Comment by yairEO** [comment]
I've made considerable changes for an upcoming release, and it will include triggering a `change` event on the "original" input, and this will be perfect in your situation where VUE can bind to the input and detect changes, and act.

it should be released within a day or two

**Comment by spaceemotion** [comment]
sweet, I'll wait til then, then. Cheers!

**Comment by yairEO** [comment]
released version `3.5.0`, please let me know if issue persists

**Comment by spaceemotion** [comment]
Thanks for the new release, I haven't had the time to try this out yet. Will see if I can take a look at this today or tomorrow.

**Comment by akshaygolash** [comment]
@yairEO , Thanks for this powerful JS library, With the recent version of tagify I am still not able to get the input back from the component. What I mean by that is -
1) My input was Hello [[JACK]]  - Which displayed correctly on the text area with JACK being the tag to be displayed
2) When I changed my input to Hello [[JACK]] and [[JILL]], It did display correctly in the text area, However, when I want to save it to the DB I would expect the final output to be like this -
"Hello [[JACK]] and [[JILL]]" but what I see is this "Hello JACK and JILL"

Any idea what I am missing here? Any help is appreciated.

**Comment by yairEO** [comment]
@akshaygolash - What do you mean by

> ..but what I see is this "Hello JACK and JILL"

"see"? see where? you must be extremely specific here explaining this step of "seeing" things
