### ISSUE TITLE
Space between tag text is not working while creating a tag in Mix-mode

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#425]
@yairEO I notice one thing that I can not enter space while creating a tag in "Mix-mode".

Like I press "#Tagify js" and press enter to create a tag but only "#tagify" is created as a tag. In other examples space is working fine and if you look in below screenshot the preset values having space as well.
![mix](https://user-images.githubusercontent.com/45350698/74817377-145c0580-52fd-11ea-857d-689c1f6e6b7f.png)

But when I try to enter a space while creating a new tag it does not work.

And one more thing want to tell you that "**focus**" and "**blur**" events are also not working in **_mix-mode_**

**Comment by yairEO** [comment]
I will try to work on this today

**Comment by singh-vikramjit** [comment]
Thanks @yairEO I am waiting for this.

**Comment by yairEO** [comment]
This is more complex than I thought, both in terms of coding it and also UX.

I think a better solution would be to allow the user to type whatever and then select which part of the text is wished to become a tag and then, through some action, convert that selection into a tag.

**Comment by singh-vikramjit** [comment]
Hi, @yairEO Thanks for your response. I will check the focus and blur and what about **autocomplete in mix-mode** are planning to check it and my question is still open and unclear that when we **remove a tag with backspace** why it does not trigger the remove event or callback.

**Comment by yairEO** [comment]
now an event is fired when deleting tags without the (x) button (there can be many ways to delete them via the browser)

**Comment by singh-vikramjit** [comment]
can you please tell me the name of the event which is fired when deleting tags without the (x) button.
