### ISSUE TITLE
Readonly with removing added tags option

### ISSUE THREAD

**Issue by dandys** [yairEO/tagify#426]
I'd like to add new tags programmatically only (user clicks on some fields and then I add suitable tags to field handled by tagify), but user will be allowed to remove already added tags as well.

When I use readonly, user can't add new tags by entering some text in tagify's field (which is desired), but he can't remove tags too (but he should).

How can I achieve this with tagify?

**Comment by yairEO** [comment]
I don't understand, when can the user add tags? always? does it uses the same field to add them? which tags exactly *should* and which *shouldn't* be allowed to delete?

**Comment by dandys** [comment]
Take a look at this example: https://jsbin.com/nedecusame/3/edit?html,css,js,output

I need to add tags by clicking on the buttons ("Tag 1", "Tag 2", "Tag 3") only. User can't type into the input and add tags this way, because I set "readonly" attribute (and that is desired behaviour). However, I need to allow user to delete added tags, but I can't do it with "readonly".

So how can I block typing in input by user (to prevent adding tags) and allow to delete tags (by clicking on "x" mark near the tag)"?

**Comment by yairEO** [comment]
You don't need to set "readonly" on the tagify for this. You can just disallow editing tags and hide the input element:

https://jsbin.com/xunapubeza/1/edit?html,css,js,output

---

`readyonly` means the user cannot do **anything** to the tags - they are "locked".

### The demo in this comment shows what you want:
1. disable editing tags
2. disable the input field which allows to enter new tags

**Comment by bekanur98** [comment]
@yairEO  By double clicking you can edit your added tags, I think it's bug or I have no idea (
