### ISSUE TITLE
Mix-mode - all previous consequent tags are deleted on backspace

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#430]
Hi @yairEO, I notice one more issue.

When I add two tags in mix-mode without entering a space between tag or any other text and when I press backspace then it removes the whole content of the input.

![two_tags](https://user-images.githubusercontent.com/45350698/75173698-91d5aa80-572f-11ea-93ae-47d13bb6489c.png)
Like in the above image I added "#tag1#tag2" and when I press backspace it clear the whole input.

**Comment by yairEO** [comment]
Why did you not follow the issue template? 
I cannot reproduce this bug. Which browser are you using?

**Comment by singh-vikramjit** [comment]
It is not a browser issue it causes because of a custom template. 

https://jsbin.com/rinapunete/edit?html,js,output

if I commented the template code then everything works fine. Can you please suggest me the best way to use the template.

**Comment by singh-vikramjit** [comment]
@yairEO I notice one thing now that in my above comment I remove the "x" (cross) button from the template so that I can only remove the tag with backspace.
and I just commented on my template code and then use the default template and i use CSS property "display:none" to hide that button and then I again face the issue.

https://jsbin.com/lujuwokase/edit?html,css,js,output

is it mandatory to have that cross button on tag template can you please check.

**Comment by yairEO** [comment]
I will check
