### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by stevecookms** [yairEO/tagify#431]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/zubitonasa/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**

Would work like Chrome, etc

- **What is happening instead?**

In running in IE11, after the page loads and you add tags, you get a JS error.  I have added the polyfills js file before the tagify script.

- **What error message are you getting?**
![Annotation 2020-02-24 122213](https://user-images.githubusercontent.com/20538795/75175446-57a0e480-5700-11ea-94d7-2f6e2b6871a2.png)

**Comment by yairEO** [comment]
I will fix it tomorrow
