### ISSUE TITLE
Display prefix in tags

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#434]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/zemixuluzu/edit?html,js,output

### Explanation

- **What is the expected behavior?**
When I add "#" as a prefix in tag template to display the tag as "#tag".

- **What is happening instead?**
 I face a strange issue. when I create a tag or two tags and the press space or any other key and then press backspace the suggestions dropdown position is very strange.

- **What error message are you getting?**
For better insight, I attached a screen recording so you can see the behavior.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45350698/75526239-ac4ea300-5a11-11ea-952c-f7645abd4f8e.gif)

**Comment by yairEO** [comment]
This is a tricky bug, BUT you can easily avoid it by using CSS instead of re-writing the template:

```css
.tagify__tag-text::before{
  content:'#';
}
```

[demo page](https://jsbin.com/quhexoc/edit?css,js,output)

**Comment by singh-vikramjit** [comment]
Thanks @yairEO, and should I create a new ticket for the "auto-complete in mix-mode". So that you can see that this thing also need your consideration.

**Comment by yairEO** [comment]
Yes you can create a new ticket for that, thanks
