### ISSUE TITLE
Remote ajax call delay

### ISSUE THREAD

**Issue by Rudy-vgs** [yairEO/tagify#435]
Hey !

I use this method to retrieve a list of tags from my API. 
[https://github.com/yairEO/tagify#ajax-whitelist](https://github.com/yairEO/tagify#ajax-whitelist)

Is there a way to prevent sending a new request every time the user writes a letter but only after he has finished typing ? (like an option "delay: xx" or a new event ) ?

Thanks

**Comment by yairEO** [comment]
You need to research the term "debounce" (*not* `throttle`) and how to implement it in javascript for `input` events. 

Here are 2 demos I've found for you:

https://codepen.io/jpkempf/pen/MbePGB
https://codepen.io/wonism/pen/dXgAxE

They have everything you need to understand how this simple trick works & implement it in your code.
