### ISSUE TITLE
ie11 style tags

### ISSUE THREAD

**Issue by dion** [yairEO/tagify#436]
Hi, I want to be able to override the style="--tag-bg:#color" property but ie11 doesn't support this syntax. any suggestions?

**Comment by yairEO** [comment]
Manually override only the *CSS selectors* which are using it with your desired color.

Alternatively, if you are using SCSS in your project, you can create a variable `$tag-bg` and assign it your desired color, and clone Tagify's `SCSS` from from the ['./src`](https://github.com/yairEO/tagify/blob/master/src/tagify.scss) folder to your project and include it.
