### ISSUE TITLE
Allow async transformTag

### ISSUE THREAD

**Issue by jaschaio** [yairEO/tagify#437]
I am using Tags like `{ id: '273275', value: 'Tag Name' }`. But on the server side tags are only stored as IDs. So initially I might only pass an `id` to tagify. I could use `transformTag` to request the value from the server (if it is not already present in state) but using a `transformTag` that returns a Promise breaks tagify.

Would be nice if using async methods for `transformTag` would work.

**Comment by jaschaio** [comment]
For anybody requiring something similar: A workaround is  executing `tagify.loadOriginalValues()` once tagify has been initialized so that `tagify.on( 'add' )` events are triggered even for initially passed values. Within the event handler we can than execute async code to turn IDs into values or request them from an API if necessary.

**Comment by yairEO** [comment]
I need to keep support for IE 11 in Tagify, and IE does not support *Promises*, so I don't know how will a cross-browser app that does what you want to do will behave in IE..

Can you describe the flow of the program? what does the user do, what is the initial state, and so on?

Thanks

**Comment by jaschaio** [comment]
Let take a simple application which uses MongoDB in the backend to store documents with tags in the database. An example for such a document while stored in the database is this:

```javascript
{
    _id: ObjectId( "5e5d1c9027d0e07c24d5a177" ),
    title: "Lorem ipsum",
    author: ObjectId( "5d9f0b16f5913887e1cee42d" ),
    createdAt: "2020-02-02T07:18:00.000+00:00",
    comments: [
        ObjectId( "5e5d1c9027d0e07c24d5a178" ),
        ObjectId( "5e5d1c9027d0e07c24d5a179" ),
        ObjectId( "5e5d1c9027d0e07c24d5a17b" ),
    ],
    tags: [
        ObjectId( "5e5d1c9027d0e07c24d2a152" ),
        ObjectId( "5e5d1c9027d0e07c24d3a155" ),
        ObjectId( "5e5d1c9027d0e07c24d4a157" ),
    ],
}
```

As you can see most things are stored as reference to other documents. For example instead of giving tags with names, IDs are given and the tags themselves are then stored in a different collection:

```javascript
// Tag Document
{
    _id: ObjectId( "5e5d1c9027d0e07c24d2a152" ),
   name: "Recipes",
   createdAt: 2019-09-26T08:47:17.000+00:00
}
```

Depending on the context those documents are loaded from the API the "tags" might just resolve to IDs instead of names. So to the values initially passed to tagify might as well only be IDs. For example `[ "5e5d1c9027d0e07c24d2a152" ]`. The app then checks if the tag is already present in state so that it can get the name from state, or it does another API request to load the tag and associated name.

Internally when the user enters a tag given a name an API request is made to load dynamically the whitelist, but tags are always stored as "ObjectIds" instead of objects with ids and names.

Not sure if that makes sense. There are of course other workarounds (like returning documents with already "resolved" documents from the server) which I am actually doing as well in some cases but its not always practical (for example for tag like values that are somewhere deeply nested within those documents)

**Comment by yairEO** [comment]
I didn't really understand this explanation.

### I understand this flow:

1. user starts typing and then you make an ajax call to load a whitelist, while they are typing the whilist gets updated. 

2. The whitelist doesn't contain any IDs but only textual names.

3. When a user selects a name from the list, a tag is added, and in that point you want to use the `transformTag` method to manipulate the tag's data with an ID you will get from another API which give you ID by NAME, and this is happening async.

-----

Since you have a reference to the tag element, you can call the `tagify.replaceTag` method, which accepts two parameters: `tagElm, tagData`

so you can listen to tagify's `add` event and then act on it. You have access to the text of the tag there: `function addTag(e){ e.detail.data }`

**Comment by jaschaio** [comment]
Thanks for trying to be helpful, I really appreciate it. Sorry that my example might not be clear. Let my try once more:

I sometimes have tagify inputs that are initialized with an ID value instead of a human readable name:

```html
<input id='givenIds' type='text' value='["5e5d1c9027d0e07c24d5a178"]' />
```

So form what I understood the `transformTag` method would be perfect for this. If I already have the name somewhere in state I could just do this to display the "name" instead of the ID:

```javascript
// ✅this works
new Tagify( elem, {
  transformTag: function( tag ) {
    tag.id = tag.value;
    tag.value = state.tagsById[ tag.value ];
  }
} );
```

This works, but it doesn't work if I don't have the name somewhere in state but need to do an API request that is async:

```javascript
// ❌this doesn't work
new Tagify( givenIds, {
  transformTag: function( tag ) {
  
    // Make api request to transform given id into name
    apiRequest( tag.value ).then( ( result ) => {
      
      tag.id = tag.value;
      tag.value = result;
      
    } )

  }
} );
```

You can check out the codepen for what I mean: https://codepen.io/jaschaio/pen/abOyYBJ?editors=1010

As I said: A workaround is using the `add` event and doing the async stuff there, but it is somehow less clean as I am emitting `add` events for tags that are already "added" just not properly transformed for end users.

**Comment by yairEO** [comment]
you should do the Ajax matching between ID -> NAME in advance, and map the result into a new array and only then use that Array to inject Tagify with the initial tags, using the method `addTags(tagsArrayWithNamesAndID)`

Then you wouldn't need to do that within `transformTag`

**Comment by jaschaio** [comment]
Maybe you are right, thanks for the suggestion. I will close this but if anybody has a similar need they should find enough inspiration within this issue
