### ISSUE TITLE
How to use tabindex attribute to focus element 

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#438]
Hi @yairEO **tabindex** attribute is not working even if i update the **tabindex** in template from -1 to other value.

can you help to figure this out?

I create an example you check it.

https://jsbin.com/totonesala/edit?html,js,output

**Comment by yairEO** [comment]
tabIndex to which template?

what are you trying to achieve?

**Comment by singh-vikramjit** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/45350698/75962990-0396bc80-5ec5-11ea-83b6-b7beb754efe7.gif)

Like when we switch between the input field with pressing tab and you can see in the above image that when I press tab on second input it goes to forth input instead of focus on Tagify input and even I change the tabindex in wrapper template from -1 to 3

**Comment by yairEO** [comment]
You shouldn't give tabIndex to any of them. I have no idea why you bother if you want them to get focus by the order they are rendered.
