### ISSUE TITLE
Not working in Edge on Windows?

### ISSUE THREAD

**Issue by vitobotta** [yairEO/tagify#439]
Hi!

I seem to have problems with Tagify in Edge on Windows. I thought it's something with my app but even the demo page at https://yaireo.github.io/tagify/ is not working at all for me. I tried in Virtualbox since I'm on Mac, but it shouldn't make any difference. Is Tagify supposed to work with this browser? Thanks

**Comment by yairEO** [comment]
Just checked on my Edge (windows 10) and all works good except one small bug in the tag's default CSS background which I will fix now

**Comment by vitobotta** [comment]
Thanks for checking. I wonder if it's something related to Virtualbox somehow... Will try with Parallels. Thanks

**Comment by yairEO** [comment]
Let me know
