### ISSUE TITLE
Not able to create a new tag when slimier tag is in dropdown ( in Mix -mode)

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#444]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
there is already a similar issue and you fix it but it doesn't work in **Mix-mode**.
https://github.com/yairEO/tagify/issues/233

### Demo Page

https://jsbin.com/zatadodewo/edit?html,css,js,output

### Explanation

When I trying to create a tag like **test** and there is already a **testing** tag is in whitelist then I am not able to make the new tag even if I remove focus from the highlighted tag which displays is the dropdown and then press **Enter** to make the tag but nothing happens. Please check the below screenshot for better insights

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/45350698/76630435-49e0c100-6540-11ea-8bb2-da130d219588.gif)

**Comment by yairEO** [comment]
What a nice bug, I will fix it today or tomorrow
