### ISSUE TITLE
Unable to write in the area with Edge

### ISSUE THREAD

**Issue by Eblancho** [yairEO/tagify#446]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
I detected the bug on my dev but to make it more easily reproducible, I use the Tagify demo site as an example.

https://yaireo.github.io/tagify/

### Explanation
The bug is rather simple to reproduce:
1. I launch Edge
2. I go to https://yaireo.github.io/tagify/
3. I click in the zone, she takes the focus, then nothing.
4. Cannot enter anything in any field EXCEPT in the "Easy To Customize" section (https://yaireo.github.io/tagify/#section-different-look)

P.S. You're doing a great job with this, keep it up growing :wink:

**Comment by yairEO** [comment]
Please try now with newest version `3.6.3`

**Comment by Eblancho** [comment]
It's working!
There is a small graphic side effect but it might be coming from my side.
![image](https://user-images.githubusercontent.com/16915783/76866808-f2569400-6864-11ea-80e8-f553b70185a8.png)
Thanks for the reactivity
