### ISSUE TITLE
How to disable input

### ISSUE THREAD

**Issue by finaffiliate** [yairEO/tagify#448]
How to disable Tagify input?

**Comment by yairEO** [comment]
With CSS, hide the `.tagify__input` element:

```
.tagify__input{ display:none; }
```

BUT you don't need this script at all if you don't wish to have an input. All you need is just CSS.. you can you Tagify's CSS (just use **same markup** as Tagify generates) or write your own styles & markup.

**Comment by yairEO** [comment]
Another way is to initialize Tagify in `read-only` mode (you can style the tags differently if you wish).

See demo: https://yaireo.github.io/tagify/#section-readonly

**Comment by yairEO** [comment]
Related to issue:
https://github.com/yairEO/tagify/issues/426#issuecomment-589993534

**Comment by EssDevUi** [comment]
another way you can do it by adding 
`{
        userInput: false,

}`
in BasetagifySettings
