### ISSUE TITLE
Get and Set Tags programmatically via JS?

### ISSUE THREAD

**Issue by matthiasballreich** [yairEO/tagify#45]
Hi,

is it possible to set and get tags programmatically via JS like [here](http://sliptree.github.io/bootstrap-tokenfield/#methods)

if not, can you add those functions?

thanks

**Comment by yairEO** [comment]
it is possible to set tags using the `addTag` method (assuming `tagify` is an instance of `Tagify`):

    tagify.addTag('foo'); // add a single tag
    tagify.addTag('foo, bar, bazz') // add multiple tags

and to get tags:

    tagify.value
