### ISSUE TITLE
Suggestions list not showing on focus

### ISSUE THREAD

**Issue by JonathanDinh** [yairEO/tagify#450]
## Prerequisites

- [ x ] I am running the latest version (3.6.3)
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Explanation
Hi,

It looks like this bug (https://github.com/yairEO/tagify/issues/102) is back.
 
In my Vue project, I have set a whitelist in my Tagify object like this:
```
<template>
  <div class="input-group">
    <input type="search" class="form-control"
      id="input-for-tagify"
      :placeholder="$t('search')"
      v-model="searchTerms"
      @keypress.enter="onSubmit($event)"  />
  </div>
</template>

<script>
import Tagify from '@yaireo/tagify';

export default {
... 
mounted() {
    const input = document.getElementById('input-for-tagify');
    const tagify = new Tagify(input, {
      delimiters: ' ',
      whitelist: ['ironman', 'antman', 'captain america', 'thor', 'spiderman'],
      dropdown: {
        classname: 'color-blue',
        enabled: 0,
        maxItems: 5,
        position: 'text',
      },
    });
  },
...
};
</script>
```

When I click inside the input without typing a character, I cannot see the whitelist as expected.

Thanks for your support,

Jonathan

**Comment by yairEO** [comment]
Looking into it Jonathan, thanks for reporting.

**Comment by yairEO** [comment]
Problem was with the `getCaretGlobalPosition` method apperently. fixed & will push soon as I will be releasing a new version combined with many other fixes/improvements.

**Comment by ctdinh** [comment]
Just tested 3.6.10...It is working, thanks!

**Comment by khudoyorrahmatov** [comment]
Hello yairEO,

I am facing the same issue with 4.31.0 today as it was fine a day ago.  Today is my launch day. Please help me out 🙏

<div class="col-md-2">
  <label for="type" class="form-label">Type</label>
  <input name="type" id="type" class="shadow-none form-control" />
</div>

let selectedType = null;
const typeField = document.querySelector('#type');

const typeTagify = new Tagify(typeField, {
    enforceWhitelist: true,
    mode : "select",
    whitelist: ['G1', 'G2', 'G3', 'CLUSTER']
})

typeTagify.on('add', (e) => {
  selectedType = e.detail.data.value;
})

typeTagify.on('dropdown:select', (e) => {
  selectedType = (!e.detail.data.value) ? e.detail.data : e.detail.data.value; // I had to do this as the select value was getting stored in "data" sometimes 🤷‍♂️
})

typeTagify.on('remove', (e) => {
  selectedType = null;
})

**Comment by yairEO** [comment]
@khudoyorrahmatov - I will fix this now
