### ISSUE TITLE
Add space after a Tag and use space key to create a tag in Mix-mode

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#453]
Hi @yairEO 

I want to add a space after a tag when a tag is created.  and also I want to allow space to create a tag in **mix-mode** 
I make an example but facing some issue can you please help to figure this out.

https://jsbin.com/wokojejifo/edit?html,js,output

1. like in add callback I added this code it add the space after the tag but cursor goes at the start of the input.
`tagify.loadOriginalValues(tagify.DOM.originalInput.value + '&nbsp;');`

I also try this way to add the space it adds the `&nbsp;` after the tag but cursor doesn't move cursor always at the end of the tag.
`tagify.DOM.input.appendChild(document.createTextNode('\u00A0'));`

can you please guide me that how can I add one space after the tag when tag created 

2. add use space to make a tag I use this code on key-down callback which works but one problem like when I start typing and dropdown appear an item is highlighted but when I press space it does not pick the highlighted one.
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/45350698/78012332-1629d780-7345-11ea-9105-5c90971d3697.gif)

please let me know the best way to achieve this.

**Comment by singh-vikramjit** [comment]
Hi @yairEO as I mention the use of a spacebar will not pick the highlighted tag but I guess it will fix this #444 problem.

but adding space after a new tag I am not able to find the best solution for it can you please look into the above code

**Comment by yairEO** [comment]
Hi, regarding `(1)`, to add a *space* after a tag was added:

```
tagify.on('add', function(e){
  e.detail.tag.insertAdjacentText('afterend', ' ')
})
```

regarding `(2)`, I've finished and will push this feature tomorrow (hopefully)

**Comment by singh-vikramjit** [comment]
Hi, I check the above thing as well but works the same I told that it adds space but the cursor doesn't move. 

I update the code in this jsbin and also explain you in the image
https://jsbin.com/hotokonexi/edit?html,js,console,output

like when I click on below tag then the cursor moves but if I press backspace instead of removing the space it removes the tags.

and if i create a tag by writing the cursor always at the end of the  tag.
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/45350698/78342050-f7bc1a00-7598-11ea-88c8-e949a7e19ff8.gif)

**Comment by singh-vikramjit** [comment]
Hi, @yairEO first problem still exists that I am not able to add the space and I found one more thing while testing like if you set a space at the end and set the value as predefined value and when you focus on the input and press backspace it removes the last tag instead of removing spacing

**Comment by yairEO** [comment]
you mean the *caret* not "cursor". (*cursor* is your mouse pointer)

Here you go: https://jsbin.com/nicugok/edit?html,js,output


```javascript
tagify.on('add', addNewTag)

function addNewTag(e) {
  var textNode = e.detail.tag.nextSibling;
  
  // add a space
  e.detail.tag.insertAdjacentText('afterend', '\u00A0');
  
  // place the caret after the space
  document
    .getSelection()
    .getRangeAt(0).setStart(textNode, 0)
}
```

**Comment by singh-vikramjit** [comment]
yes, it adds the space and move cursor but when we press backspace after adding a tag instead of removing the space it removes the tag and again if you press the backspace it removes the next tag and so on.

**Comment by yairEO** [comment]
https://rarbgtor.org/torrent/72qa4sb

**Comment by yairEO** [comment]
I see this only happens if there's no text after the last tag

**Comment by singh-vikramjit** [comment]
Hey @yairEO I one small thing which is also similar to error which we face in firefox. I test it in safari yesterday and when we add a tag then the cursor moves at the starting of tag instead of at the end.

**Comment by singh-vikramjit** [comment]
Hi, @yairEO thanks for the new update I test the bug regarding remove the tag instead of space is working fine but the cursor position issue comes back again. it adds the space but doesn't move the cursor. and also this code return an error.

`document.getSelection().getRangeAt(0).setStart(textNode, 0);`

![image](https://user-images.githubusercontent.com/45350698/80208359-51f84a00-8630-11ea-98b0-70d425cc58f3.png)

**Comment by yairEO** [comment]
in which browser is this error? *safari*?

**Comment by singh-vikramjit** [comment]
this error is in chrome and in other browsers error is in different ways

**Comment by singh-vikramjit** [comment]
Hey @yairEO I found something weird in the new version if you open the above example and try to make tag with pressing space is not working now with the previous code.

**Comment by singh-vikramjit** [comment]
Hey @yairEO have you checked above issue 
`document.getSelection().getRangeAt(0).setStart(textNode, 0);`

**Comment by yairEO** [comment]
fixed the demo for you:
https://jsbin.com/puvivuweci/1/edit?js,output

**Comment by phil-warner** [comment]
This is no longer working with 4.26.0 unfortunately. Is there an alternative approach?

**Comment by yairEO** [comment]
@phil-warner - can you be more specific what exactly *"no longer working"*?

**Comment by yairEO** [comment]
@phil-warner - where do you want the dynamically added tags be injected to? middle of a sentence? the end? do you want afterwards that the caret be moved to the end? because this thread's topic is not either of those things :)

**Comment by phil-warner** [comment]
@yairEO I'm inserting the tags at the end of the input, and the sample code places the caret after the added tag (and the default space that get's added along with it).
