### ISSUE TITLE
Unable to remove tag and placeholder question.

### ISSUE THREAD

**Issue by YauKeng** [yairEO/tagify#457]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/yuvuhiroqe/edit?html,js,output

### Explanation
I've added the demo, Steps to reproduce: 
1. Type some word and press enter to add the tag.
2. Click remove button from the tag created.
3. Tag unable to remove.

- **What is the expected behavior?**
Tag should be able to remove by using close button.

- **What is happening instead?**
Unable to remove tag when adding a new tag not from the dropdown list.

- **What error message are you getting?**
No error message.

**Comment by yairEO** [comment]
I cannot help you until you follow the ticket instructions (on this repo) and clone a [jsbin demo page](https://jsbin.com/jekuqap/edit?html,js,output) with your setup

**Comment by YauKeng** [comment]
@yairEO Hi, I've updated the post.

**Comment by yairEO** [comment]
Which browser and device? everything seems to work for me as expected on *Win10/Chrome 80*
