### ISSUE TITLE
Always show suggestions list, or way to trigger showing the suggestion list

### ISSUE THREAD

**Issue by cpury** [yairEO/tagify#46]
First of all, great job on the library. I love the design.

I have a short list of suggestions that I'd like to always show to the user. I set `suggestionsMinChars` to 0, but it seems the suggestion list is only triggered inside `callbacks.onInput`. It would be nice to have this as a custom event or method so we can manually trigger the suggestion list.

Alternatively, you could also add the functionality that if `suggestionsMinChars` is 0, the suggestion list is shown as soon as the input gets focus.

**Comment by chenhoward** [comment]
👍 same thoughts, great job on this library, and would like this feature. Is this actively being worked on?

**Comment by yairEO** [comment]
This is connected to issue #12, where i'm supposed to add support for custom suggestion list. 
There are limitation when using built-in browser lists, as you found out. Custom list requires a lot more
code but it will ensure much better UI and flexibility.

**Comment by cpury** [comment]
@yairEO sorry, I might misunderstand, but I don't see a connection to #12. I just want a custom event I can trigger to open the suggestions list. It should be very simple.

**Comment by yairEO** [comment]
@cpury - it is impossible (as far as I know) to manually show *datalists*.

the connection is that what you are asking is impossible and can only be possible one #12 will be ready
