### ISSUE TITLE
Can't resolve module

### ISSUE THREAD

**Issue by Monokai** [yairEO/tagify#461]
I'm using this code to import your library:

```js
import Tagify from '@yaireo/tagify';
```

This worked fine, but I've just updated from 3.6.3 to 3.6.6 and I'm getting this build error using webpack:

`Module not found: Error: Can't resolve '@yaireo/tagify' in 'myfile.js`

I've reverted back to 3.6.3 for now, but I'd like to stay current. Any ideas how to solve this?

**Comment by yairEO** [comment]
Try now with `3.6.7`

**Comment by quimey** [comment]
Hi!
I'm having similar issues with 3.6.7:
```
Module not found: Error: Can't resolve '@yaireo/tagify/dist/react.tagify'
Module not found: Error: Can't resolve '@yaireo/tagify/dist/tagify.css'
```
Using latest version of tagify (3.6.7):
```
$ grep tagify package.json 
    "@yaireo/tagify": "^3.6.7",
```
Dist folder still not included:
```
$ ls node_modules/@yaireo/tagify/
LICENSE  package.json  README.md  src
```

**Comment by Monokai** [comment]
I still have the same problem with 3.6.7.

**Comment by quimey** [comment]
A temporary workaround is to install this package from github:
```
$ grep tagify package.json 
    "@yaireo/tagify": "github:yaireo/tagify",
```

**Comment by yairEO** [comment]
Here now it's **back** for sure, please install `3.6.8`

**Comment by quimey** [comment]
Thanks for the fast response!
Another question, with the last version I'm getting:
```
├── @yaireo/tagify@3.6.8
├── UNMET PEER DEPENDENCY react@^16.12.0
└── UNMET PEER DEPENDENCY react-dom@^16.12.0
```
It seems that you pinned the react dependency to an older version? (I'm using 16.13.1)

**Comment by yairEO** [comment]
@quimey - Right. damnit. I will just change it to `*` and be done with it. 
don't think hardly anyone uses old versions anyway, so `*` should work for 99%

**Comment by quimey** [comment]
The dist folder is back with 3.6.8, but I don't see the `react.tagify` file there (although it is present in the src folder).
```
Module not found: Error: Can't resolve '@yaireo/tagify/dist/react.tagify'
```
```
$ ls node_modules/@yaireo/tagify/dist/
jQuery.tagify.min.js  tagify.css  tagify.min.js  tagify.polyfills.min.js
```
Any suggestion?

**Comment by yairEO** [comment]
Yeah, another npm update to `3.6.10` :)

**Comment by Monokai** [comment]
Thank you for the quick fixes. 3.6.10 works fine here.

**Comment by quimey** [comment]
Same here, thanks!

**Comment by lns-cop500** [comment]
Same thing happens again when installing 4.17.0. Reverting to 4.16.4 solved the issue temporarily/

**Comment by yungkeatchan97** [comment]
Same thing happens again when installing 4.17.0. Reverting to 4.16.4 solved the issue temporarily.

**Comment by yairEO** [comment]
I see. I will revert, I've made some change in [`package.json`](https://github.com/yairEO/tagify/commit/652877257cd7232fc2a6dd54668d41b54f3eee07) but I think I mis-configured it

**Comment by yairEO** [comment]
Just released [4.17.1](https://github.com/yairEO/tagify/releases/tag/v4.17.1) which should solve the issue

**Comment by VBikashR** [comment]
Just installed and I'm facing with the same issue "Can't find the module /node_modules/@yaireo/tagify/dist/react.tagify

dist folder is missing:
1.react.tagify.js
2. tagify.js
3. tagify.js.map
4. jQuery.tagify.min.js

I'm using:
"@yaireo/tagify": "^4.17.9",
"@types/yaireo__tagify": "^4.17.1",

**Comment by yairEO** [comment]
@VBikashR - change `dist` to `src` in the import URL

**Comment by anungbisa4** [comment]
<img width="989" alt="Screenshot 2024-04-23 at 07 56 14" src="https://github.com/yairEO/tagify/assets/20161471/5ac99e30-9a21-4314-904d-35c4b1b5324e">

 i'm using : "@yaireo/tagify": "^4.24.0",

**Comment by yairEO** [comment]
@anungbisa4 - Your bundler does not seem to process JSX files within the `node_modules` folder.

Since developers probably don't know how to configure rollup/webpack/vite to do that, I guess I will have to revert back to have `react.tagify.jsx` be pre-bundled, which causes it to be bloated because of the lack of tree-shaking that could have been done if you would have bundle it yourself within your app... I will work on it now.

**Comment by yairEO** [comment]
pushed new version: https://github.com/yairEO/tagify/releases/tag/v4.25.0

**Comment by halilcn** [comment]
Hello @yairEO 
I installed v4.25.0 and tried it but there is still an error related to vite build as I guess.

`import {MixedTags} from '@yaireo/tagify/src/react.tagify'`
`"@yaireo/tagify": "^4.25.0"`
![Screenshot 2024-05-11 at 12 42 15 AM](https://github.com/yairEO/tagify/assets/54184509/798d68fb-bcc6-44ab-943b-ac1e7453b485)

I just wanted to use MixedTags component but It took more time than I guess :(
