### ISSUE TITLE
Enforce whitelist for single-value select

### ISSUE THREAD

**Issue by thebrucecgit** [yairEO/tagify#466]
## Prerequisites

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed
- [x] I checked the documentation and found no answer

### Demo Page
https://jsbin.com/zajexuroxe/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**
If you type something that's not in the whitelist (of a single-select input), the value should be removed on blur or on enter (like what happens in multi-value tag inputs). 

- **What is happening instead?**
It's displaying a red border but the value remains. (It also calls "add" and "remove" callbacks even though it's not in the whitelist unlike multi-value tag inputs). 

- **What error message are you getting?**
None - It's not working as intended.

**Comment by yairEO** [comment]
I've made it so, but I would need more time to perfect my solution for this.
I have an idea how to make it behave more like "traditional" `<select>`, so there won't even appear a caret on focus
