### ISSUE TITLE
Tagify in Datatables (only works on first row)

### ISSUE THREAD

**Issue by Organizer21** [yairEO/tagify#468]
I am certain this must be me not knowing what I am doing. But in short, I load Datatables with Ajax content and for some reason, I don't seem to understand how this works. 

Each ROW needs a tags COLUMN to allow a user to select tags, e.g:
`<input name='tags-outside' class='tagify tagify--outside' value='tag1,tag2,tag3' placeholder='Add some tags'> `

When the Datatables ajax is loaded, in my complete function I am triggering Tagify:
`var input = document.querySelector('.tagify'); `

This works, however, it only initializes on the very first row?

**Comment by yairEO** [comment]
You are using `document.querySelector` and not `document.querySelectorAll('.tagify')` and then it will select all your `<input>` elements and *then* you would need to traverse them and apply *Tagify* for each one. 

[Here's a demo showing how](https://jsbin.com/mutixed/edit?html,js,output)

**Comment by Organizer21** [comment]
@yairEO yes, thank you the demo saved the day, much appreciated!

**Comment by Hamaad616** [comment]
or you could just provide the inputs the ids and then return the count from datatable callback and traverse through the input fields but I would prefer the @yairEO solution because it is more efficient with querySelectorAll('.yourInput')
(I know i am a bit late :) )
