### ISSUE TITLE
Type error: this.DOM.input.lastChild is null

### ISSUE THREAD

**Issue by mrpsiho** [yairEO/tagify#469]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
n/a

### Explanation

- **What is the expected behavior?**
It works.

- **What is happening instead?**
I get an error, it does not work.

- **What error message are you getting?**
Type error: this.DOM.input.lastChild is null

TypeError: this.DOM.input.lastChild is null       tagify.min.js:7:10193
    onFocusBlur tagify.min.js:7
    onFocusBlur self-hosted:875

**Comment by mrpsiho** [comment]
I am using it with React. Have tried your Tags component or mine own - I have got same error. My react component renders only 'input' element.

**Comment by yairEO** [comment]
gonna release a new version very soon, hopefully tomorrow, I think it is related to another bug i was fixing

**Comment by yairEO** [comment]
Let me know if it's fixed. it should be. You did not make a demo page nor you specified the conditions to reproduce the bug. closing for now, unless you report it's still happening, with some clarifications on the process
