### ISSUE TITLE
Vue usage?

### ISSUE THREAD

**Issue by DylanC** [yairEO/tagify#47]
Can I use this with Vue JS or do I need to use as a Vue component?

**Comment by yairEO** [comment]
I don't know, as i'm not familiar with Vue, sorry..

This is just a script like any other standalone script. 
How would you use lodash for example?

**Comment by DylanC** [comment]
@yairEO - No idea really. I'm new to Vue. I found this but it doesn't seem to work:
https://github.com/photogabble/tagify-vue

**Comment by concept47** [comment]
For posterity, in case someone stumbles upon this

`yarn add yaireo/tagify`

Then inside your Vue file (just to run a quick test)

`import Tagify from '@yaireo/tagify'`

Inside your Vue lifecycle hook, add the code to activate the input you'd like to try out

    mounted () {
      const tagInput = document.querySelector('#tags'), 
         tagify = new Tagify(tagInput, {})`
    }

you should now be able to play with tagify!

**Comment by yairEO** [comment]
Added VUE support, see #257
