### ISSUE TITLE
The original input is not updated after deleting the last tag in mix mode

### ISSUE THREAD

**Issue by QichenZhu** [yairEO/tagify#470]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/biwukuduve/edit?html,js,console,output

### Explanation
Steps to reproduce:
1) Click the upper input
2) Type #a
3) Press Enter
4) Press Backspace

(Tagify 3.6.10, Google Chrome 81.0.4044.113)

- **What is the expected behavior?**
The original input is empty.

- **What is happening instead?**
The original input is not empty.

- **What error message are you getting?**
None.

**Comment by yairEO** [comment]
Related to another bug which I've fixed, so this will be solved once I deploy the new version today

**Comment by yairEO** [comment]
Please update to `v3.7.0`
