### ISSUE TITLE
Not able to get the input value in IE if use Enter key to make a new line 

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#472]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/merusasuri/edit?html,js,console,output

### Explanation

I found two following issue:
1. I create a complete demo in Jsbin like when you open this jsbin in IE 11 and when you write something and press enter for new-line and then write something and when you click on save button in the console you can check that it returns an empty value and if you test same in other browsers then it works.

2. In (Chrome) when you click on the edit button then you can see that I put that text into the tagify input and focus the input field but when there is a tag at the end then there is no cursor appear and if you click on the edit button where there is a text at the end then the cursor appeared.
In (IE 11) if you do the same thing in IE then cursor goes at the starting of input.

**The first point is the major one please check the share your feedback.**

**Comment by yairEO** [comment]
Thank you very much for taking the time to make the demo!

I see the problem and will deal with it ASAP.

It seems IE11 adds `<p>` wrapping elements when you press <kbd>Enter</kbd>

![image](https://user-images.githubusercontent.com/845031/79803513-c732f900-836a-11ea-93cb-3b7af5567052.png)
