### ISSUE TITLE
Whitelist with color values

### ISSUE THREAD

**Issue by waterboy550** [yairEO/tagify#473]
I have a whitelist setup with values like below. Everything is working, however no colors are coming through for the different elements. Can this be done?

```
whitelist: [  { value:'apple', color:'red' },
              { value:'grape', color:'purple' },
              { value:'banana', color:'yellow' }],
```

I'm looking to add the color to 2 places.
1. to the tags while in the dropdown menu.
2. to the tags after they are selected. 

It looks like I can use the "transformTag: transformTag" example to get the color I want to the selected tags, but how would I go about applying the color to the tags while listed in the dropdown menu?

**Comment by yairEO** [comment]
There are many ways to implement tags colors, one would be to add a `transformTag` setting:

```javascript
var tagify = new Tagify(..., {transformTag})

function transformTag( tagData ){
	if( tagData.color ) 
       tagData.style = "background:" + tagData.color
}
```

Another way is shown in [this example](https://yaireo.github.io/tagify/#section-advance-options)

**Comment by waterboy550** [comment]
This works great once the item is selected, it properly fires the transformTag event and changes the color of the tag. But how do I have the drop down item colored based on the tagData.color value. Is this possible? Here is my drop down setup, can the classname value be set to something that would change the color values possibly?

`dropdown: {
maxItems: 30,
classname: "tags-look",
enabled: 1,
closeOnSelect: true
}`

**Comment by stri8ed** [comment]
You can pass a style attribute with items:

`whitelist: [  { value:'apple', style: 'background-color: red;' } ]`

**Comment by yairEO** [comment]
You can create your own HTML template for the dropdown items (`dropdownItem`) and then use the `color` property as a class name. [Read more in the README](https://github.com/yairEO/tagify#dom-templates)
