### ISSUE TITLE
Stop removing tag on backspace while you are in mix mode

### ISSUE THREAD

**Issue by ShafiqueMalik** [yairEO/tagify#475]
I am using this settings

```javascript
{
     addTagOnBlur: false,
     editTags: false,
     mode: "mix",
     pattern: "",
     backspace: false
}
```

I want to stop deleting tag on backspace press. I used " backspace:false,  and also 'backspace:'edit', " but it still remove tag. Is there any way to stop deleting tags on backspace while we are in mix mode?

Thanks in advance.

**Comment by yairEO** [comment]
I'll work on it today
