### ISSUE TITLE
Wrong value/Unexpected behavior when call removeTag sequently, or right after addTags

### ISSUE THREAD

**Issue by as247** [yairEO/tagify#476]
1. This code will not work, on ui still show 11 and 22
`tagify.addTags(["11","22"]);
tagify.removeTag("11");
tagify.removeTag("22");
`
removeTag not taking effect

2. Run `tagify.addTags(["11","22"]);` first
then run 
`tagify.removeTag("11");
tagify.removeTag("22");`
then `tagify.value` **is incorrect**

![image](https://user-images.githubusercontent.com/2641656/79890478-c01ef000-8429-11ea-90a8-041345470f61.png)

**Comment by yairEO** [comment]
Thanks for finding this bug, will be fixed ASAP!

Also noted to myself to allow removing multiple tags at once using that method
