### ISSUE TITLE
How to preventDefault on keydown event? 

### ISSUE THREAD

**Issue by rubnsom** [yairEO/tagify#477]
Amazing library, I just discovered it and has brought a lot of benefits to my project (: 

I need to add functionality to add assets to a DB when hitting "Enter", however, I haven't found the way to use preventDefault event, I'd appreciate your help!

Kind regards

**Comment by ShafiqueMalik** [comment]
> Amazing library, I just discovered it and has brought a lot of benefits to my project (:
> 
> I need to add functionality to add assets to a DB when hitting "Enter", however, I haven't found the way to use preventDefault event, I'd appreciate your help!
> 
> Kind regards

According to my information, there is no way to preventDefault in this library.

**Comment by yairEO** [comment]
Where do you mean to place the `preventDefault` at?
Can you show some code example?

**Comment by rubnsom** [comment]
Thanks for your quick response. I'm trying to use it in a redirected `keydown` event when the user hits enter. It is a **mix mode** and I don't want to insert a new line, but calling another function instead. `e.detail.originalEvent.preventDefault()` exist, but it doesn't work -- It says that is an Illegal invocation. Hope this helps.
Also I could't use `removeAllTags` method, so I'm using `e.detail.tagify.DOM.input.innerHTML = ''` which is what the method does, not big deal, but would be nice to use it properly.

`const onKeyDown = e => {
    if (isTagActive.current) return
    const {
      originalEvent: { keyCode },
      tagify: {
        DOM: {
          originalInput: { value },
        },
      },
    } = e.detail
    if (keyCode === 13 && value !== '') {
      // e.detail.originalEvent.preventDefault()
      handleAddOption(value)
      e.detail.tagify.DOM.input.innerHTML = ''
    }
  }`

**Comment by yairEO** [comment]
I see. Why couldn't you use `removeAllTags()` method? you didn't explain that mysterious part

**Comment by yairEO** [comment]
## How to preventDefault on ENTER key: ([jsbin demo](https://jsbin.com/goquloc/edit?html,js,console,output))

```javascript
var tagify = new Tagify(input, {
  mode: "mix",
  pattern: '#',
  //backspace: false
})

tagify.DOM.input.addEventListener('keydown', function(e){
  if(  e.key == "Enter"  )
    e.preventDefault()
})
```
