### ISSUE TITLE
[React] value.join() & value.trim() issues when rendering with props from parent component

### ISSUE THREAD

**Issue by rubnsom** [yairEO/tagify#478]
I'm creating a react example (**mix mode**) and I'm loading an initial whitelist array and value in the right format as documentation suggest 
`whitelist = [ {id: "497965f7", value: "Loaf pan"}, {id: "3de12171", value: "10-inch plate"} ]`
`initialValue = "Use [[10-inch plate]] or [[Loaf pan]]"`
 but I'm getting some errors when rendering. 

**Sending initialValue as string, `value.join()` is crashing**

<img width="807" alt="Screenshot1" src="https://user-images.githubusercontent.com/24323868/80037834-61598500-84c2-11ea-8590-cf2513eb8535.png">

**Sending initialValue as array, `value.join()` works and  `value.trim()` crashes at some point**
**Is there something I'm missing to make it work?** 

<img width="678" alt="Screenshot2" src="https://user-images.githubusercontent.com/24323868/80037836-61f21b80-84c2-11ea-83ac-00c5a3acabd6.png">

<img width="691" alt="Screenshot3" src="https://user-images.githubusercontent.com/24323868/80037837-61f21b80-84c2-11ea-8354-17704899615b.png">

**Comment by yairEO** [comment]
fixing this ASAP, don't worry

**Comment by rubnsom** [comment]
> fixing this ASAP, don't worry. Thanks for reporting!

Thank you, I'll keep an eye on it to pull the fix!

**Comment by rubnsom** [comment]
Hi @yairEO, 
Thanks for fixing it, I tested it and it works, but noticed that `value.trim()` is still crashing -- It can't trim an Array in `loadOriginalValues` function --> `tagify.js` file

`loadOriginalValues: function loadOriginalValues(value) {
    value = value || this.DOM.originalInput.value; // if the original input already had any value (tags)

    if (!value) return;
    this.removeAllTags();
    if (this.settings.mode === 'mix')
    **this.parseMixTags(value.trim());**
    else {
      try {
        if (typeof JSON.parse(value) !== 'string') value = JSON.parse(value);
      } catch (err) {}

      this.addTags(value).forEach(function (tag) {
        return tag && tag.classList.add('tagify--noAnim');
      });
    }
  },`
