### ISSUE TITLE
Angular module is missing after 3.6.3

### ISSUE THREAD

**Issue by delphist2008** [yairEO/tagify#479]
There is no angular-tagify files in the /dist. It was apparently removed in 3.6.7 version (maybe related to https://github.com/yairEO/tagify/issues/461)
![image](https://user-images.githubusercontent.com/3843432/80067674-77ba1c00-8568-11ea-8a50-8964c65696c7.png)

**Comment by yairEO** [comment]
huge huge mistake. Will take care of this ASAP.
