### ISSUE TITLE
Bootstrap 4 Support

### ISSUE THREAD

**Issue by matthiasballreich** [yairEO/tagify#48]
How can i use this Plugin / Javscript with Bootstrap 4? 
If i use the Bootstrap 4 Form-Controls i see the input twice. Have a look [here](https://i.stack.imgur.com/Xwgis.png)

My HTML-Code looks this:
```
<fieldset class="form-group">
<label for="tags">Tags (Limit 5)</label>
<input name='tags' placeholder='write some tags' value='foo, bar, buzz' class="form-control">               
</fieldset>
```

But when i look into the generated code i see that the input will be transformed to a <tags> Element. So there comes the problem that i see the input twice i think.
How can i use it correctly with bootstrap 4? Can you help me? Or someone else?

**Comment by yairEO** [comment]
why can't you just remove the classnames `form-group` & `form-control` ?

**Comment by matthiasballreich** [comment]
i can remove those classes, but then i don't have the bootstrap design on it. So thats why i asked if it will be possible in any way to use tagify with bootstrap 4.

**Comment by yairEO** [comment]
I understand. I can make the script use whatever classes which where on the original input, so the styling will remain. I will commit a fix soon
