### ISSUE TITLE
react.tagify is undefined when using parcel

### ISSUE THREAD

**Issue by seanyu4296** [yairEO/tagify#480]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Demo Repo
https://github.com/seanyu4296/tagify-react-parcel

### Explanation

- **What is the expected behavior?**
tagify react works with parcel
- **What is happening instead?**
when i import react.tagify in parcel it is undefined 
- **What error message are you getting?**
None

**Comment by yairEO** [comment]
You could have made live demo in [codesandbox.io](codesandbox.io)

I'm checking

**Comment by seanyu4296** [comment]
Thanks so much. Oh I didn't know I can choose a bundler in codesandbox.  @yairEO
