### ISSUE TITLE
When does `onChange` prop get called in React Tagify?

### ISSUE THREAD

**Issue by seanyu4296** [yairEO/tagify#481]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://codesandbox.io/s/tagify-react-wrapper-4gkio?file=/src/CrazyTags.js:2696-2704
- in this example,  `onChange` never gets called. I think the question also is what's the best practice for using `Tagify` in react

### Explanation

- **What is the expected behavior?**
The expected behavior is when data change in the `Tags` component. onChange gets called so i can create a controlled input based from React's state
- **What is happening instead?**
onChange never seemed to get called
- **What error message are you getting?**
None

**Comment by yairEO** [comment]
Looking into it

**Comment by yairEO** [comment]
I see there is a big problem with recent React changes:

https://github.com/facebook/react/issues/11488

**Comment by seanyu4296** [comment]
Do you think there is a possible solution that maybe I can help with? I can look into it on Monday. @yairEO

**Comment by rubnsom** [comment]
After this update, callbacks are not returning `originalInput.value` in `mix-mode`, it is technically the same output string we get on `onChange`, but it is more consistent at any point when handling data updates on callbacks like `keydown`, `blur`, `dropdown:select` etc 

Output:
`e.detail.tagify.DOM.originalInput.value: ""`

I'd be nice to keep it

**Comment by Maazansari** [comment]
Hi @yairEO , I am facing issue with values in onChange callback. I am using `MixedTags ` component with custom tag template.
initially tag render fine. but after changing anything in text-area, Actual value is does not return in onChange call back.
 

**Actual value**: `{my_custom_tag}`
**Initially render tag**:
![image](https://user-images.githubusercontent.com/11793422/113678601-4171a000-96d8-11eb-94e5-c9197bc6fd00.png)

**Value After making changes:**
![image](https://user-images.githubusercontent.com/11793422/113679240-ff952980-96d8-11eb-9c2b-3591f11265fd.png)

As you can see value contain next line characters and spaces. If i replace `MixedTags ` with `Tag `this work perfectly fine.
