### ISSUE TITLE
How to use dropdown.position = 'manual' in React (mix-mode)

### ISSUE THREAD

**Issue by rubnsom** [yairEO/tagify#482]
The drop-down list is not a child component of `<Tags>`  and it displays its content in an absolute position — if you scroll up/down the page, the dropdown position is not tie (relative) to the main input (see image)
I was trying to use `manual` position in the configuration, but the implementation can't be the same in react. [This is the example I followed](https://yaireo.github.io/tagify/#section-manual-suggestions). I'd appreciate your help by providing an example of how it'd work in React 

![image](https://user-images.githubusercontent.com/24323868/80246736-e798d700-863a-11ea-8ef5-2b7465bacf61.png)

**Comment by yairEO** [comment]
See my comment here: https://github.com/yairEO/tagify/issues/400#issuecomment-576640853

**Comment by rubnsom** [comment]
> See my comment here: [#400 (comment)](https://github.com/yairEO/tagify/issues/400#issuecomment-576640853)

That helps, thanks!
