### ISSUE TITLE
Tagify with Vuejs

### ISSUE THREAD

**Issue by Opil-Technologies** [yairEO/tagify#484]
Hello yiarEo i am new to Vuejs and using Tagify. Please how do I get values from Tagify input/tags with vuejs. Pls help, I am stuck.. Thanks in advance

**Comment by yairEO** [comment]
I'll try to make a VUE demo page and let you know when it's done

**Comment by Opil-Technologies** [comment]
Thanks a lot yairE0, I will be waiting... Thanks in advance

**Comment by yairEO** [comment]
https://codesandbox.io/s/tagify-tags-component-vue-example-l8ok4?file=/src/App.vue

**Comment by matamune94** [comment]
> https://codesandbox.io/s/tagify-tags-component-vue-example-l8ok4?file=/src/App.vue
> 
> please also update to latest _Tagify_ version

How can working with vue 2 ?

**Comment by yairEO** [comment]
@matamune94 - please ask this in stackoverflow because sadly I no longer know how to code in Vue.

**Comment by MiniJude** [comment]
> https://codesandbox.io/s/tagify-tags-component-vue-example-l8ok4?file=/src/App.vue
> 
> please also update to latest _Tagify_ version

"v-model cannot be used on a prop, because local prop bindings are not writable." from "vue": "^3.2.47",
is my vue version too high?

**Comment by yairEO** [comment]
I don't know Vue.. sorry...
