### ISSUE TITLE
How to get output of Tagify in React?

### ISSUE THREAD

**Issue by KevinLu** [yairEO/tagify#485]
Hi, I'm wondering how to get the output of Tagify in React.

I used '@yaireo/tagify/dist/react.tagify' in my component and returned this:

```javascript
<Tags
  settings={settings}
  {...tagifyProps}
  onChange={console.log("CHANGED:", tags)}
/>
```

I'm confused about the readme (https://github.com/yairEO/tagify#output-value) because when I do Tags.value it doesn't give an array of tags and I have no idea where the "original" input is.

Any help is appreciated!

**Comment by yairEO** [comment]
Use it as so:

   onChange={e => (e.persist(), console.log("CHANGED:", e.target.value))}
