### ISSUE TITLE
Create Angular codesandbox demo

### ISSUE THREAD

**Issue by yairEO** [yairEO/tagify#486]
I would like to request someone who known **Angular** to make a demo page in [codesandbox](http://codesandbox.io)

**Comment by jdnichollsc** [comment]
what do you think about using StencilJS to generate a WebComponent to integrate this with any framework? :)

**Comment by yairEO** [comment]
@jdnichollsc - I will investigate, gracias hermano!

**Comment by akaco** [comment]
I just run some test here [codesandbox](https://codesandbox.io/s/yaireo-tagify-8h39c)

**Comment by yairEO** [comment]
Done by a dear community member - https://github.com/Brakebein/ngx-tagify
