### ISSUE TITLE
Mixed Mode - Tags are in wrong order

### ISSUE THREAD

**Issue by QichenZhu** [yairEO/tagify#487]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/gediwinatu/1/edit?html,js,output

### Explanation
Steps to reproduce:

1) Click the input box
2) Press End
3) Type #b
4) Press Enter
5) Press Home
6) Type #a
7) Press Enter

(Tagify 3.7.1, Google Chrome 81.0.4044.122)

- **What is the expected behavior?**
The value displayed below the input box is
`[[{"value":"a","prefix":"#"}]]is greater than[[{"value":"b","prefix":"#"}]]`

- **What is happening instead?**
The value displayed below the input box is
`[[{"value":"b","prefix":"#"}]]is greater than[[{"value":"a","prefix":"#"}]]`

- **What error message are you getting?**
None.

**Comment by chen-wu** [comment]
It seems in "getMixedTagsAsString" function, the node comes in different order with the "currentTags" array.

**Comment by yairEO** [comment]
Thanks for reporting I'll get right on it

**Comment by QichenZhu** [comment]
Thank you for the quick fix. It works now.
