### ISSUE TITLE
Autocomplete/Whitelist behavior on select

### ISSUE THREAD

**Issue by pesseyjulien** [yairEO/tagify#49]
Hi,

When using autocomplete & whitelist options, if you select an option from the list, it does not add it as a tag. You need to press enter.

Select
<img width="308" alt="capture d ecran 2018-02-02 a 18 30 34" src="https://user-images.githubusercontent.com/10850944/35746465-2f2cb77c-0847-11e8-981a-23c18ba0ab16.png">
Result
<img width="248" alt="capture d ecran 2018-02-02 a 18 30 40" src="https://user-images.githubusercontent.com/10850944/35746464-2f0df832-0847-11e8-8d5b-45de5dd6f3f7.png">

Normal ?

**Comment by yairEO** [comment]
it only auto-fills. it works just like typing and then having to press the <kbd>enter</kbd> key only you don't really type much, since it gets auto-filled

**Comment by pesseyjulien** [comment]
Ok, thanks ! 

Will this new script automatically add it as a tag on select from the list ?

**Comment by yairEO** [comment]
yes

**Comment by pesseyjulien** [comment]
Great ! Any idea on the release date ? :)

**Comment by yairEO** [comment]
I have been working on it and then I had personal stuff happening so I quit programming for some months, and will be back to it now, slowly.. so i hope in the next few weeks it will be done

**Comment by phaberest** [comment]
Hi @yairEO any news on this matter?

**Comment by yairEO** [comment]
@phaberest -  this has been pushed on the last version update, you can see it working on the demo page
