### ISSUE TITLE
get wrong value when remove random tags from the text

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#490]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/merusasuri/edit?html,js,console,output

### Explanation

- **What is the expected behavior?**
when I start typing and create a comment like " hello #test  and #test1" and then move the cursor back with a left arrow  and remove the #test1 and then click on save button then the value which I get is "hello  and #test1"

also when you click on the any below comment from the table and then create a tag in the middle of the text before the tag which is already in the comment and click on save button gives you the wrong order of tags

- **What is happening instead?**
But the value I get is "hello  and #test" 
- **What error message are you getting?**
no error occurs 

I think because when we trigger remove tag then it remove the last tag from tags array.

**Comment by yairEO** [comment]
Looks like it's related to this - #487

**Comment by yairEO** [comment]
deployed `v3.7.2`, please try now
