### ISSUE TITLE
Pasting content from spreadsheets (Google, Excel) doesn't work

### ISSUE THREAD

**Issue by hugomn** [yairEO/tagify#496]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
There's no demo page as the paste behaviour doesn't work. Follow the steps below to reproduce.

### Explanation

- **What is the expected behavior?**
Text copied from spreadsheets is correctly pasted on tagify input

- **What is happening instead?**
The text is ignored. Fails for single or multiple cells.

- **What error message are you getting?**
No error message. The input just stays empty.

### Steps to reproduce:
1. Open tagify demo: https://yaireo.github.io/tagify/
2. Open the demo spreadsheet (https://docs.google.com/spreadsheets/d/1NpVhjhA53gw-D8MCJpFKdU1lrFVnC56O0JOGIpyWX6c/edit#gid=0) and click and copy (Ctrl + C / Cmd + C) the cell with the test.
3. Paste it (Ctrl + V / Cmd + V) in the tagify input in the demo page.

**Comment by yairEO** [comment]
Sent you a permission request (via Google drive) to view the spreadsheet document

**Comment by hugomn** [comment]
Thanks @yairEO. Made the spreadsheet public. 👌🏻

**Comment by yairEO** [comment]
It's because Google spreadsheets is copying the content with markup. 

To clean it up you should *first* paste it to some **txt** file and then copy it again

**Comment by yairEO** [comment]
Related to #376
