### ISSUE TITLE
Get value of mixed tags not working in React wrapper

### ISSUE THREAD

**Issue by rsweny** [yairEO/tagify#498]
## Prerequisites

- [x] I am running the latest version `3.7.2`
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- I expect for there to be a way to get the value of the mixed text, such that it could be restored to the same state via the value property on the Tags component.

- I have tried `tags['tagify'].getMixedTagsAsString()` but this throws an error
I have also tried `tags['component']['value']` but this returns the initial text the field started with, not its current state. Calling `tags['tagify'].update()` does not seem to update the value.

- the getMixedTagsAsString() gives the error: `cannot read property '0' of undefined`, but otherwise no error.

**Comment by yairEO** [comment]
You cannot not call any internal Tagify methods when using the React wrapper (and there is no reason to call any). You need to simply add an `onChange` event listen to your `<Tags>` component and get the value of the <Textarea> which Tagify generates & updates.

Did you try that?

**Comment by yairEO** [comment]
If you are using React then why don't you simply update the component's `value` prop to add whatever you wish to add? React is declarative and everything should be programed via *props* whenever possible
