### ISSUE TITLE
Caret position after adding a tag using mix mode

### ISSUE THREAD

**Issue by joaofmferreira** [yairEO/tagify#499]
Hi, 

after adding a tag using mix mode, the cursor position is placed in the beginning of the input field, using mix mode.  

Please find attachment below. 

Thank you
![tagify-mix-mode](https://user-images.githubusercontent.com/43538383/80615436-9708eb80-8a37-11ea-8e88-764b0c9cf69d.gif)

**Comment by yairEO** [comment]
which browser?

**Comment by joaofmferreira** [comment]
Chrome

**Comment by yairEO** [comment]
cannot reproduce.

![GIF](https://user-images.githubusercontent.com/845031/80836919-6f17b480-8bfe-11ea-80b3-8aa35265d806.gif)

**Comment by koolkt** [comment]
Having the same problem on Version 89.0.4389.90 (Official Build) (x86_64). However the problem is NOT present in chromium Version 91.0.4447.0 (Developer Build) (x86_64).

**Comment by paourissi** [comment]
The issue still exists and i can be reproduce in every browser
