### ISSUE TITLE
duplicates option not working !

### ISSUE THREAD

**Issue by themesfa** [yairEO/tagify#50]
hi . i'm try to set duplicates option to false but Still typing duplicates values is enable.
can you fix this issue please ?

**Comment by nerdess** [comment]
@themesfa 
i've fixed this issue, see my PR: https://github.com/yairEO/tagify/pull/51

**Comment by yairEO** [comment]
`duplicates` option is `false` by default. 
I've found the problem and corrected it while making it work even better by adding a `tagElem` parameter to the `markTagByValue` method, which skips the need to manually search for tags by value, and only needs to compare the `tagElem`  to its siblings.
