### ISSUE TITLE
Internet Explorer 11 fails beyond version 3.7.0

### ISSUE THREAD

**Issue by alanttran** [yairEO/tagify#501]
Seems like the current polyfills haven't been updated to match the new updates. I tried taking the current js and using a babel-polyfill but that didn't work either. I'm currently using version 3.7.0 :)

**Comment by yairEO** [comment]
Are you sure? with `3.7.3` ? I don't see any error

**Comment by alanttran** [comment]
Thank you!! Fixed in 3.7.3 :) It failed in IE11 for version 3.7.2 & 3.7.1.
