### ISSUE TITLE
Keydown event is not triggered when we are creating a tag in Mix-Mode

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#504]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/judimuqale/edit?html,js,console,output

### Explanation

- **What is the expected behavior?**
I use the space key to make a tag so that I added a keydown callback.
- **What is happening instead?**
the same code is working in 3.6.10 and after the new update, that code is not working anymore.
if you check the jsbin and press # and start typing then you can see that keydown event is only triggered when you press # and the first character.
- **What error message are you getting?**
No error message.

**Comment by yairEO** [comment]
I will check

**Comment by yairEO** [comment]
I see the problem. for now you can use the `input` event instead of `keydown` for `mix-mode`

**Comment by yairEO** [comment]
Apparently this is a big problem, requiring me to conduct through modifications. 
I wrote it down for myself to make this work.

The thing is, when the dropdown is shown, it cancels the "main" `keydown` event listener because the dropdown "needs" its own `keydown` event listener, and they both interfere with each other, but since the dropdown is shown, it has higher importance. 

I have an idea how to fix this already, it's requires a lot of delicate refactoring.

**Comment by singh-vikramjit** [comment]
hi @yairEO i try with `input` event but it doesn't work but i found a way to achive it. 
I added two additional cases in `dowpdown onKeyDown callback` 

` case ' ':`
`case 'Spacebar':`
`case 'Enter':`

**Comment by yairEO** [comment]
You shouldn't change the source-code yourself, you won't be able to upgrade Tagify later because of conflicts.

**Comment by singh-vikramjit** [comment]
Yes i know this is a kind of temporary solution and waiting for your new version

**Comment by yairEO** [comment]
fixed on `3.9.0`

**Comment by singh-vikramjit** [comment]
I check the above Jsbin with the new version but it still make some problems.

![image](https://user-images.githubusercontent.com/45350698/82184732-65719a80-98e8-11ea-8ae3-a544bf683e10.png)

1) The first highlighted tag is not working now when I press first character then it displays the highlighted tag when start typing then it disappears.
2) and after typing "team" when I press Down arrow to select the tag from dropdown and press enter then it returns an error which is in the above image.
