### ISSUE TITLE
wrong value when paste the text in to input (Mix-mode)

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#505]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/gitawizina/edit?html,js,console,output

### Explanation

- **What is the expected behavior?**
when i paste something in input and click on save button then the value should be display in console.
- **What is happening instead?**
when i fetch the `tagify.DOM.originalInput.value` after pasting the content the output is blank and if you type something in input and again paste the content then what you type recently will display in

and if you write something and after that you paste some text that will override the complete text

 console.
- **What error message are you getting?**
No error

**Comment by singh-vikramjit** [comment]
Hi, @yairEO I checked it works but only in case of plain text. like when we copy a text from a webpage some time it is inside a span or p or other tags as well and then it returns an empty value. 

For example: if you open the above jsbin and copy the heading or table and paste it inside tagify and click on save it return an empty value.

so somehow if we can remove the tag from text before paste

**Comment by yairEO** [comment]
You are right, I only fixed it for "normal" more but not for mix-mode, I will work on it.

**Comment by singh-vikramjit** [comment]
when I paste something in input it returns an error.

![image](https://user-images.githubusercontent.com/45350698/82185259-41fb1f80-98e9-11ea-8726-85a0f0effc38.png)

**Comment by singh-vikramjit** [comment]
In code function is `insertTextAtCaret` and in `onPaste` you are using `insertTextAtCursor`

I change the method name in local file and test but it doesn't work.

**Comment by singh-vikramjit** [comment]
here are my findings Please check and if it is fine then please update the code.

Please make sure the function name is the same and add `this.update();` after the `this.setRangeAtStartEnd(false, node);` 

`insertTextAtCursor: function insertTextAtCursor(text) {
    var sel = window.getSelection(),
        node = document.createTextNode(text),
        range;

    if (sel.getRangeAt && sel.rangeCount) {
      range = sel.getRangeAt(0);
      range.deleteContents();
      range.insertNode(node);
    }

    this.setRangeAtStartEnd(false, node);
    this.update();
}
