### ISSUE TITLE
Call applySettings at any time to change the default settings

### ISSUE THREAD

**Issue by oiluis** [yairEO/tagify#507]
Just a quick question, not an issue .. I know we can call the applySettings function from a tagify instance, however it seems that calling this function after the creation of tagify is not changing the settings. Perhaps I am missing something here and I couldn't find my answer looking at the source code.

**Comment by yairEO** [comment]
which exact settings are you trying to change and why?

**Comment by oiluis** [comment]
I was just curios @yairEO :) ... Just would like to let you know that I am building a Microsoft Power Apps Component using the Power Apps Component Framework, not sure if you heard about it https://docs.microsoft.com/en-us/powerapps/developer/component-framework/overview, but basically, I will build a component for the Microsoft low/no-code official platform that will wrap yours, since I think yours is pretty nice. This component will be published on https://pcf.gallery/ and I will give you all deserved credits. You did an amazing job here for the community. Thanks for keeping it.

**Comment by yairEO** [comment]
Thank you :)

You've said:

> *it seems that calling this function after the creation of tagify is not changing the setting*

and I am curious which *settings* did you try modifying.
technically there is never a reason to call `applySettings` from outside, it for internal use only. if you wish to update some settings, then do so directly by mutating on (or many) of `tagify.settings` object properties.

`applySettings` is mean for initialization only
