### ISSUE TITLE
dropdown problems with enabled:0

### ISSUE THREAD

**Issue by zenlunatics** [yairEO/tagify#508]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
with `enabled:0` for the dropdown I should be able to click in the field and then on an item in the dropdown and have it added as a tag

- **What is happening instead?**
clicking on the dropdown item closes the dropdown without adding the tag

- **What error message are you getting?**
none.

I fixed the problem by replacing
```
var hideDropdown = this.settings.dropdown.closeOnSelect,
    value = this.suggestedListItems[this.getNodeIndex(elm)].value || this.input.value;
```

with
```
var hideDropdown = this.settings.dropdown.closeOnSelect;
var item = this.suggestedListItems[this.getNodeIndex(elm)]
var value = (item.value ? item.value : item) || this.input.value;
```

the problem is that the dropdown item is just text instead of an object with a value. I'm sure you have a much better way of fixing the bug.

Another problem is that if you enter the field and the dropdown appears and then you click in the field without selecting anything on the dropdown, the dropdown disappears, which is fine, but then typing keys in the field no longer has any effect.

**Comment by yairEO** [comment]
Thanks for reporting, I'm on it.

Pretty good solution, but it's less code writing it this way:

    value = selectedOption.value || selectedOption || this.input.value

**Comment by zenlunatics** [comment]
great thanks!
