### ISSUE TITLE
minify(template) function also minify tag value

### ISSUE THREAD

**Issue by funway** [yairEO/tagify#509]
## Phenomenon

Hi,

When i input those two tags: "h i" (with one space), "h   i" (with three space). they are no duplicate. （it seems github page could not render multiple spaces rightly. =.=#）

But in the rendered dom elements, we could see those two <tag> element's title attribute are the same, with only one space. 

## Prerequisites

I use the version "@yaireo/tagify@3.8.0"

## Location

I checked the source code and found out where the problem lies.

In the `function createTagElem(tagData)`, it create the tag element's html template string firstly. The tag value has embedded into the template string, then it call `template = minify(template);`. 

This is where the problem is. minify function remove new lines and irrelevant spaces in the template string, also remove the spaces in the tag value.

## Suggestion

I think we should better keep the tag value unchanged when calling minify function.

**Comment by yairEO** [comment]
Do you really have tags with more than one space between characters? 
I've never ever thought that might be

**Comment by funway** [comment]
I agree that there is no "normal" human will type more than one space between characters. 
But we could never trust user input unless we do some validation.
Since tagify accept more than one space between characters when user add a tag , it is counfused to trim those spaces when rendering the tag into html dom.

Thanks.

**Comment by yairEO** [comment]
This is the minify function which is responsible for this:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L51

I don't remember why it replaces multiple spaces with a single space, it might be something important which might cause a bug otherwise, so I'm reluctant to change this.

I don't always remember all the hunders of different scenarios Tagify might be at :)
I also did not write tests because I gave up, there are just too many to write and I cannot sit and write tests for weeks on the little free time that I have

**Comment by funway** [comment]
I understand and thanks as always.
I implement a keydown handler to prevent user from input multiple spaces.

            $('span.tagify__input').keydown(function(e) {
                let str = this.textContent;
                if(e.keyCode === 32 && str.length >= 1 && str[str.length-1].trim() === '') {
                    e.preventDefault();
                }
            });

But I cannot achieve the same goal in tagify's keydown event. Is there any I missed?

**Comment by yairEO** [comment]
Tagify has its own [keydown event](https://github.com/yairEO/tagify#events), regardless, you could use the `pattern` to disallow multiple proceeding spaces, so the user would know something they did should be done
