### ISSUE TITLE
Tag truncation, how to show full value in tooltip?

### ISSUE THREAD

**Issue by alanttran** [yairEO/tagify#510]
I'm looking for advice on how to have the tooltip be the original value but the tag itself show an ellipsis. I initially used the transformTag to use .substring() to create my ellipsis and truncated tag. Unfortunately there are no real options to affect the tooltip through transformTag since it will show the new "truncatedvalue..." and not the original value. Thank you! Let me know if I can clarify anything.

**Comment by yairEO** [comment]
give your *whitelist data* a "title" property:

```
[
  {
    value: "very long name of a tag",
    title: "short name"
  },
  ...
]
```
