### ISSUE TITLE
Fire onChange event same as native browser does

### ISSUE THREAD

**Issue by gpetrov** [yairEO/tagify#514]
Currently with tagify on each keystroke a change event is triggered (even if it is custom - it is still a change event).

This is not always desired. In cases where the tagify mimics exactly an input field, a change should be triggered only on blur or enter - and only if the contents has changed, just  like the regular inputs.

And on each key stoke an input event should be triggered. Again just as regular inputs.

We can't use tagify efficiently in our current system now because changes get triggered way too often now. And we have to resort to debouncing events just to cool them down.

@yairEO  Please consider an option to allow to trigger change and input events based on the standard model of inputs. 

Thank you!

**Comment by yairEO** [comment]
I agree, will work on it

**Comment by gpetrov** [comment]
Just tested the latest version and there are a few glitches
* change event is triggered now correctly on blur. However it is always triggered even if the value is unchanged
* when the tagify field doesn't have the focus, but the user just deletes a tag on it by clicking the x icon on the tag - no change event is fired

**Comment by yairEO** [comment]
will be fixed ASAP

**Comment by geniusmaster33** [comment]
Earlier when new tags were added to the input field, it used to fire the change event but this has stopped. I had to downgrade to 3.9.3 for it to properly work.

**Comment by geniusmaster33** [comment]
For eg. the blur event does not get triggered in the https://yaireo.github.io/tagify/#section-different-look case.

**Comment by yairEO** [comment]
Now `onChange` event fires only when the *"original"* input's value changes on these specific points of program flow:

1. `blur` event
2. Tag **edited** successfully (not invalid)
3. Tag **removed**
4. Tag **added**
5. Tag **selected** (when `mode` is set to "select")
6. "removeAllTags" method fires
