### ISSUE TITLE
click on tag will display the cursor just after the tag 

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#515]
Based on different browser sometimes moving cursor inside input is not properly visible after the Tag. 

So I think it would be great if when we click on a tag and cursor will display just after the tag. 

for example, we have text inside the input: "Hello #tag and #this is #awesome" and when we click on #tag the cursor displayed after the #tag. or if I click on #this then it displays after the #this 

Can you please help me with this. and i also mention comments in this issue can you please take a quick look in to this #453

**Comment by yairEO** [comment]
what browsers? 

I'm looking at #453

**Comment by yairEO** [comment]
You can also give a tiny margin on the sides of the tags elements, which will solve this issue. I've intentionally left it to the developers to decide.

**Comment by singh-vikramjit** [comment]
Hey @yairEO i agree with you but i make this as a "Help with something" it is not a Suggestion.

So can you please help me with this
