### ISSUE TITLE
Mix text & tags - error when add a tag after deleted another one - IndexSizeError

### ISSUE THREAD

**Issue by eumene** [yairEO/tagify#516]
## Prerequisites
- I am running the latest version
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed

### Demo Page
https://yaireo.github.io/tagify/

### Explanation
Go to demo page and reach the "Mix text & tags" demo

Focus input at the and of the text (relic.) and start to delete the input content using backspace, until you delete "Home Simpson" tag

Start type #Li to add tag "Lisa". The dropdown is shown

Try to select the tag "Lisa" (using mouse or arrows)
Nothing appends and in console log you can see an error
_IndexSizeError: Index or size is negative or greater than the allowed amount_

![immagine](https://user-images.githubusercontent.com/3097121/82223338-d0d85e00-9922-11ea-96dc-7d142ed53311.png)

**Comment by yairEO** [comment]
Thanks for reporting!

**Comment by eumene** [comment]
Thanks guys

Can you check the release v3.9.2 ?
https://github.com/yairEO/tagify/releases
It seems that the 3.9.2 zip file contains the v3.9.1 in dist folder

**Comment by yairEO** [comment]
@eumene - yeah it's just me here, i'm a single person which Tagify is one of my hobbies.

I think I messed up `2.9.2`, i rushed to publish it without carefully making sure the version was correct after some *gulpfile* experiments.
