### ISSUE TITLE
Problem with focus for the field with only one tag in Firefix

### ISSUE THREAD

**Issue by Megas78** [yairEO/tagify#520]
## Prerequisites

- [x] I am running the latest version

If you put just one tag to the field, then click outside and after that go back to the field with tag the caret is not shown and you can't type in the field any more.

Firefox 76.0.1. Mac Os. Also was reproduced on Windows 10

**Comment by yairEO** [comment]
![GIF](https://user-images.githubusercontent.com/845031/82383963-885e9480-9a37-11ea-8948-ce6ed566db41.gif)

Unable to reproduce: FF `76.0.1` (64-bit) on Windows 10
