### ISSUE TITLE
Click on placeholder text block the input field in Firefox

### ISSUE THREAD

**Issue by singh-vikramjit** [yairEO/tagify#521]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/fifobakore/1/edit?html,css,js,output

### Explanation

- **What is the expected behavior?**
Click inside the input field and click on the placeholder and start typing will create a comment.
- **What is happening instead?**
When clicking on input field and click again on placeholder will block the input field you are not able to type anything 
- **What error message are you getting?**
No error

**Comment by mete89** [comment]
Thanks @singh-vikramjit, I was trying to reproduce the same issue. Using firefox 76.0.1 (64-bit)
