### ISSUE TITLE
Ajax whitelist

### ISSUE THREAD

**Issue by NiackZ** [yairEO/tagify#522]
Hello. First of all - thank you for your work!
I get the WhiteList from the server through AJAX and I get an error in the console + the drop-down list is empty. I was trying to do what you described in this [topic](https://github.com/yairEO/tagify/issues/465).
[imgur](https://imgur.com/a/CoheZGO)
Can you tell me where I got it wrong, please?
```

<input type="text" name="type_tags" value="">
<script src="../js/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
<script>
let type_input = document.querySelector('input[name="type_tags"]'),
type_tagify = new Tagify(type_input, {
    whitelist : [],
    enforceWhitelist:true,
    maxTags:1
});

type_tagify.on('input', getWL());
async function getWL(){
  type_tagify.settings.whitelist.length = 0;
  type_tagify.loading(true).dropdown.hide.call(type_tagify);
  var newWhitelist = await take_type();
  newWhitelist = JSON.parse(newWhitelist);
  console.log('newWhitelist down');
  console.log(newWhitelist);
  type_tagify.settings.whitelist.push(newWhitelist);
  type_tagify.loading(false).dropdown.show.call(type_tagify);
}
async function take_type(){
  return await $.ajax({
    type: 'POST',
    url: 'test.php',
    data: 'qq=0'
  });
}
</script>

```

**Comment by yairEO** [comment]
`console.log(newWhitelist)` shows nothing? maybe you have a problem with your server

I cannot help much, the code seems file to me...

**Comment by NiackZ** [comment]
> `console.log(newWhitelist)` shows nothing?
nope, 
![2020-05-24_00-43-04](https://user-images.githubusercontent.com/14057913/82739270-be618880-9d57-11ea-9867-5f06eef91bd1.png)
>  maybe you have a problem with your server
hm... okay, I'll see what's wrong.
Thank you
