### ISSUE TITLE
Manual-rendered dropdown not responding to keyboard events

### ISSUE THREAD

**Issue by Ktar5** [yairEO/tagify#525]
I've checked all the prerequisites

When I click on my tag suggestions, it instead adds that tag of what I've typed into the input, not what I've clicked in the suggestion box.

Here is the issue in a gif, where each mouse click is shown with a circle.

<img src="https://i.imgur.com/5tWJdea.gif" />

The error happens when you have an empty *whitelist* before you render the *dropdown*.
As such:
```javascript
this.tagify.dropdown.show.call(this.tagify);
this.tagify.DOM.scope.parentNode.appendChild(this.tagify.DOM.dropdown);

// console.log(this.tagify)
this.allTags.forEach(tag => {
    this.tagify.settings.whitelist.push(tag);
});
```

This can be fixed by one of two ways, which both involve the whitelist not being empty before calling the dropdown renderer:

1. Having the whitelist NOT be empty before the two lines of code that render the dropdown
2. Moving the whitelist-adding code before the dropdown rendering code

### Demo Page
Here's a demo showing the issue.
https://jsbin.com/zazinarodu/1/edit?html,js,output

Thanks for making an awesome project and I hope this helps out!

**Comment by yairEO** [comment]
Thanks for reporting, this is an important bug.
