### ISSUE TITLE
After edit a text to invalid value, I can do nothing.

### ISSUE THREAD

**Issue by aicodex** [yairEO/tagify#526]
Thanks for your libary.
I found that when i add a tag name is `tag0`, and then i add a tag name is `tag1`. After i edit `tag1` to `tag0` I can do nothing because no event happened, I have try to listen edit:*, input, blur.

Is their any event like edit:invalid? or beforeUpdate i can delete it or change it to previous value.

**Comment by yairEO** [comment]
What do you mean "I can do nothing"? what do you want to do? 
You **shouldn't** have deleted the *issue template* on Github, it is there for me to better understand user reports.
