### ISSUE TITLE
onChange is not called when clearing the last tag?

### ISSUE THREAD

**Issue by danqing** [yairEO/tagify#537]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I have this really simple React code:

```js
<Tagify
  settings={{
    placeholder: "Paste or enter emails here",
    delimiters: "[ ,;\t\n]",
  }}
  onChange={(e) => {
    try {
      const value = JSON.parse(e.target.value);
      setEmails(value.map(v => v.value));
      console.log(value);
    } catch (error) {
      setEmails([]);
    }
  }}
/>
```

If I have 1 tag in the input and I remove it, `onChange` is not called.

---

Also, unrelated to the above, but why is `e.target.value` a string? Shouldn't it be an array? It's really weird that I need to do something like `JSON.parse`, or maybe I'm using it wrong?

Thank you!

**Comment by yairEO** [comment]
Thanks for reporting, I am investigating.

regarding the other question about `e.target.value` - This is how DOM events work for form elements such as *text* `input` or `textarea`, the `e.target.value` is always a *String*, it's the nature of the DOM API, there is absolutly nothing I can do about it, and even if there was, it would be wrong to break the rules of the web as so

**Comment by danqing** [comment]
Hmm is this fixed? Looks like it still doesn't work for me..

**Comment by yairEO** [comment]
yeah it works, see the [demo](https://codesandbox.io/s/tagify-react-wrapper-oempc)

wait a few seconds for all the crazy stuff in the demo to finish and then click (x) to remove the last tag and look in the console - a `change` event will be fired.

**Comment by danqing** [comment]
Ah sorry I may have been unclear about this...

I didn't click on the X. I used backspace, and while it removes the last tag for me, no change event is called. In the demo I think it doesn't even remove the tag?

**Comment by yairEO** [comment]
I see it does trigger "change" event (in the demo) when pressing <kbd>backspace</kbd>

**Comment by danqing** [comment]
I think I can reproduce the bug now @yairEO . If the initial `value` of the component is empty, then `onChange` isn't triggered for deleting the last tag. If there is a non-empty value, it is triggered (so the demo works fine).

**Comment by danqing** [comment]
![CleanShot 2020-06-18 at 11 14 07](https://user-images.githubusercontent.com/5134133/85038705-ebd20400-b154-11ea-965e-1ecfaf0011f5.gif)

crazy tags.js repro if you want to see it in the demo:

```js
import React, {useState, useEffect, useCallback, useRef} from "react"
import {getWhitelistFromServer, getValue} from "./mockServer"

//import Tags from "@yaireo/tagify/dist/react.tagify"

//// IMPORTANT ///////////////////////////////////
// ☝☝☝ In reality use the ABOVE commented line
import Tags from "./tagify/react.tagify"

/////////////////////////////////////////////////

// Tagify settings object
const baseTagifySettings = {
  blacklist: ["xxx", "yyy", "zzz"],
  maxTags: 6,
  //backspace: "edit",
  placeholder: "type something",
  dropdown: {
    enabled: 0 // a;ways show suggestions dropdown
  }
}

// this example callback is used for all Tagify events
const callback = e =>
  console.log(`%c ${e.type}: `, "background:#222; color:#bada55", e.detail)

// callbacks props (for this demo, the same callback reference is assigned to every event type)
const tagifyCallbacks = {
  // add: callback,
  // remove: callback,
  // input: callback,
  // edit: callback,
  // invalid: callback,
  // click: callback,
  // keydown: callback,
  // focus: callback,
  // blur: callback,
  // "edit:input": callback,
  // "edit:updated": callback,
  // "edit:start": callback,
  // "edit:keydown": callback,
  // "dropdown:show": callback,
  // "dropdown:hide": callback,
  // "dropdown:select": callback
}

// this is an example React component which implemenets Tagify within
// itself. This example is a bit elaborate, to demonstrate what's possible.
const CrazyTags = () => {
  // merged tagify settings (static & dynamic)
  const settings = {
    ...baseTagifySettings,
    callbacks: tagifyCallbacks
  }

  const onChange = useCallback(e => {
    e.persist()
    console.log("CHANGED:", e.target.value)
  }, [])

  return (
    <>
      <h2>
        <em>Crazy</em> Tags:
      </h2>
      <p>
        Wait a few seconds to see things happen. <br />
        <small>
          <em>(Carefully examine the source-code)</em>
        </small>
      </p>
      <Tags
        settings={settings}
        value=""
        onChange={onChange}
      />
      <h2>Readonly tags:</h2>
      <Tags value="foo,bar" readonly />
    </>
  )
}

export default CrazyTags
```

**Comment by yairEO** [comment]
I see the problem and this seems quite a problem. *React* does not recognize the change event for some reason.

**Comment by danqing** [comment]
Hmm I think 3.11.2 has another (bigger) issue with react: when you blur, `onChange` is called with empty string, and the tags are all cleared..

**Comment by danqing** [comment]
I don't know how the demo is set up @yairEO - looks like it doesn't have the latest version, but for my code if I revert to 3.11.1 things work again (except the deleting last tag part)

**Comment by yairEO** [comment]
Yeah, the demo page is not in complete sync, I will change it now, and will also investigate regarding this new problem ASAP. thanks
