### ISSUE TITLE
Identifies the deleted tag ID

### ISSUE THREAD

**Issue by RayNEXT** [yairEO/tagify#54]
I want to delete the tag and specify its id to save in the database then how do?

**Comment by yairEO** [comment]
well, now there's no ID for each tag, it's only simple text. you know which word (tag) was deleted when you set a listener to the `remove` event for your `Tagify` instance. an event is dispatched and the argument is the "remove" event, so you can check `e.detail` : 

    var tagify = new Tagify(...)

    function onRemoveTag(e){
        console.log(e, e.detail);  // <--- e.details has the deleted tag's index & value
    }

    tagify.on('remove', onRemoveTag);

if you know the value of the tag which was removed then you can map that to any ID in your database, and that mapping is separate object (key/value) that's on the client or on the server.

If you want to attach a server-specific ID to each tag then that will require a patch on my code. 
I will see how much work this is and let you know

**Comment by yairEO** [comment]
Fixed on version `1.3.0`

See [readme](https://github.com/yairEO/tagify#tags-with-properties-example) example
