### ISSUE TITLE
Extra tag added when selecting suggestion with the Enter key but not when clicking on it

### ISSUE THREAD

**Issue by tavosansal** [yairEO/tagify#542]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
This can be reproduced in the demo page in the advance options demo https://yaireo.github.io/tagify/#section-advance-options or really in any other demos.

Here is a video explaining what I am seeing: https://soapbox.wistia.com/videos/fF1JqEYWtk

### Explanation

- **What is the expected behavior?**
My expected behavior is that selecting a tag with a click or with enter would do the same.

- **What is happening instead?**
Selecting a tag from the suggestions list with enter adds the tag that was selected and also the text that I typed to search as a tag. Selecting a tag with a click only selects the suggestion (which I think is the correct behavior and should be the same for enter as well)

- **What error message are you getting?**
No error message

**Comment by nanawel** [comment]
Thanks for creating a dedicated issue for this @tavosansal.

I wonder if there's a way to catch the Enter key and simulate a Right Arrow instead. That way we could get the wanted behavior without altering the library.

**Comment by yairEO** [comment]
Worry not good people of the internet, this shall be fixed promptly.

**Comment by tavosansal** [comment]
@yairEO thank you for looking into it
