### ISSUE TITLE
Accepting a suggestion causes text box to lose focus

### ISSUE THREAD

**Issue by giftig** [yairEO/tagify#543]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

The unmodified example from the bug report template exhibits the issue:
https://jsbin.com/jekuqap/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Typing "cc" and hitting tab to accept the `ccc` suggestion should add `ccc` and leave focus on the text box so that I can continue typing. When there is no suggestion, e.g. I type `ddd` and hit tab, I get the expected behaviour, I can continue adding new tags without having to refocus.

- **What is happening instead?**
The text box loses focus after accepting the `ccc` suggestion.

- **What error message are you getting?**
N/A

**Comment by yairEO** [comment]
Thanks a lot for reporting. I will see to it tomorrow.

**Comment by yairEO** [comment]
Sorry I was busy with work, I will fix it very soon
