### ISSUE TITLE
Required attribute support

### ISSUE THREAD

**Issue by pixobit** [yairEO/tagify#544]
Right now I don't see any way to make a tagify input required, as it breaks the form because of it's hidden nature, but this should be a pretty high priority item to fix

**Comment by yairEO** [comment]
You did not specify if you are talking about vanilla/react/vue/angular

Also, you did not explain what *"breaks the form"* means..

**Comment by yairEO** [comment]
`required` attribute won't help you much, because you still need to manually validate Tagify when your form is submitted. You can use `tagifyRef` for this.

## Here's a React example:

```jsx
<form onSubmit={onSubmit}>
	<Tags tagifyRef={tagifyRef} .../>
	<button>Submit</button>
</form>
```

### onSubmit:

```javascript
const onSubmit = e => {
    e.preventDefault()

    const isValid = !!tagifyRef.current.value.length

    tagifyRef.current.DOM.scope.classList.toggle("tagify--invalid", !isValid)

    if (!isValid) return false
}
```

The code is indeed too verbose. I will create an internal Tagify method that can validate the component and toggle the class all by itself.

**Comment by pixobit** [comment]
Sorry, I was talking about vanilla.
Also, by breaking the form I meant if by any chance you set the input/textarea to required, which later gets converted to a tagify input, when you want to submit the form and leave the input empty, you will notice that the form won't submit, and won't give you any feedback as well. This is because chrome will give you "field is not focusable" exception (will try to focus invalid fields upon validation)

**Comment by yairEO** [comment]
Now Tagify [supports](https://github.com/yairEO/tagify#html-input--textarea-attributes) the `required` attribute.

It will allow you to do something like this:

```css
.tagify--noTags[required]{ 
  --tags-border-color: red;
}
```

**Comment by engin-can** [comment]
I am experiencing what pixobit described: The `input` fields are set to `display:none` which triggers `field not focusable` error in Google Chrome when `required` attribute is added.

I've opened a ticket for this:
https://github.com/yairEO/tagify/issues/783
