### ISSUE TITLE
data-whitelist attribute doesn't treat correctly

### ISSUE THREAD

**Issue by cyrus07424** [yairEO/tagify#546]
on `v3.11.3` `data-whitelist` attribute doesn't treat correctly.

Html was
```html
<textarea data-tagify="true" data-whitelist="[&quot;TAG1&quot;, &quot;TAG2&quot;]"></textarea>
```

but appeared white list was 
```
["TAG1"
"TAG2"]
```

**Comment by yairEO** [comment]
what are all these `&quot;` things??

```html
<textarea data-tagify="true" data-whitelist="['TAG1', 'TAG2']"></textarea>
```

Please don't escape characters inside an HTML attribute, the value would not get parsed
