### ISSUE TITLE
placeholder overflow wrapper

### ISSUE THREAD

**Issue by yairEO** [yairEO/tagify#549]
![image](https://user-images.githubusercontent.com/845031/86032428-03a46480-ba40-11ea-8b96-3801b993ef31.png)

**Comment by benjamindoe** [comment]
Hi, I think this bug has regressed.

Using v4.0.3

![image](https://user-images.githubusercontent.com/15779219/114171089-b688e380-992b-11eb-911b-ad0b868db658.png)

I was able to fix in my particular situation with the following. It does mean that the user jumps between the first and second line as they start typing though.

```css
.tagify__input:empty::before {
    position: static;
}
```
![image](https://user-images.githubusercontent.com/15779219/114171515-49298280-992c-11eb-85d6-cd30b8448e86.png)

![image](https://user-images.githubusercontent.com/15779219/114171636-78d88a80-992c-11eb-8b23-1835b92ffb6c.png)

**Comment by yairEO** [comment]
Yes, this is why I've decided that the current way, where the text overflows, is preferable to the experience of the "jumping", which must be annoying to others as it is to me.

I'm leaving it as it is, and if a developer prefers to clip the text rather than have it overflow then they are free to do so, if they know CSS ;)
