### ISSUE TITLE
Jquery remove all tags not working

### ISSUE THREAD

**Issue by pesseyjulien** [yairEO/tagify#55]
Hi,

I'm trying to use the 'removeAllTags' method with the Jquery version, but it won't work. I took example on yours (https://yaireo.github.io/tagify/), which is throwing a 404 btw.

Thanks in advance for your help,
Julien

**Comment by yairEO** [comment]
thanks. it apparently was a problem with the demo's code.
I've updated the index.html file and now it's ok. 

BTW, I think at 404 you saw was GitHub's error since they host everything including the demo page.

**Comment by pesseyjulien** [comment]
perfect, thanks a bunch for the quick fix !

**Comment by ycv005** [comment]
Hey there, I am working with removing all Tags with Jquery version of your code, I have no issue but have a doubt. Why below is happening?
Not Working Code- 
`var input = $('[name=tags]').tagify();
input.removeAllTags();
`
Working Code-
`var input = $('[name=tags]').tagify();
var jqTagify = input.data('tagify');
jqTagify.removeAllTags();`

**Comment by morrow95** [comment]
Just came across this as I was looking for something similar.  Here is an example of what I use that works and does not require saving as vars : 

```
$('#s2Tags').tagify({
	placeholder: 'add keyword',
	backspace: false,
	editTags: {
		clicks: 1
	}
});

$('#s2TagsRemove').on('click', function (e) {
	e.preventDefault();
	$('#s2Tags').data('tagify').removeAllTags();
});
```
You should have used ```input.data('tagify').removeAllTags();``` in your 'not working' code.

**Comment by jjxtra** [comment]
removeAllTags doesn't clear persisted storage. How to fix?

**Comment by yairEO** [comment]
@jjxtra - well, who store the data in the persisted storage in the first place...? 😉
