### ISSUE TITLE
Not able to disable fuzzy search for whitelist

### ISSUE THREAD

**Issue by A1bi** [yairEO/tagify#555]
Hi!

As described in the documentation I tried to disable fuzzy search for the whitelist with the following configuration option:

```js
dropdown: {
  fuzzySearch: false
}
```

This unfortunately broke the search completely. I no longer get any suggestions in the dropdown. The whitelist works fine only with fuzzy search enabled. I am using the most recent version of tagify.

**Comment by yairEO** [comment]
Thank you. working on a fix!

**Comment by A1bi** [comment]
Works great. Thanks a lot! 🙂
