### ISSUE TITLE
(jQuery) Input and keypress events not working

### ISSUE THREAD

**Issue by kevinpallado** [yairEO/tagify#558]
I did test both events and supposedly I must read what is inputted on tagify input, both shows null value.

```
var taginput = $('#tags')
      .tagify({
              whitelist : ['workouts', 'fitness', 'yoga','meditation', 'strength', 'nutrition','fashion','beauty','tutorials','tips','comedy','gaming','dancing','sports','athletics','strength','running','mindfulness'],
              dropdown: {
                enabled: 1
              },
              placeholder: 'Please add some #Hashtags'
          })
      .on('input', function(e){
        console.log(e.detail)
      });
```

This is what I do, the same goes with keypress still undefined, how can I get the keyvalue inputted by the user?

tagify used version 3.13.0

**Comment by yairEO** [comment]
Thanks, I will investigate

**Comment by yairEO** [comment]
jQuery event callbacks don't work the same as "normal" DOM events callbacks. Callbacks have 2nd argument which is the data *Object* of the event, similar to `e.details`:

https://jsbin.com/mewijug/edit?html,js,console,output
