### ISSUE TITLE
Add tag on whitespace/spacebar

### ISSUE THREAD

**Issue by gabrielsze** [yairEO/tagify#559]
Hi there! Just wondering if it's possible to create tag with a whitespace (spacebar), and how to go about doing it.

(Yes, only allowing one word or hyphenated tags)

**Comment by yairEO** [comment]
Hi, you simply need to provide the desired [`delimiters`](https://github.com/yairEO/tagify#settings) setting:

```javascript
{
  delimiters: ' '
}
```
