### ISSUE TITLE
Safari Issue (not clearing)

### ISSUE THREAD

**Issue by LasseRafn** [yairEO/tagify#56]
I just discovered Tagify and wanted to play with the examples. For some reason, all the examples except the first broke. I'm not sure why, but it has something to do with the input not clearing on tag added.

Video: https://www.dropbox.com/s/a0cnfij4z0cg5do/Tagify-broken.mov?dl=0

**Comment by yairEO** [comment]
Thanks for reporting. I don't have a Mac or access to any Safari..

This video you took looks pretty insane hahaha, I wonder what can cause that...no errors in the console?

**Comment by yairEO** [comment]
which Safari version was it?

I asked a friend to check on his Safari and all works well
