### ISSUE TITLE
Automatically close dropdown is not working

### ISSUE THREAD

**Issue by tomashk** [yairEO/tagify#561]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/mawafowaji/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Close dropdown automatically after select value.

- **What is happening instead?**
Dropdown is still visible. I need to click few times on arrow on right side.

- **What error message are you getting?**
After I lose focus on windows and then go back I can see in console: ```Uncaught TypeError: this.toggleInvalidClass is not a function```

First of all, thank you very much for your great component! Respect man!

I've tried to create select input with whitelist.
The problem is, that after I select option from whitelist, dropdown doesn't hide. I've tried to close is manually (by click few times on arrow on right side) - then it works. But after I lost focus on window and then go back I've seen in console: ```"Uncaught TypeError: this.toggleInvalidClass is not a function"```. I've tried to find ```toggleInvalidClass``` function in your code, but it's not there. I think that is bug ;)

## Steps to reproduce:
1. Select value from dropdown.
2. Close dropdown by arrow.
3. Move to another windows of browser.
4. Go back to page with select component. Exception should be visible in console.

I also would like to know, how to set up your library to automatically close dropdown after select value?

Have a good day and many thanks for your hard work!

**Comment by yairEO** [comment]
Thanks for reporting. will be fixed today
