### ISSUE TITLE
Adding additional data to the tag details

### ISSUE THREAD

**Issue by tom-byrom** [yairEO/tagify#565]
Hi @yairEO ,
Thanks for this great (non dependent) script! Really enjoying using it so far over the more common jquery selectize

I've finally got to the place with writing my script where I need to ask for some help. Let me preface this by saying I'm by no means the best developer but I'm working on a project with Craft CMS where I'm allowing extensive front end user functionality. Part of that functionality is creating and editing entries.

**Here's where im at:**

- I've managed to implement the script to search Craft for already existing tags upon an 'add' event > if no exact match is found it then creates the tag in Craft and adds a hidden input to the form with the Craft tag id (this is needed to save tags to the entry on form submission).

- If exact matches are found upon a search then it grabs the exact match tag id from Craft and then creates a hidden input for the entry to save against.

So adding tags is complete and works as far as I'm concerned really well.

**My issue is upon removal of a tag.** 

I need those hidden inputs created with the Craft tag id mentioned above to save tags against an entry. This means that if I remove a tag from the tagify input I also need to remove the hidden input for that tag from the form. 

`<input type="hidden" id="1102" name="fields[tags][]" value="1102">`

I need to somehow reference the id upon the 'remove' event in tagify.

The id and value mean nothing to tagify, only to Craft at this point. 

How can I on the initial 'add' event (once I have my global variable set for the tagId) add this id to the tag data object?
![image](https://user-images.githubusercontent.com/34626292/87040763-1ad61580-c1e9-11ea-85b8-b99b66374356.png)
Can I add a for example  'tagId: 1102' to this?

I saw a tagData method in the docs. But I'm unsure how to access this and add data to it?

If I can do this I can reference on a 'remove' event the input with that id and remove it. Such as this

```// On remove get the id of the removed tag and store it in the global variable
tagify.on('remove', e => {
    tagIdRemove =  e.detail.tagId;
    // Log the value (can delete)
    console.log(tagIdRemove);
  
    var removeInput = document.getElementById(tagIdRemove);
    removeInput.remove()

})
```
I would really appreciate any help!

Thanks
Tom

**Comment by tom-byrom** [comment]
EDIT: So having written this out and looking at the problem differently I realised I can use the detail.value on an earlier 'input' event where I store the value as a global. 

I then add that global variable to the id on creation of the input.

That way I can reference the .detail.data.value on the 'remove' event, store that in a global, and then delete the hidden input with the corresponding id!

Dam. Funny how writing things out can help!

**Although my issue is solved my question about adding extra data to the tag data is still valid, if that is possible?**

**Comment by tom-byrom** [comment]
EDIT: So having written this out I've actually had a penny drop moment and figured out a way to get around the issue without having to add data to the tag data.

Instead of using the Craft tag id for the hidden input id
`<input type="hidden" id="1102" name="fields[tags][]" value="1102">`

I use the value which was available to me in a variable I created from an earlier 'input' event which stored the data.value before the 'add' event. 
`<input type="hidden" id="newtag" name="fields[tags][]" value="1102">`

I then store another global variable with the details.data.value on the 'remove' event.

Cross reference that with the input id and remove any hidden input with it.

**Although my issue is technically solved. My question still stands on being able to add additional data to the tag data?**

**Comment by yairEO** [comment]
How does your tags data looks like? I need to see the JSON structure

**Comment by tom-byrom** [comment]
Hi, not 100% sure if this is what you want?

Below is the response from the creation of a tag on the server side
![image](https://user-images.githubusercontent.com/34626292/87405100-e54d7580-c5b6-11ea-94e2-951e5ad2fa11.png)

Below is what tag data that tagify creates upon the 'add' event when referencing
` e.detail`
 
![image](https://user-images.githubusercontent.com/34626292/87406419-986a9e80-c5b8-11ea-9e00-45b52a7a4590.png)

**Comment by yairEO** [comment]
If you want to add additional data, for a scenario when the user inputs a *new* tag (which doesn't exist in the *whitelist*) then you can use the `transformTag` settings ([example here](https://yaireo.github.io/tagify/#section-advance-options)), like so:

var tagify = new Tagify(..., {
	transformTag: function(tagData){
    	tagData.myID = 123
	}
})

You can do any logic you wish inside the `transformTag` and mutate the `tagData`. the function doesn't need to return anything.

**Comment by tom-byrom** [comment]
Thanks buddy
