### ISSUE TITLE
Removing a tag that includes ampersand '&' doesn't trigger change event 

### ISSUE THREAD

**Issue by hafezdivandari** [yairEO/tagify#570]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/bibamegowi/2/edit?html,js,output

### Explanation
1. Select a tag that includes '&' from dropdown.
1. Then remove it. 

- **What is the expected behavior?**
The input value to be empty after removing this tag and be included in the dropdown. The change event to be triggered after removing this tag.

- **What is happening instead?**
The input value is not empty and this tag in not included in the dropdown anymore. The change event on input is not triggered after removing.

- **What error message are you getting?**
None

**Comment by yairEO** [comment]
Thanks for reporting, good catch! I'll fix it ASAP
