### ISSUE TITLE
onChange called multiple times in React wrapper

### ISSUE THREAD

**Issue by danqing** [yairEO/tagify#571]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

---

In the latest version, `onChange` is called multiple times in React when adding a tag. Specifically, if there are 3 tags, `onChange` is called 4 times, with 0, 1, 2, and 3 tags respectively.

The end state is correct (with 3 tags), but the handler should only be called once for each change event.

**Comment by yairEO** [comment]
it does not call multiple times, it would seem that you've simply binded your `change` event listener multiple times, probably per-tag, so it is firing multiple times

**Comment by danqing** [comment]
I was only updating from 3.13 to 3.14 and didn't change my code.
