### ISSUE TITLE
Getting the tag value from 'dropdown:select' not working as expected.

### ISSUE THREAD

**Issue by tom-byrom** [yairEO/tagify#572]
Hello :) When trying to retrieve e.details about a whitelisted suggestion using the 'dropdown:select' event. I can't get a proper value for it? Instead it looks like it returns an array with a separate key for each letter in the tag?

Why doesn't it just return the tags value like the below? As I need the value the value to update a variable.

`{ value: "addsometag" }`  

```
        function onInput( e ){
            var value = e.detail.value;
            tagify.settings.whitelist.length = 0; // reset the whitelist

            // https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort
            controller && controller.abort();
            controller = new AbortController();

            // show loading animation and hide the suggestions dropdown
            tagify.loading(true).dropdown.hide.call(tagify)

            fetch('https://example.com/tags.api', {signal:controller.signal})
                .then(RES => RES.json())
                .then(function(whitelist){

                    tagList = whitelist.data

                    tagify.settings.whitelist = tagList
                    tagify.loading(false).dropdown.show.call(tagify, value); // render the suggestions dropdown
                }
            )
            }

             tagify.on('dropdown:select', e => {
                console.log(e.detail);
             })
```

![image](https://user-images.githubusercontent.com/34626292/87403667-1167f700-c5b5-11ea-83e8-8126e5f7b616.png)

**Comment by yairEO** [comment]
Hi, which version of tagify are you using? I've places a issue template especially for it to be easier for me to help people, so you shouldn't have deleted it and pasted your own content instead.. anyway I am aware of the problem and am working on it right now

**Comment by tom-byrom** [comment]
Ahh apologies @yairEO . 

Version:  Tagify (v 3.14.1)

**Comment by yairEO** [comment]
Try now with version `3.14.2`
