### ISSUE TITLE
Tagify suggests undefined

### ISSUE THREAD

**Issue by Yahatix** [yairEO/tagify#574]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
Can be reproduced on the demo page

### Explanation

- **What is the expected behavior?**
Typing "un" in the keyword field should not suggest undefined when it is not in the whitelist

- **What is happening instead?**
undefined is being suggested

- **What error message are you getting?**
none

**Comment by yairEO** [comment]
Thanks, i'll fix it right now

**Comment by tom-byrom** [comment]
Hi @yairEO I'm using the latest version 3.15.3 and I don't think this is fixed.

If I type 'un' it suggests all tags and recommends the word 'undefined' is this normal behaviour?

**Comment by yairEO** [comment]
Hi Tom, maybe you didn't update correctly? make sure you are really really using `3.15.3`

I specifically fixed it and checked. it doesn't happen in the [demo page](https://yaireo.github.io/tagify/) now.

## Demo page recording:

![screencast 2020-07-15 12-28-14](https://user-images.githubusercontent.com/845031/87528832-c1616100-c696-11ea-87c6-6b767a9d0e9c.gif)

**Comment by tom-byrom** [comment]
100% double checked I'm using files from the master copy 3.15.3

Although I just checked the actual file contents of the master files and the scripts still say 3.15.2??

![ezgif-4-af7f611176e1](https://user-images.githubusercontent.com/34626292/87538072-8d387100-c693-11ea-899f-ac370543a097.gif)

**Comment by yairEO** [comment]
this means you have a cache issue. The script version should be stated at the top of the file: `3.15.3`

https://github.com/yairEO/tagify/blob/master/dist/tagify.min.js

**Comment by tom-byrom** [comment]
Hmmm so I didn't download the 'master' file apparently but I downloaded from versions here:

![image](https://user-images.githubusercontent.com/34626292/87545463-e4dcd980-c69f-11ea-83e9-c6a665f136ab.png)

3.15.3 here does not have the 3.15.3 files

I since downloaded the actual master from the repository homepage and got the correct script.

**Comment by yairEO** [comment]
Why don't you use NPM? those releases sometimes aren't synced very good :p

**Comment by tom-byrom** [comment]
haha I guess you can say I'm still learning. One day at a time my friend.

But thanks  - it is indeed all working!

**Comment by yairEO** [comment]
I am relieved I was found not guilty of bug-making in public

**Comment by tom-byrom** [comment]
I jumped the gun, really sorry - so it's not recommending 'undefined' as a word in the input anymore but still it gives me the dropdown with all tags?

Am I missing something else?

![ezgif-4-2c8abce36cc8](https://user-images.githubusercontent.com/34626292/87551751-b4e60400-c6a8-11ea-82ff-1ed32e37dfac.gif)

**Comment by tom-byrom** [comment]
If it helps im using the 
`position: "input",` setting

**Comment by yairEO** [comment]
I see, so the problem is that nothing is filtered

**Comment by yairEO** [comment]
Seems like [the demo](https://yaireo.github.io/tagify/#section-textarea) works fine

What is your unique _Tagify_ settings?

**Comment by tom-byrom** [comment]
Yeah I saw the demo works which has me wondering why. Could it be to do with the data?

Here is my Tagify code + the fetch to get the whitelist. PS. My total code is a lot more than this but I'm guessing only these bits will be affecting the suggestions.
```
        // Create tagify
        var inputElm = document.getElementById('tagifyField')
        var tagify = new Tagify(inputElm, {
            editTags: false,
            whitelist:[],
            maxTags: 10,
            dropdown : {  
                enabled: 2,
                maxItems: 5, 
                position: "input",
                fuzzySearch: false,
            },
        });

        // Create function to create & update whitelist from JSON url
        var updateWhitelist = function() {
            // Initial Fetch and update whitelist from url with JSON data
            fetch('https://example.com/tags.api')
            .then(RES => RES.json())
            .then(function(whitelist){
                // Target the data in the JSON array
                tagList = whitelist.data
                // Create whitelist from JSON array
                tagify.settings.whitelist = tagList
            });
        }

        // Initial call to update whitelist function
        updateWhitelist()
```

Here is how the JSON data looks from my URL

```
{
    "data": [
        {
            "value": "addnewtag"
        },
        {
            "value": "anewtag"
        },
        {
            "value": "another"
        },
        {
            "value": "art"
        },
        {
            "value": "artdirection"
        },
        {
            "value": "artdirection]]]]]]]]]]"
        },
        {
            "value": "asasd"
        },
        {
            "value": "goodtag"
        },
        {
            "value": "hello"
        },
        {
            "value": "i"
        },
        {
            "value": "korg"
        },
        {
            "value": "lklkj"
        },
        {
            "value": "marketing"
        },
        {
            "value": "mixwork"
        },
        {
            "value": "music"
        },
        {
            "value": "musictech"
       }
   ]
}
```

**Comment by tom-byrom** [comment]
@yairEO 

I just did a demo here. https://jsbin.com/lokikeneyi/edit?html,js,output

It's because of the `fuzzySearch: false` setting. Removing this settings and it works as it should.

**Comment by tom-byrom** [comment]
@yairEO hi mate - sorry just checking you saw the above? As this is still marked as 'closed'

It is def a bug that can be reproduced using the demo. When fuzzySearch is set to false it shows all tags when typing 'un'
