### ISSUE TITLE
Add minTags as configuration option

### ISSUE THREAD

**Issue by Yahatix** [yairEO/tagify#575]
It would be nice if i could specify a minimum amount of Tags which a user has to enter to make the field valid

**Comment by yairEO** [comment]
This is outside the scope of Tagify. I cannot prevent a form from being submitted from within Tagify, and at the end, Tagify is simply using an `<input>` or `<textarea>` hidden element with synced value to the tags themselves.

You, as the developer, should validate it yourself. on your `submit` event callback you can check the `tagify.value.length` (assuming *tagify* is the variable of your Tagify instance)
