### ISSUE TITLE
whitelist allow value already set on load

### ISSUE THREAD

**Issue by waterboy550** [yairEO/tagify#581]
I have a question, I am generating a whitelist of values that should be acceptable for a user to enter into a text input. Here is my issue. 

Say I'm asking the user for their favorite fruit to keep it simple. I have many fruits in my database and get a whitelist of all "active" fruits in the database. Lets say a user entered in a response and it was accepted, they can go in and edit their response whenever they want. Now say, I disable the fruit they selected while it was active. This fruit would no longer be in the whitelist. If the user went to edit their response, the entered fruit would immediately be taken out of the text area as it no longer is in the whitelist. Is there any feature or easy way to correct this issue?

The real issue is more complex than just editing the whitelist for each user to see if they have a previous response. The example above is much more simple than the real function. Basically, looking for a way to get tagify to leave existing text if it exists and assume it is in the whitelist.

**Comment by yairEO** [comment]
I don't understand anything. what does a "response" mean? Are you talking about tags? why are you using the word "response"? 

What does it mean *"I disable the fruit they selected"*? what is "disabled" mean....when does this happen..?

> This fruit would no longer be in the whitelist.

When are you updating the whitelist? at what point exactly (what happened that made you update it)?

> the entered fruit would immediately be taken out of the text area

What do you mean *"text area"*? are you using Tagify in `mix` mode?

**Comment by waterboy550** [comment]
Ok, so here as an example. I set the whitelist as (bananna, apple, grape). The user selects their answer and I save it in my database. Then they go to edit their answer at a later time, their previous answer is in the text field as they are editing it. This works as the whitelist is the same. 

Now, lets say I for some reason make the whitelist (bananna, apple). A user who previously answered grape and that value is stored in my database wants to edit their answer. When the text field is shown with grape already populated, it is then removed by tagify as it is no longer in the whitelist. 

Can tagify be setup to allow the original text value if not in the whitelist while enforcing a whitelist for all other values?

**Comment by yairEO** [comment]
You can set the `keepInvalidTags`[setting](https://github.com/yairEO/tagify#settings) to `true` and Tagify will not remove it. I am guessing you've set the `enforceWhitelist` to `true` and this is why tags are being removed.

Does this helps?
