### ISSUE TITLE
How to separate suggestions and whitelist

### ISSUE THREAD

**Issue by MohitKumar1991** [yairEO/tagify#582]
Hello I have not found a way to separate my suggestions from whitelist. 

Basically I want to show a list of suggestions which are invalid inputs. For instance I want to show a city name but the user has to add his own district code with the city name before it can be used as a tag. 

I have been trying for hours but haven't found a way to do this. Please help

**Comment by yairEO** [comment]
A list of suggestions where no suggestion may be selected? ever?

**Comment by yairEO** [comment]
The `enforceWhitelist` setting is `false` by default so a user many add any tag they wish.

Do you want the users to select items from the suggestions list, but those will **not** become tags but simply use that value as the text, so the user may continue typing?
