### ISSUE TITLE
React version without CSS

### ISSUE THREAD

**Issue by danqing** [yairEO/tagify#583]
I created #528 before which is now closed, but I still want to request for a React wrapper without CSS.

Up until version 3.15.2, I've been using a patch file like the one below to manually remove CSS after installing. However, the React wrapper is now minified (a good thing!), and patching it becomes a lot harder.

```patch
diff --git a/node_modules/@yaireo/tagify/dist/react.tagify.js b/node_modules/@yaireo/tagify/dist/react.tagify.js
index 1a39a07..e37b036 100644
--- a/node_modules/@yaireo/tagify/dist/react.tagify.js
+++ b/node_modules/@yaireo/tagify/dist/react.tagify.js
@@ -25,5 +25,3 @@
 var _tagifyMin = _interopRequireDefault(require("./tagify.min.js"));

-require("./tagify.css");
-
 function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
```

We discussed this in #528 - ideally next.js (that I rely on) should allow importing CSS. However, that is not a possibility in the near future.

I know removing the CSS for everyone may not be desirable. I want to ask if we can have a separate React file without the CSS, and then the main React file can just import that file + CSS? This way people who don't need or can't load the CSS can simply use the file without it.

Thank you!

**Comment by yairEO** [comment]
I totally agree and will decouple the CSS from the React wrapper

**Comment by danqing** [comment]
Awesome. Thank you @yairEO !
