### ISSUE TITLE
Cannot build project using Gulp by following steps in documentation

### ISSUE THREAD

**Issue by scscgit** [yairEO/tagify#586]
I want to build the project to test my changes, but the `"scripts"` in `package.json` contains `"start": ""`, and the documentation says "[Simply run gulp in your terminal, from the project's path (Gulp should be installed first).](https://github.com/yairEO/tagify#building-the-project)", but I'm getting the following error 

```
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\TagifyPath\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\TagifyPath\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\TagifyPath\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

This was tested on several different computers with the same results, and I can't find any other way to build the project.

By the way, I'd also suggest using `npx` to avoid forcing users to install the tool globally (locking it on a single version) while still letting them to do so, by adding it to the `"scripts"` section of package.json; optionally also replacing the `http-server` by `npx http-server` (possibly using a fixed @version) in ` "serve": "npx http-server -o -c-1"`, and possibly automating the build process using a free CI/CD service like GitHub Actions - you're also missing the `package-lock.json`, which would be required by a `npm ci` command in order to avoid unexpected version upgrade by `npm install`.

**Comment by yairEO** [comment]
Which gulp version do you use? it must below v4

**Comment by yairEO** [comment]
`http-server` - I will remove it, it isn't necessary.

Most of the gulp was written years ago and I was planning to upgrade to gulp V4 but it's not a smooth transition, many things doesn't work and I need to invest time trying to make it work

**Comment by scscgit** [comment]
\> npx gulp --version
> [16:12:35] CLI version 3.9.1
> [16:12:35] Local version 3.9.1

**Comment by yairEO** [comment]
I have been using multiple machines (all **windows**) to run Gulp for this project at, and it works well

**Comment by yairEO** [comment]
I've completely re-wrote the gulpfile after upgrading to Gulp `v4`, so i'm closing this because it most likely solved it
