### ISSUE TITLE
React - Textarea - Paste any text cause an error

### ISSUE THREAD

**Issue by grq** [yairEO/tagify#589]
**Steps to reproduce**

1. Go to [your React demo on SandBox](https://codesandbox.io/s/tagify-react-wrapper-oempc);
2. Click "Mix-Mode tags";
3. Try to paste any text to the textarea.

**Actual Result**

You will see `e.deleteContents is not a function`. This happens always and with any configuration in mixed mode.

**Expect Result**

The `Paste` operation should work.

**P.S.**

Thanks for your product! It's wonderful, despite this small issue! 👍

**Comment by yairEO** [comment]
Thanks for reporting, will be handled!

**Comment by yairEO** [comment]
Tagify version `3.16.0` fixed it :)
