### ISSUE TITLE
document.querySelectorAll throws TypeError

### ISSUE THREAD

**Issue by anmolonline** [yairEO/tagify#590]
I am trying to use 

`var input = document.querySelectorAll('.class1'),`

instead of the default document.querySelector as I need to use tagify multiple times on the same page. As I understand, querySelector only selects the first element & ignores the rest, hence I am trying to use querySelectorAll but without any success. I have tried multiple variations of the same but end up with the following error in console:

`Uncaught TypeError: i.hasAttribute is not a function
    applySettings http://localhost/test/dist/tagify.min.js:7`

Some help in this would be appreciated or some guidance in how to call Tagify multiple times on the same page.

**Comment by yairEO** [comment]
`querySelectorAll` returns an array-like result, and you must iterate those items and apply Tagify to each.

Something like this:

```js
document.querySelectorAll('.class1').forEach(node => {
	new Tagify(node)
})
```
