### ISSUE TITLE
when typing, cursor moves to end of string on every keystroke

### ISSUE THREAD

**Issue by andyford** [yairEO/tagify#591]
When typing a not-yet-created tag and you move the cursor to somewhere inside the string, the cursor jumps to the end of the string after typing just one character. (this does not seem to happen when editing a pre-existing tag)

animated gif:
![tagify-cursor-jump](https://user-images.githubusercontent.com/49811/88332453-e147f300-cd2e-11ea-9e4a-7c24852b6e7b.gif)

## Prerequisites

- [√ ] I am running the latest version
- [ √] I checked the documentation and found no answer
- [√ ] I checked to make sure that this issue has not already been filed

### Demo Page
Can be observed on the official demo https://yaireo.github.io/tagify/

### Explanation

- **What is the expected behavior?**
if you move the cursor to somewhere inside the string, the cursor should not jump to the end of the string after typing one character (or any number of characters)

- **What is happening instead?**
if you move the cursor to somewhere inside the string, the cursor jumps to the end of the string after typing one character

- **What error message are you getting?**
none

**Comment by yairEO** [comment]
Thanks for reporting! I will release a fix tomorrow.

**Comment by andyford** [comment]
wow that was a fast response! Thank you!

**Comment by andyford** [comment]
thanks for fixing! It works as expected now 👏
