### ISSUE TITLE
Use of dropdown.searchKeys stricly

### ISSUE THREAD

**Issue by sdev-maxime** [yairEO/tagify#592]
Hi,
With the actual config of dropdown.searchKeys, we only can add more.

Documentation config:
```
{
  dropdown: {
    searchKeys: ["nickname", "email"] // "value" & "searchBy" key are searched in, regardless
  }
}
````

The use case I have. I got customers objects collection with UUID for the value. So it contain some letters. And need to search on firstname.

The config:
![dropdown](https://user-images.githubusercontent.com/52406045/88390677-0bde8e00-cdb9-11ea-9a14-b1f4926d5af7.png)

This gives ambiguous results and it would be appreciable from a UX / UI point of view to be able to strictly search in the fields filled in. I know this is detail, and not really blocking for use.
Maybe there is a workaround to do that, or I missed something, so be free to explain it to be clean (with dropdown.enable = 1 plz)

Example of ambiguous result.
![search_ambigous](https://user-images.githubusercontent.com/52406045/88390482-adb1ab00-cdb8-11ea-9b17-acef43b79b5d.png)

To the pleasure.

**Comment by yairEO** [comment]
I see, so you want **only** to look at those properties in the list and not the value.
I will make the change
