### ISSUE TITLE
wrong index on remove event

### ISSUE THREAD

**Issue by SamueleD78** [yairEO/tagify#593]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

When i remove an item, i get -1 index in the remove event, no matter what i do

![Peek another](https://user-images.githubusercontent.com/65371710/88470161-4ea77f80-cef9-11ea-92be-0f71a79e9158.gif)

**Comment by SamueleD78** [comment]
Again, really superfast, thank you! And thank you for your job i really apreciate it.

A question: looking at the code (before the fix) i saw you were considering the index after the animation. But events are useful mainly for applications that make uses of data. So, is it really important what index is *after* the animation it's done?
In my application, for example, it's far more important to know what was the index when the user queried for the deletion, than the one after the animation it's done.
What do you think about?

**Comment by yairEO** [comment]
I wanted to keep events similar, and they are all (I think) happen at the end of their logic segment, so for example, `add` tag event happens after a tag has been added and same for `remove`. 

If you want to do something ***before*** a tag was removed you have hooks for that, that I designed to be a place where a developer have the ability to manipulate things by intervening at a certain point in time using promises.

At this point of time I've only implemented 2 hooks which I believe to be useful: `beforeRemoveTag` & `suggestionClick`

So in your case, you can use `beforeRemoveTag` 

Does it answer your question?

**Comment by SamueleD78** [comment]
Ehehe yes, it's a design coiche and i respect that. Honestly i didn't looked at the hook, of course it can be the solution.
Thank you so much, you are really kind ^^
