### ISSUE TITLE
Input doesn't unselect when remove element with focus

### ISSUE THREAD

**Issue by SamueleD78** [yairEO/tagify#594]
If the css is not loaded, when i remove an item from a control **without** focus, everything work flawlessy.

When i remove an item from a control **with** focus, the input get stuck and keep it's focus, disallowing further adding tags (no caret, etc).

![Peek 26-07-2020 04-03](https://user-images.githubusercontent.com/65371710/88469802-5cf39c80-cef5-11ea-95fb-fbc89c828d55.gif)

**Comment by yairEO** [comment]
Maybe it's a CSS issue. try removing browser Cache. I cannot reproduce this bug.

**Comment by yairEO** [comment]
Ok I see now what you mean about the focus. I will fix it.

**Comment by SamueleD78** [comment]
Superfast! Thank you so much!
