### ISSUE TITLE
Every tag entered adds &nbsp;

### ISSUE THREAD

**Issue by rishitank** [yairEO/tagify#595]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

Currently when adding a tag it adds an `&nbsp;` to the DOM. When removing the tag it does not remove them, which in turn accumulates unnecessary `&nbsp;` for each tag that was added. This makes the tag indent and result in inconsistent behaviour.

**Comment by yairEO** [comment]
I forgot some experiment I did and accidently pushed the code. I forgot to test afterwards. so sorry, thanks for reporting!
