### ISSUE TITLE
Populate input with json object

### ISSUE THREAD

**Issue by Ignatus** [yairEO/tagify#597]
Hello,

I use Tagify with a whitelist composed of object like this :
`[{'id' :  23, 'value' : 'TagA'},{'id' : 42, 'value' : 'TagB'},{'id' :  63, 'value' : 'TagC'}]`

These tags are used in a blog post (typical example).
I type "TagA", select it in the list, it's OK.
I type "TagC", select it in the list, it's OK.

I save it in my DB. No issue, all is allright

I want to re-edit the post and of course, my tagify input must have the previous tags saved.

 If i fill the input like this : `<input name="tagifyInput" value="TagA, TagC"/>`, tags are correctly recognized and formatted but it's considerated as"new" tags. As you can see above in my whitelist, each tag have an "id", and in this case, the id is not recovered (and so, not sending when i i save my edit)

If i fill the input like this : `<input name="tagifyInput" value="{'id' :23,'value':'TagA'},{'id': 63,'value' : 'TagC'}"/>`, tags are not recognized (the presence of comma in the json object is the issue).
![image](https://user-images.githubusercontent.com/6153886/88776520-5c256980-d186-11ea-90f2-8ca100d6ab71.png)

Have you got a solution ? 

Thanks !

**Comment by yairEO** [comment]
You must use proper JSON format. **Proper** JSON format **must** wrap keys and strings with `""`

   value='{"id" :23,"value":"TagA"},...'

**Comment by Ignatus** [comment]
Ok.
So i have a new issue with Twig, which automatically replaces apostrophe by quote in input fields 😄 
Thanks for your answer !
