### ISSUE TITLE
Adding tag programmatically

### ISSUE THREAD

**Issue by bobrinch** [yairEO/tagify#6]
Hi

I know I can add tags when rendering the tagify component, like so:

`<input name='user-tag' value='apple, orange, banana'>`

But in my case, I have a service which returns tags to show, but unfortunately this returns after the tagify component has been rendered. So I would need to add the tags later programmatically, like

`$('[name=user-tag]').Tagify.addTag('kiwi');`

But this is currently not possible. Can this feature of adding tags programmatically be implemented?

Thanks :+1:

**Comment by yairEO** [comment]
jQuery plugins cannot do things like `$('[name=user-tag]').Tagify.addTag('kiwi')` (won't get into that) but you can definitely add tags:

    $('[name=user-tag]').tagify();
    $('[name=user-tag]').data('tagify').addTag('aaa, bbb, ccc')

**Comment by yairEO** [comment]
@QuadTriangle - Added - https://github.com/yairEO/tagify/blob/master/README.md#jquery-version
