### ISSUE TITLE
Keep user input after selecting from dropdown

### ISSUE THREAD

**Issue by joncarlson** [yairEO/tagify#600]
We have a case where the user is selecting many tags with the same prefix from a long list. Currently, the user has to type in the prefix each time, is there a way to keep the dropdown open without clearing the users input so they can select these tags all at once?

Here's an example list of tags to demonstrate: `a_1, a_2, a_3, a_4, b_1, b_2, b_3, b_4, b_5, c_1, c_2, c_3, c_4, c_5`

If the user wanted to select all the tags that start with `b_` they currently have to type in `b_` for each one. Keeping the user input there would mean they could quickly select all the `b_` items.

If this functionality isn't there, I could submit a PR to add it.

**Comment by yairEO** [comment]
Are you talking about mix-mode?

**Comment by joncarlson** [comment]
No, I didn't describe it well enough.

I have closeOnSelect = false, which is great, but after selecting an item, the autosuggest list changes (user input is cleared). I want the autosuggest list to stay the same (keep the user input, don't clear it after select).

**Comment by yairEO** [comment]
I am working on your request dear sir
