### ISSUE TITLE
Prop Type console warning in React Wrapper Mix-Mode Tags

### ISSUE THREAD

**Issue by PrateekArora03** [yairEO/tagify#603]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation
I used Tagify for my project but while using Mix-Mode tag it is showing a warning in the console.

The below code sandbox is a demo example from the documentation
Code [here](https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/MixedModeTagify.js)
Demo link [here](https://oempc.csb.app/MixedModeTagify)

Warning screenshot is below:-
![image](https://user-images.githubusercontent.com/25227096/89062624-69a84280-d384-11ea-8e31-4c72c5c6fb02.png)

- **What error message are you getting?**
`Failed prop type: Invalid prop `children` of type `string` supplied to `r`, expected a single ReactElement.`

**Comment by yairEO** [comment]
Checking, thanks

**Comment by yairEO** [comment]
Fixed. replaced with:

```jsx
<Tags
      InputMode="textarea"
      settings={settings}
      className="myTags"
      onChange={onChange}
      value={`
        This is a textarea which mixes text with [[{"value":"tags"}]].
        <br>
        To add a [[{"value":"tag"}]], type "@" and a (Latin) character
        <br><br>
        <small>(Only tags from the <em>whitelist</em> are allowed. <em>Whitelist</em> contains names of Southpark characters.)</small
        <br>
        <small>(Open this demo in a full-window to be able to type new-line returns)</small>
      `}
/>
```
