### ISSUE TITLE
Large number are truncated

### ISSUE THREAD

**Issue by mb845** [yairEO/tagify#605]
### Demo Page
https://jsbin.com/xeyikeyoba/edit?html,js,output

### Explanation
- **What is the expected behavior?**
When a large number is entered, we expect a tag with this exact value.

- **What is happening instead?**
Currently, when a large number is entered, the created tag is a truncated. This error is due to JSON.parse at line 244.

**Comment by yairEO** [comment]
I don't see this happening in your demo page

![image](https://user-images.githubusercontent.com/845031/89330204-96b46800-d698-11ea-92f0-fa7432d6302b.png)

**Comment by yairEO** [comment]
It not "truncated" but apparently it is being converted to a *Number* and javascript has a maximum number limit, so it appears to output a different value. I will fix this.
