### ISSUE TITLE
  when I remove first word in third line, the cursor jump to previous line

### ISSUE THREAD

**Issue by amadea-mahestri** [yairEO/tagify#606]
## Prerequisites

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Demo Page
![a3bbab89-aa47-467f-8f57-d2abf0968729](https://user-images.githubusercontent.com/845031/89384146-54297480-d706-11ea-84a9-ac53d128012c.gif)

https://jsbin.com/cututozafe/1/edit?html,js,output

### Explanation
let say I have default value in textarea
```
<textarea name='mix'>
  -test [[{"id":101, "value":"cartman", "title":"Eric Cartman"}]] and 
  -[[kyle]] do not know [[homer simpson]] 
  -because he's a relic.
</textarea>
```
when I remove first word in third line, the cursor jump to previous line, see pict. thank you :)

**Comment by yairEO** [comment]
The cursor cannot jump, you mean the caret jumps. the cursor is your mouse or touchpad
