### ISSUE TITLE
Display/behaviour questions

### ISSUE THREAD

**Issue by pcolmer** [yairEO/tagify#608]
I'm trying/hoping to use tagify as a group manager/user picker in a React app. The idea is that the tag field will be the list of people in a group. To add someone to the group, you start typing their name and then pick them from the dropdown.

The general principle is working but there are some niggly issues which I'm hoping are just settings I need to tweak or some extra code (e.g. handlers) that I need to write.

1. If I start typing and then click away, whatever I've typed gets added as a tag. In theory, I could use the "enforce whitelist" option to prevent this *but* that would then cause problems when I initialise the tag field with the existing list of people because, at that point, the whitelist would be empty.

2. I've set the whitelist to have a value and a displayName. I've configured the dropdown to use the "displayName" field from the whitelist. However, when the tag is added to the tag field, it is displayed using the value. I *think* this is solved by using "transformTag", and I've tried `data => data.displayName` but that doesn't work.

3. I've set `dropdown.enabled` to 1. When I type the first letter, `onInput` builds the whitelist and it gets displayed in the dropdown. However, if the whitelist had previously been populated, the dropdown initially shows anything that matches that first letter. Going off how the whitelist is set when I have a built list, I've tried this;

```
      setTagifyProps(lastProps => ({
        ...lastProps,
        whitelist: [],
        loading: true,
        showDropdown: false
      }))
```

What is strange is that `loading: true` works (the spinner appears) but the dropdown still shows and it isn't empty.

Thank you in advance for any suggestions you can make.

**Comment by yairEO** [comment]
1. set `addTagOnBlur` setting to `false`
2. You should probably [make your own `tag` template](https://github.com/yairEO/tagify#dom-templates) to print some other property (other than "value")
3. setting `loading` to `false` doesn't hide the suggestions dropdown, it only controls the loading animation's visibility. I don't entirely understand the scenario in this section. Maybe you should set the `dropdown.fuzzySearch` setting to `false`?

`OnInput` -> `setTagifyProps` -> `whitelist: []`  = should clear the whitelist so no character input the dropdown will not be rendered because the whitelist is empty, and only after the server brings a new list, you should manually set the `showDropdown` pop to `true` and only then *Tagify* will show the dropdown

**Comment by pcolmer** [comment]
> set addTagOnBlur setting to false

Thank you for this. It solves the precise situation I described, but I omitted that pressing Return also creates a tag with the text typed so far. Is there a way of either disabling that behaviour?

> You should probably make your own tag template to print some other property (other than "value")

Thank you - I've just copied the `tag` template and done just that. Works perfectly.

> setting loading to false doesn't hide the suggestions dropdown

I apologise if I confused the situation. In my `onInput` function, the code starts with:

```
      setTagifyProps(lastProps => ({
        ...lastProps,
        whitelist: [],
        loading: true,
        showDropdown: false,
      }))
```

What I was saying was that the loading animation becomes visible, so this code is doing **something** ... but it doesn't appear to be clearing the whitelist, because the whitelist starts immediately to show any possible matches before the data has finished loading from the network.

**Comment by yairEO** [comment]
> because the whitelist starts immediately to show any possible matches

What is the scenario in which this happens? what steps does the user do?

**Comment by pcolmer** [comment]
> What is the scenario in which this happens? what steps does the user do?

I've created a screengrab video of the behaviour:

![cTgw3qYXBf](https://user-images.githubusercontent.com/1979931/89790621-18cde200-db1a-11ea-90ca-ef2c3ad3049e.gif)

As you can see, when the search starts, the dropdown is immediately visible with whichever entries were already in the whitelist that match what has been typed.

> Why do you fetch users every time the person is typing? is it not better to fetch all the users at initialization?
A compressed request with a full list will "feel" much faster to the user than multiple "small" requests.
(assuming there are no more than a few thousands)

I'm partly taking this approach because I'm not sure what the number of users in the system is going to end up being. I know the hope is that there could be many thousands, in which case loading the full list each time could be challenging.

I may well change it to a full list if conditions change.

**Comment by pcolmer** [comment]
> If I start typing and then click away, whatever I've typed gets added as a tag. In theory, I could use the "enforce whitelist" option to prevent this but that would then cause problems when I initialise the tag field with the existing list of people because, at that point, the whitelist would be empty.

I've solved this one now. Since I've configured it not to allow duplicates, the dropdown will only show results that are not already in the tag field. Therefore, the solution was to add all existing tags to the whitelist, as well as whatever got returned from the `fetch` call. That then allows me to enforce tags against the whitelist.

**Comment by yairEO** [comment]
Correct :) So logical and simple, and yet frustrating holdback to figure out.
