### ISSUE TITLE
Problem using mix-mode and delimiters together

### ISSUE THREAD

**Issue by nickstranger** [yairEO/tagify#609]
- [x] I am running the latest version
- [x]  I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Delimiters have no effect if mix-mode is selected. The documentation does not say that these two properties cannot be used together. Is this behavior intended?

I am trying to create an input where the user can enter text and hashtags (which must start with "#"). In my UX case, the user can add a hashtag by pressing the space or the symbol "," which will mean that hashtag is over and needs to be added. But it seems like delimiters don't work with mix-mode.

Example with with problem: https://jsbin.com/boxafuqomi/edit?html,js,output

**Comment by yairEO** [comment]
I understand, and will examine the code now to see what can be done to quickly assist you

**Comment by yairEO** [comment]
Do you want the comma delimiter to be ignored & erased and a tag created without a comma after it?

**Comment by nickstranger** [comment]
Delimiter char would be a part of text, not part of tag. Like
**tag1**_, text1,_ **tag2**

Tags can be absolutely new if fetching suggestions from a server is empty; and tags can be picked from suggestions if server return some variants

**Comment by yairEO** [comment]
I have been working on this for many hours, it is quite difficult. I did not do this in the first place because of the level of difficulty involved. It might not seem difficult, and very trivial, but trust me, there are browser quirks of unimaginable annoyance involved.

**Comment by eugenetraction** [comment]
@yairEO I'm having an issue with commas as well. But in my case a tag can have a comma. For example "Brainstorming, meeting". But as soon as I hit enter it trims to "Brainstorming". Is there any way to make it include commas in tags?

**Comment by yairEO** [comment]
@eugenetraction - I will be fixed today with a new version release

**Comment by eugenetraction** [comment]
@yairEO Woops, I got a bit confused. `delimeters: null` setting solved my problem, I am using mixmode. Apologies for the confusion!

**Comment by yairEO** [comment]
@eugenetraction - I've made it now the default for mix-mode, will push soon, am working on it now

**Comment by nickstranger** [comment]
@yairEO delimiters work for me now. Thank you!

**Comment by Enigmaticall** [comment]
@yairEO these delimiters work, but only once you've started typing the next word. If I have a space as a delimiter, I would like it to instantly create a tag so the user gets the feedback that it worked before they start typing the next tag. I have received this feedback from multiple users, would that be possible? Thanks in advance!

**Comment by yairEO** [comment]
@Enigmaticall - The answer is written in #1049
