### ISSUE TITLE
Package missing from npm registry

### ISSUE THREAD

**Issue by giaunguyen2176** [yairEO/tagify#610]
Does any body have this issue, I try to install the package this afternoon and suddenly the package was not found.

npm ERR! code E404 
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@yaireo%2ftagify - Not found 
npm ERR! 404  npm ERR! 404  '@yaireo/tagify@^3.4.0' is not in the npm registry. 
npm ERR! 404 You should bug the author to publish it (or use the name yourself!) 
npm ERR! 404 It was specified as a dependency of 'aduro-coaching-dashboard' 
npm ERR! 404  
npm ERR! 404 Note that you can also install from a 
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by yairEO** [comment]
I see `3.4.0` exists in the [NPM registry](https://www.npmjs.com/package/@yaireo/tagify) so I guess it was a problem with their servers..

Try to changing your Tagify version to the latest (in `package.json` file) and re-install
