### ISSUE TITLE
Readonly tags are removed

### ISSUE THREAD

**Issue by eugenetraction** [yairEO/tagify#613]
## Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/vitixocavi/edit?html,js,output

### Explanation
Readonly tags are deleted by Backspace/Delete key. This happens in mixed mode and textarea input.

**Comment by yairEO** [comment]
After 3 years of working on this code almost daily, I have never thought of anyone using `readonly` tags in mix-mode. 

What is the use-case for this, may I know?

**Comment by eugenetraction** [comment]
@yairEO 😄 There is a limitation on server side that only allows to create a record with a specific tag id, but not update. We still want user to update other text/tag content, but just not one specific tag..

I tried to use beforeRemoveTag hook, but unfortunately it is not called on Backspace/Delete, only on mouse click X icon :(

Any suggestions for a workaround?

**Comment by yairEO** [comment]
It is quite a difficult situation. a user can select all the text and then paste something else instead or simply cut it out.

To make a certain tag completely "immune" to deletion in mix-mode I would have to probably use *mutation-observer* API and somehow detect a read-only tag was removed and then re-add it. the question is, where to re-add it to....

## For example:

1. "aa [readonly tag] bb cc [normal tag] dd ee"  
2. "aa <del>[readonly tag] bb cc [normal tag]</del> dd ee"  (user selected a part and cuts it out)
3. "aa | dd ee"   (`|` is the caret)
3. "aa [readonly tag] dd ee"  (readonly tag was re-inserted)

I can work on this but it will take some time..

**Comment by eugenetraction** [comment]
Is it possible to disable selection and only have control over Delete/Backspace/X icon?

I think it would work for our case. The only problem is Delete/Backspace is not firing `beforeRemoveTag`

Example:
https://jsbin.com/roqisekume/1/edit?html,js,console,output

**Comment by yairEO** [comment]
I don't think it is possible to disable selection because then you'll "lose" the Caret and the user will be unable to type/paste text.

To make `beforeRemoveTag` work for mix-mode deletion of tags by selection it would require to prevent the default behaviour and to delete the content "manually" (programatically). I will investigate the feasibility of this approach and keep you posted.

**Comment by yairEO** [comment]
Fixed as part of version `3.19.0`

Demo with readonly tags in mix-mode:

https://jsbin.com/zuyifov/2/edit?html,js,output

**Comment by gl0dt** [comment]
I think this is only partially fixed. If you click on a read-only tag and press backspace, the tag will still be removed
