### ISSUE TITLE
Enable Tab key to go to next form input

### ISSUE THREAD

**Issue by danielcongrove** [yairEO/tagify#616]
When nothing new is entered into a tagify input, is there a way to enable pressing the Tab key to go to the next form field? Or Shift + Tab to go the previous input?

It makes it difficult for keyboard only users to navigate the form.

**Comment by yairEO** [comment]
It was enabled, must be a regression. will fix it now, thanks for reporting!

**Comment by danielcongrove** [comment]
Confirmed. That was really quick. Thank you for fixing! 👏
