### ISSUE TITLE
Tracking invalid tags

### ISSUE THREAD

**Issue by aleczratiu** [yairEO/tagify#625]
Is there a way to keep track all invalid tags, if the tag has been deleted, edited or passed while adding a new tag to know how many tags pass the regex pattern and how many not.

> My scenario: 

I paste a list of emails and I can go to next step to do some actions just when all tags pass the regex pattern.

On **value** property I found all tags which passed the pattern also invalid tags is not there but exists `__isValid: true` why ?

Another way is to use `inner-methods` **getTagElms()** to get a NodeList and map overall to find if exists a class `tagify--notAllowed`, let me know if exists another way to keep track all invalid tags.

**Comment by aleczratiu** [comment]
Indeed **invalid** event return the current invalid value, it would be awesome to have a list like valid list with values `ref.value` [0: {value: "email@test.com", __isValid: true}].

I can store all values from  **invalid** cb, but I should track all actions like (edit/delete) to check if pass the regex pattern and also if that tag initial was invalid should be deleted from stored invalid values.

Right now I make a validation based on class `tagify--notAllowd` in handleHook function which is called at (invalid/add/remove/'edit:updated') cb to keep track invalid tags.

I used this validation just to enable/disable a submit form button.

**handleHook fn**:
```
const tagNodes = [...tagifyRef.current.getTagElms()];
const invalidTags = tagNodes.some((node) => node.classList.contains('tagify--notAllowed'));
```

```
 const settings = {
        pattern,
        placeholder,
        delimiters,
        dropdown: {
            enabled: 0,
        },
        duplicates,
        backspace,
        keepInvalidTags,
        callbacks: {
            invalid: handleHook,
            add: handleHook,
            remove: handleHook,
            'edit:updated': handleHook,
        },
    };
    <Tags tagifyRef={tagifyRef} InputMode="input" settings={settings} />
```

**Comment by yairEO** [comment]
Why do you need to track invalid tags?

**Comment by aleczratiu** [comment]
``
I only used this validation to enable / disable a form submission button.
``
If I add a some invalid tags, the submit button from form will be disabled. What happens when I add a new tag after which it is valid? The Submit button should be disabled because there are some invalid labels. How would you handle this case without tracking those invalid tags?

**Comment by yairEO** [comment]
No need check each individual event:

```js
callbacks: {
    invalid: handleHook,
    add: handleHook,
    remove: handleHook,
    'edit:updated': handleHook,
}
```

You can/should use the `onChange` event listener:

```js
<Tags tagifyRef={tagifyRef} InputMode="input" settings={settings} onChange={handleHook} />
```

and a simpler/shorter test inside `handleHook` can be:

```js
return tagifyRef.current.getTagElms().length == tagifyRef.current.value.length
```
