### ISSUE TITLE
Adding tags to a dynamic element.

### ISSUE THREAD

**Issue by gnomechompsky** [yairEO/tagify#626]
I'm using ag-grid with Tagify. I have an editable cell that I tagify when entering edit mode:

```
onCellEditingStarted: function (event) {
    if (event.column.colId == "tags") {
        var input = document.querySelector(".ag-text-area-input");
        tagify = new Tagify(input);
    }
}
```

Unfortunately, ag-grid is bound to the enter key (and it seems like every other key on the keyboard) by default. So on my tagify cell I use `suppressKeyboardEvent: suppressEnter`, the function looks like this:

```
function suppressEnter(params) {
    var KEY_ENTER = 13;
    var event = params.event;
    var key = event.which;
    tagify.addTags("test", true);
    var suppress = key === KEY_ENTER;
    return suppress;
}
```

I've added a `console.log()` to `appendTag()` to log `insertBeforeNode`. Running Tagify on an element in the DOM on page load, I see the following in console:

```
<span contenteditable="" data-placeholder="​" aria-placeholder="" class="tagify__input" role="textbox" aria-autocomplete="both" aria-multiline="false">
  ::before
  ::after
</span>
```

However, in my dynamically added to the DOM element, I see this:

```
<span contenteditable="" data-placeholder="​" aria-placeholder="" class="tagify__input" role="textbox" aria-autocomplete="both" aria-multiline="false">
</span>
```

In the already in the DOM element, the tag is added and the DOM is updated. In the dynamic element, no tag is added (i.e., the text remains typable letters) and the DOM is unchanged.

**Comment by yairEO** [comment]
Are you still in need of assistance?
