### ISSUE TITLE
Tags are not being deleted in mobile device

### ISSUE THREAD

**Issue by ssinghal1989** [yairEO/tagify#628]
When opening component in mobile device tags are not deletable with delete button.

**Comment by yairEO** [comment]
I've tried and they are deleted fine. maybe if you add some more important detail...?
start by telling me which device & browser clicking on `(x)` button does not work for you

**Comment by ssinghal1989** [comment]
Clicking on x works fine. But if you enter a tag and then you press delete
button on keyboard it doesn't delete the tag. And this is happening on all
mobile devices.

**Comment by yairEO** [comment]
Just tried <kbd>Backspace</kbd> on my *Android *Chrome** browser and it's able to delete tags

**Comment by simvol** [comment]
This is mixed in mixed mode only. Seems to be an android issue..

![image](https://user-images.githubusercontent.com/10889961/99491980-9c6d4b00-2921-11eb-9338-8722924eae10.png)

**Comment by yairEO** [comment]
@simvol - "android issue"? on which ***browser*** do you see this happening?

**Comment by yairEO** [comment]
@ssinghal1989 

> *Clicking on x works fine. But if you enter a tag and then you press delete*

What does *"enter a tag"* means..?

**Comment by eugenetraction** [comment]
> @simvol - "android issue"? on which _**browser**_ do you see this happening?

Chrome. But actually only happens with GBoard (google keyboard). It is reproducible on the demo in mixed mode https://yaireo.github.io/tagify/#section-mix

**Comment by yairEO** [comment]
This was an **extremely** difficult bug. Took me hours and a ton of research to figure out this insane Chrome issue on Android where the pressed key cannot be detected by javascript on `keydown` DOM event, and not only that, the browser lost focus and hid the onscreen keyboard when the delete key was pressed if the caret position was just after a *tag* element. 

The first one was very very difficult as it seems everyone gave up on this, and not a single solution was to be found online. 

The second issue with the hidden keyboard was also annoying without much information, but didn't consume much of my time, just a bit of playing around with `focus` triggering and following by manually triggering `click` in a *timeout*, and re-place the caret at the correct node (which is the textNode before the *tag* element).

The solution also had to consider *readonly* nodes.

Will deploy soon

**Comment by eugenetraction** [comment]
@yairEO this is amazing! Yeah it seemed a very complex issue, so I didn't expect you would tackle it so quickly. We'll make sure to test it thoroughly. Is there any way we could say our thanks? Beer/pizza/coffee?

**Comment by denismosolov** [comment]
I try to remove a tag in Google Chrome on Android by pressing "Backspace" on the screen keyboard.
Sometimes it works fine, but sometimes it just stuck.
Here is the screen recording.
https://drive.google.com/file/d/1hxECbS92BfEL_mCy28ZKLAmwmr7nle7m/view
I guess it stuck because of this?

> browser lost focus and hid the onscreen keyboard when the delete key was pressed if the caret position was just after a _tag_ element.

I'd like to fix, but not sure I understand why it removed the tags Homer Simpson and Cartman, but didn't remove the Kyle.

**Comment by yairEO** [comment]
@denismosolov - Thanks for the video, I will investigate
