### ISSUE TITLE
Tagifying should not happen at blur.

### ISSUE THREAD

**Issue by lordmikefin** [yairEO/tagify#63]
If user is typing tag in the field and moves focus to other component, then tag is created.

This is bit annoying because then you have to remove the tag and retype what you were originally typing.

There should be configuration setting for preventing the tagifying process on field blur.

Of course when tag is not automatically created, then the "last" tag must be created outside of tagify field.

Here is my sample code:

`	$( "#searchbtn" ).click( function(e) {`
`		// Make sure last input value is tagified.`
`		var text = tagify.DOM.input.value.trim();`
`		if ( text ) {`
`			tagify.DOM.input.value = '';`
`			tagify.addTags(text).length;`
`		}`
`	});`

**Comment by yairEO** [comment]
ok, I will make such configuration. 

I was certain this is what everybody wants, to have the tag created on `blur` event. 
This request surprises me. why would a user not finish to type a tag and leave the focus in the middle..? where's the logic in doing that..

**Comment by lordmikefin** [comment]
Yep, you are correct, that normally the tag should be created on `blur` event.

I have created my own "datalist" for the field.

I need different type of selections in the datalist. Suggested tags (what already exists in "real" datalist) and links.
Because I do not use "real" datalist I have to move focus from tagify field into the datalist.
This will create incomplete tag.

Special case -> special logic ;)

**Comment by yairEO** [comment]
See `addTagOnBlur` settings in the README
