### ISSUE TITLE
Can't paste text in mix mode

### ISSUE THREAD

**Issue by finaffiliate** [yairEO/tagify#631]
I have problems with pasting text in mix mode. 

Here in Tagify demo page, in "Mix Text & Tags" field I tried to paste text "User auth", but there are errors in console (see [image](https://imgur.com/a/H6nCPiw)). 

The main problem, when I try to submit form with pasted input, in controllers I receive null for this field. But if I just write (not paste) the same text - everything is ok.

**Comment by yairEO** [comment]
Please do not remove the bug-report template. I cannot help you without it. I am able to paste text into mix-mode:

![GIF](https://user-images.githubusercontent.com/845031/91218226-686afb00-e721-11ea-9e55-731dad4b83e7.gif)

**Comment by jvasekpn** [comment]
I too am seeing the same bug described in the original post.
![bug5](https://user-images.githubusercontent.com/45108468/91902436-55977f80-ec67-11ea-817a-11a2086dbb87.gif)
