### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by 8483** [yairEO/tagify#632]
I am trying to replicate [this example](https://yaireo.github.io/tagify/#users-list), but I am unable to.

Here's a [codesandbox with the error](https://codesandbox.io/s/kind-sunset-r1vum?file=/src/index.js). I just copy pasted the code from the example.

**Comment by yairEO** [comment]
you copied without the code...

Go to the codepen of that example and cone it

**Comment by 8483** [comment]
Thank you for the quick reply. You need to idiot proof the examples :)
