### ISSUE TITLE
Force lowercase input?

### ISSUE THREAD

**Issue by tom-byrom** [yairEO/tagify#634]
Hello mate,
Anyway you could easily force all tags inputted to be lowercase?
Cheers
Tom

**Comment by yairEO** [comment]
Hi dear internet friend, I hope you are well and find *Tagify* pleasing to work with.

You can use CSS to just render them with lowercase:

```css
.tagify__tag{
	text-transform: lowercase;
}
```

Then you can simply convert it to *lowercase* when you save them in your database.

---

If you want to force whitelist as a "rule" so users would literally have to type only lowercase and fix their own text, then can use a [regex pattern](https://stackoverflow.com/a/8694034/104380) in the *Tagify* `pattern` setting

---

Hope this helps

**Comment by tom-byrom** [comment]
Thanks for the help @yairEO thought something like this would be the solution. Cheers
