### ISSUE TITLE
fuzzySearch: false and typing 'un' returns all tags in whitelist.

### ISSUE THREAD

**Issue by tom-byrom** [yairEO/tagify#635]
## Prerequisites

- [3.17.8 ] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/lokikeneyi/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Typing 'un' returns all results in whitelist when fuzzySearch is set to false.

If you have a tag lets say 'underarmour' it won't recommend until you type at least 4 characters, otherwise it will show all results.

set fuzzySearch to true and works as expected.

**Comment by yairEO** [comment]
Thanks for reporting, I will look into it tomorrow, I'll be away from my computer until then
