### ISSUE TITLE
Find method not supported by IE

### ISSUE THREAD

**Issue by Heinmci** [yairEO/tagify#637]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Explanation

Ever since commit 8363810485809f0bfd716c930f1dbb1c39df3aa8, when using tagify on IE, we get a js error whenever we get into the "getWhiteListItemByValue" function because it uses the method "find" which isn't supported by IE.

- **What is the expected behavior?**
When using whitelists with tagify in IE, I expect to be able to add tags
- **What is happening instead?**
I'm getting a JS error 
- **What error message are you getting?**
“Object doesn't support property or method 'find'”

Thank you for all your hard work, it really is appreciated,

Regards

**Comment by yairEO** [comment]
Sorry, I will have it fixed asap!
