### ISSUE TITLE
Make the tag search work with keywords, rather than a continuous string

### ISSUE THREAD

**Issue by 8483** [yairEO/tagify#640]
Right now it seems that the tag search works only for continuous strings, not keywords.  

Ex.  For this parameter `searchBy: "The quick brown fox jumps over the lazy dog"`, the following serach `"own fox"` will work, whereas `"qui laz"` will fail, because it's not continuous i.e. `quick` and `lazy` have words between them.  

Here's the code for such implementation.  

```js

function keywordFilter(query, string) {
    let keywords = [];
    if (query) {
        keywords = query.toLowerCase().split(" ");
    }
    let keywordsFound = [];

    keywords.forEach((keyword) => {
        keywordsFound.push(string.toLowerCase().includes(keyword));
    });

    let allKeywordsFound = keywordsFound.every((keyword) => keyword);

    return allKeywordsFound;
}
```

**Comment by yairEO** [comment]
Good idea, but for this entry:

    searchBy: "The quick brown fox jumps over the lazy dog"

**must** it include both keywords `"qui laz"` or just one of them?

**Comment by 8483** [comment]
Damn, always with the quick reply.

Yes, all the keywords, that can be any string.

This is such a QOL improvement, it's perfect for the tags.  

I suggested the same idea [here as well](https://github.com/olifolkerd/tabulator/issues/2759), and it's awesome.

**Comment by 8483** [comment]
@yairEO I don't want to sound ungrateful, I'm just really excited about this addition and would love to know when we could expect this new feature?

**Comment by yairEO** [comment]
BTW, this can be achieved using less code with Regex:

```js
var query = "The quick brown fox jumps over the lazy dog"
var niddle = "qui laz"
fuzzyRegexPattern = new RegExp(niddle.replace(/ +/g, ".*"))

if( query.match(fuzzyRegexPattern) )
  console.log("WORKS")
```

**Comment by yairEO** [comment]
not yet but will be today/tomorrow.

You can also do another Regex (similar), Example:

```js
var query = "The quick brown fox jumps over the lazy dog"

function fuzzyMatch(pattern, str) {
  pattern = '.*' + pattern.split('').join('.*') + '.*';
  const re = new RegExp(pattern);
  return re.test(str);
} 

fuzzyMatch("qui x ", query)
```

**Comment by 8483** [comment]
@yairEO You absolute madman! You went ahead and did it. Thank you so much.

**Comment by 8483** [comment]
@yairEO Now that I'm trying it, I can't get it to work...  

From what I've read in the documentation, I have to to nothing.   

I have a `searchBy` property in my JSON, but the fuzzy search doesn't work.  I am probably not doing it right somehow.

**Comment by yairEO** [comment]
I am checking

**Comment by 8483** [comment]
@yairEO Thank you so much for helping me out.

This is super weird.  

I managed to get it working by including the CDNs in my HTML. 

However, using it in a bundler i.e. `npm i @yaireo/tagify` doesn't work.  

Why is this the case?

Also, [it works in some online editors, and some not](https://imgur.com/a/DUJdaU0), no idea why...

**Comment by 8483** [comment]
Another thing...  

`The quick brown fox jumps over the lazy dog`

While the search works with non continuous strings like `quick fox`, it doesn't work in reverse i.e. `fox quick` is not found.  

This is why I did it with an array instead of regex, but probably regex can handle it as well.  

This is just a QOL improvement, the main functionality is still great!

**Comment by yairEO** [comment]
I can also write it like this:

```js
var stringHasAll = (s, query) =>
  query.split(' ').every(q => s.includes(q));

[
  'd b',  // true
  'aa',   // true
  'aa ',  // true
  ' aa',  // true
  'aaa',  // false
  'a b',  // true
  'a a a a a ',   // true
].forEach(q => console.log(
  stringHasAll('aa bb cc dd', q) 
))
```

which is same concept as your advice in the beginning (of the thread), only shorter.

The last case worries me a bit, because it's a ridiculous match

**Comment by 8483** [comment]
Any thoughts on the...

1. `npm i @yaireo/tagify` not working vs the CDN

2. `quick fox` vs `fox quick`

**Comment by yairEO** [comment]
What do you mean `npm i @yaireo/tagify` doesn't work? What are the steps to reproduce?

Here's a demo of it working with latest version `3.18.0`:
https://codesandbox.io/s/tagify-react-wrapper-test-only-n5krt
