### ISSUE TITLE
Tags outside vertical list

### ISSUE THREAD

**Issue by niallhuis** [yairEO/tagify#641]
Hi,

I am trying to show the tags outside the input (which is working - used this [example](https://yaireo.github.io/tagify/#outside-of-the-box)). What I want is for the tags to show in a vertical list. Is that possible?

Thanks

**Comment by yairEO** [comment]
Well, it's CSS. simply write your CSS to manipulate the list of tags the way you want it to look like. 
Do you know CSS?

**Comment by niallhuis** [comment]
No worries. Sorted it
