### ISSUE TITLE
cdnjs tagify works but dist tagify doesn't

### ISSUE THREAD

**Issue by caissalover** [yairEO/tagify#642]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Demo Page:
https://jsbin.com/mimoficala/2/edit?html,js,output

### Explanation
- **What is the expected behavior?**
Dist files should work correctly too

- **What is happening instead?**
cdnjs tagify works and dist/tagify doesn't

- **What error message are you getting?**
There is some issue in formatting text

Also, dist files are not really minified.

**Comment by yairEO** [comment]
> cdnjs tagify works and dist/tagify doesn't

What is the problem? i don't understand.. can you maybe describe in other words?

**Comment by caissalover** [comment]
I don't trust unpkg or cdnjs. I'd like to use your dist packages straightaway of tagify in your github releases. When I replace files in your dist directory in the JS Bin you've made instead of the unpkg files originally used, the behaviour is different as shown in JS Bin above. Dropdown suggestion menu of tags just goes away.

I even tried it on a form on my site. Your release dist files didn't work correctly whereas the cdnjs worked well.

**Comment by yairEO** [comment]
You cannot use files directly from Github, that is "illegal" and blocked by Github. 

Please trust in *CDNJS* or *UNPKG*. You have ***no reason*** not to trust them.

**Comment by caissalover** [comment]
This isn't solved. Please don't close this. I download your css and js and use them from my own server's static files. Linking github raw files was just for a demonstration.
I executed wget for both css and min.js files of tagify from unpkg and your repo. I've attached tarball of the 4 files. You can check that both have different checksums. My point is please offer the same files for both.

[test.tar.gz](https://github.com/yairEO/tagify/files/5175223/test.tar.gz)

**Comment by yairEO** [comment]
I'm about to release a new version today so this would get closed anyway since the `/dist` files will be replaced entirely. 

Why don't you work with NPM to get the files? it's highly inadvisable to download script files without going through NPM or Yarn because then you will no be aware of new version releases and it will also be a hassle to upgrade. With NPM it's **much** easier
