### ISSUE TITLE
White bar showup inside long tag (tag use multiple lines)

### ISSUE THREAD

**Issue by chjcken** [yairEO/tagify#646]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/xahizifojo/edit?html,js,output
(or you just input a tag which has a lot of word to any tagify demo page, ex: "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Nisl tincidunt eget nullam non")

### Explanation

- **What is the expected behavior?**
a long tag (tag use multiple lines) is show as normal as other short tag without white bar inside

- **What is happening instead?**
a white bar inside long tag

I have troubleshooted a bit and found that, the white bar show up because of ".tagify__tag > div::before" box-shadow spread radius is not big enough (current is 1.1em). 

I tried to inscrease this figure to 2em and it's worked, the white bar disappear, but it will appear again if tag input is longer (use more and more lines) so I think this is not the best solution :D .

 I just report the bug and hope you guy will fix in another day.

Thank you for a wonderful library.

**Comment by yairEO** [comment]
Tags were never meant to be multi-line :) This isn't a bug but designed by my specifically for single-line tags only, as I consider multi-line tags a bad UX decision, sorry..

May I know why do you have such long tags? what is the purpose of those tags?

You are always free to change the CSS completely and use a `background color` instead of `box-shadow` and solve it, but it would require some CSS tinkering.

**Comment by chjcken** [comment]
@yairEO thank you for your advise, I've already use background-color to fix the issue

btw, my tags are url so that they could be a little bit longer than I expect

**Comment by yairEO** [comment]
Why don't you give tags max-width and then trim it with an ellipsis and show the full text on hover using the OS tooltip (via the `title` HTML attribute)? is it really that important to show the whole URL, multiline?

**Comment by chjcken** [comment]
> Why don't you give tags max-width and then trim it with an ellipsis and show the full text on hover using the OS tooltip (via the `title` HTML attribute)? is it really that important to show the whole URL, multiline?

because these url could be only different by some query params at the tail so that I have to show full the url (actually my client idea) to make sure there is nothing wrong

and thanks for your advise about max-width, I will try it in another case that needs to input long tag :smile:

**Comment by yairEO** [comment]
Write (in your program's code) this CSS to be able to limit the tags' width:

    .tagify{ --tag--max-width:200px; }
    .tagify__tag-text{ white-space:nowrap; }
