### ISSUE TITLE
Display proper value for tag

### ISSUE THREAD

**Issue by pedroR** [yairEO/tagify#647]
Hi, 

I am using the mix mode and also using tagify in a React app. In first place I load from the server some data and then I build my Tag element. So initially I set the setting like this

```
const [tagifySettings, setTagifySettings] = useState({
        mode: "mix",
        pattern: /@/,
        dropdown: {
            enabled: 1,
            position: "text",
            classname: "optionsList",
            highlightFirst: false
        },
        whitelist: [],
        placeholder: 'Add a message',
        mixTagsInterpolator: ['[(${', '})]'],
        enforceWhitelist: false,
        editTags: false,
    });
```
When I load data and manage it i fill the whitelist with this array
```
[
  {
    "title": "[(${text1})]",
    "value": "Text1"
  },
  {
    "title": "[(${text2})]",
    "value": "Text2"
  }
]
``` 

When I start writing with "@Tex " I see the proper text being displayed. However when the <Tag> element renders initially it display the `title` content - [(${text1})]. How can I do to display the `value`  value - Text 1 ?

**Comment by yairEO** [comment]
Why is your title `"title": "[(${text1})]"` and not `"title": "text1"` ?

**Comment by pedroR** [comment]
hi @yairEO thanks for replying. 
You are right. However I switched for your suggestion and I get the same result when the component renders. 
When I start typing "@tex " the suggestion list now show me the value of property `value`  - [(${text1})] . 

I must be doing something wrong but I am not figuring what.
Thanks

**Comment by yairEO** [comment]
Can you please show how your whitelist is looking?

And why do you have weird characters around `text1`? 

I don't understand the problem here..

**Comment by pedroR** [comment]
My whitelist is like this:

```
[
  {
    "title": "[(${text1})]",
    "value": "Text1"
  },
  {
    "title": "[(${text2})]",
    "value": "Text2"
  }
]
```


> And why do you have weird characters around text1?

It's  what I get from the service response. ~But I think it's the same as having [[...]]~. ~Because I set the property `mixTagsInterpolator: ['[(${', '})]']`~. But now I see that I may understood wrong. The pattern (to simplify let's say [[...]] ) should include both value and title properties. Is it right?


> I don't understand the problem here..what does it mean:
Nevermind any more. I fixed it....my confusion

**Comment by yairEO** [comment]
it should be just

```
[
  {
    "title": "text1",
    "value": "Text1"
  },
  {
    "title": "text2",
    "value": "Text2"
  }
]
```

The Tagify [official demo page](https://yaireo.github.io/tagify/#section-mix) shows how a mix-tags whitelist should look like
