### ISSUE TITLE
Prevent users from entering new tags when maximum limit is reached

### ISSUE THREAD

**Issue by sarathsince85** [yairEO/tagify#648]
Hi, thanks for the wonderful script and for maintaining it. Just have a few feature requests

Right now when maximum number of tags (maxTags) input is reached, we are still allowing users to enter new tags, but later we are removing them. This wont give best experience to the end user. They are not understanding why their tags are getting removed, but keep on trying creating new one and finally gets frustrated.. 
As a workaround, right now we are showing them a text message that this field accepts 'x' number of tags only.

It will be a nice user experience if we just disable the option of creating new tags once the end user reaches the maximum limit.

**Comment by yairEO** [comment]
I believe believe it is not psychologically different the way it behaves now to the way you suggest it should behave. In both ways the user still is confused why it was possible to write tags and suddenly it is not possible.

I therefore assume the developer will write a *disclaimer* near the component or some sort of counter to how many tags are allowed (`0/6` which goes up until `6/6` for example).

If the current behaviour is not to your liking, than you are free to change it. 
it's just a CSS customization thing. 

If you inspect your Tagify component, you will notice it has dynamic class names (as mentioned in the README) and what you need is the `tagify--hasMaxTags` class name. with it, you can simply hide the input area inside the component, like so:

```css
.tagify--hasMaxTags > .tagify__input { display:none }
```

[See README](https://github.com/yairEO/tagify#settings) at `maxTags` "settings" section

**Comment by sarathsince85** [comment]
In both ways the user still is confused why it was possible to write tags and suddenly it is not possible.
In the current scenario, user is still entering the tag data, but it gets disappeared.. User will repeat it and finally thinks that the platform is buggy as they are losing the data they entered. 

In the scenario, I mentioned we can change the color of input field, or disable the input field once the maximum limit is reached. I think users are familiar with disable fields already... besides that, they are not losing the data as they are not entering anything. Losing your data has a negative psychological impact.. 

I will definitely try your solution.. Thank you..

**Comment by sarathsince85** [comment]
`.tagify--hasMaxTags > .tagify__input { display:none }`

That trick is working as I needed, except for a small bug which can be replicated as below

- User start typing on the input fields
- Tokens are displayed in the dropdown
- User selects a token by **clicking the mouse**
- Token gets selected and fills the input field
- the input field for adding new token gets hidden
- **but** the drop down gets absolutely fixed to top left corner or webpage.

Issue is only when we use a mouse click for selecting the token from drop down. Not happening when using the arrow keys for selecting the token or when using auto suggested tokens.

**Comment by yairEO** [comment]
I cannot help without a demo page showing your exact setting and code.. 

Please clone [this demo](https://jsbin.com/jekuqap/edit?html,js,output) and make it same as your setup
