### ISSUE TITLE
Use key value pair for rendering tags

### ISSUE THREAD

**Issue by sarathsince85** [yairEO/tagify#649]
Is there a way we can use key value pairs as the tag objects? For example

`var whitelist =[{ value:'Afghanistan', code:'AF' }, { value:'Åland Islands', code:'AX' }, { value:'Albania', code:'AL' }]
`
For drop down show the values and when user submits the form, send the code through a hidden field which will get updated in the background whenever tag input changes..

**Comment by yairEO** [comment]
I don't understand the question. 

What is the problem? 
How does your code looking now?
How you want it to look like?

**Comment by sarathsince85** [comment]
Sorry for being vague. 
For example, think about this scenario

I am having a whitelist of countries as above... For the end user, I will show the values (eg. Afghanistan, Albania) as the dropdown tags.. But when the data is submitted to server, I want it to send only "AF", "AL" etc., so that I can fetch it and process it.

Currently the data send to server is like
`[countries] =>[{ value:'Afghanistan', code:'AF' }, { value:'Albania', code:'AL' }]`

Another use case is
var whitelist =[{ value:'Tom', user_id:'12' }, { value:'Dick', user_id:'13' }, { value:'Hary', user_id:'14' }]
This will allow end user to select a user through tag, but I want only the user_id on the server side.

**Comment by yairEO** [comment]
Tagify docs has relevant information regarding this:
https://github.com/yairEO/tagify#output-value

You are the master of your code, you can manipulate Tagify's output however you see fit.
if you are submitting the form using AJAX, so you can modify the data just before sending it, or you
can also modify it on the moment tagify is saving it to the original value..

Just keep in mind Tagify probably needs this data in the to be able to show the chosen tags after refresh, so the format is important, or at least only the `value` should be kept if not the other properties.
