### ISSUE TITLE
Supporting for pasteKeys

### ISSUE THREAD

**Issue by hanye9895** [yairEO/tagify#652]
For some cases, people want to paste another prop instead of 'value', just like #367 
```
[
  {
    value: "a",
    nickname: "na",
    email: "a@mail.com"
  },{
    value: "b",
    nickname: "nb",
    email: "b@mail.com"
  }
]
```
when pasting `a@mail.com b@mail.com` will work as `a b`

### But it could be messed up with value
eg: a.value===b.email (or may be could check in some where)

### So , What I'm doing right now 
is to add `delimiterText`(`@`) setting and split it inner `normalizeTags` function (seems value and email before '@' was same in my case)

### But that seems not the best way...

Could it be a better way to solve the issue?

**Comment by yairEO** [comment]
Sorry but i don't understand anything. 

> when pasting `a@mail.com b@mail.com` will work as `a b`

I simply have no idea what this sentence means. And the rest also..

Can you maybe ask another friend in your team with better english to try and explain it?

**Comment by hanye9895** [comment]
Forgive my poor English, and thanks the advice
Normally, we paste items will get the tag what we pasted
> when pasting `a b foo bar` will get 4 tags (space as a delimiters) -> `a` `b` `foo` `bar`
It works perfect in most cases.

But somehow, string will not exactly same as `value` prop
(people can get string easily from existing system)
such like, `a@mail.com b@mail.com foo@mail.com bar@mail.com`
but they don't want to update them by hand~
and they don't want the 4 tag as `a@mail.com` `b@mail.com` `foo@mail.com` `bar@mail.com`,
also, they want to get the 4 tags, `a` `b` `foo` `bar`

But referring #367, adding things like `pasteKeys` maybe solve the issue

emmm, I know it's kind of weird, but I can explain when anyone having further question :)

**Comment by yairEO** [comment]
You want to be able to paste `a@mail.com b@mail.com foo@mail.com bar@mail.com` and it will create one single long tag from that string, but not when you paste other strings such as `a b foo bar`, in which case you **do wish** them to be turned into 4 separate tags?

**Comment by hanye9895** [comment]
Yes, I do wish them turned into 4 separate tags, and it will separate, when I set the `delimiters: " "` 
separate tags was perfect, has no problem.
Let me show the simple case

------
when whitelist is:
```
[
  {
    value: "a",
    nickname: "na",
    pasteKey: "a@mail.com"
  }
]
```
and now pasting `a@mail.com`, the tag will turn into `a`

**Comment by yairEO** [comment]
so why don't you make your data like this:

```js
[
  {
    value: "a@mail.com",
    nickname: "na",
    id: "a"
  }
]
```

You can also set another `tagTextProp` settings:

```js
new Tagify(input, {
	tagTextProp: 'email'
})
```

or you ca change the [tag template](https://github.com/yairEO/tagify#dom-templates) and use your own t.
emplate

**Comment by hanye9895** [comment]
That's a good idea to map a value to other props.
And I am using [tag template](https://github.com/yairEO/tagify#dom-templates) now, avatar perform awesome by the way.
But the problem is some people not only want to paste `a@mail.com` to get `a`, and they also want to paste `a` to get `a`
For further,  they want to paste `na` to get `a` (na was the nickname)

It may be mess up props(a.value===b.emai) 
What came up to me was to get the first item matched~

Some better thought about this?

**Comment by yairEO** [comment]
are you enforcing your whitelist?

**Comment by hanye9895** [comment]
Yes, I'm using tagify as member select, default enforceWhitelist is true

**Comment by yairEO** [comment]
When you type something and want it to become a *tag*, first the code tries to check if there is any item in the whitelist, with a `value` property (if there whitelist is an *Array* of *Objects*) which matches your typed text. Remember that `value` must be unique.

for example, you typed `a` and your whitelist has:

    [{value:"a", text:"foo"}, {value:"b", text:"bar"}]
    ------- MATCHES ---------

for example, you typed `a@mail.com` and your whitelist has:

    [{value:"b@mail.com", text:"boo"}, {value:"a@mail.com", text:"abc"}]
                                       ----------- MATCHES -------------

if you typed `a` and no item in the whitelist has a value equal to `a` and you `enforceWhitelist` is `true` and you cannot add this tag

**Comment by hanye9895** [comment]
The whitelist is
```
[{value:"a", text:"foo", email:"a@mail.com"}, {value:"b", text:"bar", email:"b@mail.com"}]
```
But I suddenly realize adding a `{value:"a@mail.com", text:"foo", email:"a@mail.com"}` could solve the issue

to remember the old `value`, whitelist will be
```
[
  {value:"a",                   text:"foo", email:"a@mail.com", origValue: 'a'}, 
  {value:"b",                   text:"bar", email:"b@mail.com", origValue: 'b'},
  {value:"a@mail.com", text:"foo", email:"a@mail.com", origValue: 'a'}, 
  {value:"b@mail.com", text:"bar", email:"b@mail.com", origValue: 'b'}, 
]
```

**Comment by hanye9895** [comment]
emm, It could solve the issue when pasting(pasting will not show the dropdown menu)
but when typing, the dropdown menu could be double in that way~

**Comment by yairEO** [comment]
Well what do you suggest? You can set the minimum required typed characters for the dropdown to show to be at least 2-3, so the suggestions will be more accurate
