### ISSUE TITLE
Dropdown inline styles issues

### ISSUE THREAD

**Issue by raguila8** [yairEO/tagify#654]
I am following your example ([Render Suggestions List Manually](https://yaireo.github.io/tagify/#section-manual-suggestions))  on the demo page. However, when you select tags, the position and width styles are calculated and applied to the dropdown element. In your example, the styles do not affect the position because the dropdown element is not positioned absolutely. But, when `position: absolute` is set, the position styles break the UI. Is there a way around this?

On a separate instance, if you want to append the dropdown below the input field or any element other than the body element, this is also an issue.  When you set the `dropdown.appendTarget: customElement` option, the position styles are calculated and set for you relative to client viewport and this breaks the UI when you want to position the dropdown relative to `customElement`. 

Is there a way to customize these styles or exclude them altogether?

**Comment by yairEO** [comment]
Hi, I will fix it, thanks for reporting!

**Comment by raguila8** [comment]
Thanks for the quick update! The issue is fixed for manually rendered dropdowns.
However, the issue remains when setting the `dropdown.appendTarget: customElement` option. The inline styles that are set completely break the dropdown positioning. Is there a way to overwrite or remove these inline styles?
Sorry to be a nuisance.

**Comment by yairEO** [comment]
Can you provide a demo? (there's a link template when you open a new issue)

It makes no sense to use `appendTarget` other than `body` and not wanting *tagify* to position the dropdown for you. That is **exactly** what `position:"manual"` is for...

**Comment by raguila8** [comment]
Gotcha! Disregard my last comment.

**Comment by Kopyov** [comment]
Not necessarily the case. If body tag has overflow: hidden; and the main scrollable container is a simple div, `appendTarget` positions the dropdown correctly, but once i hover on dropdown item, menu jumps to the top. If you're saying that it makes no sense to use `appendTarget` on custom containers, what's the point then to have this option at all? 😃

**Comment by yairEO** [comment]
@Kopyov - I don't remember anymore what other uses cases are there for `appendTarget`, I have so many open source projects that I don't always remember every scenario - for Tagify there are hundreds of scenarios, it's an extremely complex component.

This is why keep asking people to please create a demo so I could see exactly what's happening because I cannot understand from a written description what exactly is the problem here, you need to help me help you

**Comment by gijzy** [comment]
> Not necessarily the case. If body tag has overflow: hidden; and the main scrollable container is a simple div, `appendTarget` positions the dropdown correctly, but once i hover on dropdown item, menu jumps to the top. If you're saying that it makes no sense to use `appendTarget` on custom containers, what's the point then to have this option at all? 😃

Did you find a fix for this? @Kopyov 

I have an shadcn / radix ui dialog and when the input is appended to the body I found I can no longer click / select the dropdown items because of the way shadcn totally disables everything except the dialog and content itself.  an append to the input field itself should be a reasonable approach

**Comment by yairEO** [comment]
Hi all, I've updated the code in [v4.19.0](https://github.com/yairEO/tagify/releases/tag/v4.19.0) and now `dropdown.appendTarget` supports a function which allows to place the dropdown inside any container you want, like so:

```
var input = document.querySelector('input'),
    button = input.nextElementSibling,  // "add new tag" action-button
    tagify = new Tagify(input, {
      whitelist: ['a', 'b', 'c'],
      dropdown : {
        enabled: 0,
        appendTarget() {
            return tagify?.DOM?.scope
        }
      }
    });
```
