### ISSUE TITLE
loading data quickly from server will loose dropdown focus

### ISSUE THREAD

**Issue by hanye9895** [yairEO/tagify#656]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/kucebaw/3/edit?html,js,output

### Explanation
- **What is the expected behavior?**
loading data quickly from server will loose dropdown focus(mockAjax timeout set to 10ms)
- **What is happening instead?**
1. type 'a' 
2. dropdown show normally, hover will active the `<li>`
3. type 'g'
4. dropdown show, but hover will loose
5. select one of them, value not updated as the selected one
- **What error message are you getting?**
no error message

![onInputTwice](https://user-images.githubusercontent.com/68373171/94360199-3cef7d80-00de-11eb-97df-af1dc814c3fc.gif)

**Comment by yairEO** [comment]
No server can return data this fast. 
Are you having a real problem or just talking theoretical?

**Comment by hanye9895** [comment]
Technically, rare server could done that.
I'm using tagify as our member select, the search method could be expensive.
So, I'm just cache the result in the frontend, and it's easy to reproduce it in the second time.

and my server team were also optimize the api AFAP, the issue happens sometime

**Comment by hanye9895** [comment]
For me, the temporally hack is to provide some timeout when it's too fast
```
tagifyObj.loading(true)
const beforeTs = new Date().getTime()
const oaInfoList = await self.batch_MemberOaInfo(pastedData)
const afterTs = new Date().getTime()
const diffTs = afterTs - beforeTs

self.tagifySettings.whitelist.push(...oaInfoList.filter(t => !t.moreThanOne && comm._isO(t)).flat())

await comm.asyncTimeOut((200 - diffTs > 0) ? (200 - diffTs) : 0)
tagifyObj.loading(false)
```
But I'm hard to find where could cause the issue when I look into the code (there are no error in console)
Could you lead me some hint or clue?

**Comment by yairEO** [comment]
I am looking into this bug

**Comment by 1c7** [comment]
https://user-images.githubusercontent.com/1804755/106006497-415d8e80-60f0-11eb-95c5-d38ab9c06452.mov

**Comment by 1c7** [comment]
I have the same problem, sometime dropdown doesn't response to mouse hover

**Comment by 1c7** [comment]
## Seem like wait 100ms could "Fix" the problem
```javascript
  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
```

![image](https://user-images.githubusercontent.com/1804755/106006927-b5983200-60f0-11eb-9fce-c0b751f3be76.png)

**Comment by 1c7** [comment]
Is there are better solution than wait 100ms? @yairEO

**Comment by yairEO** [comment]
@1c7 - you are probably working in localhost where with local server, therefor the server is very very fast

The situation is that you are using ajax to pull results from the server while a user is typing.
Are you calling the `dropdown.hide()` method while the user is typing? if not, this bug shouldn't happen

**Comment by 1c7** [comment]
Thanks for reply!
* It happen on production too, not just localhost. because we only have 20 or so tag, that's proably why server are fast too.
* Yes I am calling `dropdown.hide()` while user is typing,
```javascript
tagify.on('input', self.onInput)
```
```javascript
  self.onInput = async function (e) {
    let tagify = self.tagify

    tagify.settings.whitelist.length = 0; // reset current whitelist
    tagify.loading(true) // show the loader animation

    var url = '/evaluation/tags/autocomplete'
    var search_term = '' // search word (can be empty)

    // sometime we call this method without parameter
    if (e && e.detail && e.detail.value) {
      search_term = e.detail.value;
    }

    var response = await $.ajax({
      url: url,
      type: "GET",
      data: {
        q: search_term
      }
    });
    if (response.status == 'success') {
      var data = response.data
      tagify.settings.whitelist.push(...data, ...tagify.value)
      await sleep(100);
      tagify.loading(false).dropdown.show.call(tagify, search_term);
    } else {
      tagify.loading(false).dropdown.hide.call(tagify)
    }
  }
```

**Comment by yairEO** [comment]
@1c7  Can you please create a JS demo from the this template?
jsbin.com/kucebaw/3/edit?html,js,output

**Comment by 1c7** [comment]
@yairEO 
I am unable to make a reproducible demo. 
it may have something to do with `Sticky Sidebar`
we put that tag input in a sticky sidebar

https://user-images.githubusercontent.com/1804755/106359823-ea55f480-634f-11eb-97cd-898875611f9b.mov

Let's put this aside for now, If this happen again, I would make a demo and provide a link for you to debug
Thanks

**Comment by richsch** [comment]
I have run into the same issue and two changes fixed it for me:

1. adding `debounce` to onInput
2. Removing any `dropdown.hide` calls inside `onInput`

e.g.
```
function debounce(func, timeout = 100){
    let timer;
    return (...args) => {
        clearTimeout(timer);
        timer = setTimeout(() => { func.apply(this, args); }, timeout);
    };
}

const onTagifyInput = debounce((e) => {
    .....
}, 100);
```
you can then use `onTagifyInput` when setting up your instance
