### ISSUE TITLE
Mixed mode - Remove tags issue (3.19.0)

### ISSUE THREAD

**Issue by raikow** [yairEO/tagify#657]
## Prerequisites
I'm running the 3.19.0

### Demo Page
Tagify React example (mixed mode)

### Explanation
I updated the version in the example page (package.json) to latest version 3.19.0. Then put my cursor behind the Tag "Tags" of the first line. Then press the backspace key

- **What is the expected behavior?**
The Tag should be deleted

- **What is happening instead?**
Nothing happened... The Tag is still there

**Comment by yairEO** [comment]
You mean you press the <kbd>Delete</kbd> key? 
*"behind"* - you mean "before" ?

**Comment by yairEO** [comment]
possibly related to #658

**Comment by raikow** [comment]
No I mean the [backspace key](https://www.computerhope.com/jargon/b/backspac.htm)...

If you put your cursor behind a Tag and press the backspace key the tag should be removed

**Comment by yairEO** [comment]
You mean ***caret***, not <del>cursor</del> and again, please **define** the terminology *"behind"*

The is only *before*/*after* in relation to the language direction (BIDI)

**Comment by raikow** [comment]
ok, sorry didn't know that... 
I just checked the issue on the new released versions (3.19.1 and above) this issue is gone ;)

But the issue of the #658 still exist (caret before first character of textarea => backspace => remove the latest tag in the textarea)

**Comment by yairEO** [comment]
Happy it was fixed :)

#658 is unsolvable unfortunately...
