### ISSUE TITLE
How to handle values which contain commas?

### ISSUE THREAD

**Issue by sarathsince85** [yairEO/tagify#661]
Hi, when I am having values which contains comma, the multiple tokens are getting generated by breaking the words at the commas. 

![List with comma values](https://i.stack.imgur.com/XYOzN.png)

![Token getting broken at the comma](https://i.stack.imgur.com/FVz0z.png)

This is how I am generating my tokens

```php
    ..........
    $processed = [];
    $decoded = json_decode($data, true);
    foreach($decoded as $k => $v){
        $processed[] = ["value" => $v["term"], "key" => $v['conceptId']]; 
    }   
    echo json_encode($processed);
    ..........
```

This is my json output
![JSON output](https://i.stack.imgur.com/MYeEX.jpg)

The way I am initializing tagify is explained [here](https://github.com/yairEO/tagify/issues/660).

I have gone through the docs where you have specifically mentioned [about this scenario](https://github.com/yairEO/tagify#modify-original-input-value-format), but I am struggling to resolve this issue. Can you help in resolving this. Thank you

**Comment by yairEO** [comment]
It seems like there's a bug in the code and this should work. 
I am looking at it now and will post a fix soon

**Comment by sarathsince85** [comment]
Thanks for the excellent script and the support.. 👍

**Comment by slugb0t** [comment]
Hi was this ever resolved? I'm using version 3.25.0 and I'm getting the same issue.
![image](https://user-images.githubusercontent.com/50216901/179855693-8a75b616-e51d-4658-8b46-1cd8c39b8123.png)

**Comment by JerichoSamson0706** [comment]
Good day, is this already solved? I am also having the same problem handling values containing commas. If so, I would very much appreciate if anyone would point me to the right direction to solve this. I can't find the solution in the documentations. Thank you

**Comment by yairEO** [comment]
@JerichoSamson0706 - please create a [JSBIN from this template](https://jsbin.com/jekuqap/edit?html,js,output) showcasing the problem

**Comment by jzohrab** [comment]
Hi there, I can never figure out how to create jsbins :-(, but changing the JS line `tagify.addTags(["a", "b"])` to `tagify.addTags(["a, x", "b"])` results in it getting parsed as `[{"value":"a"},{"value":"x"},{"value":"b"}]` with the corresponding three tags, instead of the expected two.

> <img width="865" alt="Image" src="https://github.com/user-attachments/assets/f7db206d-a7a4-4bd6-b50f-59612340f06b" />

**Comment by jzohrab** [comment]
Ah, I see in https://github.com/yairEO/tagify/issues/1071 there's a note about `delimiters`, thank you @yairEO for all of your work, much appreciated.
