### ISSUE TITLE
Release v3.18 is not minified

### ISSUE THREAD

**Issue by barsan-md** [yairEO/tagify#662]
If you download the released code from github: https://github.com/yairEO/tagify/releases/tag/v3.18.1
The files tagify.min.js and tagify.polyfills.min.js (maybe others) are not minified. Also the version in the comments is not correct.

Version 3.18.0 has the same problem

**Comment by yairEO** [comment]
Yeah those aren't the newest versions, apparently I forgot to push the git tags along with the releases. The currently latest release is `3.19.1` and in in a few minutes will be `3.19.2`|

I cannot go back and change older tags so it's best to ignore those that have no minified files. 

Why are you using the *release-tag* code and not the code from the `master` branch?

**Comment by barsan-md** [comment]
I assumed the master could break. Thanks, I Will get the files from master then.

**Comment by yairEO** [comment]
But why don't you use NPM or get the latest from CDN? taking files directly from a Github repository that is ***highly*** maintained like this one means after a few days you will be out-of-sync with bugfixes and updates
