### ISSUE TITLE
Whitelist dropdown not updating on changing state or props

### ISSUE THREAD

**Issue by harmeetsf** [yairEO/tagify#667]
I am trying to pass whitelist array dynamically using props but tagify is not rendering the list of whitelist variables in the dropdown. But when I pass static array in props then dropdown shows all options in props.

The intital state of array which I am passing through props is empty array and the array gets populated when I select different options in the react app.

Tagify is not able to rerender the dynamically passed settings or whitelists.

Please help how can I solve this issue.

TagField.js
--------------
```
import React from 'react';
import Tags from "@yaireo/tagify/dist/react.tagify";
import "@yaireo/tagify/dist/tagify.css";

export default function TagField(props) {
	return (<Tags
		settings={{props.settings}}
		className="input-text"
		onChange={e => (e.persist(), props.onInputChange("servicePricingFormula", e.target.value))}
	/>)
}
```

Service.js
--------------
```
import TagField from "./TagField";
export default function Service(props) {
	const variables = props.driverCodes.map(item => {
		return ({
		 	value: props[`driver${item}Name`],
		 	key: item,
		 	class: "red-tag"
		});
	});
	const settings = {
		mode: 'mix',
		pattern: /@|#/,
		whitelist : variables,
		dropdown : {
			enabled: 0,
			highlightFirst: true
		},
		enforceWhitelist: true,
		duplicates: true
	}
	return (<TagField onInputChange={props.onInputChange} settings={settings} />)
}
```

**Comment by yairEO** [comment]
You should not change the `settings` prop itself once the component has been initialized, but need to work with the proper component props, and one of them is the `whitelist` prop

**Comment by harmeetsf** [comment]
Thank you so much 👍

**Comment by yairEO** [comment]
@nesslopz - Vue is a simple wrapper you can author/edit yourself, which I've provided an [example for](https://github.com/yairEO/tagify/blob/master/dist/tagify.vue) and is very easy to configure, if you know *Vue*.

Simply set the `whitelist` to whatever you want for the `this.tagify`:

    this.tagify.whitelist = ...
