### ISSUE TITLE
Way to paste partial text to finish a tag?

### ISSUE THREAD

**Issue by mtclmn** [yairEO/tagify#668]
I have a use case where we are using Tagify to paste in a string of numbers as part of a tag.

For example, I type in "ABC", then paste the string "123456789". 
I guess I would expect this pasted string to be appended to the "ABC" as part of the same tag until I enter the delimiter character (a comma in my case), and the final tag would be "ABC123456789".
However, I see it is creating "123456789" as its own tag on paste, followed by "ABC" as text.

Is there an option for pasting partial tag text to be enabled? Or is there a native way to allow this functionality?

![Screen Recording 2020-09-30 at 05 17 14 PM](https://user-images.githubusercontent.com/4490155/94740702-167d4c80-0341-11eb-9764-e6f743e92203.gif)

Thanks @yairEO for the great work on this

**Comment by yairEO** [comment]
Thanks for letting me know about this scenario, I will fix it

**Comment by mtclmn** [comment]
Awesome, working great. thank you @yairEO !

**Comment by mtclmn** [comment]
Hi @yairEO –
The fix for this seems to have reverted (appears to have broken v4.0). I can no longer mix typed and pasted content. Not sure if this was intentional, but I reverted my project to v3.25.0 and it works for now, but just wanted to report here.
Thanks!
