### ISSUE TITLE
Ajax whitelist remove problem

### ISSUE THREAD

**Issue by didactic-goggles** [yairEO/tagify#670]
I initialized tagify input then get tags from my server, this is ok. Then I try to create new tag(also on my server), everything is ok but if i try to remove this created tag, tagify remove it from html but input value not refreshed.

![image](https://user-images.githubusercontent.com/58259532/95085988-997b1a00-0728-11eb-9f74-7935f65b8378.png)

![image](https://user-images.githubusercontent.com/58259532/95086911-b6641d00-0729-11eb-8988-d8ad58c60a36.png)

In this code you can see I update input value because when tag was added, I must set new tag ID but tagify not update tag id (code in red box). How can I add a new tag from my server? What is the best way?

**Comment by yairEO** [comment]
The `transformTag` method cannot person anything async and will take no affect.

what are you trying to do?

You should work with the `tagify.on("add", callback)` event so when a tag has been added by the user, you will update your server (also do the same for the `remove` event)

[See this section of the README](https://github.com/yairEO/tagify#save-changes-ex-to-a-server)

Also, the [FAQ section](https://github.com/yairEO/tagify#faq) can help:

[Manually update tag data after it was added](https://github.com/yairEO/tagify/issues/433)
