### ISSUE TITLE
Tag when edited by double clicking changed to HTML code

### ISSUE THREAD

**Issue by jetacpp** [yairEO/tagify#673]
It appears to be a bug triggered by double clicking a tag, type the new tag name. The result is the tag became scrambled with HTML code. The issue was reproduced on the Vue Example https://codesandbox.io/s/tagify-tags-component-vue-example-l8ok4

![image](https://user-images.githubusercontent.com/31259584/95186948-6a43c780-077f-11eb-8bf6-50fe577807b9.png)

**Comment by yairEO** [comment]
I am actively working on that demo page now so it might be buggy

**Comment by yairEO** [comment]
just published a tons of fixes on latest version `3.20.0`, one solves this issue but I forgot to tag it so am closing manually
