### ISSUE TITLE
Placeholder overflow from the input box

### ISSUE THREAD

**Issue by anubhavbsft** [yairEO/tagify#675]
## Prerequisites

- [Yes ] I am running the latest version
- [Yes ] I checked the documentation and found no answer
- [ Yes] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/witenejoku/1/edit?html,css,js,console,output

### Explanation

- **What is the expected behavior?**

The placeholder must come to next line

- **What is happening instead?**
The placeholder is overflowing

- **What error message are you getting?**
None

**Comment by yairEO** [comment]
Yes, it is meant to behave like this.

You have two options:


## Set the CSS to this: 
(might cause bugs in Firefox)

    .tagify__input::before{ position:static; }

## Set the input `min-width` to fit your text
(not recommended when having a multi-language variations of the placeholder)

    .tagify__input{ min-width: 200px; }

**Comment by anubhavbsft** [comment]
Thankyou @yairEO It worked
