### ISSUE TITLE
ReferenceError: Can't find variable: Tagify

### ISSUE THREAD

**Issue by GigaMick** [yairEO/tagify#676]
I'm using this in a laravel app.

I've installed as per the instructions and I can see this in my package.json:

```
    "dependencies": {
        "@yaireo/tagify": "^3.20.0"
    }
```

I've pasted all the code from the examples into my template just to get me started but I keep getting that error. I'm using the vanilla JS integration.

Please help as this seems awesome.

**Comment by yairEO** [comment]
Can you please set up an example at [codesandbox.io](codesandbox.io) ?
