### ISSUE TITLE
Cannot search for UTF-8 Characters in Suggestion Box

### ISSUE THREAD

**Issue by Umut-Numanoglu** [yairEO/tagify#680]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
[Demo](https://jsbin.com/bakaqut/edit?html,js,output)

### Explanation

- **What is the expected behavior?**
Being able to search for all possible UTF-8 Characters (including accented characters) 

- **What is happening instead?**
Search cannot find items even if the Tag-value is inputted exactly.
I can search for "ß" but characters like "ä", "è", "é", "ş" are not possible to search.

Possibly related to [Issue 491](https://github.com/yairEO/tagify/issues/491)
I played around with "accentedSearch" option, but it only allows me to search for alternative ASCII characters.
A normal user would assume by searching for "Flä" and not getting "Fläche" would mean it is not in Whitelist, which is wrong and misleading.

I hope we can implement an easy solution for it.
Thanks for taking your time to reading.

**Comment by svensven** [comment]
Looks like you ran into the same issue that we did: https://github.com/openfoodfacts/openfoodfacts-server/issues/4280
I put in a PR that I _think_ fixes it: https://github.com/yairEO/tagify/pull/679
