### ISSUE TITLE
tag with format category:value

### ISSUE THREAD

**Issue by lostinroom** [yairEO/tagify#681]
Hi,<br/>
I would like to create something like category:value.<br/>
Similar to https://yaireo.github.io/tagify/#section-mix.<br/>
The difference is I want to show which special key is available (from the example is @ and #).<br/>
My testing is https://codepen.io/lostinroom/pen/rNLMZLr<br/>
After I click on suggested category, I want to show suggestion for value.<br/>
Is it possible to do it?<br/>
It can work if I just type without selecting it

**Comment by yairEO** [comment]
You can use [`suggestionClick` hook](https://github.com/yairEO/tagify#hooks) for this:

[Example jsbin](https://jsbin.com/vopunepucu/1/edit?js,output)
