### ISSUE TITLE
[Help] How to inspect dropdown elements? (Sorry I couldn't find details, comments or conversation related to that)

### ISSUE THREAD

**Issue by arunn87** [yairEO/tagify#682]
How to inspect element when dropdown displaying? I am customizing the dropdown template but facing some alignment issue so trying to fix that. But unfortunately, when i inspect the element its hiding immediately. Is there any settings to turn on debug mode or something like that? 

Thank a lot.

**Comment by yairEO** [comment]
You can do this trick:

```js
setTimeout(function() {
  debugger;
}, 3000);
```

And then quickly open the dropdown and the browser will then freeze after 3s to allow inpestion

**Comment by arunn87** [comment]
Thanks a lot 👍
