### ISSUE TITLE
Readonly property not working as expected with multiple tagify textarea

### ISSUE THREAD

**Issue by arunn87** [yairEO/tagify#683]
I have multiple tagify textarea, all have unique ID but using [name=mix] as selector.

```
var tagifyFields = document.querySelectorAll('[name=mix]');
var tagifyFieldsList = Array.prototype.slice.call(tagifyFields);
if (tagifyFieldsList.length) {
  tagifyFieldsList.forEach(createMixedTagifyFields);
} 
function createMixedTagifyFields(field) {
       var settings = {
            dropdown: dropdown,
            mode: 'mix',
            pattern: /#/,
            enforceWhitelist: true,
            duplicates: true,
            editTags: 0,
            whitelist: comments,
            templates: {
                tag: tagTemplate,
                dropdownItem: tagDropDownTemplate
            }
        };
    var tagify = new Tagify(field, settings);
}
```

Its working fine until i set readonly property to some textarea.

E.g. 
2 different textarea with same whitelisted tags (one without readonly and another with readonly).
```
<textarea id="1" name="mix">Please refer to this [[001]] and [[002]]</textarea>
<textarea id="2" name="mix" readonly>New comments added, please refer to this [[001]] and [[002]]</textarea>
```

**Issue:**
Both the 001 and 002 tags getting disabled on both the textarea even though i have readonly in one textarea.

![image](https://user-images.githubusercontent.com/56428479/96866297-b2f8c180-149d-11eb-85d7-d98a528d8d85.png)

**Comment by yairEO** [comment]
Just fixed this, please check version `3.20.1` and let me know. I've worked all day on this "readonly" thing. very complex.

**Comment by yairEO** [comment]
Can you create an example on jsbin please?

**Comment by arunn87** [comment]
**Demo Page**
https://jsbin.com/bewawim/27/edit?html,js,output

**What is the expected behavior?**
Readonly in textarea not working as expected in mix mode.
- Expected to disable all tags if the textarea = readonly.
- Shouldn't disable the tags in the editable text area

**What is happening instead?**
- Can edit/remove tags from readonly textarea
- In some scenario couldn't edit/remove tags in editable (non-readonly) textarea.

Please refer to the jsbin https://jsbin.com/bewawim/27/edit?html,js,output

**Comment by arunn87** [comment]
I tried the 3.20.1 still face the same issue...
Created Jsbin https://jsbin.com/bewawim/edit?html,js,output for your reference

Thanks a lot

Regards
Arun N
Sent from my Windows 10
________________________________

**Comment by yairEO** [comment]
1. since you've set `editTags: 0` in your Tagify settings, no editing would be allowed, to none of the examples

2. you are using the exact same whitelist for all examples, since Tagify does not clone it on every instance, you might get unwanted effects, like the ones you see in the last example, were the tags appear as "readonly" even though they weren't configured as such.

[Read here](https://stackoverflow.com/q/122102/104380) how to clone your data, so each Tagify instance will point to a unique location in the memory 

3. Regarding able able to click the (x) button of tags that are in a `readonly` textarea, that will be taken care of right away

Thanks for reporting and making a nice demo, helps a alot!

**Comment by arunn87** [comment]
Thanks a lot for looking into this issue. 
Tried cloning the data (Updated Demo: https://jsbin.com/bewawim/edit?html,js,output), but the if the mix mode textarea have readonly property, the tags data returning have readonly="true" but it's not added to the tags in the UI. 

Did I miss anything?

![image](https://user-images.githubusercontent.com/56428479/97098637-0ba4a600-16ba-11eb-95a6-d2d5aa9f86bc.png)
