### ISSUE TITLE
Wrong normalization of tags in some cases

### ISSUE THREAD

**Issue by quimey** [yairEO/tagify#685]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://codesandbox.io/s/tagify-react-issue-template-forked-0bo2p

### Explanation

- **What is the expected behavior?**
If I create the tags for 1, 101 and 201 in the demo above I expect the console to print objects with "id" and "value" keys but only the object corresponding to "1" has the "id" key. The other two only have the value key.

I believe the problem is in this line:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L941

because the call to `this.dropdown.filterListItems.call(this, '')` always returns the 10 first objects, so when I make a request to normalize an object above the first 10 the search fails and the id is not retrieved.

The behaviour is the expected in the version 3.19.5 but it fails on 3.20.1.

**Comment by yairEO** [comment]
Thanks for reporting but you've forgotten the `steps to reproduce` :)

What does this sentence means? 

> "I expect the console to print objects with "id" and "value" keys"

**Comment by yairEO** [comment]
after a bit of confusion I think I understand what you've meant

**Comment by quimey** [comment]
Sorry, in the demo above when you input tags on the input box, only tags with ids less than 10 will get the whole object.

Let's say you put "1, 100" in the text box, that creates two tags one for 1 and one for 101.

If you look at tagifyRef.current.value you will see:
```
0: Object
  id: 1
  value: "1"
   __isValid: true
1: Object
  value: "101"
  __isValid: true
```

Note the missing "id: 101" in the second object.

**Comment by yairEO** [comment]
BTW, your react demo should use `onChange` without callbacks on the `settings` object itself:

```js
<Tags
  tagifyRef={tagifyRef}
  settings={settings}
  onChange={update}
  placeholder="type tags"
/>
```

it is better this way

**Comment by quimey** [comment]
Thanks for the quick fix!
