### ISSUE TITLE
Cannot create new tags with Mix Text & Tags.

### ISSUE THREAD

**Issue by peterp** [yairEO/tagify#687]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://codepen.io/vsync/pen/KKzpdxQ
(Project's own example from the documentation.)

### Explanation

- **What is the expected behavior?**

You're unable to enter new tags (even when in the whitelist) when typing `@jimm` no auto-complete pops up.

- **What is happening instead?**

Nothing happens, except an error.

- **What error message are you getting?**

```Uncaught TypeError: Cannot read property 'length' of undefined```

**Comment by yairEO** [comment]
I'm on it

**Comment by peterp** [comment]
Thanks so much @yairEO <3
