### ISSUE TITLE
How to remove border and input focus glow around tagify component ?

### ISSUE THREAD

**Issue by jetacpp** [yairEO/tagify#689]
Hello,
I am using tagify and I'd like to remove border completely when focused/not focused on tagify component. I am using [Vue example demo](https://codesandbox.io/s/tagify-tags-component-vue-example-forked-82too), and this style has no effect at all.

```
<template>
  <input :value="initialValue" v-on:change="onChange" />
</template>

<style>
input {
  border: none !important;
  border-width: 0;
  outline: none !important;
}
</style>
```

**Comment by yairEO** [comment]
https://github.com/yairEO/tagify#css-variables

you can override tagify with:

```css
.tagify{
	--tags-focus-border-color: transparent;
}
```

**Comment by jetacpp** [comment]
Thank you :smiley: !
