### ISSUE TITLE
IE11 does not trigger custom events.

### ISSUE THREAD

**Issue by lordmikefin** [yairEO/tagify#69]
Hi,

I was testing my web site with IE11 and it failed with tagify :(

It seams that IE11 does not support CustomEvent().
And the fallback method within tagify was not working either.

Read more here:
https://stackoverflow.com/questions/27176983/dispatchevent-not-working-in-ie11
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by yairEO** [comment]
Thanks for reporting! will check
