### ISSUE TITLE
Change className on form validation

### ISSUE THREAD

**Issue by MuriloScarpaSitonio** [yairEO/tagify#690]
There's anyway to change the `className` of the component if the submission to the server was invalid? I'm using React, Formik and yup. I've tried the following:

```javascript
<Tags 
    settings={settings}
    className={errors.tags && touched.tags && 'error__box'} 
/>
```

Doing this way the class won't change (and I know the field `tags` has errors because the feedback appears properly).

Thank you very much!

**Comment by yairEO** [comment]
Sorry I was away abroad, just got back. I will work on it tomorrow

**Comment by yairEO** [comment]
You can now change the class name with the new version `3.21.0`

**Comment by MuriloScarpaSitonio** [comment]
Thanks for the new version and the fantastic library. It's helping me a lot.

I've updated the package, but, by some reason, the `border-color` CSS property is not been applied. All other properties of my class are fine, except this one. Do you have any ideas of what might be?

**Comment by MuriloScarpaSitonio** [comment]
Hello!

Sorry for bring this up again but I'm afraid this functionality is not working properly. Check this sandbox: https://codesandbox.io/s/sleepy-noyce-38w8t?file=/src/App.js:145-192

The `border-color` property of the `error__box` class isn't been applied. And the funny part is that if you change it (let's say `border: 1px solid #dc3545`, for example), it suddenly starts working... until we reload the page. If we back to the original property it starts working until we reload the page as well.

I hope I was clear enough to explain the problem.

Thank you very much!

**Comment by MuriloScarpaSitonio** [comment]
Hey @yairEO, sorry for pestering you again but the validation is not working properly :(

Check the sandbox and play with the validation on blur: https://codesandbox.io/s/sleepy-noyce-38w8t?file=/src/App.js

I'll try to contribute this weekend.

Thanks a lot!

**Comment by yairEO** [comment]
Hi, I am checking, you are not "pestering" me (I don't even know that word, thanks for teaching me)
