### ISSUE TITLE
After deleting all the text of a tag, it won't let me add the same again

### ISSUE THREAD

**Issue by josejulio** [yairEO/tagify#691]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
The bug appears here
https://yaireo.github.io/tagify/

### Explanation

1- Double click `tag2` to be able to select the text. Remove the text (by manually deleting or by cutting it)
2- Click on the "input" part
3- Write the exact name `tag2` (do not paste it)

- **What is the expected behavior?**

The `tag2` should remain there

- **What is happening instead?**

The `tag2` dissapears

- **What error message are you getting?**

No error message.

I think the problem is that the `onChange` is not being called when removing the name and clicking away.

**Comment by yairEO** [comment]
I will check

**Comment by yairEO** [comment]
I will release a fix soon, hopefully in a few hours

**Comment by josejulio** [comment]
Thanks!
