### ISSUE TITLE
Custom attribute lost when adding a tag from the whitelist without selecting directly.

### ISSUE THREAD

**Issue by barsan-md** [yairEO/tagify#694]
I found a bug relative to an example you made. The aim here was to create two types of tags depending on the button pressed: blue or salmon.
https://jsbin.com/difagowada/edit?html,css,js,output
The only key difference is that i added a whitelist
`whitelist: ['aa', 'bb']`

Try to add a tag using the "salmon" plus button, digit aa or bb and do not select the element from the dropdown, just press enter. It will be blue because it lost the attribute color and blue is the default.

Thanks

(old issue: https://github.com/yairEO/tagify/issues/666)

**Comment by yairEO** [comment]
it is indeed a problematic scenario, and even more if you edit a "salmon" tag and select a suggestion from the dropdown.. I have been thinking of ways to make this work for hours.

**Comment by yairEO** [comment]
You can now simply do this:

```js
function transformTag(data, originalData){
    data.color = originalData.color
}
```

https://jsbin.com/xotepihozi/edit?html,css,js,output

**Comment by barsan-md** [comment]
Thanks a lot!
