### ISSUE TITLE
Arrows dropdown selection doesn't work with custom dropdownItemActive class

### ISSUE THREAD

**Issue by FRSgit** [yairEO/tagify#695]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://jsbin.com/keduzuqibi/edit?html,js,output

### Explanation

- **What is the expected behavior?**
When `dropdownItemActive` classname is changed to the custom one `tagify` should still work the same way as without it.
- **What is happening instead?**
Dropdown arrow navigation has issues (doesn't work at all).
- **What error message are you getting?**
None.

I've already found & fixed that bug in the #693 PR

**Comment by yairEO** [comment]
The jsbin does not show any issue and is basically very simple. Are you sure you shared the right url?

**Comment by FRSgit** [comment]
@yairEO Sorry, I must've not saved the previous jsbin or sth - do not use it often.
I've updated the demo page link in the original issue description

**Comment by yairEO** [comment]
May I know why you wish to change that class name?

**Comment by FRSgit** [comment]
I'm using CSS-modules - all of the classnames in my application are being mangled (minified) in the production build.
So e.g. the classname `dropdown-item--active` in the production bundle will become something like `aE3` (some random, the shortest possible, generated hash).

**Comment by FRSgit** [comment]
Here is a screenshot of the DOM of my app with elements generated by `tagify`:
![image](https://user-images.githubusercontent.com/10456649/98440483-49152480-20f9-11eb-8f4c-4d3703c240af.png)

All of the mangles classnames are prefixes with `pe_` because of how this app should be working, but other then that - they're completely random.

**Comment by yairEO** [comment]
But Tagify works only **after** the page has been served to the user and the javascript is executed. Are you serving pre-rendered HTML?

I still don't understand why would you change any of the Tagify class names. what is the **benefit**?

> *It's more clearly visible in the production build where all of the classnames are being mangled (minified).*

This sentence does not explain anything to me.. 

If you did not change ant of the classnames Tagify generates, and simply use Tagify out-of-the-box, will things not work for you?

**Comment by FRSgit** [comment]
No, I'm not serving prerendered HTML (though I probably will for this app, but that won't make any difference in this case).

> I still don't understand why would you change any of the Tagify class names. what is the benefit?

The benefit is that I can mangle CSS classnames to keep the output bundle file is smaller.

> If you did not change ant of the classnames Tagify generates, and simply use Tagify out-of-the-box, will things not work for you?

With my current configuration I cannot import CSS/SCSS files without some kind of mangling happening. I'm working with CSS-modules, not only to minify class names, but also to keep track of used classnames, so it's possible for the bundler to remove unused part of styling.

I used this library primarily because it seemed that the classNames were thoughtfully added into the configurable settings object.

This single line changed in my PR is the only thing which helds the users back from changing the original class names. Also, the code after the change should be performant, since class selector is superior to attribute selector in this regard.

**Comment by yairEO** [comment]
Thanks for the informative explanation, now I understand the situation and will incorporate the fix and publish a new version shortly. I will wait a few days to gather some more changed before deploying.
