### ISSUE TITLE
Would tagTextProp in React wrapper work in 'select' mode?

### ISSUE THREAD

**Issue by ykyuen** [yairEO/tagify#696]
***React*** example:
https://codesandbox.io/s/tagify-react-issue-template-forked-8lupg?file=/src/index.js

I thought in **select** mode, the **tagTextProp** could be used to display specific tag attribute other than _value_.
for example: assume the whitelist:
```
[
  { id: 100, value: "kenny", title: "Kenny McCormick" },
  { id: 101, value: "cartman", title: "Eric Cartman" },
  { id: 102, value: "kyle", title: "Kyle Broflovski" },
  { id: 103, value: "token", title: "Token Black" },
  { id: 104, value: "jimmy", title: "Jimmy Valmer" },
  { id: 105, value: "butters", title: "Butters Stotch" },
  { id: 106, value: "stan", title: "Stan Marsh" },
  { id: 107, value: "randy", title: "Randy Marsh" },
  { id: 108, value: "Mr. Garrison", title: "POTUS" },
  { id: 109, value: "Mr. Mackey", title: "M'Kay" }
]
```

Let's say the user selected the **id: 106** option, the tagify input could display the _title_ **Stan Marsh** instead of _value_ **stan**. But currently it will display the _value_ attribute even if i have set the **tagTextProp** to _title_ in **select** mode.

**Comment by yairEO** [comment]
Seems like you didn't use the latest Tagify version (you need to make sure it's latest when cloning that repo because I don't always manually keep it up-to-date every time I deploy :)
