### ISSUE TITLE
Can't select dropdown option

### ISSUE THREAD

**Issue by 8483** [yairEO/tagify#697]
Version: 3.21.0

![tags](https://user-images.githubusercontent.com/16456606/98549940-c11b5000-229b-11eb-8dfa-e2c079ade5ef.gif)

**This just randomly stopped working. I didn't change any code.**

[Here's the code sandbox.](https://codesandbox.io/s/eager-wave-82z9g?file=/src/index.js)

The tags are populated normally with `add`, but this code doesn't fire at all.

```js
entityTags.on("dropdown:select", (e) => {
    console.log(e.detail);
});
```

**Comment by yairEO** [comment]
remove this line from the dropdown item template:

     tagifySuggestionIdx="${tagData.tagifySuggestionIdx}"

I've made it so tagify adds this automatically now

**Comment by 8483** [comment]
I haven't done it. I copied the code from your examples, and it suddenly stopped working.

The code was always there and it worked, until today, without me changing anything.  

Thank you so much for the quick reply, this fixed the issue, I have no idea why tho. :)

**Comment by yairEO** [comment]
I also have no idea :) investigating the root cause would consume far too much time

**Comment by yairEO** [comment]
I've made a fix so that even if you wrote that attribute, tagify will remove it and add its own

**Comment by 8483** [comment]
Awesome! Thank you so much.
