### ISSUE TITLE
Multilple react tagify wrapper with different whitelist

### ISSUE THREAD

**Issue by ykyuen** [yairEO/tagify#698]
I want to setup multiple tagify Tags with different whitelists inside a React component but i couldn't get it working. It seems that if i set the whitelist of the 2nd Tag it will override the 1st one. The following example demonstrates the problem.

https://codesandbox.io/s/tagify-react-issue-template-forked-78ocf?file=/src/index.js

Any idea on what i have done wrongly? Thanks for your help.

**Comment by yairEO** [comment]
Interesting. I am investigating.

**Comment by yairEO** [comment]
after hours of diggings, I've found a serious bug and am working on a fix.

**Comment by ykyuen** [comment]
Thx for making this great module and prompt reply. :smiley:
