### ISSUE TITLE
transformTag: Empty values are not being removed.

### ISSUE THREAD

**Issue by jeffreydwalter** [yairEO/tagify#702]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

I have the following code:

```js
new Tagify(input, {
                transformTag: (tag) => {
                    if(new Date(tag.value).toString() === 'Invalid Date') {
                        tag.value = '';
                    }
                },
                originalInputValueFormat: valuesArr => valuesArr.map(item => item.value).join(','),
                dropdown: {
                    classname: "tags-look",
                    enabled: 0,
                    closeOnSelect: false
                }
            });
```
with the following HTML:

```html
<input type="text" name="holidays" value="" pattern="\d{2}/\d{2}" placeholder="Add Date (e.g. 12/24)">
```

### Explanation

- **What is the expected behavior?**
When I enter an invalid date I expect that tag to get removed automatically from the UI.

- **What is happening instead?**
The tag is being created without a value, and not being removed.

Here is me entering an invalid value: 
![image](https://user-images.githubusercontent.com/567047/99322475-a154d080-2835-11eb-9ea5-d007200543e6.png)

Here is Tagify adding it as an empty value after I set `tag.value = '';` in `transformTag`.
![image](https://user-images.githubusercontent.com/567047/99322530-bb8eae80-2835-11eb-8276-bc9a6a623836.png)

How do I get that invalid value to remove itself?

**Comment by yairEO** [comment]
I suggest you to use `__isValid` instead of `value`, which is a preferred way of letting Tagify know the current tag is invalid. 

```js
transformTag: (tag) => {
        if(new Date(tag.value).toString() === 'Invalid Date') {
            tag.__isValid = false;   // <------
        }
    },
```

Now that I think of this, it might be a good idea to add some sort of a setting for more advanced validations which cannot be represented by Regex. I will work on it.

**Comment by jeffreydwalter** [comment]
@yairEO that worked perfect! Thank you!

I definitely think providing the ability to write a custom validation callback in a more formal way would be great. Might even be better to get rid of the regex option in favor of just writing a function. 

I take it that `transformTag` isn't really intended to be used for validation, is that right?

**Comment by yairEO** [comment]
Cannot get rid of the regex option because that is a part of the [spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) and I very much like for tagify to seamlessly work alongside the spec for smooth familiar integration.
