### ISSUE TITLE
When using dropdown.mapValueTo option the original whitelist data structure changes

### ISSUE THREAD

**Issue by MiloCasagrande** [yairEO/tagify#703]
### Demo Page

https://jsbin.com/napabubuvu/1/edit?html,css,js,output

### Explanation

- **What is the expected behavior?**
  When using `dropdwon.mapValueTo` and a `whitelist` object-array (like `[{value, name}]`), the original data structure should be left untouched. As said in the [docs](https://github.com/yairEO/tagify#settings):

  > this setting controlls which data key will be printed in the dropdown.

  I expect that option to be valid and applied only in the case of the dropdown.

- **What is happening instead?**
  When using `dropdown.mapValueTo` and a `whitelist` object-array (like `[{value, name}]`), the original data structure is being updated and the `value` data is being overwritten with the data in `name`.

- **What error message are you getting?**
  None

**Comment by MiloCasagrande** [comment]
To clarify a little bit more the issue:

If I have the following options defined for tagify::
```javascript
{
  whitelist: [{value: 'a', name: 'first'}, {value: 'b', name: 'second'}],
  dropdown: {
    mapValueTo: 'name'
  }
}
```
After the dropdown list is shown, the original data structure will result in:
```javascript
[{value: 'first', name: 'first'}, {value: 'second', name: 'second'}]
```

**Comment by yairEO** [comment]
Thanks for reporting, I will fix this tomorrow
