### ISSUE TITLE
Keep dropdown opened ALWAYS for styling

### ISSUE THREAD

**Issue by jarkin13** [yairEO/tagify#706]
I cannot seem to figure out how to keep the dropdown consistently opened for styling. I have tried several ways. I am now trying to do something like:

```js
document.onclick = (e) => {
  e.stopImmediatePropagation();
  tags.disabled = true;
};
```

But nothing seems to work. Can you please provide me with a way to do this. Even when I try to disable js in my debugger, it closes.

**Comment by jarkin13** [comment]
Nevermind I got it with:
```
window.onclick = () => {
  debugger;
};
```

**Comment by yairEO** [comment]
For such things there's a known trick:

    setTimeout(_=> {debugger;}, 3000)
