### ISSUE TITLE
Setting  non-default mixTagsInterpolator fails to parse out tags

### ISSUE THREAD

**Issue by TheWesson** [yairEO/tagify#707]
Tagify Version `3.21.5` on Chrome on Windows

1. Attempt to set non-default mixTagsInterpolator
2. Tags are not created by Tagify constructor

```
    element.value = "set the {{temperature}}"
    var tagify = new Tagify(element, {
        mode: 'mix',
        enforceWhitelist: false,
        whitelist: [],
        duplicates: true,
        transformTag: transformTag,
        pattern: /\$/,
        mixTagsInterpolator: ['{{', '}}'],
        dropdown: {
            enabled: 0,
            maxItems: 1000,
            position: "text",
            highlightFirst: true
        }
    })
```

Problem seems to be that default mixTagsInterpolator is `[ '[[' , ']]' ]`  
and 'extend' function in applySettings makes a combined mixTagsInterpolator  `[ '[[' , ']]', '{{', '}}' ]`  
and that combined mixTagsInterpolator does not work to parse out tags delimited with `{{ }}`

Workaround:
`Tagify.prototype.DEFAULTS.mixTagsInterpolator = []`

**Comment by yairEO** [comment]
Ho, I did make some change a while back to the `extend` method, so it probably affected this scenario. 

I will look into it, thanks for reporting!
