### ISSUE TITLE
clearOnSelect not working?

### ISSUE THREAD

**Issue by alanttran** [yairEO/tagify#710]
Hi! I have a use case where we want to keep the selected choices highlighted in the dropdown instead of being removed. I thought the property 'dropdown._clearOnSelect_' set to false would work but it didn't seem to do anything...

1. Is there a way to prevent the dropdown options from clearing when it is selected?
2. What is clearOnSelect meant to do?

Thank you for your hard work!

**Comment by yairEO** [comment]
`clearOnSelect` referes to the input which the user has just typed, for example you are typing a tag:

    "new "

and then see suggestions: "new york", "new orleans", "new mexico" and so on, and you chose one, and if you set the `clearOnSelect` to `false` then the tag you chose is added and your input is kept so you can keep adding entries which starts with the word `new ` without having to re-type it.

You want to *allow* adding the *same tag* multiple times, from the suggestions list?

**Comment by yairEO** [comment]
Hi, still need assistance?
