### ISSUE TITLE
[React - Mixed mode] remove tag after starting in read-only

### ISSUE THREAD

**Issue by raikow** [yairEO/tagify#711]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] Use chrome (no issue in Firefox)

### 💥 Demo Page
***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-forked-ded84?file=/src/index.js

### Explanation

- **What is the expected behavior?**
Remove should work when start from read-only (true)

- **What is happening instead?**
Instead of removing, it only put it in read-only again

- **What error message are you getting?**
None

- **Screen recording**
[screen-recording.zip](https://github.com/yairEO/tagify/files/5664481/screen-recording.zip)

**Comment by yairEO** [comment]
Thank you for the details bug report :)

**Comment by raikow** [comment]
Hi @yairEO 
Did you have any news on that bug?
Kind Regards

**Comment by yairEO** [comment]
No, I was working on 2 other open-source projects of mine. Is this urgent?

**Comment by raikow** [comment]
Hi, 
No need to rush. I'm looking to fix it for the 1st of January, just wanted a status update for my team 😄 
Thank you.

**Comment by yairEO** [comment]
Yes :) I have many many open source projects and many things to do in all, but if it's very important for your company, I can put it at the top on my list for a small donation for my work
