### ISSUE TITLE
Make the tags clickable

### ISSUE THREAD

**Issue by kinoute** [yairEO/tagify#712]
Hello,

Thanks for this great package! I was wondering if there is an easy way to make the tags clickable natively? By natively I mean without *hacking* with the `click` callback in JS. There must be a way to make our tags clickable to redirect the user to a particular page (for example a page that have all elements with this particular tag). 

I thought doing this in "plain" HTML would be nice. Is it possible or simulating a link with `cursor: pointer` and use the `click`callback is the only way?

Thanks!

**Comment by yairEO** [comment]
You want a user to click a tag and it will go to another page? a user cannot edit a tag?

You can manipulate the tag's template to have an `<a>` tag with an `href` attribute and `target='_blank'` to force opening a new tab. 

Why do you refrain from the `onClick` javascript handler? it's pretty simple to navigate the user through the handler to anywhere you wish..

**Comment by kinoute** [comment]
I want to use tagify both to add new tags and for showing them to the users. When being shown or right after being added, I would like to make the tag clickable yes. Surround the tag's template with a `<a>` sounds nice, I'm going to dig into the documentation to see how to do that. Thanks

**Comment by yairEO** [comment]
https://jsbin.com/yakutul/2/edit?html,css,js,output

https://github.com/yairEO/tagify#dom-templates

```js
var input = document.querySelector('input')
var tagify = new Tagify(input, {
  templates: {
    tag(tagData){
        return `<tag title="${(tagData.title || tagData.value)}"
                    contenteditable='false'
                    spellcheck='false'
                    tabIndex="-1"
                    class="${this.settings.classNames.tag} ${tagData.class ? tagData.class : ""}"
                    ${this.getAttributes(tagData)}>
            <x title='' class="${this.settings.classNames.tagX}" role='button' aria-label='remove tag'></x>
            <div>
                <a href="${tagData.url}" target="_blank" class="${this.settings.classNames.tagText}">${tagData[this.settings.tagTextProp] || tagData.value}</a>
            </div>
        </tag>`
    }
  }
})
```

It would be ideal to check inside the template if `url` is defined or not, for conditionally adding the `href` attribute
