### ISSUE TITLE
In Mix mode, newly created tags are deleted when pressing backspace at the start of textbox

### ISSUE THREAD

**Issue by karthickvkumar** [yairEO/tagify#713]
Hi @yairEO 
Thanks for this amazing plugin. I faced an issue when we type a new tags and press backspace at the start position of the textbox, the entire tags are getting deleted. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/11032434/102181664-0a7d4180-3ed1-11eb-80cd-9b8000da707e.gif)

Thanks in Advance

**Comment by yairEO** [comment]
Thanks for letting me know, I will fix this

**Comment by yairEO** [comment]
Seems this only happens if the textarea first element is a tag (and not text)
