### ISSUE TITLE
document.querySelectorAll - Run the script for all input with the name "tags" - Help

### ISSUE THREAD

**Issue by 1337Zeppelin** [yairEO/tagify#714]
Hello, first of all thank you for this excellent plugin :)
I am currently creating a portfolio for my mom, I code page by page, helping me with tutorials of course, and I am currently designing the administration panel.

I have a table with the site images, some information displayed, and the "edit" and "delete" buttons that open previously generated modals on the page for each image.

I want to integrate Tagify on the "edit" modal for each items.
The problem is, Tagify is working for the first "edit" modal but not for the others surely because of the "querySelector".
The modals being generated in the page with the same name "tags" for the inputs, I would have to run the script for all the inputs with the name "tags"

I should be able to do this with `var input = document.querySelectorAll('input[name=tags]');` but I've been completely stuck since this morning trying a lot of different things that don't work.

Do you have an idea, would you be able to help me?

Thanking you very much in advance, and greetings from France.

Arthur.

**Comment by yairEO** [comment]
I have no idea what's going on without a demo page to inspect.. sorry
