### ISSUE TITLE
Check native support for promises in polyfill

### ISSUE THREAD

**Issue by wrurik** [yairEO/tagify#718]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/xopifopoju/1/edit?html,js,console,output

### Explanation
Including the polyfills breaks native Promises.
I'm using `Promise.allSettled` but it breaks when including the polyfills.
I think there should be a check if native promises are supported before applying the polyfill, or the polyfill should be extended with support for `Promise.allSettled`

**Comment by yairEO** [comment]
I will switch from this:
https://github.com/stefanpenner/es6-promise

to this:
https://github.com/taylorhakes/promise-polyfill

hopefully it will solve your issue

---

Will push a new release soon
