### ISSUE TITLE
Sort tags (not drag)

### ISSUE THREAD

**Issue by romainhe** [yairEO/tagify#721]
Hi, is there a way to sort the selected tags list ?
Yes, we can sort by flex order but what I want is a little more complicated... see the exemple screenshot
<img width="137" alt="Capture d’écran 2020-12-29 à 17 30 40" src="https://user-images.githubusercontent.com/1837829/103298909-a2177f80-49fb-11eb-844d-ee31c0b791a0.png">

thx for your help

**Comment by yairEO** [comment]
who sorts? the user or you, the program owner?

**Comment by romainhe** [comment]
Not a user action, an automatic sort (ex: by type, like the screenshot)

**Comment by yairEO** [comment]
What is stopping you from sorting it yourself?

**Comment by romainhe** [comment]
Well, if I'm not mistaken the <tag> list is automatically generated and there is no hook that will allow to modify the generation behavior of this list, right?

**Comment by yairEO** [comment]
please describe the exact steps of this sorting, as you think it should behave 

I think we aren't talking about the same thing

**Comment by yairEO** [comment]
still need help?

**Comment by romainhe** [comment]
I have two types of tags, A and B.
I have an "outside-of-the-box" type list (as on my screenshot of my first post).

So I would like to make sure that in this list the selected tags are automatically sorted by their type: 

- A 
- A
- A
--- space ---
- B
- B


And as I said, you can't change the automatic generation of elements <tag>, right? 
Maybe a "beforeAddTag" hook in which we would have access to the tags array that we could modify at that time could be useful? Or a "[tags](https://github.com/yairEO/tagify/blob/master/src/parts/templates.js)" template ?

**Comment by yairEO** [comment]
If you had provided a demo jsbin, as I begged for to do in the issue template, I could have helped much easier..

**Comment by romainhe** [comment]
Sorry for no providing a demo jsbin ; for me it wasn't an issue, I select "Help with something"

I create a code sandbox : https://codesandbox.io/s/tagify-sort-list-43u6u-43u6u

I've done most of the sorting with flexbox, but what I need as a final result requires a bit more than css (see screenshot)
<img width="457" alt="Capture d’écran 2021-01-18 à 14 33 06" src="https://user-images.githubusercontent.com/1837829/104921806-18bff100-599a-11eb-826e-98f28e2d848f.png">
To make the space between the two types you need an element that "breaks", or detect that one of the tags is the last of the first type, or the first of the second type...

Unless you have another solution?

Thx

**Comment by yairEO** [comment]
after over an hour and half of trying stuff I came up with this solution:

https://codesandbox.io/s/tagify-sort-list-43u6u-forked-sz55u?file=/src/index.js

Basically adding 2 containers within the main scope template which will host the tags, per `type`

**Comment by romainhe** [comment]
Oh great, thx for your time! So using the "add" event is enough. 
Just to understand, what makes that the tag is not added twice? Here we execute an action at a specific event but without "preventing" the event (add). I'm missing something...
Or maybe tagify detects the fact that the tag already exists in the DOM and therefore does not add it?

**Comment by yairEO** [comment]
The flow is this:
1. The tag is added & already in the DOM
2. an `add` event is fired
3. the `add` event listener is triggered in *your* and a callback is invoked
4. in the callback, the data passed from Tagify includes a reference to the DOM node which was added (the tag)
5. `appendChild` **moves** that node to a new place (which was prepared in the *template setting* of `wrapper`

**Comment by romainhe** [comment]
ok, here's the subtlety, thx
