### ISSUE TITLE
"Crazy Tags" demo in Next.js React app - ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by taylorhlabs** [yairEO/tagify#722]
I am just trying to set up the "Crazy Tags" page from the [React Demo](https://codesandbox.io/s/tagify-react-wrapper-oempc) in my Next.js project. I have installed the tagify package via NPM and essentially copy/pasted the code from the CrazyTags.js and mockServer.js demo files to my project. (And I made sure to update the reference to the tagify package in CrazyTags.js file.) When I try to run the demo page, I get the following error:
```
ReferenceError: navigator is not defined
    at /Users/userX/Documents/GitHub/next-auth-prisma-mysql/node_modules/@yaireo/tagify/dist/tagify.min.js:1:1972
    at /Users/userX/Documents/GitHub/next-auth-prisma-mysql/node_modules/@yaireo/tagify/dist/tagify.min.js:1:84
    at Object.<anonymous> (/Users/userX/Documents/GitHub/next-auth-prisma-mysql/node_modules/@yaireo/tagify/dist/tagify.min.js:1:159)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /Users/userX/Documents/GitHub/next-auth-prisma-mysql/node_modules/@yaireo/tagify/dist/react.tagify.js:1:990
    at /Users/userX/Documents/GitHub/next-auth-prisma-mysql/node_modules/@yaireo/tagify/dist/react.tagify.js:1:107
    at Object.<anonymous> (/Users/userX/Documents/GitHub/next-auth-prisma-mysql/node_modules/@yaireo/tagify/dist/react.tagify.js:1:130)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```
Any idea what might cause this? Not really sure where to start. Thanks for any input!

**Comment by taylorhlabs** [comment]
I also get the same error when trying to set up a stripped down example. Am I missing a dependency? Or is there a compatibility issue with Next.js?

**Comment by yairEO** [comment]
This is probably unrelated error due to the usage of react-router in my demo.

Why are you cloning my "crazy tags" page and not creating your own env and installing Tagify via NPM?

It would work well then

**Comment by taylorhlabs** [comment]
I did install via NPM and followed the instructions for React in your documentation. Before trying to clone your example, I tried to setup a basic instance of <Tags /> in my own project and got the same error. I'll keep digging on my end though as it seems to be a problem with my env. Thanks for your efforts on the plugin. Looks awesome if I can get it working.

**Comment by yairEO** [comment]
Can you replicate your *env* on *codesandbox.io* ?

**Comment by hype08** [comment]
hello @taylorhlabs have you figured out the issue for this?
i also have the exact same issue on Next.js 10 and also have my own example that's not a sandbox.


10:23:19.230 | Module not found: Can't resolve 'preact-render-to-string' in '/vercel/workpath0/node_modules/preact/compat'
-- | --
10:23:19.230 | info  - Collecting page data...
10:23:21.635 | > Build error occurred
10:23:21.638 | ReferenceError: navigator is not defined
10:23:21.638 | at /vercel/workpath0/node_modules/@yaireo/tagify/dist/tagify.min.js:1:1972
10:23:21.638 | at /vercel/workpath0/node_modules/@yaireo/tagify/dist/tagify.min.js:1:84
10:23:21.638 | at Object.<anonymous> (/vercel/workpath0/node_modules/@yaireo/tagify/dist/tagify.min.js:1:159)
10:23:21.639 | at Module._compile (internal/modules/cjs/loader.js:1063:30)
10:23:21.639 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
10:23:21.639 | at Module.load (internal/modules/cjs/loader.js:928:32)
10:23:21.639 | at Function.Module._load (internal/modules/cjs/loader.js:769:14)
10:23:21.639 | at Module.require (internal/modules/cjs/loader.js:952:19)
10:23:21.639 | at require (internal/modules/cjs/helpers.js:88:18)
10:23:21.639 | at /vercel/workpath0/node_modules/@yaireo/tagify/dist/react.tagify.js:1:990 {
