### ISSUE TITLE
Any implication of removing max-width from .tagify__input::after?

### ISSUE THREAD

**Issue by neilgd** [yairEO/tagify#723]
On desktop Safari (but not on Firefox or Chrome), the suggested tag is wrapping over a line:

![Screenshot 2021-01-10 133611](https://user-images.githubusercontent.com/1759173/104124629-c7848180-5349-11eb-870f-1af3f0a87ff9.png)

(You can see this at https://rawumberstudios.com/video-search/)

I can't reproduce it in a simple example, so I assume it's some sort of CSS clash with something else in my project.

If I disable max-width:100px from .tagify__input::after it seems to fix the problem though.

Perhaps you could me know if there's any reason I shouldn't do this though?

Thanks!

**Comment by yairEO** [comment]
you should do this, it's completely fine. That `max-width` has an arbitrary value and is only used to trim very long tags. If you know you don't have such long tags, then you do not need that trimming.

**Comment by neilgd** [comment]
Thank you very much!
