### ISSUE TITLE
tagTextProp makes value attribute 'undefined'

### ISSUE THREAD

**Issue by kurtinaitis** [yairEO/tagify#724]
## Prerequisites

- [x] I am running the latest version 3.22.0
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codesandbox.io/s/tagify-react-issue-template-forked-bfur8?file=/src/index.js

### Explanation
- **What is the expected behavior?**
-- when typing `123`, I expect to get it displayed as `123 (3)`

- **What is happening instead?**
-- it displays `undefined (9)`

- **What error message are you getting?**
- none

**Comment by yairEO** [comment]
You should write it as so:

```js
import React, {useCallback, useRef} from "react"
import ReactDOM from "react-dom"
import Tags from "@yaireo/tagify/dist/react.tagify"
import "./styles.scss" // basic styles for this demo

function App() {
  const tagifyRef = useRef()

  const settings = {
    editTags: false,
    dropdown: {enabled: false},
    tagTextProp: "displayValue",
    transformTag(tagData) {
      tagData.value = tagData.displayValue
      tagData.displayValue = `${tagData.value} <b>(${tagData.value.length})</b>`
      tagData.title = tagData.value.length
    }
  }

  const onTagsChange = () => {
    console.log("tags changed")
  }

  return (
    <>
      <h1>Tagify React Issue Template</h1>

      <br />
      <br />
      <Tags
        tagifyRef={tagifyRef}
        settings={settings}
        placeholder="type tags"
        onChange={onTagsChange}
      />
    </>
  )
}

ReactDOM.render(<App />, document.getElementById("app"))
```

**Comment by kurtinaitis** [comment]
Thanks for quick reply. I solved the issue by overriding HTML templates.
By looking at code I got an impression that `tagTextProp` is meant as an alternative property when there is no `value`. O is it really meant for display purposes?

**Comment by yairEO** [comment]
It says so in the [docs](https://github.com/yairEO/tagify#settings):

> *Tag data Object property which will be displayed as the tag's text. Remember to keep "value" property unique.*

You situation is unique, and I have never considered it. You have no *whitelist* and you still want to use `tagTextProp`.. which is weird, but I get it.

Anyway, my above solution is more elegant than modifying the template..
