### ISSUE TITLE
Feature request: add select & mix namespace classnames to the settings.classNames object

### ISSUE THREAD

**Issue by FRSgit** [yairEO/tagify#726]
Hey!
Thanks for the great library!

### Situation description
Now, this package allows to use custom class names by passing the new ones in the options object when creating new `Tagify` instance.
Unfortunately the above is not true for the two of class names - `namespace--mix` & `namespace--select` - they are being generated by taking namespace class name and adding the correct mode suffix (e.g.: `className.namespace + '--mix'`).

For my use case (working with CSS-modules) all of the classes are autogenerated in the production build, which means that e.g. `.namespace` class will be compiled into `.a`, but `.namespace--mix` will be compiled into something like `.b`.
And because of that just adding suffix to the namespace class does not work - the classes for mix & select modes are completely different. Now I'm ending up with something like `.a--mix` on the wrapper element instead of `.b`.

### Feature to be added
It would be nice to create 2 new properties in the classNames object: `mixMode` & `selectMode` to cover all mode-related classNames.
And when adding the classname instead of `classNames.namespace + mode` we would need to write `classNames[mode + 'Mode']`. 

What do you think? I can prepare a pull request implementing this if you want

**Comment by yairEO** [comment]
Good point, I will work in it.

**Comment by yairEO** [comment]
Done

https://github.com/yairEO/tagify/releases/tag/v3.22.1

**Comment by FRSgit** [comment]
Hey @yairEO 

About rewriting the wrapper - yup, that's exactly what I did in my project:
```js
templates: {
  wrapper(...args) {
    // adds css modules support for mix & select mode-related classes
    // in original implementation they are generated by adding `--mix` or `--select` suffix to the namespace class
    // TODO: follow up on related feature request: https://github.com/yairEO/tagify/issues/726
    const settings = args[1];
    const { classNames, mode } = settings;
    const template = Tagify.prototype.templates.wrapper.call(settings, ...args);
    return template.replace(classNames.namespace, classNames.namespace + ' ' + classNames[mode]);
  },
}
```
But well, that's not a pretty solution 😄 

And yes, there is an option to disable "classnames mangling" for some classnames (you can specify a whitelist), but that's also a bit hacky. I thought it would be perfect to have this handled directly in the library for any future users.

Thanks for changing this so quickly! Have a great week!
