### ISSUE TITLE
Request focus programmatically 

### ISSUE THREAD

**Issue by msayed-net** [yairEO/tagify#729]
After selecting/unselecting I have to rebuild some parts of the page, after that I need to re-focus inside tags input so user can continue.
I searched almost everywhere and tried many tricks, did not work
How to get it done..

Thanks

**Comment by yairEO** [comment]
what does "selecting/unselecting" means? what have you tried? can you make a demo page in jsbin?

**Comment by msayed-net** [comment]
Sorry I meant add/remove

```javascript
let input = document.querySelector(`input[id=${id}]`);
let tagify = new Tagify(input);
tagify.on('add', function (e) {
    // some work
    // rebuild DOM
});
tagify.on('remove', function (e) {
    // some work
    // rebuild DOM
});
```

after rebuilding parts of DOM tagify element loses focus, I need to get focus back into it, so keyboard inputs gets into

**Comment by yairEO** [comment]
whats does this sentence means:

> after rebuilding parts of DOM

I need to see a demo..
