### ISSUE TITLE
When using objects, typing tab to insert tag inserts value rather than tag

### ISSUE THREAD

**Issue by tim-fernico** [yairEO/tagify#732]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jukuzenohu/1/edit?html,js,output

### Explanation

Type `it` then `TAB` to add the first dropdown item

- **What is the expected behavior?**
Pressing Tab with an item selected in the dropdown should insert the tag
- **What is happening instead?**
Tab is inserting the value property
- **What error message are you getting?**
None

Thanks for a great library!

**Comment by yairEO** [comment]
Thanks for reporting, I will work on it soon
