### ISSUE TITLE
Unable to render tags when using object-based whitelist 

### ISSUE THREAD

**Issue by bluesurfer** [yairEO/tagify#735]
Consider the following code:

```
// initialize Tagify
var input = document.querySelector('textarea'),
    // init Tagify script on the above inputs
    tagify = new Tagify(input, {
        whitelist: [
            {
                code: 1,
                name: 'foo'
            },
            {
                code: 2,
                name: 'bar'
            }
        ],
        enforceWhitelist: true,
        tagTextProp: 'code',
        dropdown: {
            mapValueTo: 'name',
            enabled: 0,
            maxItems: 5,
            position: "all",
            closeOnSelect: false,
            highlightFirst: true,
            searchKeys: ['name', 'code']
        },
    })
    })
```

The dropdown menu works fine but when I click over an item then `tagify` won't render the corresponding tag. No errors are generated in the console

**Comment by yairEO** [comment]
The above whitelist is invalid as it must contain a `value` key

**Comment by yairEO** [comment]
I now see the README is missing that part where I once wrote that the `value` property is crucial for Tagify to work, I will re-add it

**Comment by bluesurfer** [comment]
@yairEO thanks for replying so fast. 

I confess that `mapValueTo` and `tagTextProp` tricked me. I was expecting to be able to map `value` into a unique property of the object list.

**Comment by yairEO** [comment]
just map the array and add `value` and make sure it will be a unique value, Tagify relies on it heavily, basically the whole code is build around the `value` :)
