### ISSUE TITLE
enforceWhitelist not enforcing whitelist

### ISSUE THREAD

**Issue by gmblack** [yairEO/tagify#736]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://yaireo.github.io/tagify/
Users List example

### Explanation
When you type in an invalid tag, for example, "ABC", then click off of the element, the invalid tag does not get removed.  It should be removed since it is not in the whitelist.

**Comment by ulinder** [comment]
I had the same issue until I realised I had put enforceWhitelist: true inside the dropdown: { }
It came naturally for me from copying the demo code :)

**Comment by yairEO** [comment]
@gmblack - I do not see any bug - no text which is *not* in the whitelist can be added as tag to the component. You are free to type whatever in the field but it will not turn into a tag

@ulinder - Do not put `enforceWhitelist:true` setting inside `dropdown:{}`, it doesn't belong there and will have no effect

**Comment by kriiv** [comment]
I was having a similar issue (albeit the opposite). Putting `enforceWhitelist:true` inside `dropdown:{}` made it work.

**Comment by Velisariy** [comment]
Similar problem: if I use code as below
```
new Tagify(input, {
    enforceWhitelist : true,
    whitelist: [{"value": "sdfsd"}],
})
```
enforceWhitelist is not working

**Comment by yairEO** [comment]
@Velisariy - please create a test page ([jsbin](https://jsbin.com/jekuqap/edit?html,js,output)) the shows this because I cannot reproduce

**Comment by Velisariy** [comment]
@yairEO [link](https://jsbin.com/fevuwemixa/1/edit?html,js,output)
Just like that
enforceWhitelist works only if you type a comma

**Comment by yairEO** [comment]
Are you running the code on the server?

**Comment by yairEO** [comment]
Thanks, now I understand. blurring with invalid content typed in should converted it to a "red background" tag and then delete it after a second, which doesn't not happen when the whitelist has objects instead of strings. 

I will investigate today.

While this is weird, and might confuse the user, it does not create any bug in the data saved and still only valid input will be converted into tags

**Comment by yairEO** [comment]
I fixed it and will push the fix along with the next Tagify version deployment because I want to gather some more fixes togather

**Comment by Velisariy** [comment]
I think "Mode select" have similar issue: it also clear input field after typing a comma symbol but not clears after blurring
```
new Tagify(input, {
    enforceWhitelist : true,
    whitelist: [{"value": "sdfsd"}],
    mode: "select",
})
```

Also should it clear invalid tags if you dynamically change whitelist array on another?

**Comment by yairEO** [comment]
@Velisariy 

> Also should it clear invalid tags if you dynamically change whitelist array on another?

What do you mean *"on another"*?

**Comment by Velisariy** [comment]
@yairEO 
Well, I mean update whitelist by ajax.
For example: initial whitelist was ['Cat breed 1', 'Cat breed 2'] and you choose tag 'Cat breed 1'.After that you change whitelist by ajax for another one like ['Dog breed 1', 'Dog breed 2']. So, your input field already have tag value 'Cat breed 1' but that value is not in whitelist. No warnings, no clears in spite of enforceWhitelist was set as true

**Comment by yairEO** [comment]
@Velisariy - Please create a reproducible demo page as I must see exactly in what way you are modifying the whitelist array
