### ISSUE TITLE
When using classNames on certain entries with Tailwind classes that contain a colon, errors occur.

### ISSUE THREAD

**Issue by NullVoxPopuli** [yairEO/tagify#737]
## Prerequisites

- [x] I am running the latest version (3.22.1)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/bucixunuxi/2/edit?html,js,output

### Explanation

- **What is the expected behavior?**

Tagify doesn't use `classNames` as selectors, as there is a lot of variability. I'd expect some internal IDs / guids to be used, or some reference system that doesn't need to query the DOM once the DOM is written to? idk. 

- **What is happening instead?**
- 
Tagify is using classNames as selectors

- **What error message are you getting?**

```
Uncaught DOMException: Element.querySelector: '<the entirety of the classNames list>' is not a valid selector
```

**Comment by yairEO** [comment]
Closing as you opened the exact same issue twice
#738
