### ISSUE TITLE
How to refer to duplicated tags ?

### ISSUE THREAD

**Issue by jetacpp** [yairEO/tagify#739]
Looking through current documentation, tagify refers to tags as "tag names" or "values". All events are generated and associated with names. In the use case where duplicated names are allowed, such as tag "Apple" with background green and tag "Apple" with background red. How do I distinguish between the two tags in tagify event system ? Perhaps, an ID attribute should be preserved as `e.detail.data.id` along side `e.detail.data.value` ?

**Comment by yairEO** [comment]
Why do you need to distinguish between tags which you allowed to be duplicates? I don't see how will some randomly generated ID tagify will create can help you since you can generate it on your own, and even so, again it's not clear in what way would it be beneficial

**Comment by jetacpp** [comment]
Yes, I meant I will provide IDs to each tag, but tagify must preserve it as its data attributes. As an example, let say I have:
```
getTags() {
  return [
{
    value: "apple",
    title: "green apple",
    style: `--tag-bg: green;`
    id: 75;   /// new
  },
{
    value: "apple",
    title: "red apple",
    style: `--tag-bg: red;`
    id: 76; // new
  }
 ]
}
```

```
tagifySettings: {
        callbacks: {
          click: (e) => {
            // identify tag by id
            if (e.detail.data.id === 75)  console.log('green apple selected')
            if (e.detail.data.id === 76) console.log('red apple selected')
            // cannot identify tag by names if duplicates are allowed
            if (e.detail.data.value === 'apple')     console.log('red or green apple ? ')
          },
        },
}
```

**Comment by yairEO** [comment]
I thought you were talking about the `duplicates` setting...

Use the `tagTextProp` settings

new Tagify(inputElm, { tagTextProp: 'text' })

And then define the whitelist like so:

[
  {
    value: 87651,
    text: 'apple`,
    title: "green apple",
    style: `--tag-bg: green;`
  },
  {
    value: 30534,
    text: 'apple,
    title: "red apple",
    style: `--tag-bg: red;`
  }
} 

again, this is not related to the `duplicates` setting which allows to really select completely identical tags (same value) again and again

**Comment by jetacpp** [comment]
Thank you ! `tagTextProp` precisely solved my issue
