### ISSUE TITLE
Can't select tag in `mix` mode when whitelist is an array of plain strings

### ISSUE THREAD

**Issue by NullVoxPopuli** [yairEO/tagify#740]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/mevawilevi/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**

No error, I can select `a` from the suggestions dropdown

- **What is happening instead?**

An error

- **What error message are you getting?**
```
Uncaught TypeError: can't assign to property "prefix" on "a": not an object
    prefixedTextToTag https://unpkg.com/@yaireo/tagify:1
    addMixTags
```

**Comment by NullVoxPopuli** [comment]
If I map over the suggestions, it works though: https://jsbin.com/wuwikahapu/1/edit?html,js,output

**Comment by yairEO** [comment]
Because `mix` mode `whitelist` must be an Array of Objects (collection) and not an Array of Strings.

May I know why are you using an Array of Strings?

**Comment by NullVoxPopuli** [comment]
> May I know why are you using an Array of Strings?

There is nothing special about the list of of tokens/tags -- they just "are", no need for IDs, labels, or anything like that

**Comment by yairEO** [comment]
I've fixed it so please use the latest Tagify version
