### ISSUE TITLE
onmozfullscreenchange / onmozfullscreenerror

### ISSUE THREAD

**Issue by Offerel** [yairEO/tagify#743]
There is an warning at least in Firefox 85.x that onmozfullscreenchange and onmozfullscreenerror should not used anymore. Its only a warning, not an error.

![grafik](https://user-images.githubusercontent.com/14041522/107876577-15e7eb80-6ec7-11eb-8183-c5a9d1347b2f.png)

Tried with tagify-3.22.1 and tagify-3.22.2

**Comment by yairEO** [comment]
I don't use this command and it's not in the [Tagify's source code](https://github.com/yairEO/tagify/blob/v3.22.1/dist/tagify.min.js)

It might come from your own project, look it up and let me know

**Comment by Offerel** [comment]
It seems, i get this, when i call `tagify.addTags(note.tags);`. note.tags contains a string of comma separated words, like `Code, Javascript, Coding, Scripts`. If i understand the documentation right, this should be no issue. 

But you are right, I have also not found onmozfullscreenchange or onmozfullscreenerror in your code. But this is the only place, where i get this warning. Tagify is bind to a input type text field via `document.getElementById('ntags')`. I don't know if this is an issue.

**Comment by yairEO** [comment]
I don't know what to tell you, but i found this:
https://stackoverflow.com/a/58687133/104380

**Comment by Offerel** [comment]
Yepp, found this also yesterday in the evening. The only problem is, that did not output such objects to the console. Since i didn't get this in Chromium and the API is deprecated, i ignore it for now. It has no direct impact on my project, I don't use the code somewhere directly. If this API is dead, it will be removed some time later...

However, many, many thx for your help. Im really happy, that i have found your library.
