### ISSUE TITLE
Uncaught TypeError: t is undefined

### ISSUE THREAD

**Issue by Offerel** [yairEO/tagify#744]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation
When calling removeAllTags() i got the above error message, after updating to tagify 3.22.2. It worked correct with 3.22.1
```javascript
var tagify = new Tagify(document.querySelector('#ntags'), {
	whitelist:[],
	dropdown : {
		classname     : "color-blue",
		enabled       : 0,
		maxItems      : 0,
		position      : "text",
		closeOnSelect : false,
		highlightFirst: true
	},
	trim: true,
	duplicates: false,
	enforceWhitelist: false,
	delimiters: ',|;| ',
	placeholder: 'Tags'
	});

tagify.setReadonly(true);
tagify.removeAllTags();
tagify.addTags(note.tags);
```

![grafik](https://user-images.githubusercontent.com/14041522/107876801-8a6f5a00-6ec8-11eb-9e57-f1a6de3e1910.png)

BTW: Above error was in Firefox 85.x, in Chromium i get:

```
Uncaught TypeError: Cannot read property 'withoutChangeEvent' of undefined
    at f.removeAllTags (tagify.min.js:1)
    at Object.success (notes.min.js:9)
    at c (jquery.min.js:36)
    at Object.fireWith [as resolveWith] (jquery.min.js:36)
    at l (jquery.min.js:36)
    at XMLHttpRequest.<anonymous> (jquery.min.js:36)
```

**Comment by Offerel** [comment]
Changing my code to 
```javascript
tagify.removeAllTags({
	withoutChangeEvent: true
});
```
will workaround the issue for now. Found this in some comment on the issue tracker. Maybe this helps to identify the issue.

**Comment by yairEO** [comment]
Thanks, will push a fix today
