### ISSUE TITLE
update tags

### ISSUE THREAD

**Issue by mehdijalalii** [yairEO/tagify#746]
i used from yairEO/tagify jquery plugin and save tags in database.
To edit these tags, when the double click on tag name, the id and other additional information will be deleted, and I will have trouble saving it because I do not have the db row id.
How do I keep the ID after editing the tags?
`<input name="drag-sort" value="[{id:1,unit_id:19,value:test1},{id:2,unit_id:19,value:test2}]">
`

**Comment by mehdijalalii** [comment]
@yairEO please help me

**Comment by yairEO** [comment]
I will help, i'm investigating this

**Comment by yairEO** [comment]
May I know your exact Tagify configuration? I need to know if you configured any specific settings

**Comment by yairEO** [comment]
Can you change `id` to `value`, or at least use the same `id` as `value` as well:

```js
[
  {
    value: 1,
    id: 1,
    unit_id: 19,
    text: test1
  }, {
    value: 2,
    id: 2,
    unit_id: 19,
    text: test2,
  }
]
```

Then you can configure Tagify with `tagTextProp: 'text'` setting and the data will persist after editing

**Comment by mehdijalalii** [comment]
**i used from this code for js:**
```
$("input[name=drag-sort]").each(function () {
    var input = document.querySelector('input[name=drag-sort]'),
        tagify = new Tagify(this);

    var dragsort = new DragSort(tagify.DOM.scope, {
        selector: '.' + tagify.settings.classNames.tag,
        callbacks: {
            dragEnd: onDragEnd
        }
    })

    function onDragEnd(elm) {
        tagify.updateValueByDOMTags()
    }
});
```
and use laravel code for generate json.
I will use your guidance and inform you of the result. Thank you very much for your attention.

**Comment by mehdijalalii** [comment]
@yairEO problem not resolved
**before edit test1 tag:**
[{"value":1, "id":1, "text":"test1"}, {"value":2, "id":2, "text":"test2"}]
**after edit test1 tag:**
[{"text":"testing","value":"testing"},{"value":2, "id":2, "text":"test2"}]

id removed and value and text duplicate

**Comment by yairEO** [comment]
I just fixed it and will release a version in a few minutes. disregard using the `tagTextProp: 'text'` setting

**Comment by mehdijalalii** [comment]
@yairEO i test new release and problem not resolved

**Comment by mehdijalalii** [comment]
@yairEO problem resolved with "type".
in type attribute used id.

**Comment by mehdijalalii** [comment]
@yairEO problem resolved and extra data not removed after edit
