### ISSUE TITLE
Display suggestions as clickable tags to insert rather than list.

### ISSUE THREAD

**Issue by kriiv** [yairEO/tagify#748]
Looking at the "Render Suggestions List Manually" demo, it works great! Is there a way to have the suggested tags show as tags below the input, instead of a dropdown list? 

Something like this?
![Screen Shot 2021-02-05 at 10 42 41 am](https://user-images.githubusercontent.com/42486612/108140144-99971780-7115-11eb-9236-c69da8b40d4a.png)

Appreciate any help. Thanks!

**Comment by yairEO** [comment]
of course, with CSS you can give it any style. Do you know CSS?
