### ISSUE TITLE
Multiple tagifys on one page

### ISSUE THREAD

**Issue by kriiv** [yairEO/tagify#749]
Wondering what would be the simplest way to have multiple Tagify fields on a single page? They will all have suggestion dropdowns as per suggestion demo. 

I've tried simply duplicating the code and renaming but having all kinds of issues. I'm guessing there is a better way.

Any help is appreciated.

**Comment by yairEO** [comment]
the demo page shows many Tagify components on a single page, it's the same as having one Tagify component, I don't see the problem since you did not create a demo and did not explain what is the problem

**Comment by antonio-quintino** [comment]
Hi,

I'm facing a related problem too:
When using multiple Tagify fields with dropdowns, vertically disposed and close enough to each other, if you click on a dropdown option that overlaps one of the next Tagify fields what happens sometimes is that the overlapped field dropdown opens and stays open without the respective field being focused.

Demo here: https://v6thd.csb.app/

And video example:
https://user-images.githubusercontent.com/1964284/114052347-e1b8f780-9885-11eb-8fc6-a66a6e9bbd33.mp4

**Comment by yairEO** [comment]
@antonio-quintino - The problem doesn't happen to me in your demo page, tested on Chrome & Firefox.

**Comment by yairEO** [comment]
I see and will work on a fix

**Comment by antonio-quintino** [comment]
Thanks @yairEO seems to be working fine now.
