### ISSUE TITLE
Space like delimiter

### ISSUE THREAD

**Issue by yaalaa** [yairEO/tagify#75]
```
"@yaireo/tagify": "^2.0.0"
```

I'd like to use space as delimiter.
I see funny behavior when a use `delimiters` with space.
Typing a space takes no effect (due to `trim` I suppose).
How ever when I type another letter it adds two tags: word before space and just typed letter.

It's like enhancement request.

**Comment by yairEO** [comment]
Thanks for reporting

**Comment by slivlikh** [comment]
Hello @yairEO, this bug is reproduceding in 4.17.9
