### ISSUE TITLE
Is there a way to disable the field? 

### ISSUE THREAD

**Issue by arkadyb** [yairEO/tagify#750]
Hi! I wonder if there is an option i can pass to have the text field be inactive/disabled? Similar to what passing `disabled=true` would do to TextField from MaterialUI. Thanks!

**Comment by yairEO** [comment]
`setReadonly` method (it's in the README docs) and the [React demo](https://codesandbox.io/s/tagify-react-wrapper-oempc) shows it in action:

Go to the "mix mode" tab in the demo page and see:
![image](https://user-images.githubusercontent.com/845031/108597535-2ea64480-7392-11eb-95fa-43acd979e16c.png)
