### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by shpsyte** [yairEO/tagify#751]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I am getting an error that says "ReferenceError: navigator is not defined"
tagify.min.js
  var isChromeAndroidBrowser = /(?=.*chrome)(?=.*android)/i.test(navigator.userAgent);

    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-router-config": "5.0.1",
    "react-router-dom": "^5.1.2",

It's a BUG or is missing a dependency on it ?

**Comment by shpsyte** [comment]
![image](https://user-images.githubusercontent.com/3891610/108440351-cfb4c400-7207-11eb-885d-f5dfe4abb3d8.png)

**Comment by shpsyte** [comment]
![image](https://user-images.githubusercontent.com/3891610/108440462-0c80bb00-7208-11eb-8daf-a226d8bab8ef.png)

**Comment by yairEO** [comment]
Are you running the code on the server?

You should know that `navigator` is a DOM API which does not exists on a Node env, therefore, you should mimic it. Googling this gives a good answer:

https://stackoverflow.com/a/64485039/104380

**Comment by shpsyte** [comment]
Tks, I am not running the code on the server.

I just install the component on the React Project and then try to use it, but during the compilation, I got this error.

**Comment by shpsyte** [comment]
But you close this one, ok. No problem with that.

**Comment by yairEO** [comment]
I closed because it is impossible you get `navigator is not defined` if you're running this on a browser. All browsers have `navigator` unless perhaps in your project it was overwritten, and even so, it's not a Tagify problem but it is a problem which is specific to your codebase, therefore I closed this because there is nothing I can do
