### ISSUE TITLE
Angular 11 : No suitable injection token for parameter 'tagifyService' of class 'MyMenuAddComponent'.

### ISSUE THREAD

**Issue by ayoubkhan558** [yairEO/tagify#752]
## Prerequisites

- [-] I am running the latest version : Angular 11 
- [ -] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
- It should run basic example

- **What is happening instead?**
- It is giving me the error 

- **What error message are you getting?**
![image](https://user-images.githubusercontent.com/20210961/108484100-555c6200-7250-11eb-8ce6-6c00ccbc7b83.png)

**Comment by yairEO** [comment]
I did not make the Angular point but it was contributed by another user, and since I know nothing about Angular, I sadly cannot fix this..sorry

**Comment by ayoubkhan558** [comment]
> I did not make the Angular port (of Tagify), it was contributed by another developer
> 
> I know nothing about Angular so I sadly cannot fix this..sorry

Please tag him here. or ask him to contribute to fix this error. Thank you waiting ..

**Comment by yairEO** [comment]
it's her, not him, and it was two years ago.. I asked her to help, it was a one-time thing.

**Comment by yairEO** [comment]
Please refer https://github.com/Brakebein/ngx-tagify as the official place for all angular related Tagify things
