### ISSUE TITLE
Dropdown shows values instead of names

### ISSUE THREAD

**Issue by TheMixy** [yairEO/tagify#753]
On page load (ASP.NET Core) I'm using javascript/ajax to fetch an object list from the database and store it in `tagList` variable.

The `tagList` is a list of objects: `{ name: "string", value: integer }`; for example `{ name: "Accounting", value: 1 }`. 

This is how I initialize tagify on my textarea control:
`var input = document.querySelector('textarea[name=tagTags]'),`
`tagify = new Tagify(input, {`
`tagTextProp: 'name',`
`enforceWhitelist: true,`
`delimiters: null,`
`whitelist: tagslist,`
`editTags: false,`
`dropdown: {`
`enabled: 0,`            
`searchKeys: ['name']`
`},`
`});`

Everything works, except that suggestions shown in drop down are values, not names. But If I select one, then name is shown in the textarea. Also search works by both names and values.

Why are values shown in suggestions and not names?

Thank you
Miha

**Comment by yairEO** [comment]
You need to also provide the `dropdown.mapValueTo = 'name'` in the settings

**Comment by TheMixy** [comment]
Thank you. Works great!
