### ISSUE TITLE
Dropdown jumps from bottom to top

### ISSUE THREAD

**Issue by rsdsoft** [yairEO/tagify#754]
```
placeAbove = viewportHeight - rect.bottom+200 < ddHeight; // flip vertically if there is no space for the dropdown below the input

      ddElm.style.cssText = "left:" + (left + window.pageXOffset) + "px; width:" + width + ";" + (placeAbove ? "top: " + (top + window.pageYOffset) + "px" : "top: " + (bottom + window.pageYOffset) + "px");
      ddElm.setAttribute('placement', placeAbove ? "top" : "bottom");
```
Can I prevent dropdown jumping by some option? I want it apepars on the bottom always in any cases.
I use in code 
```
placeAbove = false;
```
But would be nice to have some option.

**Comment by yairEO** [comment]
Currently there is no such way and you should not modify Tagify because you will not be in sync with future updates.

I will put this as a task for me to investigate regarding how to force the placement of the dropdown

**Comment by yairEO** [comment]
fixed - added `dropdown.placeAbove` setting which can be `true` or `false` which forces the placement of the suggestions dropdown to be above or below, always.
