### ISSUE TITLE
Multiline tags have a white background in the middle

### ISSUE THREAD

**Issue by phigrofi** [yairEO/tagify#755]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
Just type in a very long tag

https://codesandbox.io/s/simple-tagify-setup-6pfi2

### Explanation

- **What is the expected behavior?**
A tag with multiple lines should have a filled background

- **What is happening instead?**
It looks like it has a very bold border. 
<img width="548" alt="Screenshot 2021-02-22 at 06 11 19" src="https://user-images.githubusercontent.com/3541603/108665524-6538a800-74d5-11eb-8651-bc6582121a9c.png">

It looks like the background is solved by a box shadow and I didn't know why this was used instead of a background color. So I did not know how to solve this.

**Comment by yairEO** [comment]
This is not a bug, this is a `box-shadow` with `inset`. Tags are not meant to be multiline, so you need to adjust the CSS to accommodate for that: [`--tag-inset-shadow-size`](https://github.com/yairEO/tagify#css-variables) CSS variable.

[The demo](https://yaireo.github.io/tagify) page shows how it affects the tags - go to the demo page and click on the top right settings icon and play with that value
