### ISSUE TITLE
Method to focus specific input

### ISSUE THREAD

**Issue by kfuzaylov** [yairEO/tagify#756]
Sometimes I need set focus to specific tagify input. Could you create method like `focus`
Example
`const tags = new Tagify(input, options);
tags.focus();`

Thanks.

**Comment by yairEO** [comment]
You can give the `input` element (`tagify.DOM.input`) focus using the DOM api:

```js
tagify.DOM.input.focus()
```

All you need is to refer to the input element which is inside the Tagify component

**Comment by Timmaaaa** [comment]
Can you please put this in the documentation? 🙏 I searched for atleast half a day for this haha

**Comment by yairEO** [comment]
What you just described is a bug which I wasn't aware of, and will work on asap
