### ISSUE TITLE
Full height size of cursor in text area if mixed content starts with clip

### ISSUE THREAD

**Issue by Megas78** [yairEO/tagify#760]
Hello!
If first value of textarea is clip and you put cursor to the start of it - you will see full height size cursor. Please check screenshot from demo page. Thanks.
![Screenshot at Feb 25 15-17-07](https://user-images.githubusercontent.com/19715177/109158987-c209bc00-777c-11eb-9b88-a251bdb90e45.png)

**Comment by yairEO** [comment]
*If first value of textarea is clip*

whats is "clip" ? I don't know this term

**Comment by Megas78** [comment]
Good day! Thanks for the quick response and sorry for the inconvenience.

I reproduced it in Mac OS Big Sur 11.2.1  / Google Crome 88.0.4324.150 
To reproduce this issue:
1. Add TAG as the first element of the textarea.
2. Put caret before it.
3. Caret will have the same height as textarea has.



Please check screenshots  - I made them for each step
Thanks.

**Comment by yairEO** [comment]
I've filed a bug to Chrome - https://bugs.chromium.org/p/chromium/issues/detail?id=1182621

You can star it :) in the meanwhile I will try something and will push soon, hopefully it would work and bypass the issue
