### ISSUE TITLE
If you will make tag somewhere in the middle of textarea and then put cursor to the end and press "DEL" then tag will be deleted.

### ISSUE THREAD

**Issue by Megas78** [yairEO/tagify#762]
## Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- **What is the expected behavior?**
- if it is nothing at the right side of cursor and you press DEL then nothing happens....

- **What is happening instead?**
- Tag disappearing which is in the middle of textarea
![Screenshot at Feb 25 15-26-33](https://user-images.githubusercontent.com/19715177/109160298-4741a080-777e-11eb-88b7-ec83ed90fd3d.png)

- **What error message are you getting?**

**Comment by yairEO** [comment]
I will take a look

**Comment by yairEO** [comment]
I don't see this happening, and I must say that I don't understand you very well. I need exact steps or a video showing the bug

**Comment by Megas78** [comment]
Good day!
Please check attached video. It reproducible in all browsers on Mac OS Big Blur
1. I added tag...
2. Then I put  caret to the end of the textarea
3. Then I start pressing DEL button on keyboard... First time - empty row was deleted... second time  - tag was deleted.

https://user-images.githubusercontent.com/19715177/109267307-05623a00-7812-11eb-80a6-420bf6e5b8e0.mov

Hope it will help. Thanks

**Comment by Megas78** [comment]
Here is another issue... reproduced in FireFox 86.0 (Mac Os Big Blur)
Please check attached Video - I just pressing Backspace button. 

https://user-images.githubusercontent.com/19715177/109267887-f16b0800-7812-11eb-97b0-6739e5d2a72c.mov

**Comment by Megas78** [comment]
... and also related thing in FireFox 86.0 (Mac Os Big Blur)
1. On last step I just pressed Backspace and was expect that "5" will be deleted. Tag was deleted instead.

https://user-images.githubusercontent.com/19715177/109268597-f8464a80-7813-11eb-8f09-87d59e3adec4.mov


Thanks for your time.

**Comment by david-benes** [comment]
I ran into this as well. I am able to reproduce this easily in the latest Chrome with the latest Tagify 4.6.0.
How to reproduce:

1. Open my demo at https://jsbin.com/weculow/6/edit?html,js,output
2. Run the code
3. Click into Tagify input
4. Set caret position to the end of the second line, just after 'new line' text.
5. Press Delete on keyboard (twice)

What should happen
I would expect nothing to happen

What happens
The first press of Delete removes the last tag in the middle of input content.
The second press of Delete removes whole input content.

https://user-images.githubusercontent.com/5094562/127840383-7edc63ec-c356-403f-8615-40c1d88a9c8d.mp4

**Comment by yairEO** [comment]
@david-benes - thanks, I see it now also. I will work on a fix
