### ISSUE TITLE
whitelist using data-whitelist dont work with JSON objects

### ISSUE THREAD

**Issue by juankql** [yairEO/tagify#766]
I am using wp_json_encode to get a JSON from an Object Array in PHP, and assigning it to the data-whitelist of an input field, but the dropdown treats it as only one tag element. Using the same JSON for the value works fine. I saw in the code that you use the JSON.parse() function to create the tags from the input initial value, but not in the case of the whitelist. So my question here is, how I can parse the JSON for the whitelist in the object creation? The picture below shows how Tagify creates the tag list from the JSON string in both the value and the whitelist. Same JSON in both cases. Any suggestion?
![image](https://user-images.githubusercontent.com/20209515/109676207-d9ff8800-7b4e-11eb-8b10-a0a734c0bda3.png)

**Comment by yairEO** [comment]
Hi, it's very difficult to understand but I think you simply use a String instead of an Array of Objects (AKA JSON). You need to make sure you provide a real array of objects to your `whitelist` setting, try using `JSON.parse()` when you assign it (you already mentioned it but didn't say if you tried it)

**Comment by juankql** [comment]
Hi @yairEO, thanks for your answer, to explain myself, I am using wp_json_encode() in the backend to populate the data-whitelist attribute. And in the JS code I am using the jquery version of your library. 
The wp_json_encode() is the WordPress wrapper for the PHP function json_encode, it returns indeed a String, I tried to use the JSON.parse() before, but it seems like the input object is undefined, and throw an error.

**Comment by juankql** [comment]
Well as you say I needed to use the JSON.parse() function, there is any chance to add that feature to the core, I mean
On line 286 of the tagify.js file you check if the value is an array and use JSON.parse
 else{
                try{
                    if( JSON.parse(value) instanceof Array )
                        value = JSON.parse(value)
                }
I think it will be good if that check is done on the whitelist as well.
