### ISSUE TITLE
Livewire instructions

### ISSUE THREAD

**Issue by accesstechnology-mike** [yairEO/tagify#767]
I've lost a few hours to this one, so wondered if it was worth mentioning in the docs. 

If integrating Tagify within Livewire you need to include the `wire:ignore` directive on the input field to prevent Livewire reverting the styling to a {value:"xxx"} string.

**Comment by yairEO** [comment]
What is *"Livewire"* ?

**Comment by accesstechnology-mike** [comment]
Laravel Livewire: https://laravel-livewire.com - its part of the TALL stack. I assumed it was popular and well known - perhaps not!

**Comment by yairEO** [comment]
I don't know what laravel is.. and how does it relate to this Tagify component :)

**Comment by yairEO** [comment]
Somebody just told me he created a livewire Tagify repo, check it out:

https://github.com/Pharaonic/livewire-tagify
