### ISSUE TITLE
Method removeAllTags ignores the passed option withoutChangeEvent

### ISSUE THREAD

**Issue by blutorange** [yairEO/tagify#769]
Just a small issue we noticed while we were updating the type declaration over at DefinitelyTyped (DefinitelyTyped/DefinitelyTyped#51560)

Method [removeAllTags](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1450) lets us pass an additional options object with `withoutChangeEvent`. The problem is that no matter whether `{withoutChangeEvent:false}` or `{withoutChangeEvent:true}` gets passed, the change event never gets triggered. This is because when that method calls `update`, [it wraps the options object in another object](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1464), so what gets passed to `update` method looks like:

```javascript
{withoutChangeEvent: { withoutChangeEvent: false }}
```

Since an `object` is always `truthy`, this always behaves as if `{withoutChangeEvent: true}` had been passed.

Fix should be easy, [line 1464](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1464) should probably be, I think:

```javascript
this.update({ ...withoutChangeEvent })
```

__Note__: Fixing this would affect the method call [on line 1119](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1119) -- depending on what's intended you might have to explicitly add `{ withoutChangeEvent: true }`.

This can also be seen on the demo page:

![image](https://user-images.githubusercontent.com/2456413/110178925-7bb0fe80-7e07-11eb-87d1-dd75e563657e.png)

---
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by Brakebein** [comment]
I'm just referencing related issues and commits:

First introduced here: https://github.com/yairEO/tagify/issues/538 https://github.com/yairEO/tagify/commit/4525cc5d77cff959c497619e9c909565bb3b0a80

Later revised: https://github.com/yairEO/tagify/issues/744 https://github.com/yairEO/tagify/commit/153d2bc19975db2b8818e0e0879a3692c9c16d05 &rarr; here it becomes an object within an object

**Comment by yairEO** [comment]
Thanks, I will fix and deploy it quickly
