### ISSUE TITLE
React - Tagify does not play well with useState Array holding values for tagify

### ISSUE THREAD

**Issue by Mehdi-HAFID** [yairEO/tagify#771]
When I use a dynamic state property to render input tagify, like
```
values = useState [{…}, {…}, {…}, {…}]

0:{key: "qdsqsd", value: "qpdkqd"}
1:{key: "", value: "efbnéo"}
```

where tagify value is values[x].value . tagify remove elements from the state hook. does not even update the state when I enter something, the ui changes but the backing state hook does not.
this an example of onChange. with the tagify is value property.

```
const updateKeyValue = (value, index, key = true) => {
		const updatedValues = [...values];
		const currentKeyValue = {...updatedValues[index]};
		if(key){
			currentKeyValue.key = value;
		} else {
			currentKeyValue.value = value;
		}
		updatedValues[index] = currentKeyValue;
		setValues(updatedValues);
	}
```
![image](https://user-images.githubusercontent.com/25527904/110485952-14839a80-80e4-11eb-9cf1-cb791720139c.png)

**Comment by yairEO** [comment]
Please if possible follow the steps in the issue template - clone the React issue template codesandbox and create a page where I can see the issue so I could help
