### ISSUE TITLE
Initialize tagify with complex data

### ISSUE THREAD

**Issue by mikeazores** [yairEO/tagify#773]
Hi! 

First of all, I would like to congratulate the developer for this excellent plugin.

I want to initialize a textarea with some values (each value with some attributes as I use them to colorize the tags). Basically, this is my textarea:

```
<textarea name="jform[relations]" id="jform_relations" class="input-xxlarge" spellcheck="false">
[{"id":"8447","email":"email1@gmail.com","value":"email1@gmail.com","userid":null,"name":null,"professional":"0","user_type":"-1","title":null}]
</textarea>
```

However, the value is not added to tagify. 

My tagify object is initialized with the following properties:
```

 var tagify = new Tagify(input, {
                    tagTextProp: "name",
                    editTags: false,
                    enforceWhitelist: true,
                    whitelist: input.value.trim().split(/\s*,\s*/),
                    transformTag: transformTag,
                    dropdown: {
                        classname: "color-blue",
                        maxItems: 0,
                        searchKeys: ["name", "value"]
                    },
                    templates: {
                        dropdownItem: function (data) {
                            $first_line = data.name ? data.name : data.value;
                            $second_line = (data.professional == "1") ? data.value : data.userid !== null ? "Normal user" : "Not registered";
                            return `<div title="${data.value}" class='${this.settings.classNames.dropdownItem} ${data.class ? data.class : ""}' tabindex="0" role="option"><div>${$first_line}</div><div>${$second_line}</div></div>`
                        }
                    }
                })
```

It seems the values are not added to tagify because they are considered invalid (I see this is my custom transformTag method):

```
email: "email1@gmail.com"
id: "8447"
name: null
professional: "0"
title: null
user_type: "-1"
userid: null
value: "email1@gmail.com"
__isValid: "not allowed"
__proto__: Object
```

Any help would be much appreciated. Thanks in advance.

**Comment by yairEO** [comment]
Hi, thanks for the praises 

I would like to know why are you using `textarea` instead of an `input` element? 
it makes no sense in this context

**Comment by mikeazores** [comment]
> Hi, thanks for the praises
> 
> I would like to know why are you using `textarea` instead of an `input` element?
> it makes no sense in this context

Thanks for prompt response. I choose to use textarea because I thought my field content (the tags) will occupy more than 1 line.

Should I avoid textarea and use instead input? In what cases should I I use textarea?

Anyway, I managed to get it working by adding to the whitelist config the initial values and adding also JSON.parse.  :)

**Comment by neutronsgit** [comment]
A tagify input field will automatically expand to multiple lines.

**Comment by yairEO** [comment]
Use `<input value="[{"id":"8447","email":...">` and it should work as expected
