### ISSUE TITLE
Single-value mode reset on dropdown:show

### ISSUE THREAD

**Issue by nikkii94** [yairEO/tagify#775]
Hello!

Is it possible to clear the selected tag before dropdown:show? What I would like to achieve is a native select-like behaviour, I allow for the users to select only one item from the whitelist, but when they try to change then the dropdown should show all items, not just the one/few that matches the currently selected value.

**Comment by yairEO** [comment]
what do you mean "but when they try to change"?

Can you write the complete steps which you envision this UX?

**Comment by nikkii94** [comment]
Sorry if I wasn't clear. So here is this example: https://codepen.io/vsync/pen/yLONYdx
After I select "first option", the dropdown content will show only "first option", unless I click on the remove button, or delete the text. 
I would like that if the dropdown would show all options without I have to click on the remove button (manually), so I though somehow I should clear the input field or selected tag before showing the dropdown.

**Comment by yairEO** [comment]
I see. I will fix that, thanks for reporting
