### ISSUE TITLE
Filter don't work on dropdown opened manually

### ISSUE THREAD

**Issue by luckashenri** [yairEO/tagify#776]
I'm trying to add a button that opens the dropdown manually.
I saw some comment about it

```
const new tagify = `Tagify(...)
tagify.dropdown.show.call(tagify,` 'somevalue') // will render the dropdown
```

But the filter don't work in that case. Can someone help me?
![image](https://user-images.githubusercontent.com/25208185/111836807-a86c1800-88d5-11eb-91ae-1b82374dc107.png)
![image](https://user-images.githubusercontent.com/25208185/111838512-30ebb800-88d8-11eb-85b7-cf2067c4ac14.png)

**Comment by yairEO** [comment]
Hi, I will help you if you can please follow my issue template and provide a demo page

**Comment by luckashenri** [comment]
- [x]   I am running the latest version
- [x]   I checked the documentation and found no answer
- [x]   I checked to make sure that this issue has not already been filed

### Demo
https://jsbin.com/topokemoxu/edit?html,js,output

### Expected behavior:
I want to click on a button, and open the dropdown (suggestions list) at the last caret position (near of the text being typed).
After it opens the dropdown, I want to type something to filter the dropdown items and click at one to create a tag.

In other words, it's like press '#' on my keyboard.


### Steps to reproduce
Open the demo link, and try to click on the button. It will open the dropdown, but u'll not be able to filter the items by typing on keyboard.
Also, if you click on some item of the list, it will not create any tag.
**BUT**
If you remove the mode: mix at the settings, it will work fine. But I'm using the mix mode so...

As a quick fix, can I just insert '#' manually and open the dropdown by doing that? just a side question.

@yairEO As u asked. Can you understand the issue now?
It happens only for mix mode

**Comment by yairEO** [comment]
I've worked on an example for you - it took me a few hours and it requires me to publish a fix in Tagify's source, which I will do shortly and then post here the code example for you to see

**Comment by yairEO** [comment]
Here's the demo my friend:

https://jsbin.com/juyeliv/edit?html,js,output

**Comment by luckashenri** [comment]
Hey. Thanks for you time @yairEO .
I'm checking it, I was trying to do something similar with your fix. In your demo https://jsbin.com/juyeliv/edit?html,js,output it's not working the filter like when we press '#' for exemple.
When we open the dropdown and try to type something to filter it, it don't filter. Can you help me with it?

**Comment by luckashenri** [comment]
@yairEO I also noticed this issue.
![image](https://user-images.githubusercontent.com/25208185/112775271-d60e3b00-9012-11eb-88d2-ba4a25a2b4b2.png)
I edit your link a little, you can try it.

**Comment by yairEO** [comment]
You cannot edit my link...this not how it works, you need to clone it and only then edit it, and then send me a URL.

I don't understand your UX demands, I thought you wanted to add tags, all this time, without any prefix (ex. `@`) via an external button.

If you want the user to add tags by typing then why do you need the button...?

**Comment by luckashenri** [comment]
@yairEO 
Hey, actually, my plan is to allow users to type the prefix and open the dropdown, and also use a external button for it.
If we could just do a fake type when user click on a button will be enough.

Regarding the link, I created a new bin so you can understand the issue I spoke about earlier.
https://jsbin.com/cinevoveci/edit?html,js,output
Just try to add a tag using the prefix.

**Comment by yairEO** [comment]
it's complicated. there are many scenarios that would need special care.

Do you want the button to add a tag with a specific prefix where the caret was last-at, within the Tagify component?

**Comment by luckashenri** [comment]
@yairEO 
Kind of, I want the button to open the dropdown where the caret was last at..
Let's say I click on the button, then will show up the prefix and open the dropdown, like when we type it.

Github has a similar behavior. I'm attaching a video to show it.
The behaviour could be the same as when we type the prefix.

https://user-images.githubusercontent.com/25208185/112845468-45b81080-907b-11eb-81de-f89d78e171c9.mp4

**Comment by yairEO** [comment]
weird, my Github UI does not have this button at all
