### ISSUE TITLE
Previous tag is deleted when quickly pressing backspace and typing new text.

### ISSUE THREAD

**Issue by Vodou** [yairEO/tagify#778]
When in mix mode, if you are typing and quickly delete and add more text, the previous tag is automatically deleted. I've included the line that's causing the issue.  Additionally, the beforeRemoveTags hook intercept is ignored. While the tag appears to remain in the tagify element, the tag value is not present when calling the getMixedTagsAsString() method. I have confirmed the issue exists in the latest version 3.23.1.

https://github.com/yairEO/tagify/blob/9b811e34da1dfe34d8f8643491b35c2b128495f8/src/parts/events.js#L262

https://user-images.githubusercontent.com/7284934/111921650-4b01d380-8a5b-11eb-8fdc-4fc6b969075f.mov

**Comment by yairEO** [comment]
Thanks, I will look into this

**Comment by Vodou** [comment]
Thanks! I appreciate it!

**Comment by yairEO** [comment]
I think it might be OK now, after a minor change. it's not an easy thing to fix completely..so many browsers bugs are involved in the deletion process, messing up what should have been short & clean code.

**Comment by Vodou** [comment]
I really appreciate you taking a look at this!

**Comment by Vodou** [comment]
Bug still exists unfortunately. I wonder if fixing the issue of the beforeRemoveTags hook being ignored where the tag value is getting removed from getMixedTagsAsString(), would let me add a custom state check to the hook. Then it could allow the user to determine if the tag should be removed or not.

**Comment by Vodou** [comment]
https://jsbin.com/potatehaco/edit?html,js,console,output

**Comment by Vodou** [comment]
https://jsbin.com/potatehaco/edit?html,js,console,output

I've also set the backspace setting to false. Another workaround might be to prevent the backspace timer logic from occurring if backspace !== true
