### ISSUE TITLE
How to add tag position to tag himself?

### ISSUE THREAD

**Issue by Aaarrrgggh** [yairEO/tagify#779]
Hello,

Thanks for your wonderful plugin! 

I would like to know if it's possible to add automatically the index position of a tag inside itself?

For example, the tagged list: _First, Second, Three_ will become _1. First, 2. Second, 3. Three_

Is there a way to do this in tag template?

Thanks!

**Comment by yairEO** [comment]
Hi, I didn't understand.. do you want to change the text within the tags at some point?

**Comment by Aaarrrgggh** [comment]
Sorry for my poor english. 

I would like to add automatically the item position when the user chooses an element.

 For example, when the user chooses the first tag (my string) among the list, the script could add automatically _1._ before my   string.

I would like to use your script to allow users to classify elements, with drag & drop.

**Comment by yairEO** [comment]
I still don't understand.. what do you mean *when the user chooses an element*? what element.. where...

Why don't you just use CSS to add a `::before{ content:... }` with a CSS counter?

here's [an example](https://codepen.io/Thomas_94/pen/QrmEmx)

**Comment by Aaarrrgggh** [comment]
The user has to choose in the whiteList the tags he wants to save in the database. 

CSS counter is a good idea. I did not think about it.

**Comment by Aaarrrgggh** [comment]
I tried it and it works perfectly!

Thanks for your answer!
