### ISSUE TITLE
Drag & sort - input associated is not updated

### ISSUE THREAD

**Issue by Aaarrrgggh** [yairEO/tagify#780]
Hi,

I try to use drag & drop function to update tags order. 
Everything is okay, except the input on which tags are associated, which is not updated.
On your demo page (Drag & drop section), the code also does not work.

Thanks,

**Comment by yairEO** [comment]
just checked and it does work as expected on the [demo page](https://codepen.io/vsync/pen/jOqYOVJ) linked from the [README](https://github.com/yairEO/tagify#drag--sort)

**Comment by Aaarrrgggh** [comment]
The input called **"drag-sort"** is not updated. When you change order tags, the value of "drag-sort" input is still _tag 1, tag 2, tag 3, tag 4, tag 5, tag 6_

**Comment by yairEO** [comment]
Here is a screenshot of my previous comment's test:

![GIF 3-27-2021 6-17-16 PM](https://user-images.githubusercontent.com/845031/112725339-c31f3c00-8f28-11eb-894a-0c472903db32.gif)

As I said, it works. 

If it does not work for you, please post an demo link for me to examine.
