### ISSUE TITLE
Tags deleted if selected a second time

### ISSUE THREAD

**Issue by viccvanco** [yairEO/tagify#781]
Hi,

I have a bug with the use of Yaireo Tagify.

I have an input field with a tag initialized in my value attribute and a select field with several options.

If I change the value of my select field, it updates my tag field (the current tag is replaced).

What I don't understand is that it only works if the value has never been added before.

For example my tag field is initialized to "Fêtes", if I add "Foires", "Fêtes" is replaced, if I add "Carnaval", idem it replaces "Foires", but if I select again "Fêtes" in my select field, nothing is displayed in my tag field... And if I select "Marchés", it appears well in my tag field, but if I change it to "Carnaval", nothing is displayed anymore, because already selected before...

Here is my script :

```
$(document).ready(function() {

    $('.js-tags').tagify();

    if ($('input.js-tags').length && $('input.js-tags').data('url') === 'event_add') {

        $('#event_category').change(function() {
            
            let newCategoryName = $(this).find(':selected').text();

            if ($('tag[title="read-only category-tag"]').length) {

                let currentCategoryTagName = $('tag[title="read-only category-tag"]').find('.tagify__tag-text').text();

                $('input.js-tags').data('tagify').removeTags(currentCategoryTagName);
            }

            $('input.js-tags').data('tagify').addTags([
                {
                    value: newCategoryName,
                    readonly: true,
                    title: 'read-only category-tag'
                }
            ]);
        });
    }
});
```
Thanks for your help.

**Comment by viccvanco** [comment]
By examining the inspector of my browser I realize that the value attribute of my tag field is not updated when the tag is deleted. So when the tag is replaced, the tag is visually replaced, but the value of the linked field is not updated (neither the old tag is deleted, nor the new tag is added). How to solve this ? Thank you.

**Comment by yairEO** [comment]
I am about to release a fix for this any minute new
