### ISSUE TITLE
how to destroy tagify from Tagified element and recreate it

### ISSUE THREAD

**Issue by ermya** [yairEO/tagify#782]
Hi 
i have a table with some rows which have edit button , and i have a modal for editing table rows 
so on button on-click event i will call a javascript function that will prepare and load table row to the modal element include tagify 
i mean with every call i have to add table rows value to modal elements ,and create new tagify for the modal element to show default tagify value on it ! 
its working on first call only and then face me "warning input element is already Tagified"
is there any hint how to destroy tagify element ? i try with remove() to remove complete element and create with append before showing modal but didnt help, 
sorry im not so professional on JavaScript and i did what i knows

**Comment by yairEO** [comment]
Tagify has a `destroy` method, but I don't understand why do you want to destroy it and not simply replace all the tags in it?

Just check if it's already "tagified". There are so many ways you can do that, for example, check if the `tagify.DOM.originalInput` is the same as the input no the page.

Then you can call `tagify.loadOriginalValues( newValue )` to replace all current tags with other ones.

`newValue` may be a string or an array of strings or objects
