### ISSUE TITLE
How to format output value to support `field[]`?

### ISSUE THREAD

**Issue by engin-can** [yairEO/tagify#784]
Hi,

I was wondering if there is a way to format output values as following, since I am using ajax form `serialize()` function which results into `application/x-www-form-urlencoded` content-type:

```animals[]=dog&animals[]=cat&animals[]=bird```

Not sure if there is a way to achieve this with `originalInputValueFormat`...

**Comment by yairEO** [comment]
You can simply transform the data yourself when you send it (via AJAX). You have the Array of tags, so simply convert the array to a string that looks like the one you want:

```js
// assume these are your tags (can get the array from tagify.value)
["cat", "dog", "fish"].join('[]=') // "cat[]=dog[]=fish"
```

**Comment by engin-can** [comment]
This is not the format I am looking for. I am looking for a way to have `animals[]=dog&animals[]=cat&animals=fish`. Would it be possible to achieve this so I can use JQuery `serialize()`?

**Comment by yairEO** [comment]
Why can't you format it the way you want? it's basic javascript, unrelated to Tagify?

Basic javascript:

```js
var groupName = "animals";
["cat", "dog", "fish"].reduce((acc, item) => 
  acc += `${groupName}[]=${item}&` 
, "").slice(0, -1)
```
