### ISSUE TITLE
Can't make tagTextProp work when mode select is set

### ISSUE THREAD

**Issue by mikeazores** [yairEO/tagify#786]
Hi! 

I have configured a tagify input with mode set to "select". I'm trying to use tagTextProp to display a different text when user selects an item from dropdown list but it stills shows the value instead of the username (in the example below) of the item selected. 

I've configured [an example in codepen with tagify 4.0 version](https://codepen.io/mikeazores/pen/vYgyeGZ). 

Probably I'm missing something but can't figure out. Any help would be much appreciated Thanks in advance.

**Comment by yairEO** [comment]
I'll help you tomorrow

**Comment by yairEO** [comment]
I am working on it. It appears to be an issue with a part with old code that I now think should be completely replaced. I will probably publish tomorrow a version containing the fix.

**Comment by mikeazores** [comment]
> I am working on it. It appears to be an issue with a part with old code that I now think should be completely replaced. I will probably publish tomorrow a version containing the fix.

Thanks a lot for your efforts @yairEO

**Comment by yairEO** [comment]
Took some time to understand the issue (few hours) and I committed the fix and release a new version probably tomorrow
