### ISSUE TITLE
Way to render tags one by one?

### ISSUE THREAD

**Issue by ldelosreyes** [yairEO/tagify#787]
I have a use case where in I need to copy values from spreadsheet and paste it to a tagify field,
Since the values are more than 300, it looks like the app is freezing before it renders the tags.
Is there a way to render them one by one instead of rendering them at once after certain seconds?
Or maybe an event that I can listen once the adding of tags started and completed?
Kindly see attached GIF.
Thank you.

![screencast-yaireo github io-2021 03 31-11_57_31](https://user-images.githubusercontent.com/16955900/113088920-31117f00-9219-11eb-96b1-9ae91913c33d.gif)

**Comment by yairEO** [comment]
I will investigate this slowness, maybe I can simply improve the performance somehow.

Are you currently using the `change` event?
