### ISSUE TITLE
TypeScript error finding types declaration after installing

### ISSUE THREAD

**Issue by ryanflores79** [yairEO/tagify#788]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- **What is the expected behavior?**
To be able to import `Tag` from `react.tagify`
- **What is happening instead?**
- I did `npm install @types/yaireo__tagify`
TypeScript error:
```
Could not find a declaration file for module '@yaireo/tagify/dist/react.tagify'. '/apps/project/node_modules/@yaireo/tagify/dist/react.tagify.js' implicitly has an 'any' type.
  Try `npm install @types/yaireo__tagify` if it exists or add a new declaration (.d.ts) file containing `declare module '@yaireo/tagify/dist/react.tagify';`  TS7016
```
It keeps telling me to install the types but I already have using:
`npm install @types/yaireo__tagify`
![Screen Shot 2021-03-31 at 11 51 37 AM](https://user-images.githubusercontent.com/1671775/113195722-746aee00-9217-11eb-9981-75b2461ce6ee.png)
![Screen Shot 2021-03-31 at 11 46 48 AM](https://user-images.githubusercontent.com/1671775/113195746-7b91fc00-9217-11eb-9a46-7c0089497dc5.png)

- **What error message are you getting?**

**Comment by yairEO** [comment]
See - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50895
and - https://github.com/yairEO/tagify/pull/531#ref-issue-654727983

**Comment by Brakebein** [comment]
The type definitions only cover the core Tagify library (and we keep tracking changes). But we didn't add any for the React wrapper. I'm personally not familiar with React. @blutorange also heavily contributed to the type definitions, maybe he has an opinion on this case.

**Comment by blutorange** [comment]
I'm not an expert in react, but I'm currently working on a TypeScript project in react, so I'm a but familiar with it. I can take a look at the react wrapper when I've got time. Alternativel, @ryanflores79 if you want to submit a PR to DefinitelyTyped, feel free to do so.

**Comment by yairEO** [comment]
I am so happy to have such wonderful community, after years of doing all the work on Tagify alone, it's so nice to see others helping out :)

**Comment by ryanflores79** [comment]
I was able to work around this issue by adding a
```
//@ts-ignore
```
just above the import.

Great library, cheers!

**Comment by yairEO** [comment]
@ryanflores79 - and were you able to use the typescript declarations from *DefinitelyTyped*?

**Comment by blutorange** [comment]
I'm assuming not - as there are none for the react wrapper yet (@ts-ignore just disables type checking) -- I'm writing the type declarations for the React wrapper right now, should be up in the next few days : )

**Comment by blutorange** [comment]
@ryanflores79 jfyi, the PR over at DefinitelyTyped finally got approved, you can now update the typings package and get the types for the React wrapper. If you find any issues, please open an issue at DefinitelyTyped.
