### ISSUE TITLE
es6 import not working

### ISSUE THREAD

**Issue by mrfrancescomoro** [yairEO/tagify#79]
Hello there,
I'm having trouble importing the library in my js file.
I've installed tagify via npm and I'm trying to import it into my js component.

**import Tagify from '@yaireo/tagify/src/tagify.js';**
this is the only solution to let compile webpack correctly but I have errors in console: **Uncaught TypeError: (0 , _Tags2.default) is not a function**

I've tried these also but webpack do not complie
import Tagify from '@yaireo/tagify';   import { Tagify } from '@yaireo/tagify';

Am I doing something wrong?

Thanks
Cheers

**Comment by yairEO** [comment]
Hi, you cannot simply `import` any 3rd party script, or matter of fact, any code/function that weren't first exported using the [`export` statement](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export).

Here's what Google came up with when I ran a query on your question:

https://stackoverflow.com/q/42034327/104380

**Comment by piwel** [comment]
Maybe try `import {default as Tagify} from '@yaireo/tagify/dist/tagify.esm';`
