### ISSUE TITLE
React wrapper: MixedTags export is missing

### ISSUE THREAD

**Issue by blutorange** [yairEO/tagify#790]
* Tried with latest version 4.0.1, also with version 3.21.3

Not completely sure if I've got something wrong here, but the `MixedTags` export that is mentioned in the README.md  seems to be missing (aka not exported correctly) in the bundled file (https://github.com/yairEO/tagify/blob/master/dist/react.tagify.js). In the source file, `Tags` is supposed to be the default export, `MixedTags` is a named export.

Basically, try installing the module with NPM and require the library:

```bash
npm i @yaireo/tagify
node
  tagify = require("@yaireo/tagify/dist/react.tagify");
```

This only returns the `Tags` compnent, and no `MixedTags` anywhere to be found. Same thing happens when you use ES6 modules and built with webpack:

```javascript
import Tags from "@yaireo/tagify/dist/react.tagify"
import { MixedTags } from "@yaireo/tagify/dist/react.tagify"
// MixedTags is undefined
```

The `tagify-react-issue-template` (https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js) does not actually import `MixedTags`, both `Tags` and `MixedTags` import the same default `Tags` export:

![image](https://user-images.githubusercontent.com/2456413/113455703-9dec6b00-940b-11eb-9046-4d59715d9c03.png)

On the demo page (https://codesandbox.io/s/tagify-react-wrapper-oempc) it's working, but only because it's using the source `tagify.react.js` file, not the built file from the `dist` directory.

![image](https://user-images.githubusercontent.com/2456413/113455821-e2780680-940b-11eb-832a-244b76287d02.png)

---

Taking a look at the built file (https://github.com/yairEO/tagify/blob/master/dist/react.tagify.js), the problem seems to be that even though that file sets `exports={default, MixedTags}`, it also sets  `module.exports` to the `Tags` components.

Taking a further look at the `gulpfile.js`, the problem seems to be here: https://github.com/yairEO/tagify/blob/master/gulpfile.js#L68

I don't know much about gulp, but when I clone the repo locally and change that to

```
    const umdConf = {
        exports: function(file) {
            return 'exports';
        }
    }
```

it creates the bundle correctly. `require("@yaireo/tagify/dist/react.tagify")` then returns an object `{default: ..., MixedTags: ...}` which contains the default export and the `MixedTags` component.

**Comment by yairEO** [comment]
Thanks I will fix that!
I remember this issue from months ago but I completely forgot about it since. I will solve this asap, 
thanks again for bringing this up.

**Comment by blutorange** [comment]
Thank you, you're welcome, I like detective work : ) When writing TypeScript declarations, I want to make sure they're correct, so I compare the documentation with the source code, and also try it out fo real. It's a pretty fun thing to do. There are few more minor things I noticed with the React wrapper while doing so, I could open an issue, but perhaps you could take a quick look beforehand, perhaps some of these are intended? I made a quick note here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52157 (after the first horizontal line)

BTW regarding gulp, thanks for the hint. I guess webpack was enough for what I've done so far, but looking at the gulpfile, it really doesn't seem that hard. Perhaps I'll give it a try in my next project.
