### ISSUE TITLE
React wrapper: PropType for children does not agree with usage

### ISSUE THREAD

**Issue by blutorange** [yairEO/tagify#791]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://stackblitz.com/edit/react-hyi4yz

![image](https://user-images.githubusercontent.com/2456413/113461050-4fdf6380-941b-11eb-9ed9-cb013261e32e.png)

### Explanation

The prop types in the react wraper (https://github.com/yairEO/tagify/blob/master/src/react.tagify.js#L184) require `children` to be of type `element`. When we actually do that, only one tag with the value `[object: Object]` is displayed (see code / screenshot above)

When we use plain text ( a string ) for the children, it renders properly, but now an error is logged by prop-types, as we are using the wrong type for `children`.

```javascript
// works, but wrong according to prop-types
<Tags>a,b,c</Tags>
// works, but wrong according to prop-types
<Tags>{["a", "b", "c"]}</Tags>
// does not work, but correct according to prop-types
<Tags><span>a,b,c</span></Tags>
```

Perhaps this here https://github.com/yairEO/tagify/blob/master/src/react.tagify.js#L184 should be changed to

```javascript
    children: oneOfType([string, array]),
```

 ?

**Comment by yairEO** [comment]
The syntax is `<Tags value="foo,bar" />` with the `value` prop, why are you not using it like that?

**Comment by blutorange** [comment]
Yes, I've seen it in the docs that `value=...` is the preferred way of doing it, and that works perfectly : )

It's just that we're adding the TypeScript declarations for the React wrapper here (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52157) and if possible, I'd like to document all officially available options. `children` is mentioned in the  `README.md`, which I would consider official. When I tried using the children property, I noticed that it only works when the children are a simple string (or string array), but then React issues an error because the prop-types are set to `element`.

So I was wondering if the declared prop types should be changed.

Although, if you say `children` is deprecated, we can just omit that property from the TypeScript declarations and you can remove it in the next major version or so.

**Comment by yairEO** [comment]
`children` being mentioned in the README is a legacy forgotten thing, I will remove it now. 

In the past I wanted the value to be written as children but that's not possible with JSX in a nice way, so I chose the `value` prop instead as the only way of passing a value to the component
