### ISSUE TITLE
React wrapper: onEdit is never called 

### ISSUE THREAD

**Issue by blutorange** [yairEO/tagify#792]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://stackblitz.com/edit/react-poazae

![image](https://user-images.githubusercontent.com/2456413/113474685-b000f480-9471-11eb-91e2-8eee8372f490.png)

### Explanation

The `onEdit` property on the React component is mentioned here in the README (https://github.com/yairEO/tagify#updating-the-components-state) and can be found here in the source code (https://github.com/yairEO/tagify/blob/master/src/react.tagify.js#L31) However, the callback is never called. The `edit:updated` callbacks etc. that can be defined via `settings.callbacks` are called, see demo and screenshot above.

----

As far as I can tell, there are only specific events such as `edit:updated`, `edit:start` etc., but no plain `edit` event. The React wrapper only listens to the `edit` event (https://github.com/yairEO/tagify/blob/master/src/react.tagify.js#L92) but since that is never fired, the callback is never called.

I took a look at the commit history (`onEdit` was added here https://github.com/yairEO/tagify/commit/bcdb1dc259a34e7219d15516ad9de407bf126419) and it does not seem like there was a plain edit event in that version of this library?

Perhaps you could assign `onEdit` to one of the more specific events, such as `edit:updated` since that is when the actual edit takes place? Or possibly add multiple properties for the different edit events, though I'm not sure if that would be too much.

**Comment by blutorange** [comment]
On a side note, only the `onChange` property has a corresponding `TagifyWrapper.propTypes` here (https://github.com/yairEO/tagify/blob/master/src/react.tagify.js#L185). Perhaps you could add a prop type for the other callbacks  `onInput` `onAdd` `onRemove` `onInvalid` `onClick` `onKeydown` `onFocus` `onBlur` too?

**Comment by yairEO** [comment]
Nice catch!

Some months ago I've re-wrote all the events related to editing, splitting it to:

1. `edit:input`
2. `edit:beforeUpdate`
3. `edit:updated`
4. `edit:start`
5. `edit:keydown`

And forgot to address the change in the React wrapper. I will do it now.

**Comment by blutorange** [comment]
@yairEO Thanks for fixing it so quickly : ) One nitpick, could you take another look at the `onDropdownShow` callback? I think you may have accidentally forgotten to add it here:

https://github.com/yairEO/tagify/blob/0e88c371156ab89382fd02f09eafa5c731e7245a/src/react.tagify.js#L114-L121

And I'm not sure whether it is intentional, but should the `dropdown:updated` be included as well?

**Comment by yairEO** [comment]
Thanks for catching all this. I have no body to do me code-reviews unfortunately.

I forgot to add `dropdown:updated` to the README so when I glanced at it to add the events to the React wrapper I forgot that `dropdown:updated` was missing entirely from the docs. I will fix it all now.

**Comment by blutorange** [comment]
@yairEO  You're welcome. That's the great thing about open source after all -- somebody will catch it and it gets fixed
