### ISSUE TITLE
Duplicates: true, Bug in remove duplicate tags

### ISSUE THREAD

**Issue by LlurensMartinezUtopig** [yairEO/tagify#794]
## Prerequisites

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/tihuduf/1/edit?html,js,output

### Explanation

When I have duplicates: true and I write for example the following tags: **foo bar fan bar** and delete the last tag **bar**, if I do a console.log (tagify.value), it gives me the following result **foo fan bar.**
This leads me to the following conclusion, if you delete a duplicate tag, it will always delete **the first tag found** in the array with that value.

**Comment by yairEO** [comment]
Very interesting, I will look into this!

**Comment by LlurensMartinezUtopig** [comment]
Thanks a lot @yairEO ,
We are using your wonderful plugin (the most complete and very well worked we have found) for a large project. This bug hurts us a lot since we have to have duplicate tags and we are in a bit of a hurry because we have the delivery immediately. We would be delighted to be able to collaborate economically in some way to help solve this bug.
Thanks a lot.

**Comment by yairEO** [comment]
I only read this now, I will look into this right now, although I have a lot of actual work to do, I want to help you

**Comment by yairEO** [comment]
I hope this fixed it. Upgrade to version `4.0.4`.

Feel **free** to contribute me :)
`Paypal` - `vsync.design@gmail.com`

**Comment by LlurensMartinezUtopig** [comment]
Thank you very much @yairEO , now everything works perfectly. Nice job. We are UtopigStudio (from spain) and soon we will send you our contribution by paypal. 👍
