### ISSUE TITLE
InputEventData has wrong constructor?

### ISSUE THREAD

**Issue by chaserstrong** [yairEO/tagify#795]
The param of input event looks like:
![image](https://user-images.githubusercontent.com/18061322/114122300-943e9800-9922-11eb-895a-0b86657433eb.png)

But in @types/yaireo__tagify InputEventData looks like：
![image](https://user-images.githubusercontent.com/18061322/114122410-c819bd80-9922-11eb-9d65-406a159e73f1.png)

There is no detail props.

**Comment by chaserstrong** [comment]
@yairEO please

**Comment by yairEO** [comment]
I am not in charge of the typescript interface, it is maintained by the community 

You can [write here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52157) about this and hopefully someone will fix it

**Comment by blutorange** [comment]
@chaserstrong The `InputEventData` interface is the content of the `details` property. The `callbacks` object wraps these in a `CustomEvent` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yaireo__tagify/index.d.ts#L571

If you want to use the `InputEventData` in your project, use

```typescript
CustomEvent<InputEventData>
```

If you find any issue with the typing, please open a new issue on https://github.com/DefinitelyTyped/DefinitelyTyped/issues and mention me.
