### ISSUE TITLE
In mix mode, how to get value on input event?

### ISSUE THREAD

**Issue by chaserstrong** [yairEO/tagify#796]
Is there a way to get the value on input event like we set there:
![image](https://user-images.githubusercontent.com/18061322/114131421-2bace680-9935-11eb-93fd-8f141016c0ad.png)

Now we always get the value like this, only text: 
This is a textarea which mixes text with tags.

**Comment by yairEO** [comment]
```js
const onChange = useCallback(e => {
    console.log("CHANGED:", e.detail.value)
}, [])
```

As shown in the [React demo](https://codesandbox.io/s/tagify-react-wrapper-oempc) mentioned in the in the docs (README)

Just tested and it works as it should

**Comment by yairEO** [comment]
@qijunxin [qijunxin](https://github.com/qijunxin)

Seems to work as-expected (Chrome `102`):

https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/MixedModeTagify.jsx

https://user-images.githubusercontent.com/845031/174286450-132b318c-7252-4c7e-8d6e-1015b9cae32b.mp4
