### ISSUE TITLE
Does mix mode can't have same key?

### ISSUE THREAD

**Issue by chaserstrong** [yairEO/tagify#797]
As you can see , i want have same tag in the input. But it seems can't support.
https://codepen.io/vsync/pen/KKzpdxQ

![image](https://user-images.githubusercontent.com/18061322/114274328-77a07e00-9a50-11eb-910a-49b09897b7cf.png)

**Comment by yairEO** [comment]
You've put here my own url (from my Codepen). You need to fork the example, edit it, and send the **new** unique url.

If you want to allow items with duplicate `values`, then set the `duplicates` setting to `true` (as stated in the [README](https://github.com/yairEO/tagify#settings))
