### ISSUE TITLE
Parse mixed tags e.detail.value back into String argument

### ISSUE THREAD

**Issue by KevinLu** [yairEO/tagify#799]
Hi, is it possible to parse e.detail.value back into the String argument?

For example:
Using React `MixedTags` wrapper, `mixTagsInterpolator: ['<{', '}>']` in tagify settings.
e.detail.value = `Hi <{{"value":"username","__tagId":"223a0139-899b-4952-a6a5-ba3eae5237c2"}}> how are you? `
I want to parse `e.detail.value` to `Hi <{username}>`, is there a method to do this?

Thank you!

**Comment by yairEO** [comment]
Sorry but I don't understand what is the problem...

**Comment by KevinLu** [comment]
Hi, I just wanted to know how to remove the "value" and "__tagId" from the value in tagify.
For example:
Input: `Hi <{{"value":"username","__tagId":"223a0139-899b-4952-a6a5-ba3eae5237c2"}}> how are you? `
Output: `Hi <{username}> how are you?`

Is there a built in method form tagify to do this?

**Comment by yairEO** [comment]
update your tagify version, it should not have the `__tagId` property on each object any more

Why can't you remove the `value` string? Do you know javascript?

**Comment by KevinLu** [comment]
Thanks, just updated to v4.0.5 and __tagId is gone.
I've removed the value string with a very hacky method by first splitting by a regex and then mapping over the array from the split.
I'm just wondering if there is a built in method from tagify for doing this, so the code is cleaner?

**Comment by yairEO** [comment]
This is up to the developer responsibility to manipulate the output as see fit

How would Tagify convert back your manipulated string to tags if you change it to this format?

**Comment by KevinLu** [comment]
The output would be `Hi <{username}> how are you?`, which Tagify will then recognize "username" as a tag. You can close this issue now, since I've resolved the problem.

**Comment by yairEO** [comment]
As mentioned in the [docs](https://github.com/yairEO/tagify#mixed-content) you can set custom interpolation setting:

```js
mixTagsInterpolator: ["<{", "}>"]
```
