### ISSUE TITLE
Need to paste twice for long string to work

### ISSUE THREAD

**Issue by pesseyjulien** [yairEO/tagify#80]
Hi,

Sorry to bother you but I have a weird issue on my side. I need to paste twice a long string (ie, EAAK5RJdENGcBAMnHjKbyZCxLsXRN4XfZBbd2pZCSmAIvnZAfUOk7fCPjpxhZBLZCv5ORbw8C0vEesLQZCithVcOIb1vImOjVexahTnaR5htZCxdRJA61LM5yATxTXLeGvyoGr1AuThPZA4lfysvZAdEnqCVJPWJrkz1YVrvDWASJffBQZDZD) in the tag component. On first paste, it does not appear and then it does.

I know it's coming from my implementation, but any idea where it could be coming from ?

Thanks in advance for your help,
Julien

**Comment by yairEO** [comment]
i just pasted that string above to the first example in the demo page (on Chrome) and everything works.. does it work for you also in the demo page, on the first (top most) example?

**Comment by pesseyjulien** [comment]
Yes it does, sorry I forgot to mention it only happens in my environnement :)

I know the issue is on my side, but can’t find where..

**Comment by yairEO** [comment]
I would need a link so i could try and investigate

**Comment by pesseyjulien** [comment]
It's a private back-office, can I send you an access by email ?

**Comment by yairEO** [comment]
yes of course, send it

**Comment by pesseyjulien** [comment]
I did some update, and it's actually working now.

Just when I edit an existing field, if I copy past the existing value, the duplicate control does not work.

**Comment by yairEO** [comment]
what are the steps to reproduce this bug on the demo page?

**Comment by pesseyjulien** [comment]
Well, it does not detect the duplicate because it doubles the string :

```
JQEURY EVENT:  added 
{index: 2, tag: {…}, value: "EAAK5RJdENGcBAMnHjKbyZCxLsXRN4XfZBbd2pZCSmAIvnZAfU…Gr1AuThPZA4lfysvZAdEnqCVJPWJrkz1YVrvDWASJffBQZDZD"}
index
:
2
tag
:
{}
value
:
"EAAK5RJdENGcBAMnHjKbyZCxLsXRN4XfZBbd2pZCSmAIvnZAfUOk7fCPjpxhZBLZCv5ORbw8C0vEesLQZCithVcOIb1vImOjVexahTnaR5htZCxdRJA61LM5yATxTXLeGvyoGr1AuThPZA4lfysvZAdEnqCVJPWJrkz1YVrvDWASJffBQZDZDEAAK5RJdENGcBAMnHjKbyZCxLsXRN4XfZBbd2pZCSmAIvnZAfUOk7fCPjpxhZBLZCv5ORbw8C0vEesLQZCithVcOIb1vImOjVexahTnaR5htZCxdRJA61LM5yATxTXLeGvyoGr1AuThPZA4lfysvZAdEnqCVJPWJrkz1YVrvDWASJffBQZDZD"
__proto__
:
Object
```

You can see, the tag value is the string twice, back to back !

**Comment by pesseyjulien** [comment]
Yes, I was using 2.0.4.

I had to rollback on 2.0.1, the update was not working for me.

Other weird thing, on firefox, when I first load a page, it displays well :

![capture d ecran 2018-07-17 a 11 27 55](https://user-images.githubusercontent.com/10850944/42808873-8084f32a-89b4-11e8-98a2-12b160354c77.jpg)

If I reload the page, it adds ' " ' :

![capture d ecran 2018-07-17 a 11 28 02](https://user-images.githubusercontent.com/10850944/42808889-8a2dfef8-89b4-11e8-9765-187e06183c36.jpg)

Any idea ?

My Jquery version is 2.2.4, and I also have boostrap 3.3.6.

**Comment by yairEO** [comment]
yes, I think I know what's happening with the `"` thing. I will see what can be done about it

**Comment by pesseyjulien** [comment]
Ok thanks.

Any idea why on the last version the string is double on copy-paste ?

**Comment by yairEO** [comment]
no, I don't know why it's double.. I am unable to reproduce such a bug on Chrome nor Firefox.

when I paste a string , long or short, it all works fine. I've just replied to your personal email btw.
