### ISSUE TITLE
Loading animation not displaying in mixed mode

### ISSUE THREAD

**Issue by jebax** [yairEO/tagify#801]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://codesandbox.io/s/tagify-react-wrapper-forked-77hw1?file=/src/MixedModeTagify.js

### Explanation

- **What is the expected behavior?**
When `loading` is set to `true`, the loading animation should display at the end of the input

- **What is happening instead?**
The loading animation is not being displayed. 
I can see that in the CSS, you hide the `::after` content in mixed mode: https://github.com/yairEO/tagify/blob/430bf22661f4b6f25a27420aca5434c161cb11a3/src/tagify.scss#L555
You added a comment here saying that this is to hide autocomplete results in mixed mode. But it also hides the loading animation, which I'm guessing is unintended?

Thanks for the help!

**Comment by yairEO** [comment]
There is no *"loading"* state in *mix-mode*, I never thought there was a need. 

Why do you need it?

**Comment by yairEO** [comment]
Fixed

**Comment by jebax** [comment]
> There is no _"loading"_ state in _mix-mode_, I never thought there was a need. is shown.
> 
> Why do you need it?

we're tagging objects from our API in a free text field. so we need to load the objects from our API and ideally show a loading animation in the process.

thanks very much for the quick fix!
