### ISSUE TITLE
Drag & Sort example with React

### ISSUE THREAD

**Issue by majdjaiasoft** [yairEO/tagify#802]
I saw the example you've provided for drag & sort support but I can't implement it with React, could you provide a working example using ReactJS?

Thanks for the help!

**Comment by yairEO** [comment]
I will improve the React demo to show how to use drag/sort

**Comment by yairEO** [comment]
Here you go, a working example for dragging and dropping tags (in the React demo):

https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/CrazyTags.js:2411-2636
