### ISSUE TITLE
Tab navigation for the remove buttons

### ISSUE THREAD

**Issue by lucivpav** [yairEO/tagify#803]
Currently, one cannot use tab tavigation to select the individual tags' remove (`×`) button. Therefore, tagify is less usable for users who only use keyboard as an input device. It would be nice to have an option to enable the remove buttons to be focusable.

**Comment by yairEO** [comment]
Good point. I will take that into consideration.

**Comment by yairEO** [comment]
You can now use this new setting:

```js
a11y: {
    focusableTags: true
}
```

And when a *tag* is in focus, it can be deleted by pressing <kbd>backspace</kdb>

**Comment by lucivpav** [comment]
Thank you!!
