### ISSUE TITLE
Paste does not prevent default

### ISSUE THREAD

**Issue by amitrahav** [yairEO/tagify#804]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

***React*** example: https://codesandbox.io/s/tagify-react-issue-template-forked-19o66?file=/src/index.js

### Explanation

- **What is the expected behavior?**
Paste does not prevent default when binding event listener to tagifyRef (react class component).
 In the example above I used [this paste event example](https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event#examples), which expected to covert text to upperCase and keep the selection range marked. It happens, but the default paste behavior remains - and the text with the right behavior is being pasted again.

- **What is happening instead?**
Paste is firing `insertHTML` html exec and not preventing defaults.

- **What error message are you getting?**
None. but my paste binding event is not executing as accepted.

**Comment by yairEO** [comment]
What are you trying to do?

Tagify handles the `paste` event by itself. you should not do:

    selection.getRangeAt(0).insertNode(document.createTextNode(paste));

**Comment by amitrahav** [comment]
Im trying to manipulate text before Tagify handles it.
For example: I want `@tag` to convert into `[[ tag ]]` so Tagify could understand it as tag.

I actually figured it out - `onPaste` function should have a `e.stopImmediatePropagation();` before the `e.preventDefault();` and when I bind the event listener it should set the `useCapture` parameter as `true` as (described here)[https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters] - so it looks like this `this.tagify.current.DOM.input.addEventListener('paste', this.onPaste, true)`

Is there a smarter way to do what Im trying?

**Comment by yairEO** [comment]
You want everything pasted to become a tag? 
Your users won't be able to paste regular text, no?

**Comment by amitrahav** [comment]
I'm using mix mode, so I want the user to paste whatever they wants, but when they paste some word in `@tag` format it will convert to `[[ tag ]]` so Tagify can process it.

*Paste example:*
Input: `Hi @Introduction, let's get to work` -> Output: `Hi [[ Introduction ]], let's get to work`

---

BTW, it goes the same way on the copy direction - when I copy text from Tagify mix mode - I want it to do the same (at the moment the text looks the same as it looks in the textarea. I want tags to be copied like that: `[[ tag ]]`)
*Copy example:* 
1. Input (Tags as display in Tafigy): `Hi [[ Introduction ]], let's get to work` -> Output(Tagify default copy behavior): `Hi Introduction, let's get to work` -> Wanted  Output: `Hi [[ Introduction ]], let's get to work`

**Comment by yairEO** [comment]
I think you should handle the `copy` scenario yourself and it is unrelated to Tagify
