### ISSUE TITLE
Extra newlines added in `onChange` value in Chrome/Safari mixed mode

### ISSUE THREAD

**Issue by jebax** [yairEO/tagify#805]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://codesandbox.io/s/tagify-react-wrapper-forked-bqmqn?file=/src/MixedModeTagify.js

### Explanation

- **What is the expected behavior?**
When I enter 2 newlines between `"test"` and `"test"`, the `onChange` event should fire with 2 newline characters: `"test\n\ntest"`

- **What is happening instead?**
`onChange` fires with 3 newlines: `"test\n\n\ntest"`

Here's a video:

https://user-images.githubusercontent.com/35078047/115301645-6692f380-a159-11eb-8073-23878afbe6e9.mov

So when this value is loaded back into `MixedTags`:
<img width="537" alt="Screenshot 2021-04-19 at 21 42 27" src="https://user-images.githubusercontent.com/35078047/115301301-e8365180-a158-11eb-9ceb-9b128e955ffa.png">

This bug is quite frustrating, because the way the saved text is displayed is important, and extra newlines are confusing for a user who won't see them until after changes are saved.

I think this bug is because Chrome and Safari add `<div />`s for newlines inside `contenteditable`, which is quite annoying compared to Firefox which adds `<br />`s. Then the way that Tagify accesses the text value of the element results in different values across different browsers.

Is there something in the `getMixedTagsAsString()` method that is adding extra newlines for `<div />`s maybe?

Thanks for the help!

**Comment by yairEO** [comment]
It is indeed extremely frustrating.. I've worked so hard "fighting" so many browsers bugs and inconsistencies that you wouldn't believe.. 

This is the function which converts "mix tags" into a string value:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1526-L1561

I guess there is some bug, not sure if it's new or always has been, but I will allocate time to inspect. It's very fragile piece of code which tries to get this done "right" on all browsers.

**Comment by jebax** [comment]
yeah i saw that function, it does look tricky.

thanks for the quick response!

**Comment by raikow** [comment]
Seem correct for me (you make 3x enter/new line) in your video

test\n
\n
\n
test

**Comment by jebax** [comment]
hi @yairEO any progress on this bug?

**Comment by yairEO** [comment]
@jebax - I forgot about it, and will examine again now, thanks for reminding me someone cares about this

**Comment by jebax** [comment]
> @jebax - I forgot about it, and will examine again now, thanks for reminding me someone cares about this

Hi @yairEO ,

Thanks for your work on this bug. However the problem still seems to be there.

See the example here, I've upgraded to 4.7.2 but the bug still appears:
https://codesandbox.io/s/tagify-react-wrapper-forked-2ytok?file=/package.json


https://user-images.githubusercontent.com/35078047/130457702-8b83fb2a-7792-4233-bfb7-6f403f111a63.mov

**Comment by yairEO** [comment]
@jebax - your demo is not correct as it uses local (old) copy of Tagify instead of the one from the `package.json`:

    import { MixedTags } from "@yaireo/tagify/dist/react.tagify"
    
Just tested in your demo and it works well

**Comment by jebax** [comment]
> @jebax - your demo is not correct as it uses local (old) copy of Tagify instead of the one from the `package.json`:
> 
> ```
> import { MixedTags } from "@yaireo/tagify/dist/react.tagify"
> ```
> 
> Just tested in your demo and it works well

ah woops! thanks :)
