### ISSUE TITLE
Ability to leave select "clean" and put tags above select.

### ISSUE THREAD

**Issue by bytheway875** [yairEO/tagify#806]
Is there any built in support for being able to create something like this by modifying CSS using the default tagify implementation? When a new item is selected, it places the tag above or below the select and leaves the select itself empty. I'm assuming I can modify some CSS to do this, but I wanted to see if you've designed an implementation for this or have any recommendations. 

![Screen Shot 2021-04-20 at 1 18 26 PM](https://user-images.githubusercontent.com/4494389/115444885-c41b5480-a1da-11eb-8143-81f8f86014e3.png)

**Comment by yairEO** [comment]
Should users be able to type text inside the Tagify component?

**Comment by bytheway875** [comment]
Oh, perfect! That's exactly what I was looking for. I must have scrolled right past it. Thanks!
