### ISSUE TITLE
Empty string value can't be set when using react

### ISSUE THREAD

**Issue by chaserstrong** [yairEO/tagify#807]
***React*** issue template:
https://codesandbox.io/s/tagify-react-wrapper-forked-pl2w2?file=/src/MixedModeTagify.js

### Explanation
When i set other value, it will be ok.
And i'm afraid if this is wrong with these code:

```
loadOriginalValues( value ){
        var lastChild,
            _s = this.settings;

        value = value || (_s.mixMode.integrated
            ? this.DOM.input.textContent
            : this.DOM.originalInput.value)
```

**Comment by yairEO** [comment]
Thanks for reporting and making a demo, I will look into this
