### ISSUE TITLE
Caret becomes hidden under tag

### ISSUE THREAD

**Issue by KevinLu** [yairEO/tagify#808]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://codepen.io/vsync/pen/KKzpdxQ

### Explanation
Browser version: Edge Version 90.0.818.42 and Chrome Version 90.0.4430.85

- **What is the expected behavior?**
Caret cursor should not become hidden under tag when navigating with arrow keys, placing with mouse click or deleting.
- **What is happening instead?**
Caret cursor is becoming hidden under the tag, which can be seen in this video:
![tagify_cursor_hidden](https://user-images.githubusercontent.com/18564130/115774143-35940800-a37f-11eb-8c78-70e44b2c7166.gif)
- **What error message are you getting?**
N/A

I've found some other issues similar to this: #764 #499 #451 but no conclusive answer to why this is happening.

**Comment by yairEO** [comment]
I didn't think it was an issue so I ignored it, but now you brought it up, I will fix it.

**Comment by paourissi** [comment]
The issue still exists

**Comment by yairEO** [comment]
@paourissi - I don't see it. Please provide your system info and a video if possible
