### ISSUE TITLE
Incorrect handling of duplicates

### ISSUE THREAD

**Issue by CallMeArtych** [yairEO/tagify#81]
Input contains _foo_, _FOO_ is considered as a duplicate.
Input contains _FOO_, _foo_ **is not** considered as a duplicate.
Input contains _foobar_, _foo_ is considered as a duplicate.

**Comment by CallMeArtych** [comment]
Fixed by replacing
`return this.stringValue.indexOf(s.toLowerCase());`
with
`return this.stringValue.indexOf('"' + s + '"');`
on line 378 in tagify.js.
This disables case insensitivity (I do not need it).

**Comment by yairEO** [comment]
Thanks for reporting! right on it
