### ISSUE TITLE
React - Mix Mode - After we select tag it focuses to the starting of the input field

### ISSUE THREAD

**Issue by shubham-julaha** [yairEO/tagify#812]
## Prerequisites

- [x] I am running the latest version (4.0.5)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

***React*** issue template:
https://codesandbox.io/s/tagify-react-wrapper-oempc
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation
In the React Mix-Mode Tags when we are in the middle of the text area and if we click on the dropdown then it focuses to the starting of the input field.

- **What is the expected behavior?**
It should not go back to the starting point

- **What is happening instead?**
Currently when we click it goes to starting point, however if we press enter then it is working appropriately

- **What error message are you getting?**
No Error Message

Video Link - https://drive.google.com/file/d/1rFniTF2yS_22Q0hcXqtBEnJ963J1Zb7Z/view?usp=sharing

## Images - 
![image](https://user-images.githubusercontent.com/20798633/117019181-cfaa6780-ad12-11eb-85c3-632faf5e69db.png)
![image](https://user-images.githubusercontent.com/20798633/117019337-f23c8080-ad12-11eb-8cfe-f9f7a8903ec0.png)

Thanks!

**Comment by yairEO** [comment]
Doesn't happen to me. please state which browser are you using

**Comment by shubham-julaha** [comment]
Chrome Browser(Latest version)
Please check video link
https://drive.google.com/file/d/1rFniTF2yS_22Q0hcXqtBEnJ963J1Zb7Z/view?usp=sharing

Thanks!

**Comment by yairEO** [comment]
I see. you did not specify to click with the mouse. I thought to click the <kbd>Enter</kbd> key

**Comment by shubham-julaha** [comment]
Hi @yairEO 
is this fixed?

Thanks!

**Comment by yairEO** [comment]
not yet, is it urgent?

**Comment by markwatabe** [comment]
We started using this package (it is working very well for us!) and came across the same issue. @yairEO do you have an idea of how you would like to do the fix? My team could submit a PR if you don't have time.

**Comment by yairEO** [comment]
@markwatabe - this specific area of the code has very high complexity and requires knowledge of Tagify that extends beyond the code area which this happens. There are many internal methods and states which are not documented and could be used to try and solving this. I prefer to do it myself so the solution would integrate best with the existing-code.

It is true that my time is very very limited this week (I have a full-time job and Tagify is a hobby-project out of dozens I have on Github) but sometimes PayPal donations rejuvenate my investment. is this urgent to you?

**Comment by markwatabe** [comment]
Not so urgent, but def would be nice. Let me know when you get around to it and I'll gladly donate 50 bucks!

**Comment by david-benes** [comment]
@yairEO When do you plan the next release? This issue #812 was the only issue that prevented me from using Tagify in my project.

**Comment by yairEO** [comment]
@david-benes I will try and merge today/tomorrow

**Comment by shubham-j-hh** [comment]
Hi @yairEO 

Still not working with the latest version

**Comment by david-benes** [comment]
@shubham-j-hh Are you sure that you are using the latest version (not the cached previous version)? 

The issue was resolved and I can't reproduce it anymore with the latest.
