### ISSUE TITLE
Can I use tags outside of input ?

### ISSUE THREAD

**Issue by bacloud14** [yairEO/tagify#813]
I want to print some tags, and I really like tagify style, also I am already using it in a different page.
Can I just print tags outside of input ? tags also should be non modifiable in this case. (and better if clickable as a link)./
thanks a lot !

**Comment by yairEO** [comment]
All the examples, including *outside* and *readonly*, are shown in the [demo page](https://yaireo.github.io/tagify/)

**Comment by bacloud14** [comment]
thanks a lot !
