### ISSUE TITLE
Tagify - Remove all Tags without Button...

### ISSUE THREAD

**Issue by RostRoth** [yairEO/tagify#814]
Hi. 
I am realy new to Javascript and have a short question. 

I use Tagify in a Form and i submit this form by Ajax. 

Is it possible to remove all tags after sending through ajax? Maybe in the response?

Thanks for helping me!
Rgds
Patrick

**Comment by yairEO** [comment]
Hi

Use the `removeAllTags` [method](https://github.com/yairEO/tagify#methods) after your form has been sent:

```js
// assuming "tagify" is the name of your instance
tagify.removeAllTags()
```

**Comment by RostRoth** [comment]
Hi. Sorry for my late reply and thank you. 

But is still doesnt get it to work.
This is my script: 

`$("#add_position").submit(function(e){
				  e.preventDefault();
	 
				 var data=$(this).serialize();
				 $.ajax({
					 url:"add_position.php?products_ean="+$("#products_EAN").val(),
					 type:"POST",
					 data:data,
					 success:function(result){
						 $("#positionen").html(result);  
						 $("#add_position")[0].reset(); 
						 tagify.removeAllTags()
					 }
						});
				  });	` 

Everything works fine, except removing the Tags from the textfield :/

Thank you very much in advance!

Rgds
Patrick

**Comment by yairEO** [comment]
@RostRoth - please make sure `tagify` points to the correct instance of the tags component you want to clear the tags for.

**Comment by RostRoth** [comment]
Hi. 
This is my input-field: 

`<input type="text" id="kt_tagify_1" class="form-control form-control-lg tagify" name="tags" placeholder='Anzahl und Größen...'  />`

So is this the correct way ? :

`$("#frm-add-to-cart").submit(function(e){
			 e.preventDefault();

			var data=$(this).serialize();
			$.ajax({
				url:"add_items_in_cart.php?id="+$("#products_EAN").val(),
				type:"POST",
				data:data,
				success:function(result){
					$("#mini-cart").html(result);
					$("#frm-add-to-cart")[0].reset();
					$("#rr_select_lshop").val(null).trigger("change");
					**kt_tagify_1.removeAllTags();**
					  
				}
				   });

			 
			 });`

Sorry if my questions seems to be stupid to you but i want to get this solved but i am realy new to javascript :/
Thank you !

Rgds
Patrick

**Comment by yairEO** [comment]
`kt_tagify_1` is not a Tagify instance. how does your input becomes a Tagify component? you did not show your complete code..
