### ISSUE TITLE
tagify input format when adding tags

### ISSUE THREAD

**Issue by AmirAbbasIT** [yairEO/tagify#815]
hi...
when i'm adding tags it comes in format like `{{{"value":"abc","prefix":"@"}}}` while my whitelist is `["abc","def","hij"]`

i want the behavious when i add a tag it comes in format   `{{abc}}`  like this just value under setting... `mixTagsInterpolator: ["{{", "}}"]`

my settings are below i'm using React jS
```js
settings={{
                     mixTagsInterpolator: ["{{", "}}"],
                     mode: 'mix',
                     pattern: /@/,
                     dropdown : {
                      enabled: 1,
                      highlightFirst: true,
                       fuzzySearch:true
                     },

                     duplicates: false
                  }}
                  whitelist={variables}
```

**Comment by yairEO** [comment]
you should modify the output format yourself, I cannot change it for each person who needs it differently.

How is this a problem to you? does it not work?
