### ISSUE TITLE
Re-validation on edit/delete tags

### ISSUE THREAD

**Issue by gregory-soliton** [yairEO/tagify#816]
Hi,

I'm currently trying to allow retaining all invalid inputs and allow the user to update/fix the invalid input.

My validation rules are:
1. No duplicates
2. Max tags of 3
3. Custom validation by using  validate function.

My problem is on the edit/removing of tags. The tags looks like it is not updated... Sorry for newbie question. What should I do to update the tags?

**On duplicates:**
1. When there are duplicates, the first tag background is gray, second tag background is red.
2. Remove the first tag.
3. The second tag bg is still red and I need to edit the second tag to change the color to gray.

**On Max tags validation (example max 3):**
1. When I added fourth tag, the fourth tag bg is red.
2. Remove either one of the first three tags.
3. The fourth tag bg is still red.

**On custom validation:**
1. Add a tag that returns false on validation. The tag will be red.
2. Edit the tag to that returns true on validation. I can see that the border was changed from red to cyan.
3. After editing, the tag is still red.

Sample code:

```
var $input = $('#txtInput').tagify({
      maxTags: 3,
      keepInvalidTags: true,
      editTags: {
          keepInvalid: false,
      },
      transformTag: function transformTag(tagData) {
          if (tagData.__isValid === true) {
              tagData.style = "";
          } else {
              tagData.style = "--tag-bg:" + "var(--tag-invalid-bg)";
          }
      },
      validate: function validateItem(item) {
          if (!customValidator(item.value)) {
              return "Invalid input";
          }
          return true;
      }
});

// get the Tagify instance assigned for this jQuery input object 
// so its methods could be accessed
var jqTagify = $input.data('tagify');
```

**Comment by yairEO** [comment]
Probably related to #818

**Comment by gregory-soliton** [comment]
Hi @yairEO,

Thank you for checking!

I tried the latest code and it solved the problem on duplicates.
But the problem still persist on `Max tags validation` and `Custom validation`.

Thanks

**Comment by yairEO** [comment]
Please create a demo page, as per bug report instructions:

>💥 Demo Page
> jsbin.com/jekuqap/edit?html,js,output

**Comment by gregory-soliton** [comment]
Hi @yairEO ,

I created a demo page. Please take a look.

https://jsbin.com/demasacoja/edit?html,js,output

Thanks!

**Comment by yairEO** [comment]
"Max tags validation" is a confirmed bug and will be fixed. Regarding removing/editing tags:

https://user-images.githubusercontent.com/845031/118771527-53279500-b88b-11eb-9cce-29be47fbf508.mp4

**Comment by gregory-soliton** [comment]
Hi @yairEO ,

Thank you for your reply!

I saw the sample clip and that is the validation about duplication. Which is working based on the latest version.
But for the custom validation, it is not working. I have a custom validation to check the length of the string. just a sample.


https://user-images.githubusercontent.com/30164788/118777198-c0571c80-b8c3-11eb-91cf-67544ff81c3e.mp4

**Comment by gregory-soliton** [comment]
Also the max tags validation. Please check it out. Thanks!


https://user-images.githubusercontent.com/30164788/118778320-ef21c280-b8c4-11eb-9b6d-a7dd3690538f.mp4

**Comment by yairEO** [comment]
That is a bug, but for your case, you should use *regex* in the [`pattern` setting](https://github.com/yairEO/tagify#html-input--textarea-attributes), as per Tagify docs in order to limit the number of characters:

https://jsbin.com/todomez/1/edit?html,js,output

**Comment by gregory-soliton** [comment]
I just created a simple custom validation to show in the demo. There are other conditions and check in the in the actual code. 
Sorry, I did not mention this earlier. Thank you for the suggestion!

Also, the `pattern setting` also have the same bug with the `validate setting`.

**Comment by gregory-soliton** [comment]
> "Max tags validation" is a confirmed bug and will be fixed. Regarding removing/editing tags:
> 
>  tagify.mp4

Hi @yairEO ,

The max tags validation is not yet fixed. Should we reopen this issue or create another issue for it?

Thank you.

**Comment by gregory-soliton** [comment]
Hi @yairEO ,

I tested and found a small problem.

Max tags is set to 3 but could input more by fixing an invalid tag.

https://user-images.githubusercontent.com/30164788/120279482-77568d80-c2f1-11eb-9f48-52ad746b9ba1.mp4

**Comment by yairEO** [comment]
@gregory-soliton - good catch, I will fix this as well and release a new version, hopefully today
