### ISSUE TITLE
Show suggestions on focus not working

### ISSUE THREAD

**Issue by TheMixy** [yairEO/tagify#820]
## Prerequisites

- [x] I am running the latest version
I'm not sure which version. I downloaded it in February 2021.

### Dev system
Windows 10 PRO
Visual Studio 2019
ASP.Net Core MVC project

### Explanation

Following your code sample on https://yaireo.github.io/tagify/ for Same using custom suggestions I wrote this code:

html
```
<textarea name="tbSearch2" placeholder="Filter by tags" id="tbSearch2" class="form-control email-filter" rows="1">
</textarea>
```
js
```
var tagslist = '';
$.ajax({
    'url': "Home/GetTags",
    'success': function (data) {
        tagslist = data;

    // load tags for searching
    var tagify1 = new Tagify(document.querySelector('textarea[name=tbSearch2]'), {
        tagTextProp: 'name',
        enforceWhitelist: true,
        delimiters: null,
        whitelist: tagslist,
        editTags: false,
        enabled: 0,
        dropdown: {
            mapValueTo: 'name',
            enabled: 1,           
            searchKeys: ['name'],
        },
    });
    }
});
```
The control itself works (tags are shown when I start typing), but there are no suggestions showing on control focus as per your sample code...??

**Comment by yairEO** [comment]
how many times are you calling this ajax? this code seems buggy. you should probably **not** create an instance of *Tagify* on your jQuery ajax `success` method, but instead instantiate it and only when the response is received, populate your *tagified* component using `tagify.add(...)`

**Comment by TheMixy** [comment]
@yairEO I tried what you suggested, but it doesnt work:

```
// run on page load (note: runs only once)
var tagify1 = new Tagify(document.querySelector('textarea[name=tbSearch2]'), {
            tagTextProp: 'name',
            enforceWhitelist: true,
            delimiters: null,
            editTags: false,
            dropdown: {
                mapValueTo: 'name',
                enabled: 1,            // min search characters
                searchKeys: ['name'],
            },
        });

$.ajax({
    'url': "Email/GetTags",
    'success': function (data) {
        tagify1.add(data);
    }
});
```

I get a javascript error: `Uncaught TypeError: tagify1.add is not a function`
