### ISSUE TITLE
Creating a loading state for each tag

### ISSUE THREAD

**Issue by jsgandalf** [yairEO/tagify#822]
Hi team, I've been struggling past few weeks on this issue.

**Problem**: I would like to customize every tag that is entered into tagify with a custom loading spinner that is validated with an ajax call to a server. 
1. After the ajax call, the tag is validated. 
2. If there are errors, change the css of the individual tag. 
3. Currently I see no way to modify the DOM of each tag individually, wait for a response from a server, and then modify that tags class with css depending on the result.

**Solution**: I have modified the `templates` attributes with the html of the custom spinner, but I see no way to update the custom spinner of each tag on or off.

I've tried to listen to events and try to modify the dom... would that be the correct approach? That would work for editing a tag that is already added to the DOM, but the 'add' event listener happens before the event is added. The only way I would see this possible is through the hooks, but I don't see any hook that would work here. Please help!

Here's what I have so far:
```
 
const options = this?.data?.options || {
    keepInvalidTags     : true,         // do not remove invalid tags (but keep them marked as invalid)
    editTags            : {
      clicks: 1,              // single click to edit a tag
      keepInvalid: false      // if after editing, tag is invalid, auto-revert
    },
    transformTag        : transformTag,
    templates : {
      tag : function(tagData){
          try{
          return `<tag title='${tagData.value}' contenteditable='false' spellcheck="false" class='tagify__tag ${tagData.class ? tagData.class : ""}' ${this.getAttributes(tagData)}>
                      <x title='remove tag' class='tagify__tag__removeBtn'></x>
                     
                      <span class='tag_process ${tagData.isLoading ? "" : "hidden"}'><progress class='CSATS-Style-progress-circular'></progress></span>

                      <div>
                          ${tagData.code ?
                          `<img onerror="this.style.visibility='hidden'" src='https://lipis.github.io/flag-icon-css/flags/4x3/${tagData.code.toLowerCase()}.svg'>` : ''
                          }
                          <span class='tagify__tag-text'>${tagData.value}</span>
                      </div>
                  </tag>`
          }
          catch(err){}
      }
    }
  };
```

**Comment by yairEO** [comment]
Hi, yes, you are supposed to listen to the `add` event and then validate the tag, and in the event's callback argument you will see you have access to the tag's DOM:

```js
tagify.on('add', onTagAdded)

function onTagAdded(e){
  console.log( e.detail ) // here you'll get all relevant information needed to validate & modify the DOM
}
```

**Comment by jsgandalf** [comment]
Thank you so much! I'm so grateful for the plugin, it works really well! This was the exact push/direction I needed. I see now.
