### ISSUE TITLE
Can not make more than One Tag in Ajax whitelist

### ISSUE THREAD

**Issue by muhamedRadwan** [yairEO/tagify#823]
Hi There 
Tagify Working Only in the first Mention and then the dropdown not showing any suggestion 
When Traced the code I found this line return empty list `c.filter((t=>this.isTagDuplicate(o(t) ? t.value : t)))` from `filterListItems` function 
Any Help, please?
My List from server `[{id: 10, text: "Erwin Smith"}, {id: 11, text: "Levi Ackerman"}]`

`var xhr;
$(()=>{
            var input = document.querySelector('textarea'),
            // init Tagify script on the above inputs
            tagify = new Tagify(input, {
            //  mixTagsInterpolator: ["{{", "}}"],
                mode: 'mix',  // <--  Enable mixed-content
                pattern: /@/,  // <--  Text starting with @ 
                tagTextProp: 'text',  // <-- the default property (from whitelist item) for the text to be rendered in a tag element.
                // Array for initial interpolation, which allows only these tags to be used
                whitelist: [],
                enforceWhitelist:false,

                dropdown : {
                    enabled: 1,
                    position: 'text', // <-- render the suggestions list next to the typed text ("caret")
                    mapValueTo: 'text', // <-- similar to above "tagTextProp" setting, but for the dropdown items
                    highlightFirst: true  // automatically highlights first sugegstion item in the dropdown
                },
                callbacks: {
                    add: console.log,  // callback when adding a tag
                    remove: console.log   // callback when removing a tag
                }
            })

            // listen to any keystrokes which modify tagify's input
            tagify.on('input', onInput)

            function onInput( e ){
                var value = e.detail.value;
                var prefix = e.detail.prefix;
                tagify.settings.whitelist.length = 0; // reset the whitelist
                tagify.settings.whitelist= []; // reset the whitelist
                if(prefix == '@' && value){
                    tagify.loading(true).dropdown.hide.call(tagify)
                    if(xhr){
                        xhr.abort();
                    }
                    xhr = $.ajax({
                    url: "{{ route('get.users') }}",
                    type: 'post',
                    data: {
                            _token: $('meta[name="csrf-token"]').attr('content'),
                            search: value // search term
                    },
                    }).done(function(data) {
                        data = JSON.parse(data);
                        tagify.settings.whitelist.push(...data);
                        tagify.loading(false).dropdown.show.call(tagify)// render the suggestions dropdown
                    });
                    console.log(value);
                }
            }`

**Comment by yairEO** [comment]
Please create a demo page, as instructed in the bug report issue, if you want me to help.

Technically I do not provide support but if you make the effort in creating basic demo which illustrates your problem, I will help.

**Comment by narensingh008** [comment]
@muhamedRadwan 
The below example works for me I am using c# for server-side API and return as a list.
Example 1:
` $.each(data, function(index, value) {
           tagify.settings.whitelist.push(value);
  });
Example 2:
tagify.settings.whitelist=[{code:'01',value:'Vanjaro'},{code:'02',value:'CMS'}];

**Comment by muhamedRadwan** [comment]
We can Close It I think because duplicate is on
