### ISSUE TITLE
trigger dropdown on whitelist update

### ISSUE THREAD

**Issue by Arnaves** [yairEO/tagify#824]
I am updating the tags in white list based on pagination on a button click
how can i trigger the dropdown on white list change

**Comment by Arnaves** [comment]
I am updating the tags in white list based on pagination on a button click
how can i trigger the dropdown on white list change

**Comment by yairEO** [comment]
It is shown in the second example on the [demos page](https://yaireo.github.io/tagify)

```js
tagify.dropdown.show.call(tagify, e.detail.value); // second parameter is optional value to filter the list by
```

**Comment by Arnaves** [comment]
another help ,how to add the first suggestion on pressing tab
