### ISSUE TITLE
to prevent default paste event

### ISSUE THREAD

**Issue by kegomei** [yairEO/tagify#826]
hello, when paste, how can i just paste content to text area but not to become a tag?

**Comment by yairEO** [comment]
Are you using `mix-mode` or not? please provide your Tagify settings here

**Comment by yairEO** [comment]
In the past this is how Tagify worked - you would paste content and it would not become a tag until you click <kbd>Enter</kbd> or blured, allowing further editing. 

Some user convinced me to change it in #535 

I will create a setting so developers could choose if they want automatic tagging for pasted content or not
