### ISSUE TITLE
Alpine js + tagify

### ISSUE THREAD

**Issue by muriloelias** [yairEO/tagify#827]
Hey guys.

First of all thanks for maintaining this library. It is very good and very complete.

I am trying to use it with the alpine js and am having difficulties.

I can't get the value of tag input to send an ajax request.

In addition, I think the library has a problem with showing background color of large tags.

To help the understanding of those who want to try to help me, I posted here an example with both problems.

https://codepen.io/muriloelias/pen/JjWyQRE

Thank you very much for your attention.

Murilo

**Comment by yairEO** [comment]
Hi, thanks! there is no team, just me, a random person from the internet making open-source for fun.

### Some questions:
1. Why is your Tagify component so narrow?
2. Must you show multiline tags? if so, you should change the CSS variable as 
https://user-images.githI show in this video (and can be seen live on Tagify's [demo site](https://yaireo.github.io/tagify/)) 


https://user-images.githubusercontent.com/845031/120081446-6a098b00-c0c6-11eb-8a94-c66285635507.mp4

I don't know what is `alpine.js` but delete the `x-model` which seemed to clash with Tagify:

```html
<input name='tags' autofocus>
```

And then in the JS do this:
```js
return {
    formData: {
        tags: input.value, // <- this instead of x-model binding
        simpleinput : 'testsimpleinput'
    },
```

**Comment by basduchambre** [comment]
A bit late to the party but I encountered the same issue with AlpineJS and Tagify. The workaround I found is as follows: 

`<input type="text" name="tags" class="no-pl" x-model="formData.tags" @change="formData.tags = $event.target.value" />`
