### ISSUE TITLE
Double enter key required for predefined tags

### ISSUE THREAD

**Issue by jasonhill** [yairEO/tagify#829]
## Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
You can repro this on the tagify demo page: https://yaireo.github.io/tagify/

### Explanation

- **What is the expected behavior?**
Type a tag that exists in the predefined list of tags (e.g. Java in the second demo field). Press the enter key without selecting anything from the dropdown. The tag should be added to the input field.

- **What is happening instead?**
On the first enter key press, the dropdown disappears but the tag is not added to the input field. Press enter again and the tag is added to the input field. If you press enter on values that are not in the predefined list of tags, then the value is added to the input field on the first enter key press. Predefined values require you to select the entry from the dropdown or press enter twice.

- **What error message are you getting?**
None.

**Comment by yairEO** [comment]
Thanks Jason for catching this, I will take a look in the code as to why this is happening and what can be done

**Comment by yairEO** [comment]
You can set this setting to your Tagify instance to bypass the double <kbd>Enter</kbd> clicks:

dropdown: {
  highlightFirst: true
}

**Comment by jasonhill** [comment]
That works great. Thanks.
