### ISSUE TITLE
removeTag Not working

### ISSUE THREAD

**Issue by shashibeit** [yairEO/tagify#83]
````
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at t.removeTag (tagify.min.js:1)
    at HTMLButtonElement.<anonymous> (Medicine.js:136)
    at HTMLButtonElement.dispatch (jquery-3.3.1.js:5183)
    at HTMLButtonElement.elemData.handle (jquery-3.3.1.js:4991)
````

**Comment by yairEO** [comment]
what did you do which caused this to show?

**Comment by shashibeit** [comment]
var allowedTags = [
    {
        "value": "Jaws",
        "id": 1,
        "class": 'color-red'
    }, {
        "value": "Infernal Affairs",
        "id": 2,
        "class": 'color-red'
    }, {
        "value": "The Best Years of Our Lives",
        "id": 3,
        "class": 'color-red'
    }, {
        "value": "The Help",
        "id": 4,
        "class": 'color-red'
    }, {
        "value": "Gangs of Wasseypur",
        "id": 5,
        "class": 'color-red'
    }, {
        "value": "Kind Hearts and Coronets",
        "id": 6,
        "class": 'color-red'
    },

    {
        "value": "strawberry",
        "id": 7,
        "class": 'color-red',
        "readonly": true
    }
];

 tagify = new Tagify(document.querySelector('textarea[name=tags]'), {
        whitelist: allowedTags,
        mapValueToProp: "data-id", // map tags' values to this property name, for server reasons
        dropdown: {
            classname: "extra-properties", // custom class for the suggestions dropdown
            enabled: 1 // suggest tags after a single character input
        }
    })

 tagify.addTags(allowedTags.slice(0, 2));

**Comment by shashibeit** [comment]
I am using  bellow code to implement it in my site 
but it gives an above-mentioned error when I click on remove button
var allowedTags = [
    {
        "value": "Jaws",
        "id": 1,
        "class": 'color-red'
    }, {
        "value": "Infernal Affairs",
        "id": 2,
        "class": 'color-red'
    }, {
        "value": "The Best Years of Our Lives",
        "id": 3,
        "class": 'color-red'
    }, {
        "value": "The Help",
        "id": 4,
        "class": 'color-red'
    }, {
        "value": "Gangs of Wasseypur",
        "id": 5,
        "class": 'color-red'
    }, {
        "value": "Kind Hearts and Coronets",
        "id": 6,
        "class": 'color-red'
    },
    {
        "value": "strawberry",
        "id": 7,
        "class": 'color-red',
        "readonly": true
    },
    {
        "value": "blueberry",
        "id": 8,
        "class": 'color-darkblue'
    },
    {
        "value": "apple",
        "id": 9,
        "class": 'color-green'
    },
    {
        "value": "orange",
        "id": 10,
        "class": 'color-orange'
    },
    {
        "value": "passion fruit",
        "id": 11,
        "class": 'color-purple'
    },
    {
        "value": "banana",
        "id": 12,
        "class": 'color-yellow'
    },
    {
        "value": "paprika",
        "id": 12,
        "class": 'color-red'
    }
];
    tagify = new Tagify(document.querySelector('textarea[name=tags]'), {
        whitelist: allowedTags,
        mapValueToProp: "id", // map tags' values to this property name, for server reasons
        dropdown: {
            classname: "extra-properties", // custom class for the suggestions dropdown
            enabled: 1 // suggest tags after a single character input
        }
    })


$(".tags--removeAllBtn").click(function () {
tagify.removeTag(MedicineID);
});

**Comment by shashibeit** [comment]
tagify.removeTag(MedicineID);
This lince causing above issue

**Comment by yairEO** [comment]
Did you solve it?

**Comment by hassanrrs** [comment]
getting this error while removing the tag using javascript
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at animation (tagify.js:674)
    at Tagify.removeTag (tagify.js:660)
    at HTMLSpanElement.<anonymous> ((index):167)
    at HTMLDocument.dispatch (jquery-1.11.1.min.js:3)
    at HTMLDocument.r.handle (jquery-1.11.1.min.js:3)

Error produces on tagify.js: 674

**Comment by yairEO** [comment]
Try now with Tagify version `2.3.0`

**Comment by yairEO** [comment]
@hassanrrs - does it work now?
