### ISSUE TITLE
updating the whitelist on scroll event of the suggestion dropdown

### ISSUE THREAD

**Issue by Arnaves** [yairEO/tagify#830]
can you guide me in updating the whitelist on scroll event of the suggestion dropdown

**Comment by yairEO** [comment]
what exactly is the scenario, in steps?

**Comment by Arnaves** [comment]
On click the suggestion dropdown come, i have changed its height
At first only 10 items come in whitelist, i want to scroll down and the whitelist should update to show more suggestions

**Comment by Arnaves** [comment]
Hi YairEO,
i used 
callbacks: {
      'dropdown:scroll': (e) => {
        // do something with respect to the scroll percentage
        console.log(e.detail.percentage);
      },
I seem to have no response
looks like a bug https://github.com/yairEO/tagify/blob/master/src/tagify.js#L66
I cannot find dropdown:scroll among the other event names:
customEventsList : ['change', 'add', 'remove', 'invalid', 'input', 'click', 'keydown', 'focus', 'blur', 'edit:input', 'edit:beforeUpdate', 'edit:updated', 'edit:start', 'edit:keydown', 'dropdown:show', 'dropdown:hide', 'dropdown:select', 'dropdown:updated', 'dropdown:noMatch']

**Comment by Arnaves** [comment]
yes sir , currently there are thousands and will grow exponentially in future

**Comment by yairEO** [comment]
@Arnaves - I see that only the way you are using it is not working, but would work if you directly bind the event to your Tagify instance, like so:

```js
tagify.on('dropdown:scroll', onDropdownScroll)
```

I will fix the binding through the settings Object
