### ISSUE TITLE
Can bypass max-tags validation by editing invalid tag to be valid 

### ISSUE THREAD

**Issue by yairEO** [yairEO/tagify#832]
Max tags is set to 3 but could input more by fixing an invalid tag.

https://user-images.githubusercontent.com/30164788/120279482-77568d80-c2f1-11eb-9f48-52ad746b9ba1.mp4

_Originally posted by @gregory-soliton in https://github.com/yairEO/tagify/issues/816#issuecomment-851872672_

**Comment by gregory-soliton** [comment]
Hi @yairEO ,

I tested the latest version, it has another problem on editing other valid tags when it reached the max tags limit.

https://user-images.githubusercontent.com/30164788/120948515-583a7e80-c77d-11eb-96a5-73ed9d9d5ad0.mp4
