### ISSUE TITLE
ajax demo

### ISSUE THREAD

**Issue by sdalu** [yairEO/tagify#833]
That's more of a documentation issue.
In the provided codepen demo: https://codepen.io/vsync/pen/OJNVyQR
The reset of the current whitelist (`tagify.settings.whitelist.length = 0;`)  is done when entering `onInput`, it should be done in the ajax promise before pushing the new whitelist. Otherwise multiple ajax answer can arrive due to fast typing (or slow network) which will create duplicates

**Comment by yairEO** [comment]
it's up to the developer's responsibility to incorporate *debouncing* and to abort previous requests once a new one has been made, it's best-practice.
