### ISSUE TITLE
Get the input string before it becomes a tag

### ISSUE THREAD

**Issue by georgios89** [yairEO/tagify#835]
Hello, I am trying to extract the text that is written in the textbox before it is converted to a tag.

I tried executing the following after tagify.on('input', xxx); but it obviously doesn't work.
document.getElementById("textbox").value;

Is there any way to find it?
Thank you

**Comment by georgios89** [comment]
I did it by using e.detail.value after input is executed: tagify.on('input', xxx);

**Comment by yairEO** [comment]
so is it solved for you? I don't understand. You can also access a tag's data right before it becomes s tag through the `transformTag` setting.

The README of this project have all relevant information, like so:

![image](https://user-images.githubusercontent.com/845031/121307172-05d59b00-c900-11eb-8513-a10197be3598.png)
