### ISSUE TITLE
Values don't show

### ISSUE THREAD

**Issue by viccvanco** [yairEO/tagify#836]
Hi, in a project I need to get tags and inject them into an input field. I pass my values to the value attribute of my input field, but they are not displayed. However I tried the same thing on another project and it worked.

Here is my input : 

`<input type="text" id="reservation_form_services" name="reservation_form[services]" required="required" placeholder="Choisissez vos services" class="js-tagify-input form-control" data-list="services" value="[{"value":"79","name":"Carrosserie","category":"Entretien / Réparation véhicules"}]">`

And my js script : 

```
var tagify = new Tagify($elements, {
        tagTextProp: 'name',
        enforceWhitelist: true,
        skipInvalid: true,
        dropdown: {
            closeOnSelect: false,
            enabled: 0,
            classname: 'services-list',
            searchKeys: ['name']
        },
        maxTags: 3,
        templates: {
            dropdownItem: suggestionItemTemplate
        },
        whitelist: []
    });
```

Otherwise my script works when I type something in the input. Thank you.

**Comment by yairEO** [comment]
what is `$elements`? You may only pass ***1 single DOM node*** reference to be tagified. 
Are you using jQuery?

**Comment by viccvanco** [comment]
$elements is my input : document.querySelector('.js-tagify-input');

Yes I use jQuery with Webpack (but I use the JS version of tagify, not the jQuery version)

**Comment by yairEO** [comment]
You are not escaping double quotes, and it's better to use single quotes to wrap the `value` attribute:

```html
<input type="text" id="reservation_form_services" name="reservation_form[services]" required="required" placeholder="Choisissez vos services" class="js-tagify-input form-control" data-list="services" value='[{"value":"79","name":"Carrosserie","category":"Entretien / Réparation véhicules"}]'>
```

You cannot place value that has double quotes inside an attribute that uses double quotes around that value

**Comment by viccvanco** [comment]
Thank you, it's the `enforceWhitelist: true` which posed me problem :)
