### ISSUE TITLE
Targeting CSS from Vue side

### ISSUE THREAD

**Issue by jojukin** [yairEO/tagify#838]
@haseebeqx and @yairEO thank you for this great work on all of this!

I am helping implement Tagify on a Vue project and have it working quite well - except, I can't adjust the CSS. The [CSS Variables](https://github.com/yairEO/tagify#css-variables) do not seem to work (likely because I am not doing it right). Can you please lend a hand on how to adjust the background color of the tag ```---tag-bg``` for example with the Vue integration.

Thank you very much!

**Comment by yairEO** [comment]
`---tag-bg` you have three `---` instead of two `--`

Did you apply the variable inside the class of tagify?

`.tagify{ ... }`

**Comment by jojukin** [comment]
Thanks for your help. This is just what I needed!
