### ISSUE TITLE
Excuse me, I want to ask does it is possible only tagify value in the text when I push "enter -  key code is 13"

### ISSUE THREAD

**Issue by k870611** [yairEO/tagify#84]
I want to ask how to achieve this function which is even I select the suggestion (by click) or push right key, I can still type word in input tag, only when I push enter key, the value will be tagifyed.

**Comment by yairEO** [comment]
I'm sorry but I do not understand the question..

**Comment by k870611** [comment]
I mean in autocomplete mode , after select the suggestion by enter, user can still type word too, not tagify the input.

**Comment by yairEO** [comment]
I'm sorry.. I don't understand..

**Comment by yairEO** [comment]
I will try to see what is needed to be done for this to work, I'll let you know soon

**Comment by yairEO** [comment]
ok, this has been solved. check out the demo page

**Comment by k870611** [comment]
Thanks, it is help a lot, I want to ask a question further, does it can show suggest again after select autocomplete(like jquery - autocomplete(multiple),  http://jqueryui.com/autocomplete/#multiple)

**Comment by yairEO** [comment]
but what would it suggest? after you used the autocomplete then you must type at least a single character for the suggestion dropdown to show, and that's depending on the minimum characters length defined in your Tagify's setup to show a dropdown

**Comment by k870611** [comment]
Ok, I will re-think of this question. thanks for your response.
