### ISSUE TITLE
Work with IDs of whitelist only

### ISSUE THREAD

**Issue by wurst-hans** [yairEO/tagify#841]
Hey there, I'm looking for a solution that allows me to populate a JSON object for whitelist, but handle its IDs only when it comes to transfer between browser and server.

For example:

```
<script>
var whitelist = [
  {"id":1, "firstname": "John", "lastname": "Doe"},
  {"id":2, "firstname": "Max", "lastname": "Muster"}
];
</script>
```

What I want to achieve is, that Tagify is able to parse value of `<input type="text" value="[1,2]">` because it's a JSON value and is able to render appropriate tags based on whitelist. I know, that I can force Tagify to ouput the same way by using `originalInputValueFormat` option, ex.

```
originalInputValueFormat: function (values) {
    var result = [];
    for (var i = 0; i < values.length; i++) {
        result.push(values[i].id);
    }
    return JSON.stringify(result);
}
```

But how to be able to load correct tags on page load when value of input is `[1,2]`?

**Comment by yairEO** [comment]
Like this? https://jsbin.com/kehipil/2/edit?html,js,output

You did not specify what exactly you want the tag text to be

**Comment by wurst-hans** [comment]
Not exactly. I want input to be `<input placeholder="type tags" value="[1,2]">` and whitelist to be

```
whitelist: [
     {"id":1, "value": "John Doe"},
     {"id":2, "value": "Max Muster"}
]
```

And on initializing Tagify with `new Tagify()` I want to see two tags being added automatically: `John Doe` and `Max Muster`.
I can't find any setting, hook or anything similar in Tagify. Simply spoken, I'm looking for a solution, that allows me to specify and transfer IDs only, that refer to entries of whitelist (i.e. based on a given ID)

If there won't be any integrated solution in future, then best would be, if there will be any hook that interrupts initializing, so I can modify the final tags are going to be rendered. For example I can write a hook function then, which takes input value and looks into whitelist, ex.

```
renderHook: function (value) {
  // value is the raw input value
  var ids = JSON.parse(value);
  // result contains all tags to be rendered
  var result = [];
  for (var i = 0; i < ids.length; i++) {
    for (var j = 0; j < whitelist.length; j++) {
      if (ids[i] == whitelist[j].id) {
        result.push(whitelist[j]);
      }
    }
  }
  return result;
},

```

**Comment by yairEO** [comment]
You can change your whitelist a little and set up Tagify like this:
https://jsbin.com/kehipil/3/edit?html,js,output

```js
var input = document.querySelector('input')
var tagify = new Tagify(input, {
  tagTextProp: 'text',
  dropdown: {
    enabled: 0
  },
   whitelist: [
     {"id":1, value:1, "text": "John Doe"},
     {"id":2, value:2, "text": "Max Muster"}
   ]
})
```

**Comment by wurst-hans** [comment]
Alright, this did it. Not an absolutely clean way, because I work with `id`s instead of `value`s but I think I can manage this. Thanks a lot.

**Comment by yairEO** [comment]
Tagify must have a `value` property per tag, you can simply remove/ignore it in your *back-end* implementation

**Comment by wurst-hans** [comment]
Sorry for re-opening, but there are some issues. At first, I wondered why typing and searching did not work. I found out, that I have to set `searchKeys` option, see [here](https://jsbin.com/zociceseki/1/edit?html,js,output).

But this leads me to two questions:

The dropdown is shown and filtered for both fields, so when typing `Jim` I can see `Jim Beam` and when typing the number `3` the dropdown shows `Jim Beam` too. This is because of `searchKeys`. But when I remove `value` from `searchKeys` then initialization for `input` value fails.

Also, hovering a tag shows `value` for a tag. So the tag itself shows the `text` value, but on hover I see the numeric `value`. This is a bit odd. How can this be fixed?
