### ISSUE TITLE
Use a created array for whitelist

### ISSUE THREAD

**Issue by joshuacbb24** [yairEO/tagify#844]
Hello, 
I'm trying to use an array of objects that I created as the whitelist, but the suggestion dropdown will not populate with it's values. I have checked the array to make sure it is filled with the correct data and it is. Here is the code for the array I created.

            for (var j = 0; j < memberlist.length; j++) {
                var el = memberlist[j];
                for (var i = 0; i < name.length; i++) {
                    if (el.value == name[i]) {
                        member = true;
                    }
                }
                if (member == true) {
                    whitelist_1[z] = {

                        value: el.value,
                        name: el.value,
                        avatar: "{% static 'app/images/PngItem_4212266.png' %}",
                        email: el.email,
                        disabled: true,
                    }
                    member = false;
                    z++;
                }
                else {
                    whitelist_1[z] = {
                        value: el.value,
                        name: el.value,
                        avatar: "{% static 'app/images/PngItem_4212266.png' %}",
                        email: el.email,
                        disabled: false,
                    }

                    z++;
                }

            }

And I added it to the whitelist like so,

              whitelist: whitelist_1,

Can you please help me figure out what's wrong?

**Comment by joshuacbb24** [comment]
Here is proof the array is populated correctly

![array](https://user-images.githubusercontent.com/74516911/122306283-28564e00-ced6-11eb-801d-97af3403654e.png)

**Comment by yairEO** [comment]
Please created a minimal demo page as asked in the issue template (fork the [jsbin](https://jsbin.com/jekuqap/edit?html,js,output))


I don't understand what's the problem and I need to see it live

**Comment by joshuacbb24** [comment]
I can't really replicate it because I'm using a database to populate the array but essentially I am trying to use the array below as the whitelist, but the suggestion dropdown won't show the tags. I will attach the javascript code so you can see what was done. 


                    whitelist_1 = {

                        value: el.value,
                        name: el.value,
                        avatar: "{% static 'app/images/PngItem_4212266.png' %}",
                        email: el.email,
                        disabled: true,
                   }
 [java.docx](https://github.com/yairEO/tagify/files/6673175/java.docx)

**Comment by joshuacbb24** [comment]
> Please created a minimal demo page as asked in the issue template (fork the [jsbin](https://jsbin.com/jekuqap/edit?html,js,output))
> 
> I don't understand what's the problem and I need to see it live

**Comment by yairEO** [comment]
You can create a demo page with mock data...

Anyway, how do you actually assign your *whitelist* to the tagify instance? please paste the code
