### ISSUE TITLE
better search experience

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#847]
Hello, I am looking at replacing Choices.js (https://github.com/Choices-js/Choices) with Tagify. In the process I noticed that Choices.js has better search than Tagify. Two things I observed are

1) The matched list is sorted based on some kind of score so better matched options bubble up to the top
2) A single character matches to options that contain that character only upto certain prefix boosting the score for those that start with that character.

I believe choices.js internally uses fuse.js which seem to have a good default behavior of searching for short strings.

**Comment by yairEO** [comment]
After inspection it does appear it is using `fuse.js` but unfortunately including it will bloat the size of Tagify by `22kb`.. Maybe there is a more lightweight solution which I could use - I will Google.

I am trying to keep Tagify as low-weight as possible. Maybe there will be a way to optionally use a 3rd-party script like `fuse.js` so I won't have to manually integrate it inside Tagify's source code.

**Comment by dirslashls** [comment]
Thank you @yairEO , making it possible to optionally include it would be nice.

**Comment by yairEO** [comment]
Hi, I've recently added the `dropdown.sortBy` [setting](https://github.com/yairEO/tagify#settings), you might find it useful.

It allows custom sorting:

```js
new Tagify(inputElm, {
    dropdown: {
        sortby(suggestions, query){
           // do sorting here...
           return suggestions; // return sorted array
       }
    }
})
```

Or sort so top results will be suggestions which starts with the characters typed:

```js
new Tagify(inputElm, {
    dropdown: {
        sortby: 'startsWith'
    }
})
```
