### ISSUE TITLE
Noob question: Is it possible to use Tagify without a bundler?

### ISSUE THREAD

**Issue by homestar9** [yairEO/tagify#849]
Is a bundler required to use Tagify?  In other words, is there a way I can install Tagify via NPM and load it via a regular <script src="./node_modules/...js"> reference similar to older JS libraries? 

I have extremely limited experience with Webpack (mostly for scss) and I only need Tagify for a single page in my app.  I was thinking that referencing a .js file directly would be the easiest way to get started with Tagify.

**Comment by yairEO** [comment]
Hi, I've just added a section in the README file explaining how to do that:

https://github.com/yairEO/tagify#installation

Add these lines in the page where you wish to use Tagify:

```html
<script src="https://unpkg.com/@yaireo/tagify"></script>
<link href="https://unpkg.com/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />
```
