### ISSUE TITLE
Re-validate tag input tag does not append on tagify.value on some cases

### ISSUE THREAD

**Issue by gregory-soliton** [yairEO/tagify#850]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

### Explanation

When the tag is valid, it should be included in tagify.value.
But sometimes it does not.
Please check the clip below. Thanks!

https://user-images.githubusercontent.com/30164788/123060012-4e836d00-d445-11eb-8a70-311dadc7c462.mp4

**Comment by yairEO** [comment]
Thanks for reporting I will take a look
