### ISSUE TITLE
MixMode - When removing a tag (using x) the input field is not updated

### ISSUE THREAD

**Issue by Wolf-Byte** [yairEO/tagify#851]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://yaireo.github.io/tagify/

### Explanation

- **What is the expected behavior?**
- When removing a tag using 'x' the tag representation should be removed from the input field.

- **What is happening instead?**
- The tag is remove visually however the input field is not updated.

- **What error message are you getting?**
- None

- ***Replication steps***

1. Navigate to the official demo: https://yaireo.github.io/tagify/
2. Open the Knobs settings panel
3. Enable 'Show original input element'
2. Scroll down to the Mix mode example
3. Click the 'x' to remove "Cartman"
4. The original input is not updated

**Comment by yairEO** [comment]
Thanks for reporting, I will investigate
