### ISSUE TITLE
DOM exception when hiding the component from within the add event.

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#852]
I am using Tagify in single select mode and using the `add` event where I get the added value and then have logic to hide that removes the component (it's actually react setState call that changes to a label instead of a dropdown). This gives the following error.

DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.

The stacktrace is from the catch block at 

https://github.com/yairEO/tagify/blob/664efb0ad828a7b1a5ee27d552c0393f38f31a00/src/tagify.js#L561

I noticed that if I do the setState with a timeout of a few milliseconds, everything is fine. It seems like there is some setTimeout code within the selectOption API and so I am not sure if that's what is causing the problems.

In order to get around this problem, I am looking for options.

1) Is `add` the right event to use for custom logic including hiding the component or there is some other safer event that runs at the end of all processing by Tagify?
2) Is there a way to turn-off asynchronous processing by Tagify so there are not setTimeout calls?

**Comment by yairEO** [comment]
There are a lot of setTimeouts in Tagify...

I've begged people who seek help to post a reproducible demo with steps for me to follow, but you ignored all that... how can I help without what I've asked? I have no idea what is your specific setup and scenario..

**Comment by dirslashls** [comment]
Sorry about not providing the reproducible case. It was part of a larger code base with react.

Below is the code that reproduces the issue without any dependencies.

```html
<html>
	<head>
		<script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify@4.3.1/dist/tagify.min.js" integrity="sha256-tmCGG0wv978IdZW0dLaiERel+M4+kb27qljCOSeNxsM=" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@yaireo/tagify@4.3.1/dist/tagify.css" integrity="sha256-FcN7yt1eE3gnk83SurLMcBKYE3FjGoUOqbT5fblu38A=" crossorigin="anonymous">
	</head>
	<body>
		<input id="tagify"/>
		<script>
			const te = document.getElementById('tagify');
			const whitelist = Array(25).fill(0).map((v,idx) => `t${idx}`);
			const tagify = new Tagify(te,{
				whitelist: whitelist,
				mode: 'select',
				dropdown: {
					enabled: 0,
					maxItems: 0,
				}
			});
			tagify.on('add',(e) => {
				const pe = te.parentElement;
				const div = document.createElement('div');
				div.innerHTML = e.detail.data.value;
				// the following two lines mimick the equivalent of setState({})
				pe.replaceChild(div,te); // vdom diff will replace the original element
				tagify.destroy(); // componentWillUnmount will destroy the tagify widget
			});
		</script>
	</body>
</html>
```

The last two lines in the add handler mimic what I do with react setState that triggers unmounting the tagify component. If I comment out the tagify.destroy above, there is no error. 

Just typing the tag value and selecting works fine. For the exception to be thrown, select an option from the dropdown that triggers the click event.

**Comment by yairEO** [comment]
I wrote that error warning which you see in case the `setRangeAtStartEnd` fails to work, does that log bothers you? I don't think many users have their devtools open in the browser as they are mere mortals, unaware of such things

**Comment by dirslashls** [comment]
Thanks for checking @yairEO . If there are no other side effects related to destroying the tagify object while handlers are yet to run, then it should be OK. As I mentioned, I currently have a setTimeOut myself to avoid the setState firing synchronously and destroying the object.

**Comment by yairEO** [comment]
it's just a `console.warn` that I've placed myself, not something that should bother you
