### ISSUE TITLE
Dropdown List style is broken(has a gap from the input box)

### ISSUE THREAD

**Issue by lunacer** [yairEO/tagify#855]
There's a gap between the tags input box and the dropdown for the suggestion list.
I've tried to customize CSS but can't find a way to relocate the element.

<img width="753" alt="Screen Shot 2021-07-05 at 8 13 29 PM" src="https://user-images.githubusercontent.com/52251970/124463599-14fc1b80-ddce-11eb-89fc-8eb0e08b6594.png">

my basic setting is like this:

` const baseTagifySettings = {
    maxTags: 10,
    placeholder: `${t("Global.tags_add")}`,
    dropdown: {
      enabled: 0,
      maxItems: 10,
      position: "text", 
      closeOnSelect: true,
      classname: "customDropdownList",
    },
  };`

**Comment by yairEO** [comment]
Please create a jsbin demo page so I could inspect this issue because I don't see this happening no my own testing env.

The template for opening an issue explicitly asks to create a demo page if possible

**Comment by lunacer** [comment]
I just found the reason and It happens because of my reset CSS. I'm sorry for the wrong question and thank you for your time.
