### ISSUE TITLE
xss attack on tag invalid

### ISSUE THREAD

**Issue by popchenk** [yairEO/tagify#856]
Hello, I am having an issue trying to validate invalid tag in tagify. If you paste this ( `<img src=x onerror=prompt('XSS');>` ) into a tagify container that has space as a delimiter and is invalid, it still runs the whole html. How would I validate this ? 
With add it was kinda easy I just did it like this:

```
 tagify.on('add', function(e, tagData){
            $(e.detail.tag).children("div").text(e.detail.data.value);
        });
```
But tagify.invalid seems to run the whole html tag even though there is a space delimiter which I dont understand.

**Comment by yairEO** [comment]
I don't understand the whole flow. Can you please explain it in steps what is happening, from start to finish?

**Comment by popchenk** [comment]
Yes, basically if you take this html ` <img src=x onerror=prompt('XSS');>` and paste it into a tagify input and the tagify has space delimiter and whitelist. It still runs the whole thing, here is a [picture](https://gyazo.com/4cd60795c057cd21a0ce9bbfa1e0ce77).

Here are my tagify settings :

```
var tg = new Tagify(input3,{
            pattern             : /(?!.*\.\.)(^[^\.][^@\s]+@[^@\s]+\.[^@\s\.]+$)/,
            keepInvalidTags     : false,
            backspace           : "",
            editTags            : 1,
            blacklist: allMemberUsernames,
            delimiters:",|;| " ,
            maxTags             : $(".remaining").text(),
        }).on('add', function(e, tagData){
            $(e.detail.tag).children("div").text(e.detail.data.value);
        });
