### ISSUE TITLE
Pass own react component in to template or any workarounds?

### ISSUE THREAD

**Issue by peersky** [yairEO/tagify#857]
I'm implementing a searchbar where I'd like to make tags like `[[Find In: <MyCustomSelectorDropdown>]]` That way user can click on MyCustomSelectorDropdown and interact with it. 

Ideally I should be able to define settings something like
`settings.templates.tag = (tagData) => <MyCustomSelectorDropdown data={tagData} />`

But since templates take not component but a HTML string, it seems to be impossible to do. 

Are there any tips how to implement experience described? 

Thanks!

**Comment by yairEO** [comment]
Why impossible? :) 
React has many ways to do many things, and one of them is [rendertostaticmarkup](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup)

Tagify already supports this ([see this line](https://github.com/yairEO/tagify/blob/master/src/react.tagify.js#L14))

**Comment by peersky** [comment]
@yairEO I've tried rendertostaticmarkup but that does not really work out if I want to pass  [chakra-ui](https://github.com/chakra-ui/chakra-ui) components such like this:
```
<Menu>
<MenuButton>Button</MenuButton>
<MenuList>
   <MenuItem>1</MenuItem>
</MenuList>
</Menu>
```

**Comment by yairEO** [comment]
I will push a new version soon with better support for React components as templates, BUT, you cannot simply pass any template. 

the React component must be authored as close as possible to the current templates (in terms of class names and nodes hierarchy)

**Comment by yairEO** [comment]
Here's a demo of how it can be done:

https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/TagifyWithTemplates.jsx

**Comment by krsnaa** [comment]
@yairEO really wish you would use the stock react.tagify library from dist and not use a custom wrapper in the above codesandbox example...

**Comment by krsnaa** [comment]
> I'm implementing a searchbar where I'd like to make tags like `[[Find In: <MyCustomSelectorDropdown>]]` That way user can click on MyCustomSelectorDropdown and interact with it.
> 
> Ideally I should be able to define settings something like `settings.templates.tag = (tagData) => <MyCustomSelectorDropdown data={tagData} />`
> 
> But since templates take not component but a HTML string, it seems to be impossible to do.
> 
> Are there any tips how to implement experience described?
> 
> Thanks!

Did you get it to work?

**Comment by yairEO** [comment]
> @yairEO really wish you would use the stock react.tagify library from dist and not use a custom wrapper in the above codesandbox example...

it's not custom, it's identical, and you can switch to use the "stock" one, there's a commented `import`

**Comment by krsnaa** [comment]
> > @yairEO really wish you would use the stock react.tagify library from dist and not use a custom wrapper in the above codesandbox example...
> 
> it's not custom, it's identical, and you can switch to use the "stock" one, there's a commented `import`.
> 
> regarding your other question about React templates, I don't remember, I will check soon

Thanks @yairEO. I saw that and when I attempted to use the library import, in the TagifyWithTemplates example, it doesn't appear to have a tagify.settings object and throws errors.  Readily reproducible in the above codesandbox.

**Comment by lohit8846** [comment]
@yairEO I'm seeing the same issue as the comment above. The commented out react.tagify library is not working even when I upgrade the package. It is only working with the custom tagify source code files in the tagify directory

Can you check what the difference is between the two and make an update? This will allow us to use this nice feature that you have built to provide custom components

**Comment by RomeHein** [comment]
Yep same here 
<img width="573" alt="image" src="https://github.com/yairEO/tagify/assets/15328747/8d1fe925-d0af-4a46-a57e-2e3e9c37581a">
On this line:
<img width="328" alt="image" src="https://github.com/yairEO/tagify/assets/15328747/01bce518-351d-45eb-9ed6-873fc42137d9">

FYI, I've copied exactly the exemple provided in the react template demo: 
https://codesandbox.io/s/tagify-react-wrapper-oempc?file=/src/TagifyWithTemplates.jsx

Tagify version: 4.17.9

Btw, thanks very much for your massive work, this is really impressive 👍
