### ISSUE TITLE
How to hide virtual keyboard?

### ISSUE THREAD

**Issue by Aaarrrgggh** [yairEO/tagify#859]
Hi, 

thanks for your component!

I'm using it on an application, and I have noticed that virtual keyboard on Android appeared while focusing the tag element. Is there a way to hide it? I have to hide it manually to make your plugin work perfectly.

Thanks for your answer, 

Alexander

**Comment by yairEO** [comment]
Hi, 

How is the user gives focus to a tag? Just touch the tag?

**Comment by Aaarrrgggh** [comment]
When the user focus the input field. I have a dropdown list with many options. I tried to add inputmode=none on the input, but this does not work.

**Comment by yairEO** [comment]
How is the user supposed to add tags without the virtual keyboard?

**Comment by Aaarrrgggh** [comment]
I don"t know :)
But for some screens, virtual keyboard is too big

**Comment by yairEO** [comment]
You don't know... don't you think it's something important to know before hiding the keyboard?
