### ISSUE TITLE
Any option to reduce size of the library ?

### ISSUE THREAD

**Issue by syrm** [yairEO/tagify#861]
Hello, 

Thank you for your work.
How can i reduce the size of the library ?
Maybe a system to pick features a will use ?

**Comment by yairEO** [comment]
I thought about it and made a test to split just the simple tags from the *mix-tags* but it really doesn't save that much at the end, so I scrapped that idea.

After minification + compression the final javascript size is `14kb` 

Is that still too much for you?

**Comment by syrm** [comment]
14kb is very nice !!!!
