### ISSUE TITLE
Any possibility to custom helper title texts?

### ISSUE THREAD

**Issue by guibrancopc** [yairEO/tagify#862]
Hi there! 

First of all, thank you for this great component. It's very powerful and it's helping a lot already. 🙂 

I'm missing just a little thing, about to get a way to custom [these texts](https://github.com/yairEO/tagify/blob/06820fda2036a7c290fc8268d19cd39463939234/src/tagify.js#L62) that are showed on tag title in special cases (like `not allowed`, `pattern mismatch`, `already exists`). 

It's because I'm from Brazil and my users are from here too, so it would be good to have these texts custom for my own context.

Is there a way to get it custom from the configuration?

Or, if not, would it be considered to be developed?

Thank you in advance! 🙏

**Comment by yairEO** [comment]
Hi, You can override them with `Tagify.prototype.TEXT = {...}` for all instances or just for your instance:

```js
const myTagify = new Tagify(...)

myTagify.TEXTS = {...}
```

**Comment by guibrancopc** [comment]
Awesome! 

Thanks, @yairEO. 🙏
