### ISSUE TITLE
Can't make pattern regex work in MixMode

### ISSUE THREAD

**Issue by syrm** [yairEO/tagify#863]
## Prerequisites

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/nenoduxeli/edit?html,js,console,output

### Explanation

- **What is the expected behavior?**
Tags should match my regex

- **What is happening instead?**
The plugin don't detect tag

- **What error message are you getting?**
No one

**Comment by yairEO** [comment]
Hi, I didn't design the code in *mix-mode* to work with such patterns.

in *mix-mode* the `pattern` setting is meant only for matching the initial prefix and not for validating.. 

I didn't that that into consideration when designing the code about 4 years ago, because I thought *mix-mode* will only be used 99% for mentioning names/emails and from an available *whitelist* and only about 2 years ago I've added supposed for creating tags in mix-mode (ones not included in a whiltelist), and now it's not possible to make the `pattern` work as you expect. Have a look at the code:

https://github.com/yairEO/tagify/blob/master/src/parts/events.js#L483-L494

**Comment by syrm** [comment]
I think you could add a system here : https://github.com/yairEO/tagify/blob/master/src/parts/events.js#L488

Maybe a callback function like "validate" and its good.
I tried that : 
```
if (tag.length < 3 || tag.length > 5) {
    return;
}                        
```

**Comment by yairEO** [comment]
Can you please explain **in the most details way possible** what is your expected behavior?

**Comment by syrm** [comment]
In MixMode you should be able to validate tag.
The characters allowed, the size allowed.
You should even be able to validate them via xhr.
Validate it throught a callback function is the more flexible way.

**Comment by yairEO** [comment]
> *You should even be able to validate them via xhr.*

Please explain in details what does this means? I don't understand.

--- 

You can validate tags using the `validate` setting which is a function and I quote from the README:

> *If the pattern setting does not meet your needs, use this function, which recieves tag data object as an argument and should return true if validaiton passed or false/string of not. A string may be returned as the reason of the validation failure.*

**Comment by syrm** [comment]
>  You should even be able to validate them via xhr

You should be able to validate them by using XMLHTTPRequest (https://developer.mozilla.org/fr/docs/Web/API/XMLHttpRequest/send)

> You can validate tags using the validate setting which is a function and I quote from the README

Validate dont work in MixMode : https://jsbin.com/yorovakevu/edit?js,console,output

**Comment by yairEO** [comment]
@syrm - I don't understand, what is *"validate them by using XMLHTTPRequest"*, can you explain in **detail** the whole process, in as many words as possible?

**Comment by syrm** [comment]
When i type a tag, a callback function is call, the callback function do an XMLHTTPRequest to see all matchings tags corresponding to the input and see if the input match one of them

**Comment by yairEO** [comment]
you were not specific enough. what does it mean *"When i type a tag"*? when you actually typing or after you are done typing and the tag was just added to tagify? or just the second before it is added, you wish to validate in order to allow it to be added or not.

I will investigate why the `validate` function (defined on the *settings*) is not called for mix-mode tags, thanks for reporting on that!

**Comment by syrm** [comment]
when i’m actually typing :-)

**Comment by yairEO** [comment]
You want to call the server on each typing event? why do you think this is a good idea? Server response will for sure lag behind so you will have to debounce + kill any previous request which is ongoing.

It if better to validate (at the server, as you wish) at the point where the user stopped typing and now wants to add the tag, so then the "tag" will be validated and the UI will be "locked" until the server returns a response, and after this point, there are two possibilities:

1. tag is *valid* and can be added

2. tag is deemed *invalid* and should not be added as a tag (the text is replaced with a tag) but the text should remain as-in, and the user should be alerted, somehow, that validation failed for X reason.


This is a very general description, which should be broken down into further details.

I've asked you twice to explain your needs **in detail** but you did not explain much at all. I cannot help you without writing a full document specifying your requirements and cover all possible cases in more than 1-2 lines of an "explanation"

**Comment by syrm** [comment]
Debounce and kill etc, its the job of the developper who made the call.
I want be able to do the samething as twitter and all social media that are using a tag system in a message.

When you typing a tag, an XMLHTTPRequest is send to the server to allow auto completion.
This is a kind like a dynamic whitelist (too big to be embedded in JS) and the ability to add a tag not in the whitelist but that should respect some pattern (like space not allowed).

When you are typing on twitter if you put an invalid character for a tag (like a space) the tag is automatically valided.
But you can also pick a tag in the dropdown list which show you all availables tag in live during your typing.

**Comment by yairEO** [comment]
Is this solution good for you?

https://jsbin.com/fujezic/1/edit?js,output

**Comment by syrm** [comment]
not perfectly.

onKeydown is called after the key is is shown in tag. When i type #test the value of `e.detail.tagify.state.tag.value` is `tes`
I don't know how i can auto validate the tag if the user types an invalid character.
I type #test[space]test the tag should be automatically valided when i type space, like on twitter, i don't know how to do that with your example.

validate callback function is never called.

**Comment by yairEO** [comment]
I don't know Twitter, I never used that website.

You need to run your validations inside the `onKeyDown` function. 

Please paste here a video showing how it behaves on Twitter

**Comment by syrm** [comment]
![twitter-demo](https://user-images.githubusercontent.com/155406/127032974-b1c0cfc6-9d96-4029-b6fd-6031ae72a06c.gif)

**Comment by yairEO** [comment]
so cannot type while the async request is happening?

**Comment by syrm** [comment]
I can :-)

![twitter-test-2](https://user-images.githubusercontent.com/155406/127122704-a7c173d4-18ff-404f-b001-874e8ee9a565.gif)

**Comment by yairEO** [comment]
But I don't understand why is my [example](jsbin.com/fujezic/1/edit?js,output) not good enough for you to extend as per your requirements

**Comment by syrm** [comment]
Like i said I type #test[space]test the tag should be automatically valided when i type space, like on twitter, i don't know how to do that with your example.

**Comment by yairEO** [comment]
what do you mean *"valided"*? do you mean "vaslidated"? in what way is it validated? please write the full steps, both logic and visuals of this "validation". I've already asked this many times... I cannot help without understand in details what it is you want to happen here. 

just saying *"I want to validate when I type escape"* is not enough information for me to work with

**Comment by syrm** [comment]
Right now the tag is validated when you press [Enter] key, i should be capable to validated a tag myself in the onKeyDown.
So when someone press an invalid character for a tag (like a space) i gonna call a function to validated the tag myself (like calling e.detail.tagify.state.tag.validate())
