### ISSUE TITLE
Greater than character in whitelist array on another key than value destroys list

### ISSUE THREAD

**Issue by Tagirijus** [yairEO/tagify#872]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/dequpeqebu/edit?html,js,output

### Explanation

- **What is the expected behavior?**
I would expect the list to show me _Item a, Item b, Item c_.

- **What is happening instead?**
The dropdown list is _Item a_ and after that some part of the HTML code or so instead of _Item b_ and then comes _Item c_.

- **What error message are you getting?**
No error message.

I already tried it with `&gt;` but this did not work either. Mysteriously it only happens, when another array item of the whitelist has such a `>` character than the _value_ item.

**Comment by yairEO** [comment]
Thanks for reporting. fixed and will be included in the next release

**Comment by Tagirijus** [comment]
Cool. Thanks for the fast fix! (=

**Comment by Tagirijus** [comment]
Seems to be fixed in 4.6.0 now; thanks for that. (=
