### ISSUE TITLE
Disable the edit, and only allow dropdown input

### ISSUE THREAD

**Issue by jplevene** [yairEO/tagify#877]
### SUGGESTION:

A simple option to disable the typing input and only allow input from the dropdown which always appears on element focus

I have been trying to do this, but not been able to.

Tried:
```js
callbacks: {
	"input": (e) => e.preventDefault(), // Does not work to disable text input
	"keydown": (e) => e.preventDefault() // Also does not work to disable text input
}
```
but it does nothing.

The way I managed to do it was:
```js
// Prevent keyboard input
tagify.DOM.input.addEventListener('keydown', function(e) {
	e.preventDefault();
});
```

Just thought a simple setting would be neater and something to get rid of the cursor.

**Comment by yairEO** [comment]
As of `4.7.0` you can now use the `userInput` boolean setting to disallow user typing/pasting/editing so adding tags may only be done from the suggestions list

**Comment by jplevene** [comment]
> As of _Tagify_ version `4.7.0` you can now use the `userInput` boolean setting to disallow user typing/pasting/editing so adding tags may only be done from the suggestions list

Thanks
