### ISSUE TITLE
Only allow typing when single-value select is empty?

### ISSUE THREAD

**Issue by seabasss** [yairEO/tagify#880]
The single-value select is great, but I wish that when you've selected an option you can no longer change the text. Backspace would delete the tag and you can start typing to search again.
E.g. turning it more into a regular dropdown list with an added search when the input is cleared. Makes sense?

The regular tags works like this when you have `backspace: true`, but it doesn't seem to work on `mode : "select"`. Also I see `keepInvalidTags: false` in the single select demo, but it doesn't seem to do anything. I can select an option, change the text and it still stays where I left it. E.g. I can change the whitelisted option "Apple" into "Appl" and it just sticks around in the box even after blur.

Thank you!

**Comment by yairEO** [comment]
Good suggestion, I will do it. Thanks!
