### ISSUE TITLE
Setting default values doesn't work correctly when using searchKeys

### ISSUE THREAD

**Issue by seabasss** [yairEO/tagify#881]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/fopoluyiwi/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**
I want the default value to show the `title` (LA), but to do that I need to add `value` to `searchKeys`, which I don't want.

- **What is happening instead?**
It shows the `value` instead of the `title` (America/Los_Angeles)

- **What error message are you getting?**
No error, just wrong value displayed

It would also be great if the input got blurred on select and that the value isn't editable once added. To search for a new tag you should remove the current and start typing.

Thanks!

**Comment by yairEO** [comment]
`title` is meant for the tag's title attribute. I will investigate why it cannot be used as `tagTextProp`. Instead you can use any other word, such as `label` for example:

https://jsbin.com/suqujel/1/edit?html,js,output

**Comment by seabasss** [comment]
Thank you!

Now, the value shows up as label in the dropdown instead :)
https://jsbin.com/suqujel/1/edit?html,js,output

I want it to say LA/NY in both select and dropdown and only use the value to be stored/fetched to/from db.

**Comment by yairEO** [comment]
just remove the `searchKeys: ['label'],` line in the `dropdown` setting....

BTW - you can keep it as `title` instead of `label`

**Comment by seabasss** [comment]
> just remove the `searchKeys: ['label'],` line in the `dropdown` setting....
> 
> BTW - you can keep it as `title` instead of `label`

I can't search on the labels if I remove that. Basically, I just want the value to be what's fetched/stored and label what is displayed/searched.

Sorry, for being a pita, I'll figure something out or try to see if I can find a dedicated select plugin with search.

**Comment by yairEO** [comment]
you should leave the `value` there:

    searchKeys: ['value','title']
