### ISSUE TITLE
How to add a data field to a tag and change the output value based on that?

### ISSUE THREAD

**Issue by virtualdj** [yairEO/tagify#882]
First, thanks for your wonderful library.

I would like to allow the user to add some tags from the whitelist and then, when clicking on a tag, I would like to toggle a flag which should be stored inside the tag itself.
The toggle value should both condition the **appearance** of the tag (i.e. change its background color based on the flag value) and change the **output value** of the input control by prepending a '!' character if the flag is set. Which is the correct way to do this?

```javascript
var tagify = new Tagify(document.getElementById("tag"), {
    enforceWhitelist: true,
    whitelist: [{ value: 1, name: "Alice" }, { value: 2, name: "Bob" }, { value: 3, name: "Charlie" }],
    tagTextProp: 'name',
    editTags: false,
    delimiters: ' ',
    pattern: '^[A-Za-z0-9-]{2,}$',
    originalInputValueFormat: valuesArr => valuesArr.map(item => (item.negated ? '!' : '') + item.value).join('|'),
    dropdown: {
      enabled: 1,
      mapValueTo: 'name',
      fuzzySearch: true,
      position: 'text',
      highlightFirst: true
    }
  });

tagify.on('click', function(e) { 
  // Where should I set the "negated" flag/property to toggle it for each tag?
  e.detail.tagify.negated = !(e.detail.tagify.negated);

  // How can I save the property on the tag and update its background color based on the flag?
  tagify.replaceTag(e.detail.tag, e.detail.tagify.value);
});
```
In the example above:

1. Where should I save the _negated_ flag which I want to be toggled for each tag click?
2. Should I use the templates to change the background colour of the tag when clicked, based on the _negated_ value? Or is it better to do it on the _click_ event? I tried with the **transformTag** but I don't see a way to tell tagify that I've updated the tag _negated_ property.
3. If I add a tag "Bob" and "Charlie" and then click on "Bob" (which becomes negated), I would have the original input control with the string "!2|3", but the function in **originalInputValueFormat** doesn't seem to work (it equals to "2|3" instead). How can I affect the final output based on the tag property _negated_?

**Comment by yairEO** [comment]
You should call `replaceTag` with the second parameter being an *Object* representing the modified data:

```js
tagify.on('click', function(e) { 
  const {tag:tagElm, data:tagData} = e.detail;
  tagData.negated = !tagData.negated;
  
  if( tagData.negated )
  	tagData.style = "--tag-bg:gold";  // example of "gold" color when tag is negated.
  else
  	delete tagData.style; // remove any tag background color change 
  	
  tagify.replaceTag(tagElm, tagData);
});
```

The above is just one possible solution. you can also set a different class to the tag and then in your CSS target that class and set the `--tag-bg` there.

**Comment by virtualdj** [comment]
Great, thanks, this also makes `originalInputValueFormat` add the `! ` in front of the negated tags. Perfect!
