### ISSUE TITLE
Pasting mixed tags in mix mode

### ISSUE THREAD

**Issue by jebax** [yairEO/tagify#883]
Hi,

For our implementation of tagify it's important for us to be able to paste in content, convert it to tag syntax with `beforePaste` then have the tags displayed inside the input.

The result from `beforePaste` would be something like `random text [[{ \"id\": 1, \"value\": \"tag 1\" }]] more random text [[{ \"id\": 2, \"value\": \"tag 2\" }]]`

Is this possible with the current version of tagify? At the moment I have a `beforePaste` hook which converts some text to tagify syntax, but the input doesn't update to show the tags.

I got this semi-working by cloning the repo and adding `this.parseMixTags(result)` inside the `beforePaste` callback ([here](https://github.com/yairEO/tagify/blob/0f71ac6f8e7817418f2ae582f5a19db98b82d7e5/src/parts/events.js#L658)). But this is buggy and doesn't work very well.

Thanks for your help!

**Comment by yairEO** [comment]
> *But this is buggy and doesn't work very well.*
 
How so?

**Comment by jebax** [comment]
> > _But this is buggy and doesn't work very well._
> 
> How so?

If you already have text inside the input, then paste some more text, it messes up pretty badly. `parseMixTags` doesn't handle when you only want to parse what you have pasted

**Comment by yairEO** [comment]
I've made made a test and it seems to work ok:

https://jsbin.com/xucojahafe/1/edit?html,js,console,output

try to write some mixed tags and then copy-paste it again and again. try this string:

    [[{"value":"a"}]] [[{"value":"b"}]] dfdf [[{"value":"aa","prefix":"@"}]] not only

**Comment by jebax** [comment]
> I've made made a test and it seems to work ok:
> 
> https://jsbin.com/xucojahafe/1/edit?html,js,console,output
> 
> try to write some mixed tags and then copy-paste it again and again. try this string:
> 
> ```
> [[{"value":"a"}]] [[{"value":"b"}]] dfdf [[{"value":"aa","prefix":"@"}]] not only
> ```

ahh, this is nice calling `loadOriginalValues` when pasting. 

but as you can see the cursor jumps back to the beginning - is there a function we could call to move the cursor to the end of the pasted content?

**Comment by yairEO** [comment]
I've answered you in another issue you opened, so am closing this one
