### ISSUE TITLE
How to deal with originalInputValueFormat, enforceWhitelist, AJAX and browser going back (history)

### ISSUE THREAD

**Issue by virtualdj** [yairEO/tagify#885]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/qucuzehuwa/1/edit?html,js,output

### Explanation

- **What I'm going to do?**

   I would like to use AJAX to load a lot of tags from a database when the user starts typing, allowing him to choose only from existing tags (hence with `enforceWhitelist` enabled) and, at the same time, post only a **numeric ID** of the selected tags back to the server with a **custom separator**, when the form is submitted.

   So if the whitelist is: `[{value: 1, name: "Apple"},{value: 2, name: "Banana"},{value: 3, name: "Lemon"}]` and my typed tags are `Apple` and `Lemon`, I would like the original text input value to be `1|3` (with the `|` separator).

   This works perfectly with a code similar to the linked *demo page* above (where I introduced a delay on the whitelist populating, to simulate the AJAX call). But there are some issues with this approach.

- **What is happening instead?**
1. With `enforceWhitelist` set to `true` I could initialize the textbox `value` with the value saved on the DB (e.g. `Apple` only) but to avoid tagify to autoremove the tag, I have to pre-populate the `whitelist` at the same time with at least the saved value (e.g. `[{value: 1, name: "Apple"}]`).
  This could be done, but the numeric value is **not parsed** by tagify and neither its separator (see [this example variation](https://jsbin.com/fezakecoji/1/edit?html,js,output)); in a nutshell `value="1|2"` doesn't work while `value="Apple,Banana"` does.
2. ~Even if we don't consider the previous issue if I start with a **blank whitelist** (like the one in the JSBIN above), type a tag (which is accepted thanks to AJAX) post the form and then I **go back using the browser**, the tag is cleared because the whitelist starts blank.
  In this case I cannot apply #465 because I don't store the tags the user typed... how can this situation be handled? I see that Firefox v91 autocompletion works correctly by keeping the tags, while Microsoft Edge v92 / Chrome v93 when going back displays `1|3` for a brief moment and then the input is cleared of course, due to the empty whitelist.~
  (EDIT: removed and opened a separate thread #898)

- **What is the expected behavior?**
1. Tagify should respect the `originalInputValueFormat` or provide another callback for the inverse function during the initialization. So tagify must be able to convert `1|3` into `Apple, Lemon` on its own using the whitelist (which still I must populate in advance; since it's not possible with AJAX probably I could pull it from the DB during the page initialization).
2. Tagify should implement an event to be handled (like `add`) that is fired only on the initialization of the control? This way I could ask the DB if for example `2|3` are valid tags and then populate the whitelist as a consequence?
  ~Another thing to consider is that you cannot initialize tagify with `enforceWhitelist: false` and then **set it to `true` programmatically**; this would allow to start with `enforceWhitelist` turned off, load the information about the tags and set it to `true` after the whitelist has been populated~.
  (EDIT: use `tagify.settings.enforceWhitelist` to enable it afterward; see [example here](https://github.com/yairEO/tagify/issues/898#issuecomment-926887309))

Sorry for being quite long but I hope it's clear... basically the issues are during initialization of the tag values when using non-standard values (numeric ID instead of the names) and dealing with the browser going back with the input control already filled-in that gets cleared due to the missing whitelist (that cannot be fully loaded).

**Comment by yairEO** [comment]
Sorry this question is very long and I don't have the time to address it thoroughly.

You can try asking in stackoverflow or wait for me to clear some time for this (might take up to a few weeks)

**Comment by virtualdj** [comment]
I'm sorry for having been so long, but I wanted to explain the problem entirely.
Don't worry, take your time and I'll wait: it's a spare time project, after all!

Just focus on the browser history issue, first. I'm pretty sure this is not working correctly due to the fact I want to use an id to identify the inputted tags, but shouldn't this be a possibility?

Thank you very much, obviously!

**Comment by virtualdj** [comment]
Hi, about the browser going back issue (point number 2 on the list above) I did other tests and probably I should have opened a separate issue, because I found it's not related with `originalInputValueFormat` at all.

So, for that, look at #898.
The original question remains for point number 1.

**Comment by yairEO** [comment]
Hi @virtualdj, you can now persist your whitelist & value so it will remain after a form submit or history "back" by doing this:

https://github.com/yairEO/tagify#persisted-data

**Comment by virtualdj** [comment]
I've just tried and it works correctly, thanks!

**Comment by virtualdj** [comment]
@yairEO It's me again, for the same issue, sorry. Strangely, when I tried the example with Tagify 4.8.x I was so excited that it was working when going back that I forgot to check when loading the page "from scratch". 😢 

Now I did it and in **Chrome**:
1. I open my page, add one or more tags, submit the form
2. I go back, my tags are kept with the _localstorage_ (**CORRECT**)
3. I open another different page (optional step)
4. I open the page with Tagify again and the **old tags are there**, pre-filled in the input control (**WRONG** because this should be a **new invocation**, not the history caching)

So, how do I deal with this? Shouldn't the _localstorage_ be trashed when loading the page from scratch?

Checking stackoverflow [HERE](https://stackoverflow.com/questions/829046/how-do-i-detect-if-a-user-has-got-to-a-page-using-the-back-button#comment96594703_45857949), a possible solution could be adding this code into the initialization of Tagify to trash the _localstorage_ if this is not a back/forward (it's not supported by old browsers, but they survived without the cache anyway):

```javascript
function checkBackForward() {
	var perfEntries = performance.getEntriesByType("navigation");
	for (var i=0; i < perfEntries.length; i++) {
		if (perfEntries[i].type === 'back_forward') return true;
	}
	return false;
}

// In your initialization code when you load the localstorage:
if (!checkBackForward()) {
	console.log('Fresh start');
	// Clear the localstorage?
}
```

**Comment by yairEO** [comment]
*"I open the page with Tagify again and the old tags are there, pre-filled in the input control (WRONG because this should be a new invocation, not the history caching)"*

But then you said *"I open another different page"* - which means you should have another Tagify instance with another unique `id`, which would mean the values persisted for one will one appear on the other

**Comment by virtualdj** [comment]
> But then you said _"I open another different page"_ - which means you should have another Tagify instance with another unique `id`, which would mean the values persisted for one will one appear on the other

No, I meant that when changing pages or - if you prefer - just reloading the same page the tags are persisted in any case.
But this should not be the case: the state must be preserved only when doing back/forward, just like any HTML input control.

> You can also clear the value of your Tagify field, when you decide it's best, and the localstorage will be synced

So you're saying I should take care of this on the page that hosts Tagify itself? But then shouldn't I have an API/method that I call to clear the dictionary item that Tagify creates on the localstorage then?
I think this should be care of Tagify itself, like any other HTML input control does.

**Comment by yairEO** [comment]
> No, I meant that when changing pages or - if you prefer - just reloading the same page the tags are persisted in any case.
But this should not be the case: the state must be preserved only when doing back/forward, just like any HTML input control.

So generate a new random ID every time.

When you submit them form and go back, the browser should simply load the page with the same javascript and same random ID. You should probably clear the localstorage-related entries since you will be generating lots of random ones, so use the API provided by tagify for that

**Comment by virtualdj** [comment]
> use the API provided by *Tagify* for that

Which is this *Tagify* API that you're talking about (to clear the stored data)? I'm probably missing it.

**Comment by yairEO** [comment]
It's in the [methods](https://github.com/yairEO/tagify#methods) section, the last one:

## clearPersistedData `String` 

Clears data for the specific instance, by parameter. If the parameter is omitted, clears all persisted data related to this instance (by its id which was set in the instance's settings)

**Comment by virtualdj** [comment]
Sorry, I somewhat missed that! Cool, it works by using the function above and:
```javascript
if (!checkBackForward()) {
	tagify.removeAllTags();
	tagify.clearPersistedData();
}
```

**Comment by jjxtra** [comment]
Using this code, when I reload my page, values are still persisted.

```js
tagify.removeAllTags();
tagify.clearPersistedData();
```
