### ISSUE TITLE
Get current line number in mixed mode

### ISSUE THREAD

**Issue by hubtraum** [yairEO/tagify#887]
Hi,

do you have a suggestion for getting a) the current line number (mixed mode / textarea) of the cursor - or  b) a cursor position offset relative to the entire contents of the tag element (character count like selectionStart in a primitive textarea)?

I want to display the line number and amount of characters in the current line.

Thanks for your help!

**Comment by yairEO** [comment]
No sorry, I don't have a suggestion... 
I suggest asking on stakcoverflow, as I'm a single person and there you will find millions :)

**Comment by hubtraum** [comment]
My intention to ask here was because it's specific to how tagify handles the mixed mode.

Thanks for the hint with getCaretGlobalPosition :)
