### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by gatis-lapsins-visma** [yairEO/tagify#888]
In README is written down if want to use in Internet Explorer, need to add polyfill file. 
Tried, but it's not working. Seems in the min file there are new arrow functions which not supported in IE.
![image](https://user-images.githubusercontent.com/72132408/130017005-9ad6ab4f-301b-4d04-8349-60d545248c27.png)
![image](https://user-images.githubusercontent.com/72132408/130017023-a08c6f01-5415-4dba-9519-1c5434a3c134.png)

Thought maybe I have some problems, but seems the sample page with the newest version does not work too: https://yaireo.github.io/tagify/

Is there a chance that can fix it for IE? :)

**Comment by gatis-lapsins-visma** [comment]
Looked at the source code. Seems >1% rule from browserlist excludes IE11
![image](https://user-images.githubusercontent.com/72132408/130024597-acaebccd-7b83-4c6a-a607-2c0598dab7d5.png)

With current setup:
![image](https://user-images.githubusercontent.com/72132408/130024690-813876c6-4713-4888-a490-bc33a3196ab7.png)

tried with .5% ten ie11 shows, compiles, BUT unfortunately not all functionality then works

**Comment by yairEO** [comment]
As I wrote in the PR you summited, I will not support IE11 any more as it is too difficult to maintain and has super-lower market share, on decline. As I am the sole developer of Tagify and working on it on my spare time, I cannot spare my little free time on an old browser hardly nobody is using... sorry

**Comment by gatis-lapsins-visma** [comment]
@yairEO Sorry to hear because there are products where IE users are more. In our case, there is a pretty huge percent and we need to support IE :( 
BTW would be good to update README, because there is a written, that if you want to use internet explorer, need to include a polyfill file. 
Because in this case
![image](https://user-images.githubusercontent.com/72132408/130211701-6e3b3022-2cde-4a29-b456-6f273f053c30.png)

**Comment by yairEO** [comment]
I will update the README on the next version release
