### ISSUE TITLE
Get 'clean' string representation of mixed value tag input

### ISSUE THREAD

**Issue by urgrund** [yairEO/tagify#892]
Hello,  sorry if this is already a simple thing,  but from looking over options in Tagify I've not found a way to get a 'clean' string representation of a mixed value tag input. 

For example, take the below: 
![image](https://user-images.githubusercontent.com/13104208/130316342-f6d64567-ad7f-4351-8b17-b65bc5629332.png)

So,  DT526 is the tag,  and this all works great.

Though, when getting the 'lastOriginalValueReported'  (because 'value' doesn't include the mixed user input text), we see this 
"[[{"value":"DT526","prefix":"@"}]] is a Truck"  

In our application though, we need provide this in other formats that aren't "tagified" through Tagify, ideally we'd want a string that is:
"DT526 is a Truck" 

Is this something that Tagify provides?  Essentially a way to return the value of a mixed tag and strip all the symbols that Tagify needs leaving just the tag value?   _(similar to what tagify.value does for non mixed inputs)_ 

Cheers!

**Comment by yairEO** [comment]
Hi, this can be done easily using the DOM API itself:

https://jsbin.com/vukiyej/2/edit?html,js,console,output

```js
tagify.DOM.input.textContent
```

**Comment by urgrund** [comment]
Oh, great that works perfectly...   thanks for the quick response,  hope that wasn't a RTFM moment on my part :P
