### ISSUE TITLE
Dropdown is shown off the screen when appended to an element other than document.body

### ISSUE THREAD

**Issue by zoaked** [yairEO/tagify#893]
**Description:**
When `settings.dropdown.appendTarget` is set to any element other than null (which defaults to `document.body`) the suggestion dropdown is hidden off the top or left sides of the screen as a result of calculating a negative number for the top and/or left inline styles.

**Analysis:**
The position is being calculated using [`getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) which returns the element position relative to the viewport.  That number is then manually subtracted from [`getParentsPositions()`](https://github.com/yairEO/tagify/blob/master/src/parts/dropdown.js#L231) and added to the page offset. This results in the position being moved too far by duplicating the parent/page offsets which are already included in the client position. 

**Demo:**
https://jsbin.com/juzerevojo/1/edit?html,js,output

**Comment by yairEO** [comment]
Very good analysis! 

May I know why are you setting `appendTarget`?

**Comment by zoaked** [comment]
Understood, will scrap my efforts to use that setting. It does make me curious as to why it is offered if using it is not recommended and even if you try to it doesn't work anyway.  Perhaps it could be removed? (or at least a note added to the readme as such)

I am afraid that I must be misunderstanding your suggestion as the change event only seems to be fired when a tag is added.  The desired goal would be to hide the dropdown from the start until a search value is entered.  I tried several of the other events (including some from the dom element itself) and those did get triggered, but even after reverting enabled back to false the dropdown was still showing.  The console log shows that the setting change is being kept as seen between events, but my guess is that probably because the dropdown is already opened by that point nothing is checking the setting anymore.

Demo: (I can convert this to plain js if that would be easier for you)
https://codesandbox.io/s/still-cdn-iw90f?file=/src/components/Tags.vue

**Comment by yairEO** [comment]
@zoaked - I will not remove it, it used to work and probably works still, I need to checked. haven't checked that part in a very long time. 

---

> *I am afraid that I must be misunderstanding your suggestion as the change event only seems to be fired when a tag is added. The desired goal would be to hide the dropdown from the start until a search value is entered*

You need to set `settings.dropdown.enabled` with a number other than `0` when *tagify* has no value yet (or value was removed), and then the suggestions dropdown wouldn't be shown when the user inputs text.. and then you can change the `settings.dropdown.enabled` after a tag is added.
