### ISSUE TITLE
Backspace key is broken in select mode

### ISSUE THREAD

**Issue by zoaked** [yairEO/tagify#894]
**Description:**
When `mode` is omitted from settings (allowing multiple tags) the user is able to type in the box and use the backspace key to remove a single char from the end.  In `mode: 'select'` as soon as the backspace key is used the entire value is removed.  

**Additional Notes:** 
- After the backspace key has been hit, no events are triggered to indicate that something has happened (tags added/removed) or the input value has changed.
- When `mode: 'select'` AND `backspace: 'edit'` are used an exception is thrown in the console.  This is unrelated to the above issue, but was something I bumped into when trying to figure out why the whole value was being removed.

**Stack Trace:**
Uncaught TypeError: t is undefined
    s https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8
    editTag https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8
    setTimeout handler*onKeyDown https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8
    binding https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8
    setTimeout handler*show https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8
    onClickScope https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8
    binding https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8
    w https://unpkg.com/@yaireo/tagify/dist/tagify.min.js:8

**Analysis:**
I have not made any progress on figuring out why backspacing in select mode behaves differently from multi-tag mode.  The exception is the result of [`tagElm` being undefined in `tagify.editTag()`](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L419)

**Demo:**
This behavior can be seen on the [demo page](https://yaireo.github.io/tagify/#section-mode-select)
In case it is easier to be able to debug on a live instance: https://jsbin.com/muguqutife/1/edit?html,js,output

**Comment by zoaked** [comment]
Upon further analysis I have additional information to share on these two things.
**Proposal:**
Only [remove the tag after it has been selected](https://github.com/yairEO/tagify/blob/master/src/parts/events.js#L378-L379).  This keeps the ability to remove a tag easily while also being able to resolve typos without having to start over.  @yairEO - do you accept PRs?  I would be happy to put one together if this approach is acceptable.
```js
if (this.settings.mode == 'select' && this.settings.enforceWhitelist) {
	if(this.value.length) {
		this.removeTags();
	}
}
```

**Exception Update:**
The exception is caused by two different events trying to operate on the tag at the same time.
The tag is [removed in this one](https://github.com/yairEO/tagify/blob/master/src/parts/events.js#L379).  Once the input is empty then [another handler tries to edit it](https://github.com/yairEO/tagify/blob/master/src/parts/dropdown.js#L398).  I'm not sure what each is intended to do, but they appear to be very similar so perhaps these could be combined?  If nothing else this can be resolved by negating the condition from the first event handler so the second one ignores it. ` && !(this.settings.mode == 'select' && this.settings.enforceWhitelist)`

**Comment by yairEO** [comment]
Thanks, that's a good idea, I will make the change now.

This whole thing you're experiencing came after a recent change which was [requested here](https://github.com/yairEO/tagify/issues/880)
