### ISSUE TITLE
Image being inserted when doing drag & drop

### ISSUE THREAD

**Issue by sdalu** [yairEO/tagify#895]
From the demo page: https://yaireo.github.io/tagify/#section-extra-properties
drag and drop the country icon from tag (for example Afghanistan flag) to the input field
this result in a big flag being displayed in the input

![Screenshot 2021-08-30 at 14-17-21 Tagify - Tags input Component](https://user-images.githubusercontent.com/1355524/131337732-64b8aaae-bee7-462a-b266-fdb15184fdb5.png)

Would have expected for dragged&dropped html content being ignored

That's even worst if tag can be reordered using drag & drop, as user will tend to reorder by dragging the picture inside the tag

**Comment by yairEO** [comment]
Nice catch. simply add `pointer-events: none;` to the `img` CSS selector to prevent this.

I will investigate how to completely forbid such behavior automatically

**Comment by sdalu** [comment]
it is not limited to pictures present in the input field, dragging image from anywhere result in the same behaviour
