### ISSUE TITLE
Copy tag values from one input to another?

### ISSUE THREAD

**Issue by kwestberg** [yairEO/tagify#897]
I'm using jquery to capture a parent Tagify value, and apply this value to the dynamic children Tagity inputs.  The values are arriving, based on inspecting the child element values.  What i cant figure out is how to get the children to render the new values.  I suspect i need to trigger a change event?  If so, can it happen via a jquery call like $(".children").each() and trigger this visual update?  

Thank you in advance.

**Comment by yairEO** [comment]
I don't understand anything at all.. what parent.. what children... what does "dynamic" children inputs mean...

**Comment by kwestberg** [comment]
I’ll try to clarify.  I’m rendering dynamic text inputs and attaching your Tagify to each.  Works really well, and I’m glad I discovered this jewel of yours.  So for instance lets say five text inputs are rendered.  At this point the user goes to each text input and enters the required tags which are appropriate for that text input.  In some scenarios, the tags required for all rendered text inputs are the same.  So I wired the first rendered text input with a button that copies its values to all children text inputs.  The values are arriving in each text input, based on viewing the element values via F12/devtools.  if the first input had {value: 123, value: abc}, then after clicking my button, all the text inputs now have {value: 123, value: abc}.  The problem is, even though every text input has this copied value, the text input does not visually represent these values, even though each input does have a value.  In short, all the tagify’d inputs that received the new input values are not showing any tags.  Does that make more sense?   I suspect I need to tell tagify to re-render each input, but I am not sure how to go about this.     

And thank you for responding... =]

**Comment by kwestberg** [comment]
This is how im initiating tagify for each input rendered

    document.querySelectorAll(".css_cust").forEach(node => {
        new Tagify(node,
            {
                delimiters: ",",
                pattern: CustomPattern,
                maxTags: maxTags,
                editTags: false,
                blacklist: avoids,
                dropdown: {
                    enabled: 0,
                    maxItems: 5
                },
                callbacks: {
                    add: console.log,
                    remove: console.log,
                    invalid: console.log,
                    edit: console.log
                }
            });
    });

**Comment by yairEO** [comment]
Please also include the button's code which is copying the value

**Comment by kwestberg** [comment]
After entering AAA and BBB in the first text input, i then click a button with the class .COPY_CUSTOM.  The jquery click event is the following:

$(".copy_custom").click(function () {
     var parent = $(".first");
     var val = parent.children("*[data-custom]").val();
     $("*[data-custom]").val(val);
});

After clicking this button, all text inputs now have the following entry in each VALUE property, based on inspecting the elements via F12:
1.	value: "[{\"value\":\"aaa\"},{\"value\":\"bbb\"}]"

But as i stated, the inputs are visually empty except for the first one which i entered the AAA and BBB.

Thank you again

**Comment by yairEO** [comment]
if you are set in input's value **programmatically** you should not expect a `change` event to be fired, as if in a real user input, so it is your responsibility to fire the event.

[See this stackoverflow answer to learn how](https://stackoverflow.com/a/30110477/104380)

**Comment by yairEO** [comment]
Tagify has no notion you updated the value of the `input` tags programmatically. 

You need to run `tagify.loadOriginalValues()` where `tagify` is a variable referencing `new Tagify` for each of your *tagified* inputs.

This will rebuild the tags to match the value.

**Comment by kwestberg** [comment]
forgive me for asking so many questions.  I do appreciate your time.  But i'm at a loss on how to reach each dynamic text input instance of tagify.  I see where during the instantiation where i reference "node" as a variable, but once the init is complete, i do not see how i can reach this variable.
