### ISSUE TITLE
Going back (history) in Chrome doesn't keep input data

### ISSUE THREAD

**Issue by virtualdj** [yairEO/tagify#898]
### Issue
When you **post the data** of the form that contains the Tagify `input` element, if you **go back** with the browser after posting the control **content is not persisted** when using Chrome (while it works with Firefox).

### 💥 Demo Page (your original/unmodified Codepen link)
It's not demostrable using Codepen only, as there must be a `<form>` element inside, anyway it happens also with your original Codepen link here:

https://codepen.io/vsync/pen/OJNVyQR

### Steps to reproduce

1. Download the HTML from the Codepen link above
2. Edit the HTML file, enclosing the `<input>` element in a form and adding a Submit button. So:
```html
<body translate="no" >
<form method="get" action="not-exists"> <!-- ADDED LINE -->
  <input name='tags'
  class='some_class_name'            
  placeholder='write some tags'      
  value='css, html, javascript, css' of Objects)
  data-blacklist='.NET,PHP'>
 <input type="submit" value="Submit"> <!-- ADDED LINE -->
</form> <!-- ADDED LINE -->
    <script src [...]
```
3. Open the modified page in **Firefox**, type some tags, push the Submit button (it leads to an error of course) then go back. Your tags are still there. **CORRECT**
4. Do the same with **Chrome**: after going back, the typed tags are not there and they're replaced with the `<input>` element original values. **WRONG**

### Video demonstration

![Go back: Firefox works, Chrome does not](https://user-images.githubusercontent.com/3251704/132095211-e9e85f7f-68e3-49bb-b1b8-1af42d0cd020.gif)

**Comment by yairEO** [comment]
seems like a chrome-thing as it seems to fill the value (when going **back** in history) with a slight delay *after* the page has been rendered while FF will keep the values before the page is rendered.

I will place a slight delay when tagify is initialized to bypass this unwanted behavior and allow the `value` property time to be re-filled by the browser

**Comment by yairEO** [comment]
Because they are not in the whitelist, and you probably have `enforceWhitelist` setting set to `true`...

just add them to the whitelist when you first initialize Tagify (read the input's `value` for that)

**Comment by yairEO** [comment]
I see. 

use a `setTimeout` because Chrome has a bug that the input's value is not readable at the second of going "back" in history:

```js
var inputElm = document.querySelector('input[name=tags]'),
    whitelist = ["A# .NET", "A# (Axiom)", "A-0 System", "A+", "A++", ...

// initialize Tagify on the above input node reference
var tagify = new Tagify(inputElm, {
    enforceWhitelist: true
})

setTimeout(() => {
	// get input value as an array 
	const tagsArr = inputElm.value.trim().split(/\s*,\s*/) 
    // add to whitelist
    tagify.whitelist = tagsArr 
    // now can be added as tags (because of "enforeWhitelist"...)
    tagify.loadOriginalValues(tagsArr)
})
```

I am thinking about simply adding the tags to the whitelist automatically when the `loadOriginalValues` method is called, and this save you the trouble of this whole above thing. I just need to think what might be the consequences of modifying `loadOriginalValues` since it's used by everyone.

**Comment by virtualdj** [comment]
> I am thinking about simply adding the tags to the whitelist automatically when the `loadOriginalValues` method is called, and this save you the trouble of this whole above thing.

Yep, this is what I was saying initially on #885, in fact. That was a similar issue: when you're using `originalInputValueFormat` you are translating a string (e.g. `Apple, Lemon, ...`) into a number with a custom separator (e.g. `1|3|...`) and setting this output on the HTML input control value.
But when you go back, Tagify is not able to interpret the string (because there's not a `originalInputValueFormat` inverse function) and so it is thrown away due to `enforceWhitelist: true`. I took this occasion to explain that issue, too.

> I just need to think what might be the consequences of modifying `loadOriginalValues` since it's used by everyone.

Of course! But unfortunately this is **necessary**, because I don't think throwing away the input is something correct, when going back on the browser.

**Comment by yairEO** [comment]
> when you're using `originalInputValueFormat` you are translating a string (e.g. `Apple, Lemon, ...`) into a number with a custom separator (e.g. `1|3|...`) and setting this output on the HTML input control value.

I think this can only be solved on the implementation side and not Tagify, because after going back in history, the original input is again "tagified" (creating a *new* Tagify instance) and it does not know anything about the data which lead to the output of `originalInputValueFormat` (as numbers) - just like you said - there is no backward `originalInputValueFormat`. It would be impossible, like create a whole egg back an omelet.

You can set unique ids to your tagifed inputs and save the "real" data in your localstorage so later, if *history* goes *back*, you will be able to restore the tags from that data.

Tagify cannot create a unique id that persists between page refreshes, as its instance is re-created every time from scratch.

**Comment by virtualdj** [comment]
> Tagify cannot create a unique id that persists between page refreshes, as its instance is re-created every time from scratch.

Of course, but wouldn't be possible, for example, to **optionally delay** the validation of the tags at startup until the developer has received the whitelist from AJAX? For example, optionally starting with `enforceWhitelist: false`, waiting the AJAX whitelist and inside the callback setting `enforceWhitelist: true` so that Tagify can trash the wrong tags only after that moment?

This would allow, probably, to handle the `1|3|...` case too, as during the first call the developer could parse the input manually and reload the tags matching them with the Whitelist (i.e. calling `loadOriginalValues`).

**Comment by yairEO** [comment]
Tagify cannot know when the ajax call will be ready. only you. therefore you should set your setting to `enforceWhitelist: false` by yourself and then wait for the call to finish and change it back to `true` after you update your whitelist

**Comment by virtualdj** [comment]
Yes, but is changing `enforceWhitelist` from `false` to `true` at "runtime" supported officially? Last time I tried I wasn’t sure it was working...

**Comment by yairEO** [comment]
yes, you can change the setting. `tagify.settings.enforceWhitelist = ...`

**Comment by virtualdj** [comment]
Ah, I missed the `.settings` property, then! I confirm it works by setting `enforceWhitelist` to `false` at startup and then toggling to `true` only when the AJAX whitelist has arrived.

By the way, please let me know when you plan to fix [the Chrome issue above](https://github.com/yairEO/tagify/issues/898#issuecomment-924697702) to make Firefox and Chrome/Edge behave in the same way.

**Comment by yairEO** [comment]
@virtualdj - in what way "same way"? what is the problem now?

**Comment by virtualdj** [comment]
The same discussed above: when going back with Chrome/Edge, tags are cleared when using `enforceWhitelist` (you talked about `loadOriginalValues`).

**Comment by yairEO** [comment]
most apps today use a framework or something like *React*, so this is not an issue there, but is only for webpages which are built without any framework

**Comment by virtualdj** [comment]
> but is only for webpages which are built without any framework (which I believe are a small percentage)

In fact I'm using it in a plain javascript webpage. I'm not saying it's an insufferable issue, but it would be great to have Chrome to behave in the same way, without the "hack" of enabling and disabling `enforceWhitelist` at startup.

**Comment by yairEO** [comment]
I don't know how Firefox is doing it, since `enforceWhitelist` is `true` (in your case) so when going back (in history) your `whitelist` array is empty so the value of the field, which will become *Tagified* will be invalid and the tags removed at-once.

**Comment by virtualdj** [comment]
I think Firefox is keeping its HTML control state with the "autocomplete", maybe while Chrome does not.
Also, when going back, I noticed that **Firefox doesn't run the initialization script**, while Chrome does... that's why it doesn't remove the tags.

If you try to add this line:
```javascript
// initialize Tagify on the above input node reference
alert('Init'); // <-- ADD THIS LINE
var tagify = new Tagify(inputElm, {
```

and open the page with Firefox, then go back, the popup doesn't show. If you do the same with Chrome/Edge, when you go back, the popup shows.

Apparently the only working method to detect the browser "go back" action in Firefox is attaching to the `window.onpageshow` event.
