### ISSUE TITLE
Whitelist support id and value!

### ISSUE THREAD

**Issue by ElvenDev** [yairEO/tagify#9]
This might be harder (and not sure if possible), but if you could add into a white list of arrays ($id => $label) or something similar would be cool.

That means: In tag lists, it will add and show a label, but when saved, the input will save/use the actual set id.

This is a necessary feature if this project is used in larger databases OR there are the possibility of two same name strings.

**Comment by yairEO** [comment]
I strongly think such a map should not be done within the `tagify` script but in your own server or in the AJAX function which send the data to the server, 

Thanks for liking my plugin! :)
