### ISSUE TITLE
Suggestion: Autocomple with Tab

### ISSUE THREAD

**Issue by melenaos** [yairEO/tagify#90]
I beleve that most autocompletes work with the press of tab and it would be nice for the tagify to have this.

There are two problems with this:
- If you capture Tab and autocomplete the tag then the focus goes to the next control. This is not acceptable because you most probably want to continue adding tags.
- If you `preventDefault()` on keypress of Tag then you won't be able to navigate using Tab. Not acceptable also.

To make this work you have to test if the tag autocomplete is at suggestion mode:
```
autocomplete: {
   suggest: function suggest(s) {
      //.....
   },
   set: function set() {
      //.....
   },
   hasSuggest: function hasSuggest() {
      return this.DOM.input.getAttribute('data-suggest');
   }
}
```

And only then `preventDefault()` and `automplete.set()`

```
onKeydown: function onKeydown(e) {
   if(...)
   else if(...)
   else if ((e.key == 'ArrowRight' || e.key == 'Tab') && this.input.autocomplete.hasSuggest.call(this)) {
      e.preventDefault(); //keep cursor focus on the tag
      this.input.autocomplete.set.call(this);
      }
}
```

Something similar might have to be in dropdown too but I am not sure if you need the same Tab functionality there.

**Comment by Ranitzky** [comment]
Cool, this works for me, after changing the callback

````
case 'Tab': //add this
case 'Enter':
   e.preventDefault();
   newValue = selectedElm ? selectedElm.textContent : this.input.value;
   this.addTags(newValue, true);
   this.dropdown.hide.call(this);
   break;
````

**Comment by yairEO** [comment]
In web forms <kbd>Tab</kbd> is used to skip between the form items, and since *Tagify* was meant to transform a simple input/textarea tag into something browsers don't support, it is still in essence a form element (of a custom type) and therefore I think it is best to keep the *Tab* logic as it is

**Comment by yairEO** [comment]
I will re-consider this because others have asked (#106), but only if it will be possible to hit the <kbd>Tab</kbd> button without loosing focus, because it's **important** to keep the flow within the input field so the user could write more tags _without manually_ having to focus on the input again.

**Comment by melenaos** [comment]
If you use the code you will see that:
- When you input a tag and press tab it autocomples the tag and it's ready to input the next tag
- When you are not inputting a tag it goes to the next.

**Comment by yairEO** [comment]
Done. You can now use <kbd>Tab</kbd> to autocomplete

**Comment by melenaos** [comment]
Great!

**Comment by dehghani-mehdi** [comment]
@yairEO 

> Done. You can now use Tab to autocomplete

How?

**Comment by dehghani-mehdi** [comment]
@yairEO 

> Done. You can now use Tab to autocomplete

How?

**Comment by simon-zk** [comment]
Tab didn't work for me, so I found this solution. Maybe will be helpful for someone

```
tagify.on('keydown',function(e){
    if( e.detail.event.keyCode == 9 ){

        tagify.DOM.input.dispatchEvent(
                new KeyboardEvent('keydown', {keyCode:13, which:13, code:'Enter', key:'Enter', bubbles:true})
        );

    }
})
```

It listens for Tab keydown on the input and triggers Enter key. So basically you're just pushing Enter with Tab.
