### ISSUE TITLE
Removing Tagify-DOM onChange in select-mode with mouse-click = warning in console

### ISSUE THREAD

**Issue by Tagirijus** [yairEO/tagify#900]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/timepojiwe/1/edit?html,js,console,output

### Explanation

- I have the Tagify in `"select"` mode. I want the whole element _(the div with the id 'delete_me')_ to be removed completely after selecting an element from the Tagify instance.

- The element is being remove without any warnings, when I select the tagify item via keyoard by pressing enter. **But** if I select the item with my mouse, a warning comes up.

- Following warning message comes up in the console:

```
Error: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at https://unpkg.com/@yaireo/tagify:8:36709
    at Array.forEach (<anonymous>)
    at w.setRangeAtStartEnd (https://unpkg.com/@yaireo/tagify:8:36695)
```

Thanks for your help! (=

**Comment by minhlong** [comment]
Me too,

**Comment by yairEO** [comment]
Do it inside a `setTimeout`:

```js

tagify.on('change', () => {
    setTimeout(()=>{
      var remove_me = document.getElementById('delete_me')
      remove_me.remove()
    })
})
```

**Comment by Tagirijus** [comment]
This works, thanks for the workaround ... and thanks for the "fixing" commit! (=
