### ISSUE TITLE
Losing textarea style information when initialising tagify

### ISSUE THREAD

**Issue by lee-matthews** [yairEO/tagify#901]
Hi,

I used the following textarea config : 

`
<textarea id="test_report" name="test_report" style="resize: vertical; min-height: 100px;" ></textarea> 
`

I notice that when I load the page, it appears briefly as one would expect, then it loses the style when tagify is called on the element. I initialise tagify as  follows : 

```
   var input2 = document.querySelector('[id=test_report]');

    // init Tagify script on the above inputs
    tagify = new Tagify(input2, {
        mode             : 'mix',  // <--  Enable mixed-content
        pattern          : /@/,  // <--  Tag words which start with @ or # (can be a String instead of Regex)
        enforceWhitelist : true,
        whitelist        : whitelist,
        duplicates       : true,
		setReadonly		 : true,
		editTags		 : false,

        dropdown   : {
            enabled : 1,
			searchKeys: ["value"]
        },

        callbacks        : {
            add    : console.log,  // callback when adding a tag
            remove : console.log   // callback when removing a tag
        }
    });
```

When I look at the html after tagify has been initialised, I notice that

```
<tags class="tagify tagify--mix tagify--noTags tagify--empty" tabindex="-1">
            <span tabindex="0" data-placeholder="​" aria-placeholder="" class="tagify__input" role="textbox" aria-autocomplete="both" aria-multiline="true" contenteditable=""></span>
        </tags>
        <textarea id="test_report" name="test_report" style="resize: vertical; min-height: 100px;"></textarea>
```

That my textarea is a child of <tags class="tagify tagify--mix tagify--noTags tagify--empty" tabindex="-1">
That the textarea has kept the style information, even though it isn't taken into account.

Do I have to modify the parent of the textarea for my textarea to display correctly?

I tried doing this but I have no way of knowing when tagify() has finished initialising and when I try to modify the parent of textarea, the tagify html element doesn't yet exist. Is there a callback available that is called when tagify() has finished setting up the element?

I'm testing this on firefox 92.0 with the version of tagify that is read directly from a CDN as described in the instructions.

Can you help?

Thanks in advance.
Lee

**Comment by yairEO** [comment]
Hi Lee. The **original** input/textarea will be hidden once *Tagify* is applied, since they cannot co-exist, as Tagify is a component which masks the plain & simple original input with a complex new component and they are both in sync, behind-the-scenes.

Therefore your styles on the original input will not be visible since that element is not rendered.

You can see this by inspecting the original element with your *devtools*
