### ISSUE TITLE
How to validate a Select2?

### ISSUE THREAD

**Issue by sebasira** [yairEO/tagify#904]
I have a problem when using Select2. When the "bad" class is applied, there's no red-border applied to the select tag. I think it has to be with the inner classes of the Select2, that has a lot of **!important** but I do not know how to solve it

I also think that this could help [Styling jQuery Validation with Select2 4.0 and Bootstrap 3+](https://stackoverflow.com/questions/30783019/styling-jquery-validation-with-select2-4-0-and-bootstrap-3) but I do not know how to apply it.

I've also try with [select2-bootstrap-theme](https://github.com/select2/select2-bootstrap-theme) but still the same.

I hope you could help me! Thank you!

**Comment by sebasira** [comment]
I've managed to workaround the issue by modifying the style, by adding the selector **.bad span.select2**, like this:

```css
.bad input,
.bad select,
.bad textarea,
.bad span.select2{
```

But it's kind of ugly

**Comment by yairEO** [comment]
what does this has to do with Tagify? this is no `bad` class name in Tagify

**Comment by sebasira** [comment]
My bad! I post it in the wrong repo... it was suppose to be in the validator
