### ISSUE TITLE
HtmlFormElement's reset function does not reset the tagify's <tags> elements

### ISSUE THREAD

**Issue by krishraghuram** [yairEO/tagify#905]
HTMLFormElement has a [reset method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset). However, on calling this, only the original input element is reset, and the tagify's `<tags>` element is not reset.
Demo: https://jsbin.com/qejabivodu/2/edit?html,js,output

Currently my workaround is to listen for the [reset event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event) on these forms, and manually call tagify's `removeAllTags` method. But it would be best if this can be done by tagify itself.

**Comment by yairEO** [comment]
Great idea. just implemented and will be released in the next version (soon!)
