### ISSUE TITLE
Mix Text & Tags Working Only One Line

### ISSUE THREAD

**Issue by Shadecute** [yairEO/tagify#906]
I want use Mix Text & Tags in a laravel project, in textarea this [code](https://codepen.io/vsync/pen/KKzpdxQ) worked only for 1 line. 
<img width="860" alt="Screen Shot 2021-09-16 at 11 53 08 AM" src="https://user-images.githubusercontent.com/14329470/133570110-1ff7848e-15a3-4a33-a3a2-cd668c0a8ec9.png">

If inter is used, the next lines will not be recorded anymore

my database:
<img width="1018" alt="Screen Shot 2021-09-16 at 12 06 20 PM" src="https://user-images.githubusercontent.com/14329470/133570389-4ccd80e9-b615-4727-8877-872676daa32d.png">

**Comment by yairEO** [comment]
This should be fixed in the upcoming release (probably tomorrow)
