### ISSUE TITLE
Hitting enter/click-select in select mode prevents tabbing afterwards

### ISSUE THREAD

**Issue by Tagirijus** [yairEO/tagify#907]
Hey there,

when I use a tagify in _select_ mode and I chose an item by pressing enter or clicking it somehow prevents tabbing afterwards. So for example: I will chose any item from the list by selecting it with the arrow key and pressing enter _or_ I select it with the mouse and click it. And then I cannot tab to any other GUI element on the page anymore.

This does not happen, when I select an item from the select-list by **Tab**.

I was nto sure, if this might be a bug; that's I wanted to start a FR instead. Thank you! (=

**Comment by yairEO** [comment]
same as #903

**Comment by Tagirijus** [comment]
Ouch ... I am so sorry for not finding this issue ... also it was opened only ONE day before mine ... how could I miss this ... sorry. Thanks for the link to the other issue and for closing this one then!
