### ISSUE TITLE
Typing manually leads to different result than choosing from dropdown

### ISSUE THREAD

**Issue by krishraghuram** [yairEO/tagify#908]
#### Problem
When `tagTextProp` and `dropdown.mapValueTo` are set, then choosing a tag from dropdown leads to different behavior than typing. Please watch the demo video to understand what is "different behavior".

Demo Video: https://youtu.be/JeAgAjNUrag
Demo Link: https://jsbin.com/kijatoyilo/1/edit?html,js,output

#### Expected behavior
When typing `hello` manually, the value in the input should be `[{"name":"hello","value":"1"}]`, and not `[{"name":"hello","value":"hello"}]`. That is, when typing a `name` that is already present in the whitelist, then the `value` should be picked up from the whitelist. When typing some `name` that is not present in the whitelist, then the `value` can be set the same as `name`.

####  Additional Notes
* The demo shows a select mode input, but the issue can also be seen in normal mode.
* The issue can also be seen when `enforceWhitelist` is set to true (for both select mode and normal mode).

**Comment by krishraghuram** [comment]
Update:  Adding `searchKeys:["name"],` to the settings fixed the issue. I'm guessing that this is the expected behavior...?

Small Request: Can you update the documentation for `tagTextProp` to something like,
```
Tag data Object property which will be displayed as the tag's text. Remember to keep "value" property unique.
See Also: dropdown.mapValueTo, dropdown.searchKeys
```

**Comment by yairEO** [comment]
it is the expected behavior indeed
