### ISSUE TITLE
Delete removes previous item when there are extra spaces

### ISSUE THREAD

**Issue by jonsgreen** [yairEO/tagify#910]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/jekuqap/edit?html,js,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- **What is the expected behavior?**

With the default setting for `backspace` set to `true`,  if you have added space after a tag, then the backspace/delete button should remove the whitespace and only delete once there is no whitespace left. Only at that point should it remove the previous tag. 

- **What is happening instead?**

When there are tags selected and you hit the space bar one or more times and then press the backspace the previous tag gets deleted immediately

- **What error message are you getting?**

**Comment by yairEO** [comment]
I will fix this at once, thanks for reporting

**Comment by jonsgreen** [comment]
@yairEO Thanks for jumping on this one so quickly; sorry it has taken me this long to test the fix. I am actually finding that the behavior I was trying to address is still there. If you enter a tag and then use the space bar one or more times then whenever you hit the delete key it still deletes the previous tag. I would want the tag to only get deleted once the cursor is right next to the tag. 

Let me know if that is still considered buggy or expected behavior and whether there is anyway that I can help.

**Comment by yairEO** [comment]
@jonsgreen - Hi, don't worry, I read everything, but sometimes in a delay. I will fix this.

**Comment by jonsgreen** [comment]
@yairEO I still seem to have the problem. I wonder if it could be dependent on the operating system? I am on a Mac. Here is a recording using your demo app. I am assuming you are using the latest version there but regardless I get the same behavior using version 4.8.1 on my app as well:

https://user-images.githubusercontent.com/3073/136790528-0289b8c8-4ad8-4222-b9d4-8a8d38264b1e.mov

**Comment by jonsgreen** [comment]
I am curious if you were ever able to reproduce this behavior @yairEO on a Mac?

**Comment by jonsgreen** [comment]
@yairEO I thought I would check in one more time. This is by no means a mission critical issue for us but I am moving off of the project for a while and want to close out my loose ends. Were you ever able to confirm this issue on a Mac?

**Comment by yairEO** [comment]
Hi sorry for the delay, was super busy. I see it now again and will work on it hopefully today/tomorrow
