### ISSUE TITLE
Ability to completely disable animation

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#912]
I have a few tabs and some of them have tagify on them. When switching tabs, the content of the new tab renders immediately but has the tagify data from the previous tab showing up for a second or so before disappearing. The attached video shows this problem.

I tried setting --tag-hide-transition to 0s but that didn't work for this case. While the animation is usually good, there are cases like this tabs where it feels awkward. It would be good to have an option to turn off the animation completely.

https://user-images.githubusercontent.com/2200491/134786695-a023067f-81a3-43d6-a187-b0889acbc351.mov

.

**Comment by yairEO** [comment]
isn't each tab content has it's own HTML (own unique tagify component)?

I cannot help much without seeing this live

**Comment by dirslashls** [comment]
Thanks @yairEO , I solved it by setting z-index of the tabs. To answer your question, yes, each tab has its own html with its own unique tagify component.
