### ISSUE TITLE
Unit testing tagify

### ISSUE THREAD

**Issue by millertn** [yairEO/tagify#913]
Hello, I'm attempting to set up some unit tests for tagify. I can't quite find the right events to trigger on the right elements programmatically to simulate a user entering a value into the input and the dropdown values updating accordingly, any thoughts or ideas? I'm using Jasmine in the Aurelia framework and any help would be greatly appreciated!

**Comment by yairEO** [comment]
why are you bothering? I'm constantly changing the code and your tests will be out-of-date every now and then... also, as this is a browser-based code, there is no meaning to unit-testing, only to behavior-testing, which I did not do as there are hundreds of test-cases to create and I have other things to do (only one person with one life, no time to write hundreds of test-cases)

**Comment by millertn** [comment]
Maybe there was a miscommunication but I was not asking or implying that you or I need to create behavior tests for your library, I'm aiming to make tests to make sure my instances of tagify are working properly in tandem with my code for every implementation I am using it in. There is value in knowing our implementations of tagify are failing regardless of why so we know to fix them before that code hits production. All I was asking about was how to simulate user interaction with your library programmatically

**Comment by yairEO** [comment]
But this is not unit-testing. Unit-testing is for logical code and not browser-based (DOM-based) code. There is no logic here, only DOM operations, which should be tested in a browser (or headless-browser) env

Maybe this will be helpful to you:
https://www.testim.io
