### ISSUE TITLE
Apostrophes In Tags

### ISSUE THREAD

**Issue by fuzeboxsoftware** [yairEO/tagify#914]
I am not seeing any options or sure what even to utilize to add apostrophes to tags. They will show in the dropdown of the whitelist but in the preview and upon selection, show the HTML code and then rejects the tag selected. How does one get around this? Thanks in advance for the help!

**Comment by yairEO** [comment]
Please post some code, or even better, and a jsbin that showcase the issue (like was asked in the issue template)
