### ISSUE TITLE
Show hidden text if type after the focus change

### ISSUE THREAD

**Issue by younaAnn** [yairEO/tagify#917]
Reproduce steps: 
1. Enter several tags in the field
2. Press "Tab" and then type a new value

Actual result: exsisted tags disappeared, new tag with value "[{"value":"dh"}]new value" appeared

![image](https://user-images.githubusercontent.com/79164616/137160470-1941a8c9-227c-478b-ad50-5dcd7a6385a9.png)

**Comment by yairEO** [comment]
You are not supposed to press tab and edit the underlying (hidden) input field which is synced with Tagify. 

You are supposed to only work with the Tagified field and not the original.
