### ISSUE TITLE
Input is enabled in disabled mode

### ISSUE THREAD

**Issue by ykchong45** [yairEO/tagify#920]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
In the project's [demo page](https://yaireo.github.io/tagify/#section-disabled).

### Explanation
In disabled mode, I can click on the empty area to input more tags.

- **What is the expected behavior?**
- The input should not be focused when it's in disabled mode.

- **What is happening instead?**
- The input is focusable.

**Comment by yairEO** [comment]
Thanks for reporting!

**Comment by gidzr** [comment]
I've noticed that the tagify input dropdown is still active when disable is applied via .prop() in jquery version, and is only disabled when added using attr() instead.

**Comment by yairEO** [comment]
Because `prop` and `attr` are doing completely different things.
