### ISSUE TITLE
Distribute non-minified code on NPM

### ISSUE THREAD

**Issue by tobiasdiez** [yairEO/tagify#924]
The npm package currently only distributes the minified js file. This makes it very hard to debug problems that might occur and may lead to problems when a minified code is again minified. Also if you use a package manager, chances are high that you also use a build tool/bundler that minifies the code anyway (like most projects based on react or vue).

**Comment by yairEO** [comment]
Ok I will do that

**Comment by morrow95** [comment]
Second this... the way I have my project setup it will try to minimize the file even though its already minified and ends up breaking the file somehow.  Didn't realize what was wrong till I tried the file directly and it worked fine.
