### ISSUE TITLE
Don't trigger onChange event for loadOriginalValues

### ISSUE THREAD

**Issue by tobiasdiez** [yairEO/tagify#925]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
   `loadOriginalValues` don't trigger any change events.
- **What is happening instead?**
   It triggers a change event
- **What error message are you getting?**
  No error message, but no expected behavior.

In `loadOriginalValue`, 
https://github.com/yairEO/tagify/blob/23c7e3caf1efb791775e9b073adebc79b1f4f2ab/src/tagify.js#L290
correctly prevents the trigger of the changed event. However, it also calls
https://github.com/yairEO/tagify/blob/23c7e3caf1efb791775e9b073adebc79b1f4f2ab/src/tagify.js#L308
and in `addTags` there is
https://github.com/yairEO/tagify/blob/23c7e3caf1efb791775e9b073adebc79b1f4f2ab/src/tagify.js#L1247
which nonetheless trigger a change event.

**Comment by yairEO** [comment]
Why does it matter if `loadOriginalValues` is triggering a change event? is it that bad in your system?

**Comment by yairEO** [comment]
I will see what can be done, sorry I completely forgot about this

**Comment by tobiasdiez** [comment]
Thanks, seems to work very well. Have a nice weekend!

**Comment by tomlazersheep** [comment]
Hi, sorry to re-open this, but I actually need `change` to trigger when `loadOriginalValues` run. Is there any way to trigger it manually? @yairEO
