### ISSUE TITLE
Duplicate checker is checking tags by case insensitive.

### ISSUE THREAD

**Issue by chjcken** [yairEO/tagify#929]
Hi yairEO,

I recently realize that the duplicate checker of tagify is checking tags by case insensitive and sometimes it filters out my intended tags. In my case, my tags are artist (rapper, singer...) nickname, and they could be the same with other and just different by 1 character capitalized

Can you add another flag in setting (ex: duplicateCaseSensitive:true) to make the checker check tags by case sensitive (I mean check tags duplicate by exactly what they are)?

You can test in tagify demo page 2 tag: All in one, all in one

Thank you

**Comment by yairEO** [comment]
I will work support for optional case-insensitive `enforceWhitelist` setting

**Comment by yairEO** [comment]
This can be done with this setting:  `dropdown.caseSensitive`


[Demo](https://jsbin.com/durabem/edit?html,js,output)
