### ISSUE TITLE
Problem with transformTag and validate

### ISSUE THREAD

**Issue by Cagilisto** [yairEO/tagify#932]
I'm using tagify to handle a list of phonenumbers input by a user. Some users write phonenumbers with spaces grouping the numbers, and I'm normalizing the numbers by removing spaces. This works fine, but it seems to happen after validation, so the duplication check doesn't match if you write the same number again with spaces.

I couldn't find anything in the documentation or examples on how to solve this. Is there a way to do the transformation before the duplication check?

**Comment by yury-kozlov** [comment]
@yairEO Seems there's a similar issue happening when I edit a tag:
1. define handler to remove spaces: 
```js
settings.transformTag = (tag) => { tag.value = tag.value.replace(/ +/g, '')}
```
2. add some tag, for example: `123`
3. double click on the tag and change it to `1 2 3` (with spaces), press enter
4. custom handler is invoked (spaces are removed from the tag, value in UI remains the same), but the tag is marked as duplicate ('already exists')
5. as a result, I can't finish editing the tag unless I change it to some different value or manually remove the spaces

**Comment by yairEO** [comment]
@yury-kozlov - Thanks, I will in investigate
