### ISSUE TITLE
Add tag button next to tag text

### ISSUE THREAD

**Issue by bennetsadyba** [yairEO/tagify#935]
Hi,

is it possible to add a tag by clicking a button?
In order to add a tag one has to either press enter key after typing the tag or click outside the text. 
Is it possible to add a tag by clicking a button which is next to the text one has just entered?

It might be useful especially for mobile users.

**Comment by virtualdj** [comment]
It depends on the separator: if you set `,` as a tag separator, then mobile users could type `tag1, tag2,` and they will be added.

**Comment by yairEO** [comment]
You can create a button that does nothing so when clicking it, the *tagify* field will loose focus and so the tag will be added.

**Comment by bennetsadyba** [comment]
> 
> 
> You can create a button that does nothing so when clicking it, the _tagify_ field will loose focus and so the tag will be added.

works great, thanks for your help!
