### ISSUE TITLE
Clicking the dropdown on mobile clicks on elements placed under the dropdown

### ISSUE THREAD

**Issue by bobluppes** [yairEO/tagify#936]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/boxabet/edit?html,js,output

### Explanation
Selecting a suggested tag from the dropdown works fine on desktop. On Android firefox (possibly other browsers as well but have not tested so far), clicking the suggested tag clicks on buttons that are placed under the dropdown.

- **What is the expected behavior?**
Clicking a suggested tag in the dropdown selects that tag instead of triggering a click event on the elements below the dropdown.

- **What is happening instead?**
Click event of elements below the dropdown is triggered.

- **What error message are you getting?**
None

**Comment by yairEO** [comment]
Thanks for reporting. What am I supposed to see in the demo page?
Are you sure you put the correct link? There are no `console.log` calls and no events anywhere, and the Tagify field works as expected on Android Chrome
