### ISSUE TITLE
Focus lost when using Type-ahead-find plugin for Chrome

### ISSUE THREAD

**Issue by gdandersson** [yairEO/tagify#937]
I have the Chrome plugin Type-ahead-find installed and that takes all input whenever trying to use Tagify. Tried both on my own setup and your demo page.

For "normal" inputs (input, textarea, select) this does not happen.

**Comment by yairEO** [comment]
I don't understand anything

**Comment by gdandersson** [comment]
Step 1. Install the plugin "type-ahead-find" on Chrome
2. Go to any site using Tagify
3. Click any Tagify-box/select
4. Start typing

Tagify isn't recognized as an input field, so "type-ahead-find" receives the keys entered.

**Comment by yairEO** [comment]
ok but I cannot do anything about this... maybe you should open an issue for this plugin?

**Comment by gdandersson** [comment]
That makes more sense that I'm ok with admitting.. ;)

It was submitted and a patch has been released. Thanks for pointing out the obvious!
