### ISSUE TITLE
Microsoft Edge: Page not Responding occurred when the input is back on focus on the 2nd time

### ISSUE THREAD

**Issue by vanessawpy** [yairEO/tagify#94]
Note: the following issue can be replicated only on Microsoft Edge. Works fine in chrome. 

The following are the steps to replicate the issue.
1) on Microsoft edge, navigate to "https://yaireo.github.io/tagify/"
2) on the first text input, key in "python"
3) click on anywhere outside the text input
4) click on the text input again. the page will become not responding.

**Comment by yairEO** [comment]
I cannot test on Edge.. I don't have the browser available to me. But everything does work fine on IE11.. 

currently I will have to put this investigation on hold, because I don't have a paid account on BrowserStack...sorry

**Comment by lordmikefin** [comment]
I'll try to publish my fix today.

**Comment by lordmikefin** [comment]
I send issue to Micro$oft:
[M$ issue 18787906](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18787906/)

Go and write comments there to complain about this issue ;)
