### ISSUE TITLE
How to enable drag & sort in React

### ISSUE THREAD

**Issue by gl0dt** [yairEO/tagify#941]

**Comment by gl0dt** [comment]
Hi yairEO,

I'm using Tagify in a React app and I'm trying to enable drag&sort for <MixedTags />, I've tried to play around with the react example you provided by moving the relevant code from CrazyTags.jsx to MixedModeTagify.jsx, but couldn't make it work. Could you help clarify if Drag&Sort is supported in Mixed Mode at all? If so, could you provide an example?

Thanks a lot for helping

**Comment by yairEO** [comment]
Hi, no, d&d isn't supported in *mixed-mode*
