### ISSUE TITLE
Double quotes not parsed correctly for value and title properties in mixed mode

### ISSUE THREAD

**Issue by gl0dt** [yairEO/tagify#942]
Hi yariEO,

I parse string that has XML tags with regex and generate a tag JS object and then wrap it with "[[]]" for Tagify.
For example, this string
`This product arrives every <ph id="1" disp="{number}"/> months.`
after processing would become
```XML
This product arrives every [[{"value":"<ph id=\"1\" disp=\"{number}\"/>", "type":"ph","display":"1","readonly":true,"title":"<ph id=\"1\" disp=\"{number}\"/>"}]] months.
```

Both `value` and `title` properties within the `[[]]`are not parsed correctly and causing the tag to break. I can fix the double quotes within `value` by inserting two backslashes like `<ph id=\\"1\\" disp=\\"{number}\\"/>`, however this doesn't work for title.

Wondering if you have a workaround for this issue, really appreciate the help

Attaching my tagify tag object generator code for reference

```JS
const tags = [];
string.replace(/<ph[^>]*\/>/g, (match) => {
      //create tag object
      const tag = {
        value: match
        type:'ph',
        display: (tags.length + 1).toString(),
        readonly: true,
        title: match,
      };
      tags.push(tag);
      return '[[' + JSON.stringify(tag) + ']]'; // replace match with tag object
    });```

**Comment by yairEO** [comment]
if your `title` is the same as your `value` then please remove the `title` property or better escape it like so:

```js
'"foo"'.replace(/"/g, "&quot;")   // '&quot;foo&quot;'
```
