### ISSUE TITLE
Readonly Tag Can be Deleted

### ISSUE THREAD

**Issue by gl0dt** [yairEO/tagify#943]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/zuyifov/2/edit?html,js,output

### Explanation

- **What is the expected behavior?**
Readonly tags should not be deleted
- **What is happening instead?**
Readonly tags can be deleted if I click on the tag first and then press 'Backspace' but not 'Delete'

**Comment by henkealg** [comment]
I am currently working on an implementation of Tagify where readonly tags are central, so this issue caught my attention.
I am however not able to delete the readonly tags in your jsbin when using Chrome or Edge. Are you seeing this problem in a specific browser? If so, witch one?

**Comment by gl0dt** [comment]
I'm seeing this in Chrome, please note you would need to click on the tag first and then press Backspace to remove it.

**Comment by gl0dt** [comment]
A temporary workaround I came up with is to use the hook to stop it from being removed
```
  hooks: {
    beforeRemoveTag: (tags) => {
      return new Promise<void>((resolve, reject) => {
        isTagRemovable(tags[0].data.type) ? resolve() : reject();
      });
    },
  },
```

**Comment by henkealg** [comment]
@gl0dt  You are right about the click + backspace scenario. Good find. 👍

**Comment by yairEO** [comment]
I will fix this ASAP
