### ISSUE TITLE
Focus issue (Tagify appears by magic after dropdown has been closed)

### ISSUE THREAD

**Issue by wurst-hans** [yairEO/tagify#949]
I'm using Tagify 4.6.0 along with a Bootstrap 5 project. I can't make a demo page right now, but have recorded my screen, maybe this helps. As you can see in video, select a value from dropdown closes the dropdown and I can jump or click in following input fields without any issue.
But, there is an issue, when the document/window loses focus right after selecting a value from dropdown, for example when clicking inside the Chrome developer tools. After that, when I click inside an area where the dropdown has been shown before, it is displayed again (even when I click inside the input below the Tagify object). The DOM element for dropdown is removed correctly after closing dropdown, so I can't explain the behavior. Seems spooky. Is this a known issue?

https://user-images.githubusercontent.com/56444979/143293646-24c3799e-3d6f-45d8-a554-d48d1ef6d1cf.mp4

**Comment by wurst-hans** [comment]
I've tried to listen to some JS events, I've tried to debug it a bit, by listening to Tagify events. What I can see when the issue occurs, is that the event `dropdown:show` is triggered right after `blur` has been triggered. Maybe it's possible to stop `dropdown:show` event when `blur` has been fired or when there is no focus'ed `tagify__input` element?

**Comment by yairEO** [comment]
what does it matter when does the `dropdown:show` fires? 
Did you listen to this event and ran some code as a callback?

**Comment by wurst-hans** [comment]
It's a behavior similar to your own example/docs page https://yaireo.github.io/tagify/
Let's take third example ("Text Input" => "Same Using Custom Suggestions").

1st issue: Open Chrome Developer Tools (F12), then click inside the input to open dropdown. Right after that, click somewhere inside the developer tools to revoke focus - the dropdown will disappear. Now, when you click anywhere on your page except the area where the dropdown has been shown, the dropdown will re-appear and will hide only, after doing some clicks elsewhere on that page.

2nd issue: Again, click inside the input I've mentioned so that dropdown will be shown. Right after that, click inside the input below (next example on your page) - the dropdown will be hidden. Now, when you click anywhere on the page between these two input fields, the dropdown from input above will re-appear.

I think that's a bit strange, i.e. the issue when the focus has been lost due to clicking outside the browser window.

**Comment by yairEO** [comment]
@wurst-hans - thank you for the clear description of the problem! I will fix this
