### ISSUE TITLE
Display tags as readonly only when property is explicitly set to true

### ISSUE THREAD

**Issue by henkealg** [yairEO/tagify#950]
First of all, this is an awesome project. Thanks to @yairEO and all contributors for the job so far. 🤘 

We are using Tagify where the whitelist are fetched from the server on init.
The backend model for the whitelist tags are strongly typed, with the consequence that the readonly property for each tag are always present as a boolean.

Using version 4.9.1, tags become readonly if the readonly property is present in for the tag, regardless value. 
So in the example `[{"id": 1, "value": "TAG 1", "readonly": false}, {"id": "2", "value": "TAG 2", "readonly": true}]` both tags will display as readonly.

We have solved this issue by adding a more explicit condition to the source.
For 4.9.1 the following have been added to line 3063 in /dist/tagify.js:
`if (tagData.readonly != true) delete tagData.readonly; // only handle tag as readonly if attribute have been set explicitly to true or 1`

Demo: https://jsbin.com/mulaxasaqe/edit?html,js,output

My hope is that this fix can be added this way or another in a future release.

**Comment by yairEO** [comment]
Hi, I will investigate and fix, thanks for reporting!
