### ISSUE TITLE
Underlying input value in add callback

### ISSUE THREAD

**Issue by sashadorval** [yairEO/tagify#951]
Hello,

When the add callback is triggered, I've noticed that `e.detail.tagify.value` holds all tags including the one just added. However, if I check the value of the underlying input in the add callback, the JSON does not yet contain the tag just added.

Is this functionality intentional or just an oversight?

Thank you,

**Comment by yairEO** [comment]
The callback is called because the field is actually updated. I will change the lines order:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1167
