### ISSUE TITLE
Looking for advice on two issues

### ISSUE THREAD

**Issue by choff5507** [yairEO/tagify#953]
Hi, 
I am looking for some advice on two different issues I am having with Tagify. 

1. I have an input field I am using Tagify in. There is no "submit" button for it. Instead I simply wish to submit the field when I hit "Enter". I am using a mixed field so the issue is as I hit "Enter" to confirm my tag selection it also submits and I have not found a way to prevent this. 

I tried this method here:

```
function onTagifyKeyDown(e){
  
  if( e.detail.originalEvent.key === 'Enter' &&         // "enter" key pressed
      !tagify.state.inputText &&  // assuming user is not in the middle oy adding a tag
      !tagify.state.editing       // user not editing a tag
    ){
      console.log('Enter key detected!');
    //console.log(tagify.getTagElms())
    setTimeout(() => formElm.requestSubmit(),1000);  // put some buffer to make sure tagify has done with whatever, to be on the safe-side
  }

}
```
I cannot get this to work for me.

2. The second issue is that when I apply Tagify to my input element it turns what is otherwise a single line field into multi-line and has the added effect of allowing me to drop down far enough to where I can actually type outside of the field itself. The field is fine until I apply Tagify to it. 

If someone could give me some advice on either of these issues Id greatly appreciate it!

**Comment by yairEO** [comment]
1. please use Stackoverflow as support
2. tag your question with `Tagify`
3. I **HIGHLY** suggest you to show a complete working demo (jsbin if possible)
