### ISSUE TITLE
Issue with back press in mobile browser - Mix mode

### ISSUE THREAD

**Issue by ankit08anand** [yairEO/tagify#954]
Hi @yairEO , 

I am facing issue with back press in all mobile browser for "Mix" mode. 
This issue can also be observe in Tagify demo for "Mix" mode. 

Please help me to resolve this issue, I am using Tagify in my project, which is awesome, but only due to back press issue in mobile browser, I am stuck :(

Please check attachment. https://drive.google.com/file/d/1ASWViA6QmFDBtFQhxBFRmlthwt7G4eIQ/view?usp=sharing

Thanks in advance

**Comment by gaetangr** [comment]
Hello @ankit08anand, 

I have tried using Safari (for mobile) and Google Chrome (for mobile) and was able to use the back button.

It appears that you are trying to delete a **readonly tag**, as per the documentation : 

> Note that "homer simpson" tag is set to readonly in this example. If tried to select all text and delete everything, readonly tags will remain.
