### ISSUE TITLE
Read-only tags displayed as invalid if present in blacklist

### ISSUE THREAD

**Issue by henkealg** [yairEO/tagify#956]
Thank you @yairEO  for making the change suggested in #950.

We have a use case where we have been forced to make minor source adjustments, and I just want to make you aware of this so you can consider changing the current state. Using Tagify 4.9.2

We are presenting Tagify with a whitelist containing the user's own private tags, of witch none are read-only.
Some objects where tagging is enabled might have one or more global tags added to it. These tags are displayed as read-only to the user. To prevent the user from creating a tag with the same name as an existing global tag we are presenting all global tags to Tagify in a blacklist.

This approach works great. The only issue is that added global (read-only) tags are presented as invalid / "not allowed" if they are present in the blacklist as well as among the added tags.

We have fixed this issue by ignoring most some of the tag validation for read-only tags, with a setting toggling this validation for compatibility.

tagify.js @ line 270: `validateReadonlyTags: true, // validate tags marked as readonly`

tagify.js @ line 2791, after the tag duplicate validation:
`if (!_s.validateReadonlyTags && typeof (tagData.readonly) != undefined && tagData.readonly) return true;`

Working demo available here: https://jsbin.com/rosiqoxeci/1/edit?html,js,output

Best regards,

**Comment by yairEO** [comment]
then remove them from the blacklist...
