### ISSUE TITLE
how can I get lastest tag on invalid, add event?

### ISSUE THREAD

**Issue by DMD-Soliton** [yairEO/tagify#957]
Hi tagify team!
Problem: I can't get lastest tag element on invalid event (using jquery), but can do it after create a new tag (it can be valid or invalid)
I need to get latest tag (both valid and invalid tag) to edit title of this tag, can you help me?
https://jsbin.com/hudasiligu/1/edit?html,js,output
Thank you!

**Comment by yairEO** [comment]
Hi, there is no team, just me :)

You can simply see what's available by doing this:

```js
tagify.on('invalid', function() {
       console.log(arguments)
})
```

These are the stuff you are interesting in:

![image](https://user-images.githubusercontent.com/845031/145372789-72a24133-8fa9-4db9-be4f-cfe7387861a2.png)

So you can simply do:
```js
tagify.on('invalid', e => {
       console.log(e.detail.tag)  // the tag element which was just entered and is invalid
})
```

What are you really trying to do?

**Comment by yairEO** [comment]
you should ask such questions in stackoverflow, as here is more for bug reports and feature-requests and less on general support...
