### ISSUE TITLE
Keyboard stops working after removing all tags in select mode

### ISSUE THREAD

**Issue by zoaked** [yairEO/tagify#958]
**Description:**
Users cannot enter text in select mode after tags have been programmatically cleared by calling `removeAllTags()`. (chrome and firefox) In firefox (94.0.2) the dropdown position also moves up to cover most of the text box.

**Analysis:**
It seems to have something to do with when `enforceWhitelist` is true.

**Workaround:**
Things are fine when calling `removeTags()`. Since select mode only allows one tag to be selected, this appears to accomplish the same thing.

**Demo:**
https://jsbin.com/sefeguguwu/2/edit?html,js,output

**Comment by zoaked** [comment]
@yairEO - thanks for getting a patch pushed out for this!  I have tested it out and while the originally reported scenario is fixed, now the issue seems to have flipped.  Users cannot enter text after tags have been cleared by calling `removeTags()` or clicking on the `X` button.

Demo:
https://jsbin.com/wuguxopowa/1/edit?html,js,output

**Comment by yairEO** [comment]
I see it only happens of the Tagify field already has a value which is then changed & cleared
