### ISSUE TITLE
Long sentence representation

### ISSUE THREAD

**Issue by bacloud14** [yairEO/tagify#959]
It would be great to have the same style but that could --backspace (with justified content). I think it would be visually OK. 

```
this is
a relat-
ly long
text....
```

Never seen before, probably a bad taste ?

Little context:
I have hundreds of tags, some are sentences of up to 6-7 words. 

Thanks a lot yairEO

**Comment by yairEO** [comment]
There is nothing to request from me here, it's you as the author of your own code, who has the power over the your own CSS and is free to style tags in any way you wish

**Comment by bacloud14** [comment]
Thank you @yairEO . I will try that 😃

**Comment by yairEO** [comment]
You hereby have my blessing to style your code

**Comment by bacloud14** [comment]
It has the same behaviour on demo, when increasing `tag-pad`
