### ISSUE TITLE
Tagify: Synchronize whitelist for multiple instances in plain Javascript

### ISSUE THREAD

**Issue by scakirExtenio** [yairEO/tagify#960]
Hello everyone, 
I am having some difficulties at implementing a synchronized whitelist for n instances of tagify. In the function initPlugins you can see the method updateWhitelist(p,p,p) which is called if an add event is triggered. If updateWhitelist is called, it just replaces the tagify whitelist and suggestedListItems with the new whitelist(variable changedWhitelist). 

Here: Tagify instance structure
![Screenshot at 2021-12-13 12-02-01](https://user-images.githubusercontent.com/23379607/145978310-34af8a4c-139d-441a-bc7d-1bd2aa62333e.png)

After the add Event tagify doesn't show the added element in the suggestion.  Is it possible to reinitialize tagify instances without reloading the page or is there a smooth solution for this problem.

Best regards Extenio!

```

let changedWhitelist = [];

function initPlugins(instance) {
  let imgCount = instance.DictPathing.get('imgCount'); // Counts how many image exists so i can check if the tagify instance is the same as the image count
  document.querySelectorAll('.tag_input').forEach(function(tagInput) {
    if (!tagInput.classList.contains('tagify')) {  // Only create an instance if an image has not been tagified
      currentTagify = new Tagify(tagInput, {
        whitelist: changedWhitelist ,
        // ... other configs
      });

      tagInput.dataset.tagified = true;
      tagifyArr.push(currentTagify); // Pushes every instance to an Array
        currentTagify.on('add', function(event) {
          if (changedWhitelist.indexOf(event.detail.data.value) === -1) {
            changedWhitelist.push(event.detail.data.value);
            updateWhitelist(tagifyArr, imgCount, changedWhitelist );
          }
        });
    }
  });
}

// tagifyArr is an array of tagify instances
function updateWhitelist(tagifyArr, imgCount, changedWhitelist ) {
  changedWhitelist = changedWhitelist.filter(function(item, pos) {
    return changedWhitelist.indexOf(item) == pos;
  });

  if (changedWhitelist .length !== 0) { //Check if empty
    tagifyArr.length = imgCount; // set the tagifyArr length to the same amount as the imgCount somehow i have empty tagifyInstance.
    if (imgCount === tagifyArr.length) {
      for (let i = 0; i < tagifyArr.length; i++) {
        // I'm updating each instance with the new whitelist
        tagifyArr[i].suggestedListItems = changedWhitelist ; 
        tagifyArr[i].whitelist = changedWhitelist ;
      }
    }
  }
}
```

**Comment by yairEO** [comment]
Please create a simple demo page, as instructed in the "issue template" (which you've deleted when creating this issue) so I could assist. 

Help me help you

**Comment by scakirExtenio** [comment]
Thank you for your help,
I just found the solution, at the FAQ: 
https://github.com/yairEO/tagify/blob/master/README.md#faq
It's written that using tagify.settings.whitelist is wrong, but it worked out for me.
I think its because i m changing one instance instead of all instance of tagify.

Best regards Extenio
