### ISSUE TITLE
 select top element dropdown on ke press

### ISSUE THREAD

**Issue by one2gov** [yairEO/tagify#966]
Trying to select the top dropdown element on keypress. But not sure how to trigger the dropdown element selection.

```
$(document).on("keydown", ".tagify", function (e) {
    if (e.which == 13) {
        $('[tagifysuggestionidx~="0"]').trigger( "select" )
    }
});
```

**Comment by yairEO** [comment]
the dropdown already supports keyboard: `Arrow down` to move and `Enter` to select
