### ISSUE TITLE
Placeholder shown outside of the input field

### ISSUE THREAD

**Issue by vkirienko** [yairEO/tagify#968]
Hi,

I noticed that sometimes placeholder can be shown outside of the input field. When I reduce window size further it eventually jumps to the new line under last tag.

![image](https://user-images.githubusercontent.com/12551258/150527927-19d15c58-ac3c-488f-80ff-684b7d080dc8.png)

**Comment by yairEO** [comment]
Duplicate of https://github.com/yairEO/tagify/issues/675
