### ISSUE TITLE
How to prevent removeAllTags() to trigger change event

### ISSUE THREAD

**Issue by lambda-science** [yairEO/tagify#970]
Hello, sorry for creating this issue I need help with a trivial issue that I spent at least 2 hours without finding a solution as I'm really bad in JS.

So some context:
Basically I have a list of patients (with JsTree) that I can select. When I select one, I want to populate an input tag field with its data. So I remove all tags in the input field with removeAllTags(); (of the previous selected patient) and then populate it with addTags();.
The issue is that I have a function that save the modification on every change of the tag-list with the .change event to dynamically save as the user is typing.

Everything works fine when switching patients, however when I click twice on the same node, removeAllTags triggers the .change and simply delete all tags (because now that it removed all tags, it triggered change event and `data.node.data.correlates_with` is empty).

**So my question is: how can I make it so removeAllTags(); doesn't trigger the .change event ?**
Am I stupid and doing this the wrong way ? **Is there a Tagify function to simply replace the whole input with another tag-list instead of removing and adding (two step).**

Here is some of the code to explain the situation:
```javascript
var input7 = document.querySelector("input[id=correlates_with]");
var input7_tag = new Tagify(input7);

$("#jstree").on("select_node.jstree", function (e, data) {
  input7_tag.removeAllTags();
  input7_tag.addTags(data.node.data.correlates_with);

$("textarea[id=correlates_with]").change(function () {
  update_node_data(); // Another function that save the new value to the "node" or "patient" selected
});
```

Thanks a lot for spending time reading this !

**Comment by yairEO** [comment]
If you want to only allow selecting one-at-a-time then why not use the built-in `mode: 'select'` setting?

See this demo: https://yaireo.github.io/tagify/#section-mode-select

**Comment by lambda-science** [comment]
Re-opening for a small question, is the same logic availiable for addTags ?
```javascript
  input7_tag.removeAllTags({ withoutChangeEvent: true });
  input7_tag.addTags(data.node.data.correlates_with, {
    withoutChangeEvent: true,
  });
```
still seem's to trigger the change event ! But I guess maybe it's not the right way pass kwargs in JS ?
Alors for your question:
> BTW - If you want to only allow selecting one-at-a-time then why not use the built-in mode: 'select' setting?
I am using multiple tag per input, so I cannot use the select setting

**Comment by yairEO** [comment]
`addTags` does not support such a setting.

I think the best approach will be to un-register the `change` event listener just before you are doing your operations
and then re-register it, something like this:

```js
var input7 = document.querySelector("input[id=correlates_with]")
var input7_tag = new Tagify(input7)
var $correlates_with = $("textarea[id=correlates_with]")

$("#jstree").on("select_node.jstree", function (e, data) {
  $correlates_with.off('change', onCorrelatesWithChange)

  input7_tag.removeAllTags({ withoutChangeEvent: true });  // technically no need for "withoutChangeEvent" anymore
  input7_tag.addTags(data.node.data.correlates_with);

  $correlates_with.on('change', onCorrelatesWithChange)
}

// bind "change" event by default
$correlates_with.on('change', onCorrelatesWithChange)

function onCorrelatesWithChange() {
  update_node_data(); // Another function that save the new value to the "node" or "patient" selected
};
```

**Comment by lambda-science** [comment]
Thanks for the detailled answer ! I'll check it and let you know, if it doesn't work don't worry I'll find a workaround ! (Or just keep a "save" button instead of listening to the "change" event as it was before !)

**Comment by yairEO** [comment]
Just released a fix for #925 so the first solution should work for you

**Comment by lambda-science** [comment]
Hey @yairEO 

I tested your solution, and I have to say that I'm pretty impressed, 
```javascript
input7_tag.loadOriginalValues(data.node.data.correlates_with)
``` 
worked perfectly ! It dynamically updates the input field with the node that is selected !
Simple one line solution to a problem that I spent hours on !

Thanks a lot

**Comment by jjxtra** [comment]
removeAllTags doesn't persist to storage if id is set on options. How to fix/workaround?

**Comment by yairEO** [comment]
@jjxtra - please provide me with a basic jsbin demo
