### ISSUE TITLE
Unable to edit tags when they reached to maxTags

### ISSUE THREAD

**Issue by maheee** [yairEO/tagify#972]
## Prerequisites

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/dayuserawo/edit?html,js,output

### Source
```    <input name="basic" value="">
    <script>
    var input = document.querySelector('input[name=basic]');
    new Tagify(input, {
	    "editTags": { "clicks": 2 },
		"whitelist": [ "Alpha", "Beta", "Gamma", "Delta" ],
		"dropdown": { "enabled": 0, "maxItems": 12 },
		"maxTags": 1
	})
    </script>
```

### Explanation

- **What is the expected behavior?**
   Double clicking starts renaming and pressing "Enter" should finish it. 

- **What is happening instead?**
  When "maxTags" is set to 1, I can't exit the renaming and the whole component is left in a weird state.
  ![tagify](https://user-images.githubusercontent.com/3494278/151535725-728b8182-ac1b-4ac9-9b68-4391e1a7c513.gif)

- **What error message are you getting?**
  none

**Comment by yairEO** [comment]
Why setting `maxTags` to 1 and not using `mode : "select"`?

https://yaireo.github.io/tagify/#section-mode-select

**Comment by maheee** [comment]
Hi, thanks, this might work in this specific case.

But it looks like the bug exists whenever "maxTags" is set, not only with 1.

![image](https://user-images.githubusercontent.com/3494278/151541281-6e90c272-f149-46a3-8bc8-e7d5bb4bd8f3.png)

**Comment by yairEO** [comment]
I've renamed the title of this bug and will fix it, thanks for reporting!
