### ISSUE TITLE
Dynamically creating new tagify dropdowns when a user presses a button.

### ISSUE THREAD

**Issue by MonkeeMan1** [yairEO/tagify#975]
Hey, Tagify is great. However im having a bit of difficulty dynamically creating new tagify dropdowns when a user clicks a button. This is because if a tagify dropdown with the same class has already been made, tagify doesn't create the new dropdown. 

Is there any examples on how to create dynamically geneated tagify dropdowns?

**Comment by yairEO** [comment]
There are no examples. [It's because of this check](https://github.com/yairEO/tagify/blob/master/src/parts/dropdown.js#L190)

I don't understand the scenario, please provide a working demo as asked so in the *issue template* (which you've deleted)

**Comment by MonkeeMan1** [comment]
> There are no examples. [It's because of this check](https://github.com/yairEO/tagify/blob/master/src/parts/dropdown.js#L190)
> 
> I don't understand the scenario, please provide a working demo as asked so in the _issue template_ (which you've deleted)

No worries I've figured it out, thanks. But I didn't delete anything. As seen in the gif below nothing comes up.

https://gyazo.com/7a8a3796909464f9d793abfa54479338

**Comment by yairEO** [comment]
Ha I see. it's the *"help with something"* button :) I forgot to add the guidelines there.

Happy it worked out for you!
