### ISSUE TITLE
Can I save input#value just for tags values

### ISSUE THREAD

**Issue by bacloud22** [yairEO/tagify#976]
I don't want to rely on custom server validation for `tags`. I found that tags input values are something like :

`[{"value":"Bird Supplies","style":"--tag-bg:#72a78e"}]`

where in client side, tagify is initiated like the following:

````js
export function newTagify (tagified, input, tags, maxTags = 3) {
  if (tagified) {
    tagified.destroy()
  }
  tagified = new Tagify(input, {
    // limit text size to 35
    pattern: new RegExp(`^.{0,${TAG_SIZE}}$`),
    delimiters: ',| ',
    keepInvalidTags: false,
    editTags: {
      clicks: 1, // single click to edit a tag
      keepInvalid: true // if after editing, tag is invalid, auto-revert
    },
    maxTags,
    whitelist: tags,
    transformTag: transformTag,
    backspace: 'edit',
    placeholder: 'Type something',
    dropdown: {
      enabled: 1,
      fuzzySearch: true,
      position: 'text',
      caseSensitive: true
    },
    templates: {
      dropdownItemNoMatch: function (data) {
        return `No suggestion found for: ${data.value}`
      }
    }
  })
  return tagified
}
```
Ideally, I want just `["Bird Supplies", "blabla"]`

Thanks a lot !

**Comment by yairEO** [comment]
what does it mean *"Can I save input#value just for tags value"?*

Have you looked at README of this project? I'm certain one of the examples there will solve your issue

**Comment by bacloud22** [comment]
Sorry for the ambiguous expression. I meant the value of an input html tag. As for now I could find a way. I will check more

**Comment by bacloud22** [comment]
Indeed. Sorry for this

**Comment by yairEO** [comment]
What do you mean *"indeed"*?

**Comment by bacloud22** [comment]
The fact that is mentioned in README, in fact I was sure it is not mentioned on the site. 
`originalInputValueFormat`
Thanks!!!

**Comment by yairEO** [comment]
Thank you :) happy it helps you
