### ISSUE TITLE
Cannot disable dropdown

### ISSUE THREAD

**Issue by jamesbebbington** [yairEO/tagify#978]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
Given the following config:

```html
<input name='tags' placeholder='write some tags' value='css, html'>    
```

```js
var inputElm = document.querySelector('input[name=tags]');


// initialize Tagify on the above input node reference
var tagify = new Tagify(inputElm, {
  
    whitelist: ['c++', 'css', 'html', 'java', 'javascript'],
    autoComplete: {
        enabled: true,
        rightKey: true
    },
    dropdown: {
        enabled: false // Dropdown still displayed
    }
})
```

https://codepen.io/typer78/pen/XWzjZvY
<img width="738" alt="Screenshot 2022-02-04 at 16 53 50" src="https://user-images.githubusercontent.com/5934/152569755-c86bf54e-191c-498a-b79b-1caad4123c2f.png">

### Explanation

- **What is the expected behavior?**

I would like to configure Tagify to only show inline autocomplete suggestions but never the dropdown list. The README states that setting:

> `dropdown.enabled` to `false` will not render a suggestions list.

I would expect the component to provide an inline autocomplete suggestion when the entered text matches an element from the given `whitelist` and no dropdown to be displayed.

- **What is happening instead?**
The dropdown is displayed even though `dropdown.enabled` is set to `false`.

- **What error message are you getting?**
No error message.

**Comment by dumbasPL** [comment]
NOTE: this change breaks the previously working but technically wrong
```js
enabled: true
```

found out the hard way.
