### ISSUE TITLE
Input cursors not in the middle of the input field in Firefox

### ISSUE THREAD

**Issue by Tagirijus** [yairEO/tagify#979]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsbin.com/jekuqap/11/edit?html,js,output

***React*** issue template:
Happens here in this original Reacht template as well:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- I expect the input cursor to be in line with the input box

- Instead the cursor is slightly above and not in the middle of the input field

- Might be error messages:

```
onmozfullscreenchange is deprecated. [tagify:8:30149](https://unpkg.com/@yaireo/tagify)
onmozfullscreenerror is deprecated. [tagify:8:30149](https://unpkg.com/@yaireo/tagify)
```

Also here is a screenshot:

![tagify Firefox Style Bug](https://i.imgur.com/8mQOmN8.png)

Hope I filled out everything correct here. Also: I barely noticed this bug, since I am using Chrome. But a friend told me some other issue which happened, which seems solved, after I updated tagify to the latest version ... yet still I have this issue suddenly _(also this issue was there in earlier versions, by the way)_.

Let me know if you need any more information and thanks for your effort! (=

**Comment by Tagirijus** [comment]
Well, sorry for opening. It might be an issue with an older version of Firefox !! ... I forgot about this possibility. Stil, trying to update Firefox here and coming back to this issue ASAP. Sorry for any inconvenience so far!

**Comment by Tagirijus** [comment]
Sooooorry. Newest version of Firefox does not have this issue anymore. Wasn't your fault. (=

**Comment by yairEO** [comment]
it's called "caret" nor "cursor" :) 

It must have been a very old version which you've tested it on if it is looking like this..

**Comment by Tagirijus** [comment]
Ah thank you for clarifying. I am always happy to learn something new, hehe.

It was Firefox v76 or so ... so yeah, quite old, haha. Thanks for your reply after all! (=
