### ISSUE TITLE
AJAX and dropdown.show(whitelist_terms); not working properly.

### ISSUE THREAD

**Issue by lambda-science** [yairEO/tagify#980]
Hello, 

It's me again ! 

## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

Here is my demo page:
https://jsbin.com/ximixihoma/1/edit?html,js,output

### Explanation

- **What is the expected behavior?**
After the AJAX request is completed, dropdown menu should automatically show without pressing any key.
I have used the example from the GitHub Repo here: https://github.com/yairEO/tagify#ajax-whitelist and I simply changed the URL and the processing of the JSON.
- **What is happening instead?**
Dropdown menu doesn't show, we have to press bottom arrow key or click again in the field.
- **What error message are you getting?**
Also, the browser spam with an error:
`Uncaught (in promise) DOMException: The operation was aborted.`
while typing. Would it be possible to add delay before request in case of the user typing more letters ?

Thanks and have a nice day !
Hope to find help :)

**Comment by yairEO** [comment]
Hi I will check. currently `jsbin.com` seems to be down... first time ever I see it down

**Comment by lambda-science** [comment]
> Hi I will check. Currently `jsbin.com` seems to be down... first time ever I see it down

JSBin works on my side, that's weird ^^

**Comment by lambda-science** [comment]
Just for information, I solved the 
```
Also, the browser spam with an error:
Uncaught (in promise) DOMException: The operation was aborted.
while typing. Would it be possible to add delay before request in case of the user typing more letters ?
```
by adding a `SetTimeout` to the `onInput(e){}` function such as:
```js
var delayTimer;
function onInput(e) {
  clearTimeout(delayTimer);
  delayTimer = setTimeout(function () { 
# Ajax Stuff
  }, 700);
}
```

Now the only thing left is understanding why the dropdown menu don't show up after the request completes :)

**Comment by yairEO** [comment]
Here is how to do it: https://jsbin.com/yupiqem/1/edit?html,js,output

You've passed the whole whitelist to the show function, but you are not supposed to pass any argument if all you want is to show it. just call the function without any parameter: `pheno_terms_tag.dropdown.show()`

I've also refactored your code a little bit

**Comment by lambda-science** [comment]
Thanks @yairEO I felt like I tried that but now it is working. In the Github Readme the AJAX example puts value in `dropdown.show(value)`
Are you sure that the JSBin link is working ? It show me the old version.
Anyways thanks for the help ! Have a nice day
