### ISSUE TITLE
Add/Remove tag with jQuery AJAX

### ISSUE THREAD

**Issue by PeterPan73** [yairEO/tagify#985]
First of all, I want to congratulate you on your great work. Well done!

For several days I have been trying to add / remove a tag with jQuery AJAX, but without success.
What I'm trying to do is after I select a tag from the drop-down list, add it with the addRemoveTag function to display a load icon.
If successful (true) the loading icon is hidden, if unsuccessful (false) the tag is removed.

By the same logic, if I want to delete the tag in when pressing "x", a loading icon appears and if the addRemoveTag function returns true the tag is removed, if it returns false it remains.

I am running version 4.9.6
Demo https://jsbin.com/pizenuhafi/edit?html,js,output

I would be very grateful if someone could share some help. Thanks.

**Comment by yairEO** [comment]
Hi, sorry about not getting to this, have you managed to resolve your issue?
