### ISSUE TITLE
prevent default keys for bold and italic that currupt tagify

### ISSUE THREAD

**Issue by gpetrov** [yairEO/tagify#986]
during text edit in mixed mode, if the user presses ctrl+b or ctrl+i on a selected text, it gets the bold and italic html tags and that corrupts the tagify output.

Those keys should be disabled by default

**Comment by yairEO** [comment]
why does it *"corrupts the tagify output"?* I
Also here in this textbox I can use those shortcuts

I did an experiment a few years ago to add markdown support but haven't finished it

**Comment by yairEO** [comment]
Hi @gpetrov, is this still important?

**Comment by gpetrov** [comment]
Well it is important - if tagify doesn't support rich text with html codes - then those keys should be disabled as using them causes generation of html codes and those together with the text are stripped at the end
