### ISSUE TITLE
MaxTags Option Does not stop more tags being added

### ISSUE THREAD

**Issue by cjsmith87** [yairEO/tagify#992]
## Prerequisites
I am running the latest version on Angular

### Demo Page
https://codepen.io/vsync/pen/bGpdVOr

### Issue
The setting MaxTags adds a class to the control when it reaches the maximum but I want to be able to stop users selecting and more tags once the max count has been reached. They will then have to remove one of the existing tags before they can enter any more text to search for a tag. I think the control is working as per design, I probably just need to add some extra code

**Comment by yairEO** [comment]
These extra tags you see are not added to the value. They are only added to the component, visually, but they have a red background and a `title` attribute explicitly saying the maximum number of tags has been reached.

This is happening because I've set the `keepInvalidTags: true` setting in this particular demo.

**Comment by cjsmith87** [comment]
Thanks @yairEO, is there anyway to stop the editor allowing you to search for tags once the maximum has been reached? I want the user to have to remove a selected tag before being able to search or add more?

**Comment by yairEO** [comment]
Try setting the `tagify.dropdown.enabled` to `false` once the number of tags has been reached. You can count the number of tags using `tagify.value` when you listen to the `change` event.

```js
var inputElm = document.querySelector;
var maxTags = 3;
var tagify = new Tagify (inputElm, {
	  maxTags,
	  whitelist: [1,2,3],  
});

inputElm.addEventListener('change', onChange)

function onChange(e){
  tagify.settings.dropdown.enabled = tagify.value.length == maxTags ? false : 0
}
```

Haven't checked but this is the general direction I would do it

**Comment by cjsmith87** [comment]
That is great, thank you for all your help. I also want to stop a user typing in the box to search for more tags so I have tried to update the userInput and Placeholder properties but although the properties are updating, they are not affecting the controls behaviour, please see https://codepen.io/cjsmith87/pen/QWOxrjd

**Comment by yairEO** [comment]
You have a class on the Tagify component when maximum number of tags reached, so you can use that to hide the input element within tagify

**Comment by cjsmith87** [comment]
If I add disabled to the original input, it wont let me remove the selected tags? Sorry, I am new to web development and struggling a bit. Would you consider adding this as a feature of tagify for a fee?

**Comment by yairEO** [comment]
Can you create a [minimal demo page](https://jsbin.com/jekuqap/edit?html,js,output) and explain to me again the whole scenario?
