### ISSUE TITLE
Can't style placeholder

### ISSUE THREAD

**Issue by MartinaNemet** [yairEO/tagify#993]
I'm trying to style my placeholder inside of an input tag. I need to change color, font, font-size, line-height and fix the overflow. I tried styling it inside .tagify:.placeholder{}, .tagify.tagify--noTags{ --placeholder-font/line-height...} but none of those work. I'm not even sure if i can style it the way i want so please tell me if i can and if so, how can i do it.
Thank you :)

**Comment by yairEO** [comment]
of course you can style it, just like I did in the [Tagify SCSS file](https://github.com/yairEO/tagify/blob/master/src/tagify.scss).

The CSS selector is `.tagify__input::before`
