### ISSUE TITLE
Add delay before check with ajax whitelist

### ISSUE THREAD

**Issue by tenzap** [yairEO/tagify#994]
I use tagify with a whitelist filled dynamically by a ajax call (inspired by https://github.com/yairEO/tagify#ajax-whitelist)

However, I don't want to have a call as soon as the user starts typing. That would create a lot of immediate calls as soon as a letter is type.

For example, it would be nice to have a delay before actually doing the http request.

Some other tools like jquery-ui autocomplete or tokeninput permit to set a delay.
For example 300ms

Could it be possible to add such an option?

**Comment by yairEO** [comment]
It's up to you as the developer to add whatever solution you see fit on top of your own code which calls the server (on `input` event)

Google `javascript debounce`

I don't want Tagify to do everything completely out-of-the-box because these types of things are at the hands of the developer

**Comment by tenzap** [comment]
ok thanks for the tip :)
