### ISSUE TITLE
Typing in input field stolen by hotkey plugin

### ISSUE THREAD

**Issue by tenzap** [yairEO/tagify#995]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I'm trying to migrate to tagify to replace an older similar tool.

I have a page that has some javascript that can intercept some keyboard shortcuts. (it's a jquery hotkey plugin).

On that page I added an input field with tagify on it.

I use this https://github.com/yairEO/tagify#ajax-whitelist to fill the whitelist, so there is a call to `tagify.on('input', onInput)`. I slightly modified it to use the jquery way to do a `$.post` query.

However, when I'm in the field (has focus), and as soon as I type a letter that could be catched by the hotkey script, it is actually catched by the hotkey script and it is not seen by tagify as typing in the field, thus the "on input" is not triggered.

There is no such problem when I type in another field that is not managed by tagify.

**Comment by tenzap** [comment]
Maybe this happens because Tagify uses a `<tags>` tag, and not a `<input>` tag.

**Comment by yairEO** [comment]
> *...as soon as I type a letter that could be catched by the hotkey script, it is actually catched by the hotkey script ...*

I did not understand this sentence..

**Comment by tenzap** [comment]
Let's say I have:
```js
$(document).on('keydown', null, 'm', function() {
	alert("m keydown");
});

var tagify = new Tagify(....);
tagify.on('input', tagifyOnInput);

function tagifyOnInput(e) {
	alert("tagifyOnInput");
}

```

If I type "m" into the tagified input, It will display "m keydown" instead of "tagifyOnInput".

**Comment by tenzap** [comment]
I found that the hotkey plugin that the project uses actually filters out keypress listening on input tags like select, textarea, input tags of type text|password|search|tel|url|email|number). So I will add a exception for tagify. What test do you suggest to identify the tagify input field without error?

For now I'm using this statement
```js
if (obj.classList.contains("tagify__input")) { ... }
```
Is this future-safe or which test should I perform?

**Comment by yairEO** [comment]
This should be pretty safe

**Comment by tenzap** [comment]
Ok, thanks.

Just as a side question:

How to distinguish between 2 tagified "input" tags in the DOM? Is it possible to reference them by an id? I haven't found any id attribute on the tagified elements.
