### ISSUE TITLE
License and file header

### ISSUE THREAD

**Issue by tenzap** [yairEO/tagify#996]
Tagify is licensed under MIT license.

However I noticed that in the headers of the files, for example tagify.min.js there is no reference to MIT license but the text "do no sell this code".

This seems discordant to me. Could you please clarify?

**Comment by yairEO** [comment]
I don't know what `discordant` is, but this project has a [license file](https://github.com/yairEO/tagify/blob/master/LICENSE)

I've added *"do no sell this code"* to the license, to be CLEAR. 

**No selling of Tagify, is allowed, no matter the amount of re-branding & code modifications.**

Are you asking because you want to make profit of Tagify in some way?

**Comment by tenzap** [comment]
I'm asking because I would like to use it in another project (kalkun) and was wondering if that sort of notice _do no sell this code_ would actually prevent inclusion into Debian (either through kalkun package which would include it, or through tagify package) or other distributions.

For example I know that the "_The Software shall be used for Good, not Evil_. " note of json license implies this:
→ 
> [This license is considered non-free by Debian, GNU Project, Fedora, Google, Red Hat legal, Free Software Foundation](https://wiki.debian.org/qa.debian.org/jsonevil)

**Comment by yairEO** [comment]
I didn't understand much of what you've said, but are you an open-source contributor wishing to add Tagify to this *kalkun* project, and *kalkun* project is offered for free?

**Comment by tenzap** [comment]
Hopefully it will be more clear this way:

One fact:
- JSON MIT License with _The Software shall be used for Good, not Evil_ addition is considered non free by Debian, GNU Project, Fedora, Google, Red Hat legal, Free Software Foundation (more details here: https://wiki.debian.org/qa.debian.org/jsonevil) → Not usable in Debian and other majo...

One question:
- Tagify MIT License with _do no sell this code_ -> Are these 2 compatible? Will this still be considered free by those same entities?

BTW: [kalkun](https://github.com/kalkun-sms/Kalkun/) is gpl3 licensed...

**Comment by tenzap** [comment]
The [license file](https://github.com/yairEO/tagify/blob/master/LICENSE) says:

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, **and/or sell
copies of the Software**, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

Your header file doesn't mention MIT, neither any license except _do no sell this code_:
```
/**
 * Tagify (v 4.9.8) - tags input component
 * By Yair Even-Or
 * Don't sell this code. (c)
 * https://github.com/yairEO/tagify
 */
```
This in my opinion is contradictory.

I also think the license in the file takes precedence which would mean the license and usability is unclear.

**Comment by yairEO** [comment]
Both are applied together as I see it. my own comment is just an extension to the current license.

I will edit the LICENSE file to include it, so it's clearer.
Why are you saying JSON license all the time? it's in the format of a text and there is nothing "json" about it

**Comment by tenzap** [comment]
Thank you. Could you also clarify the headers of the files? They don't mention MIT at all.

I ended up asking on the [debian-legal mailing list](https://lists.debian.org/debian-legal). I got an [answer](https://lists.debian.org/debian-legal/2022/02/msg00003.html) and it seems your license isn't DFSG compliant (more info [on debian](https://wiki.debian.org/DFSGLicenses) and [wikipedia](https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines) That's unfortunate.

---

> Why are you saying JSON license all the time?

It seems Json is also a package ;)

Cited from the [links I posted above](https://wiki.debian.org/qa.debian.org/jsonevil):
```
JSON package is licenced under a MIT license but with an additional infamous clause:

The Software shall be used for Good, not Evil.

This license is considered non-free by Debian, [GNU Project](http://www.gnu.org/licenses/license-list.html#JSON), [Fedora](http://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses), [Google](http://wonko.com/post/jsmin-isnt-welcome-on-google-code), [Red Hat legal](https://bugzilla.redhat.com/show_bug.cgi?id=455507), [Free Software Foundation](https://www.gnu.org/licenses/license-list.en.html#NonFreeSoftwareLicenses)

The author [Douglas Crockford is well aware](http://en.wikipedia.org/wiki/Douglas_Crockford#.22Good.2C_not_Evil.22) of the harm he's doing but numerous request from different projects and parties could not change his mind.
```

**Comment by yairEO** [comment]
> Thank you. Could you also clarify the headers of the files? They don't mention MIT at all.

anyone who is serious about license will go straight to the GITHUB page and look for the LICENSE file. 
commented headers are not a "must"

**Comment by tenzap** [comment]
From my little experience, when creating a new package for inclusion in Debian one has to check the copyright of all files to fill a debian/copyright file that is very detailed down to file level (the licence & copyright info is at file level if things are not consistent). File level license has precedence over project level license AFAIK. Then, in the process of submitting a new package to official Debian repo some people of Debian team will check everything again. You may see [comment 5 here (at the bottom of the page)](https://mentors.debian.net/package/qt6/) for a package I submitted for review → I was told: `whoever sponsors this should check those files one by one, and so should do any FTP master member...`

Concerning DFSG a fast introduction might be the [DFSG wikipedia page](https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines) I reference above. Then the [DFSG page at debian wiki](https://wiki.debian.org/DFSGLicenses) 

You may also jump in to the conversation on the debian-legal@lists.debian.org mailing list by [participating to the thread I started](https://lists.debian.org/debian-legal/2022/02/msg00003.html). (you don't need to subscribe to the list to post). It is very likely you will get there a rather accurate answer.

**Comment by tenzap** [comment]
Cited from the [followup on debian list](https://lists.debian.org/debian-legal/2022/03/msg00001.html)

> Given the usual disclaimers that I barely speak for myself, let alone anyone else, that I'm not a member of the Debian and my opinion is worth precisely what an anonymous voice on a mailing list says...

> The usual recommendations are to pick a standard OSI compliant license and not customise it. Using a standard license makes life easier for users because they don't have to think about the implications --- everyone already knows what BSD licenses, GPL licenses etc mean. My usual analogy is to suggest thinking about it like an API. https://choosealicense.com/ is a good resource here and gives reasonable advice.

> I'd suggest that if the author is concerned about people using their work commercially, then the author should look at the LGPL: this will make it easy to for users to use the library in another program, but will require that if the user modifies it or base work on it, they have to distribute the modified source.

**Comment by yairEO** [comment]
well, what can I tell you.. I don't want to change Tagify's license because I want to clearly forbid people re-selling it. I have been working super hard on this code and had enough of people selling my open-source stuff online, earning tens of thousands of dollars while I do this for free (willingly).

**Comment by tenzap** [comment]
I understand. Although Tagify is great, for my part I prefer to search & use an alternative.

Please, at least make the LICENSE file and the headers consistent. I think you should probably also remove the **and/or sell copies of the Software part of the license**, what IMO would result in your software _NOT being MIT licensed anymore_.

**Comment by tenzap** [comment]
Some [additional information](https://lists.debian.org/debian-legal/2022/03/msg00002.html) was posted on the mailing list.

**Comment by yairEO** [comment]
Hi @tenzap! 
Have you found a good alternative eventually?

**Comment by tenzap** [comment]
I ended up adapting the component we already used: https://github.com/underovsky/jquery-tagsinput-revisited

**Comment by leonard84** [comment]
@yairEO, I think you should remove the MIT shield from the readme because you clearly intend not to use the MIT license.

In the same vein, you should harmonize the text and remove the section that allows selling the code, as was [mentioned before](https://github.com/yairEO/tagify/issues/996#issuecomment-1054137700).

I also wanted to intent you have with the derivation from the MIT license. Do you just want to prevent someone from taking your code, rebranding it, and selling that, or do you also want to prevent your library from being used as part of a commercial application?

**Comment by yairEO** [comment]
> Do you just want to prevent someone from taking your code, rebranding it, and selling that, or do you also want to prevent your library from being used as part of a commercial application?

The first thing - I don't want people to sell my code as-is or re-branded. 
such a thing happened to me before (with another open-source project of mine) 
and had pissed me off tons.

This component is meant to be used in a part of a (much) larger system and I 
don't care if that system is generating money or not, because that is the common
use case for web components, but I just want to be covered by the law in case I catch
someone else selling my software as the main component of a package or as part of some
components bundle they gathered from the internet and are selling as to be used as components.

I guess you get my point at this

**Comment by leonard84** [comment]
@yairEO would you be amenable to change the line https://github.com/yairEO/tagify/blob/9bd64ed14cb951b27fb23e3bae2bef7f58128ee0/LICENSE#L19

to

`This Software may not be rebranded and sold as a library under any other name other than Tagify or as part of another library.`

**Comment by yairEO** [comment]
why?

**Comment by leonard84** [comment]
Because the current line is overly broad and makes our legal team uncomfortable, and as you stated:

> This component is meant to be used in a part of a (much) larger system and I don't care
if that system is generating money or not

you are fine with it being part of a large application that is being sold. The new text would clarify that distinction.

**Comment by leonard84** [comment]
We already use it in our codebase, just with the last version that still had the unmodified MIT license. Replacing it would require work that could be avoided, even more so since we are happy with this library.
