### ISSUE TITLE
Transpile tagify.min.js

### ISSUE THREAD

**Issue by cybk** [yairEO/tagify#997]
First of all, thanks for you amazing work on this library.

I have a weird problem on an application that has been improved recently, team added tagify and works perfect for new areas, but an old section for the application requires to use a legacy service for print pdfs, this service  cannot be upgrade it because retrocompatibility (weird situation), I see this service fails if it found some ES6 code and, when I add tagify.min to vendor bundle, the arrow key functions that remain on minified version cause service to fail, it is possible to have a transpiled fersion for this file on the npm package?

**Comment by yairEO** [comment]
You are supposed to transpile it yourself.. don't you have a a build system?

https://cube.dev/blog/dependencies-transpilation/
