### ISSUE TITLE
Grammarly is messing with the tag input

### ISSUE THREAD

**Issue by melenaos** [yairEO/tagify#998]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
Sorry, no demo page. It happens to some pages when Grammarly is active.

### Explanation
Grammarly is adding two extra elements after the tag `input`.
This is messing with `appendTag` function, and instead of adding the new tag before the `input` it adds it at the end. After the `input`

![image](https://user-images.githubusercontent.com/7249160/156885961-2a834893-9929-4ca9-a728-e1017f92ceb8.png)
Grammarly adds two extra after `input` that messes with the new tag position.

### Possible solution
I have overridden the `appendTag` to temporary fix the problem in my code with the following code
```
 var DOM = this.tagify.DOM,
        insertBeforeNode = DOM.scope.lastElementChild;
      if (insertBeforeNode !== DOM.input) insertBeforeNode = DOM.scope.querySelector('.tagify__input'); // <==== Add this line
      if (insertBeforeNode === DOM.input) DOM.scope.insertBefore(tagElm, insertBeforeNode);
      else DOM.scope.appendChild(tagElm);
```

**Comment by yairEO** [comment]
Should have started by explaining what is "Grammarly"

**Comment by melenaos** [comment]
I am sorry, it's a spellchecker **browser addon** for any `input` or `textblock` on the internet.

It injects some code to find spelling and grammar errors and it help's you correct them.
It's quite popular among copywriters and foreign users.

This is how it looks on Tagify.
![image](https://user-images.githubusercontent.com/7249160/156891823-b3244952-a54d-4f91-901e-5cc4e5440f4a.png)

**Comment by yairEO** [comment]
> Grammarly adds two extra after input that messes with the new tag position.

Can't you use CSS to hide these added, unwonted, elements

**Comment by melenaos** [comment]
Please check the first post and see two things:
- The DOM. Grammarly is injecting two elements in the Tag element, at the end, after the `span.tagify__input`
- The `appendTag` function. This function is checking if the last element is the `span.tagify__input` and adds the new tag just before that. But in our case, the last elements are not the `span` but some Grammarly's elements. In this case, your `appendTag` function is placing the new tag at the end, after the `span`.

The problem is not aesthetic, it places the new tags at the end keeping the input span at the front.

Instead of
![image](https://user-images.githubusercontent.com/7249160/156917024-112f1401-c1a0-47b7-b5e6-5b92e087247f.png)

We have:
![image](https://user-images.githubusercontent.com/7249160/156916988-a4e902ec-8cce-49f1-9000-d6744f3a2657.png)

**Comment by melenaos** [comment]
My proposal for the solution is this:

```
 var DOM = this.tagify.DOM,
        insertBeforeNode = DOM.scope.querySelector('.tagify__input'); //<==this is the only change
      if (insertBeforeNode === DOM.input) DOM.scope.insertBefore(tagElm, insertBeforeNode);
      else DOM.scope.appendChild(tagElm);
```

To change the way you look for the `span.tagify__input`.

Instead of looking for the last element, you can just use the querySelector and get it using the class name `tagify__input`.

From `DOM.scope.lastElementChild` to `DOM.scope.querySelector('.tagify__input')`

**Comment by yairEO** [comment]
Ha ok, I understand now, I will make the change
